### ISSUE TITLE
[Utils] Uninstall script does not remove include dir

### ISSUE THREAD

**Issue by KernelErr** [WasmEdge/WasmEdge#1003]
After using uninstall script, empty directory `~/.wasmedge/include` were found left.

![image](https://user-images.githubusercontent.com/45716019/149073862-06afb8e5-77a9-4059-bc13-c86b86b9dcdc.png)

I think we should fix this and may add script tests to CI.

**Comment by SAtacker** [comment]
Thanks for this.
