### ISSUE TITLE
[Proposal] WASM Module Linking Proposal

### ISSUE THREAD

**Issue by KernelErr** [WasmEdge/WasmEdge#1007]
Currently, WasmEdge seems does not support the module linking proposal. As a result, section id 14 could not be recognized.

![image](https://user-images.githubusercontent.com/45716019/149268723-b6c657e7-b591-469b-b9c0-15231b80ddf1.png)

**Comment by hydai** [comment]
@q82419 Could you please check this?
Is module linking a proposal that is not supported by WassmEdge? If so, why we can pass the linking test suites in the spec tests.

**Comment by q82419** [comment]
The module linking is supported by WasmEdge but we didn't implement and export in CLI.

**Comment by hydai** [comment]
Reference: https://radu-matei.com/blog/intro-wasm-components/

**Comment by hydai** [comment]
Since the Module Linking Proposal is deprecated and replaced by the Component Model proposal, this is invalid now.
