### ISSUE TITLE
[docs] Add Chinese translation for WasmEdge Book

### ISSUE THREAD

**Issue by alabulei1** [WasmEdge/WasmEdge#1017]
## Motivation

Now we have launched an all-in-one documentation book for the WasmEdge project in English. We still need more languages support for the WasmEdge Book, such as Chinese.

## Details

Translate the [WasmEdge Book](https://wasmedge.org/book/en/) to Chinese

## Appendix

Source file of WasmEdge Book: https://github.com/WasmEdge/WasmEdge/tree/master/docs/book/en

Source file of WasmEdge Book in Chinese : https://github.com/WasmEdge/WasmEdge/tree/master/docs/book/zh

### Dev
JavaScript

- [x] #1101 
- [x] #1102 
- [x] #1110 
- [ ] #1111 
- [x] #1112 
- [x] #1113 
- [ ] #1107 
- [x] #1105 

### Embed

Go
- [x] #1089 
- [x] #1088 
- [x] #1093 
- [x] #1090 
- [x] #1091 
- [x] #1092 

Rust

- [x] #1097 

### Kubernetes

- [x] #1106 
- [x] #1108 
- [x] #1109 
- [x] #1104 
- [x] #1103 
- [x] #1099 
- [x] #1068 
- [x] #1072 
- [x] #1071 
- [x] #1074 
- [x] #1073 
- [x] #1075 
- [x] #1098 
- [x] #1099 
- [x] #1100 

### OS

- [x] #1077 
- [x] #1078 
- [x] #1069 
- [ ] mac.md
- [x] #1070 

### Extend

- [x] #1082 
- [x] #1083 
- [x] #1085 
- [x] build.md
- [x] #1079 
- [x] #1081 

### frameworks

- [x] #1203
- [x] #1204
- [x] #1205
- [x] #1206
- [x] #1207
- [x] #1208
- [x] #1209

**Comment by xzycn** [comment]
@alabulei1 Should you exchange the place of links of "Source file"?

**Comment by alabulei1** [comment]
@xzycn  Thanks for pointing this out. If you want to translate, select one issue you are interested in. https://github.com/WasmEdge/WasmEdge/labels/translation%2Fzh

**Comment by Sukriti-sood** [comment]
@alabulei1  This issue seems to have been resolved. It can be closed now.

**Comment by Sukriti-sood** [comment]
@alabulei1 Please also close isssues #1111 #1097 #1107 , as they are creating confusion for new Contributors.
