### ISSUE TITLE
WasmEdge support for android

### ISSUE THREAD

**Issue by alabulei1** [WasmEdge/WasmEdge#1025]
## Motivation

a lot of edge computing applications are running on the Android platform. We should add WasmEdge support for android.

## Details

No

## Appendix

https://android-developers.googleblog.com/2020/03/run-arm-apps-on-android-emulator.html?m=1

**Comment by hangedfish** [comment]
see https://github.com/WasmEdge/WasmEdge/pull/1044#issue-1111790551

**Comment by hangedfish** [comment]
Android Application Demo, use default Android NDK toolchains. Android Studio runs well.

https://github.com/hangedfish/WasmEdge_AndroidExample

**Comment by chairwa** [comment]
No wasmedgec included in WasmEdge release for Android. I wonder why.

**Comment by hydai** [comment]
> No wasmedgec included in WasmEdge release for Android. I wonder why.

To use ahead-of-time compilation mode, it must have LLVM dependency on the related platform. Currently, we don't port the LLVM framework and aot mechanism on the android platform. That's why we don't support it.

**Comment by chairwa** [comment]
> Currently, we don't port the LLVM framework and aot mechanism on the android platform. 
Thanks for your reply. Do you have plan to support AOT on Android, e.g. v1.0 version.

**Comment by hangedfish** [comment]
> > Currently, we don't port the LLVM framework and aot mechanism on the android platform.
> 
> Thanks for your reply. Do you have plan to support AOT on Android, e.g. v1.0 version.

If you are using Termux terminal in Android, you can install wasmedge via `pkg` command. This wasmedge release included wasmedgec and supports AOT.

https://github.com/termux/termux-packages/pull/9053

**Comment by hydai** [comment]
@hangedfish 
Do we already have AOT support on Android platform? 
https://github.com/WasmEdge/WasmEdge/blob/master/.github/workflows/build.yml#L358-L389
Looks like this is not enabled in the build workflow or release workflow?

**Comment by hangedfish** [comment]
> @hangedfish
> Do we already have AOT support on Android platform?
> https://github.com/WasmEdge/WasmEdge/blob/master/.github/workflows/build.yml#L358-L389
> Looks like this is not enabled in the build workflow or release workflow?

I think `wasmedgec` usually works on the host, while `wasmedge` works on the Android platform.
`wasmedgec` is required as a cross compiler to compile wasm to aarch64 assembly. I'm not sure if `wasmedgec` can do this.

**Comment by chairwa** [comment]
> wasmedgec is required as a cross compiler to compile wasm to aarch64 assembly.

This is key point. 
I use wasmedgec to convert wasm to so on aarch64 linux SBC, and the result so can be run on Android like a charm.
Before I thought linux so cannot be used on Android.
