### ISSUE TITLE
WasmEdge TF lite extension support for android

### ISSUE THREAD

**Issue by alabulei1** [WasmEdge/WasmEdge#1026]
## Motivation

AI inference is one of the most common applications of edge computing. Now the WasmEdge TF lite extension could only be run on X86.

## Details

No.

## Appendix

No.

**Comment by javadoors** [comment]
Where is the code of wasmedge TF Lite extension? I want to learn it.
In addition, I want to know what is the relationship between wasmedge and second state?

**Comment by q82419** [comment]
> Where is the code of wasmedge TF Lite extension? I want to learn it. In addition, I want to know what is the relationship between wasmedge and second state?

The TF and TF-lite extension is in [WasmEdge-Tensorflow repo](https://github.com/second-state/WasmEdge-tensorflow).

It's like the relationship between Firefox and Mozilla.

**Comment by q82419** [comment]
Implemented in WasmEdge-Tensorflow.
