### ISSUE TITLE
[Rust SDK] Support non blocking sockets in Rust

### ISSUE THREAD

**Issue by juntao** [WasmEdge/WasmEdge#1030]
As demonstrated in our QuickJS project, WasmEdge can now support non blocking network I/O. We need to add this feature to the wasmedge-wasi-socket Rust API too.

**Comment by KernelErr** [comment]
I created a PR(https://github.com/second-state/wasmedge_wasi_socket/pull/35) draft to add poll support for `wasmedge-wasi-socket`. However, there is some stuff we should notice.

- Someone just create a WASI network proposal draft: https://github.com/badeend/WASI-Networking. We may keep some focus on it.
- In the WASI snapshot document, `sock_accept` takes a `fd_flag` argument for specifying non-blocking and other features. But our current API does not support it. (https://github.com/WebAssembly/WASI/blob/main/phases/snapshot/docs.md)

As a result, in my PR, `accept`, `read` and `write` will not get `would block` error.

cc: @hydai

**Comment by juntao** [comment]
The WASI standard proposal should be supported by the Rust compiler. We do not want to wait for them -- they have been discussing this for 2+ years now. 

We should focus on creating a Rust SDK our existing host functions that our users can use now. If our host functions have missing features, we could add to them first. 

@L-jasmine Could you have a look?

**Comment by hydai** [comment]
Hi @L-jasmine 
I found that the PR is merged. Is this issue resolved?
