### ISSUE TITLE
unknown option: gas-limit

### ISSUE THREAD

**Issue by bitoceango** [WasmEdge/WasmEdge#1034]
### Current State

when it run the command follow by the wasmedge book
wasmedge --enable-all-statistics --gas-limit 20425 hello.wasm second state

i get an error

![image](https://user-images.githubusercontent.com/38564000/150455416-d34151bf-45db-4164-b8df-a8144dcd12fd.png)

### Expected
![image](https://user-images.githubusercontent.com/38564000/150455136-8bee82e8-9930-45da-90ff-515419cae403.png)

## Environment

my wasmedge version is wasmedge version 0.9.0

- Hardware Architecture: (e.g. x86\_64 or aarch64)
   aarch64
- Operating system: (e.g. Ubuntu 20.04 or CentOS 7.6)
   macOS Monterey 12.1
The following information is optional. Please provide them only if you have built from source.
- C++ Compiler version:
- CMake version:
- CMake flags: (e.g. `-DCMAKE_BUILD_TYPE=Release -DWASMEDGE_BUILD_AOT_RUNTIME=ON`)
- Boost version:

**Comment by q82419** [comment]
This option will be ready in version `0.9.1`.
The WasmEdge `0.9.0` not supports that yet.

**Comment by hydai** [comment]
Reference: 0.9.1 changelog: https://github.com/WasmEdge/WasmEdge/blob/master/Changelog.md#091-unreleased
