### ISSUE TITLE
[Rust] Research API calls used in FVM

### ISSUE THREAD

**Issue by juntao** [WasmEdge/WasmEdge#1035]
The FVM project uses the wasmtime SDK to implement its on-chain VM. 

https://github.com/filecoin-project/ref-fvm

We should investigate which wasmtime Rust SDK APIs it uses, and see how we can use the WasmEdge Rust SDK as a drop-in replacement in their build system. 

More details about the FVM project: https://filecoin.io/blog/posts/introducing-ref-fvm-a-new-fvm-website-and-the-early-builders-program/

**Comment by hydai** [comment]
What's the status of this issue? Do we have any plan for it?

**Comment by juntao** [comment]
I will close this. The plan for FVM has changed.
