### ISSUE TITLE
The target "wasmedge_c_static" cannot link to executable file

### ISSUE THREAD

**Issue by hangedfish** [WasmEdge/WasmEdge#1055]
### Current State

I'm trying to use the WasmEdge static library but getting some errors.

```
[cmake]   CMake Error at CMakeLists.txt:15 (target_link_libraries):
[cmake]   Target "wasmedge_c_static" of type UTILITY may not be linked into another
[cmake]   target.  One may link only to INTERFACE, OBJECT, STATIC or SHARED
[cmake]   libraries, or to executables with the ENABLE_EXPORTS property set.
[cmake] 
[cmake] 
[cmake] -- Configuring incomplete, errors occurred!
```

### Expected

The target `wasmedge_c_static` should be a static library, right? Like `wasmedge_c_shared` is a shared library, but it works fine.

## Environment

- Hardware Architecture: x86_64
- Operating system: Ubuntu 20.04

The following information is optional. Please provide them only if you have built from source.
- C++ Compiler version: Ubuntu clang version 12.0.0-3ubuntu1~20.04.4
- CMake version: 3.22.1
- CMake flags: `--no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_C_COMPILER:FILEPATH=/bin/clang-12 -DCMAKE_CXX_COMPILER:FILEPATH=/bin/clang++-12 -H/home/dev/WorkSpace/WasmEdgeHello -B/home/dev/WorkSpace/WasmEdgeHello/build -G Ninja`
- Boost version: libboost1.71-dev:amd64

## Steps to Reproduce

The WasmEdge source was added to my project as a submodule with the path `vendor/WasmEdge`
My CMakeLists.txt.
```
cmake_minimum_required(VERSION 3.21.0)
project(wasmedge_hello)

set(WASMEDGE_BUILD_TOOLS OFF CACHE BOOL "" FORCE)
set(WASMEDGE_BUILD_AOT_RUNTIME OFF CACHE BOOL "" FORCE)
set(WASMEDGE_BUILD_STATIC_LIB ON CACHE BOOL "" FORCE)
add_subdirectory(vendor/WasmEdge)
include_directories(${WasmEdge_BINARY_DIR}/include/api)

add_executable(
    main
    main.cpp
)

target_link_libraries(
    main
    wasmedge_c_static
)
```

main.cpp
```c++
#include <cstdio>
#include <wasmedge/wasmedge.h>

int main(int argc, const char* argv[]) {
    printf("WasmEdge Version: %s \n", WasmEdge_VersionGet());
    return 0;
}
```

**Comment by hangedfish** [comment]
By the way, if WasmEdge is a submodule of another project, it doesn't work with Ninja in `Release` and `RelWithDebInfo` config.
```
[build] Starting build
[proc] Executing command: /usr/local/bin/cmake --build /home/dev/WorkSpace/WasmEdgeHello/build --config RelWithDebInfo --target all -j 6 --
[build] ninja: error: build.ninja:506: unknown pool name 'link'
[build] 
[build] Build finished with exit code 1
```

**Comment by q82419** [comment]
> By the way, if WasmEdge is a submodule of another project, it doesn't work with Ninja in `Release` and `RelWithDebInfo` config.
> 
> ```
> [build] Starting build
> [proc] Executing command: /usr/local/bin/cmake --build /home/dev/WorkSpace/WasmEdgeHello/build --config RelWithDebInfo --target all -j 6 --
> [build] ninja: error: build.ninja:506: unknown pool name 'link'
> [build] 
> [build] Build finished with exit code 1
> ```

This is a known issue, we haven't fix it yet.
Please use this for workaround:
```
  if (CMAKE_GENERATOR STREQUAL Ninja)
    set(CMAKE_JOB_POOLS "link=2")
    set(CMAKE_JOB_POOL_LINK link)
  endif()
```

**Comment by q82419** [comment]
The static library version is experimental, and may not maintain for a while.
Can you turn on the option `-DWASMEDGE_FORCE_DISABLE_LTO=On` and try again? thanks.
If you have any better solution, please feel free to create a PR :)

**Comment by hangedfish** [comment]
> > By the way, if WasmEdge is a submodule of another project, it doesn't work with Ninja in `Release` and `RelWithDebInfo` config.
> > ```
> > [build] Starting build
> > [proc] Executing command: /usr/local/bin/cmake --build /home/dev/WorkSpace/WasmEdgeHello/build --config RelWithDebInfo --target all -j 6 --
> > [build] ninja: error: build.ninja:506: unknown pool name 'link'
> > [build] 
> > [build] Build finished with exit code 1
> > ```
> 
> This is a known issue, we haven't fix it yet. Please use this for workaround:
> 
> ```
>   if (CMAKE_GENERATOR STREQUAL Ninja)
>     set(CMAKE_JOB_POOLS "link=2")
>     set(CMAKE_JOB_POOL_LINK link)
>   endif()
> ```

Thanks, it works.

**Comment by hangedfish** [comment]
> The static library version is experimental, and may not maintain for a while. Can you turn on the option `-DWASMEDGE_FORCE_DISABLE_LTO=On` and try again? thanks. If you have any better solution, please feel free to create a PR :)

Doesn't works, but the option `-DWASMEDGE_FORCE_DISABLE_LTO=ON` solved another problem I had, which was that it didn't add the link flag `-fuse-ld=gold`, my toolchain only provided `lld` and didn't include `gold`.

**Comment by q82419** [comment]
It seems that we tested the `libwasmedge_c.a` for linking with only linker, but not tested with cmake.

**Comment by hangedfish** [comment]
> It seems that we tested the `libwasmedge_c.a` for linking with only linker, but not tested with cmake.

My [solution](https://github.com/hangedfish/WasmEdge_AndroidExample/blob/5195b6405726b2ee42e2d42ce654fa4908b53482/app/src/main/cpp/CMakeLists.txt)

**Comment by q82419** [comment]
Already refactored and fixed.
