### ISSUE TITLE
feat: Enable OpenVINO backend for WASI-NN

### ISSUE THREAD

**Issue by hydai** [WasmEdge/WasmEdge#1063]
## Motivation

In the previous ticket #343, we already have some `WASI-NN` implementation. However, the backend is using ONNX. In this ticket, we would like to have both ONNX and OpenVINO backend.

Machine Learning is a big topic nowadays. WasmEdge already provides [a set of TensorFlow host functions](https://github.com/second-state/wasmedge_tensorflow_interface) to enable the ML inference in WebAssembly. However, these TensorFlow host functions are defined by us and they are just a Wasm function binding from the [TensorFlow C API](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/c/c_api.h).

Here comes a standard, the [WASI-NN proposal](https://github.com/WebAssembly/wasi-nn) provides a new way to perform neural network inferencing by using a runtime-provided implementation that can leverage host native optimizations, CPU multi-threading, or powerful hardware devices such as GPUs or TPUs.

## Specification

1. Get familiar with WASI-NN proposal.
2. Modify the current WASI-NN implementation for enabling multiple backend support.
3. Take OpenVINO as another WASI-NN backend and create a demo kit that is similar to [Wasmtime](https://bytecodealliance.org/articles/implementing-wasi-nn-in-wasmtime)
4. Create unit tests and integrations tests to verify the `WASI-NN` component.

## Minimum qualifications

To apply this LFX mentorship, there are some minimum qualifications:

1. Experience with C++ programming language.
2. **Finish the challenge #1221**

## Appendix
1. WasmEdge TensorFlow rust SDK: https://github.com/second-state/wasmedge_tensorflow_interface
2. WasmEdge TensorFlow host functions: https://github.com/second-state/WasmEdge-tensorflow
3. TensorFlow C API: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/c/c_api.h
4. WASI-NN proposal: https://github.com/WebAssembly/wasi-nn
5. Implementing-wasi-nn-in-wasmtime: https://bytecodealliance.org/articles/implementing-wasi-nn-in-wasmtime

**Comment by hydai** [comment]
Hi @wangyuan249,

I just updated the Minimum qualifications. If you are interested in this issue, please finish the challenge. It will help you to get familiar with the WasmEdge data structure and how to interact with the WasmEdge.

**Comment by gusye1234** [comment]
Hi @hydai, 
I'm curious, for those who want to apply for this LFX mentorship, is there anything else we can do besides waiting after applying on the mentorship.lfx.linuxfoundation.org website and finishing the challenge?
I would really appreciate it if your could answer😊.

**Comment by q82419** [comment]
Implementation: #1340 #1440 #1461
Unit test: #1446
Docs: #1414
Examples: https://github.com/second-state/WasmEdge-WASINN-examples/pull/1
