### ISSUE TITLE
[Docs] Translate the crun.md to zh

### ISSUE THREAD

**Issue by alabulei1** [WasmEdge/WasmEdge#1068]
### The MD file link you want to translate (must be in English) 

https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/en/src/kubernetes/container/crun.md

### Target language
zh: https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/zh/src/kubernetes/container/crun.md

**Comment by baiyutang** [comment]
please assigne to me.

**Comment by luckyJ-nj** [comment]
Could you pls assign it to me?

**Comment by alabulei1** [comment]
Thank you!

since @luckyJ-nj  is new here, I will assign this issue to him/her.

@baiyutang  Thanks for your contribution again!
