### ISSUE TITLE
[Docs] Translate Linux.md to zh

### ISSUE THREAD

**Issue by MileyFu** [WasmEdge/WasmEdge#1069]
### The MD file link you want to translate (must be in English) 
https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/en/src/os/linux.md
	
### Target language
https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/zh/src/os/linux.md

**Comment by sunnywa** [comment]
@alabulei1 I'd like to translate this page into Chinese!
Could you pls assign it to me?

**Comment by sunnywa** [comment]
您的邮件我已收到。——王琦

**Comment by sunnywa** [comment]
#1191

**Comment by sunnywa** [comment]
@alabulei1 切换了一个pr地址， #1316 https://github.com/WasmEdge/WasmEdge/pull/1316
