### ISSUE TITLE
[Docs] Translate raspberrypi.md to zh

### ISSUE THREAD

**Issue by MileyFu** [WasmEdge/WasmEdge#1070]
### The MD file link you want to translate (must be in English) 
https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/en/src/os/raspberrypi.md

### Target language
https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/zh/src/os/raspberrypi.md

**Comment by zephoon** [comment]
Plz assign this to me, thx.
