### ISSUE TITLE
[Docs] Translate the kubernetes/cri/containerd.md to zh

### ISSUE THREAD

**Issue by alabulei1** [WasmEdge/WasmEdge#1071]
### The MD file link you want to translate (must be in English) 
https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/en/src/kubernetes/cri/containerd.md

### Target language
zh: https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/en/src/kubernetes/cri/containerd.md

**Comment by villanel** [comment]
apply for this.

**Comment by alabulei1** [comment]
> apply for this.

Assigned.  Thank you!
