### ISSUE TITLE
[Docs] Translate the demo/wasi.md to zh

### ISSUE THREAD

**Issue by alabulei1** [WasmEdge/WasmEdge#1074]
### The MD file link you want to translate (must be in English) 
https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/en/src/kubernetes/demo/wasi.md

### Target language
zh: https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/zh/src/kubernetes/demo/wasi.md

**Comment by wangyuan249** [comment]
Hi, I want to translate this part, please assign to me.

**Comment by wangyuan249** [comment]
#1173
