### ISSUE TITLE
[Docs] Translate seL4.md to zh

### ISSUE THREAD

**Issue by MileyFu** [WasmEdge/WasmEdge#1077]
### The MD file link you want to translate (must be in English) 
https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/en/src/os/sel4.md

### Target language
https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/zh/src/os/sel4.md

**Comment by bbcfive** [comment]
pls assign to me~
