### ISSUE TITLE
[Docs] Translate windows.md to zh

### ISSUE THREAD

**Issue by MileyFu** [WasmEdge/WasmEdge#1078]
### The MD file link you want to translate (must be in English) 
https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/en/src/os/windows.md

### Target language
https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/zh/src/os/windows.md

**Comment by sunnywa** [comment]
@alabulei1 I'd like to translate this page into Chinese!
Could you pls assign it to me?

**Comment by CoderfishGzh** [comment]
Plz assign this to me

**Comment by alabulei1** [comment]
@CoderfishGzh  May I ask did you finish the translation?

**Comment by alabulei1** [comment]
Hi, @CoderfishGzh May I ask did you finish the translation?

**Comment by alabulei1** [comment]
@CoderfishGzh It seems that you didn't start the translation, so I reassigned the issue to @meoww-bot

**Comment by sunnywa** [comment]
您的邮件我已收到。——王琦
