### ISSUE TITLE
[Docs] Translate extend/plugin/externref.md to zh

### ISSUE THREAD

**Issue by MileyFu** [WasmEdge/WasmEdge#1079]
### The MD file link you want to translate (must be in English) 
https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/en/src/extend/plugin/externref.md

### Target language
https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/zh/src/extend/plugin/externref.md

**Comment by baiyutang** [comment]
I will translate this.Please assigne to me.

**Comment by laingke** [comment]
Please assigne to me.

**Comment by ruijzhan** [comment]
Please assign this issue to me. @alabulei1

**Comment by alabulei1** [comment]
Thanks all! Since @laingke  is new here, I assigned this issue to him/her.
