### ISSUE TITLE
[Docs] Translate extend/plugin/hostfunction.md to zh

### ISSUE THREAD

**Issue by MileyFu** [WasmEdge/WasmEdge#1081]
### The MD file link you want to translate (must be in English) 
https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/en/src/extend/plugin/hostfunction.md

### Target language
https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/zh/src/extend/plugin/hostfunction.md

**Comment by JieDing** [comment]
plz assign this to me

**Comment by JieDing** [comment]
Jobs done. Waiting for reviewing. 
[docs: add zh-CN translation-hostfunction.md #1169](https://github.com/WasmEdge/WasmEdge/pull/1169)
@alabulei1

**Comment by JieDing** [comment]
#1169
