### ISSUE TITLE
[Docs] Translate extend/build_on_windows.md to zh

### ISSUE THREAD

**Issue by MileyFu** [WasmEdge/WasmEdge#1083]
### The MD file link you want to translate (must be in English) 
https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/en/src/extend/build_on_windows.md

### Target language
https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/zh/src/extend/build_on_windows.md

**Comment by wangbyby** [comment]
plz assign to me.
