### ISSUE TITLE
[Docs] Translate extend/plugin.md to zh

### ISSUE THREAD

**Issue by MileyFu** [WasmEdge/WasmEdge#1085]
### The MD file link you want to translate (must be in English) 
https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/en/src/extend/plugin.md

### Target language
https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/zh/src/extend/plugin.md

**Comment by sunnywa** [comment]
@alabulei1 I'd like to translate this page into Chinese!
Could you pls assign it to me?
