### ISSUE TITLE
Translate embed/c/ref.md to zh 

### ISSUE THREAD

**Issue by MileyFu** [WasmEdge/WasmEdge#1087]
### The MD file link you want to translate (must be in English) 
https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/en/src/embed/c/ref.md

### Target language
https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/zh/src/embed/c/ref.md

**Comment by r-asou** [comment]
Plz assign this to me

**Comment by vanshitaverma** [comment]
Hello, was this issue resolved? The first link in the issue seems broken and I am not able to open it, does this issue still need work? I am looking for documentation issues to contribute to before sending my proposal for Google Season of Docs

**Comment by alabulei1** [comment]
Hi @vanshitaverma , thanks for your interest. However, we will re-organize our docs. This issue doesn't work. I will close it. You can check out https://github.com/WasmEdge/docs/.
