### ISSUE TITLE
[Docs] Translate embed/go/bindgen.md to zh 

### ISSUE THREAD

**Issue by MileyFu** [WasmEdge/WasmEdge#1089]
### The MD file link you want to translate (must be in English) 
https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/en/src/embed/go/bindgen.md

### Target language
https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/zh/src/embed/go/bindgen.md

**Comment by deyuhua** [comment]
please assign to me.
@MileyFu
