### ISSUE TITLE
[Docs] Translate embed/go/function.md to zh

### ISSUE THREAD

**Issue by MileyFu** [WasmEdge/WasmEdge#1090]
### The MD file link you want to translate (must be in English) 
https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/en/src/embed/go/function.md

### Target language
https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/zh/src/embed/go/function.md

**Comment by peterbi** [comment]
Pls assign this to me thx

**Comment by alabulei1** [comment]
Assigned. Thank you!
