### ISSUE TITLE
[Docs] Translate embed/go/memory.md to zh

### ISSUE THREAD

**Issue by MileyFu** [WasmEdge/WasmEdge#1091]
### The MD file link you want to translate (must be in English) 
https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/en/src/embed/go/memory.md

### Target language
https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/zh/src/embed/go/memory.md

**Comment by r-asou** [comment]
Plz assign this to me

**Comment by sunnywa** [comment]
@alabulei1 I'd like to translate this page into Chinese!
Could you pls assign it to me?

**Comment by CoderfishGzh** [comment]
Plz assign this to me
