### ISSUE TITLE
[Docs] Translate embed/go/ref.md to zh

### ISSUE THREAD

**Issue by MileyFu** [WasmEdge/WasmEdge#1092]
### The MD file link you want to translate (must be in English) 
https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/en/src/embed/go/ref.md

### Target language
https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/zh/src/embed/go/ref.md

**Comment by swartz-k** [comment]
Apply for it. :-)

**Comment by alabulei1** [comment]
> Apply for it. :-)

Thanks! I will assign this issue to you.
