### ISSUE TITLE
[Docs] Translate embed/go.md to zh

### ISSUE THREAD

**Issue by MileyFu** [WasmEdge/WasmEdge#1094]
### The MD file link you want to translate (must be in English)
https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/en/src/embed/go.md

### Target language
https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/zh/src/embed/go.md

**Comment by jerbmarx** [comment]
Please assign this task to me. Thanks a lot.
