### ISSUE TITLE
[Docs] Translate embed/node.md to zh

### ISSUE THREAD

**Issue by MileyFu** [WasmEdge/WasmEdge#1095]
### The MD file link you want to translate (must be in English) 
https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/en/src/embed/node.md

### Target language
https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/zh/src/embed/node.md

**Comment by Vinson-Ben** [comment]
apply for this one , thanks~

**Comment by alabulei1** [comment]
Assigned. Thank you.
