### ISSUE TITLE
[Docs] Translate embed/python.md to zh

### ISSUE THREAD

**Issue by MileyFu** [WasmEdge/WasmEdge#1096]
### The MD file link you want to translate (must be in English) 
https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/en/src/embed/python.md

### Target language
https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/zh/src/embed/python.md

**Comment by mfordjody** [comment]
Assign to me

**Comment by hydai** [comment]
We are migrating to the new docs repo, this will be invalid.
