### ISSUE TITLE
[Docs] Translate embed/rust to zh

### ISSUE THREAD

**Issue by MileyFu** [WasmEdge/WasmEdge#1097]
### The MD file link you want to translate (must be in English) 
https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/en/src/embed/rust.md

### Target language
https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/zh/src/embed/rust.md

**Comment by r-asou** [comment]
Plz assign this to me

**Comment by alabulei1** [comment]
@Kodalien  It seemed that you have finished the translation. Could you reopen your PR? So that we could merge it. Thanks.
