### ISSUE TITLE
[Doc] Translate kubernetes-containerd.md to zh

### ISSUE THREAD

**Issue by alabulei1** [WasmEdge/WasmEdge#1099]
### The MD file link you want to translate (must be in English) 
https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/en/src/kubernetes/kubernetes/kubernetes-containerd.md

### Target language
zh: https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/zh/src/kubernetes/kubernetes/kubernetes-containerd.md

**Comment by zswaaa** [comment]
assign it to me.

**Comment by Bevisy** [comment]
Although I saw that someone was picking up this task, I found no progress for now. So thinking that no one has started working on this task for now, I made a PR in the hope that I can fix this problem. #1194

**Comment by alabulei1** [comment]
> Although I saw that someone was picking up this task, I found no progress for now. So thinking that no one has started working on this task for now, I made a PR in the hope that I can fix this problem. #1194

Thanks! I will take a look soon!
