### ISSUE TITLE
[Doc] Translate kubernetes-crio.md to zh

### ISSUE THREAD

**Issue by alabulei1** [WasmEdge/WasmEdge#1100]
### The MD file link you want to translate (must be in English) 

https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/en/src/kubernetes/kubernetes/kubernetes-crio.md

### Target language
https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/zh/src/kubernetes/kubernetes/kubernetes-crio.md

**Comment by r-asou** [comment]
Plz assign this to me

**Comment by FlyingOnion** [comment]
Hi @alabulei1, I would like to translate this document.

**Comment by ruijzhan** [comment]
@alabulei1 please assign it to me.

**Comment by alabulei1** [comment]
@ruijzhan  Sorry for this. Let me find a K8s related issue for you. Since @FlyingOnion has started the translation, I have assigned it to him/her.

**Comment by FlyingOnion** [comment]
@alabulei1 PR #1201 has been created.

**Comment by alabulei1** [comment]
> @alabulei1 please assign it to me.

@ruijzhan Could you comment on #1104 ? So that I assign it to you. #1104 is K8s related issue and I think it would match your needs. Sorry for the inconvenience.
