### ISSUE TITLE
[Docs] Translate dev/js/es6.md to zh

### ISSUE THREAD

**Issue by MileyFu** [WasmEdge/WasmEdge#1101]
### The MD file link you want to translate (must be in English) 
https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/en/src/dev/js/es6.md

### Target language
https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/zh/src/dev/js/es6.md

**Comment by r-asou** [comment]
Plz assign this to me

**Comment by border-1px** [comment]
I'm very interested in this project. Please assign this task to me. Thanks

**Comment by CoderfishGzh** [comment]
Plz assign this to me

**Comment by wenchajun** [comment]
I will be happy to translate the document，please assign to me

**Comment by alabulei1** [comment]
Sorry for my late reply. Since @wenchajun is new here, so I assigned this issue to her/him.
