### ISSUE TITLE
[Doc] Translate kubernetes/cotainerd.md to zh

### ISSUE THREAD

**Issue by alabulei1** [WasmEdge/WasmEdge#1103]
### The MD file link you want to translate (must be in English) 

https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/en/src/kubernetes/container.md

### Target language

zh: https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/zh/src/kubernetes/container.md

**Comment by r-asou** [comment]
Plz assign this to me

**Comment by zhannicholas** [comment]
Let me translate this one. @alabulei1

**Comment by ruijzhan** [comment]
Please assign this issue to me. @alabulei1

**Comment by alabulei1** [comment]
@zhannicholas Sorry for my late reply. I will assign you to this issue.

@ruijzhan Could you find another issue? I will assign you another issue.

**Comment by alabulei1** [comment]
> Please assign this issue to me. @alabulei1

@ruijzhan Could you comment on #1104? So that I assign it to you. #1104 is K8s related issue and I think it would match your needs. Sorry for the inconvenience.
