### ISSUE TITLE
[Doc] Translate kubernetes/cri.md to zh

### ISSUE THREAD

**Issue by alabulei1** [WasmEdge/WasmEdge#1104]
### The MD file link you want to translate (must be in English) 
https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/en/src/kubernetes/cri.md

### Target language
zh: https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/zh/src/kubernetes/cri.md

**Comment by zswaaa** [comment]
I'd like to translate this page into Chinese!
Could you pls assign it to me?

**Comment by alabulei1** [comment]
@zswaaa Since you have picked up issue #1104, I would assign this issue to a new developer.

@ruijzhan Could you comment here? So that I can assign you.

**Comment by alabulei1** [comment]
I made a mistake. Please ignore my comment before. @zswaaa looking forward to your translation.

**Comment by zswaaa** [comment]
#1214 @alabulei1 please review.
