### ISSUE TITLE
[Docs] Translate dev/js/networking.md to zh

### ISSUE THREAD

**Issue by MileyFu** [WasmEdge/WasmEdge#1105]
### The MD file link you want to translate (must be in English) 
https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/en/src/dev/js/networking.md

### Target language
https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/zh/src/dev/js/networking.md

**Comment by pasicopan** [comment]
Plz assign this to me

**Comment by alabulei1** [comment]
Assigned. Thank you!
