### ISSUE TITLE
[Docs] Translate kubernetes/demo.md to zh

### ISSUE THREAD

**Issue by alabulei1** [WasmEdge/WasmEdge#1106]
### The MD file link you want to translate (must be in English) 

https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/en/src/kubernetes/demo.md

### Target language

zh: https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/zh/src/kubernetes/demo.md

**Comment by r-asou** [comment]
Plz assign this to me

**Comment by Fournier605** [comment]
apply for this one, thanks

**Comment by kgpp34** [comment]
Please assign to me

**Comment by CoderfishGzh** [comment]
Apply for it. :-)

**Comment by alabulei1** [comment]
@Fournier605  Did you finish? If you don't start, I will assign this issue to other developers.

**Comment by wenchajun** [comment]
> @Fournier605 Did you finish? If you don't start, I will assign this issue to other developers.

If no one claims it, I will be happy to translate the document.

**Comment by kgpp34** [comment]
> 
It looks like the developer who applied first is not accomplished, can you please consider reassigning the task

**Comment by alabulei1** [comment]
Considering this section is very short and @Fournier605  didn't finished, so I assigned this issue to @kgpp34

**Comment by kgpp34** [comment]
I'll do it asap

**Comment by kgpp34** [comment]
I have applied for pr, please check，thanks

**Comment by kgpp34** [comment]
i have fixed the translation
