### ISSUE TITLE
[Docs] Translate dev/js/npm.md to zh

### ISSUE THREAD

**Issue by MileyFu** [WasmEdge/WasmEdge#1107]
### The MD file link you want to translate (must be in English) 
https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/en/src/dev/js/npm.md

### Target language
https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/zh/src/dev/js/npm.md

**Comment by r-asou** [comment]
Plz assign this to me
