### ISSUE TITLE
[Docs] Translate kubernetes/kubernets.md to zh

### ISSUE THREAD

**Issue by alabulei1** [WasmEdge/WasmEdge#1108]
### The MD file link you want to translate (must be in English) 

https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/en/src/kubernetes/kubernetes.md

### Target language

zh: https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/zh/src/kubernetes/kubernetes.md

**Comment by r-asou** [comment]
Plz assign this to me

**Comment by Kodalien** [comment]
Assign  it to me  @alabulei1  !

**Comment by Kodalien** [comment]
@alabulei1  need to review

**Comment by CoderfishGzh** [comment]
Apply for it. :-)

**Comment by JSCZhongJian** [comment]
Assigned to me @alabulei1

**Comment by alabulei1** [comment]
> Assigned to me @alabulei1

@JSCZhongJian I will find a new issue for you. It seems that @Kodalien accidentally closed the PR.
