### ISSUE TITLE
[Docs] Translate kubernetes/qucikstart.md to zh

### ISSUE THREAD

**Issue by alabulei1** [WasmEdge/WasmEdge#1109]
### The MD file link you want to translate (must be in English) 
https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/en/src/kubernetes/quickstart.md

### Target language
https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/en/src/kubernetes/quickstart.md

**Comment by javadoors** [comment]
@alabulei1 I'd like to translate this page into Chinese!
Could you pls assign it to me?
