### ISSUE TITLE
[Docs] Translate dev/js/rust.md to zh

### ISSUE THREAD

**Issue by MileyFu** [WasmEdge/WasmEdge#1111]
### The MD file link you want to translate (must be in English) 
https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/en/src/dev/js/rust.md

### Target language
https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/zh/src/dev/js/rust.md

**Comment by r-asou** [comment]
Hi, I prefer to translate this, plz assign this to me

**Comment by CoderfishGzh** [comment]
Plz assign this to me

**Comment by situ2001** [comment]
Hi, I have just done this translation. #1364
