### ISSUE TITLE
feat: Implement typed function references proposal

### ISSUE THREAD

**Issue by hydai** [WasmEdge/WasmEdge#1123]
## Introduction

This is one of the requirements for GC proposal.

[Typed function references](https://github.com/WebAssembly/function-references) proposal adds function references that are typed and can be called directly. Unlike `funcref` and the existing `call_indirect` instruction, typed function references need not be stored into a table to be called (though they can). A typed function reference can be formed from any function index.

## Motivation
 
* Enable efficient indirect function calls without runtime checks
* Represent first-class function pointers without the need for tables
* Easier and more efficient exchange of function references between modules and with host environment
* Optionally, support for safe closures
* Separate independently useful features from [GC proposal](https://github.com/WebAssembly/gc/blob/master/proposals/gc/Overview.md)

## Details

To finish this ticket,

1. Get familiar with Wasm Spec.
2. Dig into [Typed function references Spec](https://github.com/WebAssembly/function-references/blob/master/proposals/function-references/Overview.md).
3. Add the new type definitions and instructions in WasmEdge.
4. Provide an option for WasmEdge CLI to enable/disable this proposal.
5. Add unit tests to cover all these functions.

## Minimum qualifications

To apply this LFX mentorship, there are some minimum qualifications:

1. Experience with C++ programming language.
2. **Finish the challenge #1221**

## Appendix

1. GC Proposal: https://github.com/WebAssembly/gc
2. Typed function references Proposal: https://github.com/WebAssembly/function-references

**Comment by anonymousr007** [comment]
Hello @hydai, I am interested in this project.

**Comment by anonymousr007** [comment]
Can you please elaborate a little bit more? I am new in wasm-edge but experienced in c++ programming.

**Comment by hydai** [comment]
> Can you please elaborate a little bit more? I am new in wasm-edge but experienced in c++ programming.

Hi @anonymousr007,

I am not sure how much do you know about the WebAssembly(a.k.a. wasm). In this ticket, you will need to figure out the difference between the current wasm spec and the new spec defined in this proposal. Then, you have to implement the WasmEdge internal loader, parser, define more data structure, and finish the execution engine to fit this proposal.

Also, we take the code coverage seriously, so you will need to create the unit test for all your code.

Reference:
1. The Current Wasm Spec: https://github.com/WebAssembly/spec
2. If you want to know how it looks like, please refer to the previous lfx mentorship for proposal: https://github.com/WasmEdge/WasmEdge/pull/408. This is under reviewing.

**Comment by hydai** [comment]
Hi @anonymousr007,

I just updated the Minimum qualifications. If you are interested in this issue, please finish the challenge. It will help you to get familiar with the WasmEdge data structure and how to interact with the WasmEdge.

**Comment by Ruchip16** [comment]
@hydai I am also interested in this like I am very much experienced in C++ programming but new to wasm, but with proper guidance and research I would love to go deep in it, let me know if there is any scope of me working on the issue, thanks

**Comment by hydai** [comment]
@q82419 Can we close this?

**Comment by q82419** [comment]
Typed function reference proposal are merged.
