### ISSUE TITLE
[GitHub CI] Cent OS 8 EOL

### ISSUE THREAD

**Issue by SAtacker** [WasmEdge/WasmEdge#1139]
![image](https://user-images.githubusercontent.com/61797109/151984320-78a92638-4ebb-444a-bf58-a7fc05ccc3b0.png)

```
Run yum update -y
  yum update -y
  yum install -y git curl
  shell: sh -e {0}
CentOS Linux 8 - AppStream                      382  B/s |  38  B     00:00    
Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
Error: Process completed with exit code 1.
```

Cent OS 8: https://www.centos.org/centos-linux-eol/ 
Workarounds: https://stackoverflow.com/questions/70926799/centos-through-vm-no-urls-in-mirrorlist

_Originally posted by @SAtacker in https://github.com/WasmEdge/WasmEdge/issues/1138#issuecomment-1026888653_

**Comment by hydai** [comment]
Looks like we need to add the workarounds in this section: https://github.com/WasmEdge/WasmEdge/blob/master/utils/docker/Dockerfile.manylinux2014_x86_64#L17

**Comment by hydai** [comment]
This is fixed, I'm closing this.
