### ISSUE TITLE
A wrong implementation in WasmEdge WASI.

### ISSUE THREAD

**Issue by hydai** [WasmEdge/WasmEdge#1165]
A wrong implementation in WasmEdge WASI.

In linux , WasmEdge WASI use `epoll` to implement `poll_oneoff`. 
When FD subscribe `EVENTTYPE_FD_READ ` and `EVENTTYPE_FD_WRITE`, 
[Poller::read](https://github.com/WasmEdge/WasmEdge/blob/e532fdfba2ccdc5f8fcd89075a13620476fe9861/lib/host/wasi/inode-linux.cpp#L1366) will add the `fd` into `epoll_fd` first, this is ok.
And then, [Poller::write](https://github.com/WasmEdge/WasmEdge/blob/e532fdfba2ccdc5f8fcd89075a13620476fe9861/lib/host/wasi/inode-linux.cpp#L1390) add the `fd` into `epoll_fd` again, it will return error.
If the `fd`  has registered, poller::write should use `EPOLL_CTL_MOD`    :(

_Originally posted by @L-jasmine in https://github.com/second-state/wasmedge_wasi_socket/pull/35#discussion_r794344902_

**Comment by hydai** [comment]
Hi @L-jasmine 
We have a bugfix for this. https://github.com/WasmEdge/WasmEdge/tree/beststeve/wasi-poll_oneoff
However, we are still working on the unit test. Could you please try this branch and checkout if this bugfix does fix your problem?

**Comment by L-jasmine** [comment]
@hydai  It is fixed
