### ISSUE TITLE
feat: enable Include What You Use scanning in CI

### ISSUE THREAD

**Issue by hydai** [WasmEdge/WasmEdge#1183]
## Motivation

Currently, we use a local environment to run the Include What You Use like #1179 
However, it will be better to create a workflow for the regular scanning.

Reference: https://github.com/include-what-you-use/include-what-you-use

**Comment by abhinandanudupa** [comment]
Can you please assign it to me?

**Comment by hydai** [comment]
Sure ;-)

**Comment by abhinandanudupa** [comment]
Sorry, this is taking longer than what I expected. I have exams going on so it will take some more days.

**Comment by abhinandanudupa** [comment]
Should we run `include-what-you-need` on all Operating Systems - Ubuntu, Fedora, MacOS, Windows?

**Comment by hydai** [comment]
We can have one linux distribution only (Both Ubuntu or Fedora work for me), MacOS, and Windows.

**Comment by abhinandanudupa** [comment]
I am a bit confused. I tried scanning with `include-what-you-use` on **Fedora** and found no issues at all. But when I try the same on an **Arch based distro (Endeavour OS)** (updated to the latest version) the results are different - I get these warnings:
```bash
......
[ 16%] Built target utilBlake3
Warning: include-what-you-use reported diagnostics:

/home/user/test/WasmEdge/build/_deps/spdlog-src/include/spdlog/async.h should add these lines:
#include <stddef.h>                          // for size_t
#include <string>                            // for string
#include <utility>                           // for move, forward
#include "spdlog/details/thread_pool-inl.h"  // for thread_pool::thread_pool
namespace spdlog { class logger; }

/home/user/test/WasmEdge/build/_deps/spdlog-src/include/spdlog/async.h should remove these lines:

The full include-list for /home/user/test/WasmEdge/build/_deps/spdlog-src/include/spdlog/async.h:
#include <spdlog/async_logger.h>             // for async_overflow_policy
#include <spdlog/details/registry.h>         // for registry
#include <spdlog/details/thread_pool.h>      // for thread_pool
#include <stddef.h>                          // for size_t
#include <functional>                        // for function
#include <memory>                            // for make_shared, shared_ptr
#include <mutex>                             // for lock_guard, recursive_mutex
#include <string>                            // for string
#include <utility>                           // for move, forward
#include "spdlog/details/thread_pool-inl.h"  // for thread_pool::thread_pool
namespace spdlog { class logger; }
---

/home/user/test/WasmEdge/build/_deps/spdlog-src/src/async.cpp should add these lines:
#include "spdlog/common.h"                   // for SPDLOG_API
#include "spdlog/details/mpmc_blocking_q.h"  // for mpmc_blocking_queue
#include "spdlog/details/thread_pool.h"      // for async_msg

/home/user/test/WasmEdge/build/_deps/spdlog-src/src/async.cpp should remove these lines:
- #include <spdlog/async_logger-inl.h>  // lines 9-9
- #include <spdlog/details/periodic_worker-inl.h>  // lines 10-10
- #include <spdlog/details/thread_pool-inl.h>  // lines 11-11

The full include-list for /home/user/test/WasmEdge/build/_deps/spdlog-src/src/async.cpp:
#include <spdlog/async.h>
#include "spdlog/common.h"                   // for SPDLOG_API
#include "spdlog/details/mpmc_blocking_q.h"  // for mpmc_blocking_queue
#include "spdlog/details/thread_pool.h"      // for async_msg
---

Warning: include-what-you-use reported diagnostics:

/home/user/test/WasmEdge/build/_deps/spdlog-src/src/cfg.cpp should add these lines:

/home/user/test/WasmEdge/build/_deps/spdlog-src/src/cfg.cpp should remove these lines:
- #include <spdlog/cfg/helpers-inl.h>  // lines 8-8
......
```

I am using the same options (`cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_INCLUDE_WHAT_YOU_USE=include-what-you-use ../WasmEdge/ && make -j`) to scan and compile `wasmedge` but get a different result. I am not able to explain the difference and I am stuck on this for days. Is this an issue with the headers? Can you help me figure out the issue? Or should I just continue?

**Comment by hydai** [comment]
Could you provide the detailed information about the OS version and IWYU version?
I am also confused that it should not have different results on unix system.

**Comment by abhinandanudupa** [comment]
I am almost done with the work. Only the windows part is left

But I have one question - should I upload the IWYU reports to a place where its easy to read and fix?

**Comment by juntao** [comment]
I think it would be great to upload the report to the CI artifacts folder. Thank you!

**Comment by abhinandanudupa** [comment]
Alright

> Thank you!

: )

**Comment by abhinandanudupa** [comment]
Why is this [redirection](https://github.com/abhinandanudupa/WasmEdge/blob/master/.github/workflows/iwyu_scan.yml#L107) not [working](https://github.com/abhinandanudupa/WasmEdge/runs/5640745998?check_suite_focus=true#step:3:1126)?

I am trying to redirect the `stderr` to the `log file` [IWYU always reports in the [`stderr`](https://github.com/include-what-you-use/include-what-you-use#applying-fixes)]

**Comment by hydai** [comment]
> Why is this [redirection](https://github.com/abhinandanudupa/WasmEdge/blob/master/.github/workflows/iwyu_scan.yml#L107) not [working](https://github.com/abhinandanudupa/WasmEdge/runs/5640745998?check_suite_focus=true#step:3:1126)?
> 
> I am trying to redirect the `stderr` to the `log file` [IWYU always reports in the [`stderr`](https://github.com/include-what-you-use/include-what-you-use#applying-fixes)]

Looks like the redirection is working? The remaining logs don't contain any stderr things.

**Comment by abhinandanudupa** [comment]
Found out that cmake does not output in the `stderr` in this case.

**Comment by abhinandanudupa** [comment]
Can you please accept this [PR](https://github.com/WasmEdge/llvm-windows/pull/3) in the [llvm-windows](https://github.com/WasmEdge/llvm-windows) repo?

To compile `IWYU` on windows we need `LLVM` to be compiled with `clang` and `clang-tools-extra` projects enabled. Else we cannot find the `ClangConfig.cmake` [or a similarly named] file for the configuration. This file is not present in the installation of any of the clang tools on Visual Studio or in the repo.

**Comment by hydai** [comment]
This is fixed for a long time. I'm closing this one.
