### ISSUE TITLE
Inconsistent tests on share memory flags

### ISSUE THREAD

**Issue by eee4017** [WasmEdge/WasmEdge#1193]
We are working on implementing share memory flags as defined in [thread proposal](https://github.com/WebAssembly/threads/blob/main/proposals/threads/Overview.md)

> The limits type now has an additional field specifying whether the linear memory or table is shared.
> ```
> limits ::= {min u32, max u32?, share}
> share  ::= unshared | shared
> ```
> 
> Its encoding is as follows:
> 
> ```
> limits ::= 0x00 n:u32          => {min n, max e, unshared}
>            0x01 n:u32 m:u32    => {min n, max m, unshared}
>            0x03 n:u32 m:u32    => {min n, max m, shared}
> ```
> 
> Note that shared linear memory without an explicit maximum size is not permitted. This allows the embedder to reserve enough virtual memory for the maximum size so the base address of the linear memory does not have to change. Modifying the base address would require suspending all threads, which is burdensome.

Note that **shared linear memory without an explicit maximum size is not permitted**. 

If a shared memory maximum is not assigned, it would be assembled into `0x02` in wasm file.

For example, This simple test case in [memory.wast](https://github.com/second-state/WasmEdge-unittest/blob/wasm-dev-threads/threads/memory/memory.wast) would have `0x02` invalid flag in the wasm file.  Please check [memory.8.wasm](https://github.com/second-state/WasmEdge-unittest/blob/wasm-dev-threads/threads/memory/memory.8.wasm).

```
(assert_invalid (module (memory 1 shared)) "shared memory must have maximum")
```

I think `0x02` should be only used to represent a malformed share memory definition that maximum is not assigned. I believe v8 does so. Please check [wasm-constants.h](https://github.com/v8/v8/blob/main/src/wasm/wasm-constants.h#L76) in v8 engine. If the interpreter found `0x02` flag, it should report **shared memory must have maximum** error.

However, test `core/binary` does not consistent with this behavior. [binary.wast](https://github.com/second-state/WasmEdge-unittest/blob/master/core/binary/binary.wast#L1411) would report error message **integer too large** when interpreter found `0x02`.

Inspecting implementation of wabt (Please check [binary.h](https://github.com/WebAssembly/wabt/blob/main/src/binary.h) and [binary-writer.cc](https://github.com/WebAssembly/wabt/blob/main/src/binary-writer.cc#L66)), we could also find out that the first bit represent LIMITS_HAS_MAX, the second bit represent LIMITS_IS_SHARED. Thus, `0x02` should always report error **shared memory must have maximum** but not  **integer too large** .

**Comment by q82419** [comment]
It seems like the test `wast` file is updated. I'll double check later.

**Comment by q82419** [comment]
This is outdated.
The `multi-memories` proposal hasn't merged into the main spec, so the `core/binary` should fit the current spec.
