### ISSUE TITLE
[Uninstaller] Sourcing wrong path when uninstalling on MacOS

### ISSUE THREAD

**Issue by q82419** [WasmEdge/WasmEdge#1196]
### Current State

When running the uninstaller, the final step is to source the original bash profile:

```bash
$ bash <(curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/uninstall.sh)

......

Removing /Users/q82419/.wasmedge//include/wasmedge/int128.h
Removing /Users/q82419/.wasmedge//include/wasmedge/enum_types.h
Removing /Users/q82419/.wasmedge//lib/libwasmedge_c.dylib
Removing /Users/q82419/.wasmedge/env
Do you wish to uninstall the following?
/Users/q82419/.wasmedge/bin
/Users/q82419/.wasmedge/include/wasmedge
/Users/q82419/.wasmedge/lib
Please answer [Y/N | y/n]y
Removing /Users/q82419/.wasmedge/bin
Removing /Users/q82419/.wasmedge/include/wasmedge
Removing /Users/q82419/.wasmedge/lib
Do you wish to uninstall the following?
/Users/q82419/.wasmedge/include
Please answer [Y/N | y/n]y
Removing /Users/q82419/.wasmedge/include
Do you wish to uninstall the following?
/Users/q82419/.wasmedge
Please answer [Y/N | y/n]y
Removing /Users/q82419/.wasmedge
grep: /Users/q82419/.bashrc: No such file or directory
Sourcing not found in /Users/q82419/.bashrc
```

But the file path on MacOS failed.

### Expected

The file path (`.bashrc` or `.bash_profile`, etc.) should be associated with OS.

## Environment

- Hardware Architecture: x86_64
- Operating system: MacOS 15.7

## Steps to Reproduce

```bash
wget -qO- https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- -v 0.9.1-beta.2
bash <(curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/uninstall.sh)
```

**Comment by SAtacker** [comment]
> ### Expected
> The file path (`.bashrc` or `.bash_profile`, etc.) should be associated with OS.


It is determined by the following lines:
https://github.com/WasmEdge/WasmEdge/blob/b02f1f8b0679104a434ad6865b09fdf915313a38/utils/uninstall.sh#L247-L249
I believe this is a good way to know the default shell and hence its configuration file.

**Comment by SAtacker** [comment]
Could you please let me know the output of 
```bash
echo "${SHELL#${SHELL%/*}/}" 
```

**Comment by q82419** [comment]
> 

bash

Thanks.

**Comment by SAtacker** [comment]
There should be a `.bashrc` in $HOME, right?

**Comment by q82419** [comment]
I think it's like the previous issue you fixed (the config file is `.bashrc` for Linux, `.bash_profile` for MacOS, etc.)

**Comment by SAtacker** [comment]
Right, thanks.
>On OS X, Terminal by default runs a login shell every time, so this is a little different to most other systems, but you can configure that in the preferences.
Ref-[1](https://apple.stackexchange.com/questions/51036/what-is-the-difference-between-bash-profile-and-bashrc)
