### ISSUE TITLE
[Doc] Translate #frameworks/app.md to zh

### ISSUE THREAD

**Issue by alabulei1** [WasmEdge/WasmEdge#1203]
The MD file link you want to translate (must be in English)
https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/en/src/frameworks/app.md

Target language
zh: https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/zh/src/frameworks/app.md

**Comment by vaniot-s** [comment]
plz assign this to me

**Comment by border-1px** [comment]
I'm very interested in this project. Please assign this task to me

**Comment by CoderfishGzh** [comment]
Apply for it. :-)

**Comment by mydreamer4134** [comment]
Please assign to me.

**Comment by wenchajun** [comment]
I will be happy to translate the document，please assign to me

**Comment by Cold-Elite** [comment]
@alabulei1  Please assign to me

**Comment by alabulei1** [comment]
Sorry for my late reply. Since @mydreamer4134  is new here, I assigned this issue to him/her.

@wenchajun  I will find another issue for you.

**Comment by mydreamer4134** [comment]
> Sorry for my late reply. Since @mydreamer4134 is new here, I assigned this issue to him/her.
> 
> @wenchajun I will find another issue for you.

I'm sorry that I accidentally clicked the un-resign, please re-assign me, thanks!

**Comment by alabulei1** [comment]
> > Sorry for my late reply. Since @mydreamer4134 is new here, I assigned this issue to him/her.
> > @wenchajun I will find another issue for you.
> 
> I'm sorry that I accidentally clicked the un-resign, please re-assign me, thanks!

No worries! Assigned.
