### ISSUE TITLE
[Docs] Translate frameworks/serverless.md to zh

### ISSUE THREAD

**Issue by alabulei1** [WasmEdge/WasmEdge#1205]
### The MD file link you want to translate (must be in English) 
https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/en/src/frameworks/serverless.md

### Target language
zh: https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/zh/src/frameworks/serverless.md

**Comment by sunnywa** [comment]
@alabulei1 I'd like to translate this page into Chinese!
Could you pls assign it to me?

**Comment by alabulei1** [comment]
@sunnywa  Thanks for your contribution! Since @border-1px  is new here, I assigned this issue to him/her.
