### ISSUE TITLE
[Docs] Translate frameworks/app/reactr.md to zh

### ISSUE THREAD

**Issue by alabulei1** [WasmEdge/WasmEdge#1206]
### The MD file link you want to translate (must be in English) 
https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/en/src/frameworks/app/reactr.md

### Target language
zh: https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/zh/src/frameworks/app/reactr.md

**Comment by ruijzhan** [comment]
@alabulei1 please assign it to me

**Comment by CoderfishGzh** [comment]
Plz assign this to me

**Comment by alabulei1** [comment]
Hi, @ruijzhan May I ask have you finished the translation?

**Comment by HeZean** [comment]
Hi @alabulei1, what about let me work on it? (wont take long I believe)

**Comment by alabulei1** [comment]
Hi @HeZean 
Sure thing! Assigned this issue to you. Thank you.
