### ISSUE TITLE
[Docs] Translate frameworks/mesh/dapr.md to zh

### ISSUE THREAD

**Issue by alabulei1** [WasmEdge/WasmEdge#1208]
### The MD file link you want to translate (must be in English) 
https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/en/src/frameworks/mesh/dapr.md

### Target language
zh: https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/zh/src/frameworks/mesh/dapr.md

**Comment by vaniot-s** [comment]
plz assign this to me

**Comment by CoderfishGzh** [comment]
Apply for it. :-)
