### ISSUE TITLE
feat: Implement WASI and wasmedge_process host functions on Windows platform

### ISSUE THREAD

**Issue by hydai** [WasmEdge/WasmEdge#1227]
## Motivation

Currently, the WASI and wasmedge_process components in WasmEdge are only implemented on macOS and Linux platforms. Most of the host functions are not supported on the Windows platform.
Since we have lots of windows users, it is necessary to finish the implementations.

## Details

To finish the remaining host functions, you may need to do the following working items:

A. WASI component 
1. Check the `*win.*` files in [lib/host/wasi](https://github.com/WasmEdge/WasmEdge/tree/master/lib/host/wasi). 
2. Implement those unimplemented functions. E.g. those functions contains `return WasiUnexpect(__WASI_ERRNO_NOSYS);` or `return false;`
3. Make sure all of the WASI unit tests are passed.

B. WASMEDGE_PROCESS component
1. Check the files in [lib/host/wasmedge_process](https://github.com/WasmEdge/WasmEdge/blob/master/lib/host/wasmedge_process).
2. You will find that we [use libc to create and execute a new application process](https://github.com/WasmEdge/WasmEdge/blob/master/lib/host/wasmedge_process/processfunc.cpp#L175-L183). You will need to split the files into the corresponding OS headers like WASI, and you will need to use windows API to finish this feature.

## Recommended Skills
1. Familiar with C++ programming language.
2. Familiar with Windows API.

**Comment by moksh-pathak** [comment]
Hey! I am Moksh Pathak, and I would like to contribute to this issue. For starters, I am thinking on work on writing [Signal functions for Windows](https://github.com/WasmEdge/WasmEdge/blob/master/lib/host/wasi/environ-win.cpp).

**Comment by juntao** [comment]
> Hey! I am Moksh Pathak, and I would like to contribute to this issue. For starters, I am thinking on work on writing [Signal functions for Windows](https://github.com/WasmEdge/WasmEdge/blob/master/lib/host/wasi/environ-win.cpp).

Look forward to your contributions!

**Comment by moksh-pathak** [comment]
I opened a [Github Discussion](https://github.com/WasmEdge/WasmEdge/discussions/1360) to report my progress as well as seek advice and guidance to make the WASI host functions work on Windows.
