### ISSUE TITLE
Failed to correctly handle string parameter ending '\0'

### ISSUE THREAD

**Issue by KernelErr** [WasmEdge/WasmEdge#1234]
# Description

Following example code:

```rust
#[cfg(test)]
mod tests {
    #[test]
    fn test_dns() {
        use wasmedge_wasi_socket::WasiAddrinfo;
        let node = String::from("127.0.0.1");
        let service = String::from("80");
        let hints: WasiAddrinfo = WasiAddrinfo::default();
        let mut sockaddr = Vec::new();
        let mut sockbuff = Vec::new();
        let mut ai_canonname = Vec::new();
        let addrinfo = WasiAddrinfo::get_addrinfo(
            &node,
            &service,
            &hints,
            10,
            &mut sockaddr,
            &mut sockbuff,
            &mut ai_canonname,
        )
        .unwrap();
        for i in 0..addrinfo.len() {
            if addrinfo[i].ai_addrlen.ne(&0) {
                println!("{:?}", sockbuff[i]);
            }
        }
    }
}
```

Failed to get the correct result, and panicked unexpectedly.

# Why

If you copy the function body of `test_dns` into a common function rather than a test function. It will work with no error.

After investigation, the memory layout of the `node` is:

```
"www.google.com\0" in normal function
"www.google.com" + unknown other data in test function
```

In WasmEdge's code:

https://github.com/WasmEdge/WasmEdge/blob/2e9959f4a8e66f63b55dc153c8958964cf776ab4/lib/host/wasi/wasifunc.cpp#L1908-L1919

We use `NodePtr` and `NodeLen` as parameters and cast that address to `Node`. And then, we pass the node string to syscall `get_addrinfo`. However, the syscall function actually read the string until a '\0' in memory.

# Advice

We should check if **all** string parameter from the host function call is ending with '\0'. If `str[strlen - 1]` is not '\0' and we will pass it to syscall function, we should append one.

**Comment by q82419** [comment]
I think it's a low level API, so that the rust side `WasiAddrinfo::get_addrinfo` should handle the termination character?
@hydai  How do you think?

**Comment by KernelErr** [comment]
https://github.com/WasmEdge/WasmEdge/blob/aecb834d620380b691f123a7bf7e982698a0e96d/lib/host/wasi/inode-linux.cpp#L836-L837

If you choose to run all tests rather than run `test_dns`(although there is only one test here), this memory copy function would cause an error: signal: 11, SIGSEGV: invalid memory reference. I'm investigating on it.

**Comment by KernelErr** [comment]
Update: I think one line in `wasmedge_wasi_socket` is wrong.

https://github.com/second-state/wasmedge_wasi_socket/blob/ee7ae9f55a050820d10e7d3d11f2eef3cfe2afc4/src/lib.rs#L266

We should create a linked list for it. However, after fixing it in my local code, I found that WasmEdge could only read the first four elements of `WasiAddrinfoArray`.

![image](https://user-images.githubusercontent.com/45716019/154011514-bb3a4c08-1a83-47ac-bc10-ef1157e363e4.png)

The `ai_next` is correct on the Rust side, however, in WasmEdge, it's read as zero. Still investigating why.

![image](https://user-images.githubusercontent.com/45716019/154011728-5be821b2-ee04-43e5-8509-14e5cede9a08.png)

**Comment by KernelErr** [comment]
I created a PR for fixing this problem. https://github.com/second-state/wasmedge_wasi_socket/pull/41

In the meanwhile, please ensure if we should append '\0' on the WasmEdge side or the Rust SDK side. :)

**Comment by hydai** [comment]
Hi @KernelErr,
The `\0` should be handled on the Rust SDK side. Because it's very weird if we check this on the WASI side. The WASI side will assume the given string is valid. If you are worried about the invalid input, you can also add more check on the WASI side instead of appending the `\0`.

**Comment by hydai** [comment]
Hi @KernelErr 
I changed my mind.

I would like to change the signature of getaddrinfo: https://github.com/WasmEdge/WasmEdge/blob/2e9959f4a8e66f63b55dc153c8958964cf776ab4/lib/host/wasi/inode-linux.cpp#L772
Make the `ServiceStr` to `string_view` and then compose a local string as the argument for getaddrinfo. After doing this, WasmEdge WASI component will handle the `\0`. If the original string doesn't contain the `\0`, then WasmEdge will append it. Otherwise, WasmEdge will use the original string which already has the `\0`.
