### ISSUE TITLE
Add GitHub Actions for OpenYurt

### ISSUE THREAD

**Issue by alabulei1** [WasmEdge/WasmEdge#1247]
## Motivation

Showcase that developers could use OpenYurt to manage WasmEdge.

## Details

Create a new workflow for OpenYurt and WasmEdge

1. How to guide:  https://wasmedge.org/book/en/kubernetes/kubernetes/openyurt.html

2. The new GitHub Action workflow should be put on https://github.com/second-state/wasmedge-containers-examples/actions

3. After that, add the OpenYurt GitHub Actions workflows links on the WasmEdge Book

## Appendix

Example: https://github.com/second-state/wasmedge-containers-examples/blob/main/.github/workflows/kubernetes-containerd.yml

**Comment by zhuyaguang** [comment]
I have a question, OpenYurt cluster need two ndoe,one is master,one is edge,so how GitHub Actions workflows run two nodes?

**Comment by hydai** [comment]
@zhuyaguang 
Looks like OpenYurt can be run with KinD. It should be fine to test and run on GitHub Actions.
Ref: https://github.com/openyurtio/openyurt/blob/master/.github/workflows/ci.yaml#L134-L135

**Comment by EraKin575** [comment]
Can I work on this? I have worked with Github Actions before

**Comment by sarthaksarthak9** [comment]
@hydai  I would love to work on this issue!! pls assign me !!

**Comment by hydai** [comment]
It's all yours.

**Comment by hydai** [comment]
Hi @sarthaksarthak9 
What's the status of this? Are you going to work on this? If not, I will mark this as a hacktoberfest issue.

**Comment by sarthaksarthak9** [comment]
> Hi @sarthaksarthak9 What's the status of this? Are you going to work on this? If not, I will mark this as a hacktoberfest issue.

no, I am not working

**Comment by hydai** [comment]
We don't have any intention to support this action now due to the lack of CI runner resources. Closing it.
