### ISSUE TITLE
Add GitHub Actions for KubeEdge

### ISSUE THREAD

**Issue by alabulei1** [WasmEdge/WasmEdge#1248]
## Motivation

Showcase that developers could use KubeEdge to manage WasmEdge.

## Details

Create a new workflow for KubeEdge and WasmEdge

1. How to guide:  https://wasmedge.org/book/en/kubernetes/kubernetes/kubeedge.html

2. The new GitHub Action workflow should be put on https://github.com/second-state/wasmedge-containers-examples/actions

3. After that, add the KubeEdge GitHub Actions workflows links on the WasmEdge Book

## Appendix

Example: https://github.com/second-state/wasmedge-containers-examples/blob/main/.github/workflows/kubernetes-containerd.yml

**Comment by divya-mohan0209** [comment]
I'd like to work on this, please can you assign this to me?

**Comment by goasres** [comment]
I'd like to work on this, may you please assign this to me?

**Comment by ggold7046** [comment]
Hi @alabulei1, could you give me a little more details about what this GH action file is going to do ? I mean what actually we are trying to get from it ?

**Comment by hydai** [comment]
We don't have any intention to support this action now due to the lack of CI runner resources. Closing it.
