### ISSUE TITLE
Add GitHub Actions for SuperEdge

### ISSUE THREAD

**Issue by alabulei1** [WasmEdge/WasmEdge#1249]
## Motivation

Showcase that developers could use SuperEdge to manage WasmEdge.

## Details

Create a new workflow for SuperEdge and WasmEdge

1. How to guide:  https://github.com/superedge/superedge/commit/76529ca7cb23de1377a4027fe3ce4bb368acdc8a

2. The new GitHub Action workflow should be put on https://github.com/second-state/wasmedge-containers-examples/actions

3. After that, add the KubeEdge GitHub Actions workflows links on the SuperEdge chapter of the WasmEdge Book

## Appendix

Example: https://github.com/second-state/wasmedge-containers-examples/blob/main/.github/workflows/kubernetes-containerd.yml

**Comment by Swatishree-Mahapatra** [comment]
Hello! I am interested in solving this issue. Could you please assign it to me?

**Comment by EraKin575** [comment]
can I work on this?I have worked with Github Actions before

**Comment by juntao** [comment]
Of course. I assigned it to you. Thank you!

**Comment by EraKin575** [comment]
Thank you so much! Where can I ask for help if needed?

**Comment by juntao** [comment]
If you encounter any specific problem, you can raise an issue. Thanks.

**Comment by hydai** [comment]
We don't have any intention to support this action now due to the lack of CI runner resources. Closing it.
