### ISSUE TITLE
Is mac os support Image Extensions  and Tensorflow extensions?

### ISSUE THREAD

**Issue by sunnypandas** [WasmEdge/WasmEdge#1254]
I used 'curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- -e all' try to install wasmedge, but found:
Image Extensions not supported
Tensorflow extensions not supported

Could you please help us to advise that?

Thanks.

**Comment by alabulei1** [comment]
It seems that the Image Extensions and Tensorflow extensions are not supported on the macOS platform. @hydai  Could you confirm that?

@sunnypandas  If you want to use the Image Extensions and Tensorflow extensions, the Linux platform. is the best choice.

**Comment by sunnypandas** [comment]
Sure, thank you!

**Comment by q82419** [comment]
The MacOS platforms are not supported yet.
We will support that in the future, but the timeline isn't determined.
Thanks.

**Comment by q82419** [comment]
Supported.
