### ISSUE TITLE
Support socket SO_REUSEADDR

### ISSUE THREAD

**Issue by KernelErr** [WasmEdge/WasmEdge#1277]
After using `wasmedge_wasi_socket` to listen on a port, WasmEdge would not free that port when exiting. So if you execute the module again, that port isn't connectable in a while.

I think there are several ways to fix it:

- When exiting, WasmEdge free all ports.
- Give wasi module the ability to handle signals.

In the meanwhile, `wasmedge_wasi_socket` didn't handle the result of the binding port. We should also fix it.
https://github.com/second-state/wasmedge_wasi_socket/blob/7358ee128285cd8307342777298a1935780f3010/src/lib.rs#L536

**Comment by hydai** [comment]
Maybe this article can help you:
https://stackoverflow.com/questions/24194961/how-do-i-use-setsockoptso-reuseaddr

**Comment by hydai** [comment]
Also, I am not sure the relationship between binding port and signal handling?

**Comment by KernelErr** [comment]
Sorry, I misunderstood it. We may need to add `WasiSockSetOpt` to `wasmedge_wasi_socket`.
