### ISSUE TITLE
[bug] wasi getAddrInfo

### ISSUE THREAD

**Issue by L-jasmine** [WasmEdge/WasmEdge#1279]
https://github.com/WasmEdge/WasmEdge/blob/afad5e3d295f7248c16c519d89ebffc7434336f6/lib/host/wasi/inode-linux.cpp#L831

need transform linux ai_family to __wasi_address_family_t

AF_INET(2) -> __WASI_ADDRESS_FAMILY_INET4(0)
AF_INET6(*) -> __WASI_ADDRESS_FAMILY_INET6(1)

**Comment by juntao** [comment]
Hi @hydai 

Can you look into this? Thanks.
