### ISSUE TITLE
Provide a shared library with debuginfo

### ISSUE THREAD

**Issue by spacewander** [WasmEdge/WasmEdge#1281]
## Motivation

Currently, the installed shared library doesn't have debuginfo, which is unfriendly for debugging.

## Details

```
file ~/.wasmedge/lib/libwasmedge_c.so
/home/lzx/.wasmedge/lib/libwasmedge_c.so: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=1a983dab474a0bda913c07a7d5f6b48e7eb19a6e, stripped
```

An unstriped version of the library may be bigger but it is trivial under modern network environment. And most importantly, it saves developers' life (time is life).

**Comment by hydai** [comment]
Will consider.
However, if you do want the debug build, please build the WasmEdge with `debug` mode on the local environment. In most of the cases, the debug symbols are useless in the distribution.

**Comment by csmoe** [comment]
Or maintain a symbol server like mozilla-symbol-server might be helpful, cc https://github.com/mozilla-services/tecken

**Comment by hydai** [comment]
We don't have any intention to provide assets with debuginfo due to the lack of CI runner resources. Closing it.
