### ISSUE TITLE
LFX Workspace: Enable OpenVINO backend for WASI-NN

### ISSUE THREAD

**Issue by gusye1234** [WasmEdge/WasmEdge#1291]
## Milestones

The TODOS of enabling OpenVINO backend for WASI-NN are listed below

1. Get familiar with WASI-NN proposal: *1~2 weeks*
   1. Follow up the existing wasi-nn progress(lib/host/wasi_nn).
   2. Dive into the OpenVino lib.
2. Take OpenVINO as another WASI-NN backend. 5~6 weeks
   1. Create if-def branch for multiple ML backends for building options, with the unified `load` and `init_execution_context`  inerfaces to dynamicly choose which backends to use using `graph_encoding` .
   2. `WasiNNContext` for mulitpe-backends, and a specific memory session for OpenVINO
   3. Implement WASI-nn interfaces with OpenVINO.
   4. Create a demo kit, which can refers to this [demo](https://github.com/bytecodealliance/wasmtime/tree/main/crates/wasi-nn/examples)
3. Create unit tests and integrations tests to verify the `WASI-NN` component. *1 week*

## Future Works

More backends may be considered

## Appendices

* [Standardizing WASI: A system interface to run WebAssembly outside the web](https://hacks.mozilla.org/2019/03/standardizing-wasi-a-webassembly-system-interface/)
* [Implementing a WASI Proposal in Wasmtime: wasi-nn](https://bytecodealliance.org/articles/implementing-wasi-nn-in-wasmtime)
* [Machine Learning in WebAssembly: Using wasi-nn in Wasmtime](https://bytecodealliance.org/articles/using-wasi-nn-in-wasmtime)
* [feat: Enable OpenVINO backend for WASI-NN](https://github.com/WasmEdge/WasmEdge/issues/1063)

**Comment by q82419** [comment]
Hi @gusye1234 ,

We've already had some work on the `proposal/wasi_nn` branch.
You can take an overview on that first.
Please remember that we should work on that branch and create PR to that, not the `master`.
I'll keep update and rebase that branch onto the `master` when we have breaking changes or new releases.
Thanks.

**Comment by gusye1234** [comment]
Got it! Thanks for the reminder.

**Comment by q82419** [comment]
Implementation: #1340 #1440 #1461
Unit test: #1446
Docs: #1414
Examples: https://github.com/second-state/WasmEdge-WASINN-examples/pull/1
