### ISSUE TITLE
[Docs] Translate embed/rust/sys_run_host_func.md to zh

### ISSUE THREAD

**Issue by alabulei1** [WasmEdge/WasmEdge#1303]
### The MD file link you want to translate (must be in English) 
https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/en/src/embed/rust/sys_run_host_func.md

### Target language

https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/zh/src/embed/rust/sys_run_host_func.md

**Comment by JSCZhongJian** [comment]
Etam
