### ISSUE TITLE
Import WASI doesn't import "wasi_unstable"

### ISSUE THREAD

**Issue by spacewander** [WasmEdge/WasmEdge#1325]
## Motivation

Some Wasm files are using `wasi_unstable`, but the Wasi module only contains `wasi_snapshot_preview1`.

## Details

Got an error `When linking module: "wasi_unstable", function name: "proc_exit"` when I tried to load a specific Wasm file.

**Comment by hydai** [comment]
The `wasi_unstable` is called `old/snapshot_0` now, which is deprecated and replaced with `wasi_snapshot_preview1`.

Unfortunately, we don't have plan to implement it in the near future.
