### ISSUE TITLE
[Docs] Add crun "-smart" annotation

### ISSUE THREAD

**Issue by 0xE282B0** [WasmEdge/WasmEdge#1338]
Crun has just merged a workaround to run containers with different runtimes in the same pod: https://github.com/containers/crun/pull/886
Thanks to @flouthoc

With this change a pod can be annotated with `module.wasm.image/variant: compat-smart` and crun decides on the ending of the entrypoint if the container is WASM payload or an oci container. **That makes it possible to run WASM containers with sidecars.**

It would be great if that behavior would be documented.

**Comment by 0xE282B0** [comment]
We could add a chapter to the crun section https://wasmedge.org/book/en/kubernetes/container/crun.html or add a new section "Working with sidecars" under Kubernetes? 

Open for feedback 😊

**Comment by juntao** [comment]
This is excellent. We would really appreciate an example and a chapter in the docs book. :) Maybe you could create an example here?

https://github.com/second-state/wasmedge-containers-examples

Thanks!
