### ISSUE TITLE
Support yew SSR in WasmEdge

### ISSUE THREAD

**Issue by juntao** [WasmEdge/WasmEdge#1339]
The [yew framework](https://yew.rs) allows developers to create web UI in Rust. It could compile Rust code into WebAssembly bytecode that runs inside the browser to render the DOM objects for the UI. 

Alternatively, it could compile Rust to native machine code, and run it on a Rust-based web server (actix-web) to generate the HTML elements for the UI ([SSR](https://yew.rs/docs/next/advanced-topics/server-side-rendering)). 

With WasmEdge, there is a possibility to compile Rust to WASM and then run the WASM on a WasmEdge server. It is safer and more portable than native machine code on the server. 

The goal of this task is to create a WasmEdge HTTP server that performs SSR for yew, as an alternative to the actix-web + Rust native code stack. 

Note: We were able to do the above with the Percy framework -- a web UI framework similar to yew. We have to make some minor changes to the wasm-bindgen library so that the generated WASM file can run both in the browser (via JS shim) and on the server (via WASI). 

https://github.com/KernelErr/wasmedge-ssr-test

**Comment by abhinandanudupa** [comment]
Can you please assign this to me?

**Comment by alabulei1** [comment]
> Can you please assign this to me?

No Problem!

**Comment by abhinandanudupa** [comment]
I have a few questions to ask:

> The goal of this task is to create a WasmEdge HTTP server that performs SSR for yew, as an alternative to the actix-web + Rust native code stack.

Should I use React for the front-end or would plain HTML rendering be fine?

> Note: We were able to do the above with the Percy framework -- a web UI framework similar to yew. We have to make some minor changes to the wasm-bindgen library so that the generated WASM file can run both in the browser (via JS shim) and on the server (via WASI).

Can you please point out the changes that were made? If you have a repo/branch having these changes then it would be very helpful.

**Comment by juntao** [comment]
Hi @abhinandanudupa 

Ideally, we should support components.

For a Percy example, check out this:

https://github.com/second-state/percy-ssr-example

https://wasmedge.org/book/en/dev/rust/ssr.html

SSR requires the developer to start a server. It is actix by default. We just changed that to a WasmEdge server.

**Comment by abhinandanudupa** [comment]
Ok

**Comment by abhinandanudupa** [comment]
I have gone through the example for SSR in the [`yew` repository](https://github.com/yewstack/yew/tree/master/examples/simple_ssr) and learnt that -

The [`App` component](https://github.com/yewstack/yew/blob/31594245ef9a4e56768d820956229cfd3d7d2e49/examples/simple_ssr/src/lib.rs#L83) in `lib.rs` returns a html component which is used in the [`render` function](https://github.com/yewstack/yew/blob/31594245ef9a4e56768d820956229cfd3d7d2e49/examples/simple_ssr/src/bin/simple_ssr_server.rs#L20) to convert the html component (which was rendered on the server's side using the asynchronous `yew::ServerRenderer` function) to a string and this converted string is the body of the [response](https://github.com/yewstack/yew/blob/31594245ef9a4e56768d820956229cfd3d7d2e49/examples/simple_ssr/src/bin/simple_ssr_server.rs#L46) that will be sent to the client. There is also hydration which [takes places](https://github.com/yewstack/yew/blob/31594245ef9a4e56768d820956229cfd3d7d2e49/examples/simple_ssr/src/bin/simple_ssr_hydrate.rs#L6).

And, in the example for SSR with WasmEdge and Percy, we are trying to do [the same](https://github.com/second-state/percy-ssr-example/blob/780d6832ac750154268a3675724a04ffafa9c922/server-wasmedge/src/response.rs#L17) by converting the html component to a string and then passing the string as the body of the response.

_Is my understanding correct?_

If yes then I will have to use `wasmedge_wasi_socket`'s `TcpListener` and `TcpStream` to do the server side part , right?  (I am yet to fix issues with asynchronous code in my attempt)

**Comment by juntao** [comment]
Hi @abhinandanudupa 

My apologies for the delay. I am not very familiar with YEW SSR, but your understanding sounds correct. Do you have a working example of YEW running SSR on a native Rust web server? We can then replace the Rust web server (actix-web?) with an alternative implementation using WasmEdge networking socket API.

cheers
Michael

**Comment by abhinandanudupa** [comment]
> My apologies for the delay.

No need to apologise! I am guilty too.

> Do you have a working example of YEW running SSR on a native Rust web server? 

Using the official `yew` [example of SSR](https://github.com/yewstack/yew/tree/master/examples/simple_ssr), I have tried to use the [`HTTP server example`](https://github.com/second-state/wasmedge_wasi_socket/tree/main/examples/http_server) from the `wasmedge_wasi_socket` repository to build an example. 
As both are **official examples**, those interested in using `WasmEdge` as their server will find this easy and convenient. 

As I am yet to resolve an issue of a future being returned, the example it is _not working yet._ Check it out [here](https://github.com/abhinandanudupa/wasmedge_wasi_socket/tree/ssr-example/examples/server).

And also note that it is using the `2018` edition of `Rust` as in the `wasmedge_wasi_socket` example.

> We can then replace the Rust web server (actix-web?) with an alternative implementation using WasmEdge networking socket API.

Yes we should be able to do that using asynchronous programming.

**Comment by abhinandanudupa** [comment]
Perhaps, we can use this example to demonstrate `tokio` multi-threading in `WasmEdge` as alluded to [here](https://github.com/WasmEdge/WasmEdge/issues/1429#issue-1228619466)?

**Comment by juntao** [comment]
> Perhaps, we can use this example to demonstrate `tokio` multi-threading in `WasmEdge` as alluded to [here](https://github.com/WasmEdge/WasmEdge/issues/1429#issue-1228619466)?

Wasm is single-threaded (well, at least until the Wasm Threads proposal is fully supported). The issue above is to create a single thread scheduler to execute async functions (i.e., to stop a running function, go check for something else, and then remember to come back and resume the function again -- all in a single thread).

**Comment by juntao** [comment]
For your example, I think we could try to run a plain server using just the wasmedge-wasi-socket API. 

https://wasmedge.org/book/en/dev/rust/networking-nonblocking.html#a-non-blocking-http-server-example

The idea is that we will by pass the standard Rust `future` and `async` APIs altogether in our web server. Is that possible?

**Comment by abhinandanudupa** [comment]
Hi, I am _really sorry_ for the very late response!

Looking through the example code, I think it is an example for a server that can handle multiple clients (not sure, Correct me if I am wrong):
```rust
            match connects.get_mut(conn_id) {
                Some(NetConn::Server(server)) => match event.event_type {
                    poll::EventType::Timeout => unreachable!(),
                    poll::EventType::Error(e) => {
                        return Err(e);
                    }
                    poll::EventType::Read => {
                        let (mut tcp_client, addr) = server.accept(true)?;
                        println!("accept from {}", addr);

                        match tcp_client.write(DATA) {
                            Ok(n) if n < DATA.len() => {
                                println!(
                                    "write hello error: {}",
                                    io::Error::from(io::ErrorKind::WriteZero)
                                );
                                continue;
                            }
```

But the data it displays to each client

```rust
const DATA: &[u8] = b"Hello world!\n";
```
 is not a asynchronously generated as the  `yew::ServerRenderer` method does. So I think we cannot by pass the standard Rust `future` and `async` APIs.

**Comment by abhinandanudupa** [comment]
I have tried to use the `futures` crate's `block_on` method to complete the rendering and then return the string
```rust
use futures::executor::block_on;

fn render() -> String {
    let renderer = yew::ServerRenderer::<App>::new();
    let content = block_on(renderer.render());
    println!("{}", content);
    format!("<body>{:?}", content)
}
```
This compiles but fails in the execution as:
```bash
warning: `server` (bin "main") generated 6 warnings
    Finished dev [unoptimized + debuginfo] target(s) in 0.44s
     Running `wasmedge target/wasm32-wasi/debug/main.wasm`
[2022-05-28 23:00:20.619] [error] instantiation failed: unknown import, Code: 0x62
[2022-05-28 23:00:20.619] [error]     When linking module: "__wbindgen_placeholder__" , function name: "__wbindgen_describe"
[2022-05-28 23:00:20.619] [error]     At AST node: import description
[2022-05-28 23:00:20.619] [error]     At AST node: import section
[2022-05-28 23:00:20.619] [error]     At AST node: module
```
(when running `cargo run`)

How do I fix this? And checkout the entire code [here](https://github.com/abhinandanudupa/wasmedge_wasi_socket/blob/ssr-example/examples/server/src/bin/main.rs)

**Comment by hydai** [comment]
> How do I fix this? And checkout the entire code [here](https://github.com/abhinandanudupa/wasmedge_wasi_socket/blob/ssr-example/examples/server/src/bin/main.rs)

Looks like this is a special function generated by wasm-bindgen-future. Since this is not a standard in WASM/WASI spec, we don't support it currently.

**Comment by abhinandanudupa** [comment]
But is my understanding of the example code right? Then we won't be able to use Yew SSR, or will we?

**Comment by rotk2022** [comment]
> But is my understanding of the example code right? Then we won't be able to use Yew SSR, or will we?
> 
> I will try using other similar libraries.

I got the same problem.Do you have any other idea to finish it? I think it is not a good first issue right now.

**Comment by abhinandanudupa** [comment]
Hey @rotk2022, I am waiting for the [threads proposal](https://github.com/WasmEdge/WasmEdge/releases/tag/0.10.1-alpha.1) to be implemented in WasmEdge [stable release]

> I think it is not a good first issue right now.

Yes, I too think the same. But let's wait for the stable release.

**Comment by hydai** [comment]
There have been no updates for a while, so I am closing it. If this feature is really important, please feel free to reopen it or create a new one.
