### ISSUE TITLE
Support epoll in WasmEdge socket extension

### ISSUE THREAD

**Issue by juntao** [WasmEdge/WasmEdge#1350]
Add a host function to support the Linux epoll API in WasmEdge socket  extension. It accepts a set of connections and returns the ones that are ready.

The epoll functions should be exposed to developers through the Rust and JS APIs.

**Comment by hydai** [comment]
I think this is done on the WasmEdge and rust side.
Not sure about the JS part. @L-jasmine Could you please help with checking this?

**Comment by hydai** [comment]
This is resolved. WasmEdge provides the epoll extension now.
