### ISSUE TITLE
Add wasmedge_quickjs.wasm to the release attachments.

### ISSUE THREAD

**Issue by DarumaDocker** [WasmEdge/WasmEdge#1352]
When running js file via [wasmedge-quickjs](https://github.com/second-state/wasmedge-quickjs), it always needs to build the `wasmedge_quickjs.wasm` firstly.

I think it's better to put the prebuilt `wasmedge_quickjs.wasm` to the Github release attachments that can be downloaded directly.

**Comment by hydai** [comment]
This is done in the wasmedge-quickjs repo: https://github.com/second-state/wasmedge-quickjs/releases
