### ISSUE TITLE
A module linking example

### ISSUE THREAD

**Issue by Galaxy0106** [WasmEdge/WasmEdge#1368]
How to implement calls between multiple modules in WasmEdge？Could you give some examples, like WasmEdge-go-example？

**Comment by juntao** [comment]
We do not support module linking (call a function from another Wasm file) yet. It is on our roadmap.

Right now, if you need to call a function from another Wasm file, you can implement a host function to drop into the host where you can start another Wasm process. Thanks.

**Comment by Galaxy0106** [comment]
Thanks very much. If I adopt the embedded programming style of Go SDK, can I make the result of module A be used directly by module B in shared memory or otherwise？And if so, can the amount of data shared in this part be large?

**Comment by juntao** [comment]
My guess is that you can share memory between two WASM instances using the golang host as the go-between. The limit should just be the memory size you can allocate.

We do not have a ready made example for this though. Can you try and contribute an example? 🙏

**Comment by q82419** [comment]
> We do not support module linking (call a function from another Wasm file) yet. It is on our roadmap.
> 
> Right now, if you need to call a function from another Wasm file, you can implement a host function to drop into the host where you can start another Wasm process. Thanks.

I think the author means the multiple module case in WasmEdge C API but not the `module-linking` proposal?
If that so, you should check your WASM file, for example:

* a.wasm:
   * export function `func_a`
* b.wasm:
   * import function `module1` `func_a`
   * export function `func_b`, which calls `module1::func_a` in the function body

Then you should instantiate the `a.wasm` with the module name `module1`, and then instantiate the `b.wasm`.
If you use `WasmEdge_VMContext`, you can check [here](https://wasmedge.org/book/en/embed/c/ref.html#wasm-registrations-and-executions) for example.
If you use `WasmEdge_ExecutorContext` directly, you can check [here](https://wasmedge.org/book/en/embed/c/ref.html#executor) for example.

Thanks.

**Comment by q82419** [comment]
> Thanks very much. If I adopt the embedded programming style of Go SDK, can I make the result of module A be used directly by module B in shared memory or otherwise？And if so, can the amount of data shared in this part be large?

For your case, we can continue with the example above:

* a.wasm
   * export memory `memory`
* b.wasm
  * import memory `module1` `memory`

Then it will be the same: you should instantiate the a.wasm with the module name module1, and then instantiate the b.wasm. Therefore the memory instance will be shared between 2 module instances according to the WebAssembly specification.

**Comment by Galaxy0106** [comment]
> > Thanks very much. If I adopt the embedded programming style of Go SDK, can I make the result of module A be used directly by module B in shared memory or otherwise？And if so, can the amount of data shared in this part be large?
> 
> For your case, we can continue with the example above:
> 
> * a.wasm
>   
>   * export memory `memory`
> * b.wasm
>   
>   * import memory `module1` `memory`
> 
> Then it will be the same: you should instantiate the a.wasm with the module name module1, and then instantiate the b.wasm. Therefore the memory instance will be shared between 2 module instances according to the WebAssembly specification.
Thanks very much. If I need to compile a WASM module from a high-level language, how can I export memory from the module and how can I use this memory in another module that needs to be compiled in the same way?

**Comment by q82419** [comment]
Sorry that I cannot answer this question because it depends on your language and compiling tools.
In my experience, the memory definition is generated by the tools, and usually be the independent one in every generated WASM module (usually exported as name `memory`). So you may need to find another way to share the data (maybe by the host functions) between modules.

**Comment by dannypsnl** [comment]
It seems should in discussion, and component model proposal might solve memory problem, you can open a new discussion for this again.
