### ISSUE TITLE
[bug] sock_getaddrinfo has a bug in IPv6

### ISSUE THREAD

**Issue by L-jasmine** [WasmEdge/WasmEdge#1372]
https://github.com/WasmEdge/WasmEdge/blob/b1679143d51508ddb49555a90882b1223ed6adce/include/host/wasi/environ.h#L34

if sockaddr is IPv6, sockaddr.sa_data is 28-2, not 14

**Comment by juntao** [comment]
@hydai we should fix that during refactoring.

**Comment by hangedfish** [comment]
It is not known how the `getaddrinfo` function of the IPv6 protocol family should be used.
[src/lib.rs](https://github.com/second-state/wasmedge_wasi_socket/blob/73f1b0b1db7fffb9bf619165dafabf7bd1678fef/src/lib.rs#L240)
