### ISSUE TITLE
is this a bug?

### ISSUE THREAD

**Issue by alenandry** [WasmEdge/WasmEdge#1379]
## Environment

- Hardware Architecture: (e.g. x86\_64 or aarch64)
- Operating system: (e.g. Ubuntu 20.04 or CentOS 7.6)

The following information is optional. Please provide them only if you have built from source.
- C++ Compiler version:
- CMake version:
- CMake flags: (e.g. `-DCMAKE_BUILD_TYPE=Release -DWASMEDGE_BUILD_AOT_RUNTIME=ON`)
- Boost version:

**Comment by juntao** [comment]
What is the bug? 😅
