### ISSUE TITLE
Interruption of a process in rust

### ISSUE THREAD

**Issue by jmrua** [WasmEdge/WasmEdge#1380]
It is possible to interrupt a process that is running in Wasmedge using **wasmedge-sys**?  Similarly to what is proposed in #910 for the C SDK.

**Comment by apepkuss** [comment]
Hi @jmrua，

Thanks for your question. In the latest release (v0.5.0), `wasmedge-sys` does not support the asynchronous APIs defined in WasmEdge C-APIs. Therefore, it's infeasible to do that with `wasmedge-sys` for now. In fact, we're working on the design of the async APIs and will release them in future versions asap. Thanks again!

**Comment by jmrua** [comment]
Ok, thanks for your reply!

**Comment by expploitt** [comment]
Hello @apepkuss,

What do you think using the WasmEdge C-API in a Rust program, could be a temporal approach while the Rust wasmedge-sys crate is not updated?

Thanks!!

**Comment by apepkuss** [comment]
@expploitt

It should work to use the C-APIs in a Rust program, but it has to get lots of `unsafe` code involved too. I'm not very sure that I understand your motivation, so I just suppose that you wanna use the FFI directly but not the `safe` Rust APIs in your app. Please correct me if I was wrong. Thanks!

**Comment by apepkuss** [comment]
@expploitt BTW, we're working on a new version of `wasmedge-sys` actively, and it couples with the new C-APIs. Once it's ready, we'll release it asap. Thanks a lot!

**Comment by expploitt** [comment]
> 

Yes, it's exactly what I want to do! I need some control over the wasm VM. However, if you are going to release the new version of wasmedge-sys soon, I'll wait for that instead of using all those unsafe API calls.

**Comment by expploitt** [comment]
Perfect!! Thank you for your this super fast support @apepkuss !

**Comment by jmrua** [comment]
Hello @apepkuss, I would like to know how the status of the asynchronous APIs of the Rust binding regarding this issue in the last `wasmedge-sys` version.
Thank you!

**Comment by apepkuss** [comment]
> Perfect!! Thank you for your this super fast support @apepkuss !

Hi @expploitt, we released `wasmedge-sdk v0.1.0` and `wasmedge-sys v0.7.0` based on`WasmEdge v0.10.0` last weekend. Just try it and hope you like it! If have any questions about it, please let us know. Thanks!
