### ISSUE TITLE
How to use host functions with Tinygo?

### ISSUE THREAD

**Issue by Galaxy0106** [WasmEdge/WasmEdge#1388]
I want to import some host functions in my go source code that will be compiled to wasm with Tinygo. But I don't know if it is supported. Could you give an example if supported? Thanks very much.

**Comment by alabulei1** [comment]
@Galaxy0106  Hi, 
Thanks for reaching out. Theoretically, we could do this. Unfortunately, we don't have an example in Tinygo. We do have a similar example in Rust. See examples here. https://wasmedge.org/book/en/embed/go/ref.html#host-functions
