### ISSUE TITLE
[OSPP] Support async execution mode for WebAssembly in the WasmEdge Java SDK

### ISSUE THREAD

**Issue by alabulei1** [WasmEdge/WasmEdge#1415]
## Motivation

Asynchronous execution is a common feature for modern application runtimes. The WasmEdge Runtime allows WebAssembly programs to be executed asynchronously by its host application in a manner that is thread-safe. In this project, you will incorporate Java’s standard asynchronous constructs into the WasmEdge Java SDK. Java host applications will be able to execute embedded WasmEdge programs asynchronously.

## Details

Key tasks in this project include the following.
1. Learn the C-based WasmEdge asynchronous execution API.
2. Design and create an asynchronous execution API for Java.
3. Use JNI to connect the Java API with WasmEdge C API.

## Appendix

C API docs: https://wasmedge.org/book/en/embed/c/ref.html
Apply here: https://summer-ospp.ac.cn/#/org/prodetail/228830221

**Comment by hydai** [comment]
Hi @alabulei1 
Is this still available?

**Comment by dannypsnl** [comment]
Should track at #2025
