### ISSUE TITLE
Build from source on macOS Monterey 

### ISSUE THREAD

**Issue by MediosZ** [WasmEdge/WasmEdge#1426]
## Description

I build WasmEdge from source on macOS Monterey. I can finish compiling, but can not execute it.
When I try to run `wasmedge`, a segment fault occurs.
Can I help to solve this?

### Current State

Compilation finished, but executing it leads to a segment fault.
Here's the log of LLDB:
```bash
$ lldb wasmedge
(lldb) target create "wasmedge"
Current executable set to 'wasmedge' (x86_64).
(lldb) r
Process 39195 launched: '/usr/local/bin/wasmedge' (x86_64)
Process 39195 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x0000000000000000
error: memory read failed for 0x0
Target 0: (wasmedge) stopped.
```

### Expected

I can build `wasmedge` from source and execute it.

## Environment

- Hardware Architecture: x86_64
- Operating system: macOS Monterey

- C++ Compiler version: AppleClang 13.1.6.13160021
- CMake version: 3.22.2
- CMake flags: -DWASMEDGE_BUILD_AOT_RUNTIME=OFF 
- Boost version: 1.76.0

## Steps to reproduce

1. clone the repo 
2. build it.
3. execute it.

**Comment by juntao** [comment]
Can you try the 0.10.0 alpha pre-release? Thank you. 

https://github.com/WasmEdge/WasmEdge/releases/tag/0.10.0-alpha.1

**Comment by MediosZ** [comment]
Yes, I build it from the master branch, and v0.9.1 release package work for me.
Here are more results:
1. v0.9.1 build from source works
2. v0.9.1 release package works
3. v0.10.0 build from source doesn't work
4. v0.10.0 release package doesn't work

**Comment by juntao** [comment]
@hydai Can you look into this? Thanks.

**Comment by hydai** [comment]
I will try to reproduce this. Maybe we need to have a workflow for all available macos version + AppleClang version.

**Comment by MediosZ** [comment]
I can build from source now, it's not the problem of the source code.
Close this issue.
