### ISSUE TITLE
Create a Tokio-like async runtime in WasmEdge

### ISSUE THREAD

**Issue by juntao** [WasmEdge/WasmEdge#1429]
## Motivation

One of the most important features of WasmEdge is its support for [non-blocking network sockets](https://wasmedge.org/book/en/dev/rust/networking-nonblocking.html). However, the current WasmEdge API for async networking is still cumbersome. Rust developers would prefer to use a Tokio-like async / await API for such tasks.

But Tokio is multi-threaded and cannot run correctly in standard single-threaded WebAssembly. Yet, it is possible to [provide a single-threaded Tokio runtime](https://stackoverflow.com/questions/61763072/is-there-a-way-to-use-tokiomain-with-a-single-threaded-runtime-in-tokio-0-2). Our goal is to create a WebAssembly compatible Tokio scheduler.

## Specification

1. Study and evaluate the Tokio runtime and its API.
2. Create a single thread scheduler runtime with Tokio compatible API.
3. Compile the new runtime to WebAssembly.
4. Fix any potential gap in WasmEdge to support the new Tokio compatible runtime.
5. Create a suite of HTTP fetch (GET and POST) and server demo apps using the new Tokio API.

## Qualifications

To apply this LFX mentorship, there are some minimum qualifications:

1. Experience with the Rust programming language and the Tokio framework.
2. Experience with WebAssembly and WasmEdge.

## Appendix

1. The Tokio async runtime for Rust: https://tokio.rs/
2. Tokio single-thread scheduler: https://stackoverflow.com/questions/61763072/is-there-a-way-to-use-tokiomain-with-a-single-threaded-runtime-in-tokio-0-2
4. The non-blocking I/O API for WasmEdge: https://wasmedge.org/book/en/dev/rust/networking-nonblocking.html
5. The Rust API for the WasmEdge sockets extension: https://github.com/second-state/wasmedge_wasi_socket

**Comment by MediosZ** [comment]
Hi, @juntao 
I test tokio single-thread executor in wasi and it works.
The next step would be refactoring the wasmedge_wasi_socket to asyncify it.
Maybe we can just use tokio or implement a new one with Tokio compatible API.

**Comment by juntao** [comment]
Cool. Can you share an example of your test?

**Comment by MediosZ** [comment]
Sure. Here's a minimal example. 
```rust
use tokio::runtime; 
fn main() {
    let basic_rt = runtime::Builder::new_current_thread().build().unwrap();
    basic_rt.block_on(async {
        println!("Hello from async");
        let fut = async { 1 + 2 };
        let num = fut.await;
        println!("get num: {}", num);
    });
}
```
I also tried `tokio::fs`, but it didn't work. tokio spawns a new thread when it opens a file, which is not permitted in wasm.

**Comment by juntao** [comment]
Thanks! I think we can fork the Tokio MIO library and use `wasmedge_wasi_socket` instead of the standard I/O sockets when the build target is `wasm32-wasi`.

For Tokio itself, we use the same approach -- generate code for the single-threaded runtime when the build target is `wasm32-wasi`.

**Comment by MediosZ** [comment]
`mio` adds limited tcp support as discussed here https://github.com/tokio-rs/mio/pull/1549.
So yes, the first step would be making `wasmedge_wasi_socket` work for `mio`.
And `tokio` also uses `socket2`, I think we need to patch these codes so `tokio` may work as well.

**Comment by juntao** [comment]
Yes, I think we fork `tokio` first and see if we can make it work. We should not change or fork `socket2` however. Just use `wasmedge-wasi-socket` for the `wasm32-wasi` target, and `socket2` for other build targets.

**Comment by MediosZ** [comment]
Currently, I make a working single-thread wasi runtime. However, since we can not block the thread in wasm, the runtime has to poll the futures continously in a loop. It is naive but seems necessary.
Can we pause the wasm program when it's waiting for response and resume it once we get the response?
btw, where should we put the code of the runtime? Maybe in a separate repository?

**Comment by juntao** [comment]
Do you mean to pause and resume Wasm execution from outside of the VM (ie in the host program that embeds the VM)? 

Checkout what Wasm-opt has done for JS hosts: https://web.dev/asyncify/

We can build similar functionalities into our Go or Rust SDKs. @apepkuss @L-jasmine

**Comment by MediosZ** [comment]
Yes, it would nice if a wasm program can **pause itself** when there's nothing to do, and be resumed **by the host program** when some condition is met.
Let's say the wasm program is waiting for a network packet, there's nothing to do until the packet arrives. Then the wasm program can **block itself** instead of checking if the packet arrives endlessly. And the host program can resume it later.
If I understand it correctly, `asyncify` will block the wasm program everytime when it perform a synchronous I/O operation to **prevent the browser event loop being blocked**. I think it's slightly different from what we want.

**Comment by juntao** [comment]
I think perhaps we can do the "easy" thing first? That is to implement a single threaded scheduler for async operations. It is completely self-contained inside WasmEdge without any interaction from the host -- the Wasm app can run several async tasks concurrently on the single thread -- very much like how WasmEdge socket's non-blocking I/O works.

**Comment by MediosZ** [comment]
@juntao 
I've finished that already.
The problem is that the runtime has to poll the futures continously in a loop. But it's not a big problem for now I guess.
So maybe next step would be adding async support for `wasmedge_wasi_socket`, so that we can make use of the async scheduler.

**Comment by juntao** [comment]
What is the disadvantage of "constantly polling"? Is it performance? Is it how the non-blocking I/O in WasmEdge socket api currently works?

I think perhaps a long term solution is to leverage the Wasm Threads proposal. https://github.com/WasmEdge/WasmEdge/issues/248

**Comment by MediosZ** [comment]
The runtime is doing something unnecessay. It could just sleep and be waken later. And the performance could be slightly affected. 
The non-blocking I/O in WasmEdge socket api has to be used [in a loop.](https://github.com/second-state/wasmedge_wasi_socket/blob/73f1b0b1db7fffb9bf619165dafabf7bd1678fef/examples/nonblock_tcp_stream.rs#L14)

**Comment by juntao** [comment]
Yeah. We prefer to keep everything inside the Wasm VM (without help from the host). That is a simpler model for app developers to understand (less magic and generated code).

I think we can live with the polling for now, and look into supporting multi-thread inside Wasm as a longer term solution.

**Comment by sascha1337** [comment]
socket2 always annoyed me compiling to wasm/wasi, u will be heroes if you will get this stuff forked patched and working !

**Comment by echojoys** [comment]
Excuse me, is the instructor still recruiting students? I want to learn this technology

**Comment by alabulei1** [comment]
> Excuse me, is the instructor still recruiting students? I want to learn this technology

@echojoys Yes, please send an email to vivian@secondstate.io. Thanks.

**Comment by milesrichardson** [comment]
I wonder if a similar approach would work for compiling Tokio to browser-compatible WebAssembly... maybe replacing threads with web workers somehow?

**Comment by MediosZ** [comment]
Hi @milesrichardson,
I guess that should work, but what are the scenarios of using tokio in browsers?
