### ISSUE TITLE
A PostgreSQL database driver for WebAssembly

### ISSUE THREAD

**Issue by juntao** [WasmEdge/WasmEdge#1432]
## Problem

As WebAssembly is increasingly adopted as a server-side application runtime, WebAssembly applications, such as serverless functions and embedded functions, require access to relational databases. This can be done through socket connections to the database server. However, WebAssembly does not yet support the POSIX socket API. That means standard Rust (or JavaScript) connectors for PostgreSQL would not run correctly in WebAssembly.

## Proposed solution

WasmEdge provides its own networking socket extensions for WebAssembly. With the WasmEdge Rust and JavaScript SDKs, developers can write high-performance and non-blocking I/O applications including database connectors. In this project, the participant will utilize the WasmEdge Rust SDK to implement a connector for the PostgreSQL database.

* The immediate goal is to fork the synchronous PostgreSQL client, and use the `wasmedge-wasi-socket` API as an alternative network I/O library when the build target is `wasm32-wasi`.
* The longer-term goal is to support the Tokio-based (or Tokio-like) async PostgreSQL clients (see also #1429)

## Resources

1. WasmEdge socket API for Rust: https://github.com/second-state/wasmedge_wasi_socket
2. WasmEdge networking tutorial for Rust: https://wasmedge.org/book/en/dev/rust/networking-nonblocking.html
3. WasmEdge networking tutorial for JavaScript: https://wasmedge.org/book/en/dev/js/networking.html
4. Rust PostgreSQL clients: https://crates.io/crates/postgres

Related to #1402

**Comment by hydai** [comment]
Please correct me if I am wrong. I think we already support the database driver for MySQL. Do we have any plan to support PostgreSQL, or is this already supported?

**Comment by juntao** [comment]
We have it already.

https://github.com/WasmEdge/wasmedge-db-examples/tree/main/postgres

Closing this issue.
