### ISSUE TITLE
Implement component-model proposal in WasmEdge

### ISSUE THREAD

**Issue by hydai** [WasmEdge/WasmEdge#1433]
## Motivation

The [component-model](https://github.com/WebAssembly/component-model) proposal merges and supersedes the [Module Linking](https://github.com/WebAssembly/module-linking/) and [Interface Types](https://github.com/WebAssembly/interface-types) proposals.

With this feature, WasmEdge can execute multiple modules wasm with Module Linking and and more flexible types with Interface Type.

## Specification

1. Study and evaluate the component-model proposal.
2. Support new grammars and binary formats in component-model proposal.
3. Create a test suite for doing unit tests and integration tests.
4. Create several demonstrations applications.

## Qualifications

To apply this LFX mentorship, there are some minimum qualifications:

1. Experience with the C++ programming language.
2. Experience with WebAssembly and WasmEdge.

**Comment by daxsis** [comment]
Hello, could I ask the deadline for LFX application and test project? I could not find anywhere information about it, not on LFX or github. Thank you.

**Comment by alabulei1** [comment]
> Hello, could I ask the deadline for LFX application and mentorship challenge? I could not find anywhere information about it, not on LFX or github. Thank you.

Hi, The LFX application deadline is on May 24rh. The mentorship challenge is on May 27th. To find more details, please check out [this blog](https://www.secondstate.io/articles/lfx-mentorship-wasmedge-summer-2022/).

**Comment by dannypsnl** [comment]
Replaced with new issue #2943
