### ISSUE TITLE
wasmedge_process module not founded

### ISSUE THREAD

**Issue by KernelErr** [WasmEdge/WasmEdge#1447]
![image](https://user-images.githubusercontent.com/45716019/168261069-b7e6224b-cfc5-483d-8144-9838bf597de1.png)

For the latest code [bddef83](https://github.com/WasmEdge/WasmEdge/commit/bddef835c98ea9143c68f991735b79567fb2f0e2), there is an error message when running the wasm module. Seems that `wasmedge_process` has been moved.

**Comment by hydai** [comment]
If you are using the latest master, you may need to expose the env variable `WASMEDGE_PLUGIN_PATH` to get your plugins in the build folder load.

Otherwise, the default loaded plugin should be put in the `~/.wasmedge/plugin`.

**Comment by hydai** [comment]
@ibmibmibm 
Maybe we should remove this error message if the wasmedge process is not loaded. Because all of the plugins can be removed if users don't need them.

**Comment by L-jasmine** [comment]
```
# 0.10.0-alpha.1
codespace:/workspaces/wasmedge-quickjs/example_js/react_ssr_example> 
wasmedge --dir .:. --dir ./internal:../../internal ../../target/wasm32-wasi/release/wasmedge_quickjs.wasm server-build/index.js
[2022-05-18 02:52:18.319] [error] wasmedge_process module not founded.
listen 8002...
InternalError: Invalid argument (os error 28) 
# maybe wasi_poll_oneoff error

# 0.9.1
codespace:/workspaces/wasmedge-quickjs/example_js/react_ssr_example> 
wasmedge --dir .:. --dir ./internal:../../internal ../../target/wasm32-wasi/release/wasmedge_quickjs.wasm server-build/index.js
listen 8002...
```

**Comment by hydai** [comment]
The `wasmedge_process not found` error message is removed from the latest master, which will be `0.10.0-alpha.2` soon.

Not sure the remaining error is related to the wasmedge_process. Will take a look. Could you provide the reproduce steps?

**Comment by KernelErr** [comment]
I just compiled from source and ran a hello world wasm module. If the lastest code has removed the error message, please close this issue.

**Comment by hydai** [comment]
Fixed: https://github.com/WasmEdge/WasmEdge/commit/70ed44a14664f030e6c63ba20ec12e1ce16bc74b

@L-jasmine If you have another issue related to wasi-socket, please create a new issue for tracking it. Thanks.
