### ISSUE TITLE
The installer should copy plugins into the installed folder

### ISSUE THREAD

**Issue by hydai** [WasmEdge/WasmEdge#1448]
## Motivation

The file structure of the latest pre-release 0.10.0-alpha.1:

```
.
├── bin
│   ├── wasmedge
│   └── wasmedgec
├── include
│   └── wasmedge
│       ├── dense_enum_map.h
│       ├── enum_configure.h
│       ├── enum_errcode.h
│       ├── enum.inc
│       ├── enum_types.h
│       ├── int128.h
│       ├── spare_enum_map.h
│       ├── version.h
│       └── wasmedge.h
└── lib64
    ├── libwasmedge_c.so
    └── wasmedge
        └── libwasmedgePluginWasmEdgeProcess.so
```

We have moved the WasmEdge process host functions into an external shared library. The default installed path should be `~/.wasmedge/plugin`.

It's better that the installer and uninstaller to support copy and remove these files.

**Comment by hydai** [comment]
Hi @SAtacker,

Could you please help with this issue?

**Comment by SAtacker** [comment]
> Hi @SAtacker,
> 
> Could you please help with this issue?

Yes, thanks for notifying me.

**Comment by SAtacker** [comment]
Can you please point me to the resource where the details of these are mentioned?
Details like why was it done? How the user achieves it?
Also, I need to make the default directory to `~/.wasmedge/plugin` for this version and beyond. Is that it?

**Comment by hydai** [comment]
Yes, after 0.10.0, the default directory will have a new folder called `plugin` which contains all the default installed plugins from the tarball. You may need to check the tarball on every distros to make sure the resource path.

**Comment by SAtacker** [comment]
> Yes, after 0.10.0, the default directory will have a new folder called `plugin` which contains all the default installed plugins from the tarball. You may need to check the tarball on every distros to make sure the resource path.

Thanks. Another thing is, with the new plugins, shouldn't the directory tree you have mentioned be something like
```
.wasmedge/
                  ├── bin
                  │   ├── wasmedge
                  │   └── wasmedgec
                  ├── include
                  │   └── wasmedge
                  │       ├── dense_enum_map.h
                  │       ├── enum_configure.h
                  │       ├── enum_errcode.h
                  │       ├── enum.inc
                  │       ├── enum_types.h
                  │       ├── int128.h
                  │       ├── spare_enum_map.h
                  │       ├── version.h
                  │       └── wasmedge.h
                  └── lib64
                      └── libwasmedge_c.so
.wasmedge/plugin/
                              └── libwasmedgePluginWasmEdgeProcess.so
```

**Comment by SAtacker** [comment]
It'll be best if I could get access to a temporary tarball to avoid any implicit thoughts.

**Comment by ibmibmibm** [comment]
Currently the tarball is for system-wide installation, so it follows the system-wide plugin installation path, which is `PREFIX/LIB/wasmedge`, but the per-user plugin installation path is at `$HOME/.wasmedge/plugin`.
