### ISSUE TITLE
Is `INode::sockConnect` IPv6 implmented right?

### ISSUE THREAD

**Issue by hangedfish** [WasmEdge/WasmEdge#1450]
### Current State

`INode::sockConnect` is implemented by `::bind` under the conditions of the IPv6 protocol family

### Expected

`::connect` should be used.

## Steps to Reproduce

[lib/host/wasi/inode-win.cpp:442](https://github.com/WasmEdge/WasmEdge/blob/f77e67dfb298576b41eb7874df4f399a0de0e808/lib/host/wasi/inode-win.cpp#L442-L444)
[lib/host/wasi/inode-linux.ccp:975](https://github.com/WasmEdge/WasmEdge/blob/f77e67dfb298576b41eb7874df4f399a0de0e808/lib/host/wasi/inode-linux.cpp#L975-L976)
[lib/host/wasi/inode-macos.cpp:864](https://github.com/WasmEdge/WasmEdge/blob/f77e67dfb298576b41eb7874df4f399a0de0e808/lib/host/wasi/inode-macos.cpp#L864-L865)

**Comment by hydai** [comment]
@LFsWang Could you please take a look on this?

**Comment by LFsWang** [comment]
#1451
