### ISSUE TITLE
`fd_write`/`fd_read` does not work on socket fd

### ISSUE THREAD

**Issue by hangedfish** [WasmEdge/WasmEdge#1459]
### Current State

The fd returned by `sock_open` does not work with `fd_write`/`fd_read` etc, it will return the error "Bad file descriptor".

## Steps to Reproduce

https://github.com/WebAssembly/wasi-io/pull/4

**Comment by hangedfish** [comment]
There are many TLS libraries, like OpenSSL, that use `write`/`read` instead of `send`/`recv` for socket fds. I think it is necessary to solve this issue.

**Comment by hydai** [comment]
Hi @hangedfish 

This is not a bug.

The `wasi-io` you mentioned is a phase 2 proposal, which is not implemented and not on our current schedule. So it is not supported by the default WASI environment.

If this proposal is necessary, then we will have a new issue called `feat: implement WASI-IO in WasmEdge`

**Comment by juntao** [comment]
Let's create an issue to track wasi-io. Thank you.

**Comment by hydai** [comment]
I think this is fixed here: https://github.com/WasmEdge/WasmEdge/pull/2574
For the remaining WASI-IO proposal, we will track it in #1462.
