### ISSUE TITLE
feat: Implement WASI-IO proposal in WasmEdge

### ISSUE THREAD

**Issue by hydai** [WasmEdge/WasmEdge#1462]
## Motivation

In #1459, we would like to have the socket handled by `fd_write` and `fd_read`. That's why we need to implement the WASI-IO proposal.

## Details

The WASI-IO proposal is a phase 2 proposal, so the spec of this proposal may change. Please follow the latest master to finish the implementation.

## Appendix

* WASI-IO: https://github.com/WebAssembly/wasi-io
* WASI-IO related to `fd_write` and `fd_read`: https://github.com/WebAssembly/wasi-io/pull/4

**Comment by MediosZ** [comment]
I am willing to work on this!

**Comment by MediosZ** [comment]
Hi @hydai,
Currently we use `witx` crate to genrate cpp headers from witx files.
However, witx is a bit out-dated, and it doesn't support multiple return values which is presented is `wasi-io`.
So I guess we need to transfer to [wit-bindgen](https://github.com/bytecodealliance/wit-bindgen).
Ref: https://github.com/WebAssembly/wasi-io/issues/13

**Comment by hydai** [comment]
If the wit-bindgen tool implements all features of the original `witx`, then we can migrate to this new tool.

**Comment by MediosZ** [comment]
I will check it first.

**Comment by dannypsnl** [comment]
replaced with #2939
