### ISSUE TITLE
CMake Error: The source directory "" does not exist

### ISSUE THREAD

**Issue by java-Xs** [WasmEdge/WasmEdge#1466]
## Description
When i run this script,"./utils/android/standalone/build_for_android.sh",return some errors.
the error discripts:

Use Android NDK path: /home/ubuntu/Android/Sdk/ndk/23.1.7779620
=====================
=====================
.
/home/ubuntu/Desktop/project/wasm/android-wasmedge/WasmEdge
CMake Error: The source directory "" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
=== CMakeOutput.log ===
cat: build/CMakeFiles/CMakeOutput.log: No such file or directory
=== CMakeError.log ===

## Environment
ubuntu 16.04

- Hardware Architecture: (e.g. x86\_64 or aarch64)
- Operating system: (e.g. Ubuntu 20.04 or CentOS 7.6)

The following information is optional. Please provide them only if you have built from source.
- C++ Compiler version:
- CMake version: 3.5
- CMake flags: (e.g. `-DCMAKE_BUILD_TYPE=Release -DWASMEDGE_BUILD_AOT_RUNTIME=ON`)
- Boost version:

**Comment by hydai** [comment]
Hi @java-Xs 
One possible issue is that your os and cmake version is too old.
In our CI, we use Ubuntu 20.04 and cmake 3.22.

ref: https://github.com/WasmEdge/WasmEdge/commit/4498d443037f3cffa418be851f523dd40ac6a6e5#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721R338-R372

**Comment by java-Xs** [comment]
Hi @hydai ,thank you, you are right.    I find my mistake.sorry.Now cmake tool is upgraded ,the version is 3.23

> Hi @java-Xs One possible issue is that your os and cmake version is too old. In our CI, we use Ubuntu 20.04 and cmake 3.22.
> 
> ref: [4498d44#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721R338-R372](https://github.com/WasmEdge/WasmEdge/commit/4498d443037f3cffa418be851f523dd40ac6a6e5#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721R338-R372)
