### ISSUE TITLE
How to allocate memory and return pointer from host function

### ISSUE THREAD

**Issue by hangedfish** [WasmEdge/WasmEdge#1469]
Hi, Host Function is a useful feature that I am trying to use.

I need to return the pointer from the Host function, but I didn't find the function to allocate memory space from the `Runtime::Instance::MemoryInstance` class.

Am I missing something?

**Comment by hydai** [comment]
Hi, do you have a detailed example? E.g. some pseudo-codes for using this mechanism?

**Comment by hangedfish** [comment]
> Hi, do you have a detailed example? E.g. some pseudo-codes for using this mechanism?

I am trying to wrap OpenSSL as a plugin.

Here are some functions that need to return a pointer from the host function.
```C
// openssl/ssl.h
SSL_CTX *SSL_CTX_new(const SSL_METHOD *meth);
// ...
SSL *SSL_new(SSL_CTX *ctx);
```

It's easy to implement in WAMR, but I don't know how to implement it in WasmEdge.

```C++
namespace wrapper {
    // SSL_CTX *SSL_CTX_new(const SSL_METHOD *meth);
    uint32_t SSL_CTX_new(wasm_exec_env_t env, SSL_METHOD **meth_ptr) {
        wasm_module_inst_t module_inst = wasm_runtime_get_module_inst(env);
        if (!wasm_runtime_validate_native_addr(module_inst, meth_ptr, sizeof(SSL_METHOD *))) {
            return 0;
        }
        // Unwrap SSL_METHOD* from wasm memory
        SSL_METHOD *meth = *meth_ptr;
        SSL_CTX *ctx = ::SSL_CTX_new(meth);
        if (ctx == 0) {
            return 0;
        }
        // Wrap SSL_CTX* into wasm memory
        SSL_CTX **ctx_ptr;
        uint32_t ctx_wasm_ptr = wasm_runtime_module_malloc(module_inst, sizeof(SSL_CTX *), (void **) &ctx_ptr);
        *ctx_ptr = ctx;
        return ctx_wasm_ptr;
    }

    // void SSL_CTX_free(SSL_CTX *a)
    void SSL_CTX_free(wasm_exec_env_t env, SSL_CTX **ctx_ptr) {
        wasm_module_inst_t module_inst = wasm_runtime_get_module_inst(env);
        if (!wasm_runtime_validate_native_addr(module_inst, ctx_ptr, sizeof(SSL_CTX *))) {
            return;
        }
        SSL_CTX *ctx = *ctx_ptr;
        ::SSL_CTX_free(ctx);
        uint32_t ctx_wasm_ptr = wasm_runtime_addr_native_to_app(module_inst, ctx_ptr);
        wasm_runtime_module_free(module_inst, ctx_wasm_ptr);
    }
    // ...

#define REG_NATIVE_FUNC(func_name, signature) \
    { #func_name, (void*)func_name, signature, nullptr}
    NativeSymbol native_symbols[] = {
            REG_NATIVE_FUNC(SSL_CTX_new , "(i)i"),
            REG_NATIVE_FUNC(SSL_CTX_free, "(i)"),
            // ...
    };

    uint32_t get_export_apis(NativeSymbol** p_apis) {
        *p_apis = native_symbols;
        return sizeof(native_symbols) / sizeof(NativeSymbol);
    }
}
```

**Comment by hydai** [comment]
Hi @q82419 
Could you please help with this?

**Comment by q82419** [comment]
It seems like the WAMR maintains a heap in their memory instance implementation, so that they can provide an API to do this.
For working around, you can cast the pointer address to `uint64_t` and as the return value of your allocation host function:

```c
WasmEdge_Result SSL_CTX_new(void *Data, WasmEdge_MemoryInstanceContext *MemCxt,
                             const WasmEdge_Value *In, WasmEdge_Value *Out) {
  // Function type: { ... } -> {i64}
  SSL_CTX *ctx = ::SSL_CTX_new( ... );
  Out[0] = WasmEdge_ValueGenI64((uint64_t)(uintptr_t(ctx)));
  return WasmEdge_Result_Success;
}
```

And cast it back in the deallocation host function:

```c
WasmEdge_Result SSL_CTX_free(void *Data, WasmEdge_MemoryInstanceContext *MemCxt,
                             const WasmEdge_Value *In, WasmEdge_Value *Out) {
  // Function type: { ... , i64 } -> {}
  SSL_CTX *ctx = (SSL_CTX *)(uintptr_t(WasmEdge_ValueGenI64(In[1])));
  ::SSL_CTX_free(ctx);
  return WasmEdge_Result_Success;
}
```

Thanks.

**Comment by L-jasmine** [comment]
I am trying SSL to plugin too. And I found a problem. How I get a real `fd` ?

**Comment by hydai** [comment]
> I am trying SSL to plugin too. And I found a problem. How I get a real `fd` ? because wasmedge_wasi not return a real `fd` to wasm .

The `fd` should be stored in `RoFDPtr`:
https://github.com/WasmEdge/WasmEdge/blob/master/include/host/wasi/wasifunc.h#L365-L372

**Comment by L-jasmine** [comment]
> > I am trying SSL to plugin too. And I found a problem. How I get a real `fd` ? because wasmedge_wasi not return a real `fd` to wasm .
> 
> The `fd` should be stored in `RoFDPtr`: https://github.com/WasmEdge/WasmEdge/blob/master/include/host/wasi/wasifunc.h#L365-L372

https://github.com/WasmEdge/WasmEdge/blob/11ee9b39e24461e214f7dd1d33e31172127d6b7d/include/host/wasi/environ.h#L1096

I don't kown how plugin get `FdMap`? I think plugin can't get a real `fd`

**Comment by hydai** [comment]
To get a socket fd, you should use `wasi::sockOpen` not using its internal functions or data structures.

The SSL doesn't belong to WASI socket, which means that if you want anything provided by WASI socket, you have to use the WASI socket functions not this `generateRandomFdToNode`.

**Comment by hydai** [comment]
Something like this?

```
Fd = sockOpen(...);
Res = SSL_set_fd(ssl, Fd);
```

Or do I misunderstand what you want?

**Comment by L-jasmine** [comment]
> 

yes. The socket fd from wasi, but I need use it in ssl plugin.

```c
// demo.wasm.c
int fd=0;
int res = wasi_sock_open(*fd)  // real fd is 3, but this maybe is 3124213, because generateRandomFdToNode
res = ssl_set_fd(fd) // host function from plugin 
```

```c
 // ssl_plugin.c
 int ssl_set_fd(int fd){
  SSL_set_fd(fd); // fd = 3124213, not 3. it is error. My question is this
}
```

**Comment by hydai** [comment]
Maybe a helper function for converting random fd to real fd can help.
Let me think if there is a better way to do this

**Comment by dannypsnl** [comment]
Close as completed, feel free to reopen.
