### ISSUE TITLE
uninstall script will report error when the env file is not found

### ISSUE THREAD

**Issue by hydai** [WasmEdge/WasmEdge#1470]
## Description

https://github.com/second-state/wasmedge-core/runs/6520513228?check_suite_focus=true

In this case, we would like to run uninstall script first to make sure all of the previous wasmedge version is removed.
However, it will report an error with `exit 1`, which will cause the npm to return the error code and halt. 

### Expected

Show a warning. Not exit directly.

### Reference
https://github.com/WasmEdge/WasmEdge/blob/master/utils/uninstall.sh#L108-L123

**Comment by SAtacker** [comment]
Finally, written exams are done today. Let me get home. Sorry for the delay.

**Comment by hydai** [comment]
> Finally, written exams are done today. Let me get home. Sorry for the delay.

Never mind. That's fine :-)
