### ISSUE TITLE
Difference with wasmer

### ISSUE THREAD

**Issue by cyw3** [WasmEdge/WasmEdge#1476]
## Motivation

I am doing research on related WASI technologies. 

WasmEdge is a great project, but I want to know the difference and advantages between WasmEdge and Wasmer, Wasmtime?

Thanks!

**Comment by alabulei1** [comment]
Hi @cyw3,
 
There are many differences — performance, features, compatibilities, etc. But we do not discuss our competitors. If you are interested in learning more for your research, you can get in touch with me via email vivian AT secondstate DOT io. Thanks.

**Comment by cyw3** [comment]
Ok, thank you for your reply.

**Comment by bluebrown** [comment]
I think it's a legit question. It's confusing that there are multiple runtimes.
