### ISSUE TITLE
[WASI] RecvFrom return sender address length

### ISSUE THREAD

**Issue by L-jasmine** [WasmEdge/WasmEdge#1489]
https://github.com/WasmEdge/WasmEdge/blob/f77e67dfb298576b41eb7874df4f399a0de0e808/lib/host/wasi/wasifunc.cpp#L1823-L1825
In RecvFrom, InnerAddress should write by wasmedge_wasi, not wasm. this address is the sender's address, so wasm don't kown it is ipv4 or ipv6.

**Comment by L-jasmine** [comment]
another question.

I call `sock_recv_from(fd,recv_buf,sender_addr,flags,recv_len,oflags)`.
and then, I send a udp message from `127.0.0.1:3000` to this socket.

the sender_addr recv data is a bytes `[2, 0, 11, 184, 127, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]` .

sender_addr[0:2] is `__wasi_sockaddr_in_t.sin_family`
sender_addr[2:4] is `__wasi_sockaddr_in_t.sin_port`
sender_addr[4:8] is `__wasi_sockaddr_in_t.sin_addr`

I think this decoding should be done by wasmedge_wasi, not wasm app.

https://github.com/WasmEdge/WasmEdge/blob/f77e67dfb298576b41eb7874df4f399a0de0e808/lib/host/wasi/inode-linux.cpp#L991

**Comment by hydai** [comment]
What's the expected output of `recv_from` in libc?
If the return value of libc's version doesn't contain this information, we can handle it on the host function side.
If not, we should handle it on the Rust Crates side

**Comment by hangedfish** [comment]
wasmedge-socket is not compatible with wasi-libc and needs to implement a compatibility layer by yourself.

My code at [wasi_socket_ext.c](https://github.com/hangedfish/httpclient_wasmedge_socket/blob/main/wasmedge_wasi_socket_c/wasi_socket_ext.c)
