### ISSUE TITLE
[WASI] Close socket, but fd is leak

### ISSUE THREAD

**Issue by L-jasmine** [WasmEdge/WasmEdge#1490]
I loop accept new socket and close it,
`ls /proc/{wasmedge_pid}/fd` will keep increasing.

**Comment by hydai** [comment]
Hi @L-jasmine 
Please provide the reproduced steps for us to test and verify. Thanks.

**Comment by L-jasmine** [comment]
https://github.com/second-state/wasmedge_wasi_socket/runs/6589449432?check_suite_focus=true

`HTTP server example` show this bug

**Comment by hydai** [comment]
Looks like the TCPStream only shutdown the socket not closing the fd. So the fd is still alive but the socket is closed already.
Ref: https://stackoverflow.com/questions/35441815/are-close-and-closesocket-interchangable

**Comment by L-jasmine** [comment]
I try call `close()` after `shutdown()`, and it is fixed. 
thinks.
