### ISSUE TITLE
[Installer] Cannot install the latest version

### ISSUE THREAD

**Issue by q82419** [WasmEdge/WasmEdge#1497]
### Current State

WasmEdge 0.10.0 released, but the installer will install 0.9.1 if the `-v` option not specified.
And for the MacOS, the extensions cannot be installed with the 0.10.0 version if the `-e all` specified. (The 0.10.0-rc.1 works.)

### Expected

Install the latest version (0.10.0 now) if no version specified.
Install the extensions (image and tensorflow) for 0.10.0 on MacOS.

## Environment

- Hardware Architecture: x86_64
- Operating system: MacOS 10.15.7

**Comment by q82419** [comment]
This can be reproduced on Linux, too.
If users install WasmEdge from the installer, the 0.9.1 will be installed.

**Comment by 0yi0** [comment]
https://github.com/WasmEdge/WasmEdge/blob/97f49acab3c16053c6bf6fd6d6e17226801b8db9/utils/install.sh#L123

**Comment by SAtacker** [comment]
Thanks, @0yi0 @q82419
