### ISSUE TITLE
feat: WASI-Socket: Handle IPv4, IPv6, and more protocols

### ISSUE THREAD

**Issue by hydai** [WasmEdge/WasmEdge#1498]
## Motivation

In the current design of the WASI socket, we use `sockaddr_in` and `sockaddr_in6` to handle the IPv4 and IPv6. However, it's a big problem to deal with the structure size in WASM memory. The `sockaddr_in` uses 16 bytes whereas `sockaddr_in6` uses 28 bytes.

To simply the situation and increase the compatibility, using `sockaddr_storage` as the new interface type is a better way.

## Details

To enable this feature, there are several things need to do:
1. Handle the conversion between `sockaddr_storage` and `sockaddr_in | sockaddr_in6` in the host function implementation details.
2. Define the corresponding data structure on Rust Crates Side.

**Comment by sascha1337** [comment]
UP UP UP UP UP

**Comment by dannypsnl** [comment]
Can be replaced by #2939
