### ISSUE TITLE
Enable building and testing workflow for rust related crates on the Windows platform

### ISSUE THREAD

**Issue by hydai** [WasmEdge/WasmEdge#1504]
## Motivation

Previous discussion: #1500 

## Details

Currently, there is no workflow to build and test rust-related crates on the Windows platform. So there is no guarantee for making sure the compilation and functionality are working.

**Comment by abhinandanudupa** [comment]
I am interested in working on this but can you specify what are the tests that are to be run?

**Comment by hydai** [comment]
> I am interested in working on this but can you specify what are the tests that are to be run?

In the current tests, we already have Linux and macOS. https://github.com/WasmEdge/WasmEdge/actions/runs/2402900153

It just needs to set up the same testing workflow for the Windows platform.

**Comment by abhinandanudupa** [comment]
Got it, I will take it up.
