### ISSUE TITLE
WasmEdge CLI fail due to the plugins

### ISSUE THREAD

**Issue by q82419** [WasmEdge/WasmEdge#1524]
### Current State

After installation of WasmEdge 0.10.0, the CLI will fail on MacOS:

```
q82419@MacBook-Pro:~/proj/WasmEdge $ wasmedge
dyld: lazy symbol binding failed: Symbol not found: __ZN8WasmEdge6Plugin14PluginRegisterC1EPKNS0_6Plugin16PluginDescriptorE
  Referenced from: /Users/q82419/.wasmedge/plugin/libwasmedgePluginWasmEdgeProcess.dylib
  Expected in: flat namespace

dyld: Symbol not found: __ZN8WasmEdge6Plugin14PluginRegisterC1EPKNS0_6Plugin16PluginDescriptorE
  Referenced from: /Users/q82419/.wasmedge/plugin/libwasmedgePluginWasmEdgeProcess.dylib
  Expected in: flat namespace

Abort trap: 6
```

If there's no plugins, the CLI can execute successfully.

### Expected

The `wasmedge` CLI should run successfully with/without the plugins.

## Environment

- Hardware Architecture: x86_64
- Operating system: MacOS 10.15

## Steps to Reproduce

1. Install the WasmEdge 0.10.0 by the installer
2. Set the environment
3. Run the WasmEdge CLI

**Comment by hydai** [comment]
Duplicated with #1514
