### ISSUE TITLE
javascript hello.js not working

### ISSUE THREAD

**Issue by louisvangeldrop** [WasmEdge/WasmEdge#1529]
Can not run the hello.js example on windows. Error code 52

C:\Users\Louis\OneDrive\Apps\Repos\wasm\wasmedge\wasmedge-quickjs\example_js>wasmedge --dir .:. ..\target\wasm32-wasi\release\wasmedge_quickjs.wasm hello.js WasmEdge Runtime
[2022-06-08 17:26:41.552] [error] Bind guest directory failed:52
failed to find a pre-opened file descriptor through which "hello.js" could be opened

**Comment by hydai** [comment]
Hi @louisvangeldrop,
The WASI filesystem is not supported on the Windows platform currently, you can find the previous discussion here: https://github.com/second-state/wasmedge-quickjs/issues/55

And we already have a ongoing issue to make this happen #1477 . Will let you know once this feature is ready.

**Comment by dannypsnl** [comment]
We have tracking now, close this issue.
