### ISSUE TITLE
Mac Install Should Not Require Brew

### ISSUE THREAD

**Issue by exyzzy** [WasmEdge/WasmEdge#1544]
## Description
Current mac install requires brew, should provide alternative instructions that do not require brew

### Current State

curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash

Brew is required

    Please see --help
    If issue perists make a trace using -V and submit it to
https://github.com/WasmEdge/WasmEdge/issues/new?assignees=&labels=&template=bug_report.md

### Expected

Install without brew

## Environment

Mac OS, M1 chip

## Steps to Reproduce

curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash

**Comment by hydai** [comment]
Currently, we use `brew` to install the LLVM libraries for our ahead-of-time compiler. Most of the users may not have this dependency on their environment, that's why we will ask users to install brew.

Not sure if macOS has another package management system to install the llvm? I believe asking users to build the LLVM from the source is not a good idea. Or maybe creating a release binary without dynamically linked to LLVM is a possible way.

**Comment by exyzzy** [comment]
Personally can't stand brew so I will do harder things to keep it off my systems. I did build LLVM from source. Yes, creating a release binary without llvm sounds like a great option.

**Comment by hydai** [comment]
Hi @SAtacker 
Could we have a workaround that allows users to skip the `brew` checker? So users can decide to build and provide their LLVM. For example, use `install.sh --skip-brew` or `install.sh --ignore-brew`? Maybe you will have a good idea for this option's name.

And we will try to make our release binary without dynamic LLVM linking in future releases.

**Comment by SAtacker** [comment]
> Hi @SAtacker 
> Could we have a workaround that allows users to skip the `brew` checker? So users can decide to build and provide their LLVM. For example, use `install.sh --skip-brew` or `install.sh --ignore-brew`? Maybe you will have a good idea for this option's name.
> 
> And we will try to make our release binary without dynamic LLVM linking in future releases.

Hi,
Yes we can do that. I like your suggestion `--ignore-brew`. I shall make a PR soon.
Yes that would be great.
Thanks

**Comment by hydai** [comment]
Hi @exyzzy 
We just add a new option `--ignore-brew` to avoid asking users to install llvm via brew. Please use the latest master version of the installer script. Thanks.

**Comment by hydai** [comment]
Hi @exyzzy 
In the new release, we already embedded llvm into the binary, so it no longer needs to install llvm from brew or other places. I'm closing this.
