### ISSUE TITLE
Build wasmedge-sys error from scratch

### ISSUE THREAD

**Issue by chenyukang** [WasmEdge/WasmEdge#1552]
## Description

I added the latest wasmedge-sys to Cargo.toml, and cargo build will get error:

```
coder@pearl:~/demo$ cargo build
    Blocking waiting for file lock on build directory
   Compiling leb128 v0.2.5
   Compiling unicode-width v0.1.9
   Compiling ppv-lite86 v0.2.16
   Compiling libc v0.2.126
   Compiling memchr v2.5.0
   Compiling wasm-encoder v0.13.0
   Compiling thiserror v1.0.31
   Compiling wasmedge-sys v0.7.0
   Compiling getrandom v0.2.7
   Compiling rand_core v0.6.3
   Compiling wast v42.0.0
   Compiling rand_chacha v0.3.1
   Compiling rand v0.8.5
The following warnings were emitted during compilation:

warning: [wasmedge-sys] not_standalone
warning: [wasmedge-sys] TARGET_OS: linux
warning: [wasmedge-sys] git init output: Output { status: ExitStatus(unix_wait_status(0)), stdout: "Reinitialized existing Git repository in /home/coder/demo/target/debug/build/wasmedge-sys-37a25dfbb3310fc8/out/wasmedge/.git/\n", stderr: "" }
warning: [wasmedge-sys] git remote add output: Output { status: ExitStatus(unix_wait_status(32768)), stdout: "", stderr: "fatal: remote origin already exists.\n" }
warning: [wasmedge-sys] git fetch output: Output { status: ExitStatus(unix_wait_status(0)), stdout: "", stderr: "From https://github.com/WasmEdge/WasmEdge\n * branch              HEAD       -> FETCH_HEAD\n" }
warning: [wasmedge-sys] git checkout output: Output { status: ExitStatus(unix_wait_status(0)), stdout: "", stderr: "HEAD is now at 0eca4b9f [Misc] Add the necessary components of WasmEdge static library.\n" }

error: failed to run custom build command for `wasmedge-sys v0.7.0`

Caused by:
  process didn't exit successfully: `/home/coder/demo/target/debug/build/wasmedge-sys-8747e4711719c10f/build-script-build` (exit status: 101)
```

Then I follow the link to build from scratch

https://wasmedge.org/book/en/extend/build.html

Did I miss something?

### Current State

![image](https://user-images.githubusercontent.com/230646/173992480-8c8d5b7d-5283-47b6-b5e9-982f8145b14c.png)

### Expected

Building will be Ok

## Environment

Linux pearl 5.13.0-1029-azure #34~20.04.1-Ubuntu SMP Thu Jun 9 12:37:07 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by apepkuss** [comment]
Hi @chenyukang 

Thanks for your report. Could you please check if the way of importing `wasmedge-sys` to your `Cargo.toml` is same as below:

```toml
wasmedge-sys = {version = "0.7", features = ["standalone"]}
```

If you do not deploy [WasmEdge v0.10.0 library](https://github.com/WasmEdge/WasmEdge/releases/tag/0.10.0) on your dev environment, please enable `standalone` feature, which tells `build_script` to compile and deploy `WasmEdge` library.

If the issue's still there, please let me know. Thanks!

**Comment by chenyukang** [comment]
@apepkuss Thanks for the help.
I use your code snippet in cargo.toml, and get this error:

![image](https://user-images.githubusercontent.com/230646/174170463-78738833-fced-4ecd-8b8c-e97519f47ca2.png)

Installing libclang-12-dev resolved this issue, but I think we should add it in the doc.

Now I met another issue:

![image](https://user-images.githubusercontent.com/230646/174170693-cf9a0287-a3e4-49ea-b72a-ba97cdc925fe.png)

**Comment by apepkuss** [comment]
Hi @chenyukang 

Thanks for your report, we've already reproduced the issue. A quick fix for it is to use `non-standalone` deployment.

1. Download `WasmEdge v0.10.0` from [here](https://github.com/WasmEdge/WasmEdge/releases/tag/0.10.0) and unzip it. The unzipped folder should look like below:
```bash
├── bin
│   ├── wasmedge
│   └── wasmedgec
├── include
│   └── wasmedge
│       ├── dense_enum_map.h
│       ├── enum.inc
│       ├── enum_configure.h
│       ├── enum_errcode.h
│       ├── enum_types.h
│       ├── int128.h
│       ├── spare_enum_map.h
│       ├── version.h
│       └── wasmedge.h
└── lib64
    ├── libwasmedge_c.so
    └── wasmedge
        └── libwasmedgePluginWasmEdgeProcess.so

5 directories, 13 files
```

2. Create a folder named `.wasmedge` in the `$HOME` directory, and move all the contents in the unzipped folder into `$HOME/.wasmedge`. After that, the `$HOME/.wasmedge` directory looks like below:
```bash
root@8b5a2d78b3f1:~/.wasmedge# tree .
.
|-- bin
|   |-- wasmedge
|   `-- wasmedgec
|-- include
|   `-- wasmedge
|       |-- dense_enum_map.h
|       |-- enum.inc
|       |-- enum_configure.h
|       |-- enum_errcode.h
|       |-- enum_types.h
|       |-- int128.h
|       |-- spare_enum_map.h
|       |-- version.h
|       `-- wasmedge.h
`-- lib64
    |-- libwasmedge_c.so
    `-- wasmedge
        `-- libwasmedgePluginWasmEdgeProcess.so

5 directories, 14 files
```
3. Your `Cargo.toml` should be
```toml
[dependencies]
wasmedge-types = "0.1"
wasmedge-sys = "0.7"
```

When you finish the three steps above, just `cargo run` or `cargo build` your project.

If any further issues, please let me know! Thanks.

**Comment by chenyukang** [comment]
Fix according to your steps,

Trying to compile a sample program, got this compiling error:
![image](https://user-images.githubusercontent.com/230646/174270728-6563081f-e121-42db-ba4a-16126768e8e8.png)

I replaced it with register_wasm_from_bytes and get another linking error:

```
coder@pearl:~/demo$ cargo build
   Compiling demo v0.1.0 (/home/coder/demo)
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-m64" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.1116hwo4l79dfd48.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.12equgr6l4c56134.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.147frirn44958ros.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.177206bfsjabzoa0.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.17eiku0h5r9hdog7.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.17rl56gy3bmylpce.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.194z0ynh6lmli2ma.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.1apoq13fng1dn9aa.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.1cjhoseclru34kfb.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.1e3od86oorjl254b.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.1gy5v1sul5dz91hl.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.1k1w9i2s8aoo7amj.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.1l7x0m3yr2gpnfv.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.1oh9zh015ondm3sz.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.1oq5x9gr2gnbzjkq.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.1pw943ull81nnpm5.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.1q3d707qdjdfokod.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.1xc9n1ljwpwsu39.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.27vhl6wgd0drahme.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.28hm0j9vo9wa21qh.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.2csigeaksefbi1di.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.2doj6w51tsq4wycu.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.2hnxqvfhj754uwx7.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.2k7tkya3wjbns5yv.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.2nh6vw89gz3zyxol.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.2p5n2ncdzv3l7m5z.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.2pd2cpq4mecq0li8.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.2u5pk7c2bszg6cp0.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.331fpbtqbkoj358a.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.361dhnto04vvu558.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.362tyjk3ub2kaksg.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.38nliqwoc4f3o1ex.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.3byna2lts0x2g8ty.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.3dq2i1ceoi4922tf.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.3gxu317i0sb1g4g2.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.3u5k86gg5ujxww8e.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.3yqtgccwfg76yz4l.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.4av71ik3esxiine2.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.4ithaxvcweond8iw.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.4lnr64t9l1fite6t.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.4nooetiompfx1jwk.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.4ow5ykcg3wlp9cbz.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.4tzgqqd60muf04ru.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.4zzg9bcjbtbdqmlk.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.53nbs8tlbt8bar2c.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.55ehleikgaloj55d.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.587nzeq99nvtj95j.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.58etbnwz4oymocxz.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.591hxuqqibrkazlo.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.5afxgq8d5lfmo8gb.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.5e9kg1emiq22su5.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.5odvv7t3gasm01z.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.6mno601i3kbz0rc.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.8yntx67npkmsw2o.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.a7ltdul87y1tj9x.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.bf7ok49eg43ao5c.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.c25mpw5y7og9of9.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.fuajgqw6a1jm4g4.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.gps5t9xc8rlgmad.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.p4rr0sxhzw0knnh.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.rnu6bq1crp3pk8c.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.rnx8w8pcaemcyz1.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.sy4d78m39nlih84.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.zgm7kuic5lu69u0.rcgu.o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6.cdz36eabqx4s46t.rcgu.o" "-Wl,--as-needed" "-L" "/home/coder/demo/target/debug/deps" "-L" "/home/coder/.wasmedge/lib64" "-L" "/home/coder/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/home/coder/demo/target/debug/deps/libwasmedge_sys-1d0d702b3479f6fc.rlib" "/home/coder/demo/target/debug/deps/librand-8b4fba53a659176d.rlib" "/home/coder/demo/target/debug/deps/librand_chacha-cb21f2fce7af17f7.rlib" "/home/coder/demo/target/debug/deps/libppv_lite86-5e6fdfabf1edbf66.rlib" "/home/coder/demo/target/debug/deps/librand_core-4c553fd687d1d387.rlib" "/home/coder/demo/target/debug/deps/libgetrandom-7bf96f9aa08aa737.rlib" "/home/coder/demo/target/debug/deps/liblibc-f7cc4e82b538969b.rlib" "/home/coder/demo/target/debug/deps/libcfg_if-90e3626e3c41eec3.rlib" "/home/coder/demo/target/debug/deps/libwasmedge_types-bad553be190e40f7.rlib" "/home/coder/demo/target/debug/deps/libwat-7cfb8c3c66c9b9e1.rlib" "/home/coder/demo/target/debug/deps/libwast-7a88dcd4bae31e15.rlib" "/home/coder/demo/target/debug/deps/libmemchr-4fce41623cec2314.rlib" "/home/coder/demo/target/debug/deps/libwasm_encoder-6ff2ced1cdd8ae1f.rlib" "/home/coder/demo/target/debug/deps/libleb128-ad3cdfa3e477c620.rlib" "/home/coder/demo/target/debug/deps/libunicode_width-e91030079211fd3f.rlib" "/home/coder/demo/target/debug/deps/libthiserror-7e30c60160322737.rlib" "/home/coder/demo/target/debug/deps/liblazy_static-b33cd6b8ee13db74.rlib" "-Wl,--start-group" "/home/coder/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-516357af627e1a7d.rlib" "/home/coder/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-9cb5ef8235cf10de.rlib" "/home/coder/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-c94e3d0069d19330.rlib" "/home/coder/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-5a532766d1e80b5b.rlib" "/home/coder/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-d08f0c83526179dc.rlib" "/home/coder/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libmemchr-d995c6cafdb3d253.rlib" "/home/coder/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-02ebc04a72bd9433.rlib" "/home/coder/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-5cbc32ae14534ca9.rlib" "/home/coder/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_detect-969ebc8623abfcc9.rlib" "/home/coder/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-7f98f837d3579544.rlib" "/home/coder/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-c79b77d9c2e73c7a.rlib" "/home/coder/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-c7b2792f3bc0d0eb.rlib" "/home/coder/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-7558dde8464d46ce.rlib" "/home/coder/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-b3d84848ab790cf7.rlib" "/home/coder/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-f48e57d6d73020ee.rlib" "/home/coder/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-ffaac76756e3f83b.rlib" "/home/coder/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-2a6a2797f7a73818.rlib" "/home/coder/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-0e3656b1fda5fd7b.rlib" "-Wl,--end-group" "/home/coder/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-f98cce041f593917.rlib" "-Wl,-Bdynamic" "-lwasmedge_c" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/home/coder/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/home/coder/demo/target/debug/deps/demo-6497ceaea42a78d6" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro,-znow" "-nodefaultlibs"
  = note: /usr/bin/ld: warning: libncurses.so.5, needed by /home/coder/.wasmedge/lib64/libwasmedge_c.so, not found (try using -rpath or -rpath-link)
          /usr/bin/ld: /home/coder/.wasmedge/lib64/libwasmedge_c.so: undefined reference to `set_curterm'
          /usr/bin/ld: /home/coder/.wasmedge/lib64/libwasmedge_c.so: undefined reference to `del_curterm'
          /usr/bin/ld: /home/coder/.wasmedge/lib64/libwasmedge_c.so: undefined reference to `tigetnum'
          /usr/bin/ld: /home/coder/.wasmedge/lib64/libwasmedge_c.so: undefined reference to `setupterm'
          collect2: error: ld returned 1 exit status

  = help: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)

error: could not compile `demo` due to previous error
```

**Comment by apepkuss** [comment]
Hi @chenyukang 

According to the error message, it seems some dependency is not installed on your environment. Could you please check if these [required dependencies](https://wasmedge.org/book/en/extend/build.html#install-dependencies-on-ubuntu-2004-manually) on Linux are installed on your side? Thanks!

**Comment by chenyukang** [comment]
```rust
use wasmedge_sys::{Vm, WasmValue};
use wasmedge_types::wat2wasm;

#[cfg_attr(test, test)]
fn main() -> Result<(), Box<dyn std::error::Error>> {
    // read the wasm bytes
    let wasm_bytes = wat2wasm(
        br#"
        (module
            (export "fib" (func $fib))
            (func $fib (param $n i32) (result i32)
             (if
              (i32.lt_s
               (get_local $n)
               (i32.const 2)
              )
              (return
               (i32.const 1)
              )
             )
             (return
              (i32.add
               (call $fib
                (i32.sub
                 (get_local $n)
                 (i32.const 2)
                )
               )
               (call $fib
                (i32.sub
                 (get_local $n)
                 (i32.const 1)
                )
               )
              )
             )
            )
           )
"#,
    )?;

    // create a Vm instance
    let mut vm = Vm::create(None, None)?;

    // register the wasm bytes
    let module_name = "extern-module";
    vm.register_wasm_from_bytes(module_name, &wasm_bytes)?;

    // run the exported function named "fib"
    let func_name = "fib";
    let result = vm.run_registered_function(module_name, func_name, [WasmValue::from_i32(5)])?;

    assert_eq!(result.len(), 1);
    assert_eq!(result[0].to_i32(), 8);

    Ok(())
}
```

I can compile this code successfully, but run it will get an error:

```
coder@pearl:~/demo$ ./target/debug/demo
./target/debug/demo: symbol lookup error: ./target/debug/demo: undefined symbol: WasmEdge_ModuleInstanceFindFunction
```

**Comment by apepkuss** [comment]
> ```
> sudo apt-get install libncurses5
> ```
> 
> solved it, but it's not required dependency in the document.

@chenyukang Thanks a lot for the feedback!

@hydai Could you please help double-check if `libncurses5` should be listed in the [Install dependencies on Ubuntu 20.04 manually](https://wasmedge.org/book/en/extend/build.html#install-dependencies-on-ubuntu-2004-manually) section of mdbook? Thanks!

**Comment by chenyukang** [comment]
Btw, do you know how to pass a Vec to the function?
The Go version is like this:
https://github.com/second-state/dapr-wasm/blob/main/image-api-go/image_api.go#L55

**Comment by hydai** [comment]
> ```
> sudo apt-get install libncurses5
> ```
> 
> solved it, but it's not required dependency in the document.

The libncurses5 is required by the `llvm` package. If the users install llvm then this should be also installed. `llvm->libtinfo->ncurses`

**Comment by chenyukang** [comment]
> > ```
> > sudo apt-get install libncurses5
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > solved it, but it's not required dependency in the document.
> 
> The libncurses5 is required by the `llvm` package. If the users install llvm then this should be also installed. `llvm->libtinfo->ncurses`

I installed llvm related deps, but still missed ncurses, we can have a double-check:
![image](https://user-images.githubusercontent.com/230646/174277737-c40f9d18-b410-4469-8414-ea0ad652c449.png)

**Comment by chenyukang** [comment]
When I installed libncurses5, libtinfo5 will be installed.
![image](https://user-images.githubusercontent.com/230646/174278284-20b19193-6b2f-45c5-8147-0fc58f17bafc.png)

**Comment by apepkuss** [comment]
> Btw, do you know how to pass a Vec to the function? The Go version is like this: https://github.com/second-state/dapr-wasm/blob/main/image-api-go/image_api.go#L55

It seems `wasmedge-bindgen` is used in the Go code. I'm not familiar with it, so you can post an issue [here](https://github.com/second-state/wasmedge-bindgen).

**Comment by hydai** [comment]
> When I installed libncurses5, libtinfo5 will be installed. ![image](https://user-images.githubusercontent.com/230646/174278284-20b19193-6b2f-45c5-8147-0fc58f17bafc.png)

<img width="1792" alt="截圖 2022-06-17 at 18 30 08@2x" src="https://user-images.githubusercontent.com/2776756/174281214-4152f800-78e1-4349-b178-4b34974094a9.png">

Hmmmmmm. I used Ubuntu 20.04 without installing `libncurses5`. And I download the `wasmedge 0.10.0` from the release page (https://github.com/WasmEdge/WasmEdge/releases/download/0.10.0/WasmEdge-0.10.0-manylinux2014_x86_64.tar.gz). Compile the example program and execute it.

However, it doesn't ask me for the `libncurses5`. Do you install the old version of wasmedge before? If so, maybe try to delete all of the previous installed versions or try to specify the path to the latest wasmedge release.

**Comment by hydai** [comment]
And if I remember correctly, the `libtinfo` and `libncurses` is statically linked in our manylinux pre-built release. So I am very curious about how this error occurred :-(

**Comment by apepkuss** [comment]
> ```rust
> use wasmedge_sys::{Vm, WasmValue};
> use wasmedge_types::wat2wasm;
> 
> #[cfg_attr(test, test)]
> fn main() -> Result<(), Box<dyn std::error::Error>> {
>     // read the wasm bytes
>     let wasm_bytes = wat2wasm(
>         br#"
>         (module
>             (export "fib" (func $fib))
>             (func $fib (param $n i32) (result i32)
>              (if
>               (i32.lt_s
>                (get_local $n)
>                (i32.const 2)
>               )
>               (return
>                (i32.const 1)
>               )
>              )
>              (return
>               (i32.add
>                (call $fib
>                 (i32.sub
>                  (get_local $n)
>                  (i32.const 2)
>                 )
>                )
>                (call $fib
>                 (i32.sub
>                  (get_local $n)
>                  (i32.const 1)
>                 )
>                )
>               )
>              )
>             )
>            )
> "#,
>     )?;
> 
>     // create a Vm instance
>     let mut vm = Vm::create(None, None)?;
> 
>     // register the wasm bytes
>     let module_name = "extern-module";
>     vm.register_wasm_from_bytes(module_name, &wasm_bytes)?;
> 
>     // run the exported function named "fib"
>     let func_name = "fib";
>     let result = vm.run_registered_function(module_name, func_name, [WasmValue::from_i32(5)])?;
> 
>     assert_eq!(result.len(), 1);
>     assert_eq!(result[0].to_i32(), 8);
> 
>     Ok(())
> }
> ```
> 
> I can compile this code successfully, but run it will get an error:
> 
> ```
> coder@pearl:~/demo$ ./target/debug/demo
> ./target/debug/demo: symbol lookup error: ./target/debug/demo: undefined symbol: WasmEdge_ModuleInstanceFindFunction
> ```

@chenyukang, I created a docker container of Ubuntu 20.04 from scratch but didn't reproduce the error as you reported. Could you please try the following command to run your code?

```bash
LD_LIBRARY_PATH=/root/.wasmedge/lib64/ cargo run
```
Please modify the path to the `lib64` directory according to your environment.

**Comment by chenyukang** [comment]
> > When I installed libncurses5, libtinfo5 will be installed. ![image](https://user-images.githubusercontent.com/230646/174278284-20b19193-6b2f-45c5-8147-0fc58f17bafc.png)
> 
> <img alt="截圖 2022-06-17 at 18 30 08@2x" width="1792" src="https://user-images.githubusercontent.com/2776756/174281214-4152f800-78e1-4349-b178-4b34974094a9.png">
> 
> Hmmmmmm. I used Ubuntu 20.04 without installing `libncurses5`. And I download the `wasmedge 0.10.0` from the release page (https://github.com/WasmEdge/WasmEdge/releases/download/0.10.0/WasmEdge-0.10.0-manylinux2014_x86_64.tar.gz). Compile the example program and execute it.
> 
> However, it doesn't ask me for the `libncurses5`. Do you install the old version of wasmedge before? If so, maybe try to delete all of the previous installed versions or try to specify the path to the latest wasmedge release.

Yes, I installed an old version, 
maybe it's a weird result with the temporary solution for fixing wasmedge-sys.

I will use another clean ubuntu to have a test.

**Comment by chenyukang** [comment]
> ```shell
> ```shell
> LD_LIBRARY_PATH=/root/.wasmedge/lib64/ cargo run
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```

LD_LIBRARY_PATH=/root/.wasmedge/lib64/ cargo run
will fix the problem.

Closing this issue, but I think the installing issue for non-standalone mode need be fixed.

**Comment by apepkuss** [comment]
> > ```shell
> > ```shell
> > LD_LIBRARY_PATH=/root/.wasmedge/lib64/ cargo run
> > ```
> 
> LD_LIBRARY_PATH=/root/.wasmedge/lib64/ cargo run will fix the problem.
> 
> Closing this issue, but I think the installing issue for non-standalone mode need be fixed.

Great! We'll be optimizing the non-standalone installation. Thanks!
