### ISSUE TITLE
OSPP: WasmEdge Java SDK Async

### ISSUE THREAD

**Issue by kenvifire** [WasmEdge/WasmEdge#1568]
## Motivation

Implement the Async feature for Java language binding.

## Details

- Define async for Java binding
- Implement with JNI
- API doc and examples

**Comment by yyy1000** [comment]
I have successfully compiled the source code and written a CMake project that can link the WasmEdge library. ( Though have some problems in CMake).

**Comment by hydai** [comment]
PR merged: https://github.com/WasmEdge/WasmEdge/pull/1990
