### ISSUE TITLE
Create a Dapr Rust SDK for WasmEdge

### ISSUE THREAD

**Issue by juntao** [WasmEdge/WasmEdge#1571]
## Motivation

We would like to support WasmEdge-based microservices to communicate directly with Dapr sidecars. 

## Details

In this first iteration, we should just use the [wasmedge_http_req](https://github.com/second-state/wasmedge_http_req) API to communicate with the Dapr sidecar. 

In future iterations, we will use WasmEdge's Tokio-like async networking library to communicate through the Dapr protocol.

**Comment by Ren-ZY** [comment]
Hello~@juntao, I am willing to do this job.

**Comment by hydai** [comment]
Should we add this issue to the next LFX mentorship if this is not finished yet?

**Comment by hydai** [comment]
Looks like we already had it: https://github.com/second-state/dapr-sdk-wasmedge
Closing this, please feel free to reopen it if I misunderstood.
