### ISSUE TITLE
No wasi env has been passed with wasmedge_sys

### ISSUE THREAD

**Issue by DarumaDocker** [WasmEdge/WasmEdge#1580]
My wasm(rust):
```rust
use std::env;

#[no_mangle]
pub fn print_env() {
  println!("The env vars are as follows.");
  for (key, value) in env::vars() {
    println!("{}: {}", key, value);
  }

  println!("The args are as follows.");
  for argument in env::args() {
    println!("{}", argument);
  }
}
```

When I call `print_env` with wasmedge binary:
`wasmedge --env a=b --env c=d --reactor test.wasm print_env`

The result is ok:
```
The env vars are as follows.
a: b
c: d
The args are as follows.
test.wasm
print_env
```

But if I call `print_env` using wasmedge_sys:
```rust
use wasmedge_sys::{Config, Vm};
use std::path::Path;

fn main() {
    let mut config = Config::create().unwrap();
    config.wasi(true);

    let mut vm = Vm::create(Some(config), None).unwrap();

    // get default wasi module
    let mut wasi_module = vm.wasi_module_mut().unwrap();
    // init the default wasi module
    wasi_module.init_wasi(
        Some(vec!["abc", "123"]),
        Some(vec!["a=b"]),
        Some(vec![]),
    );  

    let wasm_path = Path::new("/home/test.wasm");
    let _ = vm.load_wasm_from_file(wasm_path);
    let _ = vm.validate();
    let _ = vm.instantiate();

    println!("{:?}", vm.run_function("print_env", vec![]));
}
```
I got:
```
The env vars are as follows.
The args are as follows.


Ok([])
```

Envs has not been passed in, and the two empty output lines showed that the two args had been passed in without content.

**Comment by apepkuss** [comment]
Hi @DarumaDocker 

Thanks for your report. Could you please attach `test.wasm` you used in your example here? Thanks!

**Comment by hydai** [comment]
Hi @apepkuss 
The `std::getenv` will not get the ENVS which is inside WASI component. You should have a wasm program using the WASI function to get the envs.

**Comment by apepkuss** [comment]
@hydai Got it, thanks for the reply! 

@DarumaDocker Please reference the reply from @hydai. If any further concerns, please comment below. Thanks!

**Comment by hydai** [comment]
> @hydai Got it, thanks for the reply!
> 
> @DarumaDocker Please reference the reply from @hydai. If any further concerns, please comment below. Thanks!

No. I mean your test code is not correct. `std::cout << ...` cannot print the result, because the `InitWASI` will not inject anything into your host environment. You should have a `getenv` inside your rust (which is compiled to the wasm later) to print the info.

**Comment by q82419** [comment]
Hi @apepkuss ,

The WasmEdge C API of initializing the WASI performs the behavior correctly.
Please refer to the PR https://github.com/WasmEdge/WasmEdge/pull/1607 for explanation.
Thanks.

**Comment by apepkuss** [comment]
> 

@q82419 Many thanks for helping check the CAPI, and also the detailed explanation. Thanks again!
