### ISSUE TITLE
Create a demo: k8s+crun+wasmedge+wasi-nn

### ISSUE THREAD

**Issue by hydai** [WasmEdge/WasmEdge#1598]
## Motivation

Currently, WasmEdge makes the extensions become plugins. We need to build a complete example for demonstrating the full functionalities of leveraging the k8s, crun, wasmedge, and wasi-nn extension, which can show that manages the AI inference service inside the wasm-based images.

## Details

This demo should base on the previous k8s+crun+wasmedge example, which can run a simple wasm+wasi application and run an HTTP server.

**Comment by yeongjukang** [comment]
@hydai can you assign this to me?

**Comment by hydai** [comment]
Fixed: https://github.com/second-state/wasmedge-containers-examples/tree/main/k8s_containerd_wasi_nn

**Comment by yeongjukang** [comment]
@hydai 
My apalogy, I totally forgot about this..
