### ISSUE TITLE
WasmEdge may fail to execute, due to the brewllvm is updated to 14.0.6

### ISSUE THREAD

**Issue by hydai** [WasmEdge/WasmEdge#1605]
### Current State

If users use `llvm@13`, then our pre-built macos binary is fine. However, if users update their llvm version from 13.0.1 to 14.0.6, then they may receive the following error:

```
dyld[92073]: Symbol not found: __ZN4llvm11PassBuilder17OptimizationLevel2O0E
  Referenced from: /Users/hydai/workspace/tmp/WasmEdge-0.10.0-Darwin/bin/wasmedgec
  Expected in: /usr/local/Cellar/llvm/14.0.6/lib/libLLVM.dylib
[1]    92073 abort      ./wasmedgec
```

The reason is that our WasmEdge is linking to 13.0.1:

```
./wasmedgec:
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
	/usr/local/opt/llvm/lib/libLLVM.dylib (compatibility version 1.0.0, current version 13.0.1)
	/usr/local/opt/llvm/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1.0.0)
```

### Expected

To avoid such a problem happening again, we should find a way to make WasmEdge on macos use statically linking to llvm.

## Environment

- Hardware Architecture: Intel and M1 model
- Operating system: MacOS

## Steps to Reproduce

Just download the previous pre-built binaries and execute it.

**Comment by q82419** [comment]
Resolved by #1749
