### ISSUE TITLE
[Installer] Design a plugin installation option

### ISSUE THREAD

**Issue by q82419** [WasmEdge/WasmEdge#1606]
## Motivation

For the WasmEdge 0.10.1-alpha.1 and after version, we supported the `WASI-NN` with OpenVINO plugin:
[WasmEdge-plugin-wasi_nn-openvino-0.10.1-alpha.1-ubuntu20.04_x86_64.tar.gz](https://github.com/WasmEdge/WasmEdge/releases/download/0.10.1-alpha.1/WasmEdge-plugin-wasi_nn-openvino-0.10.1-alpha.1-ubuntu20.04_x86_64.tar.gz)
Therefore the installer should help to install the plugin shared library into `.wasmedge/lib/wasmedge` folder.

## Details

Please design a flag to support the plugin installation. Such as `--plugin=wasi_nn_openvino`.
There's only one plugin supported now and only on linux, and we may add more plugins before the 0.11.0 version.

**Comment by SAtacker** [comment]
Hi, @q82419 Thank you for this. On it.

**Comment by hydai** [comment]
Hi @SAtacker 
Since we may have more and more plugins in the future release, do you have any idea about how to manage them?
AFAIK, we add new options to extend the current plugin installations, not sure if this mechanism will become more complex when the number of plugins grows.

My rough idea (open for discussion):
Maybe we can maintain a manifest (in `ini` format or any format which is friendly for shell script). This manifest contains at least `plugin name`, `plugin URL`, `plugin supported platforms`, `install by default`, and `the dependencies of the plugins`. And we can just update this manifest once there are any plugin updates or releases. The installer can use this manifest to fetch and download for users.
Not sure if this idea is too complex, seems like it will be a package management system.

**Comment by SAtacker** [comment]
> Hi @SAtacker Since we may have more and more plugins in the future release, do you have any idea about how to manage them? AFAIK, we add new options to extend the current plugin installations, not sure if this mechanism will become more complex when the number of plugins grows.
> 
> My rough idea (open for discussion): Maybe we can maintain a manifest (in `ini` format or any format which is friendly for shell script). This manifest contains at least `plugin name`, `plugin URL`, `plugin supported platforms`, `install by default`, and `the dependencies of the plugins`. And we can just update this manifest once there are any plugin updates or releases. The installer can use this manifest to fetch and download for users. Not sure if this idea is too complex, seems like it will be a package management system.

Yes, it's becoming like a package manager. Your idea sounds nice to me. I think we can implement a simple parser for this using bash. The file extension can be anything as long as it is a text file. We have to decide the fields. I like the fields you have suggested, `name`. `URL`, `platforms`, `default yes/no`, and `dependencies`.

1. What can dependencies be? another plugin or some library that has to be downloaded using the system package manager?
2. How will the users update this manifest if it is fetched from WasmEdge/master? Should we provide a custom manifest option too?

**Comment by SAtacker** [comment]
Did we consider a python (2.x, 3.x) script for installation? It'll be more powerful and easier to develop. Although it will add python as an installation dependency. But at the same time, we can use it for Windows and non-unix-like systems too as long as it supports python. This could be side work I can do.

**Comment by hydai** [comment]
> 1. What can dependencies be? another plugin or some library that has to be downloaded using the system package manager?

Take WASI-NN with OpenVINO as an example, our plugin doesn't contain the OpenVINO dependency IIRC. And the OpenVINO is installed by users themselves via another install script from Intel. I am not sure if this is a good way to do it: if there is any dependency required by the plugin, the owner of the plugin should provide scripts for installing and uninstalling the related dependencies,  unless users can have an option to ask us/owner of the plugin to install their ones (like we previous do for the `--ignore-brew` option).

> 2. How will the users update this manifest if it is fetched from WasmEdge/master? Should we provide a custom manifest option too?

Maybe it would be like the `cargo.toml` or `pip freeze > requirements.txt`. So people can have the default one from our release tarball or the latest master branch. However, they can modify it by passing the custom manifest to our installer.

**Comment by hydai** [comment]
> Did we consider a python (2.x, 3.x) script for installation? It'll be more powerful and easier to develop. Although it will add python as an installation dependency. But at the same time, we can use it for Windows and non-unix-like systems too as long as it supports python. This could be side work I can do.

Yup, using a scripting language makes sense. What's the minimum requirement if we want users to execute the python script? Is this a default package installed in any distro? I found that `brew` uses `bash` + `ruby`. https://github.com/Homebrew/install

**Comment by SAtacker** [comment]
> > Did we consider a python (2.x, 3.x) script for installation? It'll be more powerful and easier to develop. Although it will add python as an installation dependency. But at the same time, we can use it for Windows and non-unix-like systems too as long as it supports python. This could be side work I can do.
> 
> Yup, using a scripting language makes sense. What's the minimum requirement if we want users to execute the python script? Is this a default package installed in any distro? I found that `brew` uses `bash` + `ruby`. https://github.com/Homebrew/install

I can't find any minimum requirements for python but as long as it is not a resource-constrained embedded system python should work. Regarding default availability, I found this https://unix.stackexchange.com/questions/24802/on-which-unix-distributions-is-python-installed-as-part-of-the-default-install#:~:text=Ubuntu%20has%20had%20Python%20installed,with%20Python%20installed%20by%20default.

**Comment by hydai** [comment]
> I can't find any minimum requirements for python but as long as it is not a resource-constrained embedded system python should work. Regarding default availability, I found this https://unix.stackexchange.com/questions/24802/on-which-unix-distributions-is-python-installed-as-part-of-the-default-install

Sounds acceptable. But what's their version? 2 or 3? Or we can have a python2&3 compatible one?

cc @juntao I would like to invite Michael to join this discussion.

**Comment by SAtacker** [comment]
We can write for both 2 & 3 versions. We will use futures module [ref](https://stackoverflow.com/questions/7075082/what-is-future-in-python-used-for-and-how-when-to-use-it-and-how-it-works)

**Comment by SAtacker** [comment]
However, after reading through its docs, I don't understand how it'll help us manage our plugins. It'll still require scripts to install.

**Comment by SAtacker** [comment]
I have seen the following material:
- https://stackoverflow.com/questions/6318809/how-do-i-grab-an-ini-value-within-a-shell-script
- https://github.com/albfan/bash-ini-parser

I don't think it's a good idea.
Reasons:
1. It'll evaluate the `ini` file. There are a few comments on how dangerous it can be. For example an `ini` file can contain a variable `var=malicious_command` which will get sourced into the script and I don't know if we can tackle such circumstances. To put it simply I am not a security expert and whether this is unsafe to what extent is unknown. A simple judgement says that it's not a good option.
2. Using awk could be a solution but it's not a convenient option.

That being said, how shall we proceed?

CC @juntao @hydai

**Comment by hydai** [comment]
Hi @SAtacker 
Could you add the `--plugin=wasi_nn_openvino` to our bash installer? Just want to make sure the current installer can install the wasi-nn plugin first. However, the `bash` will be replaced soon.

Currently, `python` is my first choice. I would like to migrate our current installer from `bash` to `python`. And we have to ensure that this new installer will need to run in some pretty old systems, say centos 7. So we should use `python 2/3` compatible grammar.

I would like to have the following stages for the migration process:
1. Re-write the installer/uninstall with python, we can use `brew` as our golden example, which is still a simple bash script but invokes the ruby script.
2. Design the new manifest schema to handle the plugin information, including (Just a draft version, open for discussion)
  2.1. `name`: `wasi-nn-openvino`, `WasmEdgeProcess`
  2.2. `URL`: `URL to the installed tarball`
  2.3. `description`: `blah blah blah`
  2.4. `homepage`: `https://example.com`
  2.5. `wasmedge compatible version`: `>=0.10`, `<=0.9.1`
  2.6. `preinstall`: `maybe a preinstall script to setup the dependencies`
  2.7. `postinstall`: `export some environment variables or something`
  2.8. `postuninstall`: `remove its dependencies`
  2.9. `architure`: `x86_64`, `aarch64`
  2.10. `platform`: `linux`, `macos`, `windows`
  2.11. `default installed`: true/false
3. IIRC, python has the native support for JSON. Not sure if there is any other built-in format we can use?
4. After finalizing the `2. section`, we can go ahead for the implementation part.

But we still need to have a consensus on this decision.

cc @juntao

**Comment by juntao** [comment]
I agree that we can use Python for installer. Thanks

**Comment by SAtacker** [comment]
> Hi @SAtacker 
> Could you add the `--plugin=wasi_nn_openvino` to our bash installer? Just want to make sure the current installer can install the wasi-nn plugin first. However, the `bash` will be replaced soon.
> 
> Currently, `python` is my first choice. I would like to migrate our current installer from `bash` to `python`. And we have to ensure that this new installer will need to run in some pretty old systems, say centos 7. So we should use `python 2/3` compatible grammar.
> 
> I would like to have the following stages for the migration process:
> 1. Re-write the installer/uninstall with python, we can use `brew` as our golden example, which is still a simple bash script but invokes the ruby script.
> 2. Design the new manifest schema to handle the plugin information, including (Just a draft version, open for discussion)
>   2.1. `name`: `wasi-nn-openvino`, `WasmEdgeProcess`
>   2.2. `URL`: `URL to the installed tarball`
>   2.3. `description`: `blah blah blah`
>   2.4. `homepage`: `https://example.com`
>   2.5. `wasmedge compatible version`: `>=0.10`, `<=0.9.1`
>   2.6. `preinstall`: `maybe a preinstall script to setup the dependencies`
>   2.7. `postinstall`: `export some environment variables or something`
>   2.8. `postuninstall`: `remove its dependencies`
>   2.9. `architure`: `x86_64`, `aarch64`
>   2.10. `platform`: `linux`, `macos`, `windows`
>   2.11. `default installed`: true/false
> 3. IIRC, python has the native support for JSON. Not sure if there is any other built-in format we can use?
> 4. After finalizing the `2. section`, we can go ahead for the implementation part.
> 
> But we still need to have a consensus on this decision.
> 
> cc @juntao 

Thanks for a well detailed answer. Okay then I'll get started on the bash plugin. You shall have it before today's meeting.
