### ISSUE TITLE
Integrating bindgen into WasmEdge Rust SDK 

### ISSUE THREAD

**Issue by chenyukang** [WasmEdge/WasmEdge#1612]
## Motivation

For daily development, string is a convenient/must way to pass parameters.
I notice there are memory examples in SDK sample directory, but no string examples.
Maybe integrating bindgen into SDK?

## Details

https://github.com/second-state/wasmedge-bindgen/tree/main/host
I'm not sure it's suitable, but from my dev experiences, I need to add bindgen.

**Comment by apepkuss** [comment]
Hi @chenyukang, 
Thanks for the feedback. The issue you mention here is one of the most valuable features for Rust SDK. According to our current plan, we'd like to support more parameter types based on the `Interface Types proposal`. We'll sync up with you once it's ready. Thanks again!
