### ISSUE TITLE
Drop support for manylinux1 images in the 0.11.0 release

### ISSUE THREAD

**Issue by hydai** [WasmEdge/WasmEdge#1622]
## Motivation

The manylinux1 image is deprecated and dropped on January 1st, 2022. Reference: https://github.com/pypa/manylinux/issues/994

It will become harder to maintain this image by our side. To simply the situation, we would like to drop the manylinux1 support.

## Details

- [ ] The manylinux1 image which is built successfully last time will be kept. However, we don't update it on 0.11.0 and after.
- [ ] Bump the building environment from manylinux1 to manylinux2010, including all related projects and tools.
- [ ] Remove the manylinux1 related information from the WasmEdge book and any other documents.

cc @q82419

**Comment by q82419** [comment]
manylinux1 is removed on WasmEdge-image 0.10.1-alpha.3.
