### ISSUE TITLE
curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash 失败

### ISSUE THREAD

**Issue by jubao4415198** [WasmEdge/WasmEdge#1628]
输入指令: sudo curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash

输出：
fatal: 无法访问 'https://github.com/second-state/WasmEdge-tensorflow.git/'：GnuTLS recv error (-54): Error in the pull function.
Detected Linux-x86_64
curl: (35) OpenSSL SSL_connect: 连接被对方重设 in connection to [raw.githubusercontent.com:443](http://raw.githubusercontent.com:443/)
No path provided
Installing in /home/mky/.wasmedge
WasmEdge Installation at /home/mky/.wasmedge
Fetching WasmEdge-0.10.0
/tmp/wasmedge.160 ~/test
curl: (56) OpenSSL SSL_read: error:0A000126:SSL routines::unexpected eof while reading, errno 0

    Please see --help
    If issue perists make a trace using -V and submit it to
https://github.com/WasmEdge/WasmEdge/issues/new?assignees=&labels=&template=bug_report.md

**Comment by jubao4415198** [comment]
环境：win11 wsl2 ubuntu22.04LTS

**Comment by juntao** [comment]
Do you have VPN enabled to connect to URLs outside of the GFW?

**Comment by jubao4415198** [comment]
> 您是否启用了 VPN 以连接到 GFW 之外的 URL？

是的，我现在把vpn关掉试一下，稍后再回复您结果

**Comment by jubao4415198** [comment]
> 您是否启用了 VPN 以连接到 GFW 之外的 URL？
我把vpn关了以后 就会报这个错误
 输入：udo curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash
输出：curl: (7) Failed to connect to raw.githubusercontent.com port 443 after 2 ms: 拒绝连接
于是，我尝试用更改本地hosts文件，指定DNS解析ip
sudo vi  /etc/hosts
205.251.192.181 raw.githubusercontent.com
140.82.113.4  github.com
结果
输入：sudo curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash
输出：curl: (28) Failed to connect to raw.githubusercontent.com port 443 after 133025 ms: 连接超时
有人遇到过和我一样的问题吗？请求大家帮助

**Comment by jubao4415198** [comment]
> Do you have VPN enabled to connect to URLs outside of the GFW?

**Comment by jubao4415198** [comment]
> > Do you have VPN enabled to connect to URLs outside of the GFW?

解决办法：1.下载对应的脚本拆解脚本指令，分步骤完成目的
2.开一个海外的服务器

**Comment by alabulei1** [comment]
@jubao4415198  Thanks for your report and sharing solutions. Just want to let you know I have renamed your issue so that more users could know about this issue.  Let me know if you have any questions.
