### ISSUE TITLE
Add option to disable executing (potentially malicious) AOT code

### ISSUE THREAD

**Issue by richyliu** [WasmEdge/WasmEdge#1631]
## Motivation

Currently, `wasmedge` and any of its API functions (i.e. `WasmEdge_VMRunWasmFromFile`) will execute any AOT compiled sections in the wasm file. This poses a significant security risk, as malicious code could be inserted into the AOT section.

## Details

I propose a flag for `wasmedge` and a separate set of API functions that do not run AOT compiled code.

## Appendix

In the README, it states,
> The most important use case for WasmEdge is to safely execute user-defined or community-contributed code as plug-ins in a software product (e.g., SaaS, software-defined vehicles, edge nodes, or even blockchain nodes).

It seems like injecting arbitrary AOT section code is a trivial way to bypass any webassembly sandboxing. Please correct me if my understanding is not correct or if this behavior is intended (in which case, I would suggest adding more prominent alerts about the security implications).

**Comment by hydai** [comment]
Hi @richyliu 

Thanks for reporting this. I think we can have a flag to disable the automatically loaded AOT sections from an unknown given universal wasm format.
One possible situation is that users want to execute a wasm file with interpreter mode, however, they use a universal wasm format received from a malicious developer, and then the bad thing happens.


I will create a PR to fix this. Thanks.
