### ISSUE TITLE
Thread panicked error in wasmedge_http_req

### ISSUE THREAD

**Issue by 2019zhou** [WasmEdge/WasmEdge#1636]
I am using wasmedge_http_req (https://github.com/second-state/wasmedge_http_req)

After the successful build, I run `wasmedge get.wasm`
Then, I got the error.

```jsx
thread 'main' panicked at 'called Result::unwrap() on an Err value: IO(Error { kind: Unsupported, message: "operation not supported on this platform" })'
```

According to https://radu-matei.com/blog/tensorflow-inferencing-wasi/, the possible reason is that wasmedge does not support thread. 

However, I have no idea how to solve this problem.

ubuntu 18.04
wasmedge_http_req 0.9.0

**Comment by alabulei1** [comment]
Thanks for reporting. Please track #1633 for the progress.
