### ISSUE TITLE
Cannot use `wasmedge_http_req` to `POST` data into dapr sidecar

### ISSUE THREAD

**Issue by Ren-ZY** [WasmEdge/WasmEdge#1652]
When I try to `POST` json data into dapr sidecar using url `http://localhost:3500/v1.0/state/statestore/post`，
it turns out  to be:
```
{"errorCode":"ERR_DIRECT_INVOKE","message":"failed getting app id either from the URL path or the header dapr-app-id"}
```
maybe something wrong with this url or something wrong with the `POST` method in `wasmedge_http_req`

**Comment by 2019zhou** [comment]
plz assign to me.

**Comment by 2019zhou** [comment]
I follow the official docs for Dapr. https://docs.dapr.io/getting-started/get-started-api/#step-2-save-state
And The data can be successfully posted in http://localhost:3500/v1.0/state/statestore by the following code. 
```
use std::convert::TryFrom;
use wasmedge_http_req::{request::{Request, Method, HttpVersion}, uri::Uri};


fn main() {
    let uri = Uri::try_from("http://localhost:3500/v1.0/state/statestore").unwrap();
    let mut writer = Vec::new(); //container for body of a response
    const body: &[u8] = br#"[{ "key": "name", "value": "Bruce"}]"#;
    // println!("{:?}", String::from_utf8_lossy(body));

    let response = Request::new(&uri)
        .method(Method::POST)
        .version(HttpVersion::Http11)
        .header("Content-Length", &body.len())
        .header("Content-Type", "application/json")
        .body(body)
        .send(&mut writer)
        .unwrap();

}

```

**Comment by 2019zhou** [comment]
With [L-jasmine‘s pull request](https://github.com/second-state/wasmedge_http_req/pull/8) @L-jasmine,  data is now successfully posted.

**Comment by hydai** [comment]
Because the issue is resolved. I am closing it.
