### ISSUE TITLE
Debuging poll_oneoff.

### ISSUE THREAD

**Issue by MediosZ** [WasmEdge/WasmEdge#1653]
I am trying to implementing async io utilizing `poll_oneoff`.
And it works for projects like `tokio` and `mio`.
However, when I port `hyper` another project based on `tokio`, I get an error when I call `poll` with subscriptions.
``` 
Os { code: 28, kind: InvalidInput, message: "Invalid argument" }
```
Any suggestions about how to debug this?

**Comment by juntao** [comment]
Can you create a clean test case that reproduces this error? Thanks

**Comment by MediosZ** [comment]
Maybe I can publish my fork of `hyper` and the error will show up when runing the examples.

**Comment by juntao** [comment]
Can you add @L-jasmine to your repo? He can help reviewing it. Thanks.

**Comment by MediosZ** [comment]
Closing this because the error is caused by `wasmedge_wasi_socket`.
Move there.
