### ISSUE TITLE
[Feature] To support user-defined error code used in host functions in WasmEdge

### ISSUE THREAD

**Issue by apepkuss** [WasmEdge/WasmEdge#1659]
## Motivation

The current version of WasmEdge only supports the pre-defined error code for runtime, but the user-defined error codes used in host functions are not supported. 

## Details

According to our previous investigation on `WasmEdge v0.9.x`, we found that the error handling design (shown in the snapshot below) only considers the exceptional cases that the runtime could run into. 

<img width="537" alt="image" src="https://user-images.githubusercontent.com/4726889/179680274-26a7bd5a-f6c7-4fbf-b15a-16e5abd93589.png">

Such a design cannot handle the error code defined in host functions by users. For example, we can create a host function with the following Rust function, which contains three user-defined error codes. When we intended to "trigger" these error codes, the runtime cannot return the expected error codes; instead, the runtime handles the errors as "Terminated" (the runtime error code is 1). When the error code 1 is returned to the Rust layer, the "receiver" in `wasmedge-sys` cannot distinguish who really caused the issue.

<img width="477" alt="image" src="https://user-images.githubusercontent.com/4726889/179682981-52da14aa-b35a-4f7f-b3c9-6499a0bce8c6.png">

We present a prototype for solving the issue here. The key step is to support distinguishing between error codes for runtime error and user-defined error. For example, we prototyped an independent object named `MyError` (shown in the snapshot below), which can achieve the goal of distinguishing the two cases.

<img width="536" alt="image" src="https://user-images.githubusercontent.com/4726889/179685983-f924e40a-f367-4e46-a67d-1f19f2535190.png">

In our prototype, we verified that the idea can work correctly, and the Rust bindings can get the returned error code and the error source. The prototype can be found [here](https://github.com/apepkuss/WasmEdge-1/tree/feat_types_hostfunc_error).

**Comment by hydai** [comment]
@q82419 @ibmibmibm Looks like this is a breaking API. Will it break any external API like C API or Plugin System?
If not, we can schedule it into 0.10.2. Otherwise, we should make it in 0.11.
