### ISSUE TITLE
Increase the code coverage of inode-linux.cpp

### ISSUE THREAD

**Issue by alabulei1** [WasmEdge/WasmEdge#1669]
## Motivation

According to the codecov report, we should increase [inode-linux.cpp](https://github.com/WasmEdge/WasmEdge/blob/master/lib/host/wasi/inode-linux.cpp)

## Appendix

[Codecov report for inode-linux.cpp](https://app.codecov.io/gh/WasmEdge/WasmEdge/blob/master/lib/host/wasi/inode-linux.cpp)

**Comment by batunpc** [comment]
I'm investigating this

**Comment by alabulei1** [comment]
> I'm investigating this

Great! Would you like to take it? I could assign it to you. Much appreciated.

**Comment by batunpc** [comment]
@alabulei1 I am using m1 chip OSX and still trying to adapt to the project. Currently I am able to build the project but I believe the file mentioned `inode-linux.cpp` is specifically written for Linux (i.e. WASMEDGE_OS_LINUX). Do I need linux environment for writing tests ?

**Comment by alabulei1** [comment]
> @alabulei1 I am using m1 chip OSX and still trying to adapt to the project. Currently I am able to build the project but I believe the file mentioned `inode-linux.cpp` is specifically written for Linux (i.e. WASMEDGE_OS_LINUX). Do I need linux environment for writing tests ?

@hydai  Could help answer this question?

**Comment by hydai** [comment]
Yes, you should have a Linux environment to test it. Because some of the system functions between Linux and OSX are not the same. So I suggest that you should have a container to run the Linux env and do the stuff inside the env.

**Comment by Vishal-Chdhry** [comment]
Hi! may I pick this up?
