### ISSUE TITLE
Increase the code coverage of linux.h

### ISSUE THREAD

**Issue by alabulei1** [WasmEdge/WasmEdge#1670]
## Motivation

According to the codedcov report, we should increase [linux.h](https://github.com/WasmEdge/WasmEdge/blob/master/lib/host/wasi/linux.h)

## Appendix

[Codecov report for linux.h](https://app.codecov.io/gh/WasmEdge/WasmEdge/blob/master/lib/host/wasi/linux.h)

**Comment by Mr-akami** [comment]
@alabulei1 
Hi! may I pick this up? This is my first time to try contribute WasmEdge.

Now I couldn't find the test file of the `linux.h` even though there is some coverage. Could you tell me where?
If there is no test file, I create it.

**Comment by hydai** [comment]
Hi @Mr-akami 

1. Some of the sections can be covered by other functions.
2. There is no standalone test file for this. You can create a new one under `test/host/wasi`.
