### ISSUE TITLE
exec container process `/wasi_example_main.wasm`: Exec format error

### ISSUE THREAD

**Issue by GreyBalloonYU** [WasmEdge/WasmEdge#1675]
## Description
I want to run a simple WebAssembly app by CRI-O and crun (https://wasmedge.org/book/en/kubernetes/cri/crio.html#run-a-simple-webassembly-app), but it suddenly exits, and when check the container's log, it outputs:
```
exec container process `/wasi_example_main.wasm`: Exec format error
```
Even I follow https://wasmedge.org/book/en/kubernetes/demo/wasi.html to build a wasm app image, it's still useless.
### Current State
I cannot use CRI-O and crun to run a wasm app, but running an ordinary container like busybox by CRI-O and crun, or just running a standalone wasm app like wasi_example_main.wasm by wasmedge, is no problem.

### Expected
The expect result is in https://wasmedge.org/book/en/kubernetes/cri/crio.html#run-a-simple-webassembly-app.

## Environment
A VMware virtual machine in my laptop.
The OS in this VMware virtual machine:
```
$ uname -a
Linux ubuntu-2004-server-0 5.4.0-122-generic #138-Ubuntu SMP Wed Jun 22 15:00:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
```
crun version:
```
$ crun -V
crun version 1.5
commit: 54ebb8ca8bf7e6ddae2eb919f5b82d1d96863dea
spec: 1.0.0
+SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
```
cri-o version:
```
$ crio -v
crio version 1.21.7
Version:       1.21.7
GitCommit:     283ec410c082bf91304bbf6f5d5bf1c6490a0e3d
GitTreeState:  clean
BuildDate:     2022-05-17T17:38:58Z
GoVersion:     go1.15.2
Compiler:      gc
Platform:      linux/amd64
Linkmode:      dynamic
```
wasmedge version:
```
$ wasmedge -v
wasmedge version 0.10.0
```

- Hardware Architecture: x86\_64
- Operating system: Ubuntu 20.04

BTW, my laptop OS is windows10, and it also runs a WSL2 which OS is ubuntu 20.04 simultaneously.

## Steps to Reproduce
just follow https://wasmedge.org/book/en/kubernetes/container/crun.html and https://wasmedge.org/book/en/kubernetes/cri/crio.html#run-a-simple-webassembly-app to install crun and cri-o and run a wasm app.

**Comment by hydai** [comment]
Thanks for reporting this. I am going to reproduce it on the Ubuntu platform.

**Comment by GreyBalloonYU** [comment]
I have found the answer.
I should install a crun binary with WasmEdge support (https://wasmedge.org/book/en/kubernetes/container/crun.html):
```
./configure --with-wasmedge
```
But I actually install a crun binary as follows, it's wrong:
```
./configure
```
After install crun correctly, the wasm app can be run by cri-o and crun:
```
$ crun -V
crun version 1.5
commit: 54ebb8ca8bf7e6ddae2eb919f5b82d1d96863dea
spec: 1.0.0
+SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +WASM:wasmedge +YAJL
```

**Comment by hydai** [comment]
Awesome! Thanks.
