### ISSUE TITLE
Non-WasmEdge symbols leaked in the libwasmedge_c.so symbol table

### ISSUE THREAD

**Issue by paravoid** [WasmEdge/WasmEdge#1678]
### Current State

Despite `-fvisibility=hidden -fvisibility-inlines-hidden` being passed to the build (through `cmake/Helper.cmake`'s `CXX_VISIBILITY_PRESET`), several symbols from lld and std seem to be exposed on the dynamic symbol table.

### Expected

Only `WasmEdge_*` are exported.

## Environment

- Hardware Architecture: x86\_64
- Operating system: Debian sid
- C++ Compiler version: g++ 11.2.0
- CMake version: 3.23.2
- CMake flags: -DCMAKE_BUILD_TYPE=Release
- Boost version: 1.74.0

## Steps to Reproduce

```shell
podman run --rm -it debian:sid  # or another way to run on a clean Debian system
apt update
apt install --no-install-recommends \
    git ca-certificates build-essential debhelper \
    cmake libboost-all-dev libspdlog-dev llvm-14-dev liblld-14-dev
git clone https://github.com/WasmEdge/WasmEdge/ && cd WasmEdge
git checkout 43868961858b5956ae703359e1fe522013f50aa2
mkdir -p build && cd build
cmake -DCMAKE_BUILD_TYPE=Release .. && make -j8
# list dynamic symbol table
nm --defined-only -gDC lib/api/libwasmedge_c.so | grep -c lld:  # non-zero
# alternatively:
dpkg-gensymbols -v0.10.0 -plibwasmedge-c0 -elib/api/libwasmedge_c.so -O- | c++filt | grep -c lld:  # non-zero
```

**Comment by hydai** [comment]
Thanks for raising this issue. We will check this.

**Comment by paravoid** [comment]
Thank you for working on this! I still see some unrelated symbols being exported, this time from the std:: namespace, as well as from the llvm:: namespace :(

Instead of playing whack-a-mole with `--exclude-libs`, what do you think about using a version script. For example, I had success with this (while reverting #1756):
```diff
diff --git a/lib/api/CMakeLists.txt b/lib/api/CMakeLists.txt
index bd01b62a..f42219b7 100644
--- a/lib/api/CMakeLists.txt
+++ b/lib/api/CMakeLists.txt
@@ -92,6 +92,15 @@ if(WASMEDGE_BUILD_SHARED_LIB)
     MSVC_RUNTIME_LIBRARY "MultiThreadedDLL"
   )
 
+  set_target_properties(wasmedge_c_shared
+    PROPERTIES
+    LINK_DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/../libwasmedge.map
+  )
+  target_link_options(wasmedge_c_shared
+    PUBLIC
+    "SHELL:-Wl,--version-script=${CMAKE_CURRENT_SOURCE_DIR}/../libwasmedge.map"
+  )
+
   target_link_libraries(wasmedge_c_shared
     PRIVATE
     wasmedgeCAPI
diff --git a/lib/libwasmedge.map b/lib/libwasmedge.map
new file mode 100644
index 00000000..9b65809b
--- /dev/null
+++ b/lib/libwasmedge.map
@@ -0,0 +1,7 @@
+{
+  global:
+    WasmEdge*;
+
+  local:
+    *;
+};
```

Neither versions scripts nor CMake are my expertise, so take that all with a grain of salt :)

**Comment by paravoid** [comment]
Oh and something else: the `std::` symbols will remain in `nm`'s output as undefined, i.e. to be dynamically resolved. I think there is a question to be asked on whether you want downstream users to also link with libstdc++. This may be especially undesired given this is a C ABI library that may be used by C program. At least g++ has a `-static-libstdc++`, which may be desired here, but I didn't experiment much with it.

**Comment by hydai** [comment]
Reopen it so we can continue tracking this issue.
The goal of this one is to make sure the `libwasmedge.so` exports the symbols with the `wasmedge_` prefix.

Due to the current design, some of the symbols are still exported for the plugin system. We should revise the related design to improve this one.

**Comment by hydai** [comment]
Hi @paravoid 
Thanks for rechecking this. We found that the leaked symbols are generated using GCC with the open LTO option. That's why I don't figure it out when using Clang. And @ibmibmibm is opening a PR to fix it now.
