### ISSUE TITLE
[CLI tool] `v128` return value is not handled

### ISSUE THREAD

**Issue by Zhangyx24** [WasmEdge/WasmEdge#1704]
## Description
When executing the `func1` function in main.wasm, wasmer print `79228162514264337593543950336`, but wasmedge print nothing.
The main.wasm is uploaded as main.txt since it is not supported to upload a file end with .wasm.

[main.txt](https://github.com/WasmEdge/WasmEdge/files/9228709/main.txt)

### Current State
print nothing 

### Expected

print `79228162514264337593543950336`

## Environment

- Hardware Architecture: ( x86\_64)
- Operating system: (Ubuntu 20.04 and macOS 10) the problem occur both in ubuntu and macOS 

## Steps to Reproduce
In wasmer:  `wasmer --enable-all main.wasm -i func1`
In wasmedge : `wasmedge --reactor --enable-all main.wasm func1` or `wasmedgec main.wasm main-edge.wasm; wasmedge --reactor --enable-all main-edge.wasm func1`

**Comment by hydai** [comment]
Hi @Zhangyx24 

Thanks for reporting this issue. According to my test, I found that WasmEdge only handles some native types of the return value including `I32`, `I64`, `F32`, and `F64`. Ref: https://github.com/WasmEdge/WasmEdge/blob/master/lib/driver/tool.cpp#L352-L372

However, the return value of this program is `v128`, so the result is not handled. Will have a PR to fix this. Thanks!

**Comment by Zhangyx24** [comment]
Thanks for your answer !
