### ISSUE TITLE
[Compiler] The mask is missed on the shift operands

### ISSUE THREAD

**Issue by Zhangyx24** [WasmEdge/WasmEdge#1707]
## Steps to reproduce
Execute the `main` function in the wasm file which is uploaded as test.txt.

[test.txt](https://github.com/WasmEdge/WasmEdge/files/9229121/test.txt)

（1）`wasmedge --reactor --enable-all test.wasm main` or
 （2）`wasmedgec test.wasm test.so` `wasmedge --reactor --enable-all test.so main`

## Expected result
65
other runtime print 65 and  wasmedge in (1)print 65

## Actual result
(2)print 66

**Comment by hydai** [comment]
Hi @Zhangyx24 
Thanks for reporting this. We will check this and get you back.

**Comment by hydai** [comment]
Also, may I ask what version of wasmedge you used?

**Comment by Zhangyx24** [comment]
The version is 0.9.1

**Comment by hydai** [comment]
Thanks for reporting, this should be fixed by #1710. We will ship it in the next release.

**Comment by Zhangyx24** [comment]
Thanks for your answer !
