### ISSUE TITLE
How to import a host function(without return value) in the C api ?

### ISSUE THREAD

**Issue by Zhangyx24** [WasmEdge/WasmEdge#1716]
## Motivation
[test.txt](https://github.com/WasmEdge/WasmEdge/files/9241084/test.txt)
The test.wat is uploaded as test.txt.
[test-c.txt](https://github.com/WasmEdge/WasmEdge/files/9241102/test-c.txt)
The test.c is uploaded as test-c.txt.

## Details
However using `gcc -o test test.c -lwasmedge_c` failed and print:
test.c: In function ‘main’:
test.c:67:3: error: ‘HostFType’ undeclared (first use in this function)
   67 |   HostFType = WasmEdge_FunctionTypeCreate(ParamList1, 1, NULL, 0);
      |   ^~~~~~~~~
test.c:67:3: note: each undeclared identifier is reported only once for each function it appears in
test.c:69:31: error: ‘HostFType1’ undeclared (first use in this function)
   69 |   WasmEdge_FunctionTypeDelete(HostFType1);
      |                               ^~~~~~~~~~
test.c:72:39: error: incompatible types when initializing type ‘enum WasmEdge_ValType’ using type ‘void *’
   72 |   enum WasmEdge_ValType ReturnList2 = NULL;
      |                                       ^~~~
test.c:73:58: error: incompatible type for argument 3 of ‘WasmEdge_FunctionTypeCreate’
   73 |   HostFType = WasmEdge_FunctionTypeCreate(ParamList2, 2, ReturnList2, 0);
      |                                                          ^~~~~~~~~~~
      |                                                          |
      |                                                          enum WasmEdge_ValType
In file included from test.c:6:
.....

## question
How to import the host function without any return value?

**Comment by hydai** [comment]
Just set the `NULL` and `0`
https://github.com/WasmEdge/WasmEdge/blob/409b1b09a049e8805b44a5f6840c7a74a783e939/test/api/hostfunc_c.c#L133-L142

According to your error message, looks like you don't define the `HostFType` before you used it.

**Comment by Zhangyx24** [comment]
Thanks a lot !
