### ISSUE TITLE
[CI] Enable markdownlint for our documents

### ISSUE THREAD

**Issue by hydai** [WasmEdge/WasmEdge#1723]
## Motivation

When using markdown as a document format, we encountered the format linting issue. Just like #1721 
To fix this, we should enable a markdown linter to make all of the markdowns are checked before it gets merged.

## Details

Create a new workflow that will use [`markdownlint`](https://github.com/DavidAnson/markdownlint/) to check if the markdown is well formatted.

**Comment by HeZean** [comment]
Hi, may I work on it?

**Comment by hydai** [comment]
Sure thing. Just assigned to you.
