### ISSUE TITLE
[Rust SDK]function `wasmedge_sdk::memory::write`

### ISSUE THREAD

**Issue by EmisonLu** [WasmEdge/WasmEdge#1728]
Currently, the `memory` type of wasmedge-sdk, has the method [`write()`](https://github.com/WasmEdge/WasmEdge/blob/master/bindings/rust/wasmedge-sdk/src/externals/memory.rs#L94), which is able to safely write contents of a buffer to this `memory` at the given offset. However, the method [`write()`](https://github.com/WasmEdge/WasmEdge/blob/master/bindings/rust/wasmedge-sdk/src/externals/memory.rs#L94) requires taking ownership of the input parameter `data`, which is undesirable in some cases.

For example, if `data` is of type `Arc<Vec<...>>`, we might need the following way to call this function: `memory.write(unsafe { &*Arc::into_raw(data)}.clone(), offset)` (perhaps there is a much better way to implement this).

These cases can be avoided if the parameter `data` passed in by [`write()`](https://github.com/WasmEdge/WasmEdge/blob/master/bindings/rust/wasmedge-sdk/src/externals/memory.rs#L94) is a reference.

When using wasmedge-sys, since there is no `write()` API, I use the following as an alternative.

```rust
fn write_memory(memory: &mut Memory, offset: usize, buffer: &[u8]) -> Result<(), anyhow::Error> {
    let base_ptr_mut: *mut u8 = memory
        .data_pointer_mut(0, 1)
        .expect("failed to returns the mut data pointer to the memory.");

    unsafe { std::slice::from_raw_parts_mut(base_ptr_mut, (memory.size() * 64 * 1024) as usize) }
        .get_mut(offset..)
        .and_then(|s| s.get_mut(..buffer.len()))
        .unwrap()
        .copy_from_slice(buffer);

    Ok(())
}
```

@apepkuss Whether the argument passed in can be a `&[]`? Please take a look at this question, thank you very much!

**Comment by apepkuss** [comment]
@EmisonLu Thanks for your feedback. We'll consider your request carefully and make improvements to the related API. Thank you so much!
