### ISSUE TITLE
[Rust] Please support std::io::Error

### ISSUE THREAD

**Issue by L-jasmine** [WasmEdge/WasmEdge#1739]
https://github.com/WasmEdge/WasmEdge/blob/4f3ffe1579205d54d16466a3d68fbf1136433efc/bindings/rust/wasmedge-types/src/error.rs#L58-L67

**Comment by apepkuss** [comment]
@L-jasmine Could you please provide some necessary information of this feature request, like motivation? So that other users can get to know why you need it. Thanks a lot!

**Comment by dannypsnl** [comment]
@hydai I guess the issue should be transferred to https://github.com/WasmEdge/wasmedge-rust-sdk?

**Comment by hydai** [comment]
Yes. @L-jasmine Please move this issue to the Rust SDK.
