### ISSUE TITLE
LFX Workspace: Support serialize and deserialize in WasmEdge

### ISSUE THREAD

**Issue by q82419** [WasmEdge/WasmEdge#1741]
## Motivation

WasmEdge can load the WASM binary and instantiate it into WASM module instances for execution. In a use case, we need to serialize the loaded WASM data structure back into the encoded WASM binary or deserialize the serialized one into the WASM data structure in WasmEdge. With the serializing mechanism, WasmEdge can control the WASM binary wisely such as caching or snapshotting.

## Specification

1. Design and implement a function to serialize the loaded WASM data structure in WasmEdge back into the WASM binary.
2. Design and implement a function to deserialize the serialized WASM binary back into the loaded WASM data structure in WasmEdge.
3. Support the binary segment removal when serializing.
4. Optimize the deserializing mechanism.

## Pre-test

Anyone who wants to apply for this LFX mentorship, please make sure to submit the pre-test in #1751 .

## Appendix

1. [Serialize and deserialize in Wasm C API proposal](https://github.com/WebAssembly/wasm-c-api/blob/c9d31284651b975f05ac27cee0bab1377560b87e/example/serialize.c#L54-L63)
2. [WebAssembly binary format](https://webassembly.github.io/spec/core/binary/index.html)

**Comment by carrycooldude** [comment]
Hey @q82419 , I would love to work on this, any tips for getting started?

> Also, I also have an understanding of WASM as I gave a talk at Open Source Summit Japan on[ WASM using TFJS](https://youtu.be/AypjRRQf8bw) and I am also a contributor at [Tensorflow.js at wasm-backend](https://github.com/tensorflow/tfjs/pull/4826)
> Can you tell me where to start?

**Comment by alabulei1** [comment]
> Hey @q82419 , I would love to work on this, any tips for getting started?
> 
> > Also, I also have an understanding of WASM as I gave a talk at Open Source Summit Japan on[ WASM using TFJS](https://youtu.be/AypjRRQf8bw) and I am also a contributor at [Tensorflow.js at wasm-backend](https://github.com/tensorflow/tfjs/pull/4826)
> > Can you tell me where to start?

Hey @carrycooldude Thanks for your interest. We'd like to ask you to complete a pretest for better collaboration. See details #1751. Also, you should apply for this task on https://mentorship.lfx.linuxfoundation.org/project/da1162c6-2aaf-496f-9f23-a96a3e52c277.

**Comment by alabulei1** [comment]
> We'd like to ask you to complete a pretest for better collaboration. See details #1751

Hi @Onyx2406, 
Thanks for your application. We'd also like to ask you to complete a pretest for better collaboration. See details https://github.com/WasmEdge/WasmEdge/discussions/1751

**Comment by zeel-pathak** [comment]
Hey @q82419, I would love to work on this issue under LFX mentorship.

And already working on #1751, Would love to be working with WasmEdge and the community.
