### ISSUE TITLE
LFX Workspace: Porting OpenVINO on multiple platforms for the WASI-NN proposal in WasmEdge

### ISSUE THREAD

**Issue by q82419** [WasmEdge/WasmEdge#1742]
## Motivation

The [OpenVINO](https://www.intel.com/content/www/us/en/developer/tools/openvino-toolkit/download.html) official release supports various platforms. WasmEdge supports the WASI-NN proposal with OpenVINO backend now, but only in Ubuntu 20.04. In this project, we want to porting and integrating the OpenVINO installation for the multiple platforms such as MacOS, Windows, or manylinux with the WasmEdge WASI-NN plugin.

## Specification

1. Survey the installation guide of OpenVINO runtime on Windows, MacOS, and various Linux platforms.
2. Implement the automatically installation script on CI for the multiple platforms.
3. Integrate the OpenVINO runtime installation in WasmEdge.

## Pre-test

Anyone who wants to apply for this LFX mentorship, please make sure to submit the pre-test in #1752  .

## Appendix

1. [OpenVINO runtime official release](https://www.intel.com/content/www/us/en/developer/tools/openvino-toolkit/download.html)
2. [OpenVINO Wiki](https://github.com/openvinotoolkit/openvino/wiki)

**Comment by monalisha31** [comment]
Hi @q82419 , I would like apply for this project under the LFX mentorship program. This project seems interesting. Looking forward to contributing to it.

**Comment by alabulei1** [comment]
> Hi @q82419 , I would like apply for this project under the LFX mentorship program. This project seems interesting. Looking forward to contributing to it.

@monalisha31  Thanks for your interest. We'd like to ask you to complete a pretest for better collaboration. See details #1752.

**Comment by spencergotowork** [comment]
> > Hi @q82419 , I would like apply for this project under the LFX mentorship program. This project seems interesting. Looking forward to contributing to it.
> 
> @monalisha31 Thanks for your interest. We'd like to ask you to complete a pretest for better collaboration. See details #1752.

Thanks for your guidance, I finished it but haven't received a reply to my comments or emails yet. What should I do next? I'm not sure if my mentor has been changed.

**Comment by spencergotowork** [comment]
@alabulei1  Thanks for your guidance, I finished it but haven't received a reply to my comments or emails yet. What should I do next? I'm not sure if my mentor has been changed.
