### ISSUE TITLE
[CLI] Unexpected error message popped out but the functionality is fine

### ISSUE THREAD

**Issue by Zhangyx24** [WasmEdge/WasmEdge#1744]
## Description
The wasm file is to rename a file.
[uutils-wat.txt](https://github.com/WasmEdge/WasmEdge/files/9305497/uutils-wat.txt)
In the same directory, make a directory named `dir`, and create a file named `foo` in `dir`.

### Steps to reproduce 
(1)`wasmedge --dir=./dir uutils.wasm mv dir/foo dir/bar`
(2)`wasmedgec uutils.wasm uutils.so` and
`wasmedge --dir=./dir uutils.so mv dir/foo dir/bar`
 
### Expected result
Rename `foo` to `bar`.

#### (1) 
Successfully rename file `foo` to `bar` and print nothing
#### (2) 
Successfully rename file `foo` to `bar` but print error, but don't print what the error is 
<img width="710" alt="截屏2022-08-11 上午10 22 18" src="https://user-images.githubusercontent.com/28601300/184054437-f37cfd13-a48d-4dd6-91f0-ff64484c32b0.png">

## Environment
WasmEdge 0.9.1

- Hardware Architecture: (x86\_64)
- Operating system: ( ubuntu20.04)

**Comment by hydai** [comment]
@LFsWang 
Could you check this? Maybe related to your previous issue.

**Comment by LFsWang** [comment]
Maybe same as #1378

**Comment by Zhangyx24** [comment]
Thanks for your reply !
