### ISSUE TITLE
LFX Workspace: Node API support for WasmEdge QuickJS

### ISSUE THREAD

**Issue by juntao** [WasmEdge/WasmEdge#1745]
## Motivation

The [WasmEdge QuickJS runtime](https://wasmedge.org/book/en/dev/js.html) is a secure, fast, and lightweight JavaScript runtime for cloud-native applications. Compared with more established JavaScript runtimes like Nodejs and Deno, the WasmEdge QuickJS runtime provides runtime isolation and security at a very low overhead.

In order for WasmEdge QuickJS to be more widely adopted, it needs to support [nodejs](https://wasmedge.org/book/en/dev/js/nodejs.html) applications. WasmEdge QuickJS already supports [NPM and CJS modules](https://wasmedge.org/book/en/dev/js/npm.html).

## Details

Through the WasmEdge QuickJS extension mechanism, developers can create new JavaScript APIs for the runtime using languages like JavaScript and Rust. We have already started the work to support all Nodejs APIs. Your tasks are as follows.

* Learn the [JavaScript](https://wasmedge.org/book/en/dev/js/modules.html) and [Rust](https://wasmedge.org/book/en/dev/js/rust.html) extension mechanism for WasmEdge QuickJS.
* Study how Nodejs APIs such as `http` and `querystring` are supported today.
* Contribute to the Nodejs APIs that are currently missing.
* Create CI tests and examples for the APIs you contributed. 

## Appendix

* [Introduction to WasmEdge QuickJS](https://wasmedge.org/book/en/dev/js.html)
* [NodeJS API support in WasmEdge QuickJS](https://wasmedge.org/book/en/dev/js/nodejs.html) | [Tracking issue](https://github.com/WasmEdge/WasmEdge/issues/1535)
* [Extend WasmEdge QuickJS using JavaScript](https://wasmedge.org/book/en/dev/js/modules.html)
* [Extend WasmEdge QuickJS using Rust](https://wasmedge.org/book/en/dev/js/rust.html)

**Comment by 0saurabh0** [comment]
@juntao I would love to work on this, any tips for getting started.

**Comment by juntao** [comment]
> @juntao I would love to work on this, any tips for getting started.


👍👍👍

As a "test", may I ask you implement a nodejs api in WasmEdge QuickJS using our Rust API? You could choose any of the unimplemented nodejs api here:

https://github.com/WasmEdge/WasmEdge/issues/1535

Thank you.

**Comment by ritamgit-alt** [comment]
Hi, this project seems interesting, I would love to work on this, so where should I get started?

**Comment by alabulei1** [comment]
> Hi, this project seems interesting, I would love to work on this, so where should I get started?

Hi @ritamgit-alt , Thanks for your interest. We'd like to ask you to complete a pretest for better collaboration. See details #1753.

**Comment by 0saurabh0** [comment]
> 
> As a "test", may I ask you implement a nodejs api in WasmEdge QuickJS using our Rust API? You could choose any of the unimplemented nodejs api here:
> 
> #1535

I'm on it.

**Comment by 0saurabh0** [comment]
Can all node.js APIs be implemented in Javascript alone ?
If so where Rust will come in use ?

**Comment by juntao** [comment]
> Can all node.js APIs be implemented in Javascript alone ?
> 
> If so where Rust will come in use ?

Please refer to issue #1535 

We discussed which APIs can be done in JS and which must be done in Rust.

**Comment by Chinwendu20** [comment]
Hi, I would like to work on the project. Can I get an issue to prove myself as well?

**Comment by ConnectBhawna** [comment]
Hi, This project seems interesting to me would love to learn more about the project with the mentor.
