### ISSUE TITLE
[Docs] `hello.wasm` output is not the same as the docs describes

### ISSUE THREAD

**Issue by wudenggang** [WasmEdge/WasmEdge#1762]
## Description
文档错误，hello.wasm输出不一致。
https://github.com/WasmEdge/WasmEdge/blob/master/examples/wasm/README.md

### Current State
![文档错误](https://user-images.githubusercontent.com/3587832/185754702-24c43d7a-9f1d-4067-a205-26e29ef6b442.png)

显示输出和实际输出不一致：
### Expected
![文档错误2](https://user-images.githubusercontent.com/3587832/185754717-372cee05-ccdb-465e-b1ed-307a08f7a238.png)

**Comment by q82419** [comment]
It should be `hello` but not `hello.wasm`.
Do you want to create a PR to contribute this?
Thanks.
