### ISSUE TITLE
wasmedge can't recognize argument in GBK encoding correctly

### ISSUE THREAD

**Issue by wudenggang** [WasmEdge/WasmEdge#1779]
## Environment
- Hardware Architecture:  x86\64 
- Operating system: window10
- cmd test hello.wasm，with Chinese word argument，but panic。
![hello](https://user-images.githubusercontent.com/3587832/186190645-c7a6d886-21e8-4f38-88b6-cb728574039d.png)

**Comment by wudenggang** [comment]
Windows cmd default use local encoding method，for example GBK like me. But I don't known how to process it automatically.

**Comment by hydai** [comment]
IIRC, the current implementation supports Unicode(UTF-8), just like the above screenshots. Currently, having no ideas for fixing this, because I am not familiar with GBK encoding.

**Comment by bxb100** [comment]
How about using System properties, let the user set their input encoding
