### ISSUE TITLE
[Plugin] Refine some implementations in the httpsreq module

### ISSUE THREAD

**Issue by hydai** [WasmEdge/WasmEdge#1788]
Hi @2019zhou 
I found some issues that I didn't identify in the previous review:

1. All of the pointers should be checked whether it's nullptr or not before use: https://github.com/WasmEdge/WasmEdge/blob/master/plugins/httpsreq/httpsreqfunc.cpp#L32
2. You should return the `error code` in the return value instead of using `exit`. Because the `exit` will terminate the whole program, it will make the wasmedge exit without any other error handling: https://github.com/WasmEdge/WasmEdge/blob/master/plugins/httpsreq/httpsreqfunc.cpp#L49
3. Same as `abort`: https://github.com/WasmEdge/WasmEdge/blob/master/plugins/httpsreq/httpsreqfunc.cpp#L73

Please fix them. Thanks.

_Originally posted by @hydai in https://github.com/WasmEdge/WasmEdge/issues/1763#issuecomment-1225216156_

**Comment by q82419** [comment]
Please refine with #1768

**Comment by q82419** [comment]
4. For the logging such as https://github.com/WasmEdge/WasmEdge/blob/master/plugins/httpsreq/httpsreqfunc.cpp#L54 , please transfer to use `spdlog::error()`.
5. For the body string https://github.com/WasmEdge/WasmEdge/blob/master/plugins/httpsreq/httpsreqfunc.cpp#L110 , it seems like you never use the `Env.BodyStr`. It's not necessary to copy the buffer into std::string.

**Comment by 2019zhou** [comment]
ok
