### ISSUE TITLE
[CI] Reduce the building time of OpenWrt

### ISSUE THREAD

**Issue by hydai** [WasmEdge/WasmEdge#1790]
## Motivation

The GitHub runners have only 20 slots. However, we found that the workflow of building WasmEdge on the OpenWrt will take almost two hours, which is totally insane. This occupies the most time in our whole workflow. The reason is that the workflow builds not only WasmEdge itself but also the whole OpenWrt. Since the base commit is exactly the same in each build, we should figure out a way to create a cache or something to reduce the total building time.

## Appendix

The workflow file for OpenWrt: https://github.com/WasmEdge/WasmEdge/blob/master/.github/workflows/build_for_openwrt.yml
An example run: https://github.com/WasmEdge/WasmEdge/actions/runs/2915634679

**Comment by Sush-Dew** [comment]
@hydai Could you assign this issue to me? I am a beginner and this issue seems a good first issue to resolve.

**Comment by RahulSurwade08** [comment]
Hey, I would love to work on this issue. How can i get started?

**Comment by hydai** [comment]
> Hey, I would love to work on this issue. How can i get started?

Hi @RahulSurwade08,
You can refer to this workflow: https://github.com/WasmEdge/WasmEdge/blob/master/.github/workflows/build_for_openwrt.yml
And then try to figure out which part can be done inside a docker image, so we can use that image instead of building the whole openwrt again and again to reduce the building time.

**Comment by hydai** [comment]
> @hydai Could you assign this issue to me? I am a beginner and this issue seems a good first issue to resolve.

Hi @Sush-Dew 
Are you still on this? If not, I would like to transfer the assignee to @RahulSurwade08

**Comment by Sush-Dew** [comment]
Hi! @hydai I am working on this issue. please let me do it.

**Comment by dracoooooo** [comment]
Hi @hydai, can you assign this to me? I would like to use [cache action](https://github.com/actions/cache) to save OpenWrt artifact to reduce the building time.
