### ISSUE TITLE
[Rust] `CallingFrame` in wasmedge-sdk

### ISSUE THREAD

**Issue by EmisonLu** [WasmEdge/WasmEdge#1816]
When I use the `CallingFrame` in `wasmedge-sdk`, for example with the method `module_instance()`, the return type is `wasmedge_sys::Instance`, rather than `wasmedge_sdk::Instance`. Such inconsistencies will undoubtedly cause problems and be detrimental to the use of the `wasmedge-sdk`.

@apepkuss Please take a look at this question, thank you very much!

**Comment by apepkuss** [comment]
@EmisonLu Thanks for the feedback. Yes, you're right, the `module_instance` method returns a module instance of `wasmedge_sys::Instance` type, as the `CallingFrame` instance you're using is `automatically` returned by `runtime` and passed as an argument to host functions in [wraper_fn](https://github.com/WasmEdge/WasmEdge/blob/master/bindings/rust/wasmedge-sys/src/instance/function.rs#L14-L69) function. In essence, therefore, the `CallingFrame` type is a low-level object defined in `wasmedge-sys`, and all the operations on this type are also low-level. To make the usage much clearer and avoid misunderstanding with the high-level counterpart, we'll add more doc comments for explaining the case.

**Comment by EmisonLu** [comment]
When using `wasmedge-sdk`, should a high-level `Instance`, `Memory`, etc. be returned when performing operations on the `CallingFrame` in the host function? Is it possible to make a high-level wrapper around `CallingFrame` and its methods in `wasmedge-sdk`? Thanks a lot!
