### ISSUE TITLE
run rust binding demo error

### ISSUE THREAD

**Issue by xunfeng1980** [WasmEdge/WasmEdge#1820]
### Current State

/Users/lux/.cargo/bin/cargo build --color=always --message-format=json-diagnostic-rendered-ansi --bin wasmedge-demo --manifest-path /Users/lux/src/github.com/xunfeng1980/rust-study/crates/wasmedge-demo/Cargo.toml
   Compiling wasmedge-sys v0.9.0
error[E0425]: cannot find function, tuple struct or tuple variant `WasmEdge_CompilerCompileFromBuffer` in module `ffi`
    --> /Users/lux/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/wasmedge-sys-0.9.0/src/compiler.rs:102:24
     |
102  |               check(ffi::WasmEdge_CompilerCompileFromBuffer(
     |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: a function with a similar name exists: `WasmEdge_CompilerCompile`
     |
    ::: /Users/lux/src/github.com/xunfeng1980/rust-study/target/debug/build/wasmedge-sys-043900d69375825d/out/wasmedge.rs:2258:5
     |
2258 | /     pub fn WasmEdge_CompilerCompile(
2259 | |         Cxt: *mut WasmEdge_CompilerContext,
2260 | |         InPath: *const ::std::os::raw::c_char,
2261 | |         OutPath: *const ::std::os::raw::c_char,
2262 | |     ) -> WasmEdge_Result;
     | |_________________________- similarly named function `WasmEdge_CompilerCompile` defined here

error[E0412]: cannot find type `WasmEdge_CallingFrameContext` in module `ffi`
   --> /Users/lux/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/wasmedge-sys-0.9.0/src/frame.rs:12:33
    |
12  |     pub(crate) ctx: *const ffi::WasmEdge_CallingFrameContext,
    |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: a struct with a similar name exists: `WasmEdge_ConfigureContext`
    |
   ::: /Users/lux/src/github.com/xunfeng1980/rust-study/target/debug/build/wasmedge-sys-043900d69375825d/out/wasmedge.rs:964:1
    |
964 | pub struct WasmEdge_ConfigureContext {
    | ------------------------------------ similarly named struct `WasmEdge_ConfigureContext` defined here

error[E0412]: cannot find type `WasmEdge_CallingFrameContext` in module `ffi`
   --> /Users/lux/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/wasmedge-sys-0.9.0/src/frame.rs:16:43
    |
16  |     pub(crate) fn create(ctx: *const ffi::WasmEdge_CallingFrameContext) -> Self {
    |                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: a struct with a similar name exists: `WasmEdge_ConfigureContext`
    |
   ::: /Users/lux/src/github.com/xunfeng1980/rust-study/target/debug/build/wasmedge-sys-043900d69375825d/out/wasmedge.rs:964:1
    |
964 | pub struct WasmEdge_ConfigureContext {
    | ------------------------------------ similarly named struct `WasmEdge_ConfigureContext` defined here

error[E0425]: cannot find function, tuple struct or tuple variant `WasmEdge_CallingFrameGetExecutor` in module `ffi`
  --> /Users/lux/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/wasmedge-sys-0.9.0/src/frame.rs:22:33
   |
22 |         let ctx = unsafe { ffi::WasmEdge_CallingFrameGetExecutor(self.ctx) };
   |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `ffi`

error[E0425]: cannot find function, tuple struct or tuple variant `WasmEdge_CallingFrameGetModuleInstance` in module `ffi`
  --> /Users/lux/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/wasmedge-sys-0.9.0/src/frame.rs:42:33
   |
42 |         let ctx = unsafe { ffi::WasmEdge_CallingFrameGetModuleInstance(self.ctx) };
   |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `ffi`

error[E0425]: cannot find function, tuple struct or tuple variant `WasmEdge_CallingFrameGetMemoryInstance` in module `ffi`
  --> /Users/lux/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/wasmedge-sys-0.9.0/src/frame.rs:66:33
   |
66 |         let ctx = unsafe { ffi::WasmEdge_CallingFrameGetMemoryInstance(self.ctx, idx) };
   |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `ffi`

error[E0412]: cannot find type `WasmEdge_CallingFrameContext` in module `ffi`
   --> /Users/lux/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/wasmedge-sys-0.9.0/src/instance/function.rs:17:33
    |
17  |     call_frame_ctx: *const ffi::WasmEdge_CallingFrameContext,
    |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: a struct with a similar name exists: `WasmEdge_ConfigureContext`
    |
   ::: /Users/lux/src/github.com/xunfeng1980/rust-study/target/debug/build/wasmedge-sys-043900d69375825d/out/wasmedge.rs:964:1
    |
964 | pub struct WasmEdge_ConfigureContext {
    | ------------------------------------ similarly named struct `WasmEdge_ConfigureContext` defined here

error[E0425]: cannot find function, tuple struct or tuple variant `WasmEdge_ResultGen` in module `ffi`
    --> /Users/lux/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/wasmedge-sys-0.9.0/src/instance/function.rs:62:22
     |
62   |                 ffi::WasmEdge_ResultGen(ffi::WasmEdge_ErrCategory_UserLevelError, code)
     |                      ^^^^^^^^^^^^^^^^^^ help: a function with a similar name exists: `WasmEdge_ResultOK`
     |
    ::: /Users/lux/src/github.com/xunfeng1980/rust-study/target/debug/build/wasmedge-sys-043900d69375825d/out/wasmedge.rs:1331:5
     |
1331 |     pub fn WasmEdge_ResultOK(Res: WasmEdge_Result) -> bool;
     |     ------------------------------------------------------- similarly named function `WasmEdge_ResultOK` defined here

error[E0425]: cannot find value `WasmEdge_ErrCategory_UserLevelError` in module `ffi`
  --> /Users/lux/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/wasmedge-sys-0.9.0/src/instance/function.rs:62:46
   |
62 |                 ffi::WasmEdge_ResultGen(ffi::WasmEdge_ErrCategory_UserLevelError, code)
   |                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `ffi`

error[E0425]: cannot find function, tuple struct or tuple variant `WasmEdge_ResultGen` in module `ffi`
    --> /Users/lux/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/wasmedge-sys-0.9.0/src/instance/function.rs:65:22
     |
65   |                 ffi::WasmEdge_ResultGen(ffi::WasmEdge_ErrCategory_WASM, code)
     |                      ^^^^^^^^^^^^^^^^^^ help: a function with a similar name exists: `WasmEdge_ResultOK`
     |
    ::: /Users/lux/src/github.com/xunfeng1980/rust-study/target/debug/build/wasmedge-sys-043900d69375825d/out/wasmedge.rs:1331:5
     |
1331 |     pub fn WasmEdge_ResultOK(Res: WasmEdge_Result) -> bool;
     |     ------------------------------------------------------- similarly named function `WasmEdge_ResultOK` defined here

error[E0425]: cannot find value `WasmEdge_ErrCategory_WASM` in module `ffi`
  --> /Users/lux/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/wasmedge-sys-0.9.0/src/instance/function.rs:65:46
   |
65 |                 ffi::WasmEdge_ResultGen(ffi::WasmEdge_ErrCategory_WASM, code)
   |                                              ^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `ffi`

error[E0412]: cannot find type `WasmEdge_CallingFrameContext` in module `ffi`
   --> /Users/lux/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/wasmedge-sys-0.9.0/src/instance/function.rs:75:33
    |
75  |     call_frame_ctx: *const ffi::WasmEdge_CallingFrameContext,
    |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: a struct with a similar name exists: `WasmEdge_ConfigureContext`
    |
   ::: /Users/lux/src/github.com/xunfeng1980/rust-study/target/debug/build/wasmedge-sys-043900d69375825d/out/wasmedge.rs:964:1
    |
964 | pub struct WasmEdge_ConfigureContext {
    | ------------------------------------ similarly named struct `WasmEdge_ConfigureContext` defined here

error[E0425]: cannot find function, tuple struct or tuple variant `WasmEdge_ResultGen` in module `ffi`
    --> /Users/lux/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/wasmedge-sys-0.9.0/src/instance/function.rs:121:22
     |
121  |                 ffi::WasmEdge_ResultGen(ffi::WasmEdge_ErrCategory_UserLevelError, code)
     |                      ^^^^^^^^^^^^^^^^^^ help: a function with a similar name exists: `WasmEdge_ResultOK`
     |
    ::: /Users/lux/src/github.com/xunfeng1980/rust-study/target/debug/build/wasmedge-sys-043900d69375825d/out/wasmedge.rs:1331:5
     |
1331 |     pub fn WasmEdge_ResultOK(Res: WasmEdge_Result) -> bool;
     |     ------------------------------------------------------- similarly named function `WasmEdge_ResultOK` defined here

error[E0425]: cannot find value `WasmEdge_ErrCategory_UserLevelError` in module `ffi`
   --> /Users/lux/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/wasmedge-sys-0.9.0/src/instance/function.rs:121:46
    |
121 |                 ffi::WasmEdge_ResultGen(ffi::WasmEdge_ErrCategory_UserLevelError, code)
    |                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `ffi`

error[E0425]: cannot find function, tuple struct or tuple variant `WasmEdge_ResultGen` in module `ffi`
    --> /Users/lux/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/wasmedge-sys-0.9.0/src/instance/function.rs:124:22
     |
124  |                 ffi::WasmEdge_ResultGen(ffi::WasmEdge_ErrCategory_WASM, code)
     |                      ^^^^^^^^^^^^^^^^^^ help: a function with a similar name exists: `WasmEdge_ResultOK`
     |
    ::: /Users/lux/src/github.com/xunfeng1980/rust-study/target/debug/build/wasmedge-sys-043900d69375825d/out/wasmedge.rs:1331:5
     |
1331 |     pub fn WasmEdge_ResultOK(Res: WasmEdge_Result) -> bool;
     |     ------------------------------------------------------- similarly named function `WasmEdge_ResultOK` defined here

error[E0425]: cannot find value `WasmEdge_ErrCategory_WASM` in module `ffi`
   --> /Users/lux/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/wasmedge-sys-0.9.0/src/instance/function.rs:124:46
    |
124 |                 ffi::WasmEdge_ResultGen(ffi::WasmEdge_ErrCategory_WASM, code)
    |                                              ^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `ffi`

error[E0425]: cannot find function, tuple struct or tuple variant `WasmEdge_ModuleInstanceWASIGetNativeHandler` in module `ffi`
    --> /Users/lux/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/wasmedge-sys-0.9.0/src/instance/module.rs:682:18
     |
682  |               ffi::WasmEdge_ModuleInstanceWASIGetNativeHandler(
     |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: a function with a similar name exists: `WasmEdge_ModuleInstanceWASIGetExitCode`
     |
    ::: /Users/lux/src/github.com/xunfeng1980/rust-study/target/debug/build/wasmedge-sys-043900d69375825d/out/wasmedge.rs:2659:5
     |
2659 | /     pub fn WasmEdge_ModuleInstanceWASIGetExitCode(
2660 | |         Cxt: *const WasmEdge_ModuleInstanceContext,
2661 | |     ) -> u32;
     | |_____________- similarly named function `WasmEdge_ModuleInstanceWASIGetExitCode` defined here

error[E0425]: cannot find function, tuple struct or tuple variant `WasmEdge_ResultGetCategory` in module `ffi`
    --> /Users/lux/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/wasmedge-sys-0.9.0/src/utils.rs:44:34
     |
44   |     let category = unsafe { ffi::WasmEdge_ResultGetCategory(result) };
     |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^ help: a function with a similar name exists: `WasmEdge_ResultGetCode`
     |
    ::: /Users/lux/src/github.com/xunfeng1980/rust-study/target/debug/build/wasmedge-sys-043900d69375825d/out/wasmedge.rs:1339:5
     |
1339 |     pub fn WasmEdge_ResultGetCode(Res: WasmEdge_Result) -> u32;
     |     ----------------------------------------------------------- similarly named function `WasmEdge_ResultGetCode` defined here

error[E0531]: cannot find unit struct, unit variant or constant `WasmEdge_ErrCategory_UserLevelError` in module `ffi`
  --> /Users/lux/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/wasmedge-sys-0.9.0/src/utils.rs:54:14
   |
54 |         ffi::WasmEdge_ErrCategory_UserLevelError => Err(WasmEdgeError::User(code)),
   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `ffi`

error[E0531]: cannot find unit struct, unit variant or constant `WasmEdge_ErrCategory_WASM` in module `ffi`
  --> /Users/lux/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/wasmedge-sys-0.9.0/src/utils.rs:55:14
   |
55 |         ffi::WasmEdge_ErrCategory_WASM => gen_runtime_error(code),
   |              ^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `ffi`

error[E0425]: cannot find function, tuple struct or tuple variant `WasmEdge_PluginLoadWithDefaultPaths` in module `ffi`
    --> /Users/lux/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/wasmedge-sys-0.9.0/src/utils.rs:317:19
     |
317  |     unsafe { ffi::WasmEdge_PluginLoadWithDefaultPaths() }
     |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: a function with a similar name exists: `WasmEdge_Plugin_loadWithDefaultPluginPaths`
     |
    ::: /Users/lux/src/github.com/xunfeng1980/rust-study/target/debug/build/wasmedge-sys-043900d69375825d/out/wasmedge.rs:4391:5
     |
4391 |     pub fn WasmEdge_Plugin_loadWithDefaultPluginPaths();
     |     ---------------------------------------------------- similarly named function `WasmEdge_Plugin_loadWithDefaultPluginPaths` defined here

error[E0308]: mismatched types
   --> /Users/lux/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/wasmedge-sys-0.9.0/src/instance/function.rs:225:22
    |
225 |                 Some(wraper_fn),
    |                 ---- ^^^^^^^^^ types differ in mutability
    |                 |
    |                 arguments to this enum variant are incorrect
    |
    = note: expected fn pointer `unsafe extern "C" fn(_, _, *mut WasmEdge_MemoryInstanceContext, _, _, _, _) -> WasmEdge_Result`
                  found fn item `extern "C" fn(_, _, *const [type error], _, _, _, _) -> WasmEdge_Result {wraper_fn}`
note: tuple variant defined here
   --> /Users/lux/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/option.rs:526:5
    |
526 |     Some(#[stable(feature = "rust1", since = "1.0.0")] T),
    |     ^^^^

error[E0308]: mismatched types
   --> /Users/lux/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/wasmedge-sys-0.9.0/src/instance/function.rs:287:22
    |
287 |                 Some(wraper_fn_single),
    |                 ---- ^^^^^^^^^^^^^^^^ types differ in mutability
    |                 |
    |                 arguments to this enum variant are incorrect
    |
    = note: expected fn pointer `unsafe extern "C" fn(_, _, *mut WasmEdge_MemoryInstanceContext, _, _, _, _) -> WasmEdge_Result`
                  found fn item `extern "C" fn(_, _, *const [type error], _, _, _, _) -> WasmEdge_Result {wraper_fn_single}`
note: tuple variant defined here
   --> /Users/lux/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/option.rs:526:5
    |
526 |     Some(#[stable(feature = "rust1", since = "1.0.0")] T),
    |     ^^^^

error: aborting due to 23 previous errors

Some errors have detailed explanations: E0308, E0412, E0425, E0531.
For more information about an error, try `rustc --explain E0308`.
The following warnings were emitted during compilation:
warning: [wasmedge-sys] Use default dir: "/Users/lux/.wasmedge"
error: could not compile `wasmedge-sys` due to 24 previous errors
Process finished with exit code 101
### Expected

it work

## Environment

Darwin luxdeMacBook-Pro.local 22.1.0 Darwin Kernel Version 22.1.0: Mon Aug 15 20:06:40 PDT 2022; root:xnu-8792.40.29.161.2~1/RELEASE_ARM64_T8103 arm64

**Comment by hydai** [comment]
Hi @xunfeng1980 

According to your error msg `error[E0425]: cannot find function, tuple struct or tuple variant WasmEdge_CompilerCompileFromBuffer in module ffi`, it looks like your wasmedge library version is not updated to the latest one. This API is added in the 0.11.0 release. Please check that you have updated the wasmedge version. Thanks.

**Comment by xunfeng1980** [comment]
thx,it work.
