### ISSUE TITLE
[Rust] Pass a pointer to the host func

### ISSUE THREAD

**Issue by EmisonLu** [WasmEdge/WasmEdge#1830]
[`WasmEdge_FunctionInstanceCreateBinding`](https://github.com/WasmEdge/WasmEdge/blob/master/include/api/wasmedge/wasmedge.h#L2245-L2249) has a parameter named data, which is the additional object, such as the pointer to a data structure, to set to this host function context. Should this also be supported in the rust sdk?

@apepkuss Please take a look! Many thanks!

**Comment by apepkuss** [comment]
@EmisonLu Thanks for the feedback. I'll fix the issue asap. Thanks!
