### ISSUE TITLE
AOT codegen type mismatch  

### ISSUE THREAD

**Issue by elliott-wen** [WasmEdge/WasmEdge#1831]
Hi,  LLC reports about a type mismatch issue in the following statement.

https://github.com/WasmEdge/WasmEdge/blob/47f534c64a4648c52ea34418a0751975223a8bff/lib/aot/compiler.cpp#L326

```
IntrinsicsTable(new llvm::GlobalVariable(
            LLModule, IntrinsicsTablePtrTy->getPointerTo(), true,
            llvm::GlobalVariable::ExternalLinkage, nullptr, "intrinsics"))
```
I reckon a more appropriate statement would be 

```
IntrinsicsTable(new llvm::GlobalVariable(
            LLModule, IntrinsicsTablePtrTy, true,
            llvm::GlobalVariable::ExternalLinkage, nullptr, "intrinsics"))
```

The intrinsic table has a type of [i8* x N], and the pointer to the table would be [i8* x N]\*. Therefore the globalVariable should have the type of [i8* x N]**.

Cheers

**Comment by hydai** [comment]
Hi @elliott-wen 
Thanks for reporting this. It should be fixed in #1839
