### ISSUE TITLE
LFX Workspace: Node API support for WasmEdge QuickJS

### ISSUE THREAD

**Issue by Puellaquae** [WasmEdge/WasmEdge#1834]
# Motivation
The [WasmEdge QuickJS runtime](https://wasmedge.org/book/en/dev/js.html) is a secure, fast, and lightweight JavaScript runtime for cloud-native applications. Compared with more established JavaScript runtimes like Nodejs and Deno, the WasmEdge QuickJS runtime provides runtime isolation and security at a very low overhead.

In order for WasmEdge QuickJS to be more widely adopted, it needs to support [nodejs](https://wasmedge.org/book/en/dev/js/nodejs.html) applications. WasmEdge QuickJS already supports [NPM and CJS modules](https://wasmedge.org/book/en/dev/js/npm.html).

# Schedule
- [x] fs, 2 weeks
- [ ] crypto, 3 weeks
- [x] tty & readline, 1 week
- [ ] net & dns, 2 weeks
- [ ] http2 & tls & https, 3 weeks
- [ ] global & error, 1 week
* each module's CI tests and example will be done during its development

# Appendix
* #1745 
* https://github.com/WasmEdge/WasmEdge/issues/1535

**Comment by juntao** [comment]
Great. Thanks. There are few things to note:

1 You can use the Rust crate for `wasi-crypto` to implement the crypto package.

2 Please make sure that all networking APIs (eg `net` and `http`) are non blocking and async.

3 I do not think we have a low level Rust TLS / https library yet. But you can try the [wasmedge_http_req](https://github.com/second-state/wasmedge_http_req) crate to support https. The catch is that it is synchronous-only. 

Thanks.

**Comment by Puellaquae** [comment]
@juntao Support for the fs module has been completed. For the `chown` and `watch` functions, I haven't found the equivalent api in wasi. For the `chmod`, it has equivalent api(https://github.com/WebAssembly/wasi-filesystem/issues/33), but it's unpublished in preview1. So `chown`, `chmod` and `watch` is unsupported. I have used `wasi_ext` feature in rust, which is experimental. So it need nightly rust to compile now.

**Comment by Puellaquae** [comment]
Up to now, most of fs module is implemented and passed the test from nodejs. 

`ReadStream` and `WriteStream` (most of code is from node) only has basic function supported. 
`chmod`, `chown`, `watch` is unsupported for no equivalent api in now wasi-fs. 
`symlink` for dir and `lutimes` is not work well. 
`readlink` and `readpath` is not work in linux for some bug #1993 , while in microsoft's wsl1 it's work. 
As macos, I don't have any macos device and it also doesn't run test in macos on github action.

As test, I used the test from nodejs (https://github.com/nodejs/node/tree/main/test/parallel), and add it to github action. Tests which used unsupported function, had nodejs's undocumented api usage or depended on specific platform and implement is skipped. For unskipped test, it's all passed. By the way, test required `assert` module is also supported.

**Comment by juntao** [comment]
Do you intend to continue working on it and add support for at least the `tty` `readline` `net` and `dns` modules? Thanks

**Comment by Puellaquae** [comment]
I will continue working and finish it.

**Comment by Puellaquae** [comment]
Support for the tty and readline module has been completed. `getWindowSize` and `setRawMode` is unsupported now. Test required assert module is in fs's pr and tty's `ReadStream` and `WriteStream` is extended `net.Socket`, so it will be added soon.

**Comment by hydai** [comment]
The mentorship was finished. Closing this.
Thanks for your contribution @Puellaquae :-)
