### ISSUE TITLE
LFX Workspace: Porting OpenVINO on multiple platforms for the WASI-NN proposal in WasmEdge

### ISSUE THREAD

**Issue by spencergotowork** [WasmEdge/WasmEdge#1840]
## Motivation

The OpenVINO official release supports various platforms. WasmEdge supports the WASI-NN proposal with OpenVINO backend now, but only in Ubuntu 20.04. In this project, we want to porting and integrating the OpenVINO installation for the multiple platforms such as MacOS, Windows, or manylinux with the WasmEdge WASI-NN plugin.

## Schedule

- [x] Survey and test the installation guide of OpenVINO runtime on Windows, MacOS, and various Linux platforms, 1 week.
- [x] Integrate the OpenVINO runtime installation and CI in WasmEdge on manylinux2014 these supported systems , 2 ~ 3 weeks.
- [ ] Integrate the OpenVINO runtime installation and CI in WasmEdge on Windows 10 and Windows 11, 2 ~ 3 weeks.
- [ ] Add CI with OpenVINO as the inference backend plug-in
- [ ] Integrate the OpenVINO runtime installation and CI in WasmEdge on MacOS. (Low priority now), 2 ~ 3 weeks.

## Appendix
- [wasi-nn OpenVINO](https://www.secondstate.io/categories/wasi-nn/)
- [Stable supported versions of OpenVino](https://www.intel.cn/content/www/cn/zh/developer/tools/openvino-toolkit/system-requirements.html)
- https://github.com/WasmEdge/WasmEdge/issues/1742

**Comment by hydai** [comment]
Our tier-one target is `manylinux2014` because this is based on CentOS 7. Please prioritize the workload to make sure this platform is 100% supported first.

**Comment by hydai** [comment]
Hi @spencergotowork 
Just want to know if the OpenVINO on manylinux is finished or not. If not, we should focus on the manylinux first.
The macOS and Windows will be the second tier, doesn't block this issue by these two platforms.
