### ISSUE TITLE
[Installer] Propose the plugin manifest

### ISSUE THREAD

**Issue by hydai** [WasmEdge/WasmEdge#1842]
## Motivation

In the current design, we already provide several pre-built plugins in the release assets. However, there is not a clear way for users to install them easier. Take `WASI-NN` as an example, users need to download the plugin and copy the file into `$HOME/.wasmedge/plugin` by themselves. To simplify the situation, we should provide a clear way for users to identify the plugins' versions and make sure the plugins are compatible with their current WasmEdge version.

To make this happen, I propose a format called `plugin manifest`. This file will ship with every release, it contains the WasmEdge version tag, the name of plugins, the platform we support, the arch we support, the URL to download, and the hash to verify the plugin.

## Details

The format will be in JSON format: 
```json
{
  "wasmedge_version": {
    "prerelease": false,
    "timestamp": "2022-08-08",
    "plugins": [
      {
        "name": "wasi-nn-openvino",
        "version": "0.1.0",
        "triple": {
          "manylinux2014_x86_64": {
            "platform": "manylinux2014",
            "arch": "x86_64",
            "url": "link",
            "checksum": "hash"
          }
        }
      }
    ]
  }
}
```

* `wasmedge_version`: `<string> the release version`, such as `0.11.0`, `0.10.1-alpha.1`, and `0.9.0-rc.1`, etc.
* `prerelease`: `<boolean>`, true if this version is a prerelease such as `alpha`, `beta`, and `rc`; otherwise, false.
* `timestamp`: `<datetime/string>`, such as `"2022-08-27T19:46:21.343959"` , the release date.
* `plugins`: `<array>`, the plugin object.
  * `name`: `<string>`, the plugin name, must be lowercase.
  * `version`: `<string>`, the version of the corresponding plugin.
  * `triple`: `<object: Key<string>, Value<object>>`, the environment triple.
    * `key`: `<string>`, the full triple name such as `manylinux2014_x86_64` or `darwin_arm64`.
    * `platform`: `<string>` the platform name such as `manylinux2014`, `ubuntu20.04`, `darwin`, etc.
    * `arch`: `<string>` the hardware architecture such as `x86_64`, `aarch64`, `arm64`, etc.
    * `url`: `<string>` the URL of the corresponding plugin.
    * `checksum`: `<string>` the hash of the plugin asset.

/cc @SAtacker @ibmibmibm @q82419 
Please take a look. Feel free to give any feedback.

**Comment by SAtacker** [comment]
> In the current design, we already provide several pre-built plugins in the release assets. However, there is not a clear way for users to install them easier. Take WASI-NN as an example, users need to download the plugin and copy the file into $HOME/.wasmedge/plugin by themselves. 

The current installation script handles this.

> To simplify the situation, we should provide a clear way for users to identify the plugins' versions and make sure the plugins are compatible with their current WasmEdge version.
> To make this happen, I propose a format called plugin manifest. This file will ship with every release, it contains the WasmEdge version tag, the name of plugins, the platform we support, the arch we support, the URL to download, and the hash to verify the plugin.

That is very structured. Can we have a script that generates this manifest for every release? This will make it easier to write the parser for this. In fact we can have a script under `utils` directory for this purpose. And it will have both output and parsing for itself. FWIW we can have a separate directory to test the individual functions of both the installer and this manifest generator and decoder.

**Comment by SAtacker** [comment]
Since even python 2 supports json import we don't have to write a complicated one. But we still need tests to ensure that there are no mistakes based on Specs that we decide.

**Comment by hydai** [comment]
Since we are going to have a standalone plugin repository for recording the plugin packages, we would like to have a more structure schema to handle the situation.

In this proposal, we can make the installer can lookup the target platform manifest via a top-level manifest. And the detailed install script can be handled inside the manifest inside the plugin tarball.

Here is the new architecture of the plugin manifest:

The file structure will be:

```
plugins
|- manifest.json
|- <arch_name>
  |- <os_name>
    |- <plugin_name>
      |- <plugin.manifest.json>
|- x86_64
  |- manylinux2014
    |- wasmedge_httpsreq
      |- manifest.json
  |- ubuntu20.04
    |- wasmedge_httpsreq
      |- manifest.json
|- aarch64
  |- manylinux2014
    |- wasmedge_httpsreq
      |- manifest.json
  |- macos
    |- wasmedge_httpsreq
      |- manifest.json
```

So we can have the top level `manifest.json` to record the whole provided plugins with the following format:
```json
{
	[
		{
			"name": "<string> wasmedge_httpsreq",
			"description": "<string> ...",
			"platforms": {
				"<arch_name>": ["os_name"],
				"x86_64": ["manylinux2014", "macos"]
			},
			"conflict": [
				"the name of the conflicting plugin"
			]
		}
	]
}
```

So the installer can have this top-level manifest to identify all plugins and make the users decide which plugins they want to install.

Once the installed plugins are chosen, then the installer can use the generic path `<url>/path/to/plugins/%arch%/%os%/%plugin_name%/manifest.json` to retrieve the real information of the plugins.

And the `manifest.json` inside the `<arch>/<os>/<plugin_name>` will use the following format:

```json
{
	"name": "<string>",
	"url": "<url> the URL to plugin tarball",
	"description": "<string>",
	"signature<optional>": "<string> for verifying the signed tarball",
	"min_version": "<string> 0.10.0, minimum compatible version of wasmedge",
	"version": "<string> 0.1.0, the current version of this plugin",
	"last_updated": "<timestamp>, since developers can add more information of the current plugin without changing any tarball, this is for recording the last updated time.",
	"checksum": {
		"put any checksum you like": "",
		"sha256sum": "",
		"md5sum": "",
	}
}
```

And the content of the plugin tarball should have the following file structures:

```
plugin.tarball
|- libXXX.[so|dyld|dll] # The Plugin shared library
|- manifest.json # The manifest.json
|- ***.xxx
```

Finally, the `manifest.json` inside the tarball should define the following information:
```json
{
	"name": "<string>",
	"min_version": "<string> 0.10.0, minimum compatible version of wasmedge",
	"version": "<string> 0.1.0, the current version of this plugin",

	"preinstall": ["bash a.sh"...],
	"postinstall": [],
	"preuninstall": [],
	"postuninstall": [],
	"preupgrade": [],
	"postupgrade": [],
}
```

cc @ibmibmibm @q82419 @SAtacker 

I would like to hear more feedback from you guys.

**Comment by SAtacker** [comment]
I'll start working on it and let you know. Thanks.

**Comment by hydai** [comment]
I think the manifest is too heavy for us at the current moment. Closing this.
