### ISSUE TITLE
"Exec format error" when using custom KinD image to create pods

### ISSUE THREAD

**Issue by jcuffe** [WasmEdge/WasmEdge#1845]
## Description

I would like to run a WasmEdge HTTP server in Kubernetes. After following the quickstart instructions, I encountered the following OS 28 error when creating a pod in KinD: https://github.com/second-state/wasmedge_wasi_socket/issues/66

Previous experience led me to believe this was due to an old version of WasmEdge, so I followed the KinD quickstart instructions to create a custom image. When attempting to run *any* wasmedge image using those instructions, I encounter an `Exec format error` which is similar to the error I get when attempting to run wasmedge images with an improperly configured CRI.

### Current State

```
❯ kind create cluster --image node-wasmedge
...
You can now use your cluster with:
...

❯ kubectl run -it --rm --restart=Never http-server --image=jcuffe/http-server:latest --annotations="module.wasm.image/variant=compat"
{"msg":"exec container process `/http_server.wasm`: Exec format error","level":"error","time":"2022-09-18T22:57:14.000246110Z"}
pod "http-server" deleted
pod default/http-server terminated (Error)
```

### Expected

Expect the server to start cleanly and listen on port 1234

#### Dockerfile for KinD node
```
FROM ubuntu:22.04 AS builder

WORKDIR /data
RUN DEBIAN_FRONTEND=noninteractive apt update
RUN DEBIAN_FRONTEND=noninteractive apt install -y curl make git gcc build-essential pkgconf libtool libsystemd-dev libprotobuf-c-dev libcap-dev libseccomp-dev libyajl-dev go-md2man libtool autoconf python3 automake
RUN curl https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- -p /usr/local
RUN git clone --single-branch --branch main https://github.com/containers/crun

WORKDIR /data/crun
RUN ./autogen.sh
RUN ./configure --with-wasmedge --enable-embedded-yajl
RUN make

FROM kindest/node:v1.23.0

COPY config.toml /etc/containerd/config.toml
COPY --from=builder /data/crun/crun /usr/local/sbin/runc
COPY --from=builder /usr/local/lib/libwasmedge.so /usr/local/lib/libwasmedge.so

RUN echo "Installing Packages ..." \
   && bash -c 'cat <<< $(jq "del(.hooks.createContainer)" /etc/containerd/cri-base.json) > /etc/containerd/cri-base.json' \
   && ldconfig
```

#### Http server app Dockerfile
```
FROM scratch
ADD http_server.wasm /
CMD ["/http_server.wasm"]
```

#### Buildah command to build image (neither annotation works)
```
sudo buildah build --annotation "module.wasm.image/variant=compat" -t http_server .
sudo buildah build --annotation "module.wasm.image/variant=compat-smart" -t http_server .
```

#### Kubenetes commands
```
❯ kind create cluster --image node-wasmedge
...
You can now use your cluster with:
...

❯ kubectl run -it --rm --restart=Never http-server --image=jcuffe/http-server:latest --annotations="module.wasm.image/variant=compat"
{"msg":"exec container process `/http_server.wasm`: Exec format error","level":"error","time":"2022-09-18T22:57:14.000246110Z"}
pod "http-server" deleted
pod default/http-server terminated (Error)
```

- Hardware Architecture: x64
- Operating system: Ubuntu 20.04

**Comment by juntao** [comment]
@0xE282B0 Could you look into this when you have a chance? Much appreciated!

**Comment by hydai** [comment]
Hi @jcuffe 
Since you are using the latest crun with the newest release of WasmEdge, you need to copy the more shared libraries to your new image:

```
COPY --from=builder /usr/local/lib/libwasmedge.so.0.0.0 /usr/local/lib/libwasmedge.so.0.0.0
COPY --from=builder /usr/local/lib/libwasmedge.so.0 /usr/local/lib/libwasmedge.so.0
COPY --from=builder /usr/local/lib/libwasmedge.so /usr/local/lib/libwasmedge.so
```

**Comment by jcuffe** [comment]
After following the steps above, I saw this error during the ldconfig step of the image build:
```
/sbin/ldconfig.real: /usr/local/lib/libwasmedge.so.0 is not a symbolic link
```

Examining my local files, the file does appear to be a link:
```
❯ ls -al /usr/local/lib/libwasmedge.so*
lrwxrwxrwx 1 root root       16 Sep 12 01:20 /usr/local/lib/libwasmedge.so -> libwasmedge.so.0*
lrwxrwxrwx 1 root root       20 Sep 12 01:20 /usr/local/lib/libwasmedge.so.0 -> libwasmedge.so.0.0.0*
-rwxr-xr-x 1 root root 49463840 Sep 12 01:20 /usr/local/lib/libwasmedge.so.0.0.0*
```

@juntao has suggested in the issue linked in my OP that I use the CRI-O or containerd Github workflows to keep up to date, so I will give that another try. 

@hydai Do you have any tips for setting up this environment locally in a reproducible fashion? I seem to encounter some error due to out of date tooling or configurations every time I attempt to pick up from where I left off the previous weekend, I'm having trouble gaining any momentum. Do you do your development in containers/vms?

Thank you for all the help so far 🙏

**Comment by hydai** [comment]
> @hydai Do you have any tips for setting up this environment locally in a reproducible fashion? I seem to encounter some error due to out of date tooling or configurations every time I attempt to pick up from where I left off the previous weekend, I'm having trouble gaining any momentum. Do you do your development in containers/vms?
> 

I used a container env to do the development. Also, we have used github workflows to make sure the code works. Just like https://github.com/second-state/wasmedge-containers-examples

Since this is in active development, it will need more attention to up to date. Say the SONAME (libwasmedge.so.0.0.0) is for avoiding the out of date configurations, once the version mismatched, the crun will report `libwasmedge.so.0` is not found and fail. If you are interested in this, please refer to this PR: https://github.com/containers/crun/pull/992 . It talks about how we try to make sure the dlopen is using the correct one.

**Comment by jcuffe** [comment]
Thank you for the references! It's exciting to see how far this project has come and the work you're doing to integrate with the crun upstream. I will close this issue since I see the creator of the kind image is aware of the need to update.
