### ISSUE TITLE
Can not run javascript example on wasmedge successfully

### ISSUE THREAD

**Issue by Jeffwan** [WasmEdge/WasmEdge#1857]
## Description

I follow guidance here https://wasmedge.org/book/en/dev/js/quickstart.html
1. download `wasmedge_quickjs.wasm`
2. create a js file `hello.js`

However, following command didn't work. 

```
wasmedge --dir .:. wasmedge_quickjs.wasm hello.js WasmEdge Runtime
ReferenceError: could not load module filename 'os'
```

I tried to build wasmedge-quickjs by myself and it works fine. I feel the folder context is probably the magic here?

### Current State
example doesn't work and build from scratch works

### Expected
os module can be loaded.

## Environment

- Hardware Architecture: (e.g. x86\_64 or aarch64): x86
- Operating system: (e.g. Ubuntu 20.04 or CentOS 7.6): ubuntu:20.04

The following information is optional. Please provide them only if you have built from source.
- C++ Compiler version:
- CMake version:
- CMake flags: (e.g. `-DCMAKE_BUILD_TYPE=Release -DWASMEDGE_BUILD_AOT_RUNTIME=ON`)
- Boost version:

**Comment by juntao** [comment]
As we mentioned in the docs, you will need the `modules` folder from the GitHub repo in your current directory. It contains the JS files to support the nodejs API. Thanks.

**Comment by Jeffwan** [comment]
@juntao Thanks Michael. It works! Seems docs is a little bit unclear. People may feel copy & paste would work. Looks like we have to download the entire project which includes `modules`

**Comment by jaykchen** [comment]
I made it run by removing all 3 occurrences of "__dirname" in main.js, assuming the files needed have all been saved in current directory.

the original code as shown below:
TensorflowLiteSession(
    __dirname + '/lite-model_aiy_vision_classifier_food_V1_1.tflite');
