### ISSUE TITLE
WASI-NN PyTorch Backend supporting in manylinux2014

### ISSUE THREAD

**Issue by q82419** [WasmEdge/WasmEdge#1862]
### Current State

In current status, the `ubuntu 20.04` version of WasmEdge WASI-NN pytorch plugin should use `libtorch-cxx11-abi`, or the test would link failed.
But the `manylinux2014` version should use the `libtorch-pre-cxx11-abi`, because the `cxx11-abi` version uses `GLIBCXX`.

### Expected

Link the `libtorch-pre-cxx11-abi` successfully on `ubuntu 20.04`, or compile the `cxx11-abi` version of libtorch on `manylinux2014`.

## Environment

- Hardware Architecture: x86_64
- Operating system: CentOS 7.6

**Comment by hydai** [comment]
Since the CentOS 7 reaches EOL soon, we don't need to do this anymore.
