### ISSUE TITLE
[docs] Add examples for writing WasmEdge App in C++

### ISSUE THREAD

**Issue by alabulei1** [WasmEdge/WasmEdge#1865]
## Motivation

We already have examples to demonstrate how to write wasmedge apps in C++ for a long time. We should also add this example to the WasmEdge book.

## Appendix

https://github.com/WasmEdge/WasmEdge/tree/master/examples/embed_cxx

**Comment by TheZal** [comment]
Can u please show me which file should i edit with the example? Even a link to an example should be ok! Then I can do it! :)

**Comment by hydai** [comment]
Hi @TheZal 
We don't provide a public C++ header and library currently, however, you can embed WasmEdge C SDK into the C++ project.

Here is a reference document: https://wasmedge.org/book/en/sdk/c.html

However, if you want to build from source, you can refer to this example, which uses cmake to include and find self-built WasmEdge library: https://github.com/WasmEdge/WasmEdge/blob/master/examples/embed_cxx/CMakeLists.txt

**Comment by TheZal** [comment]
Sorry but I didn't understand: for the update of the documentation I shoud add an md file in https://github.com/WasmEdge/WasmEdge/tree/master/docs/book/en/src/sdk/c with the example inside https://github.com/WasmEdge/WasmEdge/tree/master/examples/embed_cxx?

**Comment by hydai** [comment]
The new document for the C++ example should be put inside this folder: https://github.com/WasmEdge/WasmEdge/tree/master/docs/book/en/src/sdk

You can find that we have the following schema:
```
SDK
|- c.md
|- c
  |- *.md
|- cxx.md <- here is the summary
|- cxx
  |- *.md <- here is the example document
```

**Comment by TheZal** [comment]
Perfect, gonna work on that asap! Can u assign it to me?

**Comment by TheZal** [comment]
Not sure is enough for the PR, if I have to do more just tell me :)

**Comment by Vishvsalvi** [comment]
Assign me this task

**Comment by ashutosh887** [comment]
@hydai Please assign me this issue

**Comment by hydai** [comment]
@Sukriti-sood 
Sure. Welcome :-)

**Comment by k3yss** [comment]
Should this issue be marked as complete, I think PR [#145](https://github.com/WasmEdge/docs/pull/145) already addresses this.

**Comment by hydai** [comment]
Hi @k3yss 
Thanks for addressing this. Closing it.
