### ISSUE TITLE
Shipping binary precompiled WASM files is problematic for downstreams

### ISSUE THREAD

**Issue by paravoid** [WasmEdge/WasmEdge#1869]
## Motivation

I'm a Debian Developer and interested in packaging WasmEdge and including it in Debian. (Also [see Debian bug #1003128](https://bugs.debian.org/1003128)). I already have (mostly) working packages.

Debian has strict rules for what can be included in its "main" archive. Among those, is, to put it simply that that every source package must always include the source for every file it ships (as in, the preferred source of modification), and every binary needs to be built from its source, and using only software from Debian.

The WasmEdge tarball right now ships WASM binaries under `examples`, `tests` (and examples/tests of `bindings/rust`). While I can "just" repackage the tarball and remove these, I'd like for this to be the last resort, and to work with you in case we can find some other solution which lets Debian use the upstream tarball as-is.

The good news are that **none of the shipped WASM files seem to be necessary for a default release build** (`cmake -DCMAKE_BUILD_TYPE=Release`).

Finally, note that other distributions may have similar rules, and thus any upstream fix here may be beneficial more broadly than just Debian.

## Details

The shipped WASM files can be split in the following categories:

### Handcrafted WAT, shipped alongside WASM 

These are actually the majority. Debian and derivatives (incl. Ubuntu) have been shipping wabt for a few years now. I'm hoping that these can be dropped and regenerated by the build system when necessary (e.g. when building tests or examples). If not, there is a possibility that the Debian archive will accept those as binaries shipped alongside their sources.

- bindings/rust/wasmedge-sys/tests/data/fibonacci.wasm
- bindings/rust/wasmedge-sys/tests/data/import.wasm
- bindings/rust/wasmedge-sys/tests/data/test.wasm
- bindings/rust/wasmedge-sys/examples/data/funcs.wasm
- bindings/rust/wasmedge-sys/examples/data/fibonacci.wasm
- bindings/rust/wasmedge-sys/examples/data/module2.wasm
- bindings/rust/wasmedge-sys/examples/data/wasi_print_env.wasm
- bindings/rust/wasmedge-sys/examples/data/module1.wasm
- test/mixcall/mixcallTestData/module2.wasm
- test/mixcall/mixcallTestData/module1.wasm
- test/externref/externrefTestData/funcs.wasm
- test/externref/externrefTestData/stl.wasm
- test/api/apiTestData/import.wasm
- test/api/apiTestData/test.wasm
- examples/plugin/get-string/test.wasm
- examples/capi/host_functions/parse_json/parse-json.wasm
- examples/wasm/fibonacci.wasm
- examples/wasm/factorial.wasm
- examples/wasm/factorial2.wasm

### Rust sources shipped in tree 

- examples/capi/wasi-env/wasi_get_env.wasm

This can be rebuilt in Debian assuming the Rust dependencies are installed (`apt install rustc cargo lld-14 libstd-rust-dev-wasm32; cargo build --offline --release --target=wasm32-wasi`). 

Given the build system does not really build the corresponding C test program, or execute this example, removing this precompiled .wasm the tarball would be the safest option for Debian inclusion.

### C sources shipped in tree 

The two copies are byte-for-byte identical. The former includes a Makefile, which regenerates the .wasm assuming the build dependencies are installed (`apt install --no-install-recommends clang lld make`).

Same as above: given these examples are really there as references and nothing relies on them at build time, it seems possible to remove this precompiled .wasm from the tarball.

- examples/capi/mandelbrot-set-in-threads/mandelbrot.wasm
- bindings/rust/wasmedge-sdk/examples/data/mandelbrot.wasm

### Rust sources published online

The source for these is not shipped in the tarball, which is definitely a blocker for Debian. I had a look, and these look possible to rebuild them using the Rust toolchain outlined above. Assuming the sources were to be included, and given the possibily for reproducing the binaries, a (small) possibility exists that the Debian archive will accept those as binaries shipped alongside their sources.

- examples/wasm/add.wasm
- examples/wasm/hello.wasm

### C sources published online

The source for these is not shipped in the tarball, which is definitely a blocker for Debian. Even if it was, I took a look and it looks like it would be very complicated for this to be rebuilt in a clean Debian system (and using components only from Debian). I'd recommend removing these files from the tarball entirely, and perhaps leaving URLs or CMake files to fetch those from their respective repository for anyone installing from source.

- examples/js/qjs_tf.wasm
- examples/js/qjs.wasm

**Comment by juntao** [comment]
Thank you @paravoid 

This is very helpful and we would love to be part of Debian!

It is possible for our CI to generate and publish a special tarball for Debian without these examples? 

One of the reasons we included them in the GitHub source tree is to make it easier for beginners. They can just git clone and start running those examples.

**Comment by paravoid** [comment]
> Thank you @paravoid
> 
> This is very helpful and we would love to be part of Debian!

You're welcome! Right now the real blocker is the symbol situation -- the new SONAME helps a lot, but I have an outstanding question on issue 1678, with regards to a version script :)

> It is possible for our CI to generate and publish a special tarball for Debian without these examples?
> 
> One of the reasons we included them in the GitHub source tree is to make it easier for beginners. They can just git clone and start running those examples.

I think if you'd like to go that way, I wouldn't ask you to build that kind of infrastructure -- I could repack the tarball on the Debian end instead.

Hoewver with regards to examples for beginners (of which I am one!): is this for folks that want to build WasmEdge from source? If yes, would it be possible to just add wabt in the list of dependencies? If not and this is for folks running from the binaries, then could those examples be shipped in a different tarball, or perhaps an entirely different git repository? Your "wasm-learning" repository seems to be pretty comprehensive for example, and I personally found it super helpful!

**Comment by juntao** [comment]
Thank you @paravoid 

One of the reasons to ship pre-built Wasm files is for beginners to immediately start playing with WasmEdge w/o having to install a compiler first. It is to add "education value" to the GitHub repo. I think they are not necessary in a tarball release intended for a Linux distro. So, we can safely remove them in the tarball. Thanks!

For the longer term, we do plan to split the docs, examples (or even SDKs) into separate repos. But that requires more planning. 😅

**Comment by hydai** [comment]
Hi @paravoid 

Thanks for reporting this. After checking for a while, we would like to keep all of the `Handcrafted WAT, shipped alongside WASM` part because some of them are not generated from WAT, almost hand-written. We will add more cases like these test wasm files because we are going to add more invalid test cases in the near future which can only be handcrafted and there is no tool to compile them into valid wasm files.

About the `C sources shipped in tree` part, we will remove the built binaries and ask users who want to execute these examples to build from source by themselves.

About the `Rust sources published online` part, I think this is just like the `Handcrafted WAT, shipped alongside WASM` part, so I am going to publish them with the corresponding WAT files.

And for the final part `C sources published online`, I totally agree with that it's pretty hard to build from source by users, there are so many steps that need to be set up before building it. However, I will also remove these files and try to download them via CMake.

I would like to get this fixed in the next version. Thanks again for your helpful information.

**Comment by hydai** [comment]
The compiled wasm files are replaced with their corresponding WAT files in PR #2108

**Comment by paravoid** [comment]
Thanks! While I think that's great for the items in the first category, where the WAT files are handcrafted anyway (e.g. fibonacci), I'm afraid that for the rest of them (like e.g. mandelbrot) it doesn't really change much from a distribution or open source standpoint. This is because the WAT files in those cases are not the sources (the "preferred source of modification"); the corresponding C or Rust sources are. So these files are still "binaries", and the result of a build process (clang -> wasm2wat), even if a textual representation of them is being shipped -- at least as far as I understand it!

**Comment by hydai** [comment]
I agreed with the mandelbrot and other non-handcrafted parts, even if we change it to the WAT format, which will be a huge text file and non-readable because it's still compiled from other projects.

So I have a question: do we have to ship the examples folder in the Debian package? My apologies for the lack of common sense in publishing a Debian package. I would like to know the best practice to make things right.

If this is required, I would like to remove them from the source tarball. I don't think it's easy to build and necessary for the package since most examples are not compiled unless users want to try a tutorial.

We use the source tarball to build the Fedora packages, but we only ship the following files:
* Headers
* Shared Objects
* License and other required documents
* Binaries

Ref: https://src.fedoraproject.org/rpms/wasmedge/blob/rawhide/f/wasmedge.spec

**Comment by paravoid** [comment]
Sorry for the late response!

The short answer is that we don't _have_ to ship anything :) 

However, whatever Debian ships needs to be accompanied by the source code (and for this code to be freely licensed). This includes the binary packages, but also the source package, which includes the upstream source.

For the Debian source package, we can always use a modified tarball, rather than the one that you, as upstream, ship, and remove all files we consider non-free from it (such as those WAT files). It is possible and not uncommon (e.g. "dpkg -l |grep dfsg" on any system will show a few of those), but non-ideal in two ways: first, Debian will deviate from what you as upstream consider the source; and second, other downstream distributions will have similar requirements, and thus would need to also do this kind of filtering on their end.

I'm not super familiar with Fedora's policies and how strict or lax they are; I suspect that shipping binaries in the source tarball, without the accompanying source in the same source tarball, will not be compliant with their policies. But take this with a grain of salt.

My recommendation is to drop the more complicated (= non-handcrafted) examples and instead point users to another repo for tutorials and examples. But whatever you decide, I'll manage :)

What I'd definitely recommend against is trying to do "workarounds" such as e.g. shipping WAT files generated by wasm2wat files, such as e.g. for mandelbrot (I think that's what part of #2108 did). That doesn't make a difference from a licensing perspective, and is adding steps on your end that make no functional sense. Hope this helps!

**Comment by paravoid** [comment]
Bump? Any plans to have this in 0.12 perhaps? Thanks in advance!

**Comment by hydai** [comment]
Hi @paravoid 
I'm sorry for not getting back to you sooner. I must miss your previous messages. And the answer is yes. We are going to have this in 0.12 for moving forward. I will have a PR to remove such WAT files and move them to a standalone repository if needed next week.

**Comment by paravoid** [comment]
A bit of a semi-related update. I uploaded WasmEdge (0.12 alpha2) into Debian and is now part of experimental. Still debating whether to upload it to unstable or wait for the 0.12 final. It certainly won't make it to the bookworm release. Post-bookworm, I'll also enable wasmedge in crun (which I also maintain these days). Feel free to contact me at (my github handle)@debian.org if you need more on this to avoid polluting this issue :)

Back to this issue: you can see the files I'm stripping from the upstream tarball here:
https://salsa.debian.org/debian/wasmedge/-/blob/debian/latest/debian/copyright
The Files-Excluded header is processed through Debian tooling when importing new upstream versions (gbp import-orig -> uscan -> mk-origtargz). I always prefer keeping the upstream sources intact (and signed etc.) but on the other hand, this is also relatively painless for us, so if it's too much trouble on your end, it's fine to keep it, and close this task :)

**Comment by hydai** [comment]
Hi @paravoid 
Thanks for this. The 0.12.1 was out a few days ago. And we are going to split some bindings, such as the rust one, to a standalone repository in the next release, 0.13.0.

The `Files-Excluded` list is beneficial. I will review these files and try to remove them from the source tree. I hWe hope to reduce as many precompiled WASM as possible in the near release.

**Comment by hydai** [comment]
Working status:

## Handcrafted WAT, shipped alongside WASM

- [ ] bindings/rust/wasmedge-sys/tests/data/fibonacci.wasm
- [ ] bindings/rust/wasmedge-sys/tests/data/import.wasm
- [ ] bindings/rust/wasmedge-sys/tests/data/test.wasm
- [ ] bindings/rust/wasmedge-sys/examples/data/funcs.wasm
- [ ] bindings/rust/wasmedge-sys/examples/data/fibonacci.wasm
- [ ] bindings/rust/wasmedge-sys/examples/data/module2.wasm
- [ ] bindings/rust/wasmedge-sys/examples/data/wasi_print_env.wasm
- [ ] bindings/rust/wasmedge-sys/examples/data/module1.wasm
- [ ] test/mixcall/mixcallTestData/module2.wasm
- [ ] test/mixcall/mixcallTestData/module1.wasm
- [ ] test/externref/externrefTestData/funcs.wasm
- [ ] test/externref/externrefTestData/stl.wasm
- [ ] test/api/apiTestData/import.wasm
- [ ] test/api/apiTestData/test.wasm
- [ ] examples/plugin/get-string/test.wasm
- [ ] examples/capi/host_functions/parse_json/parse-json.wasm
- [ ] examples/wasm/fibonacci.wasm
- [ ] examples/wasm/factorial.wasm
- [ ] examples/wasm/factorial2.wasm
- [ ] Rust sources shipped in tree
- [ ] examples/capi/wasi-env/wasi_get_env.wasm

## C sources shipped in tree

- [ ] examples/capi/mandelbrot-set-in-threads/mandelbrot.wasm
- [ ] bindings/rust/wasmedge-sdk/examples/data/mandelbrot.wasm

## Rust sources published online

- [ ] examples/wasm/add.wasm
- [ ] examples/wasm/hello.wasm

## C sources published online

- [ ] examples/js/qjs_tf.wasm
- [ ] examples/js/qjs.wasm

**Comment by hydai** [comment]
Hi @paravoid 
In the 0.13.0 release, we already removed all problematic precompiled WASM files. Please let me know if there is anything we need to remove. Thanks!

**Comment by paravoid** [comment]
Thank you @hydai! That's excellent!

Looking at 0.13.1, it seems that these are still present:
```
wasmedge/bindings/java/wasmedge-java/src/test/resources/apiTestData/import.wasm
wasmedge/bindings/java/wasmedge-java/src/test/resources/apiTestData/test.wasm
wasmedge/bindings/java/wasmedge-java/src/test/resources/apiTestData/fibonacci.wasm
```

**Comment by hydai** [comment]
@paravoid 
Could you please ignore the Java bindings? We will split it into another repo, just like the rust-binding. However, we don't have much engineering power now to fix the building issue in Java binding. So it will need some time to clean it up.

**Comment by paravoid** [comment]
No problem :)
