### ISSUE TITLE
Dependency for rapidjson

### ISSUE THREAD

**Issue by yanganto** [WasmEdge/WasmEdge#1878]
## Description
The current build flow is not using the existing `rapidjson`, and download a new one.  This is an issue when the user already installs `rapidjson` on Archlinux.  This is reported in Arch User Repository.

### Current State
Always download `rapidjson` and not use the existing one in the system.
https://github.com/WasmEdge/WasmEdge/blob/7d6eb6870fc73cd43bb76e6169806973b95a9574/test/spec/CMakeLists.txt#L41-L44

Archlinux will refuse to install `wasmedge`, because it also installs `rapidjson` to overwrite the existing one on the system.

### Expected
Using existing `rapidjson` or an option to do this

## Environment
- Hardware Architecture: x86_64
- Operating system: Archlinux

**Comment by hydai** [comment]
Hi @yanganto 
This fix will be shipped in the next release (ETA. the end of oct.)
