### ISSUE TITLE
Interaction of Modules: Module Linking

### ISSUE THREAD

**Issue by dm4** [WasmEdge/WasmEdge#1880]
## Motivation

As #1877 metioned, for better reuse wasm modules, we'd like to enhance WasmEdge to support more interactoins of modules. This issue brings some early ideas with some wasm examples with pseudo code, and some implementation details to support proposals like module linking or component model.

## Details

For example, here we have two wasm files: `add.wat` and `main.wat`:

```add.wat
(module
  (func (export "f") (param i32 i32) (result i32))
    local.get 0
    local.get 1
    i32.add
  )
)
```

```main.wat
(module
  (func $f (import "add" "f") (param i32 i32) (result i32))
  (func (export "start") (param i32 i32) (result i32)
    local.get 0
    local.get 1
    call $f
  )
)
```

Here we can see that `add.f` is called by `main.start`. With component model proposal, we could combine these two module into a component:

```component.wat
(component
  (core module $Add
    (func (export "f") (param i32 i32) (result i32)
      local.get 0
      local.get 1
      i32.add
    )
  )
  (core module $Main
    (func $f (import "add" "f") (param i32 i32) (result i32))
    (func $start (export "start") (param i32 i32) (result i32)
      local.get 0
      local.get 1
      call $f
    )
  )
  (core instance $add (instantiate $Add))
  (core instance $main (instantiate $Main
    (with "add" (instance $add))
  ))
  (func (export "start") (param "a" u32) (param "b" u32) (result u32) (canon lift
    (core func $main "start")
  ))
)
```

In WasmEdge, we can simply use C API to link modules together:

```test.c
#include <stdio.h>
#include <wasmedge/wasmedge.h>

int main() {
  WasmEdge_ConfigureContext *ConfCxt = WasmEdge_ConfigureCreate();
  WasmEdge_VMContext *VMCxt = WasmEdge_VMCreate(ConfCxt, NULL);
  WasmEdge_String ModNameAdd = WasmEdge_StringCreateByCString("add");
  WasmEdge_String ModNameMain = WasmEdge_StringCreateByCString("main");
  WasmEdge_String FuncNameStart = WasmEdge_StringCreateByCString("start");
  WasmEdge_VMRegisterModuleFromFile(VMCxt, ModNameAdd, "add.wasm");
  WasmEdge_VMRegisterModuleFromFile(VMCxt, ModNameMain, "main.wasm");

  WasmEdge_Value Params[2] = {WasmEdge_ValueGenI32(1), WasmEdge_ValueGenI32(2)};
  WasmEdge_Value Returns[1];
  WasmEdge_VMExecuteRegistered(VMCxt, ModNameMain, FuncNameStart, Params, 2,
                               Returns, 1);
  printf("Get the result: %d\n", WasmEdge_ValueGetI32(Returns[0]));

  WasmEdge_StringDelete(ModNameAdd);
  WasmEdge_StringDelete(ModNameMain);
  WasmEdge_StringDelete(FuncNameStart);
  WasmEdge_VMDelete(VMCxt);
  WasmEdge_ConfigureDelete(ConfCxt);
  return 0;
}
```

```
$ wat2wasm add.wat && wat2wasm main.wat
$ gcc test.c -lwasmedge && ./a.out
Get the result: 3
```

Therefore, if we only think about one of the most important feature in module linking and component model proposal: initiate module instances and commute with each others. The cureent WasmEdge implementation should be able to achieve this with no pain. We could simply use C API code to replace module linking expression in those proposals.

## Appendix

- #1877 
- [Component Model Proposal Explainer](https://github.com/WebAssembly/component-model/blob/main/design/mvp/Explainer.md)
- [Module Linking Proposal Explainer](https://github.com/WebAssembly/module-linking/blob/main/proposals/module-linking/Explainer.md)

**Comment by dannypsnl** [comment]
The potential of module instances is they are well-limited units, and hence a good context switching unit, to show this power the VM will need async call ability.

**Comment by dannypsnl** [comment]
I think we can close this safely now.
