### ISSUE TITLE
Compile Rust WASM extern function to call host function

### ISSUE THREAD

**Issue by Tails** [WasmEdge/WasmEdge#1911]
I'm trying to call the Rust SDK host from my Rust WASM code. There is a nice [example](https://github.com/WasmEdge/WasmEdge/blob/master/bindings/rust/wasmedge-sdk/examples/hello_world.rs) on how to define a host function, but the examples use pure WASM code instead of compiling Rust to WASM. 

How should ```extern "C" { ... }``` (and 'wasmedge_bindgen'?) be used to have Rust WASM compile an extern function in such a way that it will call the host function? Most bindgen examples seem to be about how to put data _into_ WASM, instead of out of it.

I'm looking for something like:

```rust
// Rust WASM code
use wasmedge_bindgen_macro::wasmedge_bindgen;

// #[wasmedge_bindgen(module = "env")]
extern "C" {
    // #[wasmedge_bindgen(module = "env")]
    fn say_hello();
}

fn main() {
   unsafe( say_hello() );
}
```

```rust
// Rust SDK
fn say_hello(caller: &CallingFrame, _args: Vec<WasmValue>) -> Result<Vec<WasmValue>, HostFuncError> {
    println!("Hello, world!");

    Ok(vec![])
}

pub fn run() -> anyhow::Result<()> {
    ...

    // create an import module
    let import = ImportObjectBuilder::new()
        .with_func::<(), ()>("say_hello", say_hello)?
        .build("env")?;

    // create a vm with the config settings
    let result = Vm::new(Some(config()));
    assert!(result.is_ok());

    // create VM and register our wasm module
    let mut vm = result?
        .register_import_module(import)?
        ;

    ...
}

**Comment by apepkuss** [comment]
@DarumaDocker Could you please help with the issue from @Tails ? It seems to be related to `wasmedge-bindgen`. Thanks!

**Comment by Tails** [comment]
I see it's related to this: https://github.com/second-state/wasmedge-bindgen/issues/4

**Comment by DarumaDocker** [comment]
@Tails `wasmedge-bindgen` is designed to pass complex data types such as String to wasm exported functions when called by the host, but not the other wasy around.

**Comment by apepkuss** [comment]
@Tails Please refer to [the reply](https://github.com/second-state/wasmedge-bindgen/issues/4#issuecomment-1274068687). Thanks!

**Comment by Tails** [comment]
Solution is posted in the referred issue.
