### ISSUE TITLE
[wasi-nn] host function failed, Code: 0x8d

### ISSUE THREAD

**Issue by apepkuss** [WasmEdge/WasmEdge#1912]
### Current State

I'm trying to `load` host func of `wasi-nn` via Rust SDK. The API calling chain is `load_from_file` ---> `load_from_bytes` ---> `"load" host func`, in which the first two APIs are defined in `wasmedge-sdk::wasi`. The code snippet between line 19 and 25 in the example code below shows the call to the `load_from_file` API.

![image](https://user-images.githubusercontent.com/4726889/194784586-75a96280-87ef-4b13-826e-79a178095131.png)

The following issue was raised while running the example code above:

```bash
[error] execution failed: host function failed, Code: 0x8d
```

According to the investigation, the error code should be thrown by 

```cpp
// wasinnfunc.cpp

Expect<uint32_t> WasiNNLoad::body(const Runtime::CallingFrame &Frame,
                                  uint32_t BuilderPtr [[maybe_unused]],
                                  uint32_t BuilderLen [[maybe_unused]],
                                  uint32_t Encoding,
                                  uint32_t Target [[maybe_unused]],
                                  uint32_t GraphIdPtr [[maybe_unused]]) {
  // Check memory instance from module.
  auto *MemInst = Frame.getMemoryByIndex(0);
  if (MemInst == nullptr) {
    return Unexpect(ErrCode::Value::HostFuncError);  <=== throw the error
  }
  
  ...

}
```

My question is **Is there any step I need to add in the example code to make the `memory` available?** For the case of `wasi` module, there is a *initialization* step. Is there a similar step for `wasi-nn` module? Thanks a lot!

## Environment

- Hardware Architecture: x86\_64
- Operating system: Ubuntu 20.04 (wasmedge/wasmedge:ubuntu-build-gcc)

I followed [Build WasmEdge with WASI-NN PyTorch Backend](https://wasmedge.org/book/en/contribute/build_from_src/plugin_wasi_nn.html#build-wasmedge-with-wasi-nn-pytorch-backend) to deploy `libtorch` and build runtime.

**Comment by q82419** [comment]
Why do you want to call the host function directly?
The host function is for the WASM use.
When a WASM module invoke the host function, the calling frame will be set in, and therefore the host function can get the memory instance of the WASM module.
You invoke the host function from the module instance directly, obviously the host function cannot get the calling frame.

**Comment by apepkuss** [comment]
@q82419 Thanks for the explanation!

One more question: Does the function [WasmEdge_ModuleInstanceCreateWasiNN](https://github.com/WasmEdge/WasmEdge/blob/master/include/api/wasmedge/wasmedge.h#L1791-L1802) serve to create an import module? I didn't find any example or test code covering the usage of the c api, so could you please provide some code to demonstrate it? Thanks a lot!

**Comment by q82419** [comment]
It's like the use of WASI creation.

```c
WasmEdge_ModuleInstanceContext *WasiNNModCxt = WasmEdge_ModuleInstanceCreateWasiNN();
WasmEdge_VMContext *VMCxt = ...; // Or the executor context
WasmEdge_VMRegisterModuleFromImport(VMCxt, WasiNNModCxt);
// Or the WasmEdge_ExecutorRegister()
```

**Comment by q82419** [comment]
@apepkuss is this resolved?

**Comment by apepkuss** [comment]
@q82419 Sure! I forgot to close it. Thanks for the reminder!
