### ISSUE TITLE
[Windows] Review the `WASI` Host API

### ISSUE THREAD

**Issue by abhinandanudupa** [WasmEdge/WasmEdge#1918]
## Goal

Review and fix bugs/issues with the WASI Host API for the Windows Platform.

### Description

The Windows Platform, unfortunately, is not POSIX compliant. Hence the functionality that is described by the [WASI standard](https://github.com/WebAssembly/wasi-filesystem) may not be completely fulfilled. The [issues section](https://github.com/WebAssembly/wasi-filesystem/issues) will be a good source to find any issues that you think are not be addressed by the WASI interface. For more information about the standard please checkout [their official repository](https://github.com/WebAssembly/WASI).

Please refer to this [comment](https://github.com/WasmEdge/WasmEdge/issues/1477#issuecomment-1207415917) to check the implementation status (not review status) of each of the functions in WasmEdge.

If you find any issues or bugs in the current implementation or you find a better way to implement the functions please leave a comment in this thread. Your suggestions are welcome!

### Review Status of the host functions

Below are the functions specified by the WASI standard which need to be reviewed

- [ ] `open` - #1919
- [ ] `fdAdvise` - #1920
- [ ] `fdAllocate` - #1921 
- [ ] `fdDatasync` - #1922 
- [ ] `fdFdstatGet` - #1923 
- [ ] `fdFdstatSetFlags` - #1924 
- [ ] `fdFilestatSetSize` - #1925 
- [ ] `fdFilestatSetTimes` - #1926 
- [ ] `fdPread` - #1927 
- [ ] `fdPwrite` - #1928 
- [ ] `fdRead` - #1929 
- [ ] `fdWrite` - #1930 
- [ ] `fdReaddir` - #1931 
- [ ] `fdSeek` - #1932 
- [ ] `fdSync` - #1933 
- [ ] `fdTell` - #1934 
- [ ] `getNativeHandler` - #1935 
- [ ] `pathCreateDirectory` - #1936 
- [ ] `pathFilestatGet` - #1937 
- [ ] `pathFilestatSetTimes` - #1938 
- [ ] `pathLink` - #1939 
- [ ] `pathOpen` - #1940 
- [ ] `pathReadlink` - #1941 
- [ ] `pathRemoveDirectory` - #1942 
- [ ] `pathRename` - #1943 
- [ ] `pathSymlink` - #1956 
- [ ] `pathUnlinkFile` - #1957
- [ ] `sockGetPeerAddr` - #1944 [One socket function]
- [ ] `unsafeFiletype` - #1945 
- [ ] `filetype` - #1946 
- [ ] `isDirectory` - #1947 
- [ ] `isSymlink` - #1948 
- [ ] `filesize` - #1949 
- [ ] `canBrowse` - #1950 
- [ ] `Poller::pollOneoff` - #1951 
- [ ] `Poller::clock` - #1952 
- [ ] `Poller::read` - #1953 
- [ ] `Poller::write` - #1954 
- [ ] `Poller::wait` - #1955 

## Environment

- Hardware Architecture: x86\_64 primarily
- Operating system: The Windows Family of Operating Systems

## Appendix

[[Windows] Implement host functions on the Windows platform #1826](https://github.com/WasmEdge/WasmEdge/pull/1826)

**Comment by hydai** [comment]
Since all of the tracked tasks are done, it should be fine to close this issue.
