### ISSUE TITLE
When I run a wasm program in container, it can not get environment variables.

### ISSUE THREAD

**Issue by TaurusM** [WasmEdge/WasmEdge#1977]
Dockerfile like this:
![image](https://user-images.githubusercontent.com/28164162/196183365-1da87793-c69f-48fe-99e9-e8dca0a8b4cc.png)

and some code about get environment variables:
![image](https://user-images.githubusercontent.com/28164162/196183575-8245db4a-7918-4681-b184-4c1633b3719d.png)

and environment variables truely exists:
![微信截图_20221017210512](https://user-images.githubusercontent.com/28164162/196184835-751ba975-ef9c-4bd0-9490-87618421e5f5.png)

and the log is:
![image](https://user-images.githubusercontent.com/28164162/196184952-81aee705-87e6-4658-972f-97fa99dcae94.png)

the dependencies are:
![image](https://user-images.githubusercontent.com/28164162/196185179-486455ca-024d-463b-a5d2-66f5798ca85a.png)

So, what is the problem, or I missed something important? Guys please help me.

**Comment by hydai** [comment]
Hi @TaurusM 
Could you provide reproduce steps?
For example, how do you execute the wasm file?

**Comment by TaurusM** [comment]
@hydai 
Thanks for your reply.
In a container, execute directly by: "/panilake-user.wasm", which defined in the Dockerfile:
![image](https://user-images.githubusercontent.com/28164162/196330309-3d16b064-bcc4-42b7-b233-43d73b741159.png)

**Comment by hydai** [comment]
Not sure of the details, what's your environment like? And how to reproduce this?

`docker run xxx:wasm-image` or `wasmedge /xxx.wasm`?

**Comment by TaurusM** [comment]
My enviroment is a k8s cluster, I start the image within a deployment.
![image](https://user-images.githubusercontent.com/28164162/196331100-939636dc-8226-4cde-bcb8-39fa6e0f2040.png)

**Comment by TaurusM** [comment]
I want to obtain the env vars within the container, such as "FUNC_CONTEXT" and so on, but not work.

**Comment by TaurusM** [comment]
I have installed wasmedge on the node, follow the guidline with https://github.com/second-state/wasmedge-containers-examples/tree/main/kubernetes_crio

**Comment by hydai** [comment]
I will check it once I am available. Thanks for the information.

**Comment by TaurusM** [comment]
OK, I'll keep eyes on this problem. If you have the result or some suggestion, please answer me in time, cause we're depending on this feature, thank you. @hydai

**Comment by hydai** [comment]
The fixed PR is merged on crun, need to wait for the new release version: https://github.com/containers/crun/pull/1037

**Comment by hydai** [comment]
No further input. I am closing it. Please feel free to re-open it if you still encounter the same issue.
