### ISSUE TITLE
missing doc - wasmedge on openwrt

### ISSUE THREAD

**Issue by dberardo-com** [WasmEdge/WasmEdge#2002]
i can see on this page: https://wasmedge.org/book/en/features/platforms.html that wasmedge is available fro openwrt, but installation instruction are missing. any hints?

**Comment by dberardo-com** [comment]
thanks a lot. are there any limitations on CPUs that can be used with wasmedge? in terms of architecture (like MIPS) and number of bits?

**Comment by hydai** [comment]
Hi @dberardo-com 
Currently, WasmEdge provides these APIs to limit the execution resources:
```
--time-limit
                Limitation of maximum time(in milliseconds) for execution, default value is 0
                for no limitations

--gas-limit
                Limitation of execution gas. Upper bound can be specified as --gas-limit
                `GAS_LIMIT`.

--memory-page-limit
                Limitation of pages(as size of 64 KiB) in every memory instance. Upper bound
                can be specified as --memory-page-limit `PAGE_COUNT`.
```

However, because we are currently focusing on integrating WasmEdge with container runtimes, we don't have the related milestones in the near future.

**Comment by dberardo-com** [comment]
thanks for the reply, my question was more related to "which are the hardware requirements" for WasmEdge to be installed on a machine. At least in terms of CPU architecture and bits.

**Comment by hydai** [comment]
Sorry for the misunderstanding.

1. CPU bits: Our first-tier supports are on 64-bit platforms, so the installer script will only handle the 64-bit cases. However, we do have some 32-bit env support, but that will require users to build from source by themselves.
2. CPU arch: Our first-tier supports are on amd64 and arm64. If you are interested in other arches such as RISCV, there is an ongoing PR to support this: https://github.com/WasmEdge/WasmEdge/pull/1682
3. Memory: This will depend on your applications. We have executed wasmedge on seL4 and RPi before, which have limited memory size.

**Comment by dberardo-com** [comment]
that's great. would be nice to see that in the documentation as well, i think i could not found it.

so for the time being i understand that MIPS processors are out of scope here. i will see if i can get my hands on some other hardware then
