### ISSUE TITLE
Out of bounds memory access, Code: 0x88 when running Rust-compiled AOT in Docker

### ISSUE THREAD

**Issue by Tails** [WasmEdge/WasmEdge#2006]
I have a Rust host app that compiles the example [hello.wasm](https://github.com/second-state/wasm-learning/tree/master/cli/hello) to a Linux native binary from within a Docker container. It runs fine when interpreted, but errors out when using the AOT .so:

```bash
thread '<unnamed>' panicked at 'error when running VM function: Core(Execution(MemoryOutOfBounds))', lib/app/src/run.rs:272:11
wasmedge_1  | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
wasmedge_1  | [2022-10-24 20:38:59.885] [error] execution failed: out of bounds memory access, Code: 0x88
wasmedge_1  | [2022-10-24 20:38:59.885] [error]     When executing module name: "prerenderer" , function name: "_start"
```

Does the Rust SDK's VM even support running AOT .so binaries?

**Comment by hydai** [comment]
> When I do this with the original .wasm file, everything runs fine. But as soon as I use an AOT-variant, compiled either by wasmedgec or by the Rust SDK itself (but always run using vm.run_func() it errors out

Just for confirmation:
1. The wasm file is compiled by `wasmedgec` or `rust SDK`.
2. Running the compiled wasm in both `rust SDK` and `wasmedge` all failed with the above error message

The Rust SDK does support AOT wasm. So I think this may be an issue with the aot compiler. Could you provide any hint about the wasm file itself?

**Comment by Tails** [comment]
Your confirmation is correct.

The WASM in my application runs some javascript that generates HTML canvas draw commands from WasmEdge-QuickJS, that passes the commands to the Host. The Rust Host then draws the commands to a servo::PathFinder canvas. 

I've created a minimum running example highlighting the problem here:
https://github.com/Tails/wasmedge-aot-mem-issue

But now that I think of it, could the problem be that the app runs in Docker?

**Comment by Tails** [comment]
Were you able to reproduce the issue @hydai?

**Comment by hydai** [comment]
Hi @Tails 
I am on some other issues this week. Will take a look next week. Thanks.
