### ISSUE TITLE
`dladdr()` on Windows

### ISSUE THREAD

**Issue by q82419** [WasmEdge/WasmEdge#2032]
## Motivation

WasmEdge will use `dladdr()` on MacOS and Linux to search the plug-in default load path.
But the same function on Windows is not implemented.

## Details

Implement the same function on Windows. (`lib/plugin/plugin.cpp`)

**Comment by Its-Maniaco** [comment]
Hello @q82419 @hydai 
Would the implementation be the same as Linux? We will have to change `UsrStr` & `LibStr` along with the results pushed into `Result`. Can you kindly confirm?

**Comment by q82419** [comment]
Hi @Its-Maniaco ,

Can you take some examples on Windows or create a PR to explain? Thanks!

**Comment by dracoooooo** [comment]
Hi, I want to know if the issue is about using the result of `dladdr()` to replace `kGlobalPluginDir`? I found a function similar to `dladdr()` on Windows called [`GetModuleFileNameA()`](https://learn.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-getmodulefilenamea).

**Comment by q82419** [comment]
> 

Yes, you're right.
Maybe this API helps? But the `hModule` argument should not be `NULL`, because we need the path of `wasmedge.dll`, not the current executable.

**Comment by ho-229** [comment]
How about [GetModuleHandleExA](https://learn.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-getmodulehandleexa) with GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS flag.
