### ISSUE TITLE
[http_req] Specific URL cannot be fetched

### ISSUE THREAD

**Issue by DarumaDocker** [WasmEdge/WasmEdge#2064]
Since there is no issues link in the repo: https://github.com/second-state/http_req, so I post here.

On my laptop (Ubuntu 22.04) I can run the example successfully:
```
use http_req::request;

fn main() {
    let mut writer = Vec::new(); //container for body of a response
    let res = request::get("https://httpbin.org/get?msg=WasmEdge", &mut writer).unwrap();

    println!("Status: {} {}", res.status_code(), res.reason());
    println!("Headers {}", res.headers());
    println!("{}", String::from_utf8_lossy(&writer));
}
```

But when I change the requested URL to `https://mmhaskell.com/blog?format=RSS`, it failed with error:
```
[2022-11-08 10:43:33.360] [error] [WasmEdge Httpsreq] SSL_get_error code -1
[2022-11-08 10:43:33.397] [error] execution failed: host function failed, Code: 0x8d
[2022-11-08 10:43:33.397] [error]     When executing function name: "_start"
```

@L-jasmine Please help look at this

**Comment by alabulei1** [comment]
@DarumaDocker  Could you help print logs of this function to show more details?

**Comment by hydai** [comment]
Since wasmedge_httpsreq is deprecated, this issue is wontfix.
