### ISSUE TITLE
[Plugin] Cannot find registered plug-in on MacOS

### ISSUE THREAD

**Issue by q82419** [WasmEdge/WasmEdge#2070]
### Current State

The plug-in registering on MacOS may be correct, but the plugin will not found.
The reason may be that the `NiftyCounter` and the `PluginRegistoryStorage` are on the different instance.

### Expected

Load the plugin correctly and pass the `wasi_crypto` tests.

## Environment

- Hardware Architecture: x86_64
- Operating system: MacOS 10.15.7

The following information is optional. Please provide them only if you have built from source.
- C++ Compiler version: Apple Clang 12

## Steps to Reproduce

Take the `wasi_crypto` for example.
Should install the `openssl` on MacOS.

```bash
brew install openssl
```

Then build the WasmEdge with the options.

```bash
cmake -GNinja -Bbuild -DCMAKE_BUILD_TYPE=Debug -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl -DWASMEDGE_PLUGIN_WASI_CRYPTO=ON -DWASMEDGE_BUILD_TESTS=ON .
```

After building, change into the directory and run the test.

```bash
cd build/test/plugins/wasi_crypto
./wasiCryptoTests
```

If adding the log in the `IncreaseNiftyCounter()`, `DecreaseNiftyCounter()`, `Plugin::registerPlugin()`, and `Plugin::find()` functions with monitoring the address of the `NiftyCounter` variable, can get the following log:

```bash
q82419@MacBook-Pro:~/proj/WasmEdge/build/test/plugins/wasi_crypto $ ./wasiCryptoTests
 >>>>> IncreaseNiftyCounter: 0x1064e4dd0 0
 <<<<< IncreaseNiftyCounter: 0x1064e4dd0 1
 >>>>> PluginRegister::registerPlugin NiftyCounter: 0x1064e4dd0 1
 ----- PluginRegister::registerPlugin registring wasi_crypto 0
      ----- plugin storage: name: wasi_crypto index: 0
 <<<<< PluginRegister::registerPlugin
Running main() from /Users/q82419/proj/WasmEdge/build/_deps/gtest-src/googletest/src/gtest_main.cc
[==========] Running 9 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 9 tests from WasiCryptoTest
[ RUN      ] WasiCryptoTest.Aeads
 ----- Plugin::find wasi_crypto -- NiftyCounter 0x100d9bac8 0
 !!!!! plugin wasi_crypto cannot find
/Users/q82419/proj/WasmEdge/test/plugins/wasi_crypto/helper.cpp:262: Failure
Expected: (Func) != (nullptr), actual: NULL vs (nullptr)
Google Test trace:
/Users/q82419/proj/WasmEdge/test/plugins/wasi_crypto/aeads.cpp:15: AES-128-GCM
Segmentation fault: 11
```

Obviously, the address of `NiftyCounter` when registering the plugin is `0x1064e4dd0`, but the address when finding the plugin is `0x100d9bac8`. Therefore the registered plugin cannot be found.

**Comment by harry900831** [comment]
I tried to fix this bug in #2128, it seems that there's still a problem.

In my opinion, the reason why there's a duplicate instance is because we both dynamic link and dynamic load in the test binary.

In the plugin test, we may dynamic load the plugin module and then use it afterword. But in the CMakelists.txt of the plugin test,  we also dynamic link to the wasmedgePlugin{PluginName} target which is a shared libarary. For instance:
```
target_link_libraries(wasmedgeHttpsReqTests
   PRIVATE
   ${GTEST_BOTH_LIBRARIES}
   wasmedgePlugin
   wasmedgePluginHttpsReq
 )
 ```
After we build the test by the above CMakelists.txt, the test binary may depend on the `libwasmedgePlugin{PluginName}.dylib` on macOS. 
otool -L $(which wasmedgeProcessTests)

```
wasmedgeProcessTests:
	@rpath/libwasmedgePluginWasmEdgeProcess.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.100.3)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1300.23.0)
```
