### ISSUE TITLE
Unexpected Execution

### ISSUE THREAD

**Issue by erxiaozhou** [WasmEdge/WasmEdge#2080]
### Current State
There is an output: 0

### Expected

Raise an exception indicating "unexpected content at the end of section".

## Environment
- Code Version: git commit id 844103848a799fe3dc315b48cf4993ccdff1e097
- Hardware Architecture: x86\_64 
- Operating system: Ubuntu 20.04

The following information is optional. Please provide them only if you have built from source.
- C++ Compiler version: clang-14
- CMake version: 3.21.6
- CMake flags:  `-DCMAKE_BUILD_TYPE=Release -DWASMEDGE_BUILD_AOT_RUNTIME=ON`
- Boost version: libboost1.71-dev:amd64

- build commands
  ```
  export CC=/usr/bin/clang-14
  export CXX=/usr/bin/clang++-14
  rm -rf build ; mkdir build ; 
  cd build ; cmake -DCMAKE_BUILD_TYPE=Release -DWASMEDGE_BUILD_AOT_RUNTIME=ON .. ; make -j ; cd ..
  ```

## Steps to Reproduce
[wasmedge1.zip](https://github.com/WasmEdge/WasmEdge/files/9997804/wasmedge1.zip)

1. build the wasmedge
2. run the test case by `build/tools/wasmedge/wasmedge --reactor <test_case_name> to_test `

**Comment by q82419** [comment]
Comment: It seems like the bug occurs in checking loaded section sizes. Will fix it.
