### ISSUE TITLE
feat: support ValType as a structured class with variant

### ISSUE THREAD

**Issue by little-willy** [WasmEdge/WasmEdge#2081]
## Motivation

In our current support for WASM, we store all `ValType`s as uint_8, since in the current official WASM spec, all type op codes are only one byte. However, as we are supporting function-reference and GC proposal, the type specifier of `ValType` may occupy multiple bytes for typed reference.

<img width="821" alt="image" src="https://user-images.githubusercontent.com/115921523/201535868-5ec643c6-6df0-4888-9667-99bf8fabeb0f.png">

Therefore, to enable the best flexibility, we may support ValType as a structured class.

## Details

We may replace the current ValType enum class definition with a structured class, which initially may only act as a wrapper for the current enum class. In the future as we are support function-reference and GC proposal, we may add more information in the structured class.

Note: since in our java and rust SDK, we also expose such ValType, the binding interface may not be compatible. Not sure whether this is acceptable.

**Comment by little-willy** [comment]
@hydai @ibmibmibm @q82419 Do you have any thought about this refactor?

**Comment by hydai** [comment]
Personally, I prefer to use a static size of type, maybe `uint32_t`.

@little-willy Do you have any idea about the definitions of the new structures? Will it be a flexible and non-static size class or something?

**Comment by q82419** [comment]
Agree with Hydai.
As the similar extensions such as instruction OpCode (8-bit to 16-bit), we used the static size of type to store the data.

**Comment by little-willy** [comment]
@q82419 @hydai 

The problem is that the ValType can possibly contains two parts, the OpCode and the heap type index for reference value. If we keep storing it as an integer, we will have to decode the integer into the two parts, which is wired and make the code hard to maintain.

My thought is to rename the current `ValType` to `ValTypeOpCode`, and introduce a new structured class for `ValType` with the following field definition
```
class ValType {
    ValTypeOpCode OpCode;
    union {
        uint_32_t HeapTypeIdx;
    } ValTypeExt;
};
```

For the current existing `ValTypeOpCode`, the `ValTypeExt` will not be set. For the extended reftype, we can set the ValTypeExt.HeapTypeIdx. And in case that the wasm spec will support more structured ValType, we are flexible to incorporate it.

For any current usage of `ValType`, we can simply replace it with `ValType.getOpCode`, so that the refactor can be clean and won't introduce too much extra logic.

**Comment by q82419** [comment]
Merged with typed-function references proposal.
