### ISSUE TITLE
AoT compiler doesn't work  from a user

### ISSUE THREAD

**Issue by alabulei1** [WasmEdge/WasmEdge#2084]
## Description

Couldn't use `wasmedgec` to AoT compile a wasm file from `.net`.

<img width="553" alt="image" src="https://user-images.githubusercontent.com/45785633/201582164-b59ef2a5-1a39-46fe-87aa-f0f8d045f74e.png">

If you need more information, let me know

**Comment by hydai** [comment]
Duplicated as https://github.com/WasmEdge/WasmEdge/issues/1898
