### ISSUE TITLE
Implement OpenCV plugin for WasmEdge and build rust wrapper for host functions

### ISSUE THREAD

**Issue by omkar-mohanty** [WasmEdge/WasmEdge#2106]
## Motivation
OpenCV cannot be compiled to `wasm32-wasi` target effectively because it  heavily uses exception and threads.  A workaround to this problem is to add OpenCV as a plugin to WasmEdge.

## Details
- [ ] Study the [HTTP requests plugin](https://wasmedge.org/book/en/write_wasm/rust/networking-https.html) .
- [ ] Write C++ host functions code for `core` OpenCV module.
- [ ] Write C++ host functions for `imgcodecs` OpenCV module.
- [ ] Write C++ host functions for `imgproc` OpenCV module.
- [ ] Write Rust wrapper for `core` ,`imgcodecs` and `imgproc` module. 
 - [ ] Review and implement host functions for rest of the OpenCV library.
 - [ ] Write Rust wrapper for rest of the OpenCV library.

**Comment by juntao** [comment]
Sounds good! The Rust wrapper could be modeled after this crate:

https://github.com/twistedfall/opencv-rust

I do not think you can use it directly but the API design could be very similar. Thanks!

**Comment by omkar-mohanty** [comment]
Hi Michael,
I made a draft PR  to track the progress of the plugin. Here is the link
https://github.com/WasmEdge/WasmEdge/pull/2112. Can you let me know if this
approach is good enough?

Thanks,
Omkar

**Comment by SAtacker** [comment]
> Sounds good! The Rust wrapper could be modeled after this crate:
> 
> https://github.com/twistedfall/opencv-rust
> 
> I do not think you can use it directly but the API design could be very similar. Thanks!

I haven't used this but it uses (a custom) binding generator for opencv c++ to rust. Ref - https://github.com/twistedfall/opencv-rust#the-binding-strategy
Sorry I am lagging behind, but could anyone please explain what is the strategy here?
CC @omkar-mohanty

**Comment by hydai** [comment]
This is replaced by the OpenCVMini plugin. Closing it.
