### ISSUE TITLE
NDK test.c out of date ... update attached

### ISSUE THREAD

**Issue by justin-echternach** [WasmEdge/WasmEdge#2117]
## Description
It appears the example code (test.c) on the Android NDK page is out of date.  Here is the fixed code ... attached in a zip file.

Wasn't sure where to post this, so forgive me if this is not the right place.
## Environment

- Hardware Architecture: (e.g. x86\_64 or aarch64)
- Operating system: (e.g. Ubuntu 20.04 or CentOS 7.6)

The following information is optional. Please provide them only if you have built from source.
- C++ Compiler version:
- CMake version:
- CMake flags: (e.g. `-DCMAKE_BUILD_TYPE=Release -DWASMEDGE_BUILD_AOT_RUNTIME=ON`)
- Boost version:

## Steps to Reproduce
go to ... https://wasmedge.org/book/en/contribute/build_from_src/android/ndk.html

and try to run the code

[test.c.zip](https://github.com/WasmEdge/WasmEdge/files/10091070/test.c.zip)

**Comment by justin-echternach** [comment]
updated the docs according to your contribution guide ... the pull request is here ...

https://github.com/WasmEdge/WasmEdge/pull/2118

**Comment by hydai** [comment]
Fixed by #2118. I am closing this.
