### ISSUE TITLE
tokio_wasi: tokio::spawn() unable to work

### ISSUE THREAD

**Issue by JasonLou99** [WasmEdge/WasmEdge#2136]
## Description
My code:
```rust
#[tokio::main]
async fn main() -> std::io::Result<()> {
    let mut handles = Vec::with_capacity(10);
    for _ in 0..10 {
        handles.push(tokio::spawn(async { println!("10") }));
    }
    // Wait for all of them to complete.
    for handle in handles {
        handle.await?;
    }

    Ok(())
}
```
cargo.toml:
```
tokio_wasi = { version = "1.21", features = ["full"] }
```

### Current State
Can compile normally, but cannot run
```shell
jason@webassembly120:~/wasm_storage/wasm_storage_client$ cargo build --target wasm32-wasi --example tcpclient         
Finished dev [unoptimized + debuginfo] target(s) in 0.03s

jason@webassembly120:~/wasm_storage/wasm_storage_client$ wasmedge ./target/wasm32-wasi/debug/examples/tcpclient.wasm
thread 'main' panicked at 'OS can't spawn worker thread: operation not supported on this platform', /home/jason/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio_wasi-1.21.3/src/runtime/scheduler/multi_thread/worker.rs:358:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2022-11-30 22:03:44.773] [error] execution failed: unreachable, Code: 0x89
[2022-11-30 22:03:44.773] [error]     In instruction: unreachable (0x00) , Bytecode offset: 0x00102f26
[2022-11-30 22:03:44.773] [error]     When executing function name: "_start"
jason@webassembly120:~/wasm_storage/wasm_storage_client$
```

### Expected

How to use multithreading or asynchronous concurrent programming in WasmEdge?

## Environment

- Hardware Architecture: (e.g. x64)
- Operating system: (e.g. Ubuntu 20.04)

**Comment by hydai** [comment]
Hi @JasonLou99, what's your platform?

---

Hi @MediosZ, could you help with this? It looks like this error is triggered from `tokio_wasi.`

**Comment by juntao** [comment]
Since Wasm is single threaded (like JS runtimes), I do not think it supports multi thread tokio yet. Currently, tokio is supported as a single thread runtime for concurrent tasks. 

We are, however, looking into ways to support multi thread apps in Wasm through host integration.

**Comment by MediosZ** [comment]
Hi @JasonLou99,
As @juntao  mentioned, multi-thread is not supported yet.
Please try using `#[tokio::main(flavor = "current_thread")]`
Here's [an example for this](https://github.com/WasmEdge/tokio/blob/master/examples/hello_world.rs).

**Comment by JasonLou99** [comment]
Thanks!
