### ISSUE TITLE
Support Unix domain sockets in wasmedge_wasi_socket

### ISSUE THREAD

**Issue by juntao** [WasmEdge/WasmEdge#2138]
## Motivation

The AF_UNIX sockets are used to improve performance for applications running on the same host, which is a common use case for Wasm apps. We should support that. 

https://en.m.wikipedia.org/wiki/Unix_domain_socket

## Details

- [ ] Support AF_UNIX in WasmEdge
- [ ] Add a Rust API for it
- [ ] Add a C API for it

**Comment by hydai** [comment]
Hi @LFsWang 
Could you help with this?

**Comment by LFsWang** [comment]
ok
