### ISSUE TITLE
Explain memory management of the string result from docs example

### ISSUE THREAD

**Issue by vlkv** [WasmEdge/WasmEdge#2156]
Hello, I am studying this example https://wasmedge.org/book/en/sdk/go/memory.html#pass-strings-to-tinygo-functions

From the wasm side we have:
```
// export greet
func greet(subject *int32) *byte {
  // ...
  output := subjectStr.String()
  output = "Hello, " + output + "!"

  return &(([]byte)(output)[0])
}
```
This is compiled to wasm with TinyGo, thus, the objects inside that wasm module will be managed with a GC. The `output` string is allocated on a wasm's heap, and `greet` function returns the address of it to the host. I am not comfortable about it already...

From the host side, we doing this:
```
  // ...
  // Run the `greet` function. Given the pointer to the subject.
  greetResult, _ := vm.Execute("greet", inputPointer)
  outputPointer := greetResult[0].(int32)

  pageSize := mem.GetPageSize()
  // Read the result of the `greet` function.
  memData, _ = mem.GetData(uint(0), uint(pageSize * 65536))
  nth := 0
  var output strings.Builder

  for {
    if memData[int(outputPointer) + nth] == 0 {
      break
    }

    output.WriteByte(memData[int(outputPointer) + nth])
    nth++
  }

  fmt.Println(output.String())

  // Deallocate the subject, and the output.
  vm.Execute("free", inputPointer)
  vm.Execute("free", outputPointer)
  // ...
```
Here we copy bytes starting from the `outputPointer` to the host's `output` string builder and then we execute `free` on the `outputPointer`.

The questions are:
1) The `greet` function's resulting string was allocated inside wasm module, so, it should be GC-ed after a while by the wasm internal machinery. Why do we call `free` on the host side for it?
2) Even if we will not call `free` for the `outputPointer` in our example, where are the guarantees that wasm's internal GC will not come and collect our resulting string, somewhere in the middle of the process of reading bytes from it to the host's `output` string builder?
3) What is the correct way of returning a string result from a wasm function then?

Thank you.

Bonus question: Why do we have this weird line `memData, _ = mem.GetData(uint(0), uint(pageSize * 65536))` here? Is there a more elegant solution?

**Comment by alabulei1** [comment]
@DarumaDocker Could please check it out?

**Comment by DarumaDocker** [comment]
@vlkv thank you in advance！
1. You are right. `free` should not be called on the host side for it is not created by `malloc`.
2. I'm not sure if wasm's internal GC will start collecting before the host's work is done. I have made a test:
```go
package main

import (
  "fmt"
  "runtime"
)

const M = 3000000

func main() {
  p := x()
  fmt.Println(p)

  runtime.GC()

  p2 := x()
  fmt.Println(p2)

  *p = 1
}

func x() *byte {
  var b = make([]byte, M)
  for i := 0; i < M; i++ {
    b[i] = 0
  }
  p := &(b[0])
  return p
}
```
The output of this program in my computer will be:
```bash
$ go run main.go
0xc000180000
0xc000480000
```

If I comment out line `*p = 1`, the output will be:
```bash
$ go run main.go
0xc000180000
0xc000180000
```

This tells us if the returned pointer is being referenced then GC will not collect the memory. So I guess maybe in wasm scenario GC will never collect the memory until the wasm module is dropped by the host, cause the func is exported and the pointer is returned to the host so GC can't tell if it is referenced.

3 and the bonus. Please refer https://github.com/WasmEdge/WasmEdge/pull/2159. It returns a new pointer that includes the  string pointer and string length.

**Comment by vlkv** [comment]
Thank you for your response and investigation. However, your answer to the question 2, raises a problem. If your "maybe in wasm scenario GC will never collect the memory until the wasm module is dropped by the host" correct, then there will a memory leak during the whole life time of a wasm module?

Otherwise, how wasm GC will know about whether host still uses the returned string or not (and the string could be GCed)?

Also, this problem seems to me could be solved if there is a mechanism of calling "malloc" for the resulting string **from the inside wasm**, leaving for the host the responsibility to call "free" on it. Is this possible (to call "malloc" from the "greet" code)?

**Comment by DarumaDocker** [comment]
> Thank you for your response and investigation. However, your answer to the question 2, raises a problem. If your "maybe in wasm scenario GC will never collect the memory until the wasm module is dropped by the host" correct, then there will be a memory leak during the whole life time of a wasm module? Otherwise, how wasm GC will know about whether host still uses the returned string or not (and the string could be GCed)?

I'm afraid that memory leaks do occur.

---
> Also, this problem seems to me could be solved if there is a mechanism of calling "malloc" for the resulting string from the inside wasm, leaving for the host the responsibility to call "free" on it. Is this possible (to call "malloc" from the "greet" code)?

We can use host function to achieve:
```
package main

//void host(int, int);
import "C"
import (
  "strings"
  "unsafe"
)

func main() {}

//export greet
func greet(subject *int32) {
  nth := 0
  var subjectStr strings.Builder
  pointer := uintptr(unsafe.Pointer(subject))
  for {
    s := *(*int32)(unsafe.Pointer(pointer + uintptr(nth)))
    if s == 0 {
      break
    }

    subjectStr.WriteByte(byte(s))
    nth++
  }

  output := []byte("Hello, " + subjectStr.String() + "!")

  ptr := (C.int)(uintptr(unsafe.Pointer(&(output[0]))))
  length := (C.int)(len(output))
  C.host(ptr, length)
}
```

```
package main

import (
  "fmt"
  "os"

  "github.com/second-state/WasmEdge-go/wasmedge"
)

type host struct {
  result []byte
}
// Host function
func (h *host) getString(_ interface{}, callframe *wasmedge.CallingFrame, params []interface{}) ([]interface{}, wasmedge.Result) {
  ptr := params[0].(int32)
  size := params[1].(int32)
  mem := callframe.GetMemoryByIndex(0)
  data, _ := mem.GetData(uint(ptr), uint(size))
  h.result = make([]byte, size)
  copy(h.result, data)

  return []interface{}{}, wasmedge.Result_Success
}

func main() {
  wasmedge.SetLogErrorLevel()
  conf := wasmedge.NewConfigure(wasmedge.WASI)
  vm := wasmedge.NewVMWithConfig(conf)

  wasi := vm.GetImportModule(wasmedge.WASI)
  wasi.InitWasi(
    os.Args[1:],
    os.Environ(),
    []string{".:."},
  )

  /************************/
  h := host{}
  obj := wasmedge.NewModule("env")

  // Add host functions into the module instance
  funcFetchType := wasmedge.NewFunctionType(
    []wasmedge.ValType{
      wasmedge.ValType_I32,
      wasmedge.ValType_I32,
    },
    []wasmedge.ValType{
    })

  hostFunc := wasmedge.NewFunction(funcFetchType, h.getString, nil, 0)
  obj.AddFunction("host", hostFunc)

  vm.RegisterModule(obj)
  /************************/

  err := vm.LoadWasmFile(os.Args[1])
  if err != nil {
    fmt.Println("failed to load wasm")
  }
  vm.Validate()
  vm.Instantiate()

  subject := "WasmEdge"
  lengthOfSubject := len(subject)

  // Allocate memory for the subject, and get a pointer to it.
  // Include a byte for the NULL terminator we add below.
  allocateResult, _ := vm.Execute("malloc", int32(lengthOfSubject+1))
  inputPointer := allocateResult[0].(int32)

  // Write the subject into the memory.
  mod := vm.GetActiveModule()
  mem := mod.FindMemory("memory")
  memData, _ := mem.GetData(uint(inputPointer), uint(lengthOfSubject+1))
  copy(memData, subject)

  // C-string terminates by NULL.
  memData[lengthOfSubject] = 0

  // Run the `greet` function. Given the pointer to the subject.
  vm.Execute("greet", inputPointer)

  // Deallocate the subject, and the output.
  vm.Execute("free", inputPointer)

  fmt.Println(string(h.result))

  vm.Release()
  conf.Release()
}

```

Here we pass the pointer and length to the host function in the end of the wasm function, then the host can get the string.

**Comment by vlkv** [comment]
> Here we pass the pointer and length to the host function in the end of the wasm function, then the host can get the string.
Wow, this ensures that copying the data to the host destination will be completed before the `greet` returns, thus GC cannot deallocate the resulting string too early for sure. Cool, thank you. 

Except for the copying the string bytes, how big is the overhead of calling host function from wasm module?

**Comment by hydai** [comment]
> Except for the copying the string bytes, how big is the overhead of calling host function from wasm module?

WasmEdge is written in C++; hence, the copying overhead should be similar to copying a string from C++ to golang with CGO.

**Comment by vlkv** [comment]
Thank you very much!

So, I think this issue could be closed after the `1. ` will be fixed in WasmEdge docs https://github.com/WasmEdge/WasmEdge/issues/2156#issuecomment-1346213797
