### ISSUE TITLE
feat: enable `codespell` in the lint workflow

### ISSUE THREAD

**Issue by hydai** [WasmEdge/WasmEdge#2160]
### Motivation
The current workflow doesn't check the code spelling, which will allow some naive spelling errors in the commits. To reduce this situation, we would like to have a workflow to ensure the files in a PR are verified by `codespell.`

Please notice that some keywords will trigger false positives, so we have to maintain an ignore list.

---

I would suggest using codespell. Although it has some false positives, it can be suppressed via the `--ignore-words` file. The ability to misspell is limited.

Anyway, both tools have the option to fix typos automatically.

_Originally posted by @RRobot-lm in https://github.com/WasmEdge/WasmEdge/issues/2157#issuecomment-1346555798_

**Comment by RRobot-lm** [comment]
Assign to me?
