### ISSUE TITLE
Support Typed Function Reference Proposal

### ISSUE THREAD

**Issue by q82419** [WasmEdge/WasmEdge#2161]
## Motivation

The [typed function reference](https://github.com/WebAssembly/function-references) proposal is turned into phase 3.

## Details

1. Support this proposal.
2. Add the configurations and options in CLI.
3. Pass the spec test suite.

**Comment by q82419** [comment]
@little-willy ,

After overviewing your latest PRs, I think you want to contribute for the typed function reference proposal?
If that, can we collect all the issues and PRs into here, and merge the PRs into the `proposal/func-ref` branch?
Or the development will cause too much ABI compability issue.
When this proposal is completed, we'll merge that branch into master.

**Comment by little-willy** [comment]
@q82419 Sure. I will collect the related PRs and issues here and turn the target branch of the PRs from `master` to `proposal/func-ref`.

Before I change the target branch of the PR, can you update the `proposal/func-ref` to the latest `master`? Seems that I don't have to the privilege to do so.

**Comment by little-willy** [comment]
Related PRs:

Preliminary refactor:
* https://github.com/WasmEdge/WasmEdge/pull/2099
* https://github.com/WasmEdge/WasmEdge/pull/2107
* https://github.com/WasmEdge/WasmEdge/pull/2150

Loading:
* https://github.com/WasmEdge/WasmEdge/pull/2124
* https://github.com/WasmEdge/WasmEdge/pull/2125
* https://github.com/WasmEdge/WasmEdge/pull/2151

Validation:
* https://github.com/WasmEdge/WasmEdge/pull/2152

Execution:
* https://github.com/WasmEdge/WasmEdge/pull/2153
* https://github.com/WasmEdge/WasmEdge/pull/2158

**Comment by hydai** [comment]
> Before I change the target branch of the PR, can you update the `proposal/func-ref` to the latest `master`? Seems that I don't have to the privilege to do so.

Done.

**Comment by little-willy** [comment]
@hydai @q82419 I have turned all the related PRs above into merging into `proposal/func-ref`. You may start reviewing these PR in the order of PR number.

**Comment by q82419** [comment]
Hi @little-willy ,

I'll update the `proposal/func-ref` branch in these days with the refactor part.
Are the loader, validator, and execution PRs ready?
If that, can you help to update your branches?
Thanks.

**Comment by little-willy** [comment]
> Are the loader, validator, and execution PRs ready?

Yes, they are ready for review. 

I have updated the 3 PRs for the loader. You may start review them. Thanks

**Comment by q82419** [comment]
> > Are the loader, validator, and execution PRs ready?
> 
> Yes, they are ready for review.
> 
> I have updated the 3 PRs for the loader. You may start review them. Thanks

Thanks.
I'll update and fix the PR in these days.
When they are ready, I'll notice you then.

**Comment by q82419** [comment]
Our plan is to fully implement this proposal in these months.
So after the PRs being merged into the proposal branch, we'll merge it into master.

**Comment by hydai** [comment]
Due to some of the modifications will break the ABI, we plan to merge it into the master branch after the 0.12 official release.
We will review each PR and do a detailed review before it gets merged into the master branch.

**Comment by little-willy** [comment]
@q82419 Could you briefly describe your idea about the refactoring in general?

**Comment by q82419** [comment]
Well, there're several concepts:

1. I think the enum name should be renamed to `ValTypeCode`, and the `ValType` will become the class to store the value type data.
2. Due to the changes, the `ValType` size will be increased (former 1 byte). This will break the instruction class size, which contains the immediate data. I'll think which is the better way to implement the `ValType` class.

**Comment by q82419** [comment]
> I see.
> 
> At the very beginning I was trying to simply keep the naming `ValType`, but it seems that that will break the general API about `ValType`, and the previous programmer that use the WasmEdge API, for example, using `ValType::I32`, will fail to compile after they upgrade to the latest version. My refactoring can make the API backward compatible with the current release, and this is the reason why I choose to implement a separate `FullValType`. But if you agree that breaking the API is acceptable, I think we can refactor to reuse the name `ValType`.

I think the breaking of API will be necessary, because in the future, the `value type` must be extended in another WASM proposals. Thats why we choose to convert `ValType` into an opaque struct -- we only need to add the APIs to decode the `ValType`, and not need to break the ABI anymore.
The another reason of pending this proposal is that the breaking ABI should be done in the main versions, such as `0.13.0`. But as you seen, the `0.12.0` is still in progress now.

**Comment by q82419** [comment]
@little-willy please help to rebase the loading phase PRs on to the `proposal/func-ref` after PR #2350 being merged.
In these weeks, I'll help to generate the spec test suits of the function reference proposal for WasmEdge. I think this works for catching the hidden bugs.

**Comment by little-willy** [comment]
@q82419 I just rebased these 3 PRs to `proposal/func-ref`. Could you take a look? Sorry for the lateness.

**Comment by q82419** [comment]
@little-willy ,

Can you help to collect your PRs into a linear source tree?
For example, the PR 2125 can be the base of PR 2126.
With this, we can merge the next PR quickly when the first one reviewed.
Thanks!

**Comment by little-willy** [comment]
My PR are in the linear order of the comment https://github.com/WasmEdge/WasmEdge/issues/2161#issuecomment-1362507720.

Since we are doing rebase when we merge a PR, the next PR will get conflict with the base branch, because the next PR include the change of current PR, while after rebase, the base branch lose the parent information of current PR. To resolve the conflict, usually I will first merge the latest base branch into the current PR again, and then merge the current PR into the next PR, so that the next PR can merge the latest base without any conflict. 

I can do this after any PR gets merged. It should be quick.

**Comment by q82419** [comment]
Hi @little-willy ,

I've merged the loader phase.
Please update the validation phase. Thanks.

**Comment by q82419** [comment]
Due to the breaking changes in `master`, I've updated the `proposal/func-ref` branch.

**Comment by q82419** [comment]
Merged.
