### ISSUE TITLE
Which backend compiler does WasmEdge use in the AoT mode?

### ISSUE THREAD

**Issue by Zhangyx24** [WasmEdge/WasmEdge#2164]
Which backend compiler does WasmEdge use in the AoT mode?

**Comment by hydai** [comment]
We use LLVM framework as our ahead-of-time compilation backend.
Ref: https://github.com/WasmEdge/WasmEdge/blob/master/lib/aot/CMakeLists.txt#L4

**Comment by hydai** [comment]
This issue is answered. I'm closing this. If you have any other questions, please raise a new issue.
