### ISSUE TITLE
[Installer] New tensorflow dependency

### ISSUE THREAD

**Issue by q82419** [WasmEdge/WasmEdge#2180]
## Motivation

Due to using the tensorflow C++ API for the WASI-NN tensorflow backend in the future, we should update the tensorflow dependency in this `0.12.0` version.

## Details

After the `0.12.0-alpha.1` version, the `libtensorflow_cc.so.2.6.0` will replace the old `libtensorflow.so.2.6.0`, so does the `.dylib` on MacOS platforms.
Please update the symbilic linking and the target file name in the installer.

**Comment by SAtacker** [comment]
Thanks, on it.

**Comment by q82419** [comment]
> Thanks, on it.

Thanks for helping. I'll update the contents in the `WasmEdge-tensorflow-deps 0.12.0-alpha.1` tomorrow.

**Comment by q82419** [comment]
Hi @SAtacker ,

The `0.12.0-alpha.1` is ready.
You can test on it for the all extensions. Thanks.

**Comment by SAtacker** [comment]
At this particular moment, I am unable to access any raw.githubusercontent.com URL. As soon as I test it again, I'll notify.
