### ISSUE TITLE
 Installer consider use unified format in argument and backward compatible warning

### ISSUE THREAD

**Issue by CaptainVincent** [WasmEdge/WasmEdge#2193]
## Motivation

The recently updated installer change argument key and value.
It's should not broken other's project directly.

## Details

1. Key change
ex. os -> platform, arch -> machine
Maybe we could backward compatible old keys and pop warning before we decide deprecated them.

2. Platform value need first letter is capitalized
ex. Linux, Darwin
Not sure the rule is good for general purpose.

**Comment by hydai** [comment]
Hi @SAtacker 

We have identified the following issues in the runwasi (docker+wasmedge) integration:

1. Can we support the os and arch keys to avoid compatibility issues?
2. Users may specify a platform manually when building a docker image, but the platform string may not be standardized (e.g., Linux, linux, LINUX). It would be beneficial to standardize the platform strings before conducting any condition checks to avoid potential issues.

**Comment by SAtacker** [comment]
> 2\.

1. We do support. https://github.com/WasmEdge/WasmEdge/blob/c03994dcd84ecda561b30ff1fae3b79f960c42de/utils/install.py#L1642-L1662
2.  For platform and machine I have followed what the python standard docs have followed. [Python2.7](https://docs.python.org/2.7/library/platform.html) [python3.6+](https://docs.python.org/3.6/library/platform.html)

**Comment by SAtacker** [comment]
I think an installer documentation is necessary.

**Comment by SAtacker** [comment]
Documentation of all the policies and standardization we follow, what will happen in different cases, what versions we support etc, so that people don't have to go through the 1500+ lines of code.

**Comment by hydai** [comment]
Agreed. Could you let me know if you are going to scratch this? Or should we (@q82419 and @hydai) provide a base document first?

**Comment by SAtacker** [comment]
> Agreed. Could you let me know if you are going to scratch this? Or should we (@q82419 and @hydai) provide a base document first?

A base document will surely help. But if you have a PR link which I can refer to that'll save you some time. I will try to comment the installer appropriately and try generating docs from it.

**Comment by hydai** [comment]
Sure thing. I will create a draft PR after the new year. Happy holidays.

**Comment by SAtacker** [comment]
> Sure thing. I will create a draft PR after the new year. Happy holidays.

Thanks, happy holidays!

**Comment by SAtacker** [comment]
> Awesome, thanks. I wonder if I pass `--os linux` to the installer, will it pass, and the result is the same as `--os Linux`? Or will it fail?

Currently, it will display an error.

**Comment by SAtacker** [comment]
Working on it.

**Comment by SAtacker** [comment]
Done in ea1c7112

**Comment by SAtacker** [comment]
Now it has become case insensitive. Ex. `linux` is same as `LiNuX` is same as `Linux`.

**Comment by SAtacker** [comment]
Can we close this @hydai ?

**Comment by hydai** [comment]
Already fixed.
