### ISSUE TITLE
[Installer] Support $DIST for WasmEdge core

### ISSUE THREAD

**Issue by q82419** [WasmEdge/WasmEdge#2196]
### Current State

The `$DIST` only supports plug-ins. But for ABI compatibility and dependencies (especially for WASI-NN), the `ubuntu` and `manylinux2014` versions of WasmEdge core and plug-ins cannot be mixed.
The extensions like the `WasmEdge-tensorflow`, `WasmEdge-image` can be ignored because they work with C API.

### Expected

If the detected or assigned $DIST is `Ubuntu 20.04` or `manylinux2014`, should install the same WasmEdge and plugins.
For example, when install with the command on Ubuntu 20.04:

```bash
$ ./install.sh -v 0.12.0-alpha.1 -D
Using Python: /usr/bin/python3
DEBUG   - Python Version: sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0)
DEBUG   - Compat object: Platform:Linux
Machine:x86_64
Version:0.12.0-alpha.1
Extensions:[]
Dist:ubuntu20.04
```

Then the `Ubuntu 20.04` version of WasmEdge the specified `--plugins` plugins (if available) should be installed.

When install with the command on Ubuntu 20.04:

```bash
$ ./install.sh -v 0.12.0-alpha.1 -D --dist manylinux2014
Using Python: /usr/bin/python3
DEBUG   - Python Version: sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0)
DEBUG   - Compat object: Platform:Linux
Machine:x86_64
Version:0.12.0-alpha.1
Extensions:[]
Dist:manylinux2014
```

Then the `manylinux2014` version of WasmEdge and the specified `--plugins` plugins (if available) should be installed.

## Environment

- Hardware Architecture: x86_64
- Operating system: Ubuntu 20.04

**Comment by q82419** [comment]
cc @hydai 

If apply this, the default installation of WasmEdge on Ubuntu will be `Ubuntu 20.04` release, but not the `manylinux2014` before.
Please help to confirm if this is available.

**Comment by SAtacker** [comment]
Thanks for this @q82419 
By `plugins` do you mean these https://github.com/WasmEdge/WasmEdge/blob/master/utils/install.py#L326-L333 ?

**Comment by q82419** [comment]
> Thanks for this @q82419 By `plugins` do you mean these https://github.com/WasmEdge/WasmEdge/blob/master/utils/install.py#L326-L333 ?

Yes.

**Comment by hydai** [comment]
Hi @q82419,
Could you specify all existing versions and releases in a table to tell us which combinations will work?
Can some of the plugins use a fallback version (if the ubuntu20.04 is not found, then it uses manylinux2014) or something?

**Comment by hydai** [comment]
Hi @SAtacker 

To improve the compatibility and functionality of our Linux platforms, we will implement the following updates:

1. Offer support for the ubuntu distribution for all ubuntu versions greater than or equal to 20.04.
2. If the user is using the ubuntu distribution, install the ubuntu version first.
3. If the user is not using the ubuntu distribution, install the manylinux version.
4. If the plugin does not support the user's ubuntu version, do not fall back to the manylinux version by default. Instead, you can display an error message to inform the user and direct them to open an issue on our GitHub repository.
5. If the user specifies a specific version using the --dist option, we will install the corresponding version of wasmedge and plugins.


These changes are necessary due to the dependencies of the WASI-NN component, including PyTorch and TensorFlow, which have different ABIs in their libraries. We must therefore divide the installation process based on the Linux distribution being used.

What do you think? Does this make sense to you?

**Comment by SAtacker** [comment]
> 1. Offer support for the ubuntu distribution for all ubuntu versions greater than or equal to 20.04.

Currently we use https://github.com/WasmEdge/WasmEdge/blob/c03994dcd84ecda561b30ff1fae3b79f960c42de/utils/install.py#L1314-L1333
To summarize, we run the shell commands which can detect an ubuntu distribution. Currently it does not check if the version is greater than 20.04, it simply checks for Ubuntu 20.04.

> 2. If the user is using the ubuntu distribution, install the ubuntu version first.

Currently it happens only if there is ubuntu 20.04 as there are no other packages yet.

> 3. If the user is not using the ubuntu distribution, install the manylinux version.

Yep.

> 4. If the plugin does not support the user's ubuntu version, do not fall back to the manylinux version by default. Instead, you can display an error message to inform the user and direct them to open an issue on our GitHub repository.

If we do this then the CI will need to be handled differently as we test on Ubuntu 16 to latest.

> 5. If the user specifies a specific version using the --dist option, we will install the corresponding version of wasmedge and plugins.

That happens now as well, however below `0.11.1` we do not have ubuntu 20.04 package i guess, and thus for versions less than `0.11.1` I did not implement this functionality, we can however change this but then again CI will fail in some cases,

> These changes are necessary due to the dependencies of the WASI-NN component, including PyTorch and TensorFlow, which have different ABIs in their libraries. We must therefore divide the installation process based on the Linux distribution being used.

Agreed, we can divide it based on the distribution. Most of the mechanism is already in place. Just need to figure some of the above concerns. Thanks.

**Comment by hydai** [comment]
1. For all ubuntu versions greater than or equal to 20.04 (e.g., 22.04), we can use ubuntu20.04 as the default version.
2. For any ubuntu version less than 20.04 (e.g., 16.04, 18.04), install the manylinux version. The manylinux version is a better solution for users on legacy systems.
3. No need to alter the previous behavior. These updates should apply to the latest release, 0.12.x series.

**Comment by q82419** [comment]
I think the following steps can help:

1. Check the default distribution first (assume that store in the variable `$DIST`).
   a. Ubuntu 20.04 or greater: suite for ubuntu 20.04 version of WasmEdge and plug-ins. (`$DIST=ubuntu20.04`)
   b. Others: suite for manylinux2014 version. (`$DIST=manylinux2014`)
2. If user assigned the `--dist` target, overwrite the distribution. (`$DIST=assigned_dist`)
3. Check the assigned version to install (the latest release by default). If the ubuntu 20.04 release is select but the version (below 0.11.1) doesn't have the ubuntu release, fallback to manylinux2014. (`$DIST=manylinux2014`)
4. Check all picked plug-ins and install them with the `$DIST` release. If any plug-in doesn't have the `$DIST` version, not to install it and print an error message.

How do you think? cc @hydai  @SAtacker
