### ISSUE TITLE
[Installer] Update the plug-in table

### ISSUE THREAD

**Issue by q82419** [WasmEdge/WasmEdge#2198]
### Current State

As the supported plug-in table here:
https://github.com/WasmEdge/WasmEdge/blob/master/utils/install.py#L254-L263
Please help to update to the latest release (0.11.2).

### Expected

The list is:

`wasi_crypto` : ubuntu20.04 x86_64, manylinux2014 x86_64, manylinux2014 aarch64
`wasi_nn-openvino` : ubuntu20.04 x86_64
`wasi_nn-pytorch` : ubuntu20.04 x86_64, manylinux2014 x86_64
`wasi_nn-tensorflowlite` : ubuntu20.04 x86_64, manylinux2014 x86_64, manylinux2014 aarch64
`wasmedge_httpsreq` : ubuntu20.04 x86_64, manylinux2014 x86_64, manylinux2014 aarch64

**Comment by SAtacker** [comment]
Thanks for this!

**Comment by hydai** [comment]
@q82419 
Could you send a PR to #2207? So we can have a plugin matrix table.
