### ISSUE TITLE
[Installer] Can't install WasmEdge on maxOS with M2 chip

### ISSUE THREAD

**Issue by alabulei1** [WasmEdge/WasmEdge#2204]
### Current State

I followed the WasmEdge book's guide to install WasmEdge on my laptop. The log shows I installed WasmEdge successfully. But when I ran `wasmedge -v`, there was no results from the terminal

![image](https://user-images.githubusercontent.com/45785633/210334672-fb632791-3738-4026-9bb3-002ed627a0b9.png)

### Expected

If I installed WasmEdge successfully, the `wasmedge -v` command should output the right verison.
## Environment

- Hardware Architecture: aarch64
- Operating system: macOS Ventura

**Comment by alabulei1** [comment]
@SAtacker  Could you help me check it out?

**Comment by SAtacker** [comment]
Hi @alabulei1 , this is an ongoing PR to solve this. There's no need to source the .zshrc. Just source your zprofile again.

**Comment by SAtacker** [comment]
Thanks! Check out the discussion on PR related to https://github.com/WasmEdge/WasmEdge/issues/2187

**Comment by SAtacker** [comment]
You should not see this once https://github.com/WasmEdge/WasmEdge/pull/2192 is merged. Thanks!

**Comment by SAtacker** [comment]
Can you please check this again @alabulei1 ?

**Comment by alabulei1** [comment]
@SAtacker    It works now. I think this issue has been fixed. Thanks for your work.
