### ISSUE TITLE
feat: A Rust library crate for mediapipe models for WasmEdge NN

### ISSUE THREAD

**Issue by juntao** [WasmEdge/WasmEdge#2229]
## Motivation

[Mediapipe](https://google.github.io/mediapipe/) is a collection of ML models for streaming data. The official website provides Python, iOS, Android, and TFLite-JS SDKs for using those models. As WasmEdge is increasingly used in data streaming applications, we would like to build a Rust library crate that enables easy integration of Mediapipe models in WasmEdge applications.

## Details

Each Mediapipe model has [a description page](https://google.github.io/mediapipe/solutions/face_detection.html) that describes its input and output tensors. The [models](https://google.github.io/mediapipe/solutions/models.html) are available in Tensorflow Lite format, which is supported by the WasmEdge Tensorflow Lite plugin.

We need at least one set of library functions for each model in Mediapipe. Each library function takes in a media object and returns the inference result. The function performs the following tasks.

* Process the input media object (e.g., a byte array for a JPEG image) into a tensor for the model. As an example, you could use the Rust [imageproc](https://crates.io/crates/imageproc) crate to process the image into a vector.
* Use WasmEdge NN to run inference of the input tensor on the model.
* Collect and interpret the result tensor. 
  * The function should at least return a struct containing the output parameters described in the model description page. For example, a face detection function should return a vector of structs. Each struct contains the coordinates of a detected page.
  * The function should also return a visual representation of the inference results. For example, we should overlay detected face boundaries and landmarks on the original image. As an example, the [draw_hollow_rect_mut()](https://docs.rs/imageproc/0.23.0/imageproc/drawing/fn.draw_hollow_rect_mut.html) in [imageproc](https://crates.io/crates/imageproc) could be used to draw detected boundaries.

### Required skills

* Basic knowledge of Rust. If you are a C / Go / Java developer interested in learning Rust, [check out this](https://github.com/second-state/rust-examples).
* Experience in working with AI models (in Python or JS). Tensorflow Lite experience is a plus.
* Experience in image processing.

### Application process

Candidates who want to apply for this issue, please go to the LFX mentorship pages to apply. There are several requirements that the candidates must submit:

Apply this on the LFX mentorship website; the link is [here](https://mentorship.lfx.linuxfoundation.org/project/e4e6d486-e6df-475d-8074-a363d0361076).
Finish the pretest; the pretest is #2230.

**Comment by sarrah-basta** [comment]
Hello @juntao and WasmEdge Runtime Developers, 

I am Sarrah Bastawala, a third year undergraduate studying Computer Science and Information Technology at [VJTI, Mumbai, India](https://vjti.ac.in/) and am interested in contributing to this library in WasmEdge. I have already [worked](https://drive.google.com/file/d/1-ZnPX_kP3_0OpV37nrPA40LJTdvJ2IcZ/view?usp=sharing) with **Machine Learning and Computer Vision models in Python** for the past two years, and having done a project using Tensorflow-lite recently for quantization of a model to deploy it on the edge, I believe I would be a good fit to carry out this project. 

While I am not a Rust Developer, I have **experience with intensive C and C++ Coding**, being a [GSoC '22 mentee](https://summerofcode.withgoogle.com/archive/2022/projects/fg4hsOK0), and have even gone through the [suggested examples](https://github.com/second-state/rust-examples) and acquired some basic knowledge of Rust.  

Thus having met the required qualifications, I am currently _working on the linked pretest_ and I believe the link to apply on the LFX portal has not yet been put up. I look forward to guidance regarding any other requirements I need to fulfill, such as self assigning this issue, etc.

**Comment by carrycooldude** [comment]
Hey @juntao 
I am Kartikey Rawat and I am passionate about Open Source and Engineering I have also been working in Developer Advocacy for 2 years now and I am proficient with TypeScript, JavaScript, Frontend Development, API, etc. Also, I worked with Postman and Turing as a Developer Advocate and Community Role with this I also contributed to one of the most significant Open Source projects TensorFlow where I contributed to the backend-wasm part of TensorflowJS(TFJS).
My Merged PRs: 1) https://github.com/tensorflow/tfjs/pull/5260
2) https://github.com/tensorflow/tfjs/pull/4826
I also created a project on TensorFlow.js: https://github.com/carrycooldude/tfjs-linear-regression

**Comment by juntao** [comment]
Hi Kartikey,

Thank you for your interest! Look forward to your solution to the pretest!

Cheers
Michael

> Hey @juntao 
> 
> I am Kartikey Rawat and I am passionate about Open Source and Engineering I have also been working in Developer Advocacy for 2 years now and I am proficient with TypeScript, JavaScript, Frontend Development, API, etc. Also, I worked with Postman and Turing as a Developer Advocate and Community Role with this I also contributed to one of the most significant Open Source projects TensorFlow where I contributed to the backend-wasm part of TensorflowJS(TFJS).
> 
> My Merged PRs: 1) https://github.com/tensorflow/tfjs/pull/5260
> 
> 2) https://github.com/tensorflow/tfjs/pull/4826
> 
> I also created a project on TensorFlow.js: https://github.com/carrycooldude/tfjs-linear-regression

**Comment by sarrah-basta** [comment]
Hello @juntao 

I have submitted my application to the [LFX mentorship page](https://mentorship.lfx.linuxfoundation.org/project/e4e6d486-e6df-475d-8074-a363d0361076) and updated the source code to my solution repository to the pretest #2230 at https://github.com/sarrah-basta/wasmedge-wasinn-mediapipe-facedet-demo.git. 
Looking forward to the review on my application and tasks and feedback on my solution to the pretest ! 
In the meanwhile, are there any requirements I would be needed to fulfill ? 

> Hello @juntao and WasmEdge Runtime Developers,
> 
> I am Sarrah Bastawala, a third year undergraduate studying Computer Science and Information Technology at [VJTI, Mumbai, India](https://vjti.ac.in/) and am interested in contributing to this library in WasmEdge. I have already [worked](https://drive.google.com/file/d/1-ZnPX_kP3_0OpV37nrPA40LJTdvJ2IcZ/view?usp=sharing) with **Machine Learning and Computer Vision models in Python** for the past two years, and having done a project using Tensorflow-lite recently for quantization of a model to deploy it on the edge, I believe I would be a good fit to carry out this project.
> 
> While I am not a Rust Developer, I have **experience with intensive C and C++ Coding**, being a [GSoC '22 mentee](https://summerofcode.withgoogle.com/archive/2022/projects/fg4hsOK0), and have even gone through the [suggested examples](https://github.com/second-state/rust-examples) and acquired some basic knowledge of Rust.
> 
> Thus having met the required qualifications, I am currently _working on the linked pretest_ and I believe the link to apply on the LFX portal has not yet been put up. I look forward to guidance regarding any other requirements I need to fulfill, such as self assigning this issue, etc.

**Comment by juntao** [comment]
Thank you! No further action is needed at this time. Thank you!

> I have submitted my application to the [LFX mentorship page](https://mentorship.lfx.linuxfoundation.org/project/e4e6d486-e6df-475d-8074-a363d0361076) and updated the source code to my solution repository to the pretest #2230 at https://github.com/sarrah-basta/wasmedge-wasinn-mediapipe-facedet-demo.git. 
> 
> Looking forward to the review on my application and tasks and feedback on my solution to the pretest ! 
> 
> In the meanwhile, are there any requirements I would be needed to fulfill ? 
> 
>

**Comment by ktwillcode** [comment]
hi @juntao 
Kartikeya this side, I applied for the mentorship and submitted a Cover letter and Resume. Is there anything more to complete the process?

**Comment by alabulei1** [comment]
@ktwillcode Hi Kartikeya, Thank you for your application. You also need to complete pretest #2230.

> hi @juntao Kartikeya this side, I applied for the mentorship and submitted a Cover letter and Resume. Is there anything more to complete the process?

**Comment by Shashang2303** [comment]
hi @juntao Shashang this side, I applied for the mentorship and submitted a cover letter and resume. This is my first time to join for the open source project and looking forward to showcase my skills and contribution for the project.

**Comment by hydai** [comment]
This should be fixed. See https://github.com/WasmEdge/mediapipe-rs

Closing it.
