### ISSUE TITLE
[wasmedge-java] Failing to build bindings, please help or provide binaries

### ISSUE THREAD

**Issue by proohit** [WasmEdge/WasmEdge#2234]
### Current State

Currently, bindings for Go and Rust have been published, but the Java bindings have to be built manually. By the way, the building fails locally on my end:

```sh
wasmedge-java $ gradle build
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

> Task :compileJava
Note: .../wasmedge-java/src/main/java/org/wasmedge/ExternRef.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :compileJNI FAILED
-- wasmedge root: 
-- wasmedge include dirs: WasmEdge_INCLUDE_DIRS-NOTFOUND
-- wasmedge lib: 
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find WasmEdge (missing: WasmEdge_INCLUDE_DIRS WasmEdge_LIBRARIES)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  FindWasmEdge.cmake:63 (find_package_handle_standard_args)
  CMakeLists.txt:10 (find_package)
```

```sh
$HOME/.wasmedge
├── bin
│   ├── show-tflite-tensor
│   ├── wasmedge
│   ├── wasmedge-tensorflow
│   ├── wasmedge-tensorflow-lite
│   └── wasmedgec
├── env
├── include
│   └── wasmedge
│       ├── enum.inc
│       ├── enum_configure.h
│       ├── enum_errcode.h
│       ├── enum_types.h
│       ├── int128.h
│       ├── version.h
│       ├── wasmedge-image.h
│       ├── wasmedge-tensorflow.h
│       ├── wasmedge-tensorflowlite.h
│       └── wasmedge.h
├── lib
│   ├── libtensorflow.so -> /home/direnc/.wasmedge/lib/libtensorflow.so.2.6.0
│   ├── libtensorflow.so.2 -> /home/direnc/.wasmedge/lib/libtensorflow.so.2.6.0
│   ├── libtensorflow.so.2.6 -> /home/direnc/.wasmedge/lib/libtensorflow.so.2.6.0
│   ├── libtensorflow.so.2.6.0
│   ├── libtensorflow_framework.so -> /home/direnc/.wasmedge/lib/libtensorflow_framework.so.2.6.0
│   ├── libtensorflow_framework.so.2 -> /home/direnc/.wasmedge/lib/libtensorflow_framework.so.2.6.0
│   ├── libtensorflow_framework.so.2.6 -> /home/direnc/.wasmedge/lib/libtensorflow_framework.so.2.6.0
│   ├── libtensorflow_framework.so.2.6.0
│   ├── libtensorflowlite_c.so
│   ├── libwasmedge-image_c.so
│   ├── libwasmedge-tensorflow_c.so
│   ├── libwasmedge-tensorflowlite_c.so
│   ├── libwasmedge.so -> libwasmedge.so.0
│   ├── libwasmedge.so.0 -> libwasmedge.so.0.0.1
│   └── libwasmedge.so.0.0.1
└── plugin
    └── libwasmedgePluginWasmEdgeProcess.so
```

### Expected

Could you kindly provide the binaries for Java so that users are able to integrate it directly?

## Environment
x86_64
Ubuntu 20.04

The following information is optional. Please provide them only if you have built from source.
- C++ Compiler version: gcc 9.4.0
- CMake version: 3.16.3
- CMake flags: (e.g. `-DCMAKE_BUILD_TYPE=Release -DWASMEDGE_BUILD_AOT_RUNTIME=ON`) see wasmedge-java
- wasmedge: 0.11.2

I have installed wasmedge with `install.sh` without setting any env vars.

**Comment by alabulei1** [comment]
@kenvifire  Could you please check it out?

**Comment by kenvifire** [comment]
Hi @proohit 

Sorry for this issue.

It's caused by WasmEdge root dir not found.
You can add `export WasmEdge_ROOT=wasm_edge_root` before gradle build.

**Comment by proohit** [comment]
Yep, `export WasmEdge_ROOT=$HOME/.wasmedge` did the trick. 

I copied `wasmedge-java.jar` to my project to root `libs/` folder and added it as a dependency with gradle:

```groovy
dependencies {
    ...
    implementation files('libs/wasmedge-java.jar')
}
```

And it finds all the classes correctly:

```java
import java.util.List;

import org.wasmedge.ConfigureContext;
import org.wasmedge.StoreContext;
import org.wasmedge.WasmEdge;
import org.wasmedge.WasmEdgeVm;
import org.wasmedge.enums.HostRegistration;

public class App {
    public static void main(String[] args) {
        // Init wasmedge
        WasmEdge.init();
        ConfigureContext config = new ConfigureContext();
        config.addHostRegistration(
                HostRegistration.WasmEdge_HostRegistration_Wasi);
        StoreContext store = new StoreContext();
        // Create WasmEdgeVM
        WasmEdgeVm vm = new WasmEdgeVm(config, store);
        vm.registerModuleFromFile("custom_framework", "libs/custom_framework_wasm.wasm");
        vm.executeRegistered("custom_framework", "start", List.of(), List.of());
    }
}
```

But the jni binding need to be on a known path, because:

```sh
./gradlew run

> Task :run FAILED
Exception in thread "main" java.lang.UnsatisfiedLinkError: no wasmedge_jni in java.library.path: /home/direnc/.wasmedge/lib:/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2429)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
        at java.base/java.lang.System.loadLibrary(System.java:1989)
        at org.wasmedge.WasmEdge.init(WasmEdge.java:18)
        at custom_framework.App.main(App.java:17)
```

So adding `wasmedge-java/build/native/libwasmedge_jni.so` to `$HOME/.wasmedge/lib` worked:
```sh
cp build/native/libwasmedge_jni.so $HOME/.wasmedge/lib/
```

Yet again, would it be possible to publish a ready to use package somewhere, just like `wasmedge_sdk` and `WasmEdge-Go`? That way, users would not have to build the bindings themselves and linking works out of the box.

**Comment by kenvifire** [comment]
@proohit 
Thanks for your suggestion. I'm working on publishing a ready to use package. It's delayed. because of the Chinese New Year. I'll continue working on it once I'm back from holidays.

Thanks,
Kenvi

**Comment by proohit** [comment]
@kenvifire thanks, happy new year and have some nice holidays.

**Comment by proohit** [comment]
Hey :) Following up on that issue, is there any news on a ready-to-use java package? It's getting a little cumbersome to support win, linux and osx while building and providing all bindings myself^^

I think it's easy to distribute a fully contained jar by:
1. building all platform dependent jni bindings separately and put them somewhere accessible e.g. `resources`
2. use `NativeUtils.loadLibraryFromJar("/resources/wasmedge.so");` instead of `loadLibraryWithPath` to access platform dependent binding from `resources`
3. I don't know if this is done automatically, but maybe bundling bindings into jar might be necessary:
```gradle
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    from sourceSets.main.output

    dependsOn configurations.runtimeClasspath
    from {
        //... plus all other bindings
        configurations.runtimeClasspath.findAll { it.name.endsWith('jar'); it.name.endsWith('so') }.collect { zipTree(it) }
    }
```

Let me hear what you think :)

**Comment by proohit** [comment]
Oh just seeing now that work was started in https://github.com/WasmEdge/WasmEdge/pull/2297 for that. Is there anything I can help with or do you have other priorities right now?

**Comment by alabulei1** [comment]
@proohit It's great to hear that you are interested in contributing to the WasmEdge Java library. As far as I know,  there're two bugs in #2297. You're welcome to contribute!

**Comment by proohit** [comment]
@alabulei1 thanks for getting back. What are the bugs, are they documented anywhere? And could you run the CI again, the logs aren't accessible anymore unfortunately ^^

**Comment by alabulei1** [comment]
I need to ask @kenvifire 's help to give more details on this. I'll get back to you soon. 

@q82419 Could you please help run the CI again? Thanks.

**Comment by q82419** [comment]
I've update that PR to base on the latest master.
You can check the changes and the CI results. Thanks.

**Comment by kenvifire** [comment]
> @alabulei1 thanks for getting back. What are the bugs, are they documented anywhere? And could you run the CI again, the logs aren't accessible anymore unfortunately ^^

Sorry for the late reply.
There are a few flaky tests, somehow JVM keeps crashing. You can take a look at them. I've already added steps to catch JVM crash logs.

**Comment by proohit** [comment]
hey, is there any news on this?^^

**Comment by juntao** [comment]
Hi @proohit 

We do not have resources to maintain a Java binding at this time. Do you have a concrete use case that requires Java to go to production? If so, we may consider prioritize it. Thanks!

**Comment by proohit** [comment]
It's not that important, I will proceed to build it myself. Though I am having some trouble to get it to work on OSX ARM64.

I was able to build the jni lib:
```sh
$ ./gradlew build -x test

> Task :compileJNI
-- wasmedge root: /Users/Direnc/.wasmedge
-- wasmedge include dirs: /Users/Direnc/.wasmedge/include
-- wasmedge lib: /Users/Direnc/.wasmedge/lib/libwasmedge.dylib
-- Configuring done (0.2s)
-- Generating done (0.0s)
-- Build files have been written to: /Users/Direnc/workspace/WasmEdge/bindings/java/wasmedge-java/build/native
[100%] Built target wasmedge_jni

BUILD SUCCESSFUL in 874ms
6 actionable tasks: 1 executed, 5 up-to-date
$ cp build/native/libwasmedge_jni.dylib $HOME/.wasmedge/lib
```

But still Java cannot find the lib:

```sh
$ ./gradlew run

> Task :run FAILED
Exception in thread "main" java.lang.UnsatisfiedLinkError: no wasmedge_jni in java.library.path: [/Users/Direnc/.wasmedge/lib/]
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2673)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
        at java.base/java.lang.System.loadLibrary(System.java:1873)
        at org.wasmedge.WasmEdge.init(WasmEdge.java:18)
        at custom_framework.ModuleWrapper.<init>(ModuleWrapper.java:36)
        at custom_framework.Server.start(Server.java:11)
        at custom_framework_example.App.main(App.java:13)

FAILURE: Build failed with an exception.
```

Here's the wasmedge lib dir:

```sh
$ ls $HOME/.wasmedge/lib                   
libwasmedge.0.0.1.dylib libwasmedge.0.dylib     libwasmedge.dylib       libwasmedge_jni.dylib
```

Maybe @kenvifire has an idea?

**Comment by kenvifire** [comment]
I'll come back to this issue next weekend. Have a baby recently, keepes me busy for a while. Sorry for the delay.
