### ISSUE TITLE
Ability to limit max memory for the wasm guest program from the Go host side

### ISSUE THREAD

**Issue by vlkv** [WasmEdge/WasmEdge#2235]
## Motivation

In my use case I have to run wasm programs on my server side (Go host) and I want to be able to explicitly set max memory size limits which could be consumed by any wasm (untrusted) program. In case wasm program will attempt to allocate more memory, let it fail with some kind of OOM error.

## Details

How about to have an option in Configuration, similar to MaxMemoryPage? Something like a MaxMemoryPagesCount:
```
import "github.com/second-state/WasmEdge-go/wasmedge"
//...
conf := wasmedge.NewConfigure(wasmedge.WASI)
conf.SetMaxMemoryPagesCount(100)
vm := wasmedge.NewVMWithConfig(conf)
// ...
```
?

UPDATE: It would be great to be able to limit both heap and stack memory.

**Comment by hydai** [comment]
Hi @vlkv 
This configuration is already provided: https://github.com/second-state/WasmEdge-go/blob/master/wasmedge/configure.go#L123-L129

**Comment by hydai** [comment]
Hi @vlkv 
I would like to know if the above configuration fits your requirement.

**Comment by vlkv** [comment]
Hi, @hydai 
If you are about
```
func (self *Configure) SetMaxMemoryPage(pagesize uint) {
	C.WasmEdge_ConfigureSetMaxMemoryPage(self._inner, C.uint32_t(pagesize))
}

func (self *Configure) GetMaxMemoryPage() uint {
	return uint(C.WasmEdge_ConfigureGetMaxMemoryPage(self._inner))
}
```
then, I guess, no.

**Comment by hydai** [comment]
Just want to know the requirement is setting and getting the max memory page.
If so, the functions are already exposed in Go SDK.

**Comment by vlkv** [comment]
I have already found this functionality in wasmtime. So, I switched to it for now.

**Comment by vlkv** [comment]
For your reference, this functionality in wasmtime-go is https://github.com/bytecodealliance/wasmtime-go/pull/171/files

**Comment by dannypsnl** [comment]
Can you explain how it didn't fit your requirement more? I didn't see difference.

**Comment by dannypsnl** [comment]
I think we already have this ability, stack limitation is not in the plan as I know. If that really is an issue, feel free to open a new issue for that.
