### ISSUE TITLE
Provide test images for Arm64 linux

### ISSUE THREAD

**Issue by Patrick0308** [WasmEdge/WasmEdge#2237]
## Motivation
Provide example-wasi  and example-wasi-http images for Arm64 linux

**Comment by hydai** [comment]
Hi @Patrick0308 
These two images are built with the `wasi/wasm` target. They only contain wasm files. I don't know what you mean in this context.

**Comment by Patrick0308** [comment]
On docker repo webpage, example-wasi and example-wasi-http images's arch is amd64. But it seems everything is ok if they only contain wasm files.
