### ISSUE TITLE
feat: provide a mock wasi-nn component in the wasmedge core

### ISSUE THREAD

**Issue by hydai** [WasmEdge/WasmEdge#2240]
## Motivation

This is a rough idea. Please discuss the details before we implement it.

WasmEdge uses plugins to handle the WASI-NN component. However, if users don't install the wasi-nn plugins or users install the plugins with something wrong. Then, WasmEdge may report the import function not found errors. To reduce the confusion, it's better to provide a mock component; it will say, `Please install wasi-nn plugin errors` if users try to call the wasi-nn without installing it. Or it will use the wasi-nn in the plugins to replace this mock component.

/cc @q82419

**Comment by juntao** [comment]
I think this is a good idea provided that it does not take too much space in WasmEdge itself.
