### ISSUE TITLE
Get "execution failed: unreachable, Code: 0x89" for rust process::id()

### ISSUE THREAD

**Issue by LiangFang001** [WasmEdge/WasmEdge#2250]
Hello:
I change rust/birds_v1/src/main.rs by following patch:
![image](https://user-images.githubusercontent.com/43950861/216247253-4c234fa8-616a-417f-9a23-b5c9bbcc9ce6.png)
and get error:
![image](https://user-images.githubusercontent.com/43950861/216247362-8544b6ff-c132-409a-8b47-1bedd894de60.png)
do some operations not supperted?

**Comment by hydai** [comment]
Hi @LiangFang001 
The process id is not supported by the WASI spec. So it's not possible to get the value from WASM/WASI side.
