### ISSUE TITLE
use birds_v2.wasm on android app

### ISSUE THREAD

**Issue by LiangFang001** [WasmEdge/WasmEdge#2251]
Hello:
I reference https://github.com/second-state/wasm-learning/blob/master/android/test.c on android NDK and succuss call `birds_v2.wasm`
but selinux denied when rust access `/sdcard/wasmedge/lite-model_aiy_vision_classifier_birds_V1_3.tflite`, and i have alloc `READ_EXTERNAL_STORAGE` and `WRITE_EXTERNAL_STORAGE` permission for app.
![image](https://user-images.githubusercontent.com/43950861/216278755-26b37cb1-83eb-43c8-a045-00e49e5db576.png)

disable selinux by `setenforce 0` will works.
![image](https://user-images.githubusercontent.com/43950861/216277983-aad56441-3a7e-41ae-b062-223ffa53c354.png)

any other way to use on android app?

**Comment by hydai** [comment]
Thanks for reporting this.

Hi, @hangedfish do you have ideas about this issue?

**Comment by hangedfish** [comment]
Did you grant permissions in the GUI? https://developer.android.com/about/versions/marshmallow/android-6.0-changes#behavior-runtime-permissions

**Comment by LiangFang001** [comment]
Yes, I can read `/sdcard/wasmedge/lite-model_aiy_vision_classifier_birds_V1_3.tflite ` by ` fopen` on NDK C++ and kotlin, but birds_v2.wasm can't read this file

**Comment by hangedfish** [comment]
What is the path mapped in WASI. It is not possible to map `/` on Android, you can try to map `/sdcard/wasmedge`.

**Comment by LiangFang001** [comment]
solved, thanks ! 
![image](https://user-images.githubusercontent.com/43950861/216308460-8950867b-0c55-469f-95a8-e7f09325e554.png)

**Comment by hangedfish** [comment]
As of now, in WasmEdge, it is not possible to map a directory without read permissions to WASI, and open will return -1.

https://github.com/WasmEdge/WasmEdge/blob/4c37361fa44a6c2860b922ef3af3af594bb760c8/lib/host/wasi/inode-linux.cpp#L175

This issue will also be present in other WebAssembly Runtimes.

https://github.com/bytecodealliance/wasm-micro-runtime/issues/2120

I suggest adding a compile-time option to disable the file system sandbox restrictions.
