### ISSUE TITLE
When using WasmEdge *Host Function* with *Threads proposal*, VM would meet some unknown errors.

### ISSUE THREAD

**Issue by aetiurf** [WasmEdge/WasmEdge#2253]
### Current State

When using WasmEdge *Host Function* with *Threads proposal*, VM would meet some unknown errors.

But when using *Host Function* or *Threads proposal* respectively, there is no errors happen.

### Expected

It should output the result:

`Get result: 100`

but got:
```
[error] execution failed: out of bounds memory access, Code: 0x88
[error]     When executing function name: "func"
Error message: out of bounds memory access
```

## Environment

- Hardware Architecture: x86\_64
- Operating system: Ubuntu 22.04.1 LTS

## Steps to Reproduce

Minimized reproduction in my [repo](https://github.com/aetiurf/WasmEdge_error_reproduction), written with WasmEdge C SDK.

**Comment by hydai** [comment]
Hi @aetiurf 
It looks like a bug in our AOT compiler. I changed your code by using un-compiled pure wasm, and it just works. However, using wasmedgec to compile and execute will trigger this error.

**Comment by aetiurf** [comment]
> Hi @aetiurf It looks like a bug in our AOT compiler. I changed your code by using un-compiled pure wasm, and it just works. However, using wasmedgec to compile and execute will trigger this error.

Yes, it works on pure wasm. thanks.

**Comment by aetiurf** [comment]
Hi @hydai 
Excuse me. How soon can this bug be fixed?

**Comment by Celebraty** [comment]
i have the same issue when using wasmedge-go, can we update the wasmedge-go after the bug fixed?

**Comment by hydai** [comment]
Hi @aetiurf 
I just used the latest master (https://github.com/WasmEdge/WasmEdge/commit/cce22069d3e6e5a4ac6607b990c4709ed574ebcc) to run your example.

I have a patch to change the `include/lib/binary path`, because I am using a local built version instead of the installer one:

```
diff --git a/Makefile b/Makefile
index 7f31c29..13be1b9 100644
--- a/Makefile
+++ b/Makefile
@@ -1,7 +1,7 @@
 MAKE = make

 all: reproduction.cpp wat2so
-       g++ reproduction.cpp -lwasmedge -o reproduction -g
+       g++ reproduction.cpp -I/home/hydai.linux/WasmEdge/build/include/api -L/home/hydai.linux/WasmEdge/build/lib/api -lwasmedge -o reproduction -g

 cpp2so: func.cpp
        clang++ func.cpp --target=wasm32 -emit-llvm -c -S
@@ -12,7 +12,7 @@ cpp2so: func.cpp

 wat2so: func.wat
        wat2wasm func.wat --enable-all
-       wasmedgec --enable-all func.wasm func.so
+       /home/hydai.linux/WasmEdge/build/tools/wasmedge/wasmedgec --enable-all func.wasm func.so

 clean:
-       rm -rf reproduction *.wasm *.so
\ No newline at end of file
+       rm -rf reproduction *.wasm *.so
```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.10
Release:	22.10
Codename:	kinetic
$ wasmedge -v
/home/hydai.linux/WasmEdge/build/tools/wasmedge/wasmedge version 0.12.0-14-gcce22069
$ make
wat2wasm func.wat --enable-all
/home/hydai.linux/WasmEdge/build/tools/wasmedge/wasmedgec --enable-all func.wasm func.so
[2023-05-04 09:37:11.654] [info] compile start
[2023-05-04 09:37:11.655] [info] verify start
[2023-05-04 09:37:11.655] [info] optimize start
[2023-05-04 09:37:11.659] [info] codegen start
[2023-05-04 09:37:11.662] [info] output start
[2023-05-04 09:37:11.665] [info] compile done
g++ reproduction.cpp -I/home/hydai.linux/WasmEdge/build/include/api -L/home/hydai.linux/WasmEdge/build/lib/api -lwasmedge -o reproduction -g
$ LD_LIBRARY_PATH=~/WasmEdge/build/lib/api ./reproduction
Get result: 100
```

### Snapshots

#### Diff
![CleanShot 2023-05-04 at 17 37 48](https://user-images.githubusercontent.com/2776756/236168331-7cc6fca4-156b-4a96-8b73-35c3dbc0ac15.png)


#### Version
![CleanShot 2023-05-04 at 17 38 23](https://user-images.githubusercontent.com/2776756/236168442-efa5ccec-2d2e-4582-b5b1-8d3addc04631.png)


#### Execution
![CleanShot 2023-05-04 at 17 38 48](https://user-images.githubusercontent.com/2776756/236168553-ac0dbbb0-2ec9-40c1-a65c-f54d703c499b.png)

**Comment by aetiurf** [comment]
> Hi @aetiurf I just used the latest master ([cce2206](https://github.com/WasmEdge/WasmEdge/commit/cce22069d3e6e5a4ac6607b990c4709ed574ebcc)) to run your example.
> 
> I have a patch to change the `include/lib/binary path`, because I am using a local built version instead of the installer one:
> 
> ```
> diff --git a/Makefile b/Makefile
> index 7f31c29..13be1b9 100644
> --- a/Makefile
> +++ b/Makefile
> @@ -1,7 +1,7 @@
>  MAKE = make
> 
>  all: reproduction.cpp wat2so
> -       g++ reproduction.cpp -lwasmedge -o reproduction -g
> +       g++ reproduction.cpp -I/home/hydai.linux/WasmEdge/build/include/api -L/home/hydai.linux/WasmEdge/build/lib/api -lwasmedge -o reproduction -g
> 
>  cpp2so: func.cpp
>         clang++ func.cpp --target=wasm32 -emit-llvm -c -S
> @@ -12,7 +12,7 @@ cpp2so: func.cpp
> 
>  wat2so: func.wat
>         wat2wasm func.wat --enable-all
> -       wasmedgec --enable-all func.wasm func.so
> +       /home/hydai.linux/WasmEdge/build/tools/wasmedge/wasmedgec --enable-all func.wasm func.so
> 
>  clean:
> -       rm -rf reproduction *.wasm *.so
> \ No newline at end of file
> +       rm -rf reproduction *.wasm *.so
> ```
> 
> ```
> $ lsb_release -a
> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 22.10
> Release:	22.10
> Codename:	kinetic
> $ wasmedge -v
> /home/hydai.linux/WasmEdge/build/tools/wasmedge/wasmedge version 0.12.0-14-gcce22069
> $ make
> wat2wasm func.wat --enable-all
> /home/hydai.linux/WasmEdge/build/tools/wasmedge/wasmedgec --enable-all func.wasm func.so
> [2023-05-04 09:37:11.654] [info] compile start
> [2023-05-04 09:37:11.655] [info] verify start
> [2023-05-04 09:37:11.655] [info] optimize start
> [2023-05-04 09:37:11.659] [info] codegen start
> [2023-05-04 09:37:11.662] [info] output start
> [2023-05-04 09:37:11.665] [info] compile done
> g++ reproduction.cpp -I/home/hydai.linux/WasmEdge/build/include/api -L/home/hydai.linux/WasmEdge/build/lib/api -lwasmedge -o reproduction -g
> $ LD_LIBRARY_PATH=~/WasmEdge/build/lib/api ./reproduction
> Get result: 100
> ```
> 
> ### Snapshots
> #### Diff
> ![CleanShot 2023-05-04 at 17 37 48](https://user-images.githubusercontent.com/2776756/236168331-7cc6fca4-156b-4a96-8b73-35c3dbc0ac15.png)
> 
> #### Version
> ![CleanShot 2023-05-04 at 17 38 23](https://user-images.githubusercontent.com/2776756/236168442-efa5ccec-2d2e-4582-b5b1-8d3addc04631.png)
> 
> #### Execution
> ![CleanShot 2023-05-04 at 17 38 48](https://user-images.githubusercontent.com/2776756/236168553-ac0dbbb0-2ec9-40c1-a65c-f54d703c499b.png)

Yes, the bug is fixed, thanks.
I would close this issue.
