### ISSUE TITLE
Cannot create static binaries using rust `wasmedge-sys` crate

### ISSUE THREAD

**Issue by brandond** [WasmEdge/WasmEdge#2257]
### Current State

Cannot build 

### Expected

Able to build static binary

## Environment

- Hardware Architecture: x86\_64
- Operating system: Alpine

```
- C++ Compiler version: clang 15.0.7
- CMake version: 3.24.3
- CMake flags: '-DCMAKE_BUILD_TYPE=Release' '-DWASMEDGE_BUILD_STATIC_LIB=ON' '-DWASMEDGE_BUILD_SHARED_LIB=OFF' '-DWASMEDGE_BUILD_AOT_RUNTIME=OFF' '-DWASMEDGE_BUILD_TOOLS=OFF' -Wno-dev
- Boost version: 1.80
```

## Steps to Reproduce

1. configure and build as described above
2. Attempt to perform cargo static build; in this case from containerd/runwasi
```bash
export 'RUSTFLAGS=-C target-feature=+crt-static'
export 'RUST_ARCH=x86_64-unknown-linux-musl'
cargo build --release '--bin=containerd*wasmtime*' '--bin=containerd-*wasmedge*' '--target=x86_64-unknown-linux-musl'
```

End of build log:
```
   Compiling wasmedge-sys v0.12.2
The following warnings were emitted during compilation:

warning: [wasmedge-sys] libwasmedge found in /usr/local/lib

error: failed to run custom build command for `wasmedge-sys v0.12.2`

Caused by:
  process didn't exit successfully: `/drone/src/target/release/build/wasmedge-sys-97faca40c6bbe06f/build-script-build` (exit status: 101)
  --- stdout
  cargo:warning=[wasmedge-sys] libwasmedge found in /usr/local/lib

  --- stderr
  thread 'main' panicked at 'Unable to find libclang: "the `libclang` shared library at /usr/lib/libclang.so.15.0.7 could not be opened: Dynamic loading not supported"', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.61.0/./lib.rs:2276:31
```

**Comment by brandond** [comment]
Possibly related: https://github.com/tikv/grpc-rs/issues/477

**Comment by brandond** [comment]
Oh, I see it's due to https://github.com/WasmEdge/WasmEdge/blob/e19b5972b130d18d65e93a93f04724bd9d5e88d6/bindings/rust/wasmedge-sys/build.rs#L36

It looks like this might be fixed on master; I'll take a shot at building with that.

**Comment by brandond** [comment]
I just realized that the cargo build is probably not using the crate from the local build. I'm awfully new at the rust toolchain, but I'll try to figure out how to get it to use the one from the WasmEdge build.

**Comment by brandond** [comment]
Updating runwasi to point at the packages from a checkout of wasmedge master seemed to be working, but the crate build failed due to missing llvm. However, the wasmedge static lib won't build with llvm installed. It fails at:
```
[build:293] make[2]: *** No rule to make target 'lib/api/libwasmedge.a', needed by 'lib/api/CMakeFiles/wasmedge_static_target'.  Stop.
[build:294] make[1]: *** [CMakeFiles/Makefile2:858: lib/api/CMakeFiles/wasmedge_static_target.dir/all] Error 2
[build:295] make: *** [Makefile:156: all] Error 2
```

**Comment by hydai** [comment]
Hi @apepkuss 
Could you please check this issue?

**Comment by apepkuss** [comment]
Hi @brandond,
According to your description above, you'd like to use Rust SDK which binds to the static library of `WasmEdge Runtime` but not the dynamic library, right? If your answer is yes, then you should not use Rust SDK (`wasmedge-sdk`) published on crates.io as the published version does not support the use case. We provided support for the use case of binding to `libwasmedge.a` after we published `wasmedge-sdk = 0.7.1` and `wasmedge-sys = 0.12.2`, so you can refer to [the `rust-static-lib` CI workflow](https://github.com/WasmEdge/WasmEdge/blob/master/.github/workflows/rust-static-lib.yml) to get the details of how to use it. If you want to know the code's details, you can refer to this commit c8d9a7fc. Thanks!

**Comment by brandond** [comment]
Yeah, as mentioned above I updated the runwasi dependencies to point at a local checkout of the WasmEdge packages, but when I did so the runwasi crate build failed due to LLVM not being installed. When I installed LLVM, the WasmEdge build started failing with the above error, and I wasn't able to figure out why.

**Comment by apepkuss** [comment]
@brandond The `rust-static-lib` CI workflow shows that Rust SDK can work with the static lib correctly. So you can refer to the [script](https://github.com/WasmEdge/WasmEdge/blob/master/.github/workflows/rust-static-lib.yml) of the workflow to check the environment on your local.

**Comment by brandond** [comment]
@apepkuss have you tried with musl libc, or just glibc?

**Comment by apepkuss** [comment]
Sorry, I don't have experience in these two. In addition, the support for the static library in `wasmedge-sys` is only verified on the `Ubuntu` platform, so I'm not sure if it would work on other platforms or not. My suggestion is that the static library should be compiled correctly first on your local environment, as the `wasmedge-sys` crate is not responsible for compiling the `WasmEdge` library.

**Comment by brandond** [comment]
Yes, I was building both wasmedge and runwasi (which pulls in the wasmedge-sys crate) on the same host. The complete logs from a failed build are available at https://drone-pr.k3s.io/k3s-io/runwasi/31/1/2 (as well as a few other runs before/after as I was experimenting)

**Comment by apepkuss** [comment]
Could you please submit a feature request [here](https://github.com/WasmEdge/WasmEdge/issues)? We'll put it on our schedule. Thanks!

**Comment by jprendes** [comment]
I believe this is fixed by https://github.com/WasmEdge/wasmedge-rust-sdk/pull/48
In particular, see the updated [README](https://github.com/WasmEdge/wasmedge-rust-sdk/pull/48/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R53).
