### ISSUE TITLE
Drop boost dependencies

### ISSUE THREAD

**Issue by xiaozhuai** [WasmEdge/WasmEdge#2258]
Is WasmEdge only depends on `boost-winapi`? Then could we drop this?
I want to keep my project with as few dependencies as possible.
If possible, it would be better to also drop the `spdlog` and `fmt`.

If this is uncomplicated and achievable, I'd like to contribute.

**Comment by hydai** [comment]
1. We use `boost` for 128-bit integer support, `winapi`, `aligned_allocator`, and `fuzz`. Currently, we have yet to make a plan to drop it. If you can figure out how to replace it easily, we will consider this.
2. It doesn't make sense to drop `spdlog` and `fmt`. We do need the logging system. If we remove these, then we still need to implement our own version.

**Comment by xiaozhuai** [comment]
> 1. We use `boost` for 128-bit integer support, `winapi`, `aligned_allocator`, and `fuzz`. Currently, we have yet to make a plan to drop it. If you can figure out how to replace it easily, we will consider this.

I will have a look at this.

> 2. It doesn't make sense to drop `spdlog` and `fmt`. We do need the logging system. If we remove these, then we still need to implement our own version.

Yes, a logging system is necessary. But I think which logging library is used should be a choice made by user project.
The library itself should provide an interface for downstream projects to pass in log callbacks.
For example, the following is what `ffmpeg` did.

```cpp
// user defined callback function
static void avLogCallback(void *, int level, const char *fmt, va_list vl) {
    char buffer[4096] = {0};
#ifdef _WIN32
    vsprintf_s(buffer, fmt, vl);
#else
    vsnprintf(buffer, 4096, fmt, vl);
#endif
    if (level <= 16) {
        LOGE << "[libav] " << QString(buffer).trimmed();
    } else if (level <= 24) {
        LOGW << "[libav] " << QString(buffer).trimmed();
    } else if (level <= 32) {
        LOGI << "[libav] " << QString(buffer).trimmed();
    } else {
        LOGD << "[libav] " << QString(buffer).trimmed();
    }
}

// then register callback
av_log_set_callback(avLogCallback);
av_log_set_level(AV_LOG_VERBOSE);
```
