### ISSUE TITLE
feat: LFX Serialization Completion

### ISSUE THREAD

**Issue by hydai** [WasmEdge/WasmEdge#2262]
## Motivation

WasmEdge is a WebAssembly runtime in both interpreter and ahead-of-time mode. However, WasmEdge only supports the binary format for the input WebAssembly file. To help the text format WebAssembly loader feature in the future, the implementation of serializing a WebAssembly module is necessary. In this mentorship, we hope the mentee should complete the serialization functions already in [the `dev/serialize` branch](https://github.com/WasmEdge/WasmEdge/tree/dev/serialize) of the `WasmEdge` repo.

### Expected outcome:
   - Complete the serialization functions of WebAssembly modules, such as the element segment and data segment encoding.
   - Complete the WebAssembly instructions encoding.
   - Generate the unit test data and pass the unit tests.
   - `>80%` of code coverage for serialization.

### Apply here

https://mentorship.lfx.linuxfoundation.org/project/4a8a4f26-0ca9-4517-8cce-582c92092e33

**Comment by Shubham4359** [comment]
Hi @hydai, I would like to work on this issue in the upcoming GSOC mentorship. Can you give me a brief idea about the prerequisites needed to learn to complete this serialization function?

**Comment by swastik959** [comment]
hi @hydai I have a good knowledge of c/c++ . I would love to work on this issue in the GSOC mentorship

**Comment by yyy1000** [comment]
Hi, I like to help with it. I contributed to WasmEdge in OSPP last year on Java Async API and understand this project well.

**Comment by muchengl** [comment]
Hello @hydai , 
Recently I've been looking into adding Postcopy to WASM runtime. An important step in this idea is the serialization of WasmEdge. I was pleasantly surprised to find that this GSoC project was similar to my previous research direction. Therefore, I am very interested in this project and hope to participate in it. I already have a good understanding of WasmEdge and am good at C language development. 
I would like to know whether I need to make some preparations or submit my proposal directly to GSoC?
Thank you.

**Comment by Swatishree-Mahapatra** [comment]
Hello, @hydai! I was trying to understand "what is the serialization of web assembly modules" and as per my understanding, we have to convert the binary representation of web assembly modules to a certain format that can be stored.

I, therefore, tried to code a basic function in JS to demonstrate what I've understood. Is this the right direction or am I missing some concept?

The code ->

```
async function serializeModule(module) {
  // Convert the module to its binary representation
  const bytes = module.binary;

  // Create a new ArrayBuffer to hold the serialized bytes
  const buffer = new ArrayBuffer(bytes.length);

  // Create a new Uint8Array to write the bytes to the buffer
  const uint8Array = new Uint8Array(buffer);

  // Write the bytes to the Uint8Array
  for (let i = 0; i < bytes.length; i++) {
    uint8Array[i] = bytes[i];
  }

  // Return the serialized bytes as a Uint8Array
  return uint8Array;
}
```

**Comment by hydai** [comment]
Since the GSoC 2023 declined this proposal, we will move it to LFX mentorship.

**Comment by MohdSultanGit** [comment]
Hello @q82419 @hydai  I am Mohd Sultan I am very excited to participate in this project under lfx mentorship term-2.
Currently i am learning and working on C/C++, Programming, etc. So, I would love to contribute in this project under your mentorship.
Can you can give me any resources, slack channel or any other required materials to work on this project.
Looking forward to work on this project
Thanks,
Mohd Sultan

**Comment by adiroy28852** [comment]
Hello @hydai, I am Aditya Roy Chowdhury. I am eager to participate in this project, under your guidance. I have some experience with Python and plenty of C++ programming, having done some DSA. I would be grateful to learn and contribute to this project. 
If possible, may I get some links/references, for an overview of what is required to be done in this project, and some resources to proceed forward? 
Eager to work and learn from this project. 
Thanks and Regards.

**Comment by q82419** [comment]
Merged.
