### ISSUE TITLE
feat: semantic exit codes for traps in wasm code execution

### ISSUE THREAD

**Issue by harry900831** [WasmEdge/WasmEdge#2268]
## Description

Status for [abort.wasm](https://github.com/caspervonb/wasi-test-suite/blob/main/libc/abort.c) and [assert-false.wasm](https://github.com/caspervonb/wasi-test-suite/blob/main/libc/assert-false.c) should be 134, status for wasmedge running abort.wasm is 1.

According to the wat, It would call the function that run into a trap. 
```
  (func $abort (type $t1)
    (unreachable)
    (unreachable))
```

And I check the [implementation of wasmtime](https://github.com/bytecodealliance/wasmtime/blob/43022c862a1d497f4b8c7c2fce47148775503add/src/commands/run.rs#L208-L251), it seems that it return 134 whenever encountering a trap.

So changing the following three parts to return 128 + SIGABRT is a work around:

- https://github.com/WasmEdge/WasmEdge/blob/4f1059b4aa934c4de3c3edff4055c28e6f0b9311/lib/driver/runtimeTool.cpp#L295
- https://github.com/WasmEdge/WasmEdge/blob/4f1059b4aa934c4de3c3edff4055c28e6f0b9311/lib/driver/runtimeTool.cpp#L411
- https://github.com/WasmEdge/WasmEdge/blob/4f1059b4aa934c4de3c3edff4055c28e6f0b9311/lib/driver/runtimeTool.cpp#L328

**Comment by hydai** [comment]
Hi @harry900831 
According to the spec, this feature is not in the standard. However, the commit told about the reason that wasmtime would like to provide more semantic exit code on such use cases: 
https://github.com/bytecodealliance/wasmtime/commit/d44384da8aa614b97ff4b385752edfdc6c483357

It would be better to explain why you want to change the `EXIT_FAILURE` to `128+SIGABRT` in your PR.

Also, although the spec doesn't define this, it's a design decision by each runtime. However, providing a meaningful exit code can help developers to receive more information. After talking to several users, we can accept this change with an obvious comment.
