### ISSUE TITLE
feat: Support the wasi-threads proposal

### ISSUE THREAD

**Issue by juntao** [WasmEdge/WasmEdge#2273]
The [wasi-threads](https://github.com/WebAssembly/wasi-threads) API would allow a Wasm instance to spawn new Wasm instances in new threads. Together with the [wasm threads](https://github.com/WebAssembly/threads) proposal, which provides atomic access to a shared memory space, we will be able to compile existing multi-thread C/C++ or Rust libraries into WASI.

> WasmEdge already supports [wasm threads](https://github.com/WasmEdge/WasmEdge/pull/1499) ([examples using a host C SDK](https://github.com/WasmEdge/WasmEdge/tree/master/examples/capi/mandelbrot-set-in-threads)). 

We should probably also provide a C and Rust API library for developers to explicitly code the `wasi_thread_spawn` call while waiting for the standard compilers to support this.

**Comment by LFsWang** [comment]
I'll do this!

**Comment by hydai** [comment]
Since this is not compatible with the Component Model, there is no way to continue supporting this proposal. I am closing it.
