### ISSUE TITLE
[Java] active module of vm has no memory

### ISSUE THREAD

**Issue by proohit** [WasmEdge/WasmEdge#2313]
## Description
When I try to get the memory from `WasmEdgeVm#getImportModuleContext(HostRegistration.WasmEdge_HostRegistration_Wasi)` and try to get the memory of that module with `ModuleInstanceContext#findMemory("memory")`, just `null` is returned.

### Current State
I don't know wether `getImportModuleContext` is the correct method or not, but other SDKs provide a `activeModule` or `GetActiveModule` method for the vm. However when trying to get the memory of that module, `null` is returned and `listMemories` is just an empty `List`.

```java
WasmEdge.init();
ConfigureContext config = new ConfigureContext();
config.addHostRegistration(
        HostRegistration.WasmEdge_HostRegistration_Wasi);
StoreContext store = new StoreContext();
this.vm = new WasmEdgeVm(config, store);

// ... load wasm module etc

ModuleInstanceContext mod = vm.getImportModuleContext(HostRegistration.WasmEdge_HostRegistration_Wasi);
MemoryInstanceContext mem = mod.findMemory("memory"); // null
mod.listMemory(); // size is 0
```
Plus, I register another `ModuleInstanceContext`, which I cannot seem to access, because `getImportModuleContext` only accepts values of enum `HostRegistration`.
### Expected

I'd like to access the memory, but it seems there is no way to access the WASI module memory.

## Environment

- x86_64
- Ubuntu 20.04

**Comment by alabulei1** [comment]
@kenvifire Could you please check this out?

**Comment by kenvifire** [comment]
You should instantiate a module instance first and list memory by `org.wasmedge.ModuleInstanceContext#listMemory`.

You can refer `org.wasmedge.ModuleInstanceContextTest` for complete test case.

**Comment by proohit** [comment]
Thanks for the hint. I was able to have a reference to my module,  although I had to manually initialize the module with an `ExecutorContext`.

For reference, here is my current implementation:

```java
            // bytes of my main module
            byte[] bytesArray = in.readAllBytes();

            WasmEdge.init();
            ConfigureContext config = new ConfigureContext();
            config.addHostRegistration(
                    HostRegistration.WasmEdge_HostRegistration_Wasi);
            StoreContext store = new StoreContext();

            // creating a WasmEdgeVm is still necessary as it imports WASI functions
            this.vm = new WasmEdgeVm(config, store);

            // this is another module which my main module expects imports from
            ModuleInstanceContext envModule = this.getEnvModule();

            LoaderContext loader = new LoaderContext(config);
            AstModuleContext astFrameworkModule = loader.parseFromBuffer(bytesArray, bytesArray.length);
            ValidatorContext validator = new ValidatorContext(config);
            validator.validate(astFrameworkModule);
            this.executor = new ExecutorContext(config, null);
            executor.registerImport(store, envModule);
            this.frameworkModule = executor.register(store, astFrameworkModule, "custom_framework");
```
