### ISSUE TITLE
[Docs]: Corrections for TF-lite

### ISSUE THREAD

**Issue by manulpatel** [WasmEdge/WasmEdge#2315]
There have been few places in [5.2.4 (Neural Network for WASI)](https://wasmedge.org/book/en/write_wasm/rust/wasinn.html), which require corrections for TF-lite:

1. Add TF-lite under [Prerequisites](https://wasmedge.org/book/en/write_wasm/rust/wasinn.html#prerequisites).
2. Correct "[using the PyTorch backend](https://wasmedge.org/book/en/write_wasm/rust/wasinn.html#using-wasi-nn-with-tensorflow-lite-backend-in-rust:~:text=wasi_nn%3A%3AGRAPH_ENCODING_TENSORFLOWLITE%20means-,using,-the%20PyTorch%20backend)" with "using the TensorFlow-Lite backend".
3. Replace "[The above Mobilenet PyTorch model](https://wasmedge.org/book/en/write_wasm/rust/wasinn.html#tensorflow-lite-backend-example)" with "TensorFlow-Lite model" and correct link to the model/python code.

**Comment by q82419** [comment]
Thanks for help!
