### ISSUE TITLE
Compile on Linux instructions needs updating (Ubuntu 22.04)

### ISSUE THREAD

**Issue by kriswuollett** [WasmEdge/WasmEdge#2320]
I believe the assumption that using an Ubuntu Docker image for testing build instructions will **_not_** work the same as a freshly installed Ubuntu 22.04 Desktop distribution. I had encountered the same issue as in #1821, i.e.,:

```
CMake Error at lib/aot/CMakeLists.txt:11 (find_package):
  Could not find a package configuration file provided by "LLD" with any of
  the following names:

    LLDConfig.cmake
    lld-config.cmake

  Add the installation prefix of "LLD" to CMAKE_PREFIX_PATH or set "LLD_DIR"
  to a directory containing one of the above files.  If "LLD" provides a
  separate development package or SDK, be sure it has been installed.
```

However following directions within a Docker `ubuntu:22.04` container works. That was confusing since my desktop should have a superset of installed packages, but with perhaps some troublesome extras in `/usr/local` like Kubernetes utils or CUDA SDK. I tried making another user account on my computer to also eliminate the possible of any extra home directory binaries or libraries for dev.

It's unfortunate that it wasn't investigated earlier and fixed since it was easily searchable: I found the solution at https://github.com/ziglang/zig/issues/419#issuecomment-1205775536. It has been a while since I worked with CMake so I currently didn't have time to investigate the package lookups. So solution was just also installing `liblld-14 liblld-14-dev`.

## Environment

- Hardware Architecture: `x86_64`
- Operating system: Ubuntu 22.04 (Desktop)

## Reproduce

(I assume just...) install Ubuntu 22.04 with Desktop install from Live CD, then:

```shell
sudo apt-get update
sudo apt install -y git
sudo apt install -y \
   software-properties-common \
   cmake \
   libboost-all-dev
sudo apt install -y \
   llvm-12-dev \
   liblld-12-dev
sudo apt install -y gcc g++
sudo apt install -y clang-12      
git log -1 | head -1
# commit 9f5408746a76dc345c75f4780a357951992567ce (HEAD -> master, origin/master, origin/HEAD)
mkdir -p build && cd build

# Fails with error mentioned above
cmake -DCMAKE_BUILD_TYPE=Release -DWASMEDGE_BUILD_TESTS=ON

sudo apt install liblld-14 && sudo apt install liblld-14-dev

# Now succeeds
cmake -DCMAKE_BUILD_TYPE=Release -DWASMEDGE_BUILD_TESTS=ON && make -j

**Comment by hydai** [comment]
Thanks for raising this. It looks like Ubuntu 22.04 will need to install `lld-14` to set up the environment automatically. Open a PR #2323 to fix this.
