### ISSUE TITLE
Instantiation failed error when  Run AI Inference function based on  Pytorch

### ISSUE THREAD

**Issue by johnvan08** [WasmEdge/WasmEdge#2330]
## Description
Follow the guide “[Run AI Inference function based on TensorFlow, OpenVINO, Pytorch, and TensorFlow-lite in WasmEdge](https://wasmedge.org/docs/category/45-ai-inference)”  
run  the command ：
wasmedge --dir .:. wasmedge-wasinn-example-mobilenet-image.wasm mobilenet.pt input.jpg
but  it cannot  work, I  got  the  error:
[2023-03-02 13:34:31.338] [error] instantiation failed: unknown import, Code: 0x62
[2023-03-02 13:34:31.340] [error]     When linking module: "wasi_ephemeral_nn" , function name: "load"
[2023-03-02 13:34:31.340] [error]     At AST node: import description
[2023-03-02 13:34:31.340] [error]     At AST node: import section
[2023-03-02 13:34:31.340] [error]     At AST node: module
then, I build  .wasm file  by  self, it  same.
## Environment

- Hardware Architecture:  x86\_64
- Operating system:wsl   Ubuntu 20.04 

The following information is optional. Please provide them only if you have built from source.
- rust version:  rustc/cargo 1.67.1 (d5a82bbd2 2023-02-07)

**Comment by hydai** [comment]
Have you installed WASI-NN plugin with Pytorch before using it? https://wasmedge.org/docs/develop/build-and-run/install#wasi-nn-plugin-with-pytorch-backend

**Comment by johnvan08** [comment]
@hydai yes,and I am  trying that  follow  the guide  https://wasmedge.org/book/en/contribute/build_from_src/plugin_wasi_nn.html  build    wasmedge plugin now

**Comment by johnvan08** [comment]
I know why it doesn't work, curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | sudo bash -s -- -p /usr/local This command should be used , but I use curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- -v 0.11.2 --plugins wasi_nn-pytorch This command
