### ISSUE TITLE
Support exception handling proposal

### ISSUE THREAD

**Issue by sdeleuze** [WasmEdge/WasmEdge#2335]
Related to #1122 as it is usually required by GCed language like Kotlin or Java, supporting exception handling proposal is necessary to run Kotin/Wasm in WasmEdge.

An easier first step would allow to parse WebAssembly bytecode built with EH proposal enabled, in order to support positive scenarios that do not throw exceptions. That would unlock a lot of potential experimentation with Kotlin/Wasm, Dart, etc.

**Comment by harry900831** [comment]
I'll do this!

**Comment by hydai** [comment]
@q82419 We supported the EH proposal in the 0.14.0 release. Could you please give a summary of the current implementation status?

**Comment by q82419** [comment]
Finished.
