### ISSUE TITLE
Memory Leak in New VM

### ISSUE THREAD

**Issue by AshantiM** [WasmEdge/WasmEdge#2370]
## Description
After doing a bit of stress testing and attatching valgrind I have seemed to find a memory leak using the new VM 
https://github.com/WasmEdge/WasmEdge/pull/2312
### Current State
My Valgrind Output:

```
==24475== 1,367,415 (712 direct, 1,366,703 indirect) bytes in 1 blocks are definitely lost in loss record 3,133 of 3,134
==24475==    at 0x4849013: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==24475==    by 0x4E3CF5C: WasmEdge::Executor::Executor::instantiate(WasmEdge::Runtime::StoreManager&, WasmEdge::AST::Module const&, std::optional<std::basic_string_view<char, std::char_traits<char> > >) in libwasmedge.so.0.0.2)
==24475==    by 0x4DAB3DA: WasmEdge_ExecutorRegister (in libwasmedge.so.0.0.2)
==24475==    by 0x11EBF13: wasmedge_sys::executor::Executor::register_named_module (executor.rs:117)
==24475==    by 0x11EB432: wasmedge_sdk::store::Store::register_named_module (store.rs:64)
==24475==    by 0x11E60BB: wasmedge_sdk::vm::Vm::register_module (vm.rs:267)

```
### Expected
Expected should be that the piece of memory be freed when the drop trait is called

## Environment
WSL on Ubuntu 22.04.1 LTS

##Additional Information
Memory Leak does not exist if you use old VM. (Any SDK code before new VM Was implemented_

## Steps to Reproduce
Attatch valgrind to a program that calls register_module on the VM and have the VM fall out of scope or call std::mem::drop

**Comment by hydai** [comment]
Hi @apepkuss Could you please check this?

**Comment by AshantiM** [comment]
Awesome, thank you very much for taking a look at this. If you think of any workaroud as well, feel free to let me know

**Comment by q82419** [comment]
@apepkuss 
Did the PR fix this issue? Thanks.

**Comment by apepkuss** [comment]
> @apepkuss Did the PR fix this issue? Thanks.

Yes.
