### ISSUE TITLE
Missing darwin_arm64 release in 0.12.0-alpha.2

### ISSUE THREAD

**Issue by loredanacirstea** [WasmEdge/WasmEdge#2373]
## Description

Previous versions (e.g. 0.11.2) offered a darwin_arm64 release. The new alpha 0.12.0 versions do not contain a darwin_arm64 release - https://github.com/WasmEdge/WasmEdge/releases/tag/0.12.0-alpha.2

### Expected

To find a `WasmEdge-0.12.0-alpha.2-darwin_arm64.tar.gz` release.

**Comment by q82419** [comment]
Sorry that the `aarch64 darwin` CI is not set now in current, so the `aarch64 darwin` version of release are uploaded by ourselves. Therefore we usually only upload that in official release.

**Comment by q82419** [comment]
Added the package.
