### ISSUE TITLE
[Installer] Support Ubuntu version of extensions installation

### ISSUE THREAD

**Issue by q82419** [WasmEdge/WasmEdge#2397]
## Motivation

The `manylinux` version of extensions (WasmEdge-tensorflow and WasmEdge-image) is not compatible with `Ubuntu` version of WasmEdge.
Therefore we should support the installation of ubuntu version extensions when the ubuntu version of WasmEdge selected.

## Details

From WasmEdge 0.11.1, we have the Ubuntu release.
For the WasmEdge-tensorflow and WasmEdge-image, I've updated the ubuntu releases.
Please help to install the same `DIST` of the extensions and WasmEdge, such as the plugins (the policy described in the comment of #2196).

For the `WasmEdge-tensorflow-tools`, please do not apply this because the tools are the stand-alone executables.

The extension with Ubuntu releases can be test: `0.11.1`, `0.11.2`, and `0.12.0-alpha.2`

cc @SAtacker

**Comment by SAtacker** [comment]
@q82419 What is to be done with [WasmEdge-TensorFlow-Dependencies](https://github.com/second-state/WasmEdge-tensorflow-deps/releases/tag/0.11.2) ?

**Comment by q82419** [comment]
> @q82419 What is to be done with [WasmEdge-TensorFlow-Dependencies](https://github.com/second-state/WasmEdge-tensorflow-deps/releases/tag/0.11.2) ?

It doesn't matter. The `Tensorflow-Deps` can not be changed.
