### ISSUE TITLE
Timeout not work when using run_func_async of Rust SDK

### ISSUE THREAD

**Issue by DarumaDocker** [WasmEdge/WasmEdge#2407]
I have created a repo for test:
https://github.com/DarumaDockerDev/timeout-test

To reproduce the problem, run following:
```bash
cargo build --lib --target wasm32-wasi
cargo run
```

When access `http://127.0.0.1:8094/normal` it will response 408  as timeout which meets with our expectation.
But if access `http://127.0.0.1:8094/wasm` it will wait 2 seconds and return 200.

I want to know that why the async wasm running break the timeout strategy.

Thank you

**Comment by apepkuss** [comment]
Please refer to [the comments](https://github.com/WasmEdge/WasmEdge/issues/2396#issuecomment-1508240654) in issue #2396

**Comment by hydai** [comment]
@DarumaDocker @apepkuss 
I would like to want to know if this issue is resolved or not.
