### ISSUE TITLE
Generate a shared memory in env

### ISSUE THREAD

**Issue by LFsWang** [WasmEdge/WasmEdge#2415]
## Motivation

The wasm file with wasi-threads will import a shared memory from `env`. In current implement, Wasmedge need to add this manually in c api ([ref](https://github.com/WasmEdge/WasmEdge/blob/master/examples/capi/mandelbrot-set-in-threads/main.cc#L30)). It is meaning we can not run an wasi-threads example directly.

## Details

From wasi threads document, the WASI host must first allocate shared memories to satisfy the module's imports.

**Comment by en-rai** [comment]
any update?

**Comment by hydai** [comment]
Hi @en-rai 
Since the wasi-thread is not compatible with WASI preview 2 and the component model, we decided to freeze this proposal unless there is a new version of it.

**Comment by dannypsnl** [comment]
@hydai Does this means we should close the issue for now?

**Comment by hydai** [comment]
Yes. I think so.
