### ISSUE TITLE
Documentation unclear: how to allocate a buffer

### ISSUE THREAD

**Issue by Photosounder** [WasmEdge/WasmEdge#2420]
Whereas WAMR has `wasm_runtime_module_malloc()` and makes it clear what it's for and how to use it, I can't find any equivalent for WasmEdge's C API.

What I want is simple, I want to allocate (and then reallocate or free) a buffer in the WASM module's heap memory, pass its 32-bit "address"/offset to a WASM function like `void plugin_fill_data(uint8_t *data) { ... }` as a pointer so that WASM function can write things to that buffer, then directly access the content of that buffer through a pointer in the host, like for a WASM module that creates data to be used by its host.

There's currently no clear hint of any such functionality existing.

**Comment by Photosounder** [comment]
My current solution relies on the WASM module exporting `malloc` (not ideal) then doing this:

```c
	WasmEdge_String memory_name = WasmEdge_StringCreateByCString("memory");
	ctx->memory = WasmEdge_ModuleInstanceFindMemory(ctx->active_module, memory_name);
	WasmEdge_StringDelete(memory_name);

	uint8_t *memory_ptr = WasmEdge_MemoryInstanceGetPointer(ctx->memory, 0, 1);

	raster_address_for_wasm = call_wasm_malloc(ctx, 1000 * sizeof(uint16_t));
	raster_buffer = (uint16_t *) &memory_ptr[raster_address_for_wasm];
```
I set `memory_ptr` only once, but I wonder if it could move...

Using this function:
```c
int32_t call_wasm_malloc(wasm_ctx_t *ctx, int32_t size)
{
	WasmEdge_Result Res;
	WasmEdge_String func_name = WasmEdge_StringCreateByCString("malloc");

	// Set parameters for WASM function call
	WasmEdge_Value ret[1], param[1] = { WasmEdge_ValueGenI32(size) };
	
	// Call WASM plugin_draw() function
	Res = WasmEdge_VMExecute(ctx->vm_ctx, func_name, param, 1, ret, 1);
	if (!WasmEdge_ResultOK(Res))
	{
		fprintf(stderr, "WASM malloc(%d) call failed: %s\n", size, WasmEdge_ResultGetMessage(Res));
		return 0;
	}

	int32_t offset = WasmEdge_ValueGetI32(ret[0]);

	WasmEdge_StringDelete(func_name);

	return offset;
}
```

There should be a better way.

**Comment by alabulei1** [comment]
@q82419 Can you help take a look?

**Comment by q82419** [comment]
It is the WAMR feature of controlling the heap in memory instances.
We'll discuss this for the future versions.

**Comment by q82419** [comment]
Close this and replaced by the issue #2463.
