### ISSUE TITLE
[OSPP] feat: Expanding WasmEdge WASI Socket Support to macOS

### ISSUE THREAD

**Issue by hydai** [WasmEdge/WasmEdge#2438]
## Motivation

WasmEdge's WASI Socket component enables developers to harness the power of networking, facilitating connectivity and interaction with databases such as MySQL, deployment of microservices, integration with Dapr, and more. However, the current implementation is limited to the Linux platform.

This project aims to investigate and resolve issues preventing the WASI Socket component from functioning on macOS, ensuring seamless cross-platform support.

## Objectives
The primary objectives of this project are to:

* Investigate and identify the underlying issues preventing WASI Socket component compatibility with macOS.
* Implement necessary changes and fixes to enable WASI Socket support on macOS.
* Validate the functionality of the WASI Socket component on macOS through testing and examples.

## Output Requirements
Upon successful completion of this project, the following deliverables are expected:

1. A modified version of the WasmEdge WASI Socket component with full macOS support.
2. Comprehensive documentation detailing the investigation process, issues identified, and solutions implemented.
3. A report demonstrating the successful execution of the WASI Socket-related test suite on the macOS platform, with no errors or warnings.
4. Verification that the following examples function correctly on macOS: Tokio, hyper, reqwest, Mysql_async, postgres, sqlx, rskafka, redis, anna-rs, and Dapr. This should include test results, comparisons, and any necessary modifications to the example code.

## Pre-test

To apply for this project, please ensure you finish challenge #2453 before the application deadline.

**Comment by hydai** [comment]
This should be fixed in 0.13.4.
Thanks for the confirmation, @lithoformer

**Comment by zifeo** [comment]
@hydai Great, do you have a link to the pull request by any chance?

**Comment by hydai** [comment]
Hi @zifeo 

I am sorry I don't have a clear answer to this question. It should be accidentally fixed by one of the following commits after 4a8cf383d26a30a5d4babca7a05f065fddd13b04

That's why I also get surprised that someone told me this issue is no longer available.

Ref: https://github.com/WasmEdge/WasmEdge/commits/master/lib/host/wasi/inode-macos.cpp
