### ISSUE TITLE
Poor performance when executing Go code

### ISSUE THREAD

**Issue by achille-roussel** [WasmEdge/WasmEdge#2445]
## Description

Hello, I'm part of the maintainer team working on the WASI preview 1 port of Go, and we are looking into adding wasmedge as one of the runtimes that we run the Go test suites against. 

However, the performance is currently too slow to be practical, averaging around ~10x slower than other WebAssembly runtimes.

### Current State

Here is a summary of a benchmark run which highlights the issue, first first linux/amd64, second for darwin/arm64 (see below for how to reproduce):

```
             │ /tmp/bench.wazero │         /tmp/bench.wasmtime         │           /tmp/bench.wasmedge           │
             │      sec/op       │   sec/op     vs base                │    sec/op      vs base                  │
JoinPath/#10         922.6n ± 0%   297.2n ± 1%  -67.79% (p=0.000 n=10)   27434.0n ± 0%  +2873.55% (p=0.000 n=10)
```

```
             │ /tmp/bench.wazero │         /tmp/bench.wasmtime          │           /tmp/bench.wasmedge           │
             │      sec/op       │    sec/op     vs base                │    sec/op      vs base                  │
JoinPath/#10         539.6n ± 0%   1016.0n ± 1%  +88.31% (p=0.000 n=10)   35985.0n ± 1%  +6569.45% (p=0.000 n=10)
```

### Expected

I would expect wasmedge to display performance in the order of wazero and wasmtime.

## Environment

I tested on these two platforms:
- linux/amd64
- darwin/arm64

## Steps to Reproduce

Checkout a fork of https://github.com/golang/go, and rebuild the compiler:
```
cd src
./make.bash
```

Apply this diff to add wasmedge as a supported runtime:
```diff
diff --git a/misc/wasm/go_wasip1_wasm_exec b/misc/wasm/go_wasip1_wasm_exec
index 9838212d98..d90725b71f 100755
--- a/misc/wasm/go_wasip1_wasm_exec
+++ b/misc/wasm/go_wasip1_wasm_exec
@@ -4,6 +4,9 @@
 # license that can be found in the LICENSE file.
 
 case "$GOWASIRUNTIME" in
+	"wasmedge")
+		exec wasmedge --dir /:/ --env PWD="$PWD" -- "$@"
+		;;
 	"wasmtime")
 		exec wasmtime run --dir=/ --env PWD="$PWD" --max-wasm-stack 1048576 "$1" -- "${@:2}"
 		;;

```

Then run this benchmark to highlight the issue:
```sh
for runtime in wazero wasmtime wasmedge
do
  GOWASIRUNTIME=$runtime \
  GOROOT=$PWD \
  GOARCH=wasm \
  GOOS=wasip1 \
  PATH=$PWD/misc/wasm:$PATH \
  ./bin/go test -run _ -bench 'JoinPath/#10' -count 10 ./src/syscall | tee /tmp/bench.$runtime
done
```

**Comment by q82419** [comment]
Hi,

I think the script use the `wasmedge` tool to run the example WASM directly, and it was run in interpreter mode?
Thanks.

**Comment by achille-roussel** [comment]
I may not be knowledgeable enough with WasmEdge, how do I confirm that it wasn't running in interpreter mode?

**Comment by juntao** [comment]
@q82419 Can you provide a patch to run the benchmark tests in AOT mode for WasmEdge? I believe there will be a significant performance boost. Thank you.

**Comment by achille-roussel** [comment]
Thanks for the tip!

With a precompilation step the performance is indeed a lot better:
```
             │ /tmp/bench.wazero │         /tmp/bench.wasmtime          │         /tmp/bench.wasmedge         │
             │      sec/op       │    sec/op     vs base                │   sec/op     vs base                │
JoinPath/#10         539.6n ± 0%   1016.0n ± 1%  +88.31% (p=0.000 n=10)   175.5n ± 0%  -67.47% (p=0.000 n=10)
```
The downside is the compilation adds a lot of time, in this case ~25s to build the benchmark:
```
[2023-04-27 10:22:25.032] [info] compile start
[2023-04-27 10:22:25.181] [info] verify start
[2023-04-27 10:22:25.342] [info] optimize start
[2023-04-27 10:22:40.370] [info] codegen start
[2023-04-27 10:22:51.111] [info] output start
[2023-04-27 10:22:51.145] [info] compile done
[2023-04-27 10:22:51.192] [info] output start
```
With optimizations disables the runtime remains good but compilation still adds ~18s:
```
             │ /tmp/bench.wazero │         /tmp/bench.wasmtime          │         /tmp/bench.wasmedge         │
             │      sec/op       │    sec/op     vs base                │   sec/op     vs base                │
JoinPath/#10         539.6n ± 0%   1016.0n ± 1%  +88.31% (p=0.000 n=10)   254.9n ± 0%  -52.76% (p=0.000 n=10)
```
```
[2023-04-27 11:22:02.743] [info] compile start
[2023-04-27 11:22:02.892] [info] verify start
[2023-04-27 11:22:03.055] [info] optimize start
[2023-04-27 11:22:03.170] [info] codegen start
[2023-04-27 11:22:20.019] [info] output start
[2023-04-27 11:22:20.065] [info] compile done
[2023-04-27 11:22:20.111] [info] output start
```

Go currently has 330 packages with tests, to compile them all in order to run the test suite would take almost 2 hours.

**Comment by juntao** [comment]
That looks good! Our goal for WasmEdge is to optimize for server side apps. On the server side, we typically have one app that runs over and over again. So, spending some time up front to AOT optimize that app seems to be a good trade off. 

That said, we are also building a single pass JIT engine into our runtime so that it can run reasonably fast without the AOT step.

**Comment by achille-roussel** [comment]
It's a good trade off when there's a single application to build indeed, but it's impractical to run a CI pipeline where hundreds of small modules need to be compiled and executed.

JIT compilation sounds like the way to go! Is there an open issue tracking this work that I can subscribe to?

**Comment by juntao** [comment]
Not yet. But @hydai Can you create a tracking issue for the JIT work? Thanks. 

> JIT compilation sounds like the way to go! Is there an open issue tracking this work that I can subscribe to?

**Comment by achille-roussel** [comment]
Hello!

I took a look at the issues that have been opened recently and did not find one related to JIT compilation.

I just wanted to bump this issue to mention that I'd still be interested in having a place to track progress on this work!

**Comment by hydai** [comment]
Hi @achille-roussel 
I just created an issue for it: https://github.com/WasmEdge/WasmEdge/issues/2482

Please notice that we are evaluating several JIT frameworks, and we have not yet decided which one will be used in our future plan.

**Comment by jwhb** [comment]
Hi all,

I have been running some performance tests (WasmEdge vs. WasmTime vs. native, each with and without crun/podman) for my master's thesis.
I too observed a significant slowness of WasmEdge in interpreter mode and I'm glad to share my results.
The benchmark program `mtree.wasm` was compiled with rustc 1.70.0 from [this code](https://github.com/hanabi1224/Programming-Language-Benchmarks/blob/main/bench/algorithm/merkletrees/1.rs).

## WasmEdge 0.12.1 vs Wasmtime 9.0.4 on macOS 13.4 arm64

| Command | Mean [s] | Min [s] | Max [s] | Relative |
|:---|---:|---:|---:|---:|
| `WasmEdge opt.` | 1.300 ± 0.014 | 1.277 | 1.344 | 1.00 |
| `Wasmtime` | 1.577 ± 0.024 | 1.546 | 1.647 | 1.21 ± 0.02 |
| `Wasmtime opt.` | 1.619 ± 0.168 | 1.539 | 2.247 | 1.25 ± 0.13 |
| `WasmEdge` | 147.446 ± 6.000 | 144.567 | 178.470 | 113.42 ± 4.78 |

```bash
wasmedgec mtree.wasm mtree_compiled.wasm  # compile wasmedge
wasmtime compile -o mtree.cwasm mtree.wasm  # compile wasmtime
PREPARE="sync; sudo purge" # clear disk & memory caches
hyperfine -r '30' --warmup '2' \
-n "WasmEdge" --prepare "$PREPARE" "wasmedge mtree.wasm 18" \
-n "WasmEdge opt." --prepare "$PREPARE" "wasmedge mtree_compiled.wasm 18" \
-n "Wasmtime" --prepare "$PREPARE" "wasmtime mtree.wasm 18" \
-n "Wasmtime opt." --prepare "$PREPARE" "wasmtime --allow-precompiled mtree.cwasm 18"
```

## WasmEdge 0.12.1 vs Wasmtime 9.0.3 on RHEL 9.2 x86_64

| Command | Mean [s] | Min [s] | Max [s] | Relative |
|:---|---:|---:|---:|---:|
| WasmEdge opt.   | 2.686 ± 0.055 | 2.618 | 2.959 | 1.29 ± 0.04 |
| Wasmtime opt.   | 2.737 ± 0.059 | 2.680 | 2.913 | 1.32 ± 0.04 |
| Wasmtime        | 2.783 ± 0.085 | 2.666 | 2.995 | 1.34 ± 0.05 |
| Podman Wasmtime | 3.718 ± 0.059 | 3.592 | 3.911 | 1.79 ± 0.05 |
| WasmEdge        | 257.815 ± 4.545 | 243.787 | 265.764 | 126.79 ± 2.40 |
| Podman wasmedge | 258.169 ± 4.344 | 252.462 | 267.398 | 126.96 ± 2.31 |

(test commands on Linux omitted)

We can observe that WasmEdge in interpreter mode is at least 95 times slower than optimized WasmEdge with this specific WASM file.

**Comment by hydai** [comment]
Hi @jwhb 
Thanks for the benchmark. This result is expected. We provide only interpreter(slow) and ahead-of-time compilation(fast) modes currently. 
Since the JIT solution is on the way, our team doesn't focus on enhancing the interpreter's performance.

**Comment by dannypsnl** [comment]
Close as not goal.

**Comment by johanbrandhorst** [comment]
Could you please update this issue when the JIT solution is available? Thanks

**Comment by dannypsnl** [comment]
I think you can track #2482
