### ISSUE TITLE
[Rust-SDK] Consider adding support WasmEdge installed path as default behavior

### ISSUE THREAD

**Issue by CaptainVincent** [WasmEdge/WasmEdge#2448]
## Motivation

Consider adding support for these environments to build wasmedge-sys as default behavior.

```
CPLUS_INCLUDE_PATH
C_INCLUDE_PATH
LD_LIBRARY_PATH
```

if user doesn't set `WASMEDGE_INCLUDE_DIR`  `WASMEDGE_LIB_DIR` or `WASMEDGE_BUILD_DIR`

## Details

I am aware that most of the details could be found in the documentation [here](https://wasmedge.org/book/zh/embed/rust.html).

However, in some cases, developers may simply install the latest version of WasmEdge and test an unreleased Rust SDK.
In such cases, they may forget to set the variables `WASMEDGE_INCLUDE_DIR`  `WASMEDGE_LIB_DIR` or `WASMEDGE_BUILD_DIR` to installed path ~~`$HOME`~~ `<Any Installed Path>/.wasmedge/lib and include`, which could result in compilation errors but can be challenging to identify and fix.

**Comment by CaptainVincent** [comment]
Maybe is my misunderstand of my compile fail root cause, I will check later.

**Comment by CaptainVincent** [comment]
@apepkuss What do you think?

**Comment by hydai** [comment]
@CaptainVincent 
Do we still need this?

**Comment by CaptainVincent** [comment]
It seems that the issue has been resolved. Currently, the rule for automatically recognizing local paths in the SDK compilation works fine. I'll go ahead and close this issue.
