### ISSUE TITLE
[Installer] Deprecate WasmEdge 0.9.x installation

### ISSUE THREAD

**Issue by q82419** [WasmEdge/WasmEdge#2488]
## Motivation

The WasmEdge 0.9.x installation should be deprecated before 2023/05/31.

## Details

As the 0.8.x before, deprecate WasmEdge 0.9.x installation.

**Comment by q82419** [comment]
Hi @SAtacker, 

Can you help this? Thanks.

**Comment by SAtacker** [comment]
> Hi @SAtacker, 
> 
> Can you help this? Thanks.

Yes, sorry for the delay. I'll do this by the end of the day.
