### ISSUE TITLE
Standalone Repository for WasmEdge Rust Binding from Version 0.13.0 Onwards

### ISSUE THREAD

**Issue by hydai** [WasmEdge/WasmEdge#2502]
Hello, WasmEdge Community,

I would like to propose a new feature request regarding the organization of our repositories. This request involves the creation of a standalone repository specifically for the Rust binding, starting from the 0.13.0 release.

**Motivation**

The Rust binding has been an integral part of WasmEdge, primarily relying on the C API provided by WasmEdge. However, as the project evolves, it has become apparent that the Rust binding has a unique development roadmap. Hence, it is sensible to consider a structural change in how we organize these components to enable more focused development.

**Proposal**

I propose to split the Rust binding into a separate, standalone repository. This move would lead to several advantages:

1. **Independent Versioning**: This would allow for independent versioning of the Rust binding, which can evolve based on its own development and release cycles. This independence would ensure that enhancements, fixes, or changes in the Rust binding do not necessitate a new release of the WasmEdge main project.

2. **Focused Issue Tracking**: By separating the repositories, we can better track issues and improvements related to the Rust binding, making it easier for contributors to participate and for maintainers to manage the project.

3. **Clearer Roadmap**: A standalone repository would allow for the development of a distinct roadmap for the Rust binding, providing clarity for developers and users alike about the future direction of this component.

4. **Reduced Complexity**: It will simplify the WasmEdge repository by reducing the number of components it directly manages, resulting in a cleaner and more manageable codebase.

**Implementation Details**

The Rust binding will be split from the WasmEdge repository starting from version 0.13.0. The new repository will maintain the history of the Rust binding's development and will be managed by the same maintainers.

The Rust binding will continue to rely on the C API provided by WasmEdge, and efforts will be made to ensure compatibility and synchronization between the two projects.

**Conclusion**

This proposal aims to enhance the efficiency of our development processes and provide a clearer roadmap for both the WasmEdge main project and the Rust binding. We believe this change will benefit the WasmEdge community in the long run.

I kindly request feedback on this proposal, and I am looking forward to hearing your thoughts and suggestions.

Thank you for your attention and your continued contributions to the WasmEdge project.

/cc WasmEdge Rust binding maintainers @apepkuss @yanganto

**Comment by apepkuss** [comment]
@hydai The issue has been fixed by https://github.com/WasmEdge/wasmedge-rust-sdk/pull/1 and https://github.com/WasmEdge/wasmedge-rust-sdk/pull/2
