### ISSUE TITLE
Update libsql integration to 0.12

### ISSUE THREAD

**Issue by juntao** [WasmEdge/WasmEdge#2503]
## Motivation

The libsql UDF runtime and examples are still in WasmEdge 0.11. We should update that.

## Details

* Update the integration WasmEdge version to 0.12.1
* Update the TFLite UDF example to WASI NN + TFLite plugin
* Update the web service UDF example to HTTPS + TLS plugin

**Comment by hydai** [comment]
What's the status of this issue?

**Comment by hydai** [comment]
Ping @L-jasmine

**Comment by hydai** [comment]
Closing due to inactive.
