### ISSUE TITLE
Support "Named Models" in WASI NN

### ISSUE THREAD

**Issue by juntao** [WasmEdge/WasmEdge#2504]
## Motivation

A new feature is being added to the WASI NN spec. We should support it.

## Details

see here: https://github.com/WebAssembly/wasi-nn/issues/36

**Comment by hydai** [comment]
The Named Models doesn't provide a way to deregister the registered models. And according to the response from [the thread](https://github.com/WebAssembly/wasi-nn/issues/36#issuecomment-1553303045), we won't have such a function in the current Named Models proposals. However, we do have the FaaS use scenario, to fit the users' requirements, we may need to have an extension function for this.

**Comment by juntao** [comment]
I think we can always implement a superset of the official spec ...

**Comment by hydai** [comment]
I will start implementing the named model feature after #2513 gets merged.

**Comment by CaptainVincent** [comment]
https://github.com/WasmEdge/WasmEdge/pull/2742
I have prepared a PR, but I am currently waiting for the release of wasi-nn before opening this PR for review.
