### ISSUE TITLE
Deprecated Notice: httpsreq plugin will be replaced by wasmedge-rustls-plugin

### ISSUE THREAD

**Issue by hydai** [WasmEdge/WasmEdge#2514]
# Deprecation Notice: `httpsreq` TLS Plugin

Hello to all our dedicated developers and users,

As we continually strive to deliver more efficient, secure, and robust solutions, we are excited to announce that we have developed a new TLS plugin based on the rustls library. Consequently, the current `httpsreq` TLS plugin will enter a deprecation phase. 

## Timeline

The deprecation process will proceed as follows:

- The `httpsreq` plugin will be officially deprecated in the 0.13.0 release.
- The `wasmedge-rustls` plugin will be released simultaneously so that users can switch their applications to the new one.
- After the 0.13.0 release, no further updates or fixes will be issued, and the `httpsreq` TLS plugin will no longer be supported. 

We strongly encourage all users to migrate to the new rustls-based plugin as soon as possible to ensure a smooth transition and continued support.

Thank you for your understanding and cooperation during this transition.

## Working items

- [ ] Remove `httpsreq` from the source tree
- [ ] Remove `httpsreq` related CI workflow, including build, test, and release
- [ ] Remove the `httpsreq` related document

**Comment by mfordjody** [comment]
？
