### ISSUE TITLE
Support installing `wasm_bpf` plugin through `install.py`

### ISSUE THREAD

**Issue by Officeyutong** [WasmEdge/WasmEdge#2537]
Currently the installation of plugin `wasm_bpf` can only be performed manually. The [install.py](https://github.com/WasmEdge/WasmEdge/blob/master/utils/install.py) doesn't seem to support install this plugin.

I'm glad to add `wasm_bpf` installation support for installing script, but I didn't find any documents on this. Is there any help documents for this?

**Comment by hydai** [comment]
Before the `wasm_bpf` is added to the `installer matrix`, you must first add a CI workflow for releasing the assets.

There are no documents for this; if you have any questions, please ping me(@hydai) or the installer maintainer (@SAtacker) directly.

**Comment by hydai** [comment]
CI for releasing pre-built assets: https://github.com/WasmEdge/WasmEdge/blob/master/.github/workflows/release.yml#L107-L289
Script related to handling the plugin: https://github.com/WasmEdge/WasmEdge/blob/master/utils/install.py#L299-L325

**Comment by SAtacker** [comment]
> Before the `wasm_bpf` is added to the `installer matrix`, you must first add a CI workflow for releasing the assets.
> 
> There are no documents for this; if you have any questions, please ping me(@hydai) or the installer maintainer (@SAtacker) directly.

I am there on discord as well (same username or Shreyas) or email id shreyasatre16 [AT] gmail [dot] com

**Comment by Officeyutong** [comment]
> CI for releasing pre-built assets: https://github.com/WasmEdge/WasmEdge/blob/master/.github/workflows/release.yml#L107-L289 Script related to handling the plugin: https://github.com/WasmEdge/WasmEdge/blob/master/utils/install.py#L299-L325

Thank you!
