### ISSUE TITLE
[Installer] New changes for extensions installation

### ISSUE THREAD

**Issue by q82419** [WasmEdge/WasmEdge#2542]
## Motivation

We'll deprecate the WasmEdge extensions (WasmEdge-tensorflow, WasmEdge-image, and WasmEdge-tensorflow-tools) in the following `0.13.0` version.
Furthermore, we will re-construct the WasmEdge-tensorflow-deps for a better use.

## Details

In current, when installing the WasmEdge-tensorflow extensions, installer will download the release from the same version of `WasmEdge-tensorflow-deps`.
We released the new tags so that the `WasmEdge-tensorflow-deps` will not necessary to be updated when a new WasmEdge version released.
Please follow the following matrix to refactor the dependency installation in installer:

* WasmEdge versions before `0.11.x` (includes `0.10.x`):
  - For `WasmEdge-tensorflow` and `WasmEdge-tensorflow-tools`:
     - Use tag `TF-2.6.0` of `WasmEdge-tensorflow-deps`
     - Supported `manylinux2014_x86_64`, `ubuntu20.04_x86_64`, `manylinux2014_aarch64`, and `darwin_x86_64`
  - For `wasi_nn-tensorflowlite`:
     - Use tag `TF-2.6.0` of `WasmEdge-tensorflow-deps`
     - Supported `manylinux2014_x86_64`, `ubuntu20.04_x86_64`, and `manylinux2014_aarch64`
* WasmEdge versions `0.12.x`:
  - For `WasmEdge-tensorflow` and `WasmEdge-tensorflow-tools`:
     - Use tag `TF-2.6.0-CC` of `WasmEdge-tensorflow-deps`
     - Supported `manylinux2014_x86_64`, `ubuntu20.04_x86_64`, `manylinux2014_aarch64`, and `darwin_x86_64`
  - For `wasi_nn-tensorflowlite`:
     - Use tag `TF-2.6.0-CC` of `WasmEdge-tensorflow-deps`
     - Supported `manylinux2014_x86_64`, `ubuntu20.04_x86_64`, and `manylinux2014_aarch64`
* WasmEdge versions `0.13.x` and after (This section can be pending):
  - No `WasmEdge-tensorflow` and `WasmEdge-tensorflow-tools`
  - For `wasi_nn-tensorflowlite`:
     - Use tag `TF-2.12.0-CC` of `WasmEdge-tensorflow-deps`
     - Supported `manylinux2014_x86_64`, `ubuntu20.04_x86_64`, and `manylinux2014_aarch64`
  - For new `wasmedge_tensorflow` and `wasmedge_tensorflowlite` plugin (not implemented yet):
     - Use tag `TF-2.12.0-CC` of `WasmEdge-tensorflow-deps`
     - Supported `manylinux2014_x86_64`, `ubuntu20.04_x86_64`,`manylinux2014_aarch64`, `darwin_x86_64`, and `darwin_arm64`

**Comment by q82419** [comment]
@SAtacker  

You can deprecate the `0.9.x` in the same PR, I think it will be more convenient for you to refactor.
Please feel free to discuss if you have any questions.
Thanks!!

**Comment by SAtacker** [comment]
Hello @q82419 ,
What is the plan for WasmEdge-image?

**Comment by q82419** [comment]
> Hello @q82419 , What is the plan for WasmEdge-image?

The `WasmEdge-image` extension will still be deprecated in the `0.13.0`, too.

**Comment by SAtacker** [comment]
Are the tags for `wasmedge-tensorflow` not there at https://github.com/second-state/WasmEdge-tensorflow/tags ?

**Comment by q82419** [comment]
> Are the tags for `wasmedge-tensorflow` not there at https://github.com/second-state/WasmEdge-tensorflow/tags ?

No, we won't have new tags in WasmEdge-Tensorflow, WasmEdge-Image, and WasmEdge-Tensorflow-tools.
That is, these extensions will not support anymore after 0.13.0 versions.
Instead, we will have wasmedge_tensorflow, wasmedge_tensorflowlite, and wasmedge_image plugins after 0.13.0 versions.
For the dependencies, please install the dependency like the old tools with the tag `TF-2.12.0-CC` of WasmEdge-Tensorflow-deps.

**Comment by SAtacker** [comment]
> > Are the tags for `wasmedge-tensorflow` not there at https://github.com/second-state/WasmEdge-tensorflow/tags ?
> 
> No, we won't have new tags in WasmEdge-Tensorflow, WasmEdge-Image, and WasmEdge-Tensorflow-tools.
> That is, these extensions will not support anymore after 0.13.0 versions.
> Instead, we will have wasmedge_tensorflow, wasmedge_tensorflowlite, and wasmedge_image plugins after 0.13.0 versions.
> For the dependencies, please install the dependency like the old tools with the tag `TF-2.12.0-CC` of WasmEdge-Tensorflow-deps.

Got it. Thanks.

**Comment by SAtacker** [comment]
What is [WasmEdge-runtime-only-0.13.0-manylinux2014_x86_64.tar.xz](https://github.com/WasmEdge/WasmEdge/releases/download/0.13.0/WasmEdge-runtime-only-0.13.0-manylinux2014_x86_64.tar.xz)?

**Comment by hydai** [comment]
> What is [WasmEdge-runtime-only-0.13.0-manylinux2014_x86_64.tar.xz](https://github.com/WasmEdge/WasmEdge/releases/download/0.13.0/WasmEdge-runtime-only-0.13.0-manylinux2014_x86_64.tar.xz)?

WasmEdge without LLVM bundled. This is only for special users now. The installer can leave it alone.

**Comment by SAtacker** [comment]
Closing this now as done in https://github.com/WasmEdge/WasmEdge/commit/a97f4caeb2c4f3832bf2127be09ca974d8ce8f51, thanks
