### ISSUE TITLE
OCI runtime create failed: io priority not supported: unknown

### ISSUE THREAD

**Issue by wenzhaojie** [WasmEdge/WasmEdge#2553]
### Current State

In order to install wasmedge runtime for kubernetes runtime class. I follow the guide to use crun with containerd for kubernetes runtime:
[https://wasmedge.org/book/en/use_cases/kubernetes/container/crun.html](https://wasmedge.org/book/en/use_cases/kubernetes/container/crun.html)

```bash
sudo apt update
sudo apt install -y make git gcc build-essential pkgconf libtool \
    libsystemd-dev libprotobuf-c-dev libcap-dev libseccomp-dev libyajl-dev \
    go-md2man libtool autoconf python3 automake
```
Next, configure, build, and install a crun binary with WasmEdge support.
```bash
git clone https://github.com/containers/crun
cd crun
./autogen.sh
./configure --with-wasmedge
make
sudo make install
```

### Expected
But error with kubenetes pod info:
```bash
Warning  FailedCreatePodSandBox  6s (x2 over 22s)      kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: OCI runtime create failed: io priority not supported: unknown
```
## Environment

- Hardware Architecture: x86_64 
- Operating system: Ubuntu 20.04

**Comment by alabulei1** [comment]
@hydai @dm4 Can you please take a look? Thanks!

**Comment by alabulei1** [comment]
Meanwhile, can you also run `crun --version` to check if `wasmedge` is installed successfully? If you did, the output message should include `+WASM:wasmedge`  just like the following content. @wenzhaojie 

```
crun --version 
crun version 1.8.3.0.0.0.5-d2ff
commit: d2ff390d37ca163ebff2467382b3a6d6c77c5ca6
rundir: /run/user/0/crun
spec: 1.0.0
+SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +WASM:wasmedge +YAJL
```

**Comment by hydai** [comment]
This is tracked in a upstream issue: https://github.com/containers/crun/issues/1231

**Comment by giuseppe** [comment]
could you please try with https://github.com/containers/crun/pull/1233 applied?

**Comment by giuseppe** [comment]
I think it is safe to close this issue, since it is a crun problem that is already tracked

**Comment by hydai** [comment]
Hi @giuseppe 
After `crun#1233` was applied, the CI passed: https://github.com/second-state/wasmedge-containers-examples/actions/runs/5194562092/jobs/9366354558 
So I think this is resolved :-)

**Comment by giuseppe** [comment]
thanks for confirming it!
