### ISSUE TITLE
Breaking: Remove wasm annotation in container images

### ISSUE THREAD

**Issue by hydai** [WasmEdge/WasmEdge#2567]
## Motivation

After https://github.com/containers/podman/pull/18542, podman no longer propagates annotations while running the container image. We should update all of the container examples and documents.

## Details

Drop `module.wasm.image/variant=compat` annotation. Use `--platform wasi/wasm` instead.

## Appendix

* https://github.com/containers/podman/pull/18542
* https://github.com/containers/crun/pull/1234
* https://github.com/containers/crun/pull/1235

**Comment by alabulei1** [comment]
After that, we should also update this in our docs.

BTW, is `--platform wasi/wasm` the same flag when using docker to build a Wasm image?

**Comment by hydai** [comment]
Yes. So the whole process will share the same flags now. Build with wasi/wasm and run with wasi/wasm.

**Comment by dannypsnl** [comment]
Does the issue complete?
