### ISSUE TITLE
No arm32 package found in version 0.8.2

### ISSUE THREAD

**Issue by Alps-Sun** [WasmEdge/WasmEdge#2571]
## Description
Supported 32-bit environment.
[https://github.com/WasmEdge/WasmEdge/releases/tag/0.8.2](https://github.com/WasmEdge/WasmEdge/releases/tag/0.8.2)
### Current State
env ：
```
Linux edgenode-4 4.9.80+ #3 Sat Aug 15 16:20:14 CST 2020 armv6l GNU/Linux

root@edgenode-4:~/yomo# cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

```
When I install version 0.8.2, I get the error：

```
Exception: Unsupported arch: armv6l
```

### Expected

Please add maynlinux1 builds for  armv6l (32 bit interpreter only) into the release artifacts. Thank you.

## Environment

- Hardware Architecture: (armv6l)
- Operating system: (Raspbian GNU/Linux 8 (jessie))

**Comment by hydai** [comment]
Since the upstream of manylinux1 only provides x86_64 and i686 arch, and it's already EOL, so we are not going to build on the environment on such arch.
