### ISSUE TITLE
Doc for the version between java bindings and WasmEdge

### ISSUE THREAD

**Issue by liangyuanpeng** [WasmEdge/WasmEdge#2601]
## Motivation

Add doc for version between  bindings (java) and wasmEdge,Today Java binding is out of sync , so the java bindings can working for which version of wasmEdge?

Releated: #2590

**Comment by hydai** [comment]
According to [the last green CI](https://github.com/WasmEdge/WasmEdge/actions/workflows/bindings-java.yml?query=is%3Asuccess), it should be at commit hash [407386c](https://github.com/WasmEdge/WasmEdge/commit/407386cb13c6d55f8da3e188b233d01e15a137a3). It's between 0.11.2 and 0.12.0.

**Comment by auula** [comment]
> ## 动机
> 添加绑定 (java) 和 wasmEdge 之间版本的文档，今天 Java 绑定不同步，那么 java 绑定可以适用于哪个版本的 wasmEdge？
> 
> 相关：#2590
> 
> ## 细节
> ## 附录

I've been doing a bit of reading lately about the built-in wasm runtime. their documentation is written very messy, and senior developers understand that the documentation is divided into two categories, the first for the use of tutorials document, the second is the API documentation. And their software promotion and traditional rogue virus software,installed in the case of the user without knowledge of your computer, without the user's permission, similar to the early PC software bundled sales, which is a disgusting behavior, bundled in the docker sales.

**Comment by auula** [comment]
> ## Motivation
> Add doc for version between bindings (java) and wasmEdge,Today Java binding is out of sync , so the java bindings can working for which version of wasmEdge?
> 
> Releated: #2590
> 
> ## Details
> ## Appendix

I've been doing a bit of reading lately about the built-in wasm runtime. their documentation is written very messy, and senior developers understand that the documentation is divided into two categories, the first for the use of tutorials document, the second is the API documentation. And their software promotion and traditional rogue virus software,installed in the case of the user without knowledge of your computer, without the user's permission, similar to the early PC software bundled sales, which is a disgusting behavior, bundled in the docker sales.

**Comment by auula** [comment]
> ## Motivation
> Add doc for version between bindings (java) and wasmEdge,Today Java binding is out of sync , so the java bindings can working for which version of wasmEdge?
> 
> Releated: #2590
> 
> ## Details
> ## Appendix

I personally recommend you to use [wasmer.io](http://wasmedge.org)!

**Comment by liangyuanpeng** [comment]
Continue tracking in https://github.com/WasmEdge/WasmEdge/issues/3091 and https://github.com/WasmEdge/WasmEdge/issues/3143
