### ISSUE TITLE
undefined symbol: WasmEdge_Driver_UniTool

### ISSUE THREAD

**Issue by MediosZ** [WasmEdge/WasmEdge#2618]
## Description
After building WasmEdge from the latest source, I got `wasmedge: symbol lookup error: wasmedge: undefined symbol: WasmEdge_Driver_UniTool` when running `wasmedge`.
### Current State
Unable to execute wasmedge.

## Environment

- Hardware Architecture: x86_64
- Operating system: Ubuntu 20.04

The following information is optional. Please provide them only if you have built from the source.
- C++ Compiler version: g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
- CMake version: cmake version 3.20.2
- CMake flags: -DWASMEDGE_BUILD_AOT_RUNTIME=OFF -DWASMEDGE_BUILD_TESTS=ON
- Boost version: 1.71.0

**Comment by hydai** [comment]
Hi @MediosZ 
Have you installed wasmedge with the installer before? The wasmedge tool depends on `libwasmedge.so`. You can use `ldd wasmedge` to check if it uses the correct library
