### ISSUE TITLE
Installation on M1 with MacOS 14

### ISSUE THREAD

**Issue by ctzurcanu** [WasmEdge/WasmEdge#2625]
### Current State

when trying to run:

go test ... -run ./go_exec

I get: 
dyld[72540]: Library not loaded: @rpath/libwasmedge.0.dylib
  Referenced from: <D47FD6E5-139F-3627-808D-775EAB3C6ACB> /private/var/folders/bk/nmh337_90t9f5nqh4...
 
  Reason: no LC_RPATH's found

## Environment

- Hardware Architecture: aarch64
- Operating system: macOS 14

The following information is optional. Please provide them only if you have built from source.
- C++ Compiler version:
- CMake version:
- CMake flags: (e.g. `-DCMAKE_BUILD_TYPE=Release -DWASMEDGE_BUILD_AOT_RUNTIME=ON`)
- Boost version:

## Steps to Reproduce

installed: latest Xcode-beta 15.0 beta 2 (15A5161b) and go lang [go1.20.5.darwin-amd64.pkg](https://go.dev/dl/go1.20.5.darwin-amd64.pkg) and

curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- -v 0.11.2

I have run also 
source .../.zprofile

**Comment by hydai** [comment]
Hi @ctzurcanu 
Could you please provide the golang source code you used? I would like to reproduce the environment. Thanks.

**Comment by ctzurcanu** [comment]
I was hoping that this is a problem of installation or hardware or new OS env or golang if not purely WasmEdge v 0.11.2 because this source is under NDA...

**Comment by ctzurcanu** [comment]
source uses https://github.com/second-state/WasmEdge-go/ v 0.11.2

**Comment by hydai** [comment]
I have macOS 13 only. I am trying to figure out how to create a VM with macOS 14 and trying to reproduce the issue.

**Comment by hydai** [comment]
I still cannot reach the macOS 14. Pending this issue until the macOS 14 is out.

**Comment by ctzurcanu** [comment]
bump (macOS 14 is out: the same issue persists)

**Comment by loredanacirstea** [comment]
Same issue on macos 14.0 (23A344) and wasmedge 0.11.3.
I also tried latest wasmedge 0.13.4 with wasmedge-go v0.13.4 and the error is

```
ld: warning: '/private/var/folders/ly/t_77xr1s4w311p8dzfkcwv_m0000gn/T/go-link-645175116/go.o' has malformed LC_DYSYMTAB, expected 126 undefined symbols to start at index 86202, found 388 undefined symbols starting at index 117
dyld[83250]: Library not loaded: @rpath/libwasmedge.0.dylib
  Referenced from: <BFBB355B-08E5-38CF-8866-7C41B59EB59D> /private/var/folders/ly/t_77xr1s4w311p8dzfkcwv_m0000gn/T/go-build4111653988/b001/keeper.test
  Reason: no LC_RPATH's found
```
Additional info:

```bash
$ otool -l wasmedge | grep LC_RPATH -A2
          cmd LC_RPATH
      cmdsize 40
         path @executable_path/../lib (offset 12)
$ otool -L wasmedge
wasmedge:
	@rpath/libwasmedge.0.dylib (compatibility version 0.0.0, current version 0.0.3)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1500.65.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.100.3)
```

**Comment by loredanacirstea** [comment]
This issue happens when running Golang tests. I reproduced it here:

https://github.com/loredanacirstea/WasmEdge-go-examples/tree/lcrpath-bug

```
cd go_ExternRef
go test .
```

**Comment by loredanacirstea** [comment]
It seems that a temporary solution is to run Golang tests with an explicit library path, as suggested in https://github.com/golang/go/issues/36572#issuecomment-817205746

```
CGO_LDFLAGS='-Wl,-rpath,/path/to/library' go test .
```
> where `/path/to/library` is the value of `LD_LIBRARY_PATH`.

On my WasmEdge-go-examples branch I tried:
```
CGO_LDFLAGS='-Wl,-rpath,/Users/user/.wasmedge/lib' go test -v .
```
Aside from warnings like `ld: warning: duplicate -rpath '/Users/user/.wasmedge/lib' ignored`, tests are executed correctly.

**Comment by hydai** [comment]
Hi @loredanacirstea 

Thanks for the hints! Currently, I use the same way to work around. I am curious to know if there is any quick fix for it. This will need time to figure out how to fix it.

**Comment by hydai** [comment]
Seems like we can only use the workaround for now. Closing it. Please feel free to re-open it if there is a better way to handle this problem.
