### ISSUE TITLE
yolov3torust

### ISSUE THREAD

**Issue by sfh123456** [WasmEdge/WasmEdge#263]
We use Python to call tensorflow to detect yolov3. We are preparing to migrate it to wasmedge. The developer can refer to this document for verification（ https://www.secondstate.io/articles/faas-image-classification/ ）
But there are some problems:

When using yolov3 detection, you need to import a piece of code of model.py in yolov3 when importing the model
And then Yolo_ model.load_ weights(self.model_ Path) can be imported into the model. I don't know how to convert this into a rust code.

There is also the need to generate a filtered bounding box boxes (this is a tensor tensor) in advance during detection
boxes: Tensor("concat_11/concat:0", shape=(None, 4), dtype=float32),There are also scores and classes
socres: Tensor("concat_12/concat:0", shape=(None,), dtype=float32)
classes: Tensor("concat_13/concat:0", shape=(None,), dtype=int32)，
The three tensors are generated by Yolo in model. py The three results are fixedThree variables need to be input when sess. Run()
and I don't know how to write this as trust.

model.py code：https://github.com/qqwweee/keras-yolo3/tree/master/yolo3

**Comment by hydai** [comment]
@q82419 Could you check this out?

**Comment by q82419** [comment]
It seems that your code uses `Keras` for training with `TensorFlow` backend.
On the `rust` side, we made the [wasmedge_tensorflow_interface](https://crates.io/crates/wasmedge_tensorflow_interface) for using `TensorFlow` for inferring the saved model.
We only support the session running by `TensorFlow` on `WasmEdge` now, and we don't have `Keras` extension yet.
Maybe we can help you if you only use `TensorFlow` for running on python.
