### ISSUE TITLE
Bump OpenVINO from 2021 to 2023

### ISSUE THREAD

**Issue by hydai** [WasmEdge/WasmEdge#2633]
## Motivation

The install script for OpenVINO is still using the 2021 edition. However, this year is 2023. We should update the version.

## Details

Please update https://github.com/WasmEdge/WasmEdge/blob/master/utils/wasi-nn/install-openvino.sh to install the 2023 edition.

**Comment by Mash707** [comment]
@hydai I am new to open source and would like to contribute to this issue. If I am correct the latest Open Vino version is 2023.0?

**Comment by Mash707** [comment]
#2636

**Comment by bahadirbklg** [comment]
#2656 is it ok?

**Comment by Mash707** [comment]
@bahadirbklg I am currently working on this issue.

**Comment by bahadirbklg** [comment]
> @bahadirbklg I am currently working on this issue.

```diff
 - OPENVINO_YEAR="2021"
 + OPENVINO_YEAR="2023"
```
  this solution leads to broken link because that seems intel didn't used link structure as code predicted.
  ```
  14 curl -sSL https://apt.repos.intel.com/openvino/$OPENVINO_YEAR/GPG-PUB-KEY-INTEL-OPENVINO-$OPENVINO_YEAR | gpg --dearmor > /usr/share/keyrings/GPG-PUB-KEY-INTEL-OPENVINO-$OPENVINO_YEAR.gpg
  ```

**Comment by Mash707** [comment]
> @Mash707
> 
> > @bahadirbklg I am currently working on this issue.
> 
> ```diff
>  - OPENVINO_YEAR="2021"
>  + OPENVINO_YEAR="2023"
> ```
> 
> this solution leads to broken link because that seems in 2023 intel didn't used link structure as code predicted.
> 
> ```
> 14 curl -sSL https://apt.repos.intel.com/openvino/$OPENVINO_YEAR/GPG-PUB-KEY-INTEL-OPENVINO-$OPENVINO_YEAR | gpg --dearmor > /usr/share/keyrings/GPG-PUB-KEY-INTEL-OPENVINO-$OPENVINO_YEAR.gpg
> ```

@bahadirbklg I have updated the script using the apt method to install openvino. The script is working fine. There are some issues in the CI file that I have to fix. You can have a look at my PR for the changes I have made

**Comment by Mash707** [comment]
> > @Mash707
> > > @bahadirbklg I am currently working on this issue.
> > 
> > 
> > ```diff
> >  - OPENVINO_YEAR="2021"
> >  + OPENVINO_YEAR="2023"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > this solution leads to broken link because that seems in 2023 intel didn't used link structure as code predicted.
> > ```
> > 14 curl -sSL https://apt.repos.intel.com/openvino/$OPENVINO_YEAR/GPG-PUB-KEY-INTEL-OPENVINO-$OPENVINO_YEAR | gpg --dearmor > /usr/share/keyrings/GPG-PUB-KEY-INTEL-OPENVINO-$OPENVINO_YEAR.gpg
> > ```
> 
> @bahadirbklg I am updating the script using the apt method to install openvino. The script is working fine. There are some issues in the CI file that I have to fix. You can have a look at my PR for the changes I have made. https://docs.openvino.ai/2023.0/openvino_docs_install_guides_installing_openvino_apt.html

Also If you would like to work on this issue together ? it would be great

**Comment by claddyk** [comment]
Hey @hydai , is this issue availiable to work on?

**Comment by hydai** [comment]
Hi @claddyk 
This is fixed by https://github.com/WasmEdge/WasmEdge/pull/2636
I am closing this issue. Thanks.

**Comment by hydai** [comment]
Since the [WasmEdge-WASINN-examples](https://github.com/second-state/WasmEdge-WASINN-examples) is not updated at the same time, I am re-opening this issue again.

**Comment by claddyk** [comment]
Can I get it assigned?

**Comment by hydai** [comment]
Wrong place. I should raise the new issue in the `WasmEdge-WASINN-examples` repo.

**Comment by Mash707** [comment]
Hii @hydai I will work on this issue. Please assign it to me

**Comment by hydai** [comment]
Hi @Mash707 
Sorry for the confusion. I raise a new issue here: https://github.com/second-state/WasmEdge-WASINN-examples/issues/25

I forgot the docs are already separated into a standalone one, and the examples repo is also separated. :-(

**Comment by Mash707** [comment]
> Hi @Mash707 
> 
> Sorry for the confusion. I raise a new issue here: https://github.com/second-state/WasmEdge-WASINN-examples/issues/25
> 
> 
> 
> I forgot the docs are already separated into a standalone one, and the examples repo is also separated. :-(

No worries.
