### ISSUE TITLE
[Installer] Install with multiple plugins

### ISSUE THREAD

**Issue by q82419** [WasmEdge/WasmEdge#2651]
## Motivation

In current, when users install WasmEdge with multiple plugins by installer, they would use the command:

```
curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- --plugins wasmedge_tensorflow;wasmedge_tensorflowlite
```

But our usage for the splitter of multiple plugins (`;`) will cause error because the `;` is the command splitter in bash and zsh.

## Details

Maybe should use `,` to separate the plugins?

cc @hydai  @SAtacker

**Comment by hydai** [comment]
Hi @q82419 
I think the current behavior is `--plugins X Y Z`, which uses `space` to separate the plugins.
We don't need to use `,`, instead, we have to emphasize how to install multiple plugins at one time in the docs.

**Comment by q82419** [comment]
It seems like its the lack of docs.
Close this issue.
