### ISSUE TITLE
[Installer] Environment not work on zsh (MacOS arm64)

### ISSUE THREAD

**Issue by q82419** [WasmEdge/WasmEdge#2652]
### Current State

After installation:

```
WasmEdge Successfully installed
Run:
source /Users/q82419/.zprofile
```

But there may be no `.zprofile` in user's home directory.

### Expected

Actually, the installer add the `. "$HOME"/.wasmedge/env` into the `.bashrc` or `.bash_profile` after installation if the shell is bash.

For the zsh, we should add that command into `.zshenv`, not `.zprofile`.
And we'd better to create the `.zshenv` if the file doesn't exist.

## Environment

- Hardware Architecture: arm64
- Operating system: MacOS 13.2

**Comment by hydai** [comment]
Hi @SAtacker 
Our CI runner provides macOS arm64 env. Please use `mac-arm64` label for testing in the workflow files.

**Comment by SAtacker** [comment]
Alrighty thanks for this
