### ISSUE TITLE
Provide `checksum` for the release assets

### ISSUE THREAD

**Issue by apepkuss** [WasmEdge/WasmEdge#2678]
Is it possible to provide `checksum` for the assets of each release? From the perspective of security, the `checksum` or similar things for the release assets is necessary for users to guarantee that they download the right things from the right place.

Related issue [#34](https://github.com/WasmEdge/wasmedge-rust-sdk/issues/34) from `wasmedge-rust-sdk`.

**Comment by hydai** [comment]
Hi @apepkuss 
I added the `SHA256SUM` files in each release asset after 0.11.2. Thanks.
