### ISSUE TITLE
feat: LFX add matrix operations for opencvmini

### ISSUE THREAD

**Issue by dannypsnl** [WasmEdge/WasmEdge#2680]
## Motivation

WasmEdge is a WebAssembly runtime that supports both interpreter and ahead-of-time modes. To expand its capabilities, we have plugin system helps people attach more existed software, OpenCVMini is one of them intend to help users get a limited OpenCV interface. In this mentorship, we aim to add more OpenCV capabilities into the WasmEdge environment.

### Expected outcome

- Define the new interfaces for OpenCVMini plugin which supports these functions
   - Complete image filtering functions in document[^1]
   - Complete drawing functions in document[^2]
   - Complete feature detection functions in document[^3]
   - Complete related `cv::Mat` member functions in document[^4]

   and
   - With OpenCV 4.x.
   - Re-export functions in C style
- Design unit tests and examples for verifying the above functions.
   - `>80%` of code coverage for these functions.
- Enable the building, testing, and packaging on the CI.
- Write documents about how to build and use this plugin.

### Recommended Skills: C/C++, OpenCV, Rust, WebAssembly

You might need Haskell, in a very low possibility.

### Pre-test

Please make sure you submit your pre-test repo link to the following discussion:
https://github.com/WasmEdge/WasmEdge/discussions/2681

### Apply here

https://mentorship.lfx.linuxfoundation.org/project/f21bec94-085e-4e2d-94ac-3b61b4471818

[^1]: https://docs.opencv.org/4.x/d4/d86/group__imgproc__filter.html
[^2]: https://docs.opencv.org/4.x/d6/d6e/group__imgproc__draw.html
[^3]: https://docs.opencv.org/4.x/dd/d1a/group__imgproc__feature.html
[^4]: https://docs.opencv.org/4.x/d3/d63/classcv_1_1Mat.html

**Comment by aashi-ihsaa** [comment]
@dannypsnl interested in this project under lfx. i have experience with rust and c++, though opencv is a new domain for me. i am working on the pre test. would be great if you could guide me a bit about the project. Thanks!

**Comment by PurviChaurasia** [comment]
Hi, @dannypsnl I am extremely interested in this project. I am working on the pre-test currently and will let you know when I'm done. I have previously worked with C++ and OpenCV and am currently working on learning rust. It would be extremely helpful if you could point out what exactly you're looking for in a candidate so that we can work towards that. I think this would help both me and @aashi-ihsaa. Thanks!
