### ISSUE TITLE
How to read host file in wasmedge runtime

### ISSUE THREAD

**Issue by chris-void-777** [WasmEdge/WasmEdge#2700]
### Discussed in https://github.com/WasmEdge/WasmEdge/discussions/2698

<div type='discussions-op-text'>

<sup>Originally posted by **chris-void-777** July 30, 2023</sup>
Now I want to compile my c code which need to read host file to wasm and run it in wasmedge.Here is a example:
```c
#include <stdio.h>
#include <errno.h>
#include <string.h>

int main() {
  FILE *file = fopen("a.txt", "rb");
  if (!file) {
    puts(strerror(errno));
    printf("cannot open file\n");
    return 1;
  }
  while (!feof(file)) {
    char c = fgetc(file);
    if (c != EOF) {
      putchar(c);
    }
  }
  fclose (file);
  return 0;
}
```
compile command:
```bash
emcc test.c -o out.wasm
```
excute command:
```bash
$ wasmedge out.wasm 
Operation not permitted
cannot open file
```
my environment: x86_64 ubuntu22.04

<br>

This appears to be due to the sandboxed nature of Wasmedge.I have checked the C language development documentation for Wasmedge, but couldn't find relevant information. Is there any way to achieve this?
Thans for your time and assistance
</div>

**Comment by hydai** [comment]
Use `--dir` option. Ref: https://wasmedge.org/docs/start/build-and-run/cli#options

**Comment by chris-void-777** [comment]
> Use `--dir` option. Ref: https://wasmedge.org/docs/start/build-and-run/cli#options

Thank you for your response. I added the parameter, but the result is still the same.The complete process is as follows:
1.Create a C language source code file named test.c with the following content:
```c
#include <stdio.h>
#include <errno.h>
#include <string.h>

int main() {
  FILE *file = fopen("./a.txt", "r");
  if (!file) {
    puts(strerror(errno));
    printf("cannot open file\n");
    return 1;
  }
  while (!feof(file)) {
    char c = fgetc(file);
    if (c != EOF) {
      putchar(c);
    }
  }
  fclose (file);
  return 0;
}
```
2.Compile the C code into WebAssembly format using Emscripten:
```bash
emcc test.c -o test.wasm
```
3.The current directory's contents are as follows:
```bash
~$ ls
add.c  a.txt  example  onnxruntime  test.c  test.wasm  test_wasmedge.c
~$ cat a.txt
hello,emcc
~$ ls -al a.txt
-rwxrwxrwx 1 chris chris 11  7月 31 14:44 a.txt
```
4.excute:
```bash
$ wasmedge --dir .:. test.wasm 
Operation not permitted
cannot open file
```
5. Here is my system environment:
```bash
$ uname -a
Linux chris-NbDE-WXX9 5.19.0-46-generic #47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 21 15:35:31 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```
Is there an issue with the parameter I added? Or is there something I overlooked?Thank you for your guidance.

**Comment by hydai** [comment]
Looks like the `emcc` is not correct.
I use `wasi-sdk` to compile it and it works.
![CleanShot 2023-07-31 at 15 09 24](https://github.com/WasmEdge/WasmEdge/assets/2776756/f133be1a-61ae-45b6-8dca-d00170a2896c)

**Comment by chris-void-777** [comment]
> Looks like the `emcc` is not correct. I use `wasi-sdk` to compile it and it works. ![CleanShot 2023-07-31 at 15 09 24](https://user-images.githubusercontent.com/2776756/257143542-f133be1a-61ae-45b6-8dca-d00170a2896c.png)

That could be because emcc might not be using the relevant WASI interfaces. I will check the documentation of Emscripten for further information. Thank you for your help.
