### ISSUE TITLE
Hangs out while executing the given testcase

### ISSUE THREAD

**Issue by luxinyi0105** [WasmEdge/WasmEdge#2710]
## Description

While executing the given testcase, WasmEdge hangs out and does not end.

### Current State

```sh
$ wasmedge mutated.wasm 
```
It will hang out and does not end.

### Expected

Correctly output a result, or terminate due to triggering internal exception handling logic, and output relevant inforfation(maybe).

## Environment

- Hardware Architecture: x86_64
- Operating system: Ubuntu 22.04
- Tools Version: wasmedge 0.13.2

## Extra info

Actually, the given test case was simply mutated a wasm file, which was obtained by compiling the C program generated with Csmith using the Emscripten compiler (Emcc). You can convert wasm file to wat format with wabt and find the mutation operation in line 2326(replace i32.sub with i32.div_s). Releated files is [here](https://github.com/luxinyi0105/wasm_runtime_test/raw/main/08-01.zip).

I used some other WebAssembly Runtimes, e.g. wasmer and wasmtime, to execute the same testcase. They will terminate the execution of the wasm file in approximately 6-8 seconds, but do not output anything. I'm not sure if their behaviour is correct, but it seems that "hang out" is not a good choice.

**Comment by alabulei1** [comment]
Hi @hydai @q82419  

Could you please take a look? Thanks!

**Comment by hydai** [comment]
Hi @luxinyi0105 
Thanks for this. It seems like the behavior is different from other runtimes. However, do you have an expected result for this test case?

**Comment by luxinyi0105** [comment]
> Hi @luxinyi0105
> Thanks for this. It seems like the behavior is different from other runtimes. However, do you have an expected result for this test case?

Thanks for your reply. But I am unable to determine what the expected result is due to a lack of understanding of WebAssembly.

**Comment by hydai** [comment]
So this Wasm file doesn't have an expected result. And the current behaviors are different between wasmtime and wasmedge.

Since the expected behavior is unknown, I will leave this as a `help wanted` issue. It will need people to dig into the execution codes and figure it out.

**Comment by hydai** [comment]
Hi @luxinyi0105 
I believe the hangs issue is caused by the interpreter mode. When I used ahead-of-time instead, it will end in 8 seconds on my dev machine.

![CleanShot 2023-08-07 at 22 36 34](https://github.com/WasmEdge/WasmEdge/assets/2776756/710e7181-7a0b-4613-b46a-62cd852f53b0)

So I think this issue can close. Could you verify it?

**Comment by luxinyi0105** [comment]
> Hi @luxinyi0105 I believe the hangs issue is caused by the interpreter mode. When I used ahead-of-time instead, it will end in 8 seconds on my dev machine.
> 
> ![CleanShot 2023-08-07 at 22 36 34](https://user-images.githubusercontent.com/2776756/258834204-710e7181-7a0b-4613-b46a-62cd852f53b0.png)
> 
> So I think this issue can close. Could you verify it?

Okay, the problem has been resolved. Thank you for your reply!
