### ISSUE TITLE
[Docs] update redirect links in the WasmEdge docs folder

### ISSUE THREAD

**Issue by hydai** [WasmEdge/WasmEdge#2716]
## Description

WasmEdge split the docs from this main repository to a brand new one, [WasmEdge/docs](https://github.com/WasmEdge/docs). Since some files are moved to different places, the original link may not work.
This issue is for tracking these unresolved/non-updated links to up-to-date.

### Current State

For example, links in [this page](https://wasmedge.org/book/en/write_wasm/rust/wasinn.html) are not available because there are [several refactoring PRs](https://github.com/WasmEdge/docs/pulls?q=is%3Apr+is%3Aclosed+author%3Aq82419) which changed the paths.

### Expected

All links in the [original WasmEdge docs](https://wasmedge.org/book/en/) should work with [the WasmEdge docs](https://wasmedge.org/docs).

If you find any link is wrong, please raise PRs to fix them.

**Comment by Mash707** [comment]
Hii @hydai I would like to work on this. Should we Raise PRs in the docs repo?

**Comment by Mash707** [comment]
> I don't think so. These files are located in https://github.com/WasmEdge/WasmEdge/tree/master/docs

Thanks for the information. I will start working on this.
