### ISSUE TITLE
Performance problem while executing the given wasm file in the interpreter mode

### ISSUE THREAD

**Issue by luxinyi0105** [WasmEdge/WasmEdge#2724]
## Description
WasmEdge maybe have performance problems while executing the [given wasm file](https://github.com/luxinyi0105/wasm_runtime_test/raw/main/08-07.zip).

### Current State
```sh
$ wasmedge mutated.wasm
```
It will take about 10 minutes to output the correct checksum result `checksum = 93DF9E88`

### Expected
```sh
$ wasmedge mutated.wasm
checksum = 93DF9E88
```

## Environment
- Hardware Architecture: x86_64
- Operating system: Ubuntu 22.04
- Tools Version: wasmedge 0.13.2

## Extra Info
The current execution result of WasmEdge is correct, but it will take about 10 minutes, far exceeding the time required to execute other wasm files. At the same time, using other WebAssembly runtimes, such as wasmer and wasmtime, to execute the same wasm file will take no more than 1 minute to obtain the correct execution results. Therefore, I believe that there may be `performance related problems` in WasmEdge, which may slow down the execution speed of the given testcase.

**Comment by hydai** [comment]
Hi @luxinyi0105 
You are using the interpreter mode by default, which is slow. If you would like to run a compute-intensive program, please use ahead-of-time compilation mode instead.

![CleanShot 2023-08-07 at 22 12 38](https://github.com/WasmEdge/WasmEdge/assets/2776756/388904cf-2170-48c9-b503-5ac27c20581b)

**Comment by luxinyi0105** [comment]
> Hi @luxinyi0105 You are using the interpreter mode by default, which is slow. If you would like to run a compute-intensive program, please use ahead-of-time compilation mode instead.
> 
> ![CleanShot 2023-08-07 at 22 12 38](https://user-images.githubusercontent.com/2776756/258827456-388904cf-2170-48c9-b503-5ac27c20581b.png)

Thanks for your reply, the problem has been resolved.
