### ISSUE TITLE
Installer does not work on Fish shell

### ISSUE THREAD

**Issue by zifeo** [WasmEdge/WasmEdge#2749]
## Description

A backward incompatible change has been introduced in https://github.com/WasmEdge/WasmEdge/commit/175fbcad9f64c2c91f343c44bf6a67c590dd17b4, breaking the installation for shells different from bash and zsh, which were working successfully before.

### Current State

```
INFO    - WasmEdge Successfully installed
Traceback (most recent call last):
  File "<stdin>", line 1776, in <module>
  File "<stdin>", line 1614, in main
  File "<frozen genericpath>", line 19, in exists
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

### Expected

Successful installation.

## Environment

- Hardware Architecture: (e.g. x86\_64 or aarch64) aarch64
- Operating system: (e.g. Ubuntu 20.04 or CentOS 7.6) macOS

## Steps to Reproduce

With Fish:
```bash
curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s --
```

**Comment by alabulei1** [comment]
Hi @SAtacker and @hydai , could you please take a look? Thanks.

**Comment by SAtacker** [comment]
I don't think it was ever designed to handle fish shell. And the patch does not intend to break backward incompatibility.
