### ISSUE TITLE
Javascript SDK

### ISSUE THREAD

**Issue by ShayanShiravani** [WasmEdge/WasmEdge#2767]
## Motivation

We want to use the Javascript SDK to embed WasmEdge into our host application.

## Details

As you mentioned in your official website, we can embed the WasmEdge functions into our host app written in Node.js, but I can't find any useful information in your technical docs explaining how I can do that. Could you please help me to find a solution?

**Comment by hydai** [comment]
Hi @ShayanShiravani 
Thanks for your interest.

We have moved the focus from [the NAPI SDK](https://github.com/second-state/wasmedge-core/) to [WasmEdge-quickjs integration](https://github.com/second-state/wasmedge-quickjs). 
It should have the same capability to use the quickjs one instead. Please let me know if you have any other questions. Thanks.
