### ISSUE TITLE
Exposing `uint8_t` / `uint16_t` / arbitrary enum types in for opencvmini plugin

### ISSUE THREAD

**Issue by Charles-Schleich** [WasmEdge/WasmEdge#2786]
## Motivation

Currently the opencvmini plugin can only accept types from that implement `ValTypeFromType`, 
the list of types is shown [here](https://github.com/WasmEdge/WasmEdge/blob/96ecb670f035ba193e0660118c24922092a6b00b/include/common/types.h#L228C1-L228C65). 
I am seeking some discussion to see if it makes sense / is possible to expose enums types that plugins would make use of.
With the idea to expose the types only if the plugin is compiled.

## Details

I am exposing the `cv::resize` and `cv::normalize` functions in the `opencvmini` plugin to support my creation of the YOLO Rust SDK.
In the case of `cv::resize`: the function takes an interpolation parameter, which is represented by an enum with 10 possible variants,  [cv::InterpolationFlags](https://docs.opencv.org/3.4/da/d54/group__imgproc__transform.html#ga5bb5a1fea74ea38e1a5445ca803ff121)
currently the only way to create a function in the plugin that can expose resizing an image, is to declare the interpolation parameter type `uint32_t`
If i try declare the parameter as a `uint16_t` or `uint8_t`, the compile error hints at the type not being supported by `ValTypeFromType` template.

Would it make sense / is this something wanted, to expose types such as enums to make calling these functions slightly more clear ?
i.e. Instead of passing in a `uint32_t` to the `resize` function, where `uint32_t` can represent many values that are not included in the enum that `resize` requires.

Does this sort of make sense, does it fit in with the expected design of WasmEdge, and is it something that the project would want to support ?

**Comment by dannypsnl** [comment]
@hydai Do you know any related proposal, simple view is this making sense, but we indeed have no `IntN` except `N = 32 or 64`

**Comment by hydai** [comment]
The value definition is in spec. You have no way to change it.
If you want to pass a short number, just use the `32` or `64` types and cast them under your host function implementation.
On the other hand, you may need to use `i32` as offset on the memory and another `i32` as length to retrieve the larger types from the WASM memory section. You can find more information such as [environ_get in WASI](https://github.com/WebAssembly/WASI/blob/main/legacy/preview1/docs.md#-environ_getenviron-pointerpointeru8-environ_buf-pointeru8---result-errno)

**Comment by Charles-Schleich** [comment]
This makes sense, @hydai.
Thank you for the share.
