### ISSUE TITLE
How can other runtimes directly use the result memory of main.wasm?

### ISSUE THREAD

**Issue by 17862687921** [WasmEdge/WasmEdge#2788]
```
//main.rs
pub fn main() {
  let mut results = [0u32; 10];

  for i in 0..10 {
    let result = i + 10;
    results[i] = result;
  }
}
```
We converted the above code into `main.wasm` through `cargo build --release --target=wasm32-wasi`, and then run it in the terminal using`wasmedge --dir .:. main.wasm`. How can we directly use the memory of the running result instead of writing it to a file. For example, in the python language, directly use the result of `results[2]` in `main.wasm` to complete subsequent calculations (such as `num=main.wasm.results[2]+100`). Thanks.

**Comment by hydai** [comment]
1. CLI doesn't support this feature.
2. You can retrieve the `memory instance` via SDK. And use the `offset + length` to get the value. However, you must know the data structure's `memory offset` first. There is no way to know which memory section belongs to the `results` after it is compiled into the Wasm format from the WasmEdge side.

**Comment by hydai** [comment]
Closing this. If you have any more questions, please feel free to re-open it or raise a new issue.
