### ISSUE TITLE
WasmEdge FFmpeg Queries

### ISSUE THREAD

**Issue by Hrushi20** [WasmEdge/WasmEdge#2790]
I'm working on the design on FFMpeg plugin on C++ side. I noticed that plugins maintain an internal data structure to hold Structs in c++ ([Example](https://github.com/WasmEdge/WasmEdge/blob/f6d99c87fef0db160d17ccf3f7f3cd87cbd56e68/plugins/wasmedge_tensorflow/tensorflow_env.h#L124)) and store the index of the data structure in Rust side ([Example](https://github.com/WasmEdge/WasmEdge/blob/f6d99c87fef0db160d17ccf3f7f3cd87cbd56e68/plugins/wasmedge_tensorflowlite/tensorflowlite_func.cpp#L107)).

FFMpeg, deals with a lot of structs (more than 50 structs). Do you think its apt to create a
`vector <void * > ffmpegLinearMemory` and use this data structure to store all the FFMpeg structs in the plugin??? 

I created a [basic memory management system](https://github.com/Hrushi20/WasmEdge/blob/62482c0f164170aa2bdad5831d90ae82c3a016b1/plugins/wasmedge_ffmpeg/ffmpeg_env.h#L30) on C++ side.
It has 3 functions-
* alloc
* dealloc
* fetchData

Do you have any other suggestions?

**Comment by hydai** [comment]
Sorry, I didn't get the point. Why do you have to create such a data structure for storing the different structs? Do you have an example code for this situation?

**Comment by Hrushi20** [comment]
The idea is -

* Everytime the rust function call an FFmpeg function we pass an index of struct in `ffmpegMemory` to the plugin
* The plugin check if the index is valid or not. If valid it fetches the struct from `ffmpegMemory`.
* Then the underlying FFmpeg C API is called using that struct. 

The reason for this approach is because I am not able to access the c++ address space (host_func) from Wasm.

https://github.com/Hrushi20/WasmEdge/blob/62482c0f164170aa2bdad5831d90ae82c3a016b1/plugins/wasmedge_ffmpeg/ffmpeg_env.h#L30

In the above link, I created a memory allocator, deallocator and fetchData functions to fetch,store,delete the structs from the data structure. 

https://github.com/Hrushi20/WasmEdge/blob/62482c0f164170aa2bdad5831d90ae82c3a016b1/plugins/wasmedge_ffmpeg/avformat/avformat_func.cpp#L68

The alloc function stores the index value of the struct in `ffmpegMemory` and this index is used on the rust side as well.

**Comment by hydai** [comment]
Another approach is that you can define the structures at the WASM level. Allocate them on the WASM memory section, get the offset, and use the offset between different functions. Using this approach can help developers to use a similar way to access the API. But your solution is easier to implement.

--- 

According to your above codes, some seem incorrect:
1. `ffmpegLinearMemory` is not a linear memory. This name is not accurate. It only stores pointers, not the real data.
2. We must provide a way to clear the `ffmpegMemory` at the end of the execution, otherwise, the memory will leak.

**Comment by Hrushi20** [comment]
Is there any benefits of allocating data on Wasm memory section. Can you give me an Example of allocating data on Wasm Memory section?

**Comment by hydai** [comment]
1. Allocating memory space on the WASM memory instance can be defined at the SDK level, which means the memory management is shipped with the SDK itself. So developers can have more flexibility to do anything on the SDK side.
2. Passing the data between WASM and host functions is unified, all you need to do is to handle the `offset` and `length` such as [this](https://github.com/WasmEdge/WasmEdge/blob/master/plugins/wasmedge_opencvmini/opencvmini_func.cpp#L109-L119).


However, if you want to do this, you may need to create the wasm-mapped data structures such as [WASI does](https://github.com/WasmEdge/WasmEdge/blob/master/thirdparty/wasi/api.hpp#L939-L959) for each data structure. It takes time.

**Comment by Hrushi20** [comment]
I think the above approach might not be the best. In future, if FFmpeg decide to update the data structure, we also need to update the wasm-mapped data structure. Also FFmpeg has a lot of structs, creating this mapping for each one will take time.

**Comment by Hrushi20** [comment]
I had another approach in mind. Once I create a struct on C++ side, can I store this structs pointer on the rust side and use this pointer between different functions to fetch the struct data?

**Comment by Hrushi20** [comment]
Hey @hydai, when the ffmpeg application frees a pointer, the same pointer in `ffmpegPointerMemory` is updated to nullptr. Do I use a queue to track such nullptr locations so that we can reuse the indices in `ffmpegPointerMemory`.

This can help us avoid lots of `nullptr` in the vector and reuse the space.

Do you have any other approach in mind???

**Comment by hydai** [comment]
You don't need to have a vector. The relationship between `index` and `pointer` is a one-to-one mapping. Using `std::map` would be better. If a pointer gets removed, we can erase the index from the map directly.

**Comment by Hrushi20** [comment]
Thanks. I'll create a variable which increments on allocation and use that as key in `std::map`.

**Comment by Hrushi20** [comment]
Hey, I am creating functions to fetch field data from Structs. What is the naming convention I should follow? 

``` C 
struct AVCodec {
    int codec_id,
    int codec_type
}
```
To fetch the data for above fields, currently I created a `AVCodec_codec_id` and `AVCodec_codec_type`  classes in plugin. These classes are responsible for fetching data from struct. Is this convention good? I feel its easier to search this way.

**Comment by hydai** [comment]
Please follow the LLVM coding style. You can also apply with https://github.com/WasmEdge/WasmEdge/blob/master/.clang-tidy

**Comment by Hrushi20** [comment]
<img width="1047" alt="Screenshot 2023-09-15 at 12 43 41 PM" src="https://github.com/WasmEdge/WasmEdge/assets/65367566/d51d26ac-ed76-4dc1-9c44-07369699f8fc">

<img width="1047" alt="Screenshot 2023-09-15 at 12 43 31 PM" src="https://github.com/WasmEdge/WasmEdge/assets/65367566/0d7f2ab9-1f2a-447b-a387-c381b759a540">


Does `libc::strerror()` gives different error output for wasmedge and native pc? I am getting error code 22 from FFmpeg, however libc is generating different error messages for same error code.  

The first image Prints `Invalid Argument` as Error when I run it natively on my computer. 
The Second image Prints `File too large` for the same error code while running on WasmEdge.

**Comment by hydai** [comment]
I don't think so. Could you check the implementation of the ffmpeg for logging more information?

**Comment by Hrushi20** [comment]
The logging is done by `libc:strerror()`. FFmpeg just returns the Error code (In this case 22).

**Comment by Hrushi20** [comment]
Another Query regarding Errors:

What error codes do I return from Plugin when related to Null Pointers/ Missing Memory or WasmEdge Errors? For now I am returning the below error codes. However I realized if any FFmpeg function returns a negative value as result, then the rust sdk would detect it as WasmEdge error if it collides with below error code. 

<img width="566" alt="Screenshot 2023-09-15 at 5 39 58 PM" src="https://github.com/WasmEdge/WasmEdge/assets/65367566/29eee57e-949f-4d2d-b32a-f27c8e432976">

Do I check for the above errors on Rust Sdk for each function call? 

Currently on C++ side, I am doing the basic checks(https://github.com/Hrushi20/WasmEdge/blob/76de3d9fdfec47c784a2b670541385ffb8911d8b/plugins/wasmedge_ffmpeg/avformat/avformat_func.cpp#L13)

**Comment by Hrushi20** [comment]
Is there a way to return String from C++ Plugin without specifying the length of the buffer in Rust? I need to return a String from FFmpeg and I don't know the length of the buffer.

**Comment by hydai** [comment]
> Another Query regarding Errors:
> 
> What error codes do I return from Plugin when related to Null Pointers/ Missing Memory or WasmEdge Errors? For now I am returning the below error codes. However I realized if any FFmpeg function returns a negative value as result, then the rust sdk would detect it as WasmEdge error if it collides with below error code.
> 
> <img alt="Screenshot 2023-09-15 at 5 39 58 PM" width="566" src="https://user-images.githubusercontent.com/65367566/268275611-29eee57e-949f-4d2d-b32a-f27c8e432976.png">
> Do I check for the above errors on Rust Sdk for each function call?
> 
> Currently on C++ side, I am doing the basic checks(https://github.com/Hrushi20/WasmEdge/blob/76de3d9fdfec47c784a2b670541385ffb8911d8b/plugins/wasmedge_ffmpeg/avformat/avformat_func.cpp#L13)

You should have a document to record these error codes and handle them on the Rust SDK side. The WasmEdge plugin doesn't ask developers to have a specific error code style.

> Is there a way to return String from C++ Plugin without specifying the length of the buffer in Rust? I need to return a String from FFmpeg and I don't know the length of the buffer.

You MUST pass the string buffer and the max length of the string. If the returned string is larger than the given buffer, it should trigger an error and fail.

**Comment by Hrushi20** [comment]
> The logging is done by `libc:strerror()`. FFmpeg just returns the Error code (In this case 22). Using the libc crate as FFmpeg return unix error codes.

<img width="377" alt="Screenshot 2023-09-18 at 3 42 17 PM" src="https://github.com/WasmEdge/WasmEdge/assets/65367566/e855bcb5-5efa-4b28-9c62-15ef405c4e00">

@hydai, there seems to be an issue. I tried running the above code on native pc and on Wasmedge. I get different error message printed for same error code. 

``` 
cargo run

Error Code: Invalid argument   (Output)                              
```

```
wasmedge target/wasm32-wasi/debug/libc-test.wasm

Error Code: File too large.  (Output)                            
```
Not sure how to proceed with this issue.

**Comment by Hrushi20** [comment]
I've done some debugging and realized that after compiling libc to wasm, the error codes do not remain the same. 
Eg: EAGAIN on native PC give error code 35, where as wasm gives 6.

**Comment by Hrushi20** [comment]
> > The logging is done by `libc:strerror()`. FFmpeg just returns the Error code (In this case 22). Using the libc crate as FFmpeg return unix error codes.
> 
> <img alt="Screenshot 2023-09-18 at 3 42 17 PM" width="377" src="https://user-images.githubusercontent.com/65367566/268614985-e855bcb5-5efa-4b28-9c62-15ef405c4e00.png">
> 
> @hydai, there seems to be an issue. I tried running the above code on native pc and on Wasmedge. I get different error message printed for same error code. I've created a new rust project and used libc rust package.
> 
> ```
> cargo run
> 
> Error Code: Invalid argument   (Output)                              
> ```
> 
> ```
> wasmedge target/wasm32-wasi/debug/libc-test.wasm
> 
> Error Code: File too large.  (Output)                            
> ```
> 
> Not sure how to proceed with this issue.

Hey @hydai @juntao, can you help me out with this. I'm not sure how to proceed with this issue

**Comment by hydai** [comment]
@Hrushi20 
Please trace the code and figure out the error code generated by which function/syscall in the WASM scope.
And will this block your progress? We can handle the errors with the correct error string later.

**Comment by Hrushi20** [comment]
Can I use `gmock` for mocking objects in C++ Plugin while testing???

**Comment by hydai** [comment]
> Can I use `gmock` for mocking objects in C++ Plugin while testing???

Yes.

**Comment by Hrushi20** [comment]
I am unable to use GMock, can you guide me on configuring GMock. I get 'gmock/gmock.h' header file is missing.

**Comment by hydai** [comment]
> I am unable to use GMock, can you guide me on configuring GMock. I get `gmock/gmock.h` header file is missing.

You should enable it first: https://github.com/WasmEdge/WasmEdge/blob/master/test/CMakeLists.txt#L14

**Comment by Hrushi20** [comment]
I changed the variable to ON, still facing the same error.

**Comment by Hrushi20** [comment]
It is compiling now. I added the 'gmock;gmock' in here: https://github.com/WasmEdge/WasmEdge/blob/5286cc54ee73d0fdcfe039bf4d1d7e82707b4086/test/CMakeLists.txt#L60

**Comment by Hrushi20** [comment]
Hey, I working on adding test. I have few queries
I am trying to test [AVFrame](https://github.com/Hrushi20/WasmEdge/blob/feature-ffmpeg-plugin/plugins/wasmedge_ffmpeg/avutil/avFrame.cpp) methods in C++ Plugin. I need to perform various other allocation, iterate through packets to get an Actual AVFrame Struct which contains data for testing. 

I am not sure about the right way of writing a unit test for these functions. If I try accessing the width,height of frame it results in NULL.

Some FFmpeg functions depends on other structs. Do I need to write the actual logic of processing a video to create such a structs? Various structs depend on each other. Should I call FFmpeg functions directly in test (Tests would be tied to FFmpeg library)?. Can you suggest me a way to write unit tests.

**Comment by hydai** [comment]
If you cannot use gmock to do this, you have to create real structs.

**Comment by Hrushi20** [comment]
Hey @hydai, can you quick review the tests I have written for `swscale` ffmpeg library. 

https://github.com/Hrushi20/WasmEdge/blob/feature-ffmpeg-plugin/test/plugins/wasmedge_ffmpeg/swscale/swscale_func.cpp.

**Comment by hydai** [comment]
If you need my review, please send a draft PR.

**Comment by Hrushi20** [comment]
Hey @hydai, I've created a draft PR #2885

**Comment by Hrushi20** [comment]
Hey, I tried integrating FFmpeg Plugin into Mediapipe-rs repository. I'm facing an issue while executing the example.  
<img width="1359" alt="Screenshot 2023-10-10 at 8 01 28 AM" src="https://github.com/WasmEdge/WasmEdge/assets/65367566/68ade2b4-e83a-43a7-bfe3-8dfb88b73eb8">

However, if I create a new repository I am able to execute FFmpeg functionalities.

**Comment by juntao** [comment]
A potential problem I can think of is that the mediapipe project already incorporated ffmpeg -- it compiles ffmpeg into Wasm. You will need to swap that out with your host function based SDK.

**Comment by Hrushi20** [comment]
I've removed the existing ffmpeg dependency from cargo.toml file and added host function based SDK in cargo.toml file.

**Comment by Hrushi20** [comment]
Hey, I wanted to check the performance difference between Rust based FFmpeg Sdk (C++ Plugin) and Wasm based FFmpeg.

I'm not able to run the wasm based FFmepg mediapipe-rs examples. I get the following error.

<img width="1359" alt="Screenshot 2023-10-13 at 12 56 19 AM" src="https://github.com/WasmEdge/WasmEdge/assets/65367566/4590d5c7-12a7-41ec-b101-2e9bb4efe0bd">

What is the Env module and clock function?

**Comment by hydai** [comment]
If you are using emcc, please make sure you use the standalone wasm mode. This is a helper function defined by emcc. It's not a standard of WASI.

**Comment by Hrushi20** [comment]
I've used cmake, ninja to build WasmEdge. How do I use standalone wasm mode?

**Comment by hydai** [comment]
> I've used cmake, ninja to build WasmEdge. How do I use standalone wasm mode? 

I cannot get it. Where do you get the wasm file contains the env/functions?

**Comment by Hrushi20** [comment]
I get this error while running `image classification` example file in mediapipe-rs.

**Comment by hydai** [comment]
> I get this error while running `image classification` example file in mediapipe-rs.

Please provide the repo you used and the detailed steps so we can reproduce it.

**Comment by Hrushi20** [comment]
## Mediapipe-rs Examples 

### Description:
While Running the [Mediapipe-rs Examples](https://github.com/WasmEdge/mediapipe-rs), I am getting following error. 

<img width="1359" alt="Screenshot 2023-10-13 at 10 15 05 PM" src="https://github.com/WasmEdge/WasmEdge/assets/65367566/9502eb4f-ffbd-4a41-89a6-3aa085a8f529">

Step 1 (Building WasmEdge) -
``` bash
mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Release -GNinja  -DWASMEDGE_BUILD_PLUGINS=ON -DWASMEDGE_PLUGIN_WASI_NN_BACKEND="TensorflowLite" .. 
ninja | sudo ninja install
```

Step 2 (Mediapipe-rs) -
Execute Mediapipe-rs using FFmpeg. I removed conditional compilation for FFmpeg.

``` bash
git clone https://github.com/WasmEdge/mediapipe-rs.git 
cd scripts
./download-models.sh 
./download-testdata.sh
./ffmpeg-deps-init.sh
./env.sh
cd ..
```

Running Audio Classification. 
``` rust
cargo run --release --example audio_classification -- ./assets/models/audio_classification/yamnet_audio_classifier_with_metadata.tflite ./assets/testdata/audio/speech_16000_hz_mono.wav

```

**Comment by Hrushi20** [comment]
Also, can you help me come up with a strategy for testing? I've written some basic tests for independent components. However, I need to write tests for components depending on various other FFmpeg structs. 

I'm not sure how to create such a struct and store it's pointer. Do I create certain util classes which call the FFmpeg C++ Module functions to initialize such structs? Do you have any other approach in mind?

**Comment by hydai** [comment]
> ## Mediapipe-rs Examples
> ### Description:
> While Running the [Mediapipe-rs Examples](https://github.com/WasmEdge/mediapipe-rs), I am getting following error.
> 
> <img alt="Screenshot 2023-10-13 at 10 15 05 PM" width="1359" src="https://user-images.githubusercontent.com/65367566/274965899-9502eb4f-ffbd-4a41-89a6-3aa085a8f529.png">
> Step 1 (Building WasmEdge) -
> 
> ```shell
> mkdir build && cd build
> cmake -DCMAKE_BUILD_TYPE=Release -GNinja  -DWASMEDGE_BUILD_PLUGINS=ON -DWASMEDGE_PLUGIN_WASI_NN_BACKEND="TensorflowLite" .. 
> ninja | sudo ninja install
> ```
> 
> Step 2 (Mediapipe-rs) - Execute Mediapipe-rs using FFmpeg. I removed conditional compilation for FFmpeg.
> 
> ```shell
> git clone https://github.com/WasmEdge/mediapipe-rs.git 
> cd scripts
> ./download-models.sh 
> ./download-testdata.sh
> ./ffmpeg-deps-init.sh
> ./env.sh
> cd ..
> ```
> 
> Running Audio Classification.
> 
> ```rust
> cargo run --release --example audio_classification -- ./assets/models/audio_classification/yamnet_audio_classifier_with_metadata.tflite ./assets/testdata/audio/speech_16000_hz_mono.wav
> ```

Where is your ffmpeg plugin? If you are using your own one, then it doesn't need the `ffmpeg-init.sh`.

**Comment by hydai** [comment]
> Also, can you help me come up with a strategy for testing? I've written some basic tests for independent components. However, I need to write tests for components depending on various other FFmpeg structs.
> 
> I'm not sure how to create such a struct and store it's pointer. Do I create certain util classes which call the FFmpeg C++ Module functions to initialize such structs? Do you have any other approach in mind?

You should create a set of helper classes to help you do the testing.

**Comment by Hrushi20** [comment]
> Where is your ffmpeg plugin? If you are using your own one, then it doesn't need the `ffmpeg-init.sh`.

I'm using my own ffmpeg.

**Comment by hydai** [comment]
> > Where is your ffmpeg plugin? If you are using your own one, then it doesn't need the `ffmpeg-init.sh`.
> 
> I'm using my own ffmpeg.

Before using your own one, does this error happen?
Looks like it tried to use a host function which is not defined.
