### ISSUE TITLE
Cannot find simdjson header when library is found

### ISSUE THREAD

**Issue by dannypsnl** [WasmEdge/WasmEdge#2791]
## Description

In `cmake` log can check the simdjson library is found

```
-- SIMDJSON found
```

, but later `ninja` command failed with

```
WasmEdge/test/spec/spectest.cpp:20:10: fatal error: 'simdjson.h' file not found
```

### Current State

simdjson.h file not found, build failed

### Expected

If library is found, build should pass

## Environment

- Hardware Architecture: aarch64
- Operating system: MacOS 13.4.1

The following information is optional. Please provide them only if you have built from source.
- C++ Compiler version: AppleClang 14.0.3.14030022
- CMake version: 3.26.1
- CMake flags: `cmake -DCMAKE_BUILD_TYPE=Debug -DWASMEDGE_BUILD_TESTS=ON -GNinja ..`
- Path of header: `/usr/local/include/simdjson.h`

## Steps to Reproduce

```shell
mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Debug -DWASMEDGE_BUILD_TESTS=ON -GNinja ..
ninja
```

**Comment by dannypsnl** [comment]
On MacOS `/usr/local/include` is not compiler default search path[^1], for me, the short hack is adding below in `test/spec/CMakeLists.txt`
```cmake
if(CMAKE_SYSTEM_NAME MATCHES "Darwin")
  target_include_directories(wasmedgeTestSpec PRIVATE /usr/local/include)
endif()
```

But I cannot ensure where is it before I do command like `find /usr -name simdjson.h`, it maybe not at `/usr/local/include` in others MacOS

[^1]: https://stackoverflow.com/questions/50333391/cmake-on-mac-fails-to-find-usr-local-include-libevhtp

**Comment by hydai** [comment]
Hi @dannypsnl 
This is a bug introduced by this PR. https://github.com/WasmEdge/WasmEdge/pull/2659/files#diff-0359530755fb63ef1b3f214d242009dd7b81505790ba55afce13af056c6506c1L48-R61
Could you try to add the `target_include_directories` as previously did?

**Comment by dannypsnl** [comment]
simdjson has no corresponding variable, at least I cannot find one. It's document also seems like no need to do anything about this, and it's true if I use downloaded version, but cmake find package doesn't work well with simdjson.

**Comment by hydai** [comment]
Hi @dannypsnl 
Since this issue is caused by a wrong cmake file, `/usr/local/lib/cmake/simdjson/simdjson-config.cmake`, do we need to report it to the upstream?

**Comment by dannypsnl** [comment]
Yes, I think so

**Comment by dannypsnl** [comment]
Well, since it's unknowably solved, I want to stop tracking this issue due to this is not the core of the project.
