### ISSUE TITLE
Support WASI-NN ggml backend on the macOS platform

### ISSUE THREAD

**Issue by hydai** [WasmEdge/WasmEdge#2797]
## Motivation

Ref: https://github.com/second-state/WasmEdge-WASINN-examples/issues/31

In the 0.13.4 release, we provided the WASI-NN ggml plugin for Linux (x86_64 and arm64). People would like to try the feature on macOS.

## Details

Enable the workflow for building, testing, and releasing the WASI-NN ggml plugin on the macOS platform since the intel model is no longer a main product line of Mac. We should focus on arm64 architecture first.

**Comment by juntao** [comment]
The key requirement here is to enable Mac METAL support when compiling llama.cpp libraries. I believe llama.cpp has the option turned on by default when you compile it standalone on a Mac, but we might need to explicitly enable it when building the library on Mac OS.
