### ISSUE TITLE
Interrupt WASM execution

### ISSUE THREAD

**Issue by localvar** [WasmEdge/WasmEdge#280]
We would like to embed WasmEdge in our product to make it easier for users to extend it.

Users can upload their WASM code to our server and we will create WASM VMs to execute the code.

We expect the execution time of the user code to be short, however, we cannot detect and eliminate dead loops before the execution. So it would be a great help if the execution could be interrupted, and in our case, we don't need to resume the execution after the interruption.

Some WASM runtime leverage 'gas' to limit the execution time, but this doesn't fulfill our requirement as the timeout duration can not be known before the execution in some cases.

A related nice to have feature is "reset a VM": a VM is left at an unpredictable state after an interruption, which makes it unusable and we will have to create a new VM to replace it.  We assume reset a VM to its initial state cost much lesser time than creating a new VM and think it can help improve our performance.

**Comment by yanganto** [comment]
Related `Krustlet` integrating issue 
https://github.com/second-state/krustlet-wasmedge-provider/issues/2

**Comment by q82419** [comment]
@localvar  Please check if the PR #910 implemented the function you want. Thanks.

**Comment by hydai** [comment]
Hi @localvar 
WasmEdge already provided mechanisms to interrupt WASM execution. I am closing this issue. Please feel free to re-open it if the current solutions are not working on your cases.
