### ISSUE TITLE
Track WASI Preview 2 Status

### ISSUE THREAD

**Issue by dannypsnl** [WasmEdge/WasmEdge#2806]
## Motivation

This issue records WASI Preview 2 and our implementation status, serve as a superior tracker.

## Details

- [ ] [wasi-clocks](https://github.com/WebAssembly/wasi-clocks) #2766
    - depends on wasi-poll
- [ ] [wasi-poll](https://github.com/WebAssembly/wasi-poll) #2934
    - This required wasmedge to support plug-in dependence
    - @dannypsnl
- [ ] [wasi-io](https://github.com/WebAssembly/wasi-io)
    - IO stream
    - depends on wasi-poll
    - @dannypsnl
- [ ] [wasi-filesystem](https://github.com/WebAssembly/wasi-filesystem)
    - depends on wasi-poll, wasi-clocks, and wasi-io
- [ ] [wasi-sockets](https://github.com/WebAssembly/wasi-sockets)
    - depends on wasi-io
    - @LFsWang
- [x] [wasi-nn](https://github.com/WebAssembly/wasi-nn)
    - plugin: https://github.com/WasmEdge/WasmEdge/tree/master/plugins/wasi_nn
- [ ] [wasi-http](https://github.com/WebAssembly/wasi-http)
- [ ] [wasi-random](https://github.com/WebAssembly/wasi-random) #2875 

## Appendix

- https://github.com/orgs/bytecodealliance/projects/10/views/1
- https://github.com/WebAssembly/WASI/blob/main/Proposals.md
- https://github.com/bytecodealliance/wasmtime/tree/main/crates/wasi/src/preview2

**Comment by LFsWang** [comment]
I will do wasi-sockets!

**Comment by dannypsnl** [comment]
> I will do wasi-sockets!

Notice that means you also need to implement wasi-poll and wasi-io, the dependency concept between plugin system isn't defined yet.

**Comment by dannypsnl** [comment]
That's workable, in this solution I think we will leave wasi-nn and wasi-random as plugin. The others will need a reimplementation as internal component.

**Comment by hydai** [comment]
Replaced by #2939
