### ISSUE TITLE
Error while building WasiNN Plugin

### ISSUE THREAD

**Issue by Hrushi20** [WasmEdge/WasmEdge#2811]
## Description
I'm using the latest wasmedge 0.13.4 version. I'm not able to build the WasiNN Plugin. I'm trying to build the MediaPipe-rs module and I require WasiNN.

### Current State
<img width="1009" alt="Screenshot 2023-09-15 at 7 36 07 PM" src="https://github.com/WasmEdge/WasmEdge/assets/65367566/841f1c4b-701b-4e11-88f0-63401584c8a6">

## Environment

- Hardware Architecture: (Mac M1)
- Operating system: (MacOS)

The following information is optional. Please provide them only if you have built from source.
- C++ Compiler version:
- CMake version:   3.27.2
- CMake flags: `-DCMAKE_BUILD_TYPE=Release -DWASMEDGE_PLUGIN_WASI_NN_BACKEND="TensorflowLite"`

Commands executed - 
* cmake -GNinja -Bbuild -DCMAKE_BUILD_TYPE=Release -DWASMEDGE_PLUGIN_WASI_NN_BACKEND="TensorflowLite"
* cmake --build build

**Comment by juntao** [comment]
@hydai Do we have a Mac CI or docker image to support building from the source on Mac? Thanks.

**Comment by hydai** [comment]
We do have [macOS CI for the plugins](https://github.com/WasmEdge/WasmEdge/blob/master/.github/workflows/build-extensions.yml#L491-L512) except for WASI-NN plugins.

**Comment by hydai** [comment]
This should be fixed after #2808

**Comment by hydai** [comment]
This is fixed in https://github.com/WasmEdge/WasmEdge/pull/2872
Closing it.

**Comment by hydai** [comment]
Sorry, linked to the wrong PR. Reopen it

This is the correct one.
