### ISSUE TITLE
bug: AOT mode get different result from interpreter mode while executing the same testcase

### ISSUE THREAD

**Issue by luxinyi0105** [WasmEdge/WasmEdge#2884]
### Summary

While executing a wasm file with AOT mode and interpreter mode, wasmedge get different running results. 

The given [testcase](https://github.com/luxinyi0105/wasm_runtime_test/raw/main/09-27-2.zip) was simply mutated a wasm file, which was obtained by compiling C program generated with `Csmith` using `Emscripten Compiler`(Emcc). 

The original C program is `c_file.c`, the compilation results with Emscripten is `wasm_file.wasm`, and its wat format is `wat_file.wat`. 

We mutated the wat file as follows:
  - change all the `i32/i64.sub` with `i32/i64.add`.
  - change all the `i32/i64.gt_u` with `i32/i64.le_s`.
  - change `i32.ge_s` in line 2310 with `i32.gt_u`.

 The result after mutation is `mutated_file_30507.wat`, its wasm format is `mutated_file_30507.wasm`.

### Current State

```sh
 $ ~/Wasm_Runtime_Tools/WasmEdge_0.13.4-44-g27b3669b/build/tools/wasmedge/wasmedgec mutated_file_30507.wasm mutated_file_30507.aot.wasm 
[2023-09-27 18:48:01.787] [info] compile start
[2023-09-27 18:48:01.789] [info] verify start
[2023-09-27 18:48:01.791] [info] optimize start
[2023-09-27 18:48:01.918] [info] codegen start
[2023-09-27 18:48:02.040] [info] output start
[2023-09-27 18:48:02.042] [info] compile done
[2023-09-27 18:48:02.042] [info] output start
```

```sh
 $ ~/Wasm_Runtime_Tools/WasmEdge_0.13.4-44-g27b3669b/build/tools/wasmedge/wasmedge mutated_file_30507.aot.wasm
```
Output nothing

### Expected State

I use some other runtime tools, such as `wasmer` and `wasmtime`, to execute the same testcase. They output a very long garbled code and attach `undefined element: out of bounds table access` at the end of it.

Actually, when I use `interpreter mode` of wasmedge to execute the same testcase, wasmedge can get the same running result as `wasmer` and `wasmtime`. So maybe there is something wrong with wasmedge's `AOT mdoe`. The execution results of `AOT` and `interpreter mode` are shown in the following figure.

![截图 2023-09-27 18-53-59](https://github.com/WasmEdge/WasmEdge/assets/92167273/e3f8ded7-af27-4bdd-a58b-48d9f20086f8)

An interesting phenomenon is that while using `wasmedgec` to compile wasm files into corresponding aot format, if we choose another file name, such as `mutated_file.aot.wasm`, and then use command `wasmedge mutated_file.aot.wasm` to execute aot file, wasmedge can get the same result as `interpreter mode`. This situation where results are different due to different file names has also occurred in other issues, such as issue #2733 and issue #2881, but the root cause of the problem has not been found yet.

### Reproduction steps

```bash
See "Current State" and "Expected State" for detail.
```

### Components

CLI

### WasmEdge Version or Commit you used

0.13.4

### Operating system information

Ubuntu 22.04

### Hardware Architecture

x64_64

### Compiler flags and options

- C++ Compiler version: 11.4.0
- CMake version: 3.22.1
- CMake flags: default

**Comment by q82419** [comment]
Tested on master (`0.14.0-rc.5`), and this cannot be reproduced.

```bash
$ ./wasmedge mutated_file_30507.aot.wasm
# ...
# ... large amount of outputs
[2024-05-10 13:33:23.751] [error] execution failed: undefined element, Code: 0x40c
[2024-05-10 13:33:23.752] [error]     When executing function name: "_start"
```
