### ISSUE TITLE
feat: WASI-NN GGML backend release plan

### ISSUE THREAD

**Issue by hydai** [WasmEdge/WasmEdge#2886]
### Summary

Currently, the WasmEdge WASI-NN plugin has various platforms that need to be handled.

To make users convenient, we should provide at least the following platforms:

1. Linux:
    - Ubuntu 20.04 based image
        - [ ] x86_64 with AVX, AVX2, and OpenBLAS enabled (users should install `libopenblas-dev` to execute)
        - [ ] aarch64 with AVX, AVX2, and OpenBLAS enabled (users should install `libopenblas-dev` to execute)
        - [ ] x86_64 with AVX, AVX2, and cuBLAS enabled (users should install cuda-toolkit to execute)
        - [ ] aarch64 with AVX, AVX2, and cuBLAS enabled (users should install cuda-toolkit to execute)
    - CentOS 7 (manylinux2014) based image
        - [ ] x86_64 with AVX, and AVX2 enabled, without OpenBLAS
        - [ ] aarch64 with AVX, and AVX2 enabled, without OpenBLAS
2. macOS:
    - [ ] Intel model without Metal enabled
    - [ ] Apple silicon with Metal enabled

### Windows

We don't have any plan for support for the Windows platform since the maintainers don't use such platforms to develop and test the related features. If users want to try it on Windows, please use `WSL` instead.

If any contributors want to help with this. Please comment on this issue to let us know.

### macOS

The WASI-NN GGML backend relies on [llama.cpp](https://github.com/ggerganov/llama.cpp), we found several issues when enabling Metal with the Intel models. We decided to disable Metal on the Intel models to avoid these issues.

Reference: https://github.com/ggerganov/llama.cpp/issues/3092

### Linux

To accelerate the performance, we will enable AVX and AVX2 by default. If your hardware doesn't have such a feature, please try to build the WASI-NN GGML plugin yourself.

The OpenBLAS on CentOS 7 is pretty old. We encountered building issues and decided to disable OpenBLAS on such platforms. If users find it can work on such platforms without any issues, please let us know.

**Comment by juntao** [comment]
For devices with CUDA dev kit, we should enable cuBLAS as well.

**Comment by hydai** [comment]
Since we have a Jetson AGX Orin machine, we can enable cuBLAS on such platforms. I am adding this target to the list.

**Comment by hydai** [comment]
Closing this, I will have a new release plan for the GGML backend due to the complexity.
