### ISSUE TITLE
bug: MemoryInstance::getPointer function changed. The example get-string is outdated and needs to fix

### ISSUE THREAD

**Issue by sarrah-basta** [WasmEdge/WasmEdge#2887]
### Summary

I have encountered a bug in one of WasmEdge's example plugins, specifically in the "get-string" **(WasmEdge/examples/plugin/get-string/)** example. While trying to test my new plugin for WasmEdge (Wasi-OCR) (https://github.com/WasmEdge/WasmEdge/issues/2356#issuecomment-1531213003), **(which was completely developed and seamlessly working 3 months ago)** I found that the "get-string" example, provided by WasmEdge, is not working as expected. The problem seems to be related to the MemInst->getPointer function, which is causing a compilation error. This specific example was referred by me earlier as well and was working then, and it is the only reference I have found so far that illustrates memory transfer of strings via the WasmEdge C++ Plugin API.

### Current State

I have encountered a bug in one of WasmEdge's example plugins, specifically in the "get-string" example. The issue appears to be related to changes in memory access functions, leading to the following compilation error:

```
/home/sarrah/1_data/wasmedge_intern/WasmEdge/examples/plugin/get-string/getstring.cpp: In member function 'WasmEdge::Expect<void> {anonymous}::GetString::body(const WasmEdge::Runtime::CallingFrame&, uint32_t, uint32_t, uint32_t)':
/home/sarrah/1_data/wasmedge_intern/WasmEdge/examples/plugin/get-string/getstring.cpp:39:50: error: no matching function for call to 'WasmEdge::Runtime::Instance::MemoryInstance::getPointer<char*>(uint32_t&, uint32_t&)'
   39 |     char *const Buf = MemInst->getPointer<char *>(BufPtr, BufLen);
      |                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
```

### Expected State

The expected behavior is that the "get-string" example provided by WasmEdge should build successfully without any compilation errors, as it did previously.

Additional Information :

- I have developed a new plugin (Wasi-OCR) for WasmEdge, which also relies on memory access functions. I suspect that the issue may be related to recent changes in these memory access functions.
- Link to the Wasi-OCR plugin details: [Wasi-OCR Plugin](https://github.com/WasmEdge/WasmEdge/issues/2356#issuecomment-1531213003)
- Additionally, I've created a Rust library crate that utilizes the Wasi-OCR plugin for image processing. Here's the link to the Rust library: [Wasi-OCR Rust Library](https://github.com/sarrah-basta/wasmedge_ai_testing/tree/main/wasi-ocr)

I kindly request assistance in resolving this issue or guidance on how to adapt the "get-string" example and consequentially my developed plugin to work seamlessly with the latest changes in memory access functions in WasmEdge.

### Reproduction steps

```bash
1. Build WasmEdge with options '-DWASMEDGE_BUILD_EXAMPLE=ON'

cd WasmEdge
mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Release -DWASMEDGE_BUILD_EXAMPLE=ON ..
```
2. Execute the build command:
`make`
```


### Screenshots

_No response_

### Any logs you want to share for showing the specific issue

```bash
[ 98%] Building CXX object examples/plugin/get-string/CMakeFiles/GetString.dir/getstring.cpp.o
/home/sarrah/1_data/wasmedge_intern/WasmEdge/examples/plugin/get-string/getstring.cpp: In member function ‘WasmEdge::Expect<void> {anonymous}::GetString::body(const WasmEdge::Runtime::CallingFrame&, uint32_t, uint32_t, uint32_t)’:
/home/sarrah/1_data/wasmedge_intern/WasmEdge/examples/plugin/get-string/getstring.cpp:39:50: error: no matching function for call to ‘WasmEdge::Runtime::Instance::MemoryInstance::getPointer<char*>(uint32_t&, uint32_t&)’
   39 |     char *const Buf = MemInst->getPointer<char *>(BufPtr, BufLen);
      |                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
In file included from /home/sarrah/1_data/wasmedge_intern/WasmEdge/include/runtime/instance/module.h:23,
                 from /home/sarrah/1_data/wasmedge_intern/WasmEdge/include/plugin/plugin.h:21,
                 from /home/sarrah/1_data/wasmedge_intern/WasmEdge/examples/plugin/get-string/getstring.cpp:4:
/home/sarrah/1_data/wasmedge_intern/WasmEdge/include/runtime/instance/memory.h:227:3: note: candidate: ‘std::enable_if_t<is_pointer_v<T>, T> WasmEdge::Runtime::Instance::MemoryInstance::getPointer(uint32_t) const [with T = char*; std::enable_if_t<is_pointer_v<T>, T> = char*; uint32_t = unsigned int]’
  227 |   getPointer(uint32_t Offset) const noexcept {
      |   ^~~~~~~~~~
/home/sarrah/1_data/wasmedge_intern/WasmEdge/include/runtime/instance/memory.h:227:3: note:   candidate expects 1 argument, 2 provided
make[2]: *** [examples/plugin/get-string/CMakeFiles/GetString.dir/build.make:76: examples/plugin/get-string/CMakeFiles/GetString.dir/getstring.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1088: examples/plugin/get-string/CMakeFiles/GetString.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```

### Components

C SDK, Rust SDK

### WasmEdge Version or Commit you used

01829c

### Operating system information

Ubuntu 22.04

### Hardware Architecture

x86_64

### Compiler flags and options

- C++ Compiler Version : 
GNU Make 4.3
Built for x86_64-pc-linux-gnu
- CMake Version :
cmake version 3.22.1
- Compiler Flags :
-DCMAKE_BUILD_TYPE=Release -DWASMEDGE_BUILD_EXAMPLE=ON

**Comment by hydai** [comment]
Hi @sarrah-basta 
I believe the example needs to be updated.

The API is changed to ensure memory safety.
https://github.com/WasmEdge/WasmEdge/blob/master/include/runtime/instance/memory.h#L224-L234

All the plugins bundled in the WasmEdge repo are modified to the new APIs.
https://github.com/WasmEdge/WasmEdge/blob/4808085b5397126fa75bb43aa4acbf97ce27d09c/plugins/wasi_nn/wasinnfunc.cpp#L45

**Comment by hydai** [comment]
Hi @sarrah-basta 
I updated the example so you can follow the same way to update your own plugin. Thanks for this issue :-).

**Comment by sarrah-basta** [comment]
Hello @hydai , thank you so much for the help!
