### ISSUE TITLE
Allocation error?

### ISSUE THREAD

**Issue by orangeC23** [WasmEdge/WasmEdge#2949]
### Summary

Using clang to compile the following C file into Wasm binaries, and execute the Wasm binaries.
However, WasmEdge prints different result.

### Current State

WasmEdge prints:
```
File 'Data/hello.txt' created and allocated with 0 bytes of space.
Enter snapshot
File Size: 30 bytes 
File Permissions: 0 
File Owner UID: 0 
File Group GID: 0 
Current offset: 0 
Leave snapshot

```

### Expected State

wasmtime and WAMR print the same :
```
Error allocating file space: Success
Enter snapshot
Error getting file attributes: Bad file descriptor
```

And using command `clang -o allocate1 allocate1.c` to compile the C file to native code, and execute it using `./allocate1`, it also prints:
```
Error allocating file space: Success
Enter snapshot
Error getting file attributes: Bad file descriptor
```

### Reproduction steps

```bash
The c file is :

#include <stdio.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/stat.h>

int get_fd(const char* file_name, int open_style){
    // Open a file for reading
    int fd = open(file_name, open_style);
    if (fd == -1) {
        perror("Failed to open the file");
        return 1;
    }

    return fd;
}

int fd_allocate (int fd, const char* filename, off_t start_value, off_t len_value){
    if (posix_fallocate(fd, start_value, len_value) != 0) {
        perror("Error allocating file space");
        close(fd);
        return 1;
    }

    printf("File '%s' created and allocated with %lld bytes of space.\n", filename, (long long)len_value);
    return fd;
}

int fd_allocatePbjTO8Xu2z (int fd, const char* file_name){
    off_t start_value = 85;
    off_t len_value = 0;
    return fd_allocate(fd, file_name, start_value, len_value);
}

int snapshot(int myfd){   
    printf("Enter snapshot\n");
    
    struct stat file_info;
    if (fstat(myfd, &file_info) == -1) {
        perror("Error getting file attributes");
        close(myfd);
        return 1;
    }

    printf("File Size: %lld bytes \n", (long long)file_info.st_size);
    printf("File Permissions: %o \n", file_info.st_mode & ~S_IFMT); 
    printf("File Owner UID: %d \n", file_info.st_uid);
    printf("File Group GID: %d \n", file_info.st_gid);
    

    off_t cur_offset = lseek(myfd, 0, SEEK_CUR);
    if (cur_offset == -1) {
        perror("Error getting current offset");
    }
    printf("Current offset: %lld \n", (long long)cur_offset);

    if (close(myfd) == -1) {
        perror("Error closing file");
        return 1;
    }

    printf("Leave snapshot\n");
}


int main() {
    const char* file_name = "Data/hello.txt";
    int open_style= O_CREAT | O_RDWR;
    int fd = get_fd(file_name, open_style);
    fd_allocatePbjTO8Xu2z(fd, file_name);
    snapshot(fd);
    return 0;
}
```

(1)compile it into wasm `./wasi-sdk-16.0/bin/clang --target=wasm32-unkown-wasi --sysroot=./wasi-sdk-16.0/share/wasi-sysroot  allocate1.c -o allocate1.wasm`
(2)exeute open.wasm
`./wasmtime run --dir=./Data allocate1.wasm`
`./wasm-micro-runtime-WAMR-05-18-2022/product-mini/platforms/linux/build/iwasm --dir=./Data allocate1.wasm`
`./wasmedge0.9/bin/wasmedge --dir=./Data allocate1.wasm`
The permission of Data/hello.txt is 0700 or 0600, user1 create the Data/hello.txt file and user1 execute the Wasm file.
```


### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Components

CLI

### WasmEdge Version or Commit you used

0.9.1

### Operating system information

Ubuntu 20.04

### Hardware Architecture

x86_64

### Compiler flags and options

Not building from source.
Using `curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- -p /home/user1/wasmedge0.9 -v 0.9.1 --ignore-brew` to install WasmEdge.

**Comment by hydai** [comment]
Hi, the 0.9.1 is pretty old, and many of the WASI-FS components have already been modified. Please use 0.13.4, 0.12.1, or 0.11.2 for testing.

I use `WASI-SDK 0.20.0` with the following versions: `0.11.2`, `0.12.1`, and `0.13.4`. It looks like this issue no longer exists.

<img width="960" alt="CleanShot 2023-10-10 at 22 00 39@2x" src="https://github.com/WasmEdge/WasmEdge/assets/2776756/79a22747-be7f-4286-87fe-faf57a2f8b14">

**Comment by orangeC23** [comment]
Yes. Thanks for your answer !
