### ISSUE TITLE
agx orin, free(): invalid pointer Aborted (core dumped)

### ISSUE THREAD

**Issue by thunder95** [WasmEdge/WasmEdge#2951]
### Summary

I followd this tutorial below and use AGX Orin device:

https://blog.stackademic.com/fast-and-portable-llama2-inference-on-the-heterogeneous-edge-a62508e82359

When I run 
`wasmedge --dir .:. --nn-preload default:GGML:CPU:llama-2-7b-chat.Q5_K_M.gguf wasmedge-ggml-llama-interactive.wasm default
`

it throws "free(): invalid pointer Aborted (core dumped)"

**Comment by juntao** [comment]
Can you confirm that you have the correct GGUF and Wasm files in your local directory? And where is your WasmEdge installed?

```
which wasmedge 

wasmedge --version
```

Thanks.

**Comment by thunder95** [comment]
@juntao thanks for your quick reply.

/home/ytx/.wasmedge/bin/wasmedge
wasmedge version 0.13.4

**Comment by thunder95** [comment]
followd this tutorial step by step, and in my local directory: llama-2-7b-chat.Q5_K_M.gguf   wasmedge-ggml-llama-interactive.wasm

**Comment by hydai** [comment]
Please also provide the operating system info.

**Comment by thunder95** [comment]
@hydai AGX ORIN 64G Linux ytx-desktop 5.10.104-tegra #1 SMP PREEMPT Tue Jan 24 15:09:44 PST 2023 aarch64 aarch64 aarch64 GNU/Linux

**Comment by hydai** [comment]
Hi @thunder95,
Thanks for reporting this issue.
After verifying on the AGX Orin, I found the current release assets for the manylinux2014 aarch64 platform are incompatible with the Ubuntu20.04 aarch64. I am working on creating a set of new release assets on such a platform. Once this is resolved, I will update you on this issue.

**Comment by hydai** [comment]
The release assets should be updated manually, and the installer should also be updated. Re-open this until the previous two items are finished.

**Comment by hydai** [comment]
Hi @thunder95 
This issue is fixed. Please try again on the Jetson Orin. Thanks!
If you encounter any new issues, please feel free to re-open this.
