### ISSUE TITLE
Add the software bill of materials

### ISSUE THREAD

**Issue by alabulei1** [WasmEdge/WasmEdge#2975]
Check out docs: https://clomonitor.io/docs/topics/checks/#software-bill-of-materials-sbom

**Comment by jaydee029** [comment]
Hi, I would like to work on this.

**Comment by jaydee029** [comment]
Looking at other CNCF projects , maybe we can move forward with SPDX format , I found this [https://github.com/kubernetes-sigs/bom](url) to satisfy our requirements, some projects add the sbom along with every release. @hydai @dannypsnl

**Comment by dannypsnl** [comment]
Sounds good!

**Comment by jaydee029** [comment]
So ,how do we go about this? Does the maintainer generate a file and make it a part of the release ? or do we work on this and add it to the repository in a specific place?. i'm a bit unaware of how the release process works. @dannypsnl

**Comment by alabulei1** [comment]
Do you mean this changelog file? https://github.com/WasmEdge/WasmEdge/blob/master/Changelog.md

**Comment by jaydee029** [comment]
So, not exactly I think i'll have to edit the .github/workflows/release.yml and add a job to generate sbom

**Comment by hydai** [comment]
Fixed by #3090
