### ISSUE TITLE
Add token permissions

### ISSUE THREAD

**Issue by alabulei1** [WasmEdge/WasmEdge#2979]
Check out docs: https://clomonitor.io/docs/topics/checks/#token-permissions-from-openssf-scorecard

**Comment by MeenuyD** [comment]
Hello @alabulei1 I would like to work on this issue can you please assign it to me and tell me which file it should add

**Comment by alabulei1** [comment]
Hi @MeenuyD 

If you're looking for easy issues, please check out #2970 and #2971.

**Comment by MeenuyD** [comment]
Hello @alabulei1 I have created the pr for both can you please review that

**Comment by jaydee029** [comment]
Hey @alabulei1 I would like to work on this , would be following up with a pull request.

**Comment by jaydee029** [comment]
13 workflow permissions were added , I'll raise another PR for remaining workflows.

**Comment by hydai** [comment]
This should be fixed in #3203.
