### ISSUE TITLE
 Different output when running the same wasm file

### ISSUE THREAD

**Issue by XinyuShe** [WasmEdge/WasmEdge#3016]
### Summary

I constructed a wasm binary with an exported function called "main". I used the following command and compared the outputs of WASMEDGE with other runtimes.
There are two issues: the first is the problem with the first output being -nan, and the second is that the seventh output is different.

### Current State

[filea6.zip](https://github.com/WasmEdge/WasmEdge/files/13259784/filea6.zip)

```bash
-----------------wasmtime-----------------
warning: using `--invoke` with a function that returns values is experimental and may break in the future
NaN
4342532170260590600
0
0
0
0
-1588437232890788350
0

-----------------wasmer-----------------
NaN 4342532170260590600 0 0 0 0 -1588437232890788350 0

-----------------wasmedge-----------------
[2023-11-05 05:27:56.908] [info] compile start
[2023-11-05 05:27:56.908] [info] verify start
[2023-11-05 05:27:56.909] [info] optimize start
[2023-11-05 05:27:56.914] [info] codegen start
[2023-11-05 05:27:56.923] [info] output start
[2023-11-05 05:27:57.044] [info] compile done
-nan
4.34253e+18
0
0
0
0
16858306840818763266
0
```

### Expected State

I expect wasmedge has the same output as other runtimes

### Reproduction steps

```bash
wasmedge compile filea6.wasm -o filea6.wasm.so
wasmedge --reactor filea6.wasm.so main
```

### Components

CLI

### WasmEdge Version or Commit you used

wasmedge version 0.13.4

### Operating system information

Docker version 24.0.5, build ced0996

### Hardware Architecture

Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-79-generic x86_64)

**Comment by dannypsnl** [comment]
Please fill expected state properly.

**Comment by dannypsnl** [comment]
This is not bug but known issue, wasmedge output uint64, others use int64.

**Comment by XinyuShe** [comment]
I'm not sure if you've noticed the issue with '-nan'. Why does NaN have a positive or negative sign?

**Comment by ibmibmibm** [comment]
Because rust print out positive and negative NaNs without sign, but c++ dose.

**Comment by XinyuShe** [comment]
Thanks for your clarification!
