### ISSUE TITLE
bug: compiled wasm might fall into infinite loop

### ISSUE THREAD

**Issue by XinyuShe** [WasmEdge/WasmEdge#3019]
### Summary

- [filea58.zip](https://github.com/WasmEdge/WasmEdge/files/13275366/filea58.zip)

### Current State

![image](https://github.com/WasmEdge/WasmEdge/assets/60457190/de91121d-9b57-4636-ba43-928dd91282fd)

It can be observed that WasmEdge does not report errors, it may fall into an infinite loop.

```bash
root@4252f5ec38df:/home/a# time wasmedge compile filea58.wasm filea58.so
[2023-11-06 10:37:30.653] [info] compile start
[2023-11-06 10:37:30.657] [info] verify start
[2023-11-06 10:37:30.659] [info] optimize start
[2023-11-06 10:37:30.758] [info] codegen start
[2023-11-06 10:37:30.859] [info] output start
[2023-11-06 10:37:30.864] [info] compile done

real    0m0.228s
user    0m0.209s
sys     0m0.039s
root@4252f5ec38df:/home/a# time wasmedge --reactor filea58.so main^Z
[24]+  Stopped                 wasmedge --reactor filea58.so main

real    0m38.649s
user    0m0.000s
```

### Expected State

Report "out of memory access"

### Reproduction steps

```bash
wasmedge filea21.wasm
wasmedge compile filea21.wasm filea21_aot.wasm
wasmedge filea21_aot.wasm main
```
#### wasmtime

```bash
wasmtime compile  -o filea21.cwasm filea21.wasm
wasmtime --allow-precompiled --invoke main  filea21.cwasm
```
#### wasmer

```bash
wasmer compile  -o filea21.wasmer filea21.wasm
wasmer run -i main filea21.wasmer
```

#### wamr

```bash
wamrc --bounds-checks=1 -o filea21.wasm.aot filea21.wasm
iwasm --heap-size=0 -f main filea21.wasm.aot
```

### Components

CLI

### WasmEdge Version or Commit you used

- wasmedge version 0.13.4
- wasmtime-cli 14.0.1
- wasmer 3.3.0
- wamrc 1.2.3
- iwasm 1.2.3

### Operating system information

Docker version 24.0.5, build ced0996

### Hardware Architecture

Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-79-generic x86_64)

**Comment by q82419** [comment]
Fixed in the current master (`0.14.0-rc.5`).
