### ISSUE TITLE
bug: free(): invalid pointer on Raspberry Pi

### ISSUE THREAD

**Issue by Tenderyi** [WasmEdge/WasmEdge#3022]
### Summary

I followd this tutorial below
https://blog.stackademic.com/fast-and-portable-llama2-inference-on-the-heterogeneous-edge-a62508e82359

When I run
`wasmedge --dir .:. --nn-preload default:GGML:CPU:llama-2-7b-chat.Q5_K_M.gguf wasmedge-ggml-llama-interactive.wasm default `

it throws "free(): invalid pointer"

the device i uesd is Raspberry Pi 3 Model B+，the wasmedge version is 0.13.5, and  the OS is as follows:

wry@raspberrypi:~/Project $ uname -a
Linux raspberrypi 5.4.72-v8+ #1356 SMP PREEMPT Thu Oct 22 13:58:52 BST 2020 aarch64 GNU/Linux

### Hardware Architecture

aarch64

**Comment by hydai** [comment]
Please use the bug report format to submit your issue.
