### ISSUE TITLE
bug: free(): invalid pointer on Raspberry Pi

### ISSUE THREAD

**Issue by Tenderyi** [WasmEdge/WasmEdge#3023]
### Summary

I followd this tutorial below
https://blog.stackademic.com/fast-and-portable-llama2-inference-on-the-heterogeneous-edge-a62508e82359

but it throws "free(): invalid pointer"

### Current State

it throws "free(): invalid pointer" and aborts immediately

### Expected State

it shows the word "Question:" on the screen

### Reproduction steps

```bash
1. download files below
wasmedge-ggml-llama-interactive.wasm
llama-2-7b-chat.Q5_K_M.gguf
2. 'wasmedge --dir .:. --nn-preload default:GGML:CPU:llama-2-7b-chat.Q5_K_M.gguf wasmedge-ggml-llama-interactive.wasm default '
3. wasmedge throws "free(): invalid pointer"
```

### Components

CLI

### WasmEdge Version or Commit you used

0.13.5

### Operating system information

Linux raspberrypi 5.4.72-v8

### Hardware Architecture

aarch64

**Comment by hydai** [comment]
It looks like the arm64 manylinux2014 assets is only working on CentOS7.
Could you please try:

`curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- --plugin wasi_nn-ggml --dist ubuntu20.04`

And execute the same command again?

**Comment by juntao** [comment]
@Tenderyi did it work? Thanks.

**Comment by Tenderyi** [comment]
yes, it works! Thanks.

**Comment by dannypsnl** [comment]
Close as resolved, feel free to reopen if need further discussion.

**Comment by Tenderyi** [comment]
Now I have a situation that I have to run it on ubuntu18.04 cause my device _Atlas 200 DK_ only support that kind of OS. In that case, I have the same issue happened on Raspberry Pi because they have the same hardware architecture —— aarch64.
How can I solve this issue ?

**Comment by hydai** [comment]
Please build from source instead.
However, since Ubuntu 18.04 is quite old, you may need to update your toolchains first, including CMake, G++, and several other libraries.
Just so you know, we do the following stuff to make WasmEdge+GGML run on CentOS 7.
https://github.com/WasmEdge/WasmEdge/blob/master/utils/docker/Dockerfile.manylinux2014_aarch64

```bash
# In WasmEdge folder
git config --global --add safe.directory $(pwd) # (Optional) You may need this for ensuring the git can retrieve the correct version information.
# You can set `WASMEDGE_BUILD_AOT_RUNTIME` to OFF to skip the LLVM dependencies
# Also, if you don't want to install libopenblas-dev, setting `WASMEDGE_PLUGIN_WASI_NN_GGML_LLAMA_BLAS` to OFF
cmake -Bbuild -GNinja -DCMAKE_BUILD_TYPE=Release -DWASMEDGE_BUILD_AOT_RUNTIME=OFF -DWASMEDGE_BUILD_TOOLS=ON -DWASMEDGE_PLUGIN_WASI_NN_BACKEND=GGML -DWASMEDGE_PLUGIN_WASI_NN_GGML_LLAMA_BLAS=OFF
cmake --build build

# The ggml plugin will be `build/plugins/wasi_nn/libwasmedgePluginWasiNN.so
# Tool will be `build/tools/wasmedge
# And libwasmedge.so will be `build/lib/api/libwasmedge.so`
```

**Comment by Tenderyi** [comment]
Thank you, it works!
