### ISSUE TITLE
bug: Different output when running the same wasm file

### ISSUE THREAD

**Issue by XinyuShe** [WasmEdge/WasmEdge#3027]
### Summary

I  randomly constructed a WASM file [filea232.zip](https://github.com/WasmEdge/WasmEdge/files/13305542/filea232.zip), and some of  the output results are 
 floating-point numbers. However, the output from wasmedge differs from that of the other three runtimes.

### Current State

Even if 78488.55 is rounded to one decimal place, the result should be 78488.6, but it is 78488.5 in wasmedge's output.

![image](https://github.com/WasmEdge/WasmEdge/assets/60457190/3e727c87-5bab-420a-86cb-b828df2b3919)
```bash
root@4252f5ec38df:/home/a# wasmedge --reactor  filea232.wasm main
0
4808067800659923616
0
78488.5
0
0
0
4808067800659923616
root@4252f5ec38df:/home/a# wasmtime --invoke main  filea232.wasm
warning: using `--invoke` with a function that returns values is experimental and may break in the future
0
4808067800659923616
0
78488.55
0
0
0
4808067800659923616
root@4252f5ec38df:/home/a# wasmer run filea232.wasm -i main --cranelift
0 4808067800659923616 0 78488.55 0 0 0 4808067800659923616
root@4252f5ec38df:/home/a# iwasm --heap-size=0 -f main --llvm-jit filea232.wasm
0x0:i32,0x42b9b030c25412a0:i64,0x0:i32,78488.55:f32,0x0:i32,0x0:i32,0x0:i32,0x42b9b030c25412a0:i64
```

### Expected State

The output of WASMEDGE should be same to those of  other runtimes

### Reproduction steps

```bash
root@4252f5ec38df:/home/a# wasmtime --version
wasmtime-cli 14.0.1
root@4252f5ec38df:/home/a# wasmer --version
wasmer 3.3.0
root@4252f5ec38df:/home/a# wamrc --version
wamrc 1.2.3
root@4252f5ec38df:/home/a# iwasm --version
iwasm 1.2.3
root@4252f5ec38df:/home/a# wasmedge --version
wasmedge version 0.13.4
```
#### wasmedge
```bash
wasmedge --reactor  filea232.wasm main
```
#### wasmtime
```bash
wasmtime --invoke main  filea232.wasm
```
#### wasmer
```bash
wasmer run filea232.wasm -i main --cranelift
```

#### wamr
```bash
iwasm --heap-size=0 -f main --llvm-jit filea232.wasm
```

### Components

CLI

### WasmEdge Version or Commit you used

wasmedge version 0.13.4

### Operating system information

Docker version 24.0.5, build ced0996

### Hardware Architecture

Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-79-generic x86_64)

**Comment by hydai** [comment]
Hi @XinyuShe 
After I execute the wasm, the result is `78488.546875`, which means if this value is rounded into only one decimal, it will be `78488.5`. And the result is expected.

`78488.55` is rounded to two decimals, versus `78488.5` is rounded to one decimal. I can't see any issue with it.

**Comment by dannypsnl** [comment]
Close as invalid.
