### ISSUE TITLE
question: https://wasmedge.org/docs/develop/deploy/podman/#prerequisites missing crun instructions

### ISSUE THREAD

**Issue by nareddyt** [WasmEdge/WasmEdge#3028]
### Summary

Step 3 of https://wasmedge.org/docs/develop/deploy/podman/#prerequisites: It seems like some instructions are missing.

> Build and configure crun with WasmEdge support

> Next, configure and build a crun binary with WasmEdge support.

Maybe there should be a git clone, similar to https://wasmedge.org/docs/develop/deploy/oci-runtime/crun/#prerequisites?

**Comment by hydai** [comment]
Hi @nareddyt 
Thanks for reporting this.

Yup, it looks like the `git clone` part is missed. @alabulei1 Should we move this issue to https://github.com/WasmEdge/docs ?

**Comment by hydai** [comment]
The issue is moved to docs. Closing.
