### ISSUE TITLE
Plugin not compatible: manylinux2014x86_64wasi_nn-ggml-cuda on amazon linux 2

### ISSUE THREAD

**Issue by richzw** [WasmEdge/WasmEdge#3029]
### Summary

We tried to install WasmEdge in amazon linux 2 through command `curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- --plugin wasi_nn-ggml`, however  we met this error `Plugin not compatible: manylinux2014x86_64wasi_nn-ggml-cuda`

```
$ curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- --plugin wasi_nn-ggml
Using Python: /home/ec2-user/miniconda3/bin/python3
ERROR   - Exception on process - rc= 1 output= b'' command= ['cat /etc/lsb-release 2>/dev/null | grep RELEASE']
ERROR   - Exception on process - rc= 1 output= b'' command= ['cat /etc/lsb_release 2>/dev/null | grep DESCRIPTION']
WARNING - Experimental Option Selected: plugins
WARNING - plugins option may change later
INFO    - Compatible with current configuration
INFO    - Running Uninstaller
WARNING - SHELL variable not found. Using bash as SHELL
INFO    - shell configuration updated
INFO    - Downloading WasmEdge
|============================================================|100.00 %INFO    - Downloaded
INFO    - Installing WasmEdge
INFO    - WasmEdge Successfully installed
ERROR   - Plugin not compatible: manylinux2014x86_64wasi_nn-ggml-cuda
INFO    - Run:
source /home/ec2-user/.bashrc
```

```
$ uname -a
Linux ip-10-0-3-204.ec2.internal 5.10.186-179.751.amzn2.x86_64 #1 SMP Tue Aug 1 20:51:38 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

$ wasmedge --version
wasmedge version 0.13.5
```

**Comment by hydai** [comment]
Hi @richzw 
May I ask for the instance type and the AMI information you used?

**Comment by richzw** [comment]
@hydai , the instance type is `g4dn.4xlarge` and AMI name is  `Deep Learning AMI GPU PyTorch 1.13.1 (Amazon Linux 2) 20230818` ref https://docs.aws.amazon.com/dlami/latest/devguide/appendix-ami-release-notes.html

**Comment by richzw** [comment]
@hydai, Does the `WASI_NN_PYTORCH` should be used in this AMI?

**Comment by hydai** [comment]
We never verify it on Amazon Linux. However, instead of using the installer, you could download the release assets directly to test: https://github.com/WasmEdge/WasmEdge/releases/tag/0.13.5

It seems like the installer cannot work correctly on Amazon Linux

**Comment by juntao** [comment]
@richzw You could try to run the installer without the plugin option -- that is to install WasmEdge only. 

```
curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash
```

Then you can download the GGML plugin files for Nvidia CUDA from the release assets and put them into `~/.wasmedge/plugin` folder.

**Comment by richzw** [comment]
> @richzw You could try to run the installer without the plugin option -- that is to install WasmEdge only.
> 
> ```
> curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash
> ```
> 
> Then you can download the GGML plugin files for Nvidia CUDA from the release assets and put them into `~/.wasmedge/plugin` folder.

@juntao, Thank you very much for your reply. 

The GGML plugin you mentioned is WasmEdge-plugin-wasi_nn-ggml-cuda-0.13.5-ubuntu20.04_x86_64.tar.gz
 under this page https://github.com/WasmEdge/WasmEdge/releases. Please correct me if I am wrong.

I noticed this plugin `wasi_nn-ggml` was verified under AWS EC2 g5.xlarge + Nvidia A10G 24G GPU + Amazon deep learning base Ubuntu 20.04 per this link https://github.com/second-state/WasmEdge-WASINN-examples/blob/master/wasmedge-ggml-llama-interactive/README.md. I could try it in this platform.

**Comment by richzw** [comment]
@juntao @hydai I just tested it under AWS EC@ g5.xlarge + Nvidia A10G 24G GPU + Deep Learning AMI GPU PyTorch 2.1.0 (Ubuntu 20.04) 20231103, the installation command could run successfully.

```
$ curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- --plugin wasi_nn-ggml
Using Python: /opt/conda/bin/python3
WARNING - Experimental Option Selected: plugins
WARNING - plugins option may change later
INFO    - Compatible with current configuration
INFO    - Running Uninstaller
WARNING - Uninstaller did not find previous installation
WARNING - SHELL variable not found. Using bash as SHELL
INFO    - shell configuration updated
INFO    - Downloading WasmEdge
|============================================================|100.00 %INFO    - Downloaded
INFO    - Installing WasmEdge
INFO    - WasmEdge Successfully installed
INFO    - Downloading Plugin: wasi_nn-ggml-cuda
|============================================================|100.00 %INFO    - Downloaded
INFO    - Run:
source /home/ubuntu/.bashrc
```

However, when I try to run the command `wasmedge --dir .:. --nn-preload default:GGML:AUTO:llama-2-7b-chat-wasm-q5_k_m.gguf  llama-chat.wasm`, the error `[error] [WASI-NN] GGML backend: Error: unable to init model` come up.

```
$ wasmedge --dir .:. --nn-preload default:GGML:AUTO:llama-2-7b-chat-wasm-q5_k_m.gguf  llama-chat.wasm
[INFO] Model alias: default
[INFO] Prompt context size: 4096
[INFO] Number of tokens to predict: 1024
[INFO] Number of layers to run on the GPU: 100
[INFO] Batch size for prompt processing: 4096
[INFO] Use default system prompt
[INFO] Prompt template: Llama2Chat
[INFO] Stream stdout: false
[INFO] Log prompts: false
[INFO] Log statistics: false
[INFO] Log all information: false
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA A10G, compute capability 8.6
[2023-11-13 09:06:20.382] [error] [WASI-NN] GGML backend: Error: unable to init model.
Error: "Fail to load model into wasi-nn: Backend Error: WASI-NN Backend Error: Caller module passed an invalid argument"
```

Is there any way to debug this issue? to find out which parameter is wrong per this codes

```cpp
  {
    llama_model_params ModelParams = llama_model_default_params();
    // If the `n_gpu_layers` in `setInput` is different from the
    // `n_gpu_layers` in `llama_model_params`, we will reload
    // the model with the new configuration.
    if (ModelParams.n_gpu_layers != static_cast<int32_t>(CxtRef.NGPULayers)) {
      ModelParams.n_gpu_layers = CxtRef.NGPULayers;
      GraphRef.LlamaModel = llama_load_model_from_file(
          GraphRef.ModelFilePath.c_str(), ModelParams);
      if (GraphRef.LlamaModel == nullptr) {
        spdlog::error("[WASI-NN] GGML backend: Error: unable to init model."sv);
        Env.NNGraph.pop_back();
        return ErrNo::InvalidArgument;
      }
    }
  }
```

By the way, maybe the `ModelParams` could be output in this error log. It could help to debug this error.

**Comment by hydai** [comment]
Hi @richzw 

Could you please share the file size and sha256 checksum of `llama-2-7b-chat-wasm-q5_k_m.gguf`?

Also, re-run the command with `--log-all`; it should provide some information.

cc @apepkuss I would like to know if this option `--log-all` will set the `enable-log` field in the `setInput` function.

**Comment by richzw** [comment]
@hydai , @apepkuss Thank you very much for your response.

The size of `llama-2-7b-chat-wasm-q5_k_m.gguf` is `45343` and the sha256sum of this file is `b8757f4112989b0783055abf93e17a7e78e8f708e44853f7fe6535c3107161f5`

```
> sha256sum llama-2-7b-chat-q5_k_m.gguf
b8757f4112989b0783055abf93e17a7e78e8f708e44853f7fe6535c3107161f5  llama-2-7b-chat-q5_k_m.gguf

-rw-rw-r-- 1 ubuntu ubuntu   45343 Nov 13 09:05 llama-2-7b-chat-q5_k_m.gguf
```

**Comment by hydai** [comment]
Hi @richzw 
It seems like your model is broken.

Here is my result:

```
total 4671056
-rw-r--r--. 1 hydai rd 4783156928 Nov 14 12:09 llama-2-7b-chat.Q5_K_M.gguf
e0b99920cf47b94c78d2fb06a1eceb9ed795176dfa3f7feac64629f1b52b997f  ./llama-2-7b-chat.Q5_K_M.gguf
```

**Comment by apepkuss** [comment]
@richzw For your convenience, you can use the following command to download the model file: 

```console
curl -LO https://huggingface.co/second-state/Llama-2-7B-Chat-GGUF/resolve/main/llama-2-7b-chat.Q5_K_M.gguf
```

**Comment by richzw** [comment]
@hydai @apepkuss Thank you very much for your help. It works well now.

**Comment by apepkuss** [comment]
@richzw Please close the issue if no more questions. Thanks a lot!

**Comment by richzw** [comment]
@hydai @apepkuss Currently, it seems the plugin is not compatible with Amazon Linux 2, is there any plan to do that? If so, May I could do some work?

**Comment by hydai** [comment]
Created #3034 for this.
