### ISSUE TITLE
feat: Retrieving the number of tokens from the `wasi-nn-ggml` plugin

### ISSUE THREAD

**Issue by apepkuss** [WasmEdge/WasmEdge#3033]
### Summary

In the scenario of multi-turn conversations, the number of tokens of the user query and the assistant answer, respectively, in each turn are required for dynamically updating the chat history to fit the context window size.

### Details

In the scenario of multi-turn conversations, chat history grows by appending new questions by `User` and answers from `Model`. The size of chat history, in `token`, will touch the upper bound (set by the `ctx_size` field in metadata). When this happens, chat history will pop out one or more [messages](https://github.com/second-state/llama-utils/blob/main/api-server/endpoints/src/chat.rs#L124). The strategy of how many messages should be removed from chat history depends on two factors: *context size* and *number of tokens of each message*. *context size* is set by the users case-by-case, while *number of tokens of each message* has to be computed at run time. The following three kinds of `number of tokens` are required:

- Number of tokens of each prompt, namely user query, including the pattern symbols if possible, such as `<s>` in Llama-2 models;
- Number of tokens of each completion, namely assistant response;
- Number of total tokens of the current chat history, including the pattern symbols if possible.

In addition, the three kinds of data are also part of the OpenAI-compatible chat response. The data are also required by different AI service frontends, such as ChatBot UI, to dynamically adjust chat history.

So far, the `wasi-nn_ggml` plugin does not provide support to allow developers to get the *number of tokens of each message* back. 

`llama.cpp` should provide support for "computing" or "storing" the statistics mentioned above.

**Comment by hydai** [comment]
This is fixed in #3048
