### ISSUE TITLE
`sock_shutdown` a closed fd segfaults

### ISSUE THREAD

**Issue by yagehu** [WasmEdge/WasmEdge#3041]
### Summary

`fd_close` any file descriptor then attempting to call `sock_shutdown` on it causes wasmedge CLI to segfault.

### Reproduction steps

```wat
(module
  (type (func))
  (type (func (param i32 i32 i32) (result i32)))
  (type (func (param i32)))
  (type (func (param i32) (result i32)))
  (import "wasi_snapshot_preview1" "sock_accept" (func $sock_shutdown (type 1)))
  (import "wasi_snapshot_preview1" "proc_exit" (func $proc_exit (type 2)))
  (import "wasi_snapshot_preview1" "fd_close" (func $fd_close (type 3)))
  (func $_start
    (call $fd_close
      (i32.const 2)
    )
    drop
    (call $sock_shutdown
      (i32.const 2)
      (i32.const 27)
      (i32.const 1337)
    )
    call $proc_exit
  )
  (memory 2)
  (export "memory" (memory 0))
  (export "_start" (func $_start))
)
```

1. Build with options `wat2wasm shutdown.wat -o shutdown.wasm`
2. Execute with flags `wasmedge shutdown.wasm`
3. Get error

```
$ wasmedge shutdown.wasm
Segmentation fault (core dumped)
```

### Components

CLI

### WasmEdge Version or Commit you used

0.13.5

### Operating system information

Fedora 39

### Hardware Architecture

amd64

**Comment by dannypsnl** [comment]
Reproducible

1. macOS: 14.1.1, M2 Max
2. wasmedge version 0.13.4-100-g8f37aedc
