### ISSUE TITLE
A difference was found in the printing time of a file?

### ISSUE THREAD

**Issue by Userzxcvbvnm** [WasmEdge/WasmEdge#3050]
### Summary

The test case is uploaded as time.wasm, it is compiled form time.c. (time.wasm is uploaded as time-wasm.txt, time.c is uploaded as time-c.txt)
A difference was discovered between Wasmedge and other WebAssembly runtimes (wasmtime, wasmer, etc.) and native code.

# Expected result: (natively ,wasmtime, wasmer result):
File Size: 0 bytes
File Permissions: 0
File Owner ID: 0
File Group ID: 0
Last Access Time: 1700705140
Last Modification Time: 1700483370
Last Status Change Time: 1700483370

# Actual result:(WasmEdge)
File Size: 0 bytes
File Permissions: 777
File Owner ID: 0
File Group ID: 0
Last Access Time: 10290639077
Last Modification Time: 10290417962
Last Status Change Time: 10290417962

[time-c.txt](https://github.com/WasmEdge/WasmEdge/files/13449547/time-c.txt)
[time-wasm.txt](https://github.com/WasmEdge/WasmEdge/files/13449548/time-wasm.txt)

Are there any differences in the file time design of WasmEdge?

# Environment
WasmEdge 0.13.4
Windows 10
amd64

**Comment by professorabhay** [comment]
Hey @hydai! Can you please tell me something more about that?
I would like to try this.

**Comment by hydai** [comment]
Hi @professorabhay 
If you want to fix this, please follow these steps:

1. Build WasmEdge from the source on the Windows platform.
2. Run the given test wasm file to reproduce this issue.
3. The bug should be inside this function: https://github.com/WasmEdge/WasmEdge/blob/master/lib/host/wasi/inode-win.cpp#L412
4. Fix it. Pass the test. And then send a PR to us.
