### ISSUE TITLE
Maybe a writing error ?

### ISSUE THREAD

**Issue by Userzxcvbvnm** [WasmEdge/WasmEdge#3051]
### Summary

using `wasmedge --dir=./Data write.wasm`
The test case is uploaded as write.wasm, it is compiled form write.c.
[write-c.txt](https://github.com/WasmEdge/WasmEdge/files/13449932/write-c.txt)
[write-wasm.txt](https://github.com/WasmEdge/WasmEdge/files/13449933/write-wasm.txt)

### Current State

Successfully get the file fd.
Current offset: 0
Wrote 0 bytes to the file.
File Size: 33 bytes

Although there is nothing to write in the buffer, the start value is 50, which is larger than the file size. It may be expected to expand the file size. And this is what wasmtime does.

### Expected State

Successfully get the file fd.
Current offset: 0
Wrote 0 bytes to the file.
File Size: 50 bytes

### Reproduction steps
The wasm file is uploades.
using `wasmedge run --dir=./Data write.wasm` to execute the wasm file.

### Screenshots

using `wasmedge run --dir=./Data write.wasm` to execute the wasm file.

### Any logs you want to share for showing the specific issue

The actual printing messager is shown in Current State.

### Components

CLI

### WasmEdge Version or Commit you used

0.13.4

### Operating system information

Windows10

### Hardware Architecture

amd64

### Compiler flags and options

The wasm file is compiled from the C file, using clang.

**Comment by dannypsnl** [comment]
Please provide reproduction steps.

**Comment by Userzxcvbvnm** [comment]
> Please provide reproduction steps.
Thanks for your reply! I have updated the reproduction steps.
