### ISSUE TITLE
Print hard link file number error.

### ISSUE THREAD

**Issue by Userzxcvbvnm** [WasmEdge/WasmEdge#3054]
### Summary

The test case is uploaded as readlink.wasm, it is compiled form readlink.c.
[readlink-wasm.txt](https://github.com/WasmEdge/WasmEdge/files/13455022/readlink-wasm.txt)
[readlink-c.txt](https://github.com/WasmEdge/WasmEdge/files/13455023/readlink-c.txt)

One hard link file (Data/link/hello_hardlink.txt) is pointed to Data/hello.txt, and one soft link file(Data/link/hello_softlink.txt) is pointed to Data/hello.txt.
And the expected hard link number is 1.
And in wasi api (https://github.com/WebAssembly/wasi-libc/blob/main/libc-bottom-half/headers/public/wasi/api.h), nlink means number of hard linke to the file.
    /**
     * Number of hard links to the file.
     */
    __wasi_linkcount_t nlink;

### Current State

Successfully get the file fd.
File Type: 4
Number of hard links to the file: 2 
File Size: 33 bytes

### Expected State

Successfully get the file fd.
File Type: 4
Number of hard links to the file: 1 
File Size: 33 bytes

### Reproduction steps

The test case is uploaded as readlink.wasm, it is compiled form readlink.c.
using `wasmedge --dir=./Data readlink.wasm` to execute this wasm file.

### Screenshots

![DESCRIPTION](LINK.png)

### Any logs you want to share for showing the specific issue

The actual log is shown in Current State.

### Components

CLI

### WasmEdge Version or Commit you used

0.13.4

### Operating system information

Windows10

### Hardware Architecture

amd64

### Compiler flags and options

using clang to compile the c file into wasm file.

**Comment by sheharyaar** [comment]
Hi @Userzxcvbvnm, why is the expected number of hard links 1 ? The current output shows the correct value (i.e 2), the number of hard links include `./Data/hello.txt` and `./Data/link/hello_hardlink.txt`

Reference : https://www.redhat.com/sysadmin/linking-linux-explained

**Comment by hydai** [comment]
Fixed by #3370
