### ISSUE TITLE
Google colab: /bin/bash: line 1: wasmedge: command not found

### ISSUE THREAD

**Issue by taozhiyuai** [WasmEdge/WasmEdge#3066]
### Summary

I try to run Yi-34B on Google colab following the instruction from https://www.secondstate.io/articles/yi-34b/

there are four steps for  "Run the Yi-34B-Chat model on your own device", it is ok from step 1 to 3, but when the ERR info for step 4 is "/bin/bash: line 1: wasmedge: command not found"

does anyone could help? thx

![1](https://github.com/WasmEdge/WasmEdge/assets/146583103/fbcd013c-dec3-4e78-ae98-d4e3ecd9be21)

**Comment by alabulei1** [comment]
Can you run `wasmedge -v` to check if you installed WasmEdge correctly?

**Comment by dannypsnl** [comment]
Please check your PATH environment variable
