### ISSUE TITLE
question: Function type check of WASI proc_exit

### ISSUE THREAD

**Issue by unicornt** [WasmEdge/WasmEdge#3070]
### Summary

Hi, I noticed that WasmEdge does not check the type of wasi function when importing them. I am quite curious about why it is no checked(like other runtimes) and how WasmEdge calls the wasi function with wrong type.
The code is like this.
```WASM
(module
  (type (;0;) (func (param i32 i32 i32) (result i32)))
  (type (;1;) (func (param i32) (result i32)))
  (type (;2;) (func (param i32)))
  (type (;3;) (func))
  (import "wasi_snapshot_preview1" "proc_exit" (func (;0;) (type 3)))
  (func (;1;) (type 3)
    call 0
  )
  (table (;0;) 6 6 funcref)
  (memory (;0;) 8192 8192)
  (export "memory" (memory 0))
  (export "_start" (func 1))
  (export "__indirect_function_table" (table 0))
)
```
[case.zip](https://github.com/WasmEdge/WasmEdge/files/13533835/report32.zip)

I run this code in terminal with `wasmedge case.wasm` and it returns `0`. I also tried other runtimes and they all throw the error.

![image](https://github.com/WasmEdge/WasmEdge/assets/18662046/92ad2140-41b9-4f55-a9c4-be0b9949003d)

**Comment by q82419** [comment]
Nice catch.
