### ISSUE TITLE
bug: Failed to clean up all installed files

### ISSUE THREAD

**Issue by apepkuss** [WasmEdge/WasmEdge#3078]
### Summary

The `uninstall.sh` failed to clean up all installed files on macOS.

### Reproduction steps

1. Run the command `curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- -v 0.13.5 --plugins wasi_nn-ggml` to install both `WasmEdge` and  `wasi_nn-ggml` plugin on macOS. After that, the directory structure is shown as below:

    ```console
    /Users/sam/.wasmedge
    ├── bin
    │   ├── wasmedge
    │   └── wasmedgec
    ├── env
    ├── include
    │   └── wasmedge
    │       ├── enum.inc
    │       ├── enum_configure.h
    │       ├── enum_errcode.h
    │       ├── enum_types.h
    │       ├── int128.h
    │       ├── version.h
    │       └── wasmedge.h
    ├── lib
    │   ├── libwasmedge.0.0.3.dylib
    │   ├── libwasmedge.0.0.3.tbd
    │   ├── libwasmedge.0.dylib -> libwasmedge.0.0.3.dylib
    │   ├── libwasmedge.0.tbd -> libwasmedge.0.0.3.tbd
    │   ├── libwasmedge.dylib -> libwasmedge.0.dylib
    │   └── libwasmedge.tbd -> libwasmedge.0.tbd
    └── plugin
        ├── ggml-metal.metal
        └── libwasmedgePluginWasiNN.dylib
    ```

2. Uninstall by running the command `bash <(curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/uninstall.sh) -q`. After that, the directory is still there and the `ggml-metal.metal` file is not removed.

    ```console
    /Users/sam/.wasmedge
    ├── bin
    ├── include
    └── plugin
        └── ggml-metal.metal
    ```

### Screenshots

![DESCRIPTION](LINK.png)

### Components

Others

### WasmEdge Version or Commit you used

0.13.5

### Operating system information

macOS 14.1.1

### Hardware Architecture

Apple M1 Pro

**Comment by hydai** [comment]
Hi @SAtacker 
Could you please check this issue?

**Comment by SAtacker** [comment]
Okay, so the path is wrongly appended for ggml-metal.metal `#/Users/XXXXX/.wasmedge/ggml-metal.metal` is incorrect. It should be under the plugins directory.
