### ISSUE TITLE
Can not open the directory?

### ISSUE THREAD

**Issue by Userzxcvbvnm** [WasmEdge/WasmEdge#3082]
### Summary

The test program is to delete a subdirectory Data/tmpdir in directory Data.
However, WasmEdge fails.

The c file is uploaded as 
[test-c.txt](https://github.com/WasmEdge/WasmEdge/files/13610351/test-c.txt)

The wasm file is uploaded as 
[test-wasm.txt](https://github.com/WasmEdge/WasmEdge/files/13610350/test-wasm.txt)

### Current State

Print:
```
Failed to open the file.
: Is a directory
```

### Expected State

Print:
```
Successfullly get the file fd.
File deleted successfully.
```

And the sub directory tmpdir is deleted.

And this is what wasmer does.

### Reproduction steps

using command `wasmedge --dir=./Data test.wasm`

### Screenshots

![DESCRIPTION](LINK.png)

### Components

CLI

### WasmEdge Version or Commit you used

0.13.4

### Operating system information

Ubuntu 20.04

### Hardware Architecture

x86_64

### Compiler flags and options

Using clang to compile the c file into wasm file.

**Comment by dannypsnl** [comment]
Please post source code next time, especially your C file is short.

I don't understand your environment, `--dir=./Data` will use `Data/` as current directory from my understanding, and your code is trying to open a file named `Data`. Might you expand more?

**Comment by Userzxcvbvnm** [comment]
> Please post source code next time, especially your C file is short.
> 
> I don't understand your environment, `--dir=./Data` will use `Data/` as current directory from my understanding, and your code is trying to open a file named `Data`. Might you expand more?
> 
> In this sense, you will need to provide full steps including how you prepare your file system for the program.

Thanks for your reply!
The c file is already uploaded a s test-c.txt, and the wasm file is already uploaded as test-wasm.txt, since .c and .wasm file cannot be uploaded. Please download the file and change the suffic.

**Comment by Userzxcvbvnm** [comment]
> No, I mean you can just post C code in code block.

Ok, here's the c code:
```
#include <stdio.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/stat.h>

int path_remove_directory(int basedir_fd, const char *file_name) {
    if (unlinkat(basedir_fd, file_name, AT_REMOVEDIR) == -1) {
        printf("Error deleting file.\n");
        close(basedir_fd);
        return 1;
    }

    printf("File deleted successfully.\n");
    return basedir_fd;
}

int get_fd(const char* file_name, int open_style){
    int fd = open(file_name, open_style);
    if (fd == -1) {
        perror("Failed to open the file.\n");
    }else{
        printf("Successfullly get the fle fd.\n");
    }

    return fd;
}

int main() {
    const char* file_name = "Data";
    int open_style= O_RDWR;
    int fd = get_fd(file_name, open_style);

    if (fd != -1){
        const char *file_name = "tmpdir";
        path_remove_directory(fd, file_name);
    }
    
    return 0;
}
```

**Comment by yagehu** [comment]
This is not a bug with WasmEdge, you just need to change your `O_RDWR` to `O_RDONLY`. https://github.com/bytecodealliance/wasm-micro-runtime/issues/2884
