### ISSUE TITLE
Get the source file of link file error ?

### ISSUE THREAD

**Issue by Userzxcvbvnm** [WasmEdge/WasmEdge#3083]
### Summary

`Data/link/hello_softlink.txt` is a soft link file points to `Data/hello.txt`.
MaybeWasmEdge print the pointed file of softlink file error.

The c file is uploaded as 
[test-c.txt](https://github.com/WasmEdge/WasmEdge/files/13610415/test-c.txt)

The wasm file is uploaded as 
[test-wasm.txt](https://github.com/WasmEdge/WasmEdge/files/13610416/test-wasm.txt)

### Current State

Print:
```
Successfully get the file fd.
The target of 'hello_softlink.txt' is: C:\Users\gjt\Desktop\WASITest-main-1\WASITest\wasmedge\Data\link\hello_softlink.txt
```

The source file is the softlink itself?
Maybe this is incorrect?

### Expected State

Print:
```
Successfully get the file fd.
The target of 'hello_softlink.txt' is: ./hello.txt
```

WAMR, wasmtime, wazsero all print this result.

### Reproduction steps

Using command `wasmedge --dir=./Data test.wasm`

### Screenshots

![DESCRIPTION](LINK.png)

### Components

CLI

### WasmEdge Version or Commit you used

0.13.4

### Operating system information

Windows 10

### Hardware Architecture

x86_64

### Compiler flags and options

Using clang to compile the c file into wasm file.

**Comment by nox1134** [comment]
Hi! I'd like to work on this issue.

**Comment by hydai** [comment]
I just assigned it to you. @nox1134
