### ISSUE TITLE
Read a directory bug ?

### ISSUE THREAD

**Issue by Userzxcvbvnm** [WasmEdge/WasmEdge#3084]
### Summary

There is a file `Data/mydir/test.txt` is in the path `Data/mydir`
The test program is to print the files in the path `Data/mydir`.

The c file is uploaded as
[readdir-c.txt](https://github.com/WasmEdge/WasmEdge/files/13613347/readdir-c.txt)

The wasm file is uploaded as
[readdir-wasm.txt](https://github.com/WasmEdge/WasmEdge/files/13613349/readdir-wasm.txt)

### Current State

WasmEdge prints:
```
Successfully get the file fd.
opendir.
```

WasmEdge print the content of `Data/mydir` fails.

### Expected State

Print:
```
Successfully get the file fd.
.
..
test.txt
```

wasmer wasmtime wazero print the above message.

### Reproduction steps

using command `wasmedge --dir=./Data test.wasm`

### Screenshots

![DESCRIPTION](LINK.png)

### Components

CLI

### WasmEdge Version or Commit you used

0.13.4

### Operating system information

Windows10

### Hardware Architecture

amd64

### Compiler flags and options

using clang to compile c file into wasm binaries.

**Comment by dannypsnl** [comment]
Cannot reproduce on macOS

```shell
$ wasmedge --dir=./Data readdir.wasm 
Successfully get the file fd.
.
..
test.txt
$ wasmedge --version
wasmedge version 0.13.5
```

**Comment by Userzxcvbvnm** [comment]
Thanks for your reply ! I tried it with WasmEdge 0.13.5 on Windows and still get the result :
```
Successfully get the file fd.
opendir.
```

**Comment by dannypsnl** [comment]
So it seems a windows specific problem.
