### ISSUE TITLE
bug: Failed to load plugins in PyO3 project on CentOS-7

### ISSUE THREAD

**Issue by apepkuss** [WasmEdge/WasmEdge#3100]
### Summary

I am using `PyO3` and `maturin` to prototype a project, which simply loads `wasi-nn_ggml` plugin via `wasmedge-rust-sdk`. [Here](https://github.com/apepkuss/load_plugin/blob/main/src/lib.rs) is the source code. 

The observations are:

- When using `maturin develop` to build the source, the generated Python wheel file works well. It can print out the count and names of the plugins loaded by "PluginManager":
  ```console
  (.env) [root@277f2e649aad load_plugin]# python
  Python 3.10.13 (main, Dec  5 2023, 08:22:38) [GCC 10.2.1 20210130 (Red Hat 10.2.1-11)] on linux
  Type "help", "copyright", "credits" or "license" for more information.
  >>> import load_plugin
  >>> load_plugin.run()
  Hello, world!
  Plugin count: 1
  Plugin names: ["wasi_nn"]
  ```
- When using `maturin build`, the printing info show that no plugin is loaded:
  ```console
  (.env) [root@277f2e649aad load_plugin]# python
  Python 3.10.13 (main, Dec  5 2023, 08:22:38) [GCC 10.2.1 20210130 (Red Hat 10.2.1-11)] on linux
  Type "help", "copyright", "credits" or "license" for more information.
  >>> import load_plugin
  >>> load_plugin.run()
  Hello, world!
  Plugin count: 0
  Plugin names: []
  >>> 
  ``` 

Before opening this bug issue, I also filed the same issue in [pyo3/maturin](https://github.com/PyO3/maturin/issues/1884). According to the investigations by me and the maintainer of `maturin`, the issue seems to be related to the C-API: [WasmEdge_PluginLoadFromPath](https://github.com/WasmEdge/WasmEdge/blob/master/include/api/wasmedge/wasmedge.h#L3908C34-L3908C61). Note that using [WasmEdge_PluginLoadWithDefaultPaths](https://github.com/WasmEdge/WasmEdge/blob/master/include/api/wasmedge/wasmedge.h#L3899) also shows the same issue when the plugin .so file is located in the default installation directory.

The key info of software and hardware:

- docker image: wasmedge/wasmedge:manylinux2014_x86_64
- WasmEdge 0.13.5
- wasmedge-rust-sdk 0.13.2
- PyO3: 0.20.0
- maturin: 1.4.0
- Rust: 1.74.1
- Python: 3.10

### Reproduction steps

The steps to reproduce the issue:

- Git clone test code

  Git clone test code and put it into a directory named, for example, `workspace`:
  ```bash
  cd workspace
  git clone https://github.com/apepkuss/load_plugin.git
  ```

  Docker pull `wasmedge/wasmedge:manylinux2014_x86_64`

  ```bash
  docker run --name="test-plugin" -it -v $HOME/workspace/:/root/workspace wasmedge/wasmedge:manylinux2014_x86_64
  ```

The steps below are run in the docker container:

- Download library file

  In the docker container, download and unzip the library file:

  ```bash
  cd load_plugin

  # download .so file
  curl -LO https://github.com/WasmEdge/WasmEdge/releases/download/0.13.5/WasmEdge-plugin-wasi_nn-ggml-0.13.5-manylinux2014_x86_64.tar.gz

  # unzip
  tar -xf WasmEdge-plugin-wasi_nn-ggml-0.13.5-manylinux2014_x86_64.tar.gz
  
  # set LD_LIBRARY_PATH
  export LD_LIBRARY_PATH=/root/workspace/test/load_plugin:$LD_LIBRARY_PATH
  ```
- Install WasmEdge Runtime
  ```bash
  curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- -v 0.13.5
  ```
- Set up Python environment
  - Create a virtual environment
    ```bash
    cd load_plugin
    
    # create virtual env
    /opt/python/cp310-cp310/bin/python -m venv .env

    # activate env
    source .env/bin/activate
    ```

  - Install dependencies
    ```bash
    pip install maturin patchelf
    ```

- Build with `maturin develop`
 
  - Build 
    ```bash
    maturin develop -r
    ```

  - Test
    ```bash
    (.env) [root@277f2e649aad load_plugin]# python
    Python 3.10.13 (main, Dec  5 2023, 08:22:38) [GCC 10.2.1 20210130 (Red Hat 10.2.1-11)] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import load_plugin
    >>> load_plugin.run()
    Hello, world!
    Plugin count: 1
    Plugin names: ["wasi_nn"]
    ```

- Build with `maturin build` (Failed)
  
  - Uninstall the `load_plugin` package if there is one installed
    ```bash
    # uninstall `load_plugin` installed by `maturin develop`
    pip uninstall load_plugin
    ```

  - `maturin build` the `load_plugin` wheel:
    ```bash
    maturin build --compatibility manylinux2014 -i /root/workspace/test/load_plugin/.env/bin/python -r -o dist
    ```

  - Install the wheel
    ```bash
    pip install dist/load_plugin-0.1.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
    ```

  - Test
    ```bash
    (.env) [root@277f2e649aad load_plugin]# python
    Python 3.10.13 (main, Dec  5 2023, 08:22:38) [GCC 10.2.1 20210130 (Red Hat 10.2.1-11)] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import load_plugin
    >>> load_plugin.run()
    Hello, world!
    Plugin count: 0
    Plugin names: []
    >>> 
    ```

### Screenshots

![DESCRIPTION](LINK.png)

### Components

C SDK

### WasmEdge Version or Commit you used

0.13.5

### Operating system information

CentOS-7.9

### Hardware Architecture

x86_64

### Compiler flags and options

WasmEdge is installed via the command `curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- -v 0.13.5 --plugins wasi_nn-ggml`

**Comment by q82419** [comment]
@hydai , please check this is still valid or not if we deprecate CentOS 7 in the future.

**Comment by hydai** [comment]
Since CentOS 7 will be EOL at the end of June 2024, I don't think we need to fix this.
