### ISSUE TITLE
bug: Failed to run `tinyllama-1.1b-chat-v0.3` with the `wasi-nn` plugin of `0.13.5`

### ISSUE THREAD

**Issue by apepkuss** [WasmEdge/WasmEdge#3111]
### Summary

Compared with the previous version of `wasi-nn` plugin, the new update (b1656) failed to run `tinyllama-1.1b-chat-v0.3` on Ubuntu-22.04(Intel(R) Xeon(R) Platinum 8259CL CPU) as well as macOS-14.2(M1 Pro).

(Left: The previous version. Right: the latest version)
<img width="1730" alt="image" src="https://github.com/WasmEdge/WasmEdge/assets/4726889/03e61ff4-2ec0-46e7-a3a5-23fee0d42536">

The sha256sum values of the latest and old `wasi-nn` plugins:
  - Latest version: 63220211418ffbac339b5beb934fe24e845bae6735980705c2f0389d2c48f81d
  - Old version: 1025c310976d3e7944a39e27c830f485eaa5f7518ce275a25d7735d0361bb386

### Reproduction steps

- Install WasmEdge 0.13.5 + ggml plugin of latest version

- Download `tinyllama-1.1b-chat-v0.3`
    ```bash
    curl -LO https://huggingface.co/second-state/TinyLlama-1.1B-Chat-v0.3-GGUF/resolve/main/tinyllama-1.1b-chat-v0.3.Q5_K_M.gguf
    ```

- Download `llama-chat.wasm v0.2.0`
  ```bash
  curl -LO https://github.com/second-state/llama-utils/raw/dev/chat/llama-chat.wasm
  ```
  To check the version, run `wasmedge llama-chat.wasm -V`

- Run the model
  ```bash
  wasmedge --dir .:. --nn-preload default:GGML:AUTO:tinyllama-1.1b-chat-v0.3.Q5_K_M.gguf llama-chat.wasm -p chatml
  ```

### Screenshots

![DESCRIPTION](LINK.png)

### Components

Others

### WasmEdge Version or Commit you used

0.13.5

### Operating system information

Ubuntu-22.04, macOS-14.2

### Hardware Architecture

x86_64, aarch64

**Comment by hydai** [comment]
@apepkuss 
Could we reproduce this issue with `run-llm.sh`?

**Comment by apepkuss** [comment]
The TinyLlama-1.1b-chat model has already updated to `v1.0`, so we only support `v1.0` now. I'll close the issue. Thanks!
