### ISSUE TITLE
bug: Failed to run `openhermes-2.5-mistral-7b` with the `wasi-nn` plugin of `0.13.5`

### ISSUE THREAD

**Issue by apepkuss** [WasmEdge/WasmEdge#3112]
### Summary

The latest `wasi-nn` plugin failed to run `openhermes-2.5-mistral-7b`. And the behaviors on macOS-14.2 (m1 pro) and Ubuntu-22.04 (Intel(R) Xeon(R) Platinum 8259CL CPU), respectively, are different:

- On macOS
  <img width="1114" alt="image" src="https://github.com/WasmEdge/WasmEdge/assets/4726889/1569c074-960c-4b7f-aa17-cb3f12d13225">

- On Ubuntu
  <img width="860" alt="image" src="https://github.com/WasmEdge/WasmEdge/assets/4726889/81eea70c-e95b-4b47-8c65-6a99e1f4bb5b">

### Reproduction steps

- Install WasmEdge 0.13.5 + ggml plugin of latest version
- Download `openhermes-2.5-mistral-7b`
  ```bash
  curl -LO https://huggingface.co/second-state/OpenHermes-2.5-Mistral-7B-GGUF/resolve/main/openhermes-2.5-mistral-7b.Q5_K_M.gguf
  ```
- Download `llama-chat.wasm`
  ```bash
  curl -LO https://github.com/second-state/llama-utils/raw/dev/chat/llama-chat.wasm
  ```
- Run the model
  ```bash
  wasmedge --dir .:. --nn-preload default:GGML:AUTO:openhermes-2.5-mistral-7b.Q5_K_M.gguf llama-chat.wasm -p chatml -r '<|im_end|>'
  ```

### Screenshots

![DESCRIPTION](LINK.png)

### Components

Others

### WasmEdge Version or Commit you used

0.13.5

### Operating system information

Ubuntu 22.04, macOS 14.2

### Hardware Architecture

x86_64, aarch64

**Comment by hydai** [comment]
@apepkuss Could you please check if the problem still exists with the latest plugin?

**Comment by hydai** [comment]
No response, closing it. Please feel free to re-open it if there are any issues.
