### ISSUE TITLE
bug: Download error from urllib: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by stackermans** [WasmEdge/WasmEdge#3127]
### Summary

The install script is looking for `https://github.com/WasmEdge/WasmEdge/releases/download/0.13.5/WasmEdge-plugin-wasi_nn-ggml-0.13.5-darwin_x86_64.tar.gz` which does not exist.

### Current State

```
INFO    - Installing WasmEdge
INFO    - WasmEdge Successfully installed
INFO    - Downloading Plugin: wasi_nn-ggml
ERROR   - Download error from urllib: HTTP Error 404: Not Found
ERROR   - URL: https://github.com/WasmEdge/WasmEdge/releases/download/0.13.5/WasmEdge-plugin-wasi_nn-ggml-0.13.5-darwin_x86_64.tar.gz
```

### Reproduction steps

Execute `curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- --plugins wasi_nn-ggml` on OSX

### Screenshots

![DESCRIPTION](LINK.png)

### Components

CLI

### WasmEdge Version or Commit you used

0.13.5

### Operating system information

OSX

### Hardware Architecture

arm64 (M2)

**Comment by hydai** [comment]
Hi @stackermans 
Could you please run `arch` and `uname -a` to show your current architecture?
It looks like you are using x86 mode.
If you want to switch back to arm64, please follow this guide: https://vineethbharadwaj.medium.com/m1-mac-switching-terminal-between-x86-64-and-arm64-e45f324184d9

**Comment by baiXfeng** [comment]
@hydai I've got a Mac with an x86 system, and I'm facing the same issue. Does it mean this program doesn't support x86 platforms?
`
baifeng@BF-MAC ~ % curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- --plugins wasi_nn-ggml
Using Python: /Users/baifeng/.pyenv/shims/python3 
WARNING - CUDA should be only available on Linux
WARNING - Experimental Option Selected: plugins
WARNING - plugins option may change later
INFO    - Compatible with current configuration
INFO    - Running Uninstaller
WARNING - SHELL variable not found. Using zsh as SHELL
INFO    - shell configuration updated
INFO    - Downloading WasmEdge
|============================================================|100.00 %INFO    - Downloaded
INFO    - Installing WasmEdge
INFO    - WasmEdge Successfully installed
INFO    - Downloading Plugin: wasi_nn-ggml
ERROR   - Download error from urllib: HTTP Error 404: Not Found
ERROR   - URL: https://github.com/WasmEdge/WasmEdge/releases/download/0.13.5/WasmEdge-plugin-wasi_nn-ggml-0.13.5-darwin_x86_64.tar.gz
baifeng@BF-MAC ~ % 
`
run arch ouput:
`
baifeng@BF-MAC ~ % arch
i386
`

**Comment by hydai** [comment]
Hi @baiXfeng 
This should be fixed now. Please try again.

@stackermans 
Please feel free to re-open this issue if you still encounter the same problem.
