### ISSUE TITLE
bug: CI failed at plugins (manylinux2014_x86_64-plugins-deps, g++, Release)

### ISSUE THREAD

**Issue by dm4** [WasmEdge/WasmEdge#3137]
### Summary

As this job: https://github.com/WasmEdge/WasmEdge/actions/runs/7393162193/job/20112684186

It shows:

```
CMake Error at /opt/rh/devtoolset-11/root/usr/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY) (found
  version "1.0.2k")
Call Stack (most recent call first):
  /opt/rh/devtoolset-11/root/usr/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /opt/rh/devtoolset-11/root/usr/share/cmake-3.26/Modules/FindOpenSSL.cmake:670 (find_package_handle_standard_args)
  plugins/wasi_crypto/CMakeLists.txt:5 (find_package)
```

### Current State

CI failed.

### Expected State

CI passed.

### Reproduction steps

1. Create a PR and wait.

### Components

Others

### WasmEdge Version or Commit you used

latest

### Operating system information

manylinux2014

### Hardware Architecture

x86_64

**Comment by jaydee029** [comment]
Hi, @dm4 I think this part of the ci is invoked specifically when you are working with plugins , cause the test just passed in the 
following PR a minute ago
[https://github.com/WasmEdge/WasmEdge/actions/runs/7436056462/job/20232110059?pr=3093](url)

**Comment by dm4** [comment]
Hi @jaydee029, I suspect this was a random failure in the GitHub workflow. Since there have been no subsequent failed jobs after I merged the same commit into the master branch, I think we can close this issue now and reopen it if we identify a specific cause. Thank you for the information.
