### ISSUE TITLE
LFX Mentorship (Mar-May, 2024): Integrate MLX as a new WASI-NN backend

### ISSUE THREAD

**Issue by hydai** [WasmEdge/WasmEdge#3168]
### Summary

LLM is a hot topic, there are more and more frameworks to make the execution of LLM faster. WasmEdge already integrated the [llama.cpp](https://github.com/ggerganov/llama.cpp) as one of the backend. And we want to bring more. [MLX](https://github.com/ml-explore/mlx) is an array framework on Apple silicon created by Apple machine learning research. With MLX, we believe it can have a huge improvement on macOS.

### Details

- Pre-test: To apply for this mentorship, you MUST finish a pre-test. Pre-test link: https://github.com/WasmEdge/WasmEdge/discussions/3182
- Expected Outcome: A new plugin provides an MLX [WASI-NN](https://github.com/second-state/wasmedge-wasi-nn) backend, a test suite for validating the plugin, documents, and examples for explaining how to use the plugin.
- Recommended Skills: C++, Wasm
- Mentor(s):
  - Hung-Ying Tai (@hydai)
  - dm4 (@dm4)

### Appendix

1. MLX: https://github.com/ml-explore/mlx
2. WASI-NN: https://github.com/second-state/wasmedge-wasi-nn
3. WASI-NN llama.cpp backend(check `ggml.h` and `ggml.cpp`): https://github.com/WasmEdge/WasmEdge/tree/master/plugins/wasi_nn

**Comment by jaydee029** [comment]
It was great seeing wasmedge demo with llms in the last community meet, looking forward to contribute to this when the applications open.

**Comment by nox1134** [comment]
Hi @hydai! I would love to solve this issue for the upcoming LFX program.

**Comment by qstommyshu** [comment]
Hi @hydai !I would like to work on this issue under LFX mentorship.

**Comment by guptaaryan16** [comment]
Hi @hydai, I am interested in working on this issue as well, having been a part of MLX community, it seems great

**Comment by minghuaw** [comment]
Just wondering if there is any chance that this could be implemented in rust? I am currently working on a rust binding of mlx.

**Comment by hydai** [comment]
> Just wondering if there is any chance that this could be implemented in rust? I am currently working on a rust binding of mlx.

I don't think we would be interested in an unofficial support binding because we would like to sync with the upstream constantly.

**Comment by hydai** [comment]
Completed. Closing it.
