### ISSUE TITLE
LFX Mentorship (Mar-May, 2024): Integrate burn.rs as a new WASI-NN backend

### ISSUE THREAD

**Issue by hydai** [WasmEdge/WasmEdge#3172]
### Summary

WasmEdge supports PyTorch, TensorFlow Lite, llama.cpp, and more NN backend. [Burn.rs](https://github.com/tracel-ai/burn) is a new deep-learning framework built using Rust. The portability, flexibility, and compute efficiency are important to Wasm. That's why we would love to have `burn.rs` as a new [WASI-NN](https://github.com/second-state/wasmedge-wasi-nn) backend.

### Details

- Pre-test: To apply for this mentorship, you MUST finish a pre-test. Pre-test link: https://github.com/WasmEdge/WasmEdge/discussions/3182
- Expected Outcome: A new plugin provides a burn.rs [WASI-NN](https://github.com/second-state/wasmedge-wasi-nn) backend, a test suite for validating the plugin, documents, and examples for explaining how to use the plugin.
- Recommended Skills: Rust, Wasm
- Mentor(s):
  - Hung-Ying Tai (@hydai, hydai@secondstate.io)
  - dm4 (@dm4, dm4@secondstate.io),

### Appendix

1. Burn.rs: https://github.com/tracel-ai/burn
2. WASI-NN: https://github.com/second-state/wasmedge-wasi-nn
3. How we integrate PyTorch: https://github.com/WasmEdge/WasmEdge/tree/master/plugins/wasi_nn
4. How we implement a Rust plugin: https://github.com/WasmEdge/WasmEdge/tree/master/plugins/wasmedge_rustls

**Comment by chococandy63** [comment]
Hello @hydai, I would like to work on this project. Any updates on pre-test?

**Comment by hydai** [comment]
Hi @chococandy63 
The pre-test is still preparing; we are going to announce it on 1/29.

**Comment by chococandy63** [comment]
Thank you @hydai for notifying me!!

**Comment by souravpy** [comment]
Is there any pre-test yet? I would like to pick this issue up!

**Comment by staru09** [comment]
Is this still open to work?

**Comment by hydai** [comment]
Hi @staru09 
No longer available for others. @CaptainVincent is working on it.

**Comment by staru09** [comment]
okayy

**Comment by q82419** [comment]
Replaced by roadmap issue #3543.
