### ISSUE TITLE
Support TLS2

### ISSUE THREAD

**Issue by Avey777** [WasmEdge/WasmEdge#3198]
### Summary

Upgrade to TLS 2

### Details

```
(base) root@Jengro:~# curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- -p /usr/local --plugins wasi_nn-tensorflowlite wasmedge_tensorflow
curl: (35) OpenSSL/3.0.11: error:0A000438:SSL routines::tlsv1 alert internal error
(base) root@Jengro:~# 
```

https://github.com/curl/curl/issues/10002

**Comment by hydai** [comment]
The URL we used here provides TLS1.2 and TLS1.3. See: https://testtls.com/raw.githubusercontent.com/443
I don't think we have anything to do in this case.
