### ISSUE TITLE
feat: Implementing Coredump for Post-Mortem Debugging in WebAssembly

### ISSUE THREAD

**Issue by hydai** [WasmEdge/WasmEdge#3205]
### Summary

This project, [wasm-coredump](https://github.com/WebAssembly/tool-conventions/blob/main/Coredump.md), aims to enhance the debugging capabilities of WebAssembly by implementing a coredump feature for post-mortem analysis. When WebAssembly encounters a runtime error, it will initiate a process to collect debugging information, including stack frames, local variable values, and a snapshot of the linear memory. This data is saved in a coredump file, which, along with DWARF information, can be analyzed post-mortem to debug the error. The project involves creating or enhancing tools to generate and analyze Wasm coredumps, addressing the unique challenges of WebAssembly's memory model and execution semantics.

### Details

Expected Outcome:
- A new API and tool option to specify the saved coredump files.
- Implement the coredump inside the WasmEdge components, when a trap is triggered, there should be a whole process to log and save any information defined in the [wasm-coredump](https://github.com/WebAssembly/tool-conventions/blob/main/Coredump.md) spec.
- The coredump file must be compatible with the current toolchain, including [wasmgdb](https://github.com/xtuc/wasm-coredump/tree/main/bin/wasmgdb) and [wasm-edit](https://github.com/xtuc/wasm-coredump/tree/main/bin/rewriter).
- Documentation on the coredump format, including how to encode process, module, and instance information.
- Tutorials, examples, and demonstration of post-mortem debugging using the implemented coredump feature.

Recommended Skills:
- WebAssembly
- C++
- Debugger

### Appendix

The original issue is from here: https://github.com/WasmEdge/WasmEdge/issues/2264

**Comment by sid-008** [comment]
I'd like to potentially work on this for my gsoc proposal, any ideas how I can get started piecing it together?

**Comment by hydai** [comment]
> I'd like to potentially work on this for my gsoc proposal, any ideas how I can get started piecing it together?

Hi @sid-008 

If you don't have any concept about the WASM, I suggest you use the above tools, wasmgdb and wasm-edit, to know how it may work in a real use case. Since you will need to implement the wasm-coredump, you will need to read the spec and arrange the implementation plan in your proposal.

**Comment by sid-008** [comment]
> > I'd like to potentially work on this for my gsoc proposal, any ideas how I can get started piecing it together?
> 
> Hi @sid-008
> 
> If you don't have any concept about the WASM, I suggest you use the above tools, wasmgdb and wasm-edit, to know how it may work in a real use case. Since you will need to implement the wasm-coredump, you will need to read the spec and arrange the implementation plan in your proposal.

Hey @hydai, thanks for replying. I've used WASM and emscripten before to do a few graphics related things with raylib. I have a decent idea of how WASM works, including the linear memory model and other concepts.  I've never used WASM-gdb or wasmedit before, so I'll look into those shortly. 

I've looked into the wasm-coredump spec very briefly as well. Hope I can keep you in the loop about this!

**Comment by sid-008** [comment]
Hey @hydai I was working on my GSOC proposal for this project, [link](https://docs.google.com/document/d/1i0qzk_LGWj8-bimUWq-Z40lhDqjMzqPxHH0uo16lF5M/edit?usp=sharing) its incomplete but I plan to finish it by tomorrow. I've explored the WASM-coredump spec and gone through the demo as well. However I've come across a few important things to note:
in: [https://github.com/xtuc/wasm-coredump/tree/main/bin/rewriter](https://github.com/xtuc/wasm-coredump/tree/main/bin/rewriter) there has been mention that:

```The Coredump runtime has a performance cost.```

This however has not been elaborated upon. Currently my plan for implementation is to implement the coredump inside the relevant WasmEdge components by modifying the section of wasmedge's code that is responsible for handling the trap events/runtime errors. Along with this I'd like to also include a sort of way to run the wasm module in "debug mode" with a flag of sorts.

**Comment by sid-008** [comment]
Hey @hydai I'll be finishing up my proposal shortly. Any inputs would be much appreciated. [You can find the proposal here](https://docs.google.com/document/d/1i0qzk_LGWj8-bimUWq-Z40lhDqjMzqPxHH0uo16lF5M/edit?usp=sharing)

**Comment by sid-008** [comment]
Hey @hydai I was submitting my proposal and was asked about the "size" of the project as per the organisation. Kindly let me know what the expected size of the project is( i.e small/medium or large)

**Comment by hydai** [comment]
> Hey @hydai I was submitting my proposal and was asked about the "size" of the project as per the organisation. Kindly let me know what the expected size of the project is( i.e small/medium or large). In my proposal I have an expected coding period of 10 weeks + 2 weeks of buffer time(i.e 350 hours)

Large

**Comment by sid-008** [comment]
@hydai is there any feedback I can incorporate or any changes I need to make to my proposal? You can find the link [here](https://docs.google.com/document/d/1i0qzk_LGWj8-bimUWq-Z40lhDqjMzqPxHH0uo16lF5M/edit)
