### ISSUE TITLE
feat: Enabling LLM fine tuning in the WASI-NN PyTorch plugin

### ISSUE THREAD

**Issue by hydai** [WasmEdge/WasmEdge#3208]
## Motivation

WasmEdge is a lightweight and cross-platform runtime for AI / LLM applications. It allows developers to create LLM apps on a Mac or Windows dev machine, compile them to Wasm, and deploy them on Nvidia machines without any changes to the binary app.

It achieves application portability across CPUs and GPUs by supporting a W3C standard API called [WASI-NN](https://github.com/second-state/wasmedge-wasi-nn), which abstracts GPU-related AI functions as high-level APIs. At this stage, however, only inference functions are supported.

In this project, we aim to support fine-tuning features in WasmEdge. It will improve the developer experience for WasmEdge-enabled LLM tools.

WasmEdge currently offers a PyTorch inference backend for WASI-NN. We would like to add support for PyTorch's LLM fine-tuning functions in this project. We plan to extend the current WASI-NN spec by adding a set of extra APIs, and then implement them through PyTorch C++ libraries in the WasmEdge PyTorch plugin. You will then port fine-tuning's data pre- and post-processing logic from Python to Rust so that they can be compiled to Wasm and call the WASI-NN fine-tuning API functions.

### Details

Expected outcome:

- Use llama2-7b as the base LLM for fine-tuning; the final implementation should handle it correctly.
Extend the [WASI-NN](https://github.com/second-state/wasmedge-wasi-nn) spec if needed to support the fine-tuning feature.
- Implement the fine-tuning functions inside [WASI-NN PyTorch plugin](https://github.com/WasmEdge/WasmEdge/blob/master/plugins/wasi_nn/torch.h).
- A Rust crate for the pre- and post-processing functions required for the fine-tuning API. This crate is to be compiled to Wasm to call the WASI-NN functions.
- Documentation, examples, tutorials, and demonstration are required.

Recommended Skills: C++, WebAssembly, PyTorch

### Appendix

PyTorch C++ API: https://pytorch.org/cppdocs/
WasmEdge PyTorch plugin examples: https://github.com/second-state/WasmEdge-WASINN-examples/tree/master/pytorch-mobilenet-image
The yolo-rs project is a port of the YOLO models to WasmEdge PyTorch: https://github.com/Charles-Schleich/yolo-rs
Guides on PyTorch-based LLM fine-tuning libraries: https://llama.meta.com/get-started/#fine-tuning

**Comment by isHuangXin** [comment]
Hi @hydai, 
I find this project interesting and would like to participate.  I am a third-year master's student in computer science, with a research focus on AI, particularly Large Language Models, and Storage Systems. I am proficient in C++, Python, and PyTorch, and have extensive experience fine-tuning various LLMs such as Llama2 and CodeLlama for code generation. Additionally, I possess expertise in system optimization for AI training.

**Comment by dianyo** [comment]
Hi @hydai,
This project is really cool, and i would like to join! I am an experienced ML engineer now working at Leonardo.AI. I have a computer science degree, and I deploy deep learning service on both cloud and edge before. Although I don't have experienced in training LLM at the moment, I'm familiar with PyTorch and have the ability to dig into the underlying layers (Aten, torchscript, fxgraph.) I'm keen to upgrade my knowledge through make my hands dirty by this project!

**Comment by Sayanjones** [comment]
Hi @hydai , I am also interested to work on this project. Can we discuss this further?

**Comment by Sayanjones** [comment]
The broad experience mentioned (scalable AI, generative AI) is helpful but not essential for the WasmEdge fine-tuning project. The core requirements are C++, WebAssembly, and PyTorch knowledge. The provided resources in the appendix can still be valuable references for this project.

**Comment by sandeepB3** [comment]
Hello @hydai, I'm trying to comprehend the contents of the `wasmedge/plugin/wasi_nn` folder. I was wondering, if I use `CMake` to build the files in `wasmedge/plugin/wasi_nn` directory and then copy the built PyTorch binary files (.so/.dylib/.dll) to the plugins directory in my WasmEdge runtime using: `cp wasinn_pytorch.dylib ~/.wasmedge/plugin/`, would this achieve the same result as installing the WASI-NN plug-in with the PyTorch backend using the `curl` command as mentioned in the docs?

**Comment by Sayanjones** [comment]
Hey @hydai, It extends ```WasmEdge``` to support fine-tuning for LLMs like llama2-7b. Add APIs to the ```WASI-NN``` standard (if needed) for fine-tuning. Update WASI-NN PyTorch Pluginto modify the plugin to implement these fine-tuning functionalities. Write the data processing logic in Rust and compile it to ```Wasm``` for interaction with WASI-NN APIs. While building the ```WASI-NN``` PyTorch plugin with ```CMake``` is possible, using ```curl``` for official installation is recommended for simplicity and guaranteed compatibility.

**Comment by sandeepB3** [comment]
> Hey @hydai, It extends `WasmEdge` to support fine-tuning for LLMs like llama2-7b. Add APIs to the `WASI-NN` standard (if needed) for fine-tuning. Update WASI-NN PyTorch Pluginto modify the plugin to implement these fine-tuning functionalities. Write the data processing logic in Rust and compile it to `Wasm` for interaction with WASI-NN APIs. While building the `WASI-NN` PyTorch plugin with `CMake` is possible, using `curl` for official installation is recommended for simplicity and guaranteed compatibility.

Yes, using `curl` for the official installation of the WASI-NN plug-in with the PyTorch backend is simple. 

However, as you mentioned in your message, we need to **"update the WASI-NN PyTorch plugin to implement these fine-tuning functionalities."** This implies that the plugin downloaded using curl does not include the fine-tuning functionalities.

Therefore, for testing our updated plugin, we would have to rebuild it and integrate it into our runtime.

**Comment by sandeepB3** [comment]
Hey @hydai, does the wasi_nn-pytorch plugin work only with the [PyTorch 1.8.2 LTS](https://pytorch.org/get-started/locally/) dependency? If so is there any workaround for using the wasi_nn-pytorch in OSX platform (macOS)? Since macOS is currently not supported for version 1.8.2 LTS or lower.

**Comment by hydai** [comment]
Not selected by GSoC, closing it.
