### ISSUE TITLE
Test different CMAKE options in CI workflow

### ISSUE THREAD

**Issue by 0yi0** [WasmEdge/WasmEdge#321]
As #318 occurred because CI missed the case, it might be good to test all options (or combinations) at least before each release.

**Comment by hydai** [comment]
Could you define which CMAKE options should be tested?
We will need a table to create the CI matrix.

**Comment by 0yi0** [comment]
Maybe `-DCMAKE_BUILD_TYPE=Release` with all feature-related options?
- `-DWASMEDGE_BUILD_AOT_RUNTIME`
- `-DWASMEDGE_BUILD_TOOLS`

Here's the options from `./CMakeLists.txt`,
```
# List of WasmEdge options
option(WASMEDGE_BUILD_TESTS "Generate build targets for the wasmedge unit tests." OFF)
option(WASMEDGE_BUILD_COVERAGE "Generate coverage report. Require WASMEDGE_BUILD_TESTS." OFF)
option(WASMEDGE_BUILD_AOT_RUNTIME "Enable WasmEdge LLVM-based ahead of time compilation runtime." ON)
option(WASMEDGE_BUILD_SHARED_LIB "Generate the WasmEdge shared library." ON)
option(WASMEDGE_BUILD_STATIC_LIB "Generate the WasmEdge static library." ON)
option(WASMEDGE_BUILD_TOOLS "Generate wasmedge and wasmedgec tools." ON)
```
and I also see `-DWASMEDGE_COMPILE_LIBRARY` in `./lib/api/CMakeLists.txt` but it's not listed above.

**Comment by hydai** [comment]
@q82419 
Do you remember this option `WASMEDGE_COMPILE_LIBRARY`?

**Comment by q82419** [comment]
It's the flag for Windows when building the API.
This definition will be added automatically when `WASMEDGE_BUILD_SHARED_LIB` or `WASMEDGE_BUILD_STATIC_LIB` is `ON`.

**Comment by hydai** [comment]
I think we have to re-design the workflows for this situation. Close it.
