### ISSUE TITLE
How can I run wasmedge on Windows11  with GGML plugin

### ISSUE THREAD

**Issue by zhanghui-china** [WasmEdge/WasmEdge#3225]
### Summary

on ubuntu, I use
wasmedge --dir .:. --nn-preload default:GGML:AUTO:mixtral-8x7b-instruct-v0.1.Q5_K_M.gguf llama-chat.wasm -p mistral-instruct

It shows:
![image](https://github.com/WasmEdge/WasmEdge/assets/63148804/b7d412dc-ca4c-4de6-9f2b-72522ba91046)

But on windows 11, when i run the same command line:
wasmedge --dir .:. --nn-preload default:GGML:AUTO:mixtral-8x7b-instruct-v0.1.Q5_K_M.gguf llama-chat.wasm -p mistral-instruct

It shows:
<img width="596" alt="19ed33c3e679c38409cc053b04ab387" src="https://github.com/WasmEdge/WasmEdge/assets/63148804/1ca93ecc-7cc3-4216-ad62-ab7bb671afe2">

I've installed wasmedge on windows using "winget install wasmedge"
and i downloaded WasmEdge-plugin-wasi_nn-ggml-0.13.5-darwin_x86_64.tar.gz and decompressed to C:\Program Files\WasmEdge\lib

<img width="317" alt="3de636ebc23ed4fd570f4703f8292a5" src="https://github.com/WasmEdge/WasmEdge/assets/63148804/f57ed0ba-f7fb-4f0f-96b3-a486d39964f1">

How can I run wasmedge on Windows in order to chat with LLM?

**Comment by hydai** [comment]
Hi @zhanghui-china 

Currently, we don't support the ggml plugin directly on Windows. If you would like to try it, please use the WSL/WSL2 environment instead. Thanks.

**Comment by zhanghui-china** [comment]
ok，3q。
