### ISSUE TITLE
bug: LlamaEdge  0.4.0 installation on Mac Intel model, missing file ' WasmEdge-plugin-wasmedge_rustls-0.13.5-darwin_x86_64.tar.gz'

### ISSUE THREAD

**Issue by hintcnuie** [WasmEdge/WasmEdge#3253]
### Summary

Env:
   MacOS  14.2.1,  CPU:  Intel Core i9

Issue Description:

when doing excise  following guild [LlamaEdge v0.4.0 新版发布，添加 RAG 和 Llava 支持](https://mp.weixin.qq.com/s/c2lmu7Zr231bgzWq8uTk7Q),  input the command:

`bash <(curl -sSfL 'https://raw.githubusercontent.com/LlamaEdge/LlamaEdge/main/run-llm.sh') --model llama-2-7b-chat `

Command output:

> 

[+] Downloading the selected model from https://huggingface.co/second-state/Llama-2-7B-Chat-GGUF/resolve/main/Llama-2-7b-chat-hf-Q5_K_M.gguf
################################################################################################################### 100.0%################################################################################################################### 100.0%
[+] Extracting prompt type: llama-2-chat 
[+] No reverse prompt required
[+] Install WasmEdge with wasi-nn_ggml plugin ...

Using Python: /usr/local/bin/python3 
INFO    - CUDA is only supported on Linux
INFO    - CUDA is only supported on Linux
WARNING - Experimental Option Selected: plugins
WARNING - plugins option may change later
INFO    - Compatible with current configuration
INFO    - Running Uninstaller
WARNING - SHELL variable not found. Using zsh as SHELL
INFO    - shell configuration updated
INFO    - Downloading WasmEdge
|============================================================|100.00 %INFO    - Downloaded
INFO    - Installing WasmEdge
INFO    - WasmEdge Successfully installed
INFO    - Downloading Plugin: wasi_nn-ggml
|============================================================|100.00 %INFO    - Downloaded
INFO    - Downloading Plugin: wasmedge_rustls
ERROR   - Download error from urllib: HTTP Error 404: Not Found
ERROR   - URL: https://github.com/WasmEdge/WasmEdge/releases/download/0.13.5/WasmEdge-plugin-wasmedge_rustls-0.13.5-darwin_x86_64.tar.gz
Failed to install WasmEdge

See the screenshot:
<img width="861" alt="Screenshot 2024-03-04 at 22 01 44" src="https://github.com/WasmEdge/WasmEdge/assets/4081542/73f90921-db49-4dda-8051-d8f559768a17">

Issue:
 
   There is no installation file for Mac Intel x86_64 model, but Mac Arm64 model.

Current file: [WasmEdge-plugin-wasmedge_rustls-0.13.5-darwin_arm64.tar.gz](https://github.com/WasmEdge/WasmEdge/releases/download/0.13.5/WasmEdge-plugin-wasmedge_rustls-0.13.5-darwin_arm64.tar.gz)
Missing:
 https://github.com/WasmEdge/WasmEdge/releases/download/0.13.5/WasmEdge-plugin-wasmedge_rustls-0.13.5-darwin_x86_64.tar.gz

### Current State

Installation LlamaEdge failed:
1. Download GGUF model successfully
2.Install WasmEdge rustls 1.3.5 failed on Mac Intel model.

### Expected State

Installation LlamaEdge successfully and start the Bot:
1. Download GGUF model successfully
2.Install WasmEdge rustls 1.3.5 successfully .

### Reproduction steps

Execute the command on Mac Intel  model.

`bash <(curl -sSfL 'https://raw.githubusercontent.com/LlamaEdge/LlamaEdge/main/run-llm.sh') --model llama-2-7b-chat `

### Screenshots

 
<img width="861" alt="Screenshot 2024-03-04 at 22 01 44" src="https://github.com/WasmEdge/WasmEdge/assets/4081542/b6150082-dba7-44e6-9f38-f8dbff8c9373">

### Any logs you want to share for showing the specific issue

[+] Downloading the selected model from https://huggingface.co/second-state/Llama-2-7B-Chat-GGUF/resolve/main/Llama-2-7b-chat-hf-Q5_K_M.gguf
################################################################################################################### 100.0%################################################################################################################### 100.0%
[+] Extracting prompt type: llama-2-chat 
[+] No reverse prompt required
[+] Install WasmEdge with wasi-nn_ggml plugin ...

Using Python: /usr/local/bin/python3 
INFO    - CUDA is only supported on Linux
INFO    - CUDA is only supported on Linux
WARNING - Experimental Option Selected: plugins
WARNING - plugins option may change later
INFO    - Compatible with current configuration
INFO    - Running Uninstaller
WARNING - SHELL variable not found. Using zsh as SHELL
INFO    - shell configuration updated
INFO    - Downloading WasmEdge
|============================================================|100.00 %INFO    - Downloaded
INFO    - Installing WasmEdge
INFO    - WasmEdge Successfully installed
INFO    - Downloading Plugin: wasi_nn-ggml
|============================================================|100.00 %INFO    - Downloaded
INFO    - Downloading Plugin: wasmedge_rustls
ERROR   - Download error from urllib: HTTP Error 404: Not Found
ERROR   - URL: https://github.com/WasmEdge/WasmEdge/releases/download/0.13.5/WasmEdge-plugin-wasmedge_rustls-0.13.5-darwin_x86_64.tar.gz
Failed to install WasmEdge

### Components

CLI

### WasmEdge Version or Commit you used

0.13.5

### Operating system information

MacOS 14.2.1, Intel CPU

### Hardware Architecture

X86_64

**Comment by hydai** [comment]
@hintcnuie 
Just updated the release assets, please try again.

**Comment by hintcnuie** [comment]
nice work! quick response! @hydai
