### ISSUE TITLE
bug: Randomly fail of Windows or Windows-MSVC test for LLVM

### ISSUE THREAD

**Issue by q82419** [WasmEdge/WasmEdge#3257]
### Summary

The CI test on Windows fails `wasmedgeLLVMCoreTests` randomly for both clang-cl and MSVC.
The `wasmedgeAPIAOTCoreTests` always passes, therefore it may occur on JIT, and this issue appeared after merging JIT supporting into master.

### Reproduction steps

Run on CI.

### Components

C SDK

### WasmEdge Version or Commit you used

master

### Operating system information

Windows 11

### Hardware Architecture

x86_64

**Comment by LFsWang** [comment]
I will do this

**Comment by LFsWang** [comment]
I found the error is `LLVM ERROR: IMAGE_REL_AMD64_ADDR32NB relocation requires an ordered section layout`. It seem a common issue from here https://github.com/llvm/llvm-project/issues/55386

```cpp
    case COFF::IMAGE_REL_AMD64_ADDR32NB: {
      // ADDR32NB requires an offset less than 2GB from 'ImageBase'.
      // The MemoryManager can make sure this is always true by forcing the
      // memory layout to be: CodeSection < ReadOnlySection < ReadWriteSection.
      const uint64_t ImageBase = getImageBase();
      if (Value < ImageBase || ((Value - ImageBase) > UINT32_MAX)) {
        llvm::errs() << "IMAGE_REL_AMD64_ADDR32NB relocation requires an"
                     << "ordered section layout.\n";
        write32BitOffset(Target, 0, 0);
      } else {
        write32BitOffset(Target, RE.Addend, Value - ImageBase);
      }
      break;
    }
```
