### ISSUE TITLE
question: <title>

### ISSUE THREAD

**Issue by hintcnuie** [WasmEdge/WasmEdge#3259]
### Summary

**Env**:
    Ubuntu 23.10 (GNU/Linux 6.5.0-1011-raspi aarch64)

**Issue**:
 
When Execute :

`wasmedge --dir .:. --nn-preload default:GGML:AUTO:llava-v1.6-vicuna-7b-Q5_K_M.gguf llama-api-server.wasm -p vicuna-llava -c 4096 --llava-mmproj llava-v1.6-vicuna-7b-mmproj-model-f16.gguf -m llava-v1.6-vicuna-7b`

Log:

[2024-03-06 12:09:13.770] [error] instantiation failed: module name conflict, Code: 0x60

[2024-03-06 12:09:13.770] [error] At AST node: module

 Screenshot:

![start_LlamaEdge_3](https://github.com/WasmEdge/WasmEdge/assets/4081542/31985f6b-129e-42a8-8094-ef3bfc851cdd)

 **Question**

The web ui works well, but the what's the error message in the log?

**Comment by alabulei1** [comment]
Hi @hintcnuie 

Thanks for reporting. The error message here are false-positive errors. They do not impact the program's functionality. We will try to remove these errors soon.

**Comment by hydai** [comment]
This is already listed on the troubleshooting: https://github.com/LlamaEdge/LlamaEdge?tab=readme-ov-file#troubleshooting.
So, I am closing this.
