### ISSUE TITLE
question: LLamaEdge installation failed in Raspberry Pi OS

### ISSUE THREAD

**Issue by hintcnuie** [WasmEdge/WasmEdge#3261]
### Summary

Hi,
  
   I am fan in the Raspberry Pi , since WasmEdge support both the Cloud and IoT devices for the Wasm, so I have a trial on my Raspberry Pi.  When I try to install LlamaEdge in my Raspberry 4b  device with 8G memory, it throws error like this:
```

curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- -v 0.13.5  --plugins wasi_nn-ggml wasmedge_rustls
Using Python: /usr/bin/python3 
INFO    - CUDA cannot be detected via nvcc
INFO    - CUDA 12.x cannot be detected via nvidia-smi
ERROR   - Exception on process - rc= 1 output= b'' command= ['cat /etc/lsb-release 2>/dev/null | grep RELEASE']
ERROR   - Exception on process - rc= 1 output= b'' command= ['cat /etc/lsb_release 2>/dev/null | grep DESCRIPTION']
WARNING - Experimental Option Selected: plugins
WARNING - plugins option may change later
INFO    - Compatible with current configuration
INFO    - Running Uninstaller
ls: cannot access '/home/pi/.wasmedge': No such file or directory
WARNING - SHELL variable not found. Using bash as SHELL
INFO    - shell configuration updated
INFO    - Downloading WasmEdge
|============================================================|100.00 %INFO    - Downloaded
INFO    - Installing WasmEdge
INFO    - WasmEdge Successfully installed
INFO    - Downloading Plugin: wasi_nn-ggml
|============================================================|100.00 %INFO    - Downloaded
ERROR   - Plugin not compatible: manylinux2014aarch64wasmedge_rustls
INFO    - Run:
source /home/pi/.bashrc
pi@raspberrypi:~ $ source ~/.bashrc
pi@raspberrypi:~ $ wasmedge -v
wasmedge version 0.13.5
pi@raspberrypi:~ $ 
```

Does LlamaEdge plan to support Raspberry Pi OS?  I tried to install LlamaEdge into Raspberry Pi with Ubuntu 23.10, it succeeded. But Raspberry Pi is failed,  any plan on it ?

**Comment by juntao** [comment]
Yeah, the Rustls plugin is supported but not pre-compiled on the RPi platform. That's causing the error you saw.

But, the Rustls is not required for most models. It is primarily required by multimodal models. You can safely do this if you do not need to run the Llava models.

```
curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- -v 0.13.5  --plugins wasi_nn-ggml
```

**Comment by hydai** [comment]
Hi @hintcnuie 
I just built a new asset for the manylinux2014 aarch64 platform.
You can download it manually via https://github.com/WasmEdge/WasmEdge/releases/download/0.13.5/WasmEdge-plugin-wasmedge_rustls-0.13.5-manylinux2014_aarch64.tar.gz

I created a PR #3262 to make the installer support.

**Comment by hydai** [comment]
This should be fixed, please feel free to reopen it if you still encounter some issues.

**Comment by hintcnuie** [comment]
sure, I'll install the new build on Raspberry pi after the LlamaEdge 's new release
