### ISSUE TITLE
feat: Support Qwen-VL model

### ISSUE THREAD

**Issue by thiner** [WasmEdge/WasmEdge#3264]
### Summary

Support Qwen-VL model.

### Details

Qwen-VL maybe the only VL model which supports Chinese OCR. Could you please support this model in WasmEdge? 

### Appendix

The model repo: https://huggingface.co/Qwen/Qwen-VL. They provide  4bit quantization officially: https://huggingface.co/Qwen/Qwen-VL-Chat-Int4

**Comment by hydai** [comment]
@apepkuss 
Do you know if we can convert the Qwem-VL into the GGUF format at this moment?

**Comment by apepkuss** [comment]
Not sure if the model could be converted to GGUF. According to the descriptions on `Qwen-VL` and `Qwen-VL-Chat`, we will try `Qwen-VL-Chat`, and list it as a candidate in LlamaEdge [#71](https://github.com/LlamaEdge/LlamaEdge/issues/71).

**Comment by thiner** [comment]
Yes, convert to GGUF seems not feasible currently. I think the only runnable quantized model is the GPTQ model provided officially.

**Comment by hydai** [comment]
Since this should be an upstream issue, I'm closing it. We are happy to support it if the GGUF provides fundamental support for this kind of model.
