### ISSUE TITLE
feat: support relaxed simd proposal

### ISSUE THREAD

**Issue by hydai** [WasmEdge/WasmEdge#3282]
### Summary

The relaxed SIMD proposal is now in Phase 4. We should consider to implement it.

Ref: https://github.com/WebAssembly/relaxed-simd

### Details

Implement the whole spec of the relaxed SIMD proposal, including the interpreter, AOT, and JIT.

**Comment by hydai** [comment]
@LFsWang Would you like to do this?

**Comment by LFsWang** [comment]
ok

**Comment by q82419** [comment]
Comment: 

according to the [binary format of instruction OpCodes](https://github.com/WebAssembly/relaxed-simd/blob/main/proposals/relaxed-simd/Overview.md#binary-format), relaxed-simd instructions need 3-byte length of OpCode: `0xFD`, `0x01`, `0x00` to `0x2F`.

As the current WasmEdge structure, we only supports 2-byte OpCode. Refactoring before implement this proposal is necessary.

**Comment by q82419** [comment]
> Comment:
> 
> according to the [binary format of instruction OpCodes](https://github.com/WebAssembly/relaxed-simd/blob/main/proposals/relaxed-simd/Overview.md#binary-format), relaxed-simd instructions need 3-byte length of OpCode: `0xFD`, `0x01`, `0x00` to `0x2F`.
> 
> As the current WasmEdge structure, we only supports 2-byte OpCode. Refactoring before implement this proposal is necessary.

Comment: This fixed in #3320 .
