### ISSUE TITLE
LFX Workspace: Integrate whisper.cpp as a new WASI-NN backend #3170

### ISSUE THREAD

**Issue by rum1887** [WasmEdge/WasmEdge#3287]
### Summary

WasmEdge supports PyTorch, TensorFlow Lite, llama.cpp, and more NN backend. Dealing with the voice-to-text is a big thing that we want to achieve. To make it possible, we would like to integrate [whisper.cpp](https://github.com/ggerganov/whisper.cpp), a port of OpenAI's Whisper model in C/C++ as a new [WASI-NN](https://github.com/second-state/wasmedge-wasi-nn) backend.

### Milestones 

Progress: [here](https://gist.github.com/rum1887/f18cabf083edf3aa9806835af7ff3fbb)

Week 1-2
- Review the llama.cpp project 

Week 2-4
- Complete the initial structure of the plugin
- Unit tests

Week 5-6
- Testing the plugin 
- Develop examples

Midterm PR: 

Week 7-8
- Develop more examples and enhance the plugin

Week 9-10
- Tutorials, Blogging and publicising

Week 11-12
- Enhancements 

Final Work Report:

**Comment by hydai** [comment]
> Review the llama.cpp project

llama.cpp and whisper.cpp is different. Please make sure you are working on the correct project.

**Comment by rum1887** [comment]
> > Review the llama.cpp project
> 
> llama.cpp and whisper.cpp is different. Please make sure you are working on the correct project.

yes, I included llama.cpp because whisper.cpp also uses the ggml backend.

**Comment by rum1887** [comment]
UPDATE [1]: 
Have added a basic file to load the model using default whisper parameters.

**Comment by hydai** [comment]
Please update the progress on this issue. Nothing has been updated in a long time. And the last update of your PR was two weeks ago.

**Comment by rum1887** [comment]
Update:
Working on a small example + unit case for loading with parse. Will update the pr by the end of this week and discuss over office hours

**Comment by hydai** [comment]
Hi @rum1887 
I am still not receiving your progress and any new commits inside your PR. Please update them in the recent days.

**Comment by hydai** [comment]
This is a final notification. We still haven't received your PR or updates for the final evaluation.

**Comment by hydai** [comment]
We tried to contact the mentee. However, we didn't receive any further updates from Discord, GitHub issue, and PR. I am closing this because the mentee is no longer working on it.
