### ISSUE TITLE
bug: execute a test case with illegal subopcode

### ISSUE THREAD

**Issue by erxiaozhou** [WasmEdge/WasmEdge#3327]
### Summary

WasmEdge executes a test case containing an invalid opcode 0xfc 0x476 without exception, indicating a possible bug in decoding.

### Current State

No exception

### Expected State

An exception indicating "unsupported opcode fc 476"

### Reproduction steps

1. Build with command: cmake  -DCMAKE_INSTALL_PREFIX="$install_dir" -DCMAKE_PREFIX_PATH="/usr/lib/llvm-12"  -DCMAKE_BUILD_TYPE=Release -DWASMEDGE_BUILD_AOT_RUNTIME=OFF     ..
2. Execute with command: wasmedge run <test_case> --invoke "to_test"
[memory.init_1309_458_17118908302125874.zip](https://github.com/WasmEdge/WasmEdge/files/14896084/memory.init_1309_458_17118908302125874.zip)

4. After execution, there is on exception, and that is unexpected.

### Screenshots

![DESCRIPTION](LINK.png)

### Components

CLI

### WasmEdge Version or Commit you used

a5e6f2d011776a1d997586b6e9af0ec01efa3642

### Operating system information

Ubuntu 20.04

### Hardware Architecture

x86_64

### Compiler flags and options

cmake  -DCMAKE_INSTALL_PREFIX="$install_dir" -DCMAKE_PREFIX_PATH="/usr/lib/llvm-12"  -DCMAKE_BUILD_TYPE=Release -DWASMEDGE_BUILD_AOT_RUNTIME=OFF     ..

**Comment by q82419** [comment]
Hi @erxiaozhou ,

This should be fixed in PR #3320 . Thanks!
