### ISSUE TITLE
The function type of wasi_snapshot_preview1::path_readlink is not correct

### ISSUE THREAD

**Issue by L-jasmine** [WasmEdge/WasmEdge#333]
I build a wasi-quickjs (use wasi-sdk 12). but when I run it on wasmEdge.
```
$ wasmedge qjs.wasm -h
[2021-08-02 01:22:46.053] [error] instantiation failed: incompatible import type, Code: 0x61
[2021-08-02 01:22:46.058] [error]     Mismatched function type. Expected: params{i32 , i32 , i32 , i32 , i32 , i32} returns{i32} , Got: params{i32 , i32 , i32 , i32 , i32} returns{i32}
[2021-08-02 01:22:46.060] [error]     When linking module: "wasi_snapshot_preview1" , function name: "path_readlink"
[2021-08-02 01:22:46.063] [error]     At AST node: import description
[2021-08-02 01:22:46.064] [error]     At AST node: import section
[2021-08-02 01:22:46.065] [error]     At AST node: module
```
on wasmer
```
$ wasmer run qjs.wasm -- -h
QuickJS version 1.0.0
usage: qjs [options] [file [args]]
-h  --help         list options
-e  --eval EXPR    evaluate EXPR
-i  --interactive  go to interactive mode
-m  --module       load as ES6 module (default=autodetect)
    --script       load as ES6 script (default=autodetect)
-I  --include file include an additional file
    --std          make 'std' and 'os' available to the loaded script
-T  --trace        trace memory allocation
-d  --dump         dump the memory usage stats
    --memory-limit n       limit the memory usage to 'n' bytes
    --unhandled-rejection  dump unhandled promise rejections
-q  --quit         just instantiate the interpreter and quit
```

**Comment by hydai** [comment]
@q82419  Could you check this?

`path_readlink` is a valid wasi function:
https://github.com/WebAssembly/WASI/blob/main/phases/snapshot/witx/wasi_snapshot_preview1.witx#L372

**Comment by hydai** [comment]
Seems like our `path_readlink` function has 6 args whereas WASI spec only has 5 args.

**Comment by L-jasmine** [comment]
> Seems like our `path_readlink` function has 6 args whereas WASI spec only has 5 args.

in my wasm path_readlink  is  (func (param i32 i32 i32 i32 i32 i32) (result i32))

**Comment by hydai** [comment]
@L-jasmine Could you provide the steps of creating the wasi-quickjs?

After checking the WASI-SDK, the `path_readlink` should have only 5 args:

https://github.com/WebAssembly/wasi-libc/blob/659ff414560721b1660a19685110e484a081c3d4/libc-bottom-half/sources/__wasilibc_real.c#L473-L488

**Comment by q82419** [comment]
@L-jasmine 
This function was not changed in the past 2 years. Can you provide your WASM file and the source? Thanks.

**Comment by L-jasmine** [comment]
wasmer: https://github.com/wasmerio/wasmer/blob/master/lib/wasi/src/syscalls/mod.rs#L1907-L1922
wasilibc: https://github.com/WebAssembly/wasi-libc/blob/659ff414560721b1660a19685110e484a081c3d4/libc-bottom-half/sources/__wasilibc_real.c#L473-L476

**Comment by q82419** [comment]
It seems like the `arg5` is defined in the result column.
https://github.com/WebAssembly/WASI/blob/main/phases/snapshot/witx/wasi_snapshot_preview1.witx#L380
We'll fix it and check for other functions. Thanks.

**Comment by hydai** [comment]
This should be fixed at this pre-release: https://github.com/WasmEdge/WasmEdge/releases/tag/0.8.2-rc.4
Please use the new binary and try again. Thanks for your report.

**Comment by L-jasmine** [comment]
> This should be fixed at this pre-release: https://github.com/WasmEdge/WasmEdge/releases/tag/0.8.2-rc.4
> Please use the new binary and try again. Thanks for your report.

it can run in 0.8.2-rc.4
