### ISSUE TITLE
bug: Unexpected error when running get-string example

### ISSUE THREAD

**Issue by PinappleUnderTheSea** [WasmEdge/WasmEdge#3332]
### Summary

I meet another error after setting WASMEDGE_PLUGIN_PATH when running examples\plugin\get-string\test.wasm

### Reproduction steps

1. Build with options  
```
cmake -Bbuild -DWASMEDGE_BUILD_EXAMPLE=ON .
cmake --build build
```

2. Execute with flags 
```
export WASMEDGE_PLUGIN_PATH=<My/Path>/WasmEdge/build/examples/plugin/get-string/
wat2wasm test.wat
wasmedge test.wasm
```
3.Get error
```
[2024-04-09 13:59:13.607] [error] instantiation failed: module name conflict, Code: 0x300
[2024-04-09 13:59:13.608] [error]     At AST node: module
```

No matter which line in lines 5~7 (import lines) I delete, the error always occurs.

### Components

CLI

### WasmEdge Version or Commit you used

Commit 8be2282

### Operating system information

Ubuntu 22.04 (wsl)

### Hardware Architecture

x86_64

**Comment by hydai** [comment]
@q82419 Please check if our previous bugfix is making this issue disappear.

**Comment by PinappleUnderTheSea** [comment]
> @q82419 Please check if our previous bugfix is making this issue disappear.

Commits after 8be22829393f8410880d441e7029d6f6f4d831c5 did not mention these files or cases

**Comment by q82419** [comment]
Hi @PinappleUnderTheSea ,

I tested on the latest master and it works well.

```bash
# At the path of WasmEdge
$ WASMEDGE_PLUGIN_PATH=build/examples/plugin/get-string/  ./build/tools/wasmedge/wasmedge --string="HELLO_WORLD" test.wasm
HELLO_WORLD
```

Please check again. Thanks!

**Comment by PinappleUnderTheSea** [comment]
> Hi @PinappleUnderTheSea ,
> 
> I tested on the latest master and it works well.
> 
> ```shell
> # At the path of WasmEdge
> $ WASMEDGE_PLUGIN_PATH=build/examples/plugin/get-string/  ./build/tools/wasmedge/wasmedge --string="HELLO_WORLD" test.wasm
> HELLO_WORLD
> ```
> 
> Please check again. Thanks!

sorry to trouble, I do not know WasmEdge well.  I tried:
```
 ./build/tools/wasmedge/wasmedge --string="HELLO_WORLD" test.wasm
```
but the terminal shows:
```
unknown option: string
```
Is there something I ignored?

**Comment by q82419** [comment]
Maybe you didn't build from master, or didn't assign the correct plug-in path.
The option is for the plug-in, the example `get-string` plug-in registered the option `string`, so that when loading the plug-in, this option can be accepted by the CLI.

**Comment by PinappleUnderTheSea** [comment]
> ```shell
> WASMEDGE_PLUGIN_PATH=build/examples/plugin/get-string/  ./build/tools/wasmedge/wasmedge --string="HELLO_WORLD" test.wasm
> ```

It works!!! Thanks a lot.
