### ISSUE TITLE
feat: extend `wasi_logging` plugin to support log file

### ISSUE THREAD

**Issue by apepkuss** [WasmEdge/WasmEdge#3399]
### Summary

The latest version of `wasi_logging` plugin provides support for "dumping" log data to `stdout` and `stderr`. There is also a solid requirement for saving log data to a log file.

### Details

It would be great if the following requirements can be satisfied:

1. Dump log data to a file with the extension `.log`. 
2. It would be better to allow user to specify the filename.
3. Use an environment variable, for example `WASM_LOG`, to specify the log level.

**Comment by q82419** [comment]
@apepkuss ,

1. Where's the example (rust) using this plugin?
2. I think the context (`"stderr"` or `"stdout"`) will be the filename or console to logging.
3. It's not necessary. The logging level is in the function parameter already.

**Comment by hydai** [comment]
https://github.com/WasmEdge/WasmEdge/tree/master/examples/plugin/wasi-logging

**Comment by apepkuss** [comment]
@q82419 For some scenarios, it's required to log the running data to a file instead of `stderr` and `stdout`. For example, dump the log info to `common.log` file so that another app or program analyzes the log info further.

**Comment by q82419** [comment]
> @q82419 For some scenarios, it's required to log the running data to a file instead of `stderr` and `stdout`. For example, dump the log info to `common.log` file so that another app or program analyzes the log info further.

Of course but I didn't challenge about that.

**Comment by q82419** [comment]
Implemented in #3416
