### ISSUE TITLE
bug: error wasm

### ISSUE THREAD

**Issue by Gins92** [WasmEdge/WasmEdge#3428]
### Summary

hello, i'm using mabook m1 and its look like this
<img width="500" alt="Screenshot 2024-05-26 at 13 24 42" src="https://github.com/WasmEdge/WasmEdge/assets/123242780/f1651ae6-7ef5-4254-892f-fe8b447c322f">

### Reproduction steps

1. Build with options '...'
2. Execute with flags '....'
3. Execute with inputs '....'
4. Get error

### Screenshots

![DESCRIPTION](LINK.png)

### Components

Others

### WasmEdge Version or Commit you used

 Darwin-arm64

### Operating system information

mac os sonoma

### Hardware Architecture

macbook m1 air

**Comment by hydai** [comment]
What's the permission for the `.profile`? Please show the output of running `ls -alh ~/.profile`

**Comment by Gins92** [comment]
its look like this, can you help me ?
[image: Screenshot 2024-05-26 at 21.23.39.png]

Pada Min, 26 Mei 2024 pukul 16.23 hydai ***@***.***> menulis:

**Comment by dannypsnl** [comment]
Please post text in code block, avoid image as possible is very helpful.

**Comment by Gins92** [comment]
***@***.*** ~ % ls -alh-/ .profile

ls: unrecognized option `--/'

usage: ls ***@***.***%,] [--color=when] [-D
format] [file ...]

***@***.*** ~ %



Pada Sen, 27 Mei 2024 pukul 08.20 Lîm Tsú-thuàn ***@***.***>
menulis:

**Comment by hydai** [comment]
Hi, @Gins92 
The command is `ls -alh ~/.profile`. It seems you are using an incorrect command.

**Comment by Gins92** [comment]
-rw-r--r--  1 root  staff    40B Sep  7  2023
/Users/ginanjarrindarto/.profile



Pada Sen, 27 Mei 2024 pukul 14.59 hydai ***@***.***> menulis:

**Comment by hydai** [comment]
It seems like the permission is incorrect. Could you please run `sudo chown $USER:staff ~/.profile` to modify the permission?
