### ISSUE TITLE
Feat: Support WASI-NN proposal

### ISSUE THREAD

**Issue by hydai** [WasmEdge/WasmEdge#343]
## Motivation

Machine Learning is a big topic nowadays. WasmEdge already provides [a set of TensorFlow host functions](https://github.com/second-state/wasmedge_tensorflow_interface) to enable the ML inference in WebAssembly. However, these TensorFlow host functions are defined by us and they are just a Wasm function binding from the [TensorFlow C API](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/c/c_api.h).

Here comes a standard, the [WASI-NN proposal](https://github.com/WebAssembly/wasi-nn) provides a new way to perform neural network inferencing by using a runtime-provided implementation that can leverage host native optimizations, CPU multi-threading, or powerful hardware devices such as GPUs or TPUs.

## Specification

1. Follow the Spec of [WASI-NN proposal](https://github.com/WebAssembly/wasi-nn/blob/main/phases/ephemeral/witx/wasi_ephemeral_nn.witx)
2. Implement related host functions in WasmEdge.
3. Add unit tests and coverage to these functions.
4. Take OpenVINO as WASI-NN backend and create a demo kit that is similar to [Wasmtime](https://bytecodealliance.org/articles/implementing-wasi-nn-in-wasmtime)

## Appendix
1. WasmEdge TensorFlow rust SDK: https://github.com/second-state/wasmedge_tensorflow_interface
2. WasmEdge TensorFlow host functions: https://github.com/second-state/WasmEdge-tensorflow
3. TensorFlow C API: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/c/c_api.h
4. WASI-NN proposal: https://github.com/WebAssembly/wasi-nn
5. Implementing-wasi-nn-in-wasmtime: https://bytecodealliance.org/articles/implementing-wasi-nn-in-wasmtime

**Comment by danijak** [comment]
Hi @hydai,
I am Javed Ali. I would like to apply for LFX mentorship and would like to work on it. I have experience with Machine learning & deep learning. I also have open-source experience through Google Summer of Code 2021 at NRNB. I would be really glad if you could guide me to relevant resources. Thanks

**Comment by hydai** [comment]
Hi @danijak  That's cool.

WASI-NN abstracts a high-level API to allow users to execute inference with a trained model in WebAssembly.
To achieve this mission, the following background information is very important:

1. Basic knowledge of [WebAssembly spec version1.1](https://webassembly.github.io/spec/core/binary/index.html)
2. How wasm interacts with host functions such as WASI (https://github.com/WebAssembly/WASI).
3. After you have the basic understanding of Wasm, you can find the [awesome demo which is presented by bytecodealliance](https://bytecodealliance.org/articles/implementing-wasi-nn-in-wasmtime). This will help you to know the relationship between Wasm, WASI-NN, and OpenVINO.

**Comment by danijak** [comment]
Hi @hydai,
yes sure, I will go through these documents & will write my proposal accordingly.
Thanks
