### ISSUE TITLE
feat: Deprecate 0.12.x and lower versions support in installer

### ISSUE THREAD

**Issue by q82419** [WasmEdge/WasmEdge#3432]
### Summary

Due to the official release for `0.14.0`, and `0.13.0` for updating plug-ins for a lone time, we can deprecate `0.12.x` and lower for installer now.

### Details

Besides `0.12.x` and lower versions, we can remove the extensions as well, such as `image extension`, and `tensorflow-tools`.
I think this can simplfy the installer implementation much more.

**Comment by SAtacker** [comment]
Do we get rid of tensorflow extensions of all kinds including deps and libraries instead of just tools ?

**Comment by q82419** [comment]
> Do we get rid of tensorflow extensions of all kinds including deps and libraries instead of just tools ?

We get rid of extensions (`image`, `tensorflow`, and `tensorflowlite`) and tools (`tensorflow-tools`).
But the plug-ins after `0.13.x` (`tensorflow plugin`) still needs their tensorflow-deps.
That is, you can remove the extensions installation from `github.com/second-state/WasmEdge-image`, `github.com/second-state/WasmEdge-tensorflow`, and `github.com/second-state/WasmEdge-tensorflow-tools` and the `-e` option.
It will be much more simpler because we only support plugins from now.
Thanks!
