### ISSUE TITLE
WasmEdge-plugin-wasmedge_rustls-0.14.0-darwin_arm64.tar.gz not found

### ISSUE THREAD

**Issue by pongponglau** [WasmEdge/WasmEdge#3437]
### Summary

When I run the command "curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- --plugins wasmedge_rustls wasi_nn-ggml", the following error is returned when installing the plugin wasmedge_rustls.

### Current State

INFO    - CUDA is only supported on Linux
INFO    - CUDA is only supported on Linux
WARNING - Experimental Option Selected: plugins
WARNING - plugins option may change later
INFO    - Compatible with current configuration
INFO    - Running Uninstaller
WARNING - SHELL variable not found. Using zsh as SHELL
INFO    - shell configuration updated
INFO    - Downloading WasmEdge
|============================================================|100.00 %INFO    - Downloaded
INFO    - Installing WasmEdge
INFO    - WasmEdge Successfully installed
INFO    - Downloading Plugin: wasmedge_rustls
ERROR   - Download error from urllib: HTTP Error 404: Not Found
ERROR   - URL: https://github.com/WasmEdge/WasmEdge/releases/download/0.14.0/WasmEdge-plugin-wasmedge_rustls-0.14.0-darwin_arm64.tar.gz

### Expected State

The plguin asset file is found at URL https://github.com/WasmEdge/WasmEdge/releases/download/0.14.0/WasmEdge-plugin-wasmedge_rustls-0.14.0-darwin_arm64.tar.gz

### Reproduction steps

Run the following command on Mac book Pro with M2 chip

curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- --plugins wasmedge_rustls wasi_nn-ggml

### Screenshots

<img width="569" alt="Screenshot 2024-05-29 at 1 04 01 AM" src="https://github.com/WasmEdge/WasmEdge/assets/17664137/06241659-b999-44c8-a6f7-777a248283d9">

### Components

Rust SDK

### WasmEdge Version or Commit you used

0.14

### Operating system information

macOS 13.2.1

### Hardware Architecture

Apple M2 arm64

**Comment by hydai** [comment]
Hi @pongponglau 
The Rustls plugin is no longer shipped with 0.14.0 because the rustls crate can be built into Wasm. If you still want to use the rustls plugin, please use WasmEdge 0.13.5 instead.

**Comment by pongponglau** [comment]
Yes, it is ok after using the old version. Thank you.

**Comment by hydai** [comment]
Thanks for the confirmation.
