### ISSUE TITLE
Feat: Support WASI-Crypto proposal

### ISSUE THREAD

**Issue by hydai** [WasmEdge/WasmEdge#345]
## Motivation

After WasmEdge provides an experimental API, WASI Socket, for supporting Berkeley Sockets API in Wasm. WasmEdge enabled a new way to open a new socket, listen to an existed socket, and send and receive data. Moreover, it will be nice if we can do more things in the related features such as SSL support.

To achieve this feature, one possible way is to compile the OpenSSL library to Wasm and link it as a library. However, the performance may be not good, because all the computation jobs are done at the wasm level. Here is an alternative way, instead of the previous one, we can wrap the OpenSSL library to Wasm external functions. For example, binding `ssl_connect` to `(import "openssl" "ssl_connect" ... )`. Unfortunately, this is not an easy way to do it.

To simply the workload, we decide to implement the WASI-crypto proposal first, and then use this proposal to make the above things happen.

## Specification

1. Follow the spec of [WASI-crypto proposal](https://github.com/WebAssembly/wasi-crypto).
2. Implement the interface functions in WasmEdge `wasi-crypto` modules.
3. Add unit tests and coverage to related functions.
4. Create a demo kit to show the WASI-Crypto features.

## Appendix
1. WASI-Crypto: https://github.com/WebAssembly/wasi-crypto
2. WASI-Crypto Rust SDK: https://github.com/WebAssembly/wasi-crypto/tree/main/implementations/bindings/rust

**Comment by feniljain** [comment]
Hey @hydai, the project seems fascinating, I have always been interested in learning more about wasm. I would like to work on the project, could you guide me on how I could get started?

**Comment by hydai** [comment]
Hi @feniljain, that's good to hear.

This feature contains the following background knowledge:

1. **WebAssembly Binary Format**. WasmEdge is followed the [Spec version 1.1](https://webassembly.github.io/spec/core/binary/index.html)
2. **WebAssembly Concept**. You can find some tutorials and examples on the [MDN Web Docs](https://developer.mozilla.org/en-US/docs/WebAssembly)
3. After you have the basic understanding of Wasm, then the next step is to study the spec definitions between [the current working version](https://github.com/WasmEdge/WasmEdge/tree/master/docs/witx) and [the WASI-Crypto version](https://github.com/WebAssembly/wasi-crypto). And try to integrate them into WasmEdge.
4. Finally, we can start to write the implementation and tests. The headers are under `include/host/wasi-crypto`. And the implementation codes are under `lib/host`.

This issue is a three months project which is on the [LFX Mentorship](https://github.com/cncf/mentoring/blob/main/lfx-mentorship/README.md). If you are interested, please apply on [this webpage](https://mentorship.lfx.linuxfoundation.org/project/cc32c302-a4dd-4113-b6d2-9294e20cceba) when the applications open.

**Comment by feniljain** [comment]
Thanks @hydai. I would like to apply for it, what all do I need to provide to improve my application, do I need to have previous contributions in this project, provide implementation proposal, etc.?

**Comment by hydai** [comment]
That will be awesome 😎 
No worries. You don't need to have any contributions in WasmEdge before.
However, we would like to know `why are you interested in WasmEdge` and `what experience and skills you have that are applicable to this mission`. These are very important to us ;-)

**Comment by spider0061** [comment]
@hydai Hello, I wanted to say that I am interested in this project as well. In past I have worked as a GSoC student developer in 2020 where I worked on building a configuration wizard. Also, I have been an Amazon intern where I worked on AWS, React and Java. Other than this I am a proficient developer in C/C++ and Python. Currently I am looking to learn more and grow my tech stack. I just wanted to know what can be the starting point to learn more about WASM. Thanks

**Comment by VedantParanjape** [comment]
Hi @hydai I am interested in this project. Can you specify the tech stack of this project. I am C/C++ developer.

**Comment by vedangj044** [comment]
Hello @hydai, I am a student from India. I would like to contribute to this project. I have previously contributed to open-source projects that use Rust. I have enjoyed rust very much and am excited about WASM.

**Comment by hangedfish** [comment]
I think IoT devices need a `mbedtls` backend because `OpenSSL` is not lightweight

**Comment by hydai** [comment]
I am not familiar with `mbedtls`. Does it have the functionality equivalent to `OpenSSL`?

**Comment by hangedfish** [comment]
> I am not familiar with `mbedtls`. Does it have the functionality equivalent to `OpenSSL`?

`mbedtls` provides a minimum viable implementation of the TLS 1.2/1.3 protocol. In other respects some `openssl` features are not supported, such as `pkcs#7`.

**Comment by q82419** [comment]
Merged: #1590 #1643
