### ISSUE TITLE
File allocation bug?

### ISSUE THREAD

**Issue by Userzxcvbvnm** [WasmEdge/WasmEdge#3475]
### Summary

Allocate the file size from a value which is larger the file size, WasmEdge fails to allocate. I'm not sure whether this is a bug.

### Current State

WasmEdge print:
```
Get file size: 0 bytes.
Enter function fd_allocate_00072_gxX49
Space allocation in file successful.
Get file size: 0 bytes.
```

### Expected State

Get file size: 0 bytes.
Enter function fd_allocate_00072_gxX49
Space allocation in file successful.
Get file size: 1 bytes.

### Reproduction steps

The test case is :
```

#include <stdio.h>
#include <stdlib.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>

void print_file_size(int fd){
    struct stat st;
    if (fstat(fd, &st) == -1) {
        printf("Get file size failed.\n");
    } else {
        printf("Get file size: %ld bytes.\n", st.st_size);
    }
}


int get_fd(const char *filename, int flags) {
    int fd = open(filename, flags);
    
    if (fd == -1) {
        printf("Get file descriptor of file %s failed!\n", filename);
        return -1;
    } else {
        printf("Get file descriptor of file %s succeed!\n", filename);
        return fd;
    }
}

void closebyfd(int fd) {
    if (close(fd) == -1) {
        printf("Close the file by descriptor failed!\n");
    }
}

void fd_allocate_00072_gxX49(int fd) {
    printf("Enter function fd_allocate_00072_gxX49\n");
    
    int result = posix_fallocate(fd, 1, 0);

    if (result == 0) {
        printf("Space allocation in file successful.\n");
    } else {
        printf("Error allocating space in file.\n");
    }
}

int main() {
    int fd = get_fd("subdir_1/subfile_2", O_WRONLY | O_TRUNC);
    if (fd == -1) {
        return -1; // Return from main if get_fd failed
    }

    print_file_size(fd);
    fd_allocate_00072_gxX49(fd);
    print_file_size(fd);


    closebyfd(fd);

    return 0;
}

```

Steps to reproduce:
(1)compile to wasm:`./wasi-sdk-21.0/bin/clang --target=wasm32-unkown-wasi --sysroot=./wasi-sdk-21.0/share/wasi-sysroot test.c -o test.wasm`

(2)Running wasm:
(Before run the Wasm file, subdir_1/subfile_2 exists.)
wasmedge --dir=. test.wasm

### Screenshots

![DESCRIPTION](LINK.png)

### Components

CLI

### WasmEdge Version or Commit you used

0.13.5 and 0.13.3

### Operating system information

Ubuntu 20.04

### Hardware Architecture

x86_64

**Comment by Daksh-10** [comment]
**Solved**
Hello @Userzxcvbvnm , I think the problem was the function 
```c
int posix_fallocate(int fd, off_t offset, off_t len);
``` 

So, the offset provide in the above code was one and the allocated memory was zero, so I just interchanged them and allocated 1 byte of memory to the file.

```c
int result = posix_fallocate(fd, 0, 1);
int result = posix_fallocate(fd, 0, 5);
``` 
![image](https://github.com/user-attachments/assets/95c200a3-da91-46cf-b02a-3c5c620629bf)
![image](https://github.com/user-attachments/assets/6f994312-a8fd-4829-8bfd-66d9484eefaf)

**Comment by dannypsnl** [comment]
https://www.man7.org/linux/man-pages/man3/posix_fallocate.3.html

Reasonable, thanks!
