### ISSUE TITLE
bug: fails to raise an exception on a invalid test case

### ISSUE THREAD

**Issue by erxiaozhou** [WasmEdge/WasmEdge#3481]
### Summary

The test case is invalid.

The output of the command `wasm-validate --enable-all <test_case>`
is 
```
<test_case>:00000b3: error: alignment must be equal to natural alignment (4)
``` 

### Current State

No exception

### Expected State

Raise an exception.

### Reproduction steps

1. Build with command: cmake  -DCMAKE_INSTALL_PREFIX="$install_dir" -DCMAKE_PREFIX_PATH="/usr/lib/llvm-12"  -DCMAKE_BUILD_TYPE=Release -DWASMEDGE_BUILD_AOT_RUNTIME=OFF     ..
2. Execute with command: wasmedge run --reactor <test_case> "to_test"
[i32.eqz_7BBBBPBBPBBPBBB_615_17181389666367977.zip](https://github.com/user-attachments/files/15859272/i32.eqz_7BBBBPBBPBBPBBB_615_17181389666367977.zip)

### Screenshots

![DESCRIPTION](LINK.png)

### Components

CLI

### WasmEdge Version or Commit you used

813c200119dad7ebd5ea2ce462bc61549ecab115

### Operating system information

Ubuntu 20.04

### Hardware Architecture

x86_64

**Comment by guojidan** [comment]
please asign to me @hydai 😃

**Comment by hydai** [comment]
It's yours :-).

**Comment by guojidan** [comment]
The memory alignment of `Atomic instruction` must be equal to the natural, so we need to judge atomic instructions and non-atomic instructions respectively.

**Comment by erxiaozhou** [comment]
@guojidan Hi, when I try the attached test case on version 47b4aabe6bbcc9fd665757bcbcff4c9e3be3bbf7, the WasmEdge (interpreter mode) does not raise an exception as well. Is it correct?

**Comment by guojidan** [comment]
> [@guojidan](https://github.com/guojidan) Hi, when I try the attached test case on version [47b4aab](https://github.com/WasmEdge/WasmEdge/commit/47b4aabe6bbcc9fd665757bcbcff4c9e3be3bbf7), the WasmEdge (interpreter mode) does not raise an exception as well. Is it correct?

Some atomic instructions were omitted in the previous repair PR. The fix PR was committed [PR](https://github.com/WasmEdge/WasmEdge/pull/3987).

**Comment by erxiaozhou** [comment]
> > [@guojidan](https://github.com/guojidan) Hi, when I try the attached test case on version [47b4aab](https://github.com/WasmEdge/WasmEdge/commit/47b4aabe6bbcc9fd665757bcbcff4c9e3be3bbf7), the WasmEdge (interpreter mode) does not raise an exception as well. Is it correct?
> 
> Some atomic instructions were omitted in the previous repair PR. The fix PR was committed [PR](https://github.com/WasmEdge/WasmEdge/pull/3987).

Thank you four your reply!
