### ISSUE TITLE
bug: raise exception on a valid test case

### ISSUE THREAD

**Issue by erxiaozhou** [WasmEdge/WasmEdge#3482]
### Summary

The test case is valid, while WasmEdge raise an exception indicating that "section size mismatch".
Though the test case requires multi-memory feature, it is well-formatted.

### Current State

An exception indicating that "section size mismatch".

### Expected State

If the multi-memory feature is disabled, there should be no exception. Otherwise, it seems to lead to an exception indicating "alignment is too large".

### Reproduction steps

1. Build with command: cmake  -DCMAKE_INSTALL_PREFIX="$install_dir" -DCMAKE_PREFIX_PATH="/usr/lib/llvm-12"  -DCMAKE_BUILD_TYPE=Release -DWASMEDGE_BUILD_AOT_RUNTIME=OFF     ..
2. Execute with command: wasmedge run --reactor <test_case> "to_test"
[i64.lt_u_65PPPPMBBBBBBBBBBBB_0_1718153639188319.zip](https://github.com/user-attachments/files/15859465/i64.lt_u_65PPPPMBBBBBBBBBBBB_0_1718153639188319.zip)

### Screenshots

![DESCRIPTION](LINK.png)

### Components

CLI

### WasmEdge Version or Commit you used

813c200119dad7ebd5ea2ce462bc61549ecab115

### Operating system information

Ubuntu 20.04

### Hardware Architecture

x86_64

**Comment by guojidan** [comment]
hi, I'm very interested in this project and I'm planning to start my work from this issue, so please assign to me 😄

**Comment by hydai** [comment]
It's yours now :-)
