### ISSUE TITLE
LFX Workspace: Support piper as a new backend of the WASI-NN WasmEdge plugin

### ISSUE THREAD

**Issue by PeterD1524** [WasmEdge/WasmEdge#3483]
### Summary

# Motivation

WasmEdge supports PyTorch, TensorFlow Lite, llama.cpp, and more NN backend. Dealing with the text-to-voice is a big thing that we want to achieve. To make it possible, we would like to integrate [piper](https://github.com/rhasspy/piper), A fast, local neural text-to-speech system in C++ as a new [WASI-NN](https://github.com/second-state/wasmedge-wasi-nn) backend.

# Details

Expected Outcome: A new plugin provides a piper [WASI-NN](https://github.com/second-state/wasmedge-wasi-nn) backend, a test suite for validating the plugin, documents, and examples for explaining how to use the plugin.

# Milestones

- [ ] (M1) [1 weeks] Piper plugin, Plans, Research
  - Improve draft work at https://github.com/PeterD1524/WasmEdge/tree/wasi_nn_piper
  - Create pull request for [wasmedge-wasi-nn](https://github.com/second-state/wasmedge-wasi-nn) to support the new Piper backend
  - Get familiar with WasmEdge development workflow
- [ ] (M2) [1 weeks] test suite, documents, and examples

### Appendix

- https://github.com/WasmEdge/WasmEdge/issues/3381
- https://github.com/PeterD1524/WasmEdge/tree/wasi_nn_piper

**Comment by PeterD1524** [comment]
PR (WIP): https://github.com/WasmEdge/WasmEdge/pull/3499

**Comment by PeterD1524** [comment]
PR for [WASI-NN Rust SDK](https://github.com/second-state/wasmedge-wasi-nn/tree/ggml/rust): https://github.com/second-state/wasmedge-wasi-nn/pull/15

**Comment by hydai** [comment]
Thanks @PeterD1524 
@dm4 is going to review the wasmedge-wasi-nn PR.

Is #3499 ready to review, or is it still in the WIP stage?

**Comment by PeterD1524** [comment]
#3499 is it still in the WIP stage.

**Comment by PeterD1524** [comment]
Week 1 Summary

- Created main PR
  - https://github.com/WasmEdge/WasmEdge/pull/3499
  - added backend structure
- Created PR for wasmedge-wasi-nn to support the new Piper backend
  - https://github.com/second-state/wasmedge-wasi-nn/pull/15

**Comment by PeterD1524** [comment]
Week 2 Summary

- Main PR
  - Fixed minor stuff
  - Added tests and build workflow
- Created PR in [second-state/WasmEdge-WASINN-examples](https://github.com/second-state/WasmEdge-WASINN-examples) for example usage
  - https://github.com/second-state/WasmEdge-WASINN-examples/pull/145
- Created PR in [WasmEdge/docs](https://github.com/WasmEdge/docs)
  - https://github.com/WasmEdge/docs/pull/238

**Comment by PeterD1524** [comment]
Week 3 Summary
- Main PR
  - Fixed minor stuff
- Fixed some docs in [WasmEdge/docs](https://github.com/WasmEdge/docs)
  - https://github.com/WasmEdge/docs/pull/239

**Comment by PeterD1524** [comment]
Week 4 Summary
- main PR
  - Improved code for input validation
  - Resolved build issue
  - Merged

**Comment by PeterD1524** [comment]
I just realized that Piper just downloads `libonnxruntime.so` and links to it, so `libwasmedgePluginWasiNN.so` doesn't work on its own. It looks like there is no easy option to toggle this behavior.

**Comment by hydai** [comment]
Should we follow the same procedure for downloading `libonnxruntime.so` for users? How hard will it be to ask users to install it themselves?

**Comment by PeterD1524** [comment]
> Should we follow the same procedure for downloading `libonnxruntime.so` for users?

Can we ship `libonnxruntime.so` with `libwasmedgePluginWasiNN.so` together in the `WasmEdge-plugin-wasi_nn-piper.tar.gz`. I don't know if that is a good idea.

> How hard will it be to ask users to install it themselves?

On Ubuntu it probably looks like:
```
curl -LO https://github.com/microsoft/onnxruntime/releases/download/v1.14.1/onnxruntime-linux-x64-1.14.1.tgz
tar zxf onnxruntime-linux-x64-1.14.1.tgz
mv onnxruntime-linux-x64-1.14.1/include/* /usr/local/include/
mv onnxruntime-linux-x64-1.14.1/lib/* /usr/local/lib/
rm -rf onnxruntime-linux-x64-1.14.1.tgz onnxruntime-linux-x64-1.14.1
```

**Comment by hydai** [comment]
> Can we ship `libonnxruntime.so` with `libwasmedgePluginWasiNN.so` together in the `WasmEdge-plugin-wasi_nn-piper.tar.gz`. I don't know if that is a good idea.

It's definitely not ;-)
Let's ask users to download and install the onnx runtime. Maybe we just need to mention the official website.

**Comment by PeterD1524** [comment]
@hydai
I opened a PR to fix the dependency problem: https://github.com/WasmEdge/WasmEdge/pull/3583

**Comment by PeterD1524** [comment]
> Hi @PeterD1524
> 
> I would like to have the pre-built Piper plugin in the release assets for the other platforms. Currently, we only have Ubuntu22.04 assets. Could you please also enable the manylinux builds? Here are some related workflow files:
> 
> 1. https://github.com/WasmEdge/WasmEdge/blob/master/.github/workflows/matrix-extensions.json
> 2. https://github.com/WasmEdge/WasmEdge/blob/master/.github/workflows/reusable-build-extensions-on-manylinux.yml
> 3. https://github.com/WasmEdge/WasmEdge/blob/master/.github/workflows/reusable-build-extensions.yml

I will take a look. We don't need enable manylinux2014, right? I saw it will be deprecated ([#3542](https://www.github.com/WasmEdge/WasmEdge/issues/3542), [#3571](https://www.github.com/WasmEdge/WasmEdge/pull/3571)).

**Comment by hydai** [comment]
We don't need to care about manylinux2014, which is CentOS 7, an EOL and legacy OS. Just focus on the manylinux2_28, which is AlmaLinux 8.
The Piper CI issue is here: #3576

**Comment by PeterD1524** [comment]
I opened a PR for this: https://github.com/WasmEdge/WasmEdge/pull/3614

I have some questions:
1. Currently I install the onnxruntime dependency for piper in [.github/workflows/reusable-build-extensions-on-manylinux.yml](https://github.com/WasmEdge/WasmEdge/blob/master/.github/workflows/reusable-build-extensions-on-manylinux.yml). I also saw that pytorch is installed in [utils/docker/Dockerfile.manylinux_2_28-plugins-deps](https://github.com/WasmEdge/WasmEdge/blob/master/utils/docker/Dockerfile.manylinux_2_28-plugins-deps), but I guess this will require rebuilding and pushing the docker image. Where should I put it?
2. Currently I only enable x86_64 for manylinux2_28. Do we need aarch64 too? I'm still figuring out how to run github actions with aarch64 images to test it.

**Comment by hydai** [comment]
> 1. Currently I install the onnxruntime dependency for piper in [.github/workflows/reusable-build-extensions-on-manylinux.yml](https://github.com/WasmEdge/WasmEdge/blob/master/.github/workflows/reusable-build-extensions-on-manylinux.yml). I also saw that pytorch is installed in [utils/docker/Dockerfile.manylinux_2_28-plugins-deps](https://github.com/WasmEdge/WasmEdge/blob/master/utils/docker/Dockerfile.manylinux_2_28-plugins-deps), but I guess this will require rebuilding and pushing the docker image. Where should I put it?

We will use the workflows to install a new dependency and verify the behavior to check if it meets our requirements. If so, we will add it to the dockerfile here[1].

> 2. Currently I only enable x86_64 for manylinux2_28. Do we need aarch64 too? I'm still figuring out how to run github actions with aarch64 images to test it.

You just need to add the same entry into the aarch64 matrix. Our CI runners will take care of it. You don't need to specify the GitHub action runners for it.

[1]: https://github.com/WasmEdge/WasmEdge/tree/master/utils/docker

**Comment by PeterD1524** [comment]
> We will use the workflows to install a new dependency and verify the behavior to check if it meets our requirements. If so, we will add it to the dockerfile here[1](https://github.com/WasmEdge/WasmEdge/tree/master/utils/docker).

ok

> You just need to add the same entry into the aarch64 matrix. Our CI runners will take care of it. You don't need to specify the GitHub action runners for it.

Sorry, I meant to run it locally or on my forked repo. I managed to build it locally in wasmedge/wasmedge:manylinux_2_28_aarch64-plugins-deps. Anyway, I added the aarch64 entry.

**Comment by hydai** [comment]
If you want to, the only way is to use cross-compilation. GitHub doesn't provide a free arm64 machine for the CI runners.

**Comment by PeterD1524** [comment]
Do we want ubuntu20.04 release assets for Piper plugin? If I understand correctly, the ubuntu22.04 assets we have now are for testing only.

**Comment by hydai** [comment]
Yes. Please.
We would like to maintain manylinux228 and ubuntu 20.04 at the current stage.

**Comment by PeterD1524** [comment]
PR: https://github.com/WasmEdge/WasmEdge/pull/3633

**Comment by hydai** [comment]
PR merged, we are going to re-run the release process for rc.1 to check the results.

**Comment by hydai** [comment]
Hi @PeterD1524 
We found that piper CI will fail on manylinux_2_28, see: https://github.com/WasmEdge/WasmEdge/actions/runs/10354310449/job/28666897830?pr=3645
It's likely related to the recent upgrade of the fmt library (10 -> 11). Could you please help check on this?

**Comment by PeterD1524** [comment]
Hi, I opened a PR to fix this: https://github.com/WasmEdge/WasmEdge/pull/3646.

**Comment by hydai** [comment]
Everything related to the Piper backend should be done. @PeterD1524, is it okay to close this issue and mark it as done now?
