### ISSUE TITLE
feat: Moving WASI-logging from plugin into wasmedge built-in feature

### ISSUE THREAD

**Issue by hydai** [WasmEdge/WasmEdge#3485]
### Summary

WASI logging provides an excellent way to handle the logging system. We ship this proposal via a standalone plugin, so users will need to install it separately. This causes a redundant step to do an extra installation.
Instead of a plugin, we would like to migrate it as a built-in wasmedge feature just like the WASI spec did.

### Details

1. Create a new folder, `wasi-logging,` under the `host` directory.
2. Move the `wasi-logging` related implementation from `plugins` to the above folder.
3. Clean up all documents of the `wasi-logging` plugin.

**Comment by lazyperson1020** [comment]
@hydai Can you assign this issue to me? I am trying to work on it.

**Comment by hydai** [comment]
Hi @lazyperson1020 
Thanks for your interest. However, I am working on it now.

**Comment by hydai** [comment]
Fixed by #3617
