### ISSUE TITLE
feat: Bump OpenVINO to 2024.2.0

### ISSUE THREAD

**Issue by hydai** [WasmEdge/WasmEdge#3489]
### Summary

Intel just released [OpenVINO 2024.2.0](https://github.com/openvinotoolkit/openvino/releases/tag/2024.2.0), which supports:
1. LLaMA3 optimization
2. Phi-3

It's awesome for our WASI-NN use cases; I think upgrading to this version may help us extend more examples for the WASI-NN OpenVINO backend and leverage the maximum power of the Intel hardware.

### Details

1. Upgrade the WASI-NN OpenVINO backend to 2024.2.0
2. The OpenVINO APIs may change because the previous version uses the 2023 edition.
3. Ensure the tests and workflows pass.

**Comment by PrabhuUdurg** [comment]
Hi! I am new here, can I be assigned to this issue? Can you please also share developer docs if you have any, thanks!!

**Comment by hydai** [comment]
Hi @PrabhuUdurg 
Here is the building guide for the previous OpenVINO plugin: https://wasmedge.org/docs/contribute/source/plugin/wasi_nn#build-wasmedge-with-wasi-nn-openvino-backend
You need to bump the OpenVINO dependency first and then check if there is anything that needs to be fixed after the upgrade.

**Comment by PrabhuUdurg** [comment]
Hi @hudai I changed version, but how I can make tests, should I use this ones https://wasmedge.org/docs/contribute/source/os/linux#run-tests ?

**Comment by hydai** [comment]
> Hi @hudai I changed version, but how I can make tests, should I use this ones https://wasmedge.org/docs/contribute/source/os/linux#run-tests ?

You will find that there are WASI-NN OpenVINO tests when running the test.

**Comment by PrabhuUdurg** [comment]
Let me know if everything is alright, since i am new here)
