### ISSUE TITLE
Feat: Create a checker/helper tool to sync the `errcode.h` and `wasmedge.h.in`

### ISSUE THREAD

**Issue by hydai** [WasmEdge/WasmEdge#349]
## Motivation

See the discussion in #341 , https://github.com/WasmEdge/WasmEdge/pull/341#discussion_r685191280

Currently, the `wasmedge.h.in` is synced with `errcode.h` manually. This is not good, we should avoid relying on human to sync code.

## Expected

Create a checker, a helper tool, or split the `wasmedge.h.in` to multiple and sync from `errcode.h` directly.

**Comment by chenyukang** [comment]
I have found some inconsistencies between `wasmedge.h.in` and the headers files,  usually we missed some enum values in `wasmedge.h.in`.
I would like to write a script to detect all the issues. 
We can run this script in CI (or attached to local git hooks...)
Which programming language do you think is more acceptable for you? @hydai

**Comment by hydai** [comment]
To reduce the dependencies, I prefer to use script language such as shell script(built-in) or python(easy to get from apt/yum).

**Comment by q82419** [comment]
Maybe we can use the cmake `configure_file` to config the `wasmedge.h.in` and the `errorcode.h` automatically?

**Comment by q82419** [comment]
Similarly, the `enum`s such as `WasmEdge_Proposal`, `WasmEdge_HostRegistration`, `WasmEdge_CompilerOptimizationLevel`, `WasmEdge_ValType`, `WasmEdge_RefType`, and `WasmEdge_Mutability` should be automatically synchronized.

**Comment by chenyukang** [comment]
> Maybe we can use the cmake `configure_file` to config the `wasmedge.h.in` and the `errorcode.h` automatically?

I'm not familiar with cmake `configure_file`, after some googling, I think it's mainly used to generate variable things?
In this case, we need to generate snippets from Enums, according to a rule:

```
enum EnumName { 
      Value1 ,
      Value2 ,
      ....
}
```

to

```
enum WasmEdge_EnumName {
        WasmEdge_Value1,
        WasmEdge_Value2,
        ....
}
```

**Comment by q82419** [comment]
I think it's better to make enum headers to support both C and C++.
After then, a script in CI for checking the synchronization between the C and C++ enums is necessary.
@chenyukang  would you modify your PR and help for this after the [PR298](https://github.com/WasmEdge/WasmEdge/pull/298) being merged?
Thanks.

**Comment by chenyukang** [comment]
> I think it's better to make enum headers to support both C and C++.
> After then, a script in CI for checking the synchronization between the C and C++ enums is necessary.
> @chenyukang would you modify your PR and help for this after the [PR298](https://github.com/WasmEdge/WasmEdge/pull/298) being merged?
> Thanks.

Ok
