### ISSUE TITLE
Fail to read the source file a softlink file.

### ISSUE THREAD

**Issue by Userzxcvbvnm** [WasmEdge/WasmEdge#3493]
### Summary

WasmEdge fails to read the source file of a softlink file.

### Current State

WasmEdge prints:
```
Enter function path_readlink_00001_xYCLW
readlinkat
```

### Expected State

prints:
```
Enter function path_readlink_00001_xYCLW
Symbolic link contents: subdir_1/subdir_1/subfile_2
```

This is what wasmtime  and WAMR do.

### Reproduction steps

The test case is :
```

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <fcntl.h>

int get_fd(const char *filename, int flags) {
    int fd = open(filename, flags);
    
    if (fd == -1) {
        printf("Get file descriptor of file %s failed!\n", filename);
        return -1;
    } else {
        printf("Get file descriptor of file %s succeed!\n", filename);
        return fd;
    }
}

void closebyfd(int fd) {
    if (close(fd) == -1) {
        printf("Close the file %d by descriptor failed!\n", fd);
    }
}

void path_readlink_00001_xYCLW() {
    printf("Enter function path_readlink_00001_xYCLW\n");

    char link[100];
    ssize_t numBytes = readlinkat(AT_FDCWD, "softfile_1", link, 100);

    if (numBytes == -1) {
        printf("readlinkat\n");
    } else {
        link[numBytes] = '\0';
        printf("Symbolic link contents: %s\n", link);
    }
}

int main() {
    

    path_readlink_00001_xYCLW();

    

    return 0;
}


```

Steps to reproduce:
(1)compile to wasm:`./wasi-sdk-21.0/bin/clang --target=wasm32-unkown-wasi --sysroot=./wasi-sdk-21.0/share/wasi-sysroot test.c -o test.wasm`

(2)Running wasm:
(Before run the Wasm file, softfile_1 exists and is a softlink file points to subdir_1/subdir_1/subfile_2.)
wasmedge --dir=. test.wasm

### Screenshots

![DESCRIPTION](LINK.png)

### Components

CLI

### WasmEdge Version or Commit you used

0.13.5 and 0.13.3

### Operating system information

Ubuntu 20.04

### Hardware Architecture

x86_64

**Comment by Daksh-10** [comment]
**ISSUE**
I tried recreating the above issue, I used emscripten to compile and then executed the wasm in web and with wasmtime and wasmedge.

1. Web - It printed readlinkat .
![Screenshot from 2024-08-04 02-16-07](https://github.com/user-attachments/assets/3493a6e6-ef76-425e-9ab3-a4d0e4316e3b) 

2. Wasmedge - It throws error (__syscall_readlinkat, i.e. the system call was not provide to the env, @Userzxcvbvnm how did you compiled the file with emscripten or WASI)
![Screenshot from 2024-08-04 02-16-54](https://github.com/user-attachments/assets/599e8a3c-cb0b-459d-8ca7-a5988673320d)

3. Wasmtime - It also throws similar error 
![Screenshot from 2024-08-04 02-21-17](https://github.com/user-attachments/assets/70e1c145-7837-4084-9307-9b56e6e91c17)

**Comment by Userzxcvbvnm** [comment]
(Before run the Wasm file, softfile_1 exists and is a softlink file points to subdir_1/subdir_1/subfile_2.)
wasmedge --dir=. test.wasm

And the command if wasmtime should be `wasmtime run --dir=. test.wasm`

**Comment by Daksh-10** [comment]
**PROBLEM**
I tried to compile with above command, but I compiled it with **wasi-sdk-24.0**.
It is showing the same error which you proposed!

With Wasmedge
![image](https://github.com/user-attachments/assets/f0c9aa79-0979-4c20-8799-e55f52697da5)
With Wasmtime
![image](https://github.com/user-attachments/assets/3e96548f-04be-4bf5-9f74-11a4c47499c8)

I don't clearly, know but I think the issue is with how the wasmedge, access paths to directories and files.

This was my folder structure :-
`main/
├── test.c
├── softlink_1 -> test/targetfile.txt
└── test/
    └── targetfile.txt
`

**Comment by Userzxcvbvnm** [comment]
> wasmtime run --dir=. test.wasm
the wasmtime command should be `wasmtime run --dir=. test.wasm`, rather than `wasmtime test.wasm`

**Comment by Userzxcvbvnm** [comment]
> **PROBLEM** I tried to compile with above command, but I compiled it with **wasi-sdk-24.0**. It is showing the same error which you proposed!
> 
> With Wasmedge ![image](https://private-user-images.githubusercontent.com/114306188/355242780-f0c9aa79-0979-4c20-8799-e55f52697da5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwOTI4OTEsIm5iZiI6MTcyMzA5MjU5MSwicGF0aCI6Ii8xMTQzMDYxODgvMzU1MjQyNzgwLWYwYzlhYTc5LTA5NzktNGMyMC04Nzk5LWU1NWY1MjY5N2RhNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQwNDQ5NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01Nzk2ZWZkMzNiZjAwNDI5NWJhMmVmNWI1ZjUzYjBiNDM4NGI1MzIxOGNlN2MwMDUxN2NhMWY2MWQ1OTI3MzJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Mu8Gp9iYldQe6TROYHhMv68sd-ZelqjoB2amTOZdHWY) With Wasmtime ![image](https://private-user-images.githubusercontent.com/114306188/355242832-3e96548f-04be-4bf5-9f74-11a4c47499c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwOTI4OTEsIm5iZiI6MTcyMzA5MjU5MSwicGF0aCI6Ii8xMTQzMDYxODgvMzU1MjQyODMyLTNlOTY1NDhmLTA0YmUtNGJmNS05Zjc0LTExYTRjNDc0OTljOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQwNDQ5NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNjU2MWFhNzQwZTBlNjFhMDFiYmYxNDBjZmUxOWYyNWFiMTY1ZjE4OTZlZjczOThiOTdjNTRmNWEyYjQ3OGZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hiJBBng46Vy97y_IXYb0jMmWZ4OlQXB58terSfiwcnE)
> 
> I don't clearly, know but I think the issue is with how the wasmedge, access paths to directories and files.
> 
> This was my folder structure :- main/ ├── test.c ├── softlink_1 -> test/targetfile.txt └── test/ └── targetfile.txt
> 
> #3584

the wasmtime command should be `wasmtime run --dir=. test.wasm`, rather than `wasmtime test.wasm`

**Comment by Userzxcvbvnm** [comment]
Using wasi-sdk21 or wasi-sdk24, We got the same result:
(1)wasmtime
command:'wasmtime run --dir=. test.wasm' (Should use --dir=. to set the pre-opened directory for wasmtime, rather than using 'wasmtime test.wasm')
result:
```
Enter function path_readlink_00001_xYCLW
Symbolic link contents: hello.txt
```

(2)wasmedge
command:'wasmedge --dir=. test.wasm'
result:
 ```
Enter function path_readlink_00001_xYCLW
readlinkat
```

The directory is:
Data/
├── test.c
├── softlink_1 -> subdir_1/subdir_1/subfile_2
└── test.wasm
└── subdir_1
            └──subdir_1
                       └──subfile_2

**Comment by himanshisrestha** [comment]
I replicated this issue, and following are the details:

## Replication:
- Test case
![image](https://github.com/user-attachments/assets/3c7d7c02-a00e-4cb5-9e14-3740e7d98c40)

- compiled using wasi-sdk 

- Made the following directory and symbolic link :

``` 
subdir_1/
└── subdir_1/
    └── subfile_2
softfile_1 -> subdir_1/subdir_1/subfile_2 (symbolic link)
```

## Outputs:
Output from wasmedge: 
![image](https://github.com/user-attachments/assets/cb2d5c6b-f12f-479a-8427-58f4fcac70e3)

Output from wasmtime :
![image](https://github.com/user-attachments/assets/74d9a3f7-befe-4328-8aaf-fea19d4d0611)

### Remarks  :  Both wasmedge and wasmtime produces the same expected result. So the issue can be closed.

**Comment by himanshisrestha** [comment]
@hydai , Sorry that I missed to mention the environment used. I have updated the details in the comment. Just adding here for ease.

- Wasmedge version: wasmedge version 0.14.1-38-gcd44d69b
- Wasi-sdk version:  wasi-sdk-24 
- Architecture: x86_64
- OS: Linux (Ubuntu 22.04.5 LTS)

**Comment by hydai** [comment]
It seems to be fixed now. I'm closing this issue.
