### ISSUE TITLE
feat: Enable manylinux_2_28 for all workflows currently using manylinux2014

### ISSUE THREAD

**Issue by 0yi0** [WasmEdge/WasmEdge#3511]
### Summary

This issue aims to record all related issues and PRs to enable `manylinux_2_28` in our CI workflows.

### Details

This is roughly equivalent to upgrading GCC from 11 to 13 thus several compilation issues need to be fixed.

#### List of all components
- `docker.yml` db8cc3c12fafe9d7af17797c76375d271a80c226 already disabled `manylinux2014` here.
- `build.yml` & `release.yml`
  - core - arm64 - #3409
  - core - x86_64 - #3348
  - plugins - arm64 - #3413
  - plugins - x86_64 - #3421
- ~`test-install-script.yml`~
- ~`test-python-install-script.yml`~ Wait until install scripts change to `manylinux_2_28`.

| parts | status |
| --- | --- |
| wasi_nn-tensorflowlite | - |
| wasi_nn-wasi_nn-ggml | - |
| wasi_nn-wasi_nn-pytorch | #3513 |
| wasm_bpf | #3512 |
| wasi_crypto | #3413 |
| wasi_logging | - |
| wasmedge_process | - |
| wasmedge_tensorflow | - |
| wasmedge_tensorflowlite | - |
| wasmedge_image | - |
| wasmedge_opencvmini | - |
| wasmedge_ffmpeg | - |

**Comment by q82419** [comment]
Related to #3542.
