### ISSUE TITLE
bug: Can't run Qwen2 on cuda

### ISSUE THREAD

**Issue by alabulei1** [WasmEdge/WasmEdge#3515]
### Summary

When I run Qwen2-7b on cuda, the behavior of Qwen2-7b is ver strange. See the following screenshot.

<img width="873" alt="image" src="https://github.com/WasmEdge/WasmEdge/assets/45785633/d84a3d94-e142-4468-8ebf-289c741bf2c7">

However, when I run it on the M chip MacBook, it works well.

### Reproduction steps

1.Following the instruction from this article: https://www.secondstate.io/articles/qwen2-7b-instruct/#run-qwen2-7b-instruct-on-your-own-device
2. It works well on my Macbook
3. It can't answer my question on my CUDA

### Screenshots

![DESCRIPTION](LINK.png)

### Components

CLI

### WasmEdge Version or Commit you used

0.13.5 and b3075 (commit 3d7ebf63

### Operating system information

Ubuntu 22.04.2 LTS

### Hardware Architecture

cuda 12.1

**Comment by hydai** [comment]
Please try b3259 instead.

**Comment by hydai** [comment]
Please try b3358 instead.

**Comment by hydai** [comment]
No updates. Closing it.
