### ISSUE TITLE
Moving WasmEdge-Stable-Diffusion project into WasmEdge Org

### ISSUE THREAD

**Issue by hydai** [WasmEdge/WasmEdge#3522]
### Summary

Currently, the WasmEdge-Stable-Diffusion project is under https://github.com/grorge123/wasmedge-stable-diffusion
To make it maintained by the WasmEdge team, we would like to move it into the WasmEdge org.

### Details

Migrate the project from https://github.com/grorge123/wasmedge-stable-diffusion to WasmEdge/wasmedge-stable-diffusion

cc @grorge123

**Comment by q82419** [comment]
Hi @grorge123 ,

Please also modify the [module name here](https://github.com/grorge123/wasmedge-stable-diffusion/blob/main/rust/src/stable_diffusion_interface.rs#L402) as `"wasmedge_stablediffusion"`. Thanks!

**Comment by hydai** [comment]
Done. See: https://github.com/WasmEdge/wasmedge-stable-diffusion
