### ISSUE TITLE
feat: Support ChatTTS as WASI-NN backend

### ISSUE THREAD

**Issue by grorge123** [WasmEdge/WasmEdge#3532]
### Summary

WasmEdge supports many NN backends, like llama, Pytorch, and Neural Speed. The objective of this work is to support ChatTTS as a new WASI-NN backend. ChatTTS is a text-to-speech model designed specifically for dialogue scenarios such as LLM assistant.

### Progress

- [x] Implement ChatTTS backend in WASI-NN
- [x] Support parameter setting
- [x] Support ChatTTS in [wasmedge-wasi-nn](https://github.com/second-state/wasmedge-wasi-nn)
- [x] Add an example in [WasmEdge-WASINN-examples](https://github.com/second-state/WasmEdge-WASINN-examples)

### Appendix

[ChatTTS](https://github.com/2noise/ChatTTS)

**Comment by hydai** [comment]
Should the title be ChatTTS?

**Comment by lazyperson1020** [comment]
The ChatTTS doesn't have an API at the moment. Could you provide with more documentation on ChatTTS.

**Comment by hydai** [comment]
Hi @grorge123 
It seems like all of the issues are fixed. Could we close this?

**Comment by grorge123** [comment]
Sure.
