### ISSUE TITLE
bug: [WASI-NN] Argument parsing error on Windows

### ISSUE THREAD

**Issue by L-jasmine** [WasmEdge/WasmEdge#3533]
### Summary

The usage of --preload is `--preload default:GGML:AUTO:Llama-2-7B-Chat-GGUF\llama-2-7b-chat.Q5_K_M.gguf`, but in Windows, file names may contain `:`, for example `--preload default:GGML:AUTO:C:\Users\45876\llama-2-7b-chat.Q5_K_M.gguf`.

This will result in the `Config` being pushed to `Builders`, but it will not be in `Builders[1]`.

https://github.com/WasmEdge/WasmEdge/blob/4616a88f8c916478412896926f261c02f2275038/plugins/wasi_nn/wasinnenv.h#L197

https://github.com/WasmEdge/WasmEdge/blob/4616a88f8c916478412896926f261c02f2275038/plugins/wasi_nn/ggml.cpp#L715-L716

### Current State

[2024-07-05 12:54:54.601] [error] [WASI-NN] GGML backend: Parse metadata error
[2024-07-05 12:54:54.601] [error] [WASI-NN] GGML backend: Failed to parse metadata.
Error: "Fail to load model into wasi-nn: Backend Error: WASI-NN Backend Error: Invalid Encoding"

`Builders[1`] is `preload:\Users\45876\llama-2-7b-chat.Q5_K_M.gguf`

### Reproduction steps

``` c
wasi_ephemeral_nn::load_by_name_with_config("C:\Users\45876\llama-2-7b-chat.Q5_K_M.gguf","{}")
```

### Screenshots

![image_1](https://github.com/WasmEdge/WasmEdge/assets/14789875/15cec8be-6219-40f0-8b44-e6c4678dc344)
![image_720](https://github.com/WasmEdge/WasmEdge/assets/14789875/911e0db1-042d-4656-82c8-59c18d354de2)
![debug](https://github.com/WasmEdge/WasmEdge/assets/14789875/42615f1a-214a-4f36-854a-7fc7b329cef2)
![result](https://github.com/WasmEdge/WasmEdge/assets/14789875/17fcbc6f-6b80-413c-a8ff-a02e592f59d5)

### Components

CLI, C SDK

### WasmEdge Version or Commit you used

0.14.0

### Operating system information

Windows 11

### Hardware Architecture

amd64

**Comment by hydai** [comment]
@dm4 
Let's remove the `default:GGML:AUTO:<model>:<config>`. The reason is that it will produce more edge cases to handle the `<model>:<config>`.
