### ISSUE TITLE
Getting error while building wasm-edge from source

### ISSUE THREAD

**Issue by kumarutkarsh1248** [WasmEdge/WasmEdge#3535]
### Summary

i am building with BUILD_EXAMPLE=ON and getting this error
![Screenshot from 2024-07-06 15-15-47](https://github.com/WasmEdge/WasmEdge/assets/118059940/ca6e5ce9-3bb1-4d4d-9bfe-8e1f4c18e69c)

**Comment by hydai** [comment]
You should report it in bug format. I am closing it since there is no information about which commit/version you used, what environment you are in, what commands you are running, and what kind of hardware and platform you are using.
