### ISSUE TITLE
Roadmap Q3/2024: WASI-NN GGML plugin with latest llama.cpp integration

### ISSUE THREAD

**Issue by q82419** [WasmEdge/WasmEdge#3539]
### Summary

Integrate the latest llama.cpp in GGML backend of WASI-NN.

**Comment by hydai** [comment]
This is fixed. 0.14.1 provides the latest llama.cpp version at that time. And we are going to sync up with the llama.cpp upstream.

**Comment by q82419** [comment]
Close this and use the new roadmap issue instead.
