### ISSUE TITLE
question: [WASI-NN] Should we disable OpenMP by default?

### ISSUE THREAD

**Issue by dm4** [WasmEdge/WasmEdge#3544]
### Summary

The newer version of llama.cpp [enable OpenMP by default](https://github.com/ggerganov/llama.cpp/blob/31ec3993f6e050322a249c07af79dbde66ea6ddc/ggml/CMakeLists.txt#L142). Should we disable it to keep the behavior of our WASI-NN plugin consistent with before?

@hydai, do you have any thoughts?

**Comment by hydai** [comment]
Because the OpenMP is not shipped by default on each platform, let's disable it from now.
