### ISSUE TITLE
bug: installation failed

### ISSUE THREAD

**Issue by Aniket369874** [WasmEdge/WasmEdge#3556]
### Summary

-V

### Details

Please see --help
	If issue persists make a trace using -V and submit it to
https://github.com/WasmEdge/WasmEdge/issues/new?assignees=&labels=&template=bug_report.md

    * Failed to install WasmEdge

### Appendix

-V

**Comment by Aniket369874** [comment]
tel me how to solve this problem

**Comment by Aniket369874** [comment]
tell me how to solve this problem

**Comment by hydai** [comment]
Please provide the command you used and the full log.

**Comment by hydai** [comment]
No updates, closing this.
