### ISSUE TITLE
[Plugin] WASI_LOGGING support Windows

### ISSUE THREAD

**Issue by L-jasmine** [WasmEdge/WasmEdge#3570]
### Summary

I need to run the LlamaEdge api-server.wasm on Windows, but it must use WASI_LOGGING.

Therefore, I expect that wasi_logging can support Windows.

**Comment by hydai** [comment]
WASI_LOGGING supports Windows. However, we don't set up the release workflow for it. As a workaround, please build the plugin manually until we publish the pre-built assets.

**Comment by ak516** [comment]
i would like work on this issue could you please assign this to me

**Comment by hydai** [comment]
This is not planned. We are going to embed the wasi-logging into the wasmedge library. No longer need to do this.
