### ISSUE TITLE
[CI] manylinux: WASI-NN Neural Speed

### ISSUE THREAD

**Issue by 0yi0** [WasmEdge/WasmEdge#3574]
### Summary

Build and release WASI-NN Neural Speed on `manylinux_2_28`

### Details

- [ ] Update `utils/wasi-nn/install-neuralspeed.sh`: which is currently apt-only
- [ ] Update
  - `.github/workflows/matrix-extensions.json`
  - `.github/extensions.paths-filter.yml`
  - `.github/workflows/reusable-build-extensions.yml`

**Comment by AdeshGhadage** [comment]
hey, i want to work on this issue can you assign me?

**Comment by 0yi0** [comment]
See #3744
