### ISSUE TITLE
LFX Mentorship (Sept-Nov 2024): Create a Wasm-based LLM app for financial analysts

### ISSUE THREAD

**Issue by juntao** [WasmEdge/WasmEdge#3580]
# Summary

### Description

We would like to develop an LLM-based financial data analytics application using open source LLMs, embedding models, the LlamaEdge application server, vector databases, and data processing tools. It will provide an open source "template" and showcase "best practices" for similar applications in this fast growing application area.

### Expected outcome

* Create a data processing pipeline in Python or Rust to automatically
    * collect public company’s SEC 10-Q quarterly reports and press releases. e.g., [Apple 10-Q](https://www.sec.gov/edgar/browse/?CIK=0000320193) and [Apple press release](https://www.apple.com/newsroom/2024/05/apple-reports-second-quarter-results/)
    * generate a summary for each SEC 10-Q and press release documents using an LLM service such as [LlamaParse](https://docs.llamaindex.ai/en/stable/llama_cloud/llama_parse/) or [EYELEVEL xRay](https://dashboard.eyelevel.ai/xray/) 
    * create and continuously update a vector database with the summary and original text. The vector is computed from the summary to improve search efficiency.
* Create a server-side RAG app that can chat with the vector knowledge base of financial statements.
* Evaluate the answer quality
* Explore LLM function calling to incorporate real-time information and actions

### Recommend skills

* Python
* [LlamaEdge](https://github.com/LlamaEdge/LlamaEdge) -- see a [tutorial](https://llamaedge.com/docs/user-guide/get-started-with-llamaedge)
* ChatGPT and LLMs
* The [RAG process](https://llamaedge.com/docs/category/server-side-rag)
* Rust (optional)

### Pre-test

[Follow instructions](https://docs.gaianet.ai/node-guide/quick-start) to create and deploy a Gaia node, which is contains an LLM, an embedding model, and a vector database snapshot.

[Choose one of the tutorials](https://docs.gaianet.ai/category/knowledge-bases) to create a vector snapshot from your own documents, and update the Gaia node with the new snapshot.

### Mentor

Michael Yuan @juntao michael@secondstate.io

**Comment by lazyperson1020** [comment]
Hey @juntao I am interested to work on it . So can we not use [SEC API](https://sec-api.io/ ) here?

**Comment by anshikavashistha** [comment]
@juntao I would be happy to contribute into this project.What are thr prerequisites for this project ?

**Comment by juntao** [comment]
> Hey @juntao I am interested to work on it . So can we not use [SEC API](https://sec-api.io/) here?

We definitely could build the solution so that it can work with the SEC API as a data source -- the user will need to bring in their own SEC API key though.

**Comment by juntao** [comment]
> @juntao I would be happy to contribute into this project.What are the prerequisites for this project ?

Would love to have you as a contributor. :) We have a pretest mentioned in the issue. Thanks.

**Comment by 0saurabh0** [comment]
Hi @juntao 
Are the technologies to be used in this project pre-defined (say `qdrant` for vector db etc)?
and also where the pre-task should be submitted?

**Comment by HitanshuPrasad** [comment]
Interested in the project loking forward to meaningful contributions!

**Comment by SumantxD** [comment]
Hi @juntao 👋 
The project seems interesting to me. Myself Sumant, I am a Generative AI Engineer and have experience in building RAG-based chatbots. I have worked extensively with LangChain, Llama Index, and open-source models like Mistral and Llama-3.

**pre-test completion:**
deployed a Gaia node, which contian Phi-3-mini-4k-instruct LLM, nomic-embed-text embedding model, and a vector database snapshot of my resume.
<img width="1470" alt="Screenshot 2024-07-28 at 4 24 01 AM" src="https://github.com/user-attachments/assets/c3572bd7-2160-40e1-9278-b9e6cd199c71">
<img width="1334" alt="Screenshot 2024-07-28 at 4 28 37 AM" src="https://github.com/user-attachments/assets/bf7fb749-2ead-4c96-96fc-b8946244dd53">
<img width="1470" alt="Screenshot 2024-07-28 at 4 37 39 AM" src="https://github.com/user-attachments/assets/372a48d4-c2f9-4703-a43a-bd116ab71d4f">
<img width="1470" alt="Screenshot 2024-07-28 at 4 19 38 AM" src="https://github.com/user-attachments/assets/251585ad-6808-42f2-b3d1-66ae48de5036">

**prior-experience with open source**
Participated in the AsyncAPI Mentorship Program 2023 and built a simulator desktop application.
repo: https://github.com/asyncapi/simulator
notable PR:
1) https://github.com/asyncapi/simulator/pull/185
2) https://github.com/asyncapi/simulator/pull/180

Looking forward to make some meaningful contributions. 😄

**Comment by HitanshuPrasad** [comment]
Hi @juntao  , i have completed the pretest and was looking for any extended task that could be helpful. 
Where/ How should i submit my  pre -test results ?

Thanks!

**Comment by BKnight11** [comment]
hi guys, i m facing a problem as i m not getting the url as mentioned in the insttuction , i have tried using the localhost ,but still it did not run, can someone please help me out with this.
![Screenshot 2024-07-29 143152](https://github.com/user-attachments/assets/bd00fe03-1a17-47a2-ab67-50b7b2eb0bd4)

**Comment by omsurase** [comment]
Hi @BKnight11, This issue could be due to insufficient VRAM for the llm when running gaianet node( thats my experience ). Try tweaking the config.json present inside the gaianet directory by reducing chat_batch_size , chat_ctx_size attributes.

**Comment by BKnight11** [comment]
Thank you @omsurase for trying to help me out :), well unfortunately its still not working out. I tried reducing chat_batch_size from 4096 to 2048 , chat_ctx_size from 16 to 8, as it was not working out i further reduced it to 1024 and 4 respectively but this did not help out as well. 
![Screenshot 2024-07-29 210505](https://github.com/user-attachments/assets/5a0eec0d-e914-4573-80ce-38f81ec70292)
 
![Screenshot 2024-07-29 210814](https://github.com/user-attachments/assets/2d9f4d7d-b5f9-44e0-becf-02317145b6c5)

kindly tell if anyone knows any other way to fix the issue.

**Comment by gjyotin305** [comment]
Hi @juntao 

- This is with Phi-3-mini-4k-instruct LLM, nomic-embed-text embedding model and RAG with a 500 word story on Athena an AGI, made by Robert (Synthetically generated story).
- ![image](https://github.com/user-attachments/assets/8ad163bc-729f-482b-85c9-99e2e94e4a55)

- ![image](https://github.com/user-attachments/assets/3c8c971c-39d2-4f70-abd0-e1899bd3798b)

**Comment by juntao** [comment]
@SumangalChhetri you could try a smaller model to see if it starts. Eg

https://github.com/GaiaNet-AI/node-configs/tree/main/qwen2-0.5b-instruct

Remember to do `gaianet stop` before you init again. Thanks

**Comment by aryan0931** [comment]
Interested in the project loking forward to meaningful contributions, as it matches my skills and I have already worked on LLM apps before.

**Comment by lazyperson1020** [comment]
For my pre-test, I have taken a dataset which has the reports of the 2023 SEC-10K [link](https://huggingface.co/datasets/itzme091/financial-qa-10K-modified2) .I finetuned Phi-3-Mini-4k-instruct (converted to gguf) [link](https://colab.research.google.com/drive/17x4gVSti8ArXVTUNVqMPcROuchu9FJ-4?usp=sharing) which can be found [here](https://huggingface.co/itzme091/sec-try1) and then converted the dataset into text files (for some of the companies separately) which can be found [here](https://huggingface.co/datasets/itzme091/SEC_textfiles) and made their snapshots [here](https://huggingface.co/itzme091/Snapshots) . 
I then changed the config files accordingly and started a gaianet node with the fine-tuned LLM and my snapshots. 


![nvidia](https://github.com/user-attachments/assets/adfdd460-e358-40dc-83a1-66daadd42038)
![imgonline-com-ua-twotoone-efHEVQGpbHGuas](https://github.com/user-attachments/assets/2ce19e2e-7bbf-406f-b18f-72c7ab31ab7d)

**Comment by lazyperson1020** [comment]
@juntao Can I use [a python library](https://pypi.org/project/sec-edgar-downloader/) and make a script that can eventually automate the entire process?

**Comment by SumangalChhetri** [comment]
Thank you @juntao , the smaller modle you told me to work on worked, i did try to make knowledge base form any URL. I parsed the URL content to a markdown file using fire crawl and also converted your markdown file to a snapshot of embeddings using hugging face.However i m facing quite similar issue like my first one when i m trying to customize my node i.e the URL is not coming and even reducing chat_batch_size , chat_ctx_size is not helping . I am trying to resolve the issue but it would be of great help if anyone could kindly help me to fix the issue.

Here the URL is showing up.
![Screenshot 2024-08-04 205000](https://github.com/user-attachments/assets/5da05849-0561-46f1-8516-0a0aa0cfd22f)

But after trying to customize the node the URL is not showing up.
![URL not ](https://github.com/user-attachments/assets/88b0f21f-d402-4dd8-8380-2cef0609f918)

**Comment by lazyperson1020** [comment]
Hey @juntao I have made a python script that can automatically download the filing and parse using Llama-Parse. The file can then be uploaded to huggingface.  [link](https://github.com/lazyperson1020/LFX-WasmEdge-PreTask-SEC/blob/main/Parsing%20and%20Uploading%20(1).ipynb)

**Comment by aryan0931** [comment]
hello @juntao I have completed the pre-tests, 
<img width="1455" alt="Screenshot 2024-08-08 at 8 17 27 PM" src="https://github.com/user-attachments/assets/945c2380-7d25-41eb-80dd-0e27c40ee135">
<img width="1464" alt="Screenshot 2024-08-08 at 8 17 46 PM" src="https://github.com/user-attachments/assets/ecb0b6c8-7e03-4b40-a214-2a2a603bd3ee">

I've completed the task of creating a vector snapshot from my documents and updated the Gaia node with the new snapshot. You can find the snapshot [here](https://huggingface.co/aryan0931/aryan/tree/main). The node has been updated with data from the House of the Dragon series.I have already worked on in building some llm apps one of them was related to amazon financial data, and I would like to work on this project.

**Comment by SRIMANKS** [comment]
> Thank you @omsurase for trying to help me out :), well unfortunately its still not working out. I tried reducing chat_batch_size from 4096 to 2048 , chat_ctx_size from 16 to 8, as it was not working out i further reduced it to 1024 and 4 respectively but this did not help out as well. ![Screenshot 2024-07-29 210505](https://private-user-images.githubusercontent.com/132873278/353139911-5a0eec0d-e914-4573-80ce-38f81ec70292.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0Njc4NTgsIm5iZiI6MTcyMzQ2NzU1OCwicGF0aCI6Ii8xMzI4NzMyNzgvMzUzMTM5OTExLTVhMGVlYzBkLWU5MTQtNDU3My04MGNlLTM4ZjgxZWM3MDI5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMlQxMjU5MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYTY3ZDE0MTZhNDFmNzNmNjdlZTM0Zjk0ZTc5YWI4MWFmZWJkZDkwZTQyZmNjZGYxNDI3ZmE0ZGM1ZDUzMzE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qR3Dms_dfiwpFy3p_U0gIetUrpEgrolD8z1KigeD6xE)
> 
> ![Screenshot 2024-07-29 210814](https://private-user-images.githubusercontent.com/132873278/353139994-2d9f4d7d-b5f9-44e0-becf-02317145b6c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0Njc4NTgsIm5iZiI6MTcyMzQ2NzU1OCwicGF0aCI6Ii8xMzI4NzMyNzgvMzUzMTM5OTk0LTJkOWY0ZDdkLWI1ZjktNDRlMC1iZWNmLTAyMzE3MTQ1YjZjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMlQxMjU5MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOGM3YmZmMTk4NDIwNjc2Zjk3ZGQ1OGFiZTJjM2EwMzY2NWY2NzMwYjVlN2E3NGFhZjFlYmFhNjhhOGFhODRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IIlONxNViR_I5KunfFJT5iIBAjnpsREhlzG4t8j3PFg)
> 
> kindly tell if anyone knows any other way to fix the issue.

same issue still persists

**Comment by itsme-ranger** [comment]
Dear @juntao, I have deployed a GitHub PR summary bot based on an open-source LLM successfully. You can check the 

![image](files:///Users/Gerry/Desktop/flow-net.png)
![image](files:///Users/Gerry/Desktop/flow-net2.png)

You can check my proposal for improvement, including the snapshot here

I have experiences in discriminative AI but I want to participate in gen AI too

**Comment by angad-singhh** [comment]
Hey @juntao , I have completed both the pre-test mentioned and have submitted the application on the portal. The pre-test can be found here [pre-test](https://github.com/angad-singhh/Mentorship-Pretest). I have been exploring the possible solutions and related API's including SEC EDGAR API and llama Parse, will update the same. 

Wasn't able to make it in last LFX term, looking forward for this one.
Thanks, 
Angad Singh

**Comment by staru09** [comment]
Hi @juntao I was playing around different methods of creating a knowledge base as mentioned [here](https://docs.gaianet.ai/category/knowledge-bases) and I started with the pdf one using llamaparse and used llama 3.1 7B but it seems as if it was hallucinating and here are the results 
![pdf](https://github.com/user-attachments/assets/d875ba74-52e2-44c2-aed3-43ecf1567afd)
then I tried to use plain text file and here are the results
![Screenshot from 2024-08-17 16-10-30](https://github.com/user-attachments/assets/6e8e4ef5-d797-4f77-9eb1-731532270af1)
![Screenshot from 2024-08-17 16-09-47](https://github.com/user-attachments/assets/42e1c073-cb0f-464f-a964-cedaa65266cc)
![Screenshot from 2024-08-17 16-09-33](https://github.com/user-attachments/assets/fc333022-7965-4521-be96-57232b4d6ea7)

I used apple's 10-Q filing to create a snapshot for both pdf as well as text and the chat_ctx_size is set to 1000 because of computational constraint. I don't know but text file is giving best results though results aren't very accurate but can you please suggest what else could be done here.

**Comment by staru09** [comment]
Hi @juntao I tried creating a summary of reports here is a [notebook](https://github.com/staru09/LFX_test/blob/main/Financial_chatbot/Code/llama3.1_summarizer.ipynb) that does the same. The results aren't very good but they can be improved by using different version of llama3.1 or using openai api . Please let me know if anything else could be done.

**Comment by lazyperson1020** [comment]
Dearest @juntao The major issue that I found was the lack of analysis of the reports with specific numbers and values that were given in the reports as TABLES. Thus I have created a python script that takes financial reports (in excel format as provided on SEC site) and generates the summaries through  gaianet node (llama.us.gaianet.network) and saves them as text file. This can then be converted to embeddings / snapshots and used through RAG. 
I hope that you have a look at it here- [https://github.com/lazyperson1020/sec-excel-sum/blob/main/coverter.py](https://github.com/lazyperson1020/sec-excel-sum/blob/main/coverter.py)
**Looking forward to wonderful contributions and beyond**.
![image](https://github.com/user-attachments/assets/be240ba9-8f11-4f8c-a85a-e6e9e673c966)

**Comment by staru09** [comment]
Hi @juntao 
Update of summarization 
I tried summarization by llama 3 using gaianet. I wrote python [script](https://github.com/staru09/LFX_test/blob/main/Financial_chatbot/Code/pdf_preprocess.py) to chunk the 10-Q pdf page wise and then create a csv [file](https://github.com/staru09/LFX_test/blob/main/Financial_chatbot/Dataset/CSV/test.csv) from it. Then I again wrote a python [script](https://github.com/staru09/LFX_test/blob/main/Financial_chatbot/Code/csv_summarizer.py) to summarize and add a summary column to the csv [file.](https://github.com/staru09/LFX_test/blob/main/Financial_chatbot/Dataset/CSV/test_summary.csv) 
Now this csv file can be used to create vector embeddings and to RAG any LLM of our choice.

Here is a sample flow chart 
![Flowchart](https://github.com/user-attachments/assets/ffc51615-4c67-46dd-b249-f79e4ca6c7d5)

Please let me know if I am missing anything or anything that can be improved here.

**Comment by staru09** [comment]
Hi @juntao  
[This](https://github.com/staru09/LFX_test/blob/main/Financial_chatbot/Dataset/PDF/Document.pdf) is the apple's 10-Q filing of 2017 and [this](https://github.com/staru09/LFX_test/blob/main/Financial_chatbot/Dataset/CSV/out_summary.csv) is the final csv containing the page wise summary along with the context. Should I use some other chunking strategy or is there any way through which I can improve the summarization.

**Comment by staru09** [comment]
Greetings @juntao 
Using [this](https://github.com/staru09/LFX_test/blob/main/Financial_chatbot/Code/3.1%20qna_generate.py) and [this](https://github.com/staru09/LFX_test/blob/main/Financial_chatbot/Code/3.2%20qna_format.py) I was able to generate [this](https://github.com/staru09/LFX_test/blob/main/Financial_chatbot/Dataset/Text/test.txt) which can be fed directly to finetune a llama and improve the responses for our bot.

**Comment by lazyperson1020** [comment]
Hey @juntao  , I analysed many reports and  I also found an issue that in the PDFs, there are many paragraphs in which we have the references given to some other paragraphs or texts. So, to get a better quality answer, we must pass the whole context along with the referenced part as the chunk. Clever creation of chunks and embeddings is thus an important part of the project. I hope to have a healthy discussion with you on how we can improve upon such things using latest findings and advanced RAG pipeline. 
<img width="877" alt="Screenshot 2024-08-25 at 3 59 57 PM" src="https://github.com/user-attachments/assets/1650c9c4-1e55-46e3-a0a9-1ca850ccbc9d">

**Comment by staru09** [comment]
Hi @juntao  @hydai 
I created this [text](https://github.com/staru09/LFX_test/blob/main/Financial_chatbot/Dataset/Text/qna.txt) file containing qna related to 10-Q filings of 2017 using gaianet but I feel in order to finetune llama.cpp for being a better financial analyst bot, I guess I would be needing more general questions rather than the ones specific to any particular company's filings. Should I use some book or other financial  documents for finetuning it?
Looking forward for your suggestions.

**Comment by staru09** [comment]
Hi @juntao 
I was going through 10-Q reports and found that it's mostly divided into 2 parts with 1st part containing the financial information and second part containing things that are not exactly financial (not much tabular data)  so while chunking and creating embeddings, can we create different embeddings for the financial data in these reports and different one for part 2 as per the given index?
![Screenshot from 2024-08-27 15-33-29](https://github.com/user-attachments/assets/dda54974-a6a4-4d3b-a89c-aee4892d1c3f)

**Comment by lazyperson1020** [comment]
Hey @juntao just to add, there is a lot of work done on Sentiment Analysis of the SEC filings. I think we can leverage that also in our project as simply relying on the texts of the filings won't be beneficial in the extensive analysis of the reports.

**Comment by staru09** [comment]
Hi @juntao just an update [this](https://github.com/staru09/LFX_test/blob/main/Financial_chatbot/Code/data_scrap.py) is the script to download the filings and save them as PDF format.
