### ISSUE TITLE
August 6th 2024, Community Meeting Agenda

### ISSUE THREAD

**Issue by alabulei1** [WasmEdge/WasmEdge#3582]
### Summary

We hold a monthly [community meeting](https://wasmedge.org/docs/contribute/community#community-meeting) to showcase community-created content, introduce new features, review upcoming milestones, and engage in Q&A with the WasmEdge community. Everyone is welcome, and we encourage you to attend or present a session!

This issue aims to foster discussion within the WasmEdge community about potential topics for the meeting. If you have a topic you want to present or learn more about, please comment with your name and a brief description of the topic.

## Agenda
* Introduction
* Session 1: Stable diffusion demo by @grorge123 
* Session 2: Use LLM function calls to control your own computer by @juntao 
* Session 3: LFX mentorship term 3 by @hydai 
* Open Discussion
* Closing

### Appendix

Time: The first Tuesday of each month at 11PM Hong Kong Time/ 7AM PST.

[Public meeting agenda/notes](https://docs.google.com/document/d/1iFlVl7R97Lze4RDykzElJGDjjWYDlkI8Rhf8g4dQ5Rk/edit#) | [Zoom link](https://us06web.zoom.us/j/88282362606?pwd=UFhOdzlVKyswdW43c21BKy9DdkdyUT09)

**Comment by hydai** [comment]
Session Title: LFX mentorship term 3
Speaker: hydai

**Comment by grorge123** [comment]
Session Title: Stable Diffusion Plugin
Speaker: Han Wen Tsao

**Comment by alabulei1** [comment]
I think we can also have a function call demo @juntao

**Comment by juntao** [comment]
> I think we can also have a function call demo @juntao 

Session title: Use LLM function calls to control your own computer

Session speaker: Michael Yuan

**Comment by alabulei1** [comment]
Great. I have already updated the agenda. See you soon!
