### ISSUE TITLE
LFX mentorship (Sept-Nov 2024): WASM Serializer with new proposals

### ISSUE THREAD

**Issue by q82419** [WasmEdge/WasmEdge#3585]
### Summary

WasmEdge provides WASM module serializer in C API level to convert the loaded WASM structure back into binary format.
But in current status, after implementing the `function-references`, `GC`, `relaxed-SIMD`, and `exception-handling` proposals, the partitions of these proposals in serializer are not implemented yet.
Thus, we would invite mentees to complete the binary format serialization in WasmEdge.

### Details

Description: WasmEdge provides WASM module serializer in C API level for developers to convert the loaded WASM structure back into binary format. But after supporting the `function-references`, `GC`, `relaxed-SIMD`, and `exception-handling` proposals in WasmEdge, the partitions of these proposals in serializer are not implemented yet. Thus, we would invite mentees to complete the binary format serialization with the above WASM proposals in WasmEdge.

Expected Outcome:
* Complete the serialization of the new module extensions in WASM proposals.
* Complete the serialization of the new instructions added in WASM proposals.
* Add some basic unit tests with hand-writing WASM binaries.

Recommended Skills: C++, WASM, git

Mentor(s):
- Yi-Ying He (@q82419, [yiying@secondstate.io](mailto:yiying@secondstate.io))

For those LFX mentorship applicants, we recommand them to provide their github profiles in their resume, so that we can refer to their owned repositories (especially in C/C++).

### Appendix

- Mentorship page: https://mentorship.lfx.linuxfoundation.org/project/c96de5c4-e1c3-4a02-a18a-65507d1cb675
- WASM Function Reference Types proposal: https://github.com/WebAssembly/function-references
- WASM GC proposal: https://github.com/WebAssembly/gc
- WASM Relaxed SIMD proposal: https://github.com/WebAssembly/relaxed-simd
- WASM Exception Handling proposal: https://github.com/WebAssembly/exception-handling

**Comment by HitanshuPrasad** [comment]
Hi @hydai ! Looking forward to being part of the project since I have experience in C/C++. Anything on where can I start to track this is issue ?

**Comment by Shruti78** [comment]
hi @hydai i want to contribute in your project , with knowledge of WASM, git, c++ . Please assign me this issue.

**Comment by hydai** [comment]
> Hi @hydai ! Looking forward to being part of the project since I have experience in C/C++. Anything on where can I start to track this is issue ?

All related information is listed in the issue.

> hi @hydai i want to contribute in your project , with knowledge of WASM, git, c++ . Please assign me this issue.

We don't use assign here. Check the LFX mentorship website for the applications.

**Comment by shailpujan88** [comment]
Hello everyone, @hydai, I am Shail Pujan, a student in Computer Science. I am interested in WASMEdge Serializer Project.

Could you please advise me on the most important aspect to strengthen my application? Should I focus on increasing my contribution to the project(solving issues) or crafting a solid proposal and implementation plan?
Any guidance will be really helpful!

Thanks a lot!
Looking forward to great contribution.

**Comment by arujjval** [comment]
@hydai Just to be clear, do we have to implement it right now or we will be implementing it during mentorship?

**Comment by hydai** [comment]
> @hydai Just to be clear, do we have to implement it right now or we will be implementing it during mentorship?

I don't get the point. This is a mentorship program; the issue describes the mission a mentee should complete during the mentorship term 3.

**Comment by arujjval** [comment]
@hydai I mean can we work on this on our own?

**Comment by hydai** [comment]
> @hydai I mean can we work on this on our own?

I got so confused.
A mentee sends the application on the LFX mentorship website, and only one of them will be accepted to own this project idea during the mentorship. If you don't know how LFX mentorship works, please check the LFX mentorship guidelines first.

**Comment by itsme-ranger** [comment]
Dear @hydai, I have read all the specs and the source codes. I think I found which parts to modify or add

**Comment by itsme-ranger** [comment]
Dear @hydai, I already applied this on LFX Mentorship. For now, the way how I'll solve this is by learning and adapting to the finished works here. For main serialization, the main part is in `lib/loader/serialize` and adapts like with the changes that come from #2626. For partitions of these proposals in serializer implementations, We have to understand the changes like in #3311. I have experience in developing computer vision analytics, mainly using modern C++ with implementing best practices and features like using smart pointer, template metaprogramming, RAII style, lambda expression, and unit testing

**Comment by q82419** [comment]
Completed #3722
