### ISSUE TITLE
bug: WASI-NN Neural speed calls Py_XDECREF more than once

### ISSUE THREAD

**Issue by PeterD1524** [WasmEdge/WasmEdge#3596]
### Summary

The WASI-NN Neural speed plugin implementation calls [Py_XDECREF](https://docs.python.org/3/c-api/refcounting.html#c.Py_XDECREF) on the same PyObject more than once.
If the object’s reference count reaches 0, the object’s type’s deallocation function is invoked.

For example first in:
https://github.com/WasmEdge/WasmEdge/blob/c43ac946ee6c84c42f4c21634f6831a537de988b/plugins/wasi_nn/neuralspeed.cpp#L144-L154

Second in the destructor of Graph:
https://github.com/WasmEdge/WasmEdge/blob/c43ac946ee6c84c42f4c21634f6831a537de988b/plugins/wasi_nn/neuralspeed.h#L24-L30

I think this is causing failure sometimes in tests. If you're lucky, the test will pass. Otherwise you get segmentation fault or some undefined behavior.

### Expected State

Maybe let only the destructor do the work or set those `PyObject*` to `nullptr` after calling [Py_XDECREF](https://docs.python.org/3/c-api/refcounting.html#c.Py_XDECREF) or just use [Py_CLEAR](https://docs.python.org/3/c-api/refcounting.html#c.Py_CLEAR)

### Components

Others

### WasmEdge Version or Commit you used

c43ac946ee6c84c42f4c21634f6831a537de988b

### Operating system information

Linux

### Hardware Architecture

x86_64

**Comment by hydai** [comment]
Hi @grorge123, Could you please help with this issue?

**Comment by PeterD1524** [comment]
Some more discoveries:

https://github.com/WasmEdge/WasmEdge/blob/c43ac946ee6c84c42f4c21634f6831a537de988b/plugins/wasi_nn/neuralspeed.cpp#L126-L135

`GraphRef.Model` isn't accessed before. Maybe `Py_XDECREF(GraphRef.NeuralSpeedModule);` instead of `Py_XDECREF(GraphRef.Model);`.


https://github.com/WasmEdge/WasmEdge/blob/c43ac946ee6c84c42f4c21634f6831a537de988b/plugins/wasi_nn/neuralspeed.cpp#L276-L294

[PyList_GetItem](https://docs.python.org/3/c-api/list.html#c.PyList_GetItem) returns borrowed references. Therefore maybe not use `Py_DECREF` on the returned `PyObject *`.

https://docs.python.org/3/c-api/intro.html#reference-count-details:
> When no ownership is transferred, the caller is said to borrow the reference. Nothing needs to be done for a [borrowed reference](https://docs.python.org/3/glossary.html#term-borrowed-reference).

https://docs.python.org/3/c-api/intro.html#reference-counts

**Comment by PeterD1524** [comment]
Minor leak problems:

[PyUnicode_FromString](https://docs.python.org/3/c-api/unicode.html#c.PyUnicode_FromString) returns a new reference and [PyImport_Import](https://docs.python.org/3/c-api/import.html#c.PyImport_Import) does not steal a reference so I think it should be `Py_DECREF`ed after PyImport_Import. Or just use [PyImport_ImportModule](https://docs.python.org/3/c-api/import.html#c.PyImport_ImportModule) which accepts `const char *`.
https://github.com/WasmEdge/WasmEdge/blob/61961a1cd294f612442da396477fcd760bac7e4e/plugins/wasi_nn/neuralspeed.cpp#L117-L118
Another PyUnicode_FromString:
https://github.com/WasmEdge/WasmEdge/blob/61961a1cd294f612442da396477fcd760bac7e4e/plugins/wasi_nn/neuralspeed.cpp#L268-L269
