### ISSUE TITLE
Problem setting llama 2 chatbot

### ISSUE THREAD

**Issue by xartus2004** [WasmEdge/WasmEdge#3609]
### Summary

I was following the execution steps in [Llama2 Inference](https://blog.stackademic.com/fast-and-portable-llama2-inference-on-the-heterogeneous-edge-a62508e82359)
## Expected Behavior
```console
$ wasmedge --dir .:. --nn-preload default:GGML:AUTO:llama-2-7b-chat-q5_k_m.gguf llama-chat.wasm
```
[USER]:
Who is the "father of the atomic bomb"?
[ASSISTANT]:
The "father of the atomic bomb" is a term commonly associated with physicist J. Robert Oppenheimer. Oppenheimer was a leading figure in the development of the atomic bomb during World War II, serving as the director of the Manhattan Project, which was responsible for the development and deployment of the first nuclear weapons. He is often referred to as the "father of the atomic bomb" due to his significant contributions to the field of nuclear physics and his leadership in the development of the bomb.
[USER]:
Was he a communist?
[ASSISTANT]:
J. Robert Oppenheimer was not a communist. While he was associated with the Manhattan Project, which was a secret government project, and was involved in the development of the atomic bomb, he was not a member of the Communist Party or had any known political affiliations with communism. Oppenheimer was a physicist and a scientist, and his primary focus was on the development of nuclear weapons during World War II.

## Current Behavior
```console
$ wasmedge --dir .:. --nn-preload default:GGML:AUTO:llama-2-7b-chat-q5_k_m.gguf llama-chat.wasm
```
[error] Might an invalid wasm file
[error] loading failed: magic header not detected, Code: 0x103
[error]     Bytecode offset: 0x00000000
[error]     At AST node: component
[error]     File name: "/home/paranjay/Documents/wasm-projects/llama-3-inference/llama-chat.wasm"

## Steps to Reproduce

1. curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- --plugin wasi_nn-ggml
2. source $HOME/.wasmedge/env
3. curl -LO https://github.com/second-state/llama-utils/raw/main/chat/llama-chat.wasm
4. curl -LO https://huggingface.co/wasmedge/llama2/resolve/main/llama-2-7b-chat-q5_k_m.gguf
5. wasmedge --dir .:. --nn-preload default:GGML:AUTO:llama-2-7b-chat-q5_k_m.gguf llama-chat.wasm
6. get the error
[error] Might an invalid wasm file
[error] loading failed: magic header not detected, Code: 0x103
[error]     Bytecode offset: 0x00000000
[error]     At AST node: component
[error]     File name: "/home/paranjay/Documents/wasm-projects/llama-3-inference/llama-chat.wasm"

## Components
CLI, C SDK, Rust SDK, Others

## WasmEdge Version or Commit you used
0.14.0

## Operating system information
ubuntu22.04

## Hardware Architecture
x86_64

**Comment by juntao** [comment]
Please download a release version of the llama-chat.wasm file

https://github.com/LlamaEdge/LlamaEdge/releases/download/0.12.5/llama-chat.wasm

And use the LlamaEdge installer to install WasmEdge

curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install_v2.sh | bash -s

**Comment by hydai** [comment]
Hi @xartus2004 
May I ask the command you used is from which document? The URL[1] you used is not existed.
Please download the release version from here[2].

[1]: https://github.com/LlamaEdge/LlamaEdge/raw/main/chat/llama-chat.wasm
[2]: https://github.com/LlamaEdge/LlamaEdge/releases/download/0.12.5/llama-chat.wasm

**Comment by xartus2004** [comment]
Oh my bad. I didn't checked the link.
This one works fine.
Thanks @juntao

**Comment by xartus2004** [comment]
Hi @hydai
The commands were from this article https://blog.stackademic.com/fast-and-portable-llama2-inference-on-the-heterogeneous-edge-a62508e82359
