### ISSUE TITLE
feat: Avoid triggering unrelated workflow jobs to reduce the CI usage

### ISSUE THREAD

**Issue by hydai** [WasmEdge/WasmEdge#3616]
### Summary

For example, this PR[1] modified the wasi-nn plugin, triggering all of the plugin CI jobs. We want to make sure the related CI jobs are executed to reduce the usage of our limited runners.

[1]: https://github.com/WasmEdge/WasmEdge/pull/3615

### Details

1. Use path filters to limit the CI executions
2. We have to reduce the usage of the arm64 runners, which are self-hosted, and the resources are limited and permanently block the CI jobs.

**Comment by 0yi0** [comment]
Is there reliable ways to generate white-list files for each plugins? If not, I think this should only be for specific plugins/platforms.

**Comment by hydai** [comment]
The folder should be good enough. If the WASI-NN is modified, then we just need to run WASI-NN plugins test suites.
