### ISSUE TITLE
[Call for Vote] Create wasmedge-llmc repo

### ISSUE THREAD

**Issue by hydai** [WasmEdge/WasmEdge#3653]
### Summary

For #3523, we are introducing a new plugin, wasmedge-llmc, into our ecosystem, allowing users to train the GPT model inside the wasm applications. In this issue, I am calling for voting about creating a new binding repository for it.

### Details

The main maintainer of this new project, wasmedge-llmc, will be @hydai
We need at least 3/4 of the WasmEdge Runtime maintainers to vote to continue this process.

- [x] @hydai 
- [x] @juntao 
- [x] @ibmibmibm 
- [x] @q82419

**Comment by juntao** [comment]
LGTM

**Comment by ibmibmibm** [comment]
LGTM

**Comment by q82419** [comment]
LGTM

**Comment by hydai** [comment]
Created https://github.com/WasmEdge/wasmedge-llmc
