### ISSUE TITLE
Would WasmCloud runtime replace my current FaaS across multiple clouds?

### ISSUE THREAD

**Issue by nathanawmk** [WasmEdge/WasmEdge#367]
Based on what I understand about WASMCloud, I think the fast speed and the fact that it is truly platform agnostic really represent the future. I wish to explore migrating my workloads (FaaS) that spans across on-premise, Azure, GCP and AWS over to WASMEdge.  Has anyone attempted to do this?

**Comment by hydai** [comment]
This issue is inactive. I am closing it. Please feel free to open a new issue if you have any more questions.
