### ISSUE TITLE
Streamline the install scripts

### ISSUE THREAD

**Issue by juntao** [WasmEdge/WasmEdge#369]
## Abstract

We should have a unified set of install scripts for wasmedge itself. The current install scripts only install include/ and lib/ but not bin/.

## Details

Modify the following scripts to install bin/

* install_wasmedge.sh
* install_wasmedge_tensorflow.sh
* install_wasmedge_image.sh

Also, shouldn't the `*deps.sh` scripts be incorporated into the corresponding install script? That is for the install script to detect the deps, and if they are missing, install them.

**Comment by SAtacker** [comment]
Hi @juntao ,
I have made a script https://gist.github.com/SAtacker/cf3ca3dd8df04313f58420574802fee1 which is a modification of the existing one.
![image](https://user-images.githubusercontent.com/61797109/131525307-5713e9e1-c868-4096-bc72-fff171bfbc5d.png)
Let me know if I need to do the same for others.

**Comment by juntao** [comment]
Yes. It would be great to have this in the extension install scripts too. 

Can you send us a PR with your change? Thanks.

**Comment by SAtacker** [comment]
In the project tree, I assume we need this under `utils`. Don't we?
