### ISSUE TITLE
WasmEdge Community meeting on 3rd Sep

### ISSUE THREAD

**Issue by alabulei1** [WasmEdge/WasmEdge#3697]
### Summary

We hold a monthly [community meeting](https://wasmedge.org/docs/contribute/community#community-meeting) to showcase community-created content, introduce new features, review upcoming milestones, and engage in Q&A with the WasmEdge community. Everyone is welcome, and we encourage you to attend or present a session!

This issue aims to foster discussion within the WasmEdge community about potential topics for the meeting. If you have a topic you want to present or learn more about, please comment with your name and a brief description of the topic.

## Agenda
* Introduction
* Session 1: Piper demo by @PeterD1524 
* Session 2: WasmEdge 0.1.4.1 Preview by @hydai 
* Session 3:  Cursor + Local LLM by @alabulei1 
* Open Discussion
* Closing

### Appendix

Time: The first Tuesday of each month at 11PM Hong Kong Time/ 7AM PST.

[Public meeting agenda/notes](https://docs.google.com/document/d/1iFlVl7R97Lze4RDykzElJGDjjWYDlkI8Rhf8g4dQ5Rk/edit#) | [Zoom link](https://us06web.zoom.us/j/88282362606?pwd=UFhOdzlVKyswdW43c21BKy9DdkdyUT09)

**Comment by hydai** [comment]
Hi @PeterD1524 
Would you like to discuss the Piper and demonstrate it in the community meeting?

**Comment by PeterD1524** [comment]
> Hi @PeterD1524 Would you like to discuss the Piper and demonstrate it in the community meeting?

Thank you for the invitation. Unfortunately, I won’t be able to attend the community meeting, but I’m happy to provide any presentation materials if needed.

**Comment by hydai** [comment]
> Thank you for the invitation. Unfortunately, I won’t be able to attend the community meeting, but I’m happy to provide any presentation materials if needed.

Then, would you like to record a presentation so we can play the video during the community meeting?

**Comment by PeterD1524** [comment]
Okay, can you provide some guidance?

**Comment by hydai** [comment]
> Okay, can you provide some guidance?

Here is a talk[1] provided by @grorge123. He discussed the Stable Diffusion plugin at the last community meeting. If you don't have any idea, we suggest the process as follows:

1. Introduce yourself.
2. Introduce the framework or plugin you developed.
3. Show a demo.
4. Walk through the implementation or explain the SDK you created.

The entire process should take less than 15 minutes.

Please note that the above format is not fixed or required, so you don't need to write slides in any specific format; you can decide what to present.

[1]: https://youtu.be/F26dlG-HmJU?si=tCi4jEas3AEY4VZN&t=117

**Comment by alabulei1** [comment]
Hi @hydai 

Could you talk about WasmEdge 0.14.1 preview?

**Comment by hydai** [comment]
> Hi @hydai
> 
> Could you talk about WasmEdge 0.14.1 preview?

Sure.

**Comment by PeterD1524** [comment]
@hydai 
The video: https://youtu.be/sfzgRWS4978
The slides: https://docs.google.com/presentation/d/1rmNJeLlsrjmBdcgAZAmjzIjJIwJOSU8sKTz3wxNsfHU/edit

Sorry I'm really bad at this :(

**Comment by alabulei1** [comment]
Well received. Thank you!
