### ISSUE TITLE
Cross-platform install

### ISSUE THREAD

**Issue by juntao** [WasmEdge/WasmEdge#370]
## Abstract

Now we support multiple OSes and platforms, the install script should support that.

## Details

Detect the correct OS and install the correct binary files. If the OS is not supported, throw an error.

**Comment by SAtacker** [comment]
Commit https://github.com/WasmEdge/WasmEdge/commit/a91f5c69e3cecc49a25ebb9d0b7b12c702de448e and its previous one resolves this for current stable releases of WasmEdge for `aarch64` and `x86_64` linux

**Comment by q82419** [comment]
Installer handled.
