### ISSUE TITLE
feat: Update `stable-diffusion` plugin to `master-64d231f` or above

### ISSUE THREAD

**Issue by apepkuss** [WasmEdge/WasmEdge#3701]
### Summary

The [FLUX.1-schnell](https://huggingface.co/second-state/FLUX.1-schnell-GGUF) has already supported by stable-diffusion.cpp. To support the model in `stable-diffusion` plugin, it is necessary to upgrade to `master-64d231f` or above.

### Details

Upgrade `stable-diffusion` plugin to `stable-diffusion.cpp master-64d231f`.

**Comment by hydai** [comment]
This is fixed by #3709
