### ISSUE TITLE
feat: Provide a `whisper & piper` combo plugin 

### ISSUE THREAD

**Issue by apepkuss** [WasmEdge/WasmEdge#3702]
### Summary

There is a solid requirement from [whisper-api-server](https://github.com/LlamaEdge/whisper-api-server) to use `whisper` and `piper` plugins at runtime.

### Details

There is a solid requirement from [whisper-api-server](https://github.com/LlamaEdge/whisper-api-server) to use `whisper` and `piper` plugins at runtime. Due to the constraints of `wasi-nn` interface, a feasible way is to provide a combo plugin that provides support for both `whisper` and `piper`.

**Comment by hydai** [comment]
I plan to have this in 0.14.1 RC4.
Currently, we are working on RC3.

**Comment by apepkuss** [comment]
Great!

**Comment by hydai** [comment]
Closing due to https://github.com/WasmEdge/WasmEdge/issues/3793#issuecomment-2375398068
