### ISSUE TITLE
[CI] manylinux: WASI-NN Burn.rs

### ISSUE THREAD

**Issue by 0yi0** [WasmEdge/WasmEdge#3729]
### Summary

Build and release WASI-NN Burn.rs on `manylinux_2_28`

### Details

- [ ] Update `utils/docker/Dockerfile.manylinux_2_28-plugins-deps` with corresponding dependencies
- [ ] Update these files; check examples here #3721
  - `.github/extensions.paths-filter.yml`
  - `.github/workflows/matrix-extensions.json`
    * `wasi_nn_burnrs-squeezenet`
    * `wasi_nn_burnrs-whisper`
  - `.github/workflows/reusable-build-extensions.yml`

**Comment by hydai** [comment]
The Rust-related plugins will soon be moved to https://github.com/WasmEdge/rust-plugins. Maybe we will no longer need this issue.
