### ISSUE TITLE
How to start a WasmEdge VM instance as a thread?

### ISSUE THREAD

**Issue by Galaxy0106** [WasmEdge/WasmEdge#374]
## Abstract
Sorry to interrupt, I am a graduate student of Huazhong University of Science and Technology. I want to use WasmEdge to do some experiments recently. It is mentioned in the project documentation that we can start a WasmEdge VM instance as a thread, but I did not find some examples or references. Can you provide some examples or documentation, thank you very much...

**Comment by hydai** [comment]
Hi @Galaxy0106 
To make WasmEdge run as a thread, you can use our [C API](https://github.com/WasmEdge/WasmEdge/blob/master/docs/c_api_quick_start.md) to create a VM instance.

**Comment by hydai** [comment]
Inactive issue. I am closing it.
