### ISSUE TITLE
question: Plugin circular dependencies make WasmEdge upgrades and releases complex.

### ISSUE THREAD

**Issue by CaptainVincent** [WasmEdge/WasmEdge#3767]
### Summary

The situation I encountered while verifying the `burn.rs` plugin was that the WasmEdge API had been upgraded, but since it hadn't been released yet, there was a version mismatch, causing the plugin registration to fail.

A similar issue/behavior will occur after the WasmEdge release, where both the Rust SDK  and the plugin SDK crates need to be upgraded. After the upgrades, we will have to return to WasmEdge to upgrade the burn.rs plugin for it to load successfully (circular upgrade dependency).

**Comment by hydai** [comment]
Let's separate the burnrs plugin and all future Rust plugins into a new repo.

**Comment by hydai** [comment]
@CaptainVincent 
The repo is created, please move the burnrs plugin to the new repo.

**Comment by CaptainVincent** [comment]
Waiting for #3830.
