### ISSUE TITLE
LFX Workspace: Support Wasm-C-API proposal

### ISSUE THREAD

**Issue by q82419** [WasmEdge/WasmEdge#379]
This issue is for the workspace of the WASM-C-API proposal supporting.

**Comment by William-Mou** [comment]
Hello, these are rough schedules in three months!

1. Study the WasmEdge C API and the WASM C/C++ API: 2 week
    * Understanding the workflow and architecture of WasmEdge 
    * Bottleneck: wrapping the WASM C/C++ API
2. Implementation: 8 weeks
    * Observe WasmEdge runtime and non-runtime behavior
    * Review the existing non-runtime API
    * Understand the test environment and CI
    * Plan and discuss runtime API program architecture with mentee
    * Try to complete the API
    * Pay attention to coding style
3. Code review and complete the documentation
    * I hope that the program can also be readable
    * Write appropriate documents for developers and API users to read

If you have any suggestions, please let me know!
Thank You!

**Comment by q82419** [comment]
Workspace Week 2

* Checked the study progress of WASM-C-API.
  * It seems like you have basic concepts of WASM workflow and use cases of WASM-C-API from the examples.
* Discussed the following directions.
  * The macros in the C-API header is very complex. You should try to make the macro wrappers of implementations and make sure the all declared functions are covered in your own way first.

**Comment by q82419** [comment]
Workspace Week 3
* Checked the tracing progress of `wasm.h`.
  * The implementation in the proposal used lots of macro and templates. You should try to trace through the macros.
* Keep on tracing and summarize the structures in the header.
  * We can look into the independent parts first, such as `ref` and `trap`. Some structures are in the same scope, such as `func`, `memory`, `global`, and `table`.
