### ISSUE TITLE
feat: support `--lora-model-dir` of stable-diffusion.cpp in `wasmedge_stablediffusion` plugin

### ISSUE THREAD

**Issue by apepkuss** [WasmEdge/WasmEdge#3792]
### Summary

The `--lora-model-dir` CLI option of stable-diffusion.cpp is used to specify the directory of lora models. To run with LoRA, it is required to support the CLI option in `wasmedge_stablediffusion` plugin.

```bash
--lora-model-dir [DIR]             lora model directory
```

Reference: https://github.com/leejet/stable-diffusion.cpp/blob/master/docs/flux.md#flux-dev-q8_0-with-lora

### Details

As a reference, [Run with LoRA](https://github.com/leejet/stable-diffusion.cpp/blob/master/docs/flux.md#run-with-lora) shows a simple example about how to use `--lora-model-dir` CLI option of sd.cpp.

**Comment by hydai** [comment]
@apepkuss 
It seems like we already supported this feature in the SD plugin. Maybe the remaining thing is to have a function from the Rust SDK to use it. Ref: https://github.com/WasmEdge/WasmEdge/blob/cf6a8787dbb1e0c4db1c3e6d244c856bbd3222c3/plugins/wasmedge_stablediffusion/sd_func.cpp#L222-L226

**Comment by apepkuss** [comment]
@hydai Yeah, I'll provide support for the interface in `wasmedge_stable_diffusion` crate. Thanks!
