### ISSUE TITLE
feat: Support the whisper plugin on GPU

### ISSUE THREAD

**Issue by alabulei1** [WasmEdge/WasmEdge#3796]
### Summary

Now the whisper plugin on the CPU is great. However, when it processes a video with 60 minutes, it will take about 30 minutes to get the final results.

### Details

Support the whisper plugin on the GPU machine to improve the performance

**Comment by hydai** [comment]
@q82419 
Please check if we can have a build for the Metal and CUDA frameworks.

**Comment by q82419** [comment]
We fetched the `whisper.cpp` for an old and stable version (`v1.6.2`), which was released several months ago.
From then, the `whisper.cpp` synchronized `ggml` with lots of changes, including the options about hardware supporting.
For supporting CUDA and Metal, we should refactor our code and update the `whisper.cpp` dependency first.

**Comment by q82419** [comment]
#3766 will turn on Metal automatically on Apple devices.

**Comment by hydai** [comment]
Fixed.
