### ISSUE TITLE
bug: `INode::fdWrite` sometimes returns 0 incorrectly on Windows

### ISSUE THREAD

**Issue by TBBle** [WasmEdge/WasmEdge#3811]
### Summary

While trying to replicate a read-slowdown bug observed in a Rust project, I found that sometimes `File::write_all` was reporting `WRITE_ALL_EOF` failure despite writing all its data.

On examination, it seems that `File::write` was sometimes returning `Ok(0)` despite data having been written, and this appears to be bubbling up from 

### Current State

Given this repro case in Rust:
```rust
// https://github.com/WasmEdge/WasmEdge/issues/3811
use std::fs::File;
use std::io::{Error, Write};

fn inspect_failure(e: &Error, attempts: usize, buffer_size: usize) {
    assert_eq!(e.kind(), std::io::ErrorKind::WriteZero);
    let expected_size: u64 = (attempts * buffer_size).try_into().unwrap();
    let filesize = std::fs::metadata("tmp.txt").unwrap().len();
    println!("Unexpected failure seen; after {attempts} loops of writing a {buffer_size} string ({expected_size} expected bytes), filesize was {filesize}.");
    assert_eq!(expected_size, filesize);
}

fn main() -> std::io::Result<()> {
    const BUF: &[u8] =
        "This textline will be repeated multiple times as part of a test\n".as_bytes();
    assert_eq!(BUF.len(), 64);
    let mut output = File::create("tmp.txt")?;

    for attempts in 1..=1024 {
        output
            .write_all(BUF)
            .inspect_err(|err| inspect_failure(err, attempts, BUF.len()))?;
    }
    Ok(())
}
```

the program fails more often than it passes.

Note that `File::write_all`'s implementation is to repeatedly call `File::write` with the given buffer until it is empty, and it throws an error if `File::write` reports a 0-byte success. (If the buffer is already empty, `File::write` is not called.)

Per Rust's `Write::Write` trait documentation:
```
    /// If this method consumed `n > 0` bytes of `buf` it must return [`Ok(n)`].
    /// If the return value is `Ok(n)` then `n` must satisfy `n <= buf.len()`.
    /// A return value of `Ok(0)` typically means that the underlying object is
    /// no longer able to accept bytes and will likely not be able to in the
    /// future as well, or that the buffer provided is empty.
```

I did have a simpler repro which open-coded `File::write_all` and confirmed that the failure was always coming through on the first loop, so there was no OS interrupts or partial writes being seen, which makes sense for such a small buffer.

I believe this to be a bug on the WasmEdge side because, per my repro, the data _was_ written by the call that returned `Ok(0)`, so I suspect the bug is that in `INode::fdWrite`; specifically, there's a code-path in [this block](https://github.com/WasmEdge/WasmEdge/blob/0.14.1/lib/host/wasi/inode-win.cpp#L1210-L1227) where `NWritten += NumberOfBytesWrite` is not called, even though bytes were written, and no error was returned to the caller. I can't immediately see the faulty code path, since it seems like the only way to not call that addition is to set Result. And in this case, there's only one IOV.

I _suspect_ the fix is to _aways_ call `NWritten += NumberOfBytesWrite` after `GetOverlappedResult`, irrespective of the value of the result, so that we do not accidentally signal EOF due to a (valid) partial write.

Looking at the code, the failure-path loop that calls `GetOverlappedResult` on the remaining cancelled operations may wipe out the number of bytes written, so I think we should be adding `NWritten` immediately after `GetOverlappedResult` in all cases, before looking at the status code. (This probably applies to all 8 calls to `GetOverlappedResult` in this file, I think).

### Expected State

All 65kb of data should be written and no errors raised.

### Reproduction steps

```pwsh
cargo new wasmedge-3811
cd wasmedge-3811
# Populate src/main.rs with the above repro case however you see fit
$Env:CARGO_TARGET_WASM32_WASIP1_RUNNER="wasmedge --dir .:."
cargo run --target wasm32-wasip1
```

### Any logs you want to share for showing the specific issue

```console
> cargo run --target wasm32-wasip1 
   Compiling wasmedge-3811 v0.1.0 (C:\Users\paulh\Rust\wasmedge-3811)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.61s
     Running `wasmedge --dir .:. target\wasm32-wasip1\debug\wasmedge-3811.wasm`
Unexpected failure seen; after 1 loops of writing a 64 string (64 expected bytes), filesize was 64.
Error: Error { kind: WriteZero, message: "failed to write whole buffer" }
error: process didn't exit successfully: `wasmedge --dir .:. target\wasm32-wasip1\debug\wasmedge-3811.wasm` (exit code: 1)
```

Note that other failure counts are possible, e.g.,
```console
Unexpected failure seen; after 25 loops of writing a 64 string (1600 expected bytes), filesize was 1600.
```

### Components

CLI, Rust SDK

### WasmEdge Version or Commit you used

0.14.1

### Operating system information

Windows 11 (Microsoft Windows [Version 10.0.22631.4169])

### Hardware Architecture

x86_64

**Comment by TBBle** [comment]
I attempted to implement the above-described solution in #3812, but it didn't appear to fix things, so more debugging is needed.

At worst, somehow `GetOverlappedResult` can validly return `TRUE` and report writing zero bytes despite having actually written bytes, and it is totally undocumented. Then we'd have a significant semantic mismatch, as Rust expects `write`/`NtWriteFile` semantics from `File;;write`, and `io::Write` documents a 0-length write to mean "File closed" or similar.

One thing I'll note is that when I had my open-coded `write_all` implementation, putting a `println!` inside the loop seemed to make it stop reproducing, suggesting that either performing other IO or simply sleeping might make the problem go away, suggesting the failure involves some kind of thread/timing problem.

**Comment by hydai** [comment]
Hi @TBBle 
Thanks for your detailed report; this helps a lot!
We have a PR for fixing issue #3870. Please apply this patch and see if the problem persists.

**Comment by TBBle** [comment]
I grabbed `WasmEdge-0.14.1-134-gadf6c36b-windows.zip.zip` from #3870's [CI run](https://github.com/WasmEdge/WasmEdge/actions/runs/11792816460) and tried it locally, and it seems to have fixed the issue.

```console
> Env:CARGO_TARGET_WASM32_WASIP1_RUNNER="$PWD\WasmEdge-0.14.1-134-gadf6c36b-windows\bin\wasmedge --dir .:."
> cargo run --target wasm32-wasip1 --release ; dir .\tmp.txt
   Compiling wasmedge-3811 v0.1.0 (C:\Users\paulh\Rust\wasmedge-3811)
    Finished `release` profile [optimized] target(s) in 0.47s
     Running `C:\Users\paulh\Rust\wasmedge-3811\WasmEdge-0.14.1-134-gadf6c36b-windows\bin\wasmedge --dir .:. target\wasm32-wasip1\release\wasmedge-3811.wasm`

    Directory: C:\Users\paulh\Rust\wasmedge-3811

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          12/11/2024 10:58 PM          65536 tmp.txt
```

(Same result over multiple runs, with the current WasmEdge release, it failed 5/5 times as shown in the initial bug report.)

----

A "quick" test suggests that it hasn't fixed the Windows-only very slow file reading that I was originally looking into when I hit this issue, but I expect that is a separate issue anyway, and I don't recall putting together a reproducer for it. I don't even remember how `File::write_all` was related... Maybe I was writing a reproducer, but if so, I don't know where I put it.
