### ISSUE TITLE
Have Rust's rusqlite crate running on WasmEdge just like it runs on Wasmtime

### ISSUE THREAD

**Issue by JohnFrrr** [WasmEdge/WasmEdge#3816]
### Summary

[This example](https://github.com/rusqlite/rusqlite/tree/master/examples/persons) in the [rusqlite](https://docs.rs/rusqlite/latest/rusqlite/) crate repository shows in the readme how to compile it for wasm32-wasi and run with wasmtime.
It would be amazing to be able to use this crate in WasmEdge as well to develop Rust apps using SQLite as database but when I try to run it I get the errors below:
```
[2024-10-06 16:00:58.473] [error] instantiation failed: unknown import, Code: 0x302
[2024-10-06 16:00:58.473] [error]     When linking module: "env" , function name: "__extenddftf2"
[2024-10-06 16:00:58.473] [error]     At AST node: import description
[2024-10-06 16:00:58.473] [error]     This may be the import of host environment like JavaScript or Golang. Please check that you've registered the necessary host modules from the host programming language.
[2024-10-06 16:00:58.473] [error]     At AST node: import section
[2024-10-06 16:00:58.473] [error]     At AST node: module
```

Would it be difficult to make it work in WasmEdge considering that it already compiles for wasm32-wasi?

**Comment by hydai** [comment]
It's so weird that wasmtime can execute a standard wasm that wasmedge cannot.

Could you please share the steps you took to build this wasm?
Because I cannot reproduce this issue.

![CleanShot 2024-10-07 at 03 50 34](https://github.com/user-attachments/assets/dcff0d89-2918-418b-976a-6603539163ca)

**Comment by hydai** [comment]
Here is the command I used:

```
export WASI_SDK_PATH=/home/hydai/workspace/tmp/rusqlite/wasi-sdk-24.0-x86_64-linux
export CC_wasm32_wasi="${WASI_SDK_PATH}/bin/clang --sysroot=${WASI_SDK_PATH}/share/wasi-sysroot"
cargo build --example persons --target wasm32-wasi --release --features bundled
wasmtime --version
wasmtime target/wasm32-wasi/release/examples/persons.wasm
wasmedge -v
wasmedge target/wasm32-wasi/release/examples/persons.wasm
```

**Comment by JohnFrrr** [comment]
I thought it could be my macOs but I tried in a fresh ubuntu container and I had the same error... Maybe it's an arm64-only issue? (using Macbook Pro M2)

Here is the command I used:
```
export WASI_SDK_PATH=/home/wasi-sdk-24.0-arm64-linux
export CC_wasm32_wasi="${WASI_SDK_PATH}/bin/clang --sysroot=${WASI_SDK_PATH}/share/wasi-sysroot"
cargo build --example persons --target wasm32-wasi --release --features bundled
wasmedge target/wasm32-wasi/release/examples/persons.wasm
```
My terminal output:
![image](https://github.com/user-attachments/assets/3e567dc4-23de-4974-965a-98bd9867ca9b)

**Comment by hydai** [comment]
Could you please run the same wasm with wasmtime on the macOS?

**Comment by hydai** [comment]
The reason is that your error message shows that the wasm is trying to import an unknown function, which is `env::__ __extenddftf2`. This is not a known function defined in any wasm spec.

**Comment by JohnFrrr** [comment]
Trying with wasmtime I got the same error:
```
Error: failed to run main module `target/wasm32-wasi/release/examples/persons.wasm`

Caused by:
    0: failed to instantiate "target/wasm32-wasi/release/examples/persons.wasm"
    1: unknown import: `env::__extenddftf2` has not been defined
```
Found [this similar issue](https://github.com/WebAssembly/wasi-sdk/issues/361) about this `__extenddftf2` function but the suggested `export LIBSQLITE3_FLAGS="-DLONGDOUBLE_TYPE=double"` before build solution didn't work either.

**Comment by hydai** [comment]
It seems like there is nothing to do from the runtime side since this symbol is impossible to provide from our end. One interesting thing is that the error only occurs on the arm64 target, while the x64 target works.

**Comment by hydai** [comment]
Also, I found the upstream is going to support wasm32-unknown-unknown: https://github.com/rusqlite/rusqlite/pull/1010
If this PR applies, it should fix this error.

**Comment by JohnFrrr** [comment]
Thanks, I'll keep an eye on it.

**Comment by hydai** [comment]
Hi @JohnFrrr 
Since this issue is not related to the runtime (WasmEdge/wasmtime), should we close it?

**Comment by JohnFrrr** [comment]
Hi, yes I think so... If a PR to this repo can't fix it, it doesn't belong here. Thank you for your attention!
