### ISSUE TITLE
feat: Allow user-specified piper parameters in audio speech request

### ISSUE THREAD

**Issue by apepkuss** [WasmEdge/WasmEdge#3817]
### Summary

The following `Piper` parameters listed below are defined as fields of the [RunConfig struct](https://github.com/WasmEdge/WasmEdge/blob/master/plugins/wasi_nn/piper.h#L25-L67) in the piper plugin:

- OutputType
- SpeakerId
- NoiseScale
- LengthScale
- NoiseW
- SentenceSilenceSeconds
- JsonInput
- PhonemeSilenceSeconds

From the perspective of users' view, these parameters should be allowed to set in requests that are then passed to the server. According to the [example](https://github.com/second-state/WasmEdge-WASINN-examples/blob/master/wasmedge-piper/src/main.rs#L3-L11), however, the parameters are set by the `build_from_bytes` interface ONLY while creating a Graph instance. Is it possible to introduce `Metadata` (like used in `ggml` plugin) to allow to set the parameters at runtime.

### Details

NA.

**Comment by hydai** [comment]
Hi @PeterD1524,  
I think that the Piper backend supports the above options during the initialization time. Would it be possible to have these options changed during execution time inside the `setinput` function, just like what we did in the llama.cpp plugin: https://github.com/WasmEdge/WasmEdge/blob/master/plugins/wasi_nn/ggml.cpp#L846-L859?

**Comment by PeterD1524** [comment]
Hi, could I get some clarification? Please consider the following scenario. `"default"` represents the default value chosen by Piper or the model.

The initial parameters:

```json
{
  "output_type": "default",
  "speaker": "default",
  "noise_scale": "default",
  "length_scale": "default",
  "noise_w": "default",
  "sentence_silence": "default",
  "phoneme_silence": "default"
}
```

Then you called `set_input` with `{"noise_scale":1.0}`. The parameters became:

```json
{
  "output_type": "default",
  "speaker": "default",
  "noise_scale": 1.0,
  "length_scale": "default",
  "noise_w": "default",
  "sentence_silence": "default",
  "phoneme_silence": "default"
}
```

Later you called `set_input` again with `{"length_scale":2.0}`. What do you expect the parameters to be?

A:

```json
{
  "output_type": "default",
  "speaker": "default",
  "noise_scale": "default",
  "length_scale": 2.0,
  "noise_w": "default",
  "sentence_silence": "default",
  "phoneme_silence": "default"
}
```

B:

```json
{
  "output_type": "default",
  "speaker": "default",
  "noise_scale": 1.0,
  "length_scale": 2.0,
  "noise_w": "default",
  "sentence_silence": "default",
  "phoneme_silence": "default"
}
```

A or B?

**Comment by PeterD1524** [comment]
I am also thinking of dropping the `json_input` parameter.
It has the same functionality with the `set_input` approach but limited to one-time overriding the `speaker` parameter. It will allow passing an input like `{"text":"hello","speaker_id":2}` to choose another speaker. It exists to match the behavior of the original Piper command-line program.

I think the behavior will be ambiguous if the `json_input` approach and the `set_input` approach coexist.

Another way is to extend the `json_input` functionality with more parameters (`output_type`, `noise_scale`, etc.) without using the `set_input` approach.

**Comment by apepkuss** [comment]
> Hi, could I get some clarification? Please consider the following scenario. `"default"` represents the default value chosen by Piper or the model.
> 
> The initial parameters:
> 
> ```json
> {
>   "output_type": "default",
>   "speaker": "default",
>   "noise_scale": "default",
>   "length_scale": "default",
>   "noise_w": "default",
>   "sentence_silence": "default",
>   "phoneme_silence": "default"
> }
> ```
> 
> Then you called `set_input` with `{"noise_scale":1.0}`. The parameters became:
> 
> ```json
> {
>   "output_type": "default",
>   "speaker": "default",
>   "noise_scale": 1.0,
>   "length_scale": "default",
>   "noise_w": "default",
>   "sentence_silence": "default",
>   "phoneme_silence": "default"
> }
> ```
> 
> Later you called `set_input` again with `{"length_scale":2.0}`. What do you expect the parameters to be?
> 
> A (each call of `set_input` for parameters is an one-time override):
> 
> ```json
> {
>   "output_type": "default",
>   "speaker": "default",
>   "noise_scale": "default",
>   "length_scale": 2.0,
>   "noise_w": "default",
>   "sentence_silence": "default",
>   "phoneme_silence": "default"
> }
> ```
> 
> B (each call of `set_input` for parameters is a permanent change):
> 
> ```json
> {
>   "output_type": "default",
>   "speaker": "default",
>   "noise_scale": 1.0,
>   "length_scale": 2.0,
>   "noise_w": "default",
>   "sentence_silence": "default",
>   "phoneme_silence": "default"
> }
> ```
> 
> A or B?

For me, `A` choice. @hydai What's your idea?

**Comment by hydai** [comment]
> I am also thinking of dropping the `json_input` parameter. It has the same functionality with the `set_input` approach but limited to one-time overriding the `speaker` parameter. It will allow passing an input like `{"text":"hello","speaker_id":2}` to choose another speaker. It exists to match the behavior of the original Piper command-line program.
> 
> I think the behavior will be ambiguous if the `json_input` approach and the `set_input` approach coexist.
> 
> Another way is to extend the `json_input` functionality with more parameters (`output_type`, `noise_scale`, etc.) without using the `set_input` approach.

We plan to use this plugin under the API server use case, which means the request will have various configurations and may have different parameters each time. Maybe extending the `json_input` is a good choice so we can have everything be one-time overriding; each request will produce one output only, and the related configuration will reset to default after the request is finished.

**Comment by PeterD1524** [comment]
Okay, I'll extend the `json_input` for one-time overriding. The model will have to be initialized (`build_from_bytes`) with `{"json_input":true}}` to use this feature.
