### ISSUE TITLE
bug: `max-len` and `split-on-word` of whisper plugin does not work

### ISSUE THREAD

**Issue by apepkuss** [WasmEdge/WasmEdge#3837]
### Summary

The `max-len` and `split-on-word` config params for whisper plugin does not work. The test code can be found [here](https://github.com/second-state/WasmEdge-WASINN-examples/blob/test-whisper/whisper-basic/src/main.rs#L15-L21). The test was run with [whisper-0.14.1-plugin-lts-8a2d406](https://github.com/second-state/WasmEdge-plugin-registry/releases/tag/whisper-0.14.1-plugin-lts-8a2d406).

whisper.cpp v1.7.1 shows the following results (irrelevant logs ignored) while running with `--max-len 1` and `--split-on-word true`:

```bash
(base) azureuser@sam-llm:/data/sam/downloads$ whisper -m ./ggml-medium.bin -f ./test.wav --split-on-word true -ml 1
error: input file not found 'true'
whisper_init_from_file_with_params_no_state: loading model from './ggml-medium.bin'
whisper_init_with_params_no_state: use gpu    = 1
whisper_init_with_params_no_state: flash attn = 0
whisper_init_with_params_no_state: gpu_device = 0
whisper_init_with_params_no_state: dtw        = 0
whisper_model_load: loading model
whisper_model_load: n_vocab       = 51865
whisper_model_load: n_audio_ctx   = 1500
whisper_model_load: n_audio_state = 1024
whisper_model_load: n_audio_head  = 16
whisper_model_load: n_audio_layer = 24
whisper_model_load: n_text_ctx    = 448
whisper_model_load: n_text_state  = 1024
whisper_model_load: n_text_head   = 16
whisper_model_load: n_text_layer  = 24
whisper_model_load: n_mels        = 80
whisper_model_load: ftype         = 1
whisper_model_load: qntvr         = 0
whisper_model_load: type          = 4 (medium)
whisper_model_load: adding 1608 extra tokens
whisper_model_load: n_langs       = 99
whisper_model_load:      CPU total size =  1533.14 MB
whisper_model_load: model size    = 1533.14 MB
whisper_init_state: kv self size  =   50.33 MB
whisper_init_state: kv cross size =  150.99 MB
whisper_init_state: kv pad  size  =    6.29 MB
whisper_init_state: compute buffer (conv)   =   28.55 MB
whisper_init_state: compute buffer (encode) =  170.15 MB
whisper_init_state: compute buffer (cross)  =    7.72 MB
whisper_init_state: compute buffer (decode) =   98.19 MB

system_info: n_threads = 4 / 4 | AVX = 1 | AVX2 = 1 | AVX512 = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | METAL = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | CUDA = 0 | COREML = 0 | OPENVINO = 0 | CANN = 0

main: processing './test.wav' (70656 samples, 4.4 sec), 4 threads, 1 processors, 5 beams + best of 5, lang = en, task = transcribe, timestamps = 1 ...


[00:00:00.000 --> 00:00:00.310]  
[00:00:00.310 --> 00:00:00.480]   This
[00:00:00.480 --> 00:00:00.720]   is
[00:00:00.720 --> 00:00:00.840]   a
[00:00:00.840 --> 00:00:01.320]   test
[00:00:01.320 --> 00:00:02.040]   record
[00:00:02.040 --> 00:00:02.430]   for
[00:00:02.430 --> 00:00:04.000]   Whisper.cpp

...
``` 

The following is the results of test code:

```bash
WASMEDGE_PLUGIN_PATH=/Users/sam/wasmedge-plugin-registry/whisper/8a2d406/plugin wasmedge --dir .:. ./target/wasm32-wasip1/release/whisper-basic.wasm ggml-medium.bin test.wav 
objc[35337]: Class GGMLMetalClass is implemented in both /Users/sam/wasmedge-plugin-registry/whisper/8a2d406/plugin/libwasmedgePluginWasiNN.dylib (0x1027402a0) and /Users/sam/.wasmedge/plugin/libwasmedgePluginWasiNN.dylib (0x102b78260). One of the two will be used. Which one is undefined.
Read model, size in bytes: 1533763059
Config: {"max-len":1,"split-on-word":true}
Loaded graph into wasi-nn with ID: Graph#0
Read input tensor, size in bytes: 141408
Recognized from audio: 
[00:00:00.000 --> 00:00:03.540]  This is a test record for Whisper.cpp
```

### Reproduction steps

NA

### Screenshots

![DESCRIPTION](LINK.png)

### Components

Others

### WasmEdge Version or Commit you used

0.14.1

### Operating system information

Ubuntu-20.04, macOS 14.6.1

### Hardware Architecture

x86_64, Apple Silicon M1Pro

**Comment by q82419** [comment]
@apepkuss 

It seems like the [build_from_bytes](https://github.com/second-state/wasmedge-wasi-nn/blob/ggml/rust/src/graph.rs#L136-L148) and [build_from_files](https://github.com/second-state/wasmedge-wasi-nn/blob/ggml/rust/src/graph.rs#L151-L166) are the old APIs without passing the metadata.
As the GGML example, they used the [build_from_cache](https://github.com/second-state/WasmEdge-WASINN-examples/blob/master/wasmedge-ggml/basic/src/main.rs#L100) API.
However, this API calls `load_by_name_with_config` host function, which the whisper backend not implemented.

Currently I think you can use the [metadata from input tensor](https://github.com/second-state/WasmEdge-WASINN-examples/tree/master/wasmedge-ggml#metadata) instead.

**Comment by apepkuss** [comment]
I'll try `set_input` to do it. Thanks!

**Comment by q82419** [comment]
Comment: I tried to set the log into the whisper.cpp source, and ensured that the options are set into the whisper parameter, but it still not work. I'll keep trying.

**Comment by apepkuss** [comment]
@q82419 Try the [test code](https://github.com/second-state/WasmEdge-WASINN-examples/blob/test-whisper/whisper-basic/src/main.rs#L15-L21) again with the latest whisper plugin ([wasmedge-0.14.1-plugin-lts-d259eed](https://github.com/second-state/WasmEdge-plugin-registry/releases/tag/wasmedge-0.14.1-plugin-lts-d259eed)). It seems the issue is not fixed. If I am wrong, please correct me and show me the right way to do it with the test code. Thanks a lot!

**Comment by q82419** [comment]
> @apepkuss
> 
> It seems like the [build_from_bytes](https://github.com/second-state/wasmedge-wasi-nn/blob/ggml/rust/src/graph.rs#L136-L148) and [build_from_files](https://github.com/second-state/wasmedge-wasi-nn/blob/ggml/rust/src/graph.rs#L151-L166) are the old APIs without passing the metadata. As the GGML example, they used the [build_from_cache](https://github.com/second-state/WasmEdge-WASINN-examples/blob/master/wasmedge-ggml/basic/src/main.rs#L100) API. However, this API calls `load_by_name_with_config` host function, which the whisper backend not implemented.
> 
> Currently I think you can use the [metadata from input tensor](https://github.com/second-state/WasmEdge-WASINN-examples/tree/master/wasmedge-ggml#metadata) instead.

@apepkuss please check this.

**Comment by apepkuss** [comment]
@q82419 Thanks for the reminder. It works. Thanks a lot!
