### ISSUE TITLE
[Install script] Remove APT dependencies

### ISSUE THREAD

**Issue by juntao** [WasmEdge/WasmEdge#384]
Since we are installing the manylinux build in the script, we do NOT need to install the dependency packages via APT.

Let's remove that section from the script altogether.

**Comment by SAtacker** [comment]
In #381 
I have added section like
```bash
_pkg_mgr() {
    if [ $PERM_ROOT == 1 ]; then
        apt "$@"
    fi
}
```
1. Here we can add the script to detect the package manager as well. This will be difficult to maintain as we'll have to look out for every package manager out there
2. Or we can check if `apt` is available and go with it , else do nothing

**Comment by juntao** [comment]
My suggestion is to remove APT installs altogether. The install script uses the manylinux build, which should not have those external dependencies. Please try it. 

This way, we will not depend on ANY linux package manager.

**Comment by SAtacker** [comment]
How does the below flow for the install script sound?
1. If `git` is not available --> default the version strings manually for now, 
(This will need changes on every new release)
2. If `wget` is not available, the script will check for `curl`  and if both are not available it'll display a message to have one of those and exit.

If there is some automation already done which I am unaware of (I have checked the GitHub actions) w.r.t. releases without `git` binary please let me know.

**Comment by juntao** [comment]
Let's assume that the user must have `git` and `wget` or `curl` installed in order to use the script. If they do not, just print a message asking the user to install and quit. Thanks.

**Comment by juntao** [comment]
Let's do #390 as well. Thanks.
