### ISSUE TITLE
bug: Certificate Problem downloading MacOS & 404 with wasi_logging

### ISSUE THREAD

**Issue by sscotti** [WasmEdge/WasmEdge#3871]
### Summary

I am a newbie just curious about this.  I tried using the script to install on a 2016 MacBook Pro running MacOS 12.7.6 (21H1320).  Minor hiccup initially because my Python version was not configured for the cacert.pem path.  Running the install certs script in the Python folder failed also with an SSL warning, so I fixed it manually by just downloading the latest:

[cacert.pem](https://github.com/certifi/python-certifi/blob/master/certifi/cacert.pem)

and then configuring that in my .zprofile for now:

```
export SSL_CERT_FILE=~/cacert.pem
export REQUESTS_CA_BUNDLE=~/cacert.pem
```

Then the install script that I used worked:

`curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- --plugins wasi_nn-ggml
`
But the script with the logging module failed:

`curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- --plugins wasi_logging wasi_nn-ggml
`

```
|============================================================|100.00 %INFO    - Downloaded
INFO    - Installing WasmEdge
INFO    - WasmEdge Successfully installed
INFO    - Downloading Plugin: wasi_logging
ERROR   - Download error from urllib: HTTP Error 404: Not Found
ERROR   - URL: https://github.com/WasmEdge/WasmEdge/releases/download/0.14.1/WasmEdge-plugin-wasi_logging-0.14.1-darwin_x86_64.tar.gz
```

vs:

```
macbookpro@MBP2016 ~ % curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- --plugins wasi_nn-ggml
Using Python: /Library/Frameworks/Python.framework/Versions/3.10/bin/python3 
WARNING - Experimental Option Selected: plugins
WARNING - plugins option may change later
INFO    - Compatible with current configuration
INFO    - Running Uninstaller
WARNING - SHELL variable not found. Using zsh as SHELL
INFO    - shell configuration updated
INFO    - Downloading WasmEdge
|============================================================|100.00 %INFO    - Downloaded
INFO    - Installing WasmEdge
INFO    - WasmEdge Successfully installed
INFO    - Downloading Plugin: wasi_nn-ggml
|============================================================|100.00 %INFO    - Downloaded
INFO    - Run:
```
I am interested in using this to run and possibly train LLM models from Hugging Face on the laptop and later probably on another machine (NVIDIA equipped laptop) or an Mx Chip Mac.

If any one has experience with that and want to walk me through the setup, let me know.

### Current State

Seems to have been fixed, although there is a 404 error with the logging module download.

If you are running Python on a Mac you apparently need to setup the host env or a virtual environment with the cacert.pem path specified.

### Expected State

Expected no error, but got the SSL cert error and no download.

### Reproduction steps

Described above.

### Screenshots

![DESCRIPTION](LINK.png)

### Any logs you want to share for showing the specific issue

I should say that after it is installed I do get this, so maybe logging is installed.
```

macbookpro@MBP2016 ~ % wasmedge --version
wasmedge version 0.14.1
 (plugin "wasi_logging") version 0.1.0.0
/Users/macbookpro/.wasmedge/lib/../plugin/libwasmedgePluginWasiNN.dylib (plugin "wasi_nn") version 0.10.1.0
```

### Components

CLI

### WasmEdge Version or Commit you used

 0.14.1

### Operating system information

MacOS 12.7.6 

### Hardware Architecture

x86_64

**Comment by hydai** [comment]
WASI-Logging has been bundled into libwasmedge since 0.14.1. This error is expected due to there is no wasi-logging plugin anymore.

**Comment by hydai** [comment]
It should be fine after removing the wasi-logging from the options. I am closing this issue. Feel free to reopen it if there are still any problems with them.
