### ISSUE TITLE
feat: Enable/disable the timestamps printing in whisper plugin

### ISSUE THREAD

**Issue by apepkuss** [WasmEdge/WasmEdge#3873]
### Summary

In whisper.cpp, there is a CLI option named `--no-timestamps`. The option is responsible for enabling or disabling the timestamps printing in the transcription result, for example:

- `--no-timestamps=false` (default setting)
  ```text
  [00:00:00.000 --> 00:00:08.000]   And so, my fellow Americans, ask not what your country can do for you,
  [00:00:08.000 --> 00:00:11.000]   ask what you can do for your country.
  ```
- `--no-timestamps=true`
  ```text
  And so my fellow Americans, ask not what your country can do for you, ask what you can do for your country.
  ```

It is also required for whisper plugin to support the feature of this CLI option. It should allow users to enable/disable the timestamps by requests.

### Details

Same as the summary.

**Comment by q82419** [comment]
I think you can summarize the options maybe we need again, as you mentioned in https://github.com/WasmEdge/WasmEdge/issues/3772

**Comment by apepkuss** [comment]
Yes，you're right basically. As for this feature request, it is from a recent use case. Before this case, I'm not sure if it is required or not to support it in our whisper plugin. Anyway, I'll check again if there are any other options needed to support. Thanks!

**Comment by apepkuss** [comment]
@hydai @q82419 The following whisper options also have to be supported. I divide them according to the priority. The options tagged with high priority are important for `VideoLangua` project to improve the efficiency of both development and verification. Thanks a lot!

- High priority

```bash
-bo N,     --best-of N            [5      ] number of best candidates to keep
-bs N,     --beam-size N       [5      ] beam size for beam search
-osrt,      --output-srt           [false  ] output result in a srt file
-olrc,      --output-lrc            [false  ] output result in a lrc file
-oj,         --output-json          [false  ] output result in a JSON file
-ojf,        --output-json-full   [false  ] include more information in the JSON file
-nt,         --no-timestamps   [false  ] do not print timestamps
```

- Low priority

```bash
-otxt,     --output-txt        [false  ] output result in a text file
-ovtt,     --output-vtt        [false  ] output result in a vtt file
-np,       --no-prints         [false  ] do not print anything other than the results
-pp,       --print-progress    [false  ] print progress
-nt,       --no-timestamps     [false  ] do not print timestamps
-ng,       --no-gpu            [false  ] disable GPU
-fa,       --flash-attn        [false  ] flash attention
```
