### ISSUE TITLE
feat: log `language` metadata in whisper plugin 

### ISSUE THREAD

**Issue by apepkuss** [WasmEdge/WasmEdge#3877]
### Summary

For the convenience of inspecting the `language` metadata, it would be better for whisper plugin to log the value of the metadata while [enable-log](https://github.com/WasmEdge/WasmEdge/blob/master/plugins/wasi_nn/wasinn_whisper.cpp#L231) is set to true (or, [enable-debug-log](https://github.com/WasmEdge/WasmEdge/blob/master/plugins/wasi_nn/wasinn_whisper.cpp#L240) is enabled).

### Details

When we test the whisper plugin, we cannot observe the value of the `language` metadata inside whisper plugin. However, this metadata plays key role in the practical application, such as in the case of audio transcriptions. For the convenience of inspecting the `language` metadata, it would be better for whisper plugin to log the value of the metadata while [enable-log](https://github.com/WasmEdge/WasmEdge/blob/master/plugins/wasi_nn/wasinn_whisper.cpp#L231) is set to true (or, [enable-debug-log](https://github.com/WasmEdge/WasmEdge/blob/master/plugins/wasi_nn/wasinn_whisper.cpp#L240) is enabled).

**Comment by grorge123** [comment]
You can pass the `enable-debug-log` option through the `set_input` function. The following code is a revised [wasi-nn-example](https://github.com/second-state/WasmEdge-WASINN-examples/tree/master/whisper-basic).
```
    let config_data = serde_json::to_string(&json!({"enable-debug-log": true}))
        .unwrap()
        .as_bytes()
        .to_vec();
    ctx.set_input(1, TensorType::U8, &[1], &config_data)
        .expect("Failed to set input");
    ctx.set_input(0, TensorType::F32, &[1, wav_buf.len()], &wav_buf)?;
```

If you enable `enable-debug-log` option, whisper will log `language` and other metadata in console.

Such as ![image](https://github.com/user-attachments/assets/59c7ef7d-f106-4db2-95cf-32367012bc44)

Or do you mean we need to write to a file?
