### ISSUE TITLE
Feat: Add `getaddrinfo` function in socket component

### ISSUE THREAD

**Issue by hydai** [WasmEdge/WasmEdge#388]
## Motivation

Currently, our socket functions can handle ipv4 and ipv6 address. However, we would like to have a helper function to handle the url string. That is `getaddrinfo`.

## Appendix

* https://man7.org/linux/man-pages/man3/getaddrinfo.3.html

**Comment by alittlehorse** [comment]
i will do it

**Comment by hydai** [comment]
Since the `getaddrinfo` and `freeaddrinfo` should be a pair function. This feature will need to implement both functions.

**Comment by alittlehorse** [comment]
'Socket component' refers to the various socket methods in `lib/host/wasi/wasifunc.cpp` ,such as   `WasiSockBind` or `WasiSockListen `? Do I need to add helper functions here and modify the corresponding .h files?

**Comment by alittlehorse** [comment]
What is the relationship between this issue and `https://github.com/second-state/wasmedge_wasi_socket`？thank you.

**Comment by hydai** [comment]
Yes, because the `getaddrinto` is a new function, you will add the definitions and implementation in `host/wasi`. 

Another thing is that there is no compiler directly supports WASI socket features. So an alternative way is providing a standalone SDK like `wasmedge_wasi_socket` for users to leverage the WASI socket functions. After you finish the `getaddrinfo` part, you will also need to update `wasmedge_wasi_socket` to add a corresponding helper functions such as [`sock_bind`](https://github.com/second-state/wasmedge_wasi_socket/blob/main/src/lib.rs#L24).

**Comment by alittlehorse** [comment]
`wasmedge_wasi_socket`sdk just like `WasmEdge-image`,right? Could you give me an sdk example implemented with similar ideas in second state repo?

**Comment by hydai** [comment]
Well, `wasmedge_wasi_socket` is like `wasmedge_tensorflow_interface`(https://github.com/second-state/wasmedge_tensorflow_interface). It's a rust library which allows users to leverage the wasi socket host functions from the high level language such as Rust.

**Comment by alittlehorse** [comment]
Wow, thank you!
