### ISSUE TITLE
feat: support `clip-g text encoder` in stable-diffusion plugin

### ISSUE THREAD

**Issue by apepkuss** [WasmEdge/WasmEdge#3880]
### Summary

To support [sd-3.5](https://huggingface.co/stabilityai/stable-diffusion-3.5-large), sd.cpp introduces `--clip_g` CLI option used to specify the path to the clip-g text encoder. It's also required for SD plugin to provide the feature.

As a reference, SD plugin supported `--clip_l` of sd.cpp before. `--clip_g` might be supported in a similar way, so that `wasmedge-stable-diffusion` crate can integrate it asap.

### Details

Same as the statements in Summary.

**Comment by apepkuss** [comment]
According to the commit history of sd.cpp, it provides support for sd-3.5 from `master-ac54e00`.

**Comment by hydai** [comment]
Hi @grorge123 
Please help with this issue. Thanks.
