### ISSUE TITLE
bug: WasmEdge ggml plugin on Jetson+CUDA11 does not exist

### ISSUE THREAD

**Issue by minhtribk12** [WasmEdge/WasmEdge#3885]
### Summary

I run the script to install WasmEdge as follow:
 curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install_v2.sh | bash
the script will (based on os, cuda, etc) download a plugin name: "WasmEdge-plugin-wasi_nn-ggml-cuda-11-0.14.1-ubuntu20.04_aarch64.tar.gz".
But seems like the file is not available in your release: https://github.com/WasmEdge/WasmEdge/releases/tag/0.14.1

### Current State

unable to install

### Reproduction steps

Run  curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install_v2.sh | bash on a Jetson developer kit with ubuntu 20.04 and cuda 11

### Screenshots

![DESCRIPTION](LINK.png)

### Components

Others

### WasmEdge Version or Commit you used

0.14.1

### Operating system information

Ubuntu 20.04

### Hardware Architecture

aarch64

**Comment by hydai** [comment]
Hi @minhtribk12 
Currently, we are not provided with the aarch64 + cuda11 pre-built release due to the lack of Jetson devices. If you want to try it, please build from source by yourself.

**Comment by minhtribk12** [comment]
Hi @hydai
Thanks, could you provide some instruction for build from source? :D

**Comment by hydai** [comment]
Because the Jetson devices have various models, please update the `CUDAARCHS` to your own one.
Also, if your CUDA compiler is not in the default path, please update `CMAKE_CUDA_COMPILER` to the correct one.

The following is our previous script on the Jetson devices.

```bash
export CUDAARCHS=72
export CXXFLAGS="-Wno-error"

_BUILD_NUMBER="${BUILD_NUMBER:-'b4067'}"
_OUTPUT_PREFIX="${OUTPUT_PREFIX:-'build'}"
_ARCH="${ARCH:-'x86_64'}"
_OUTPUT_NAME=WasmEdge-plugin-wasi_nn-ggml-cuda-0.14.1-ubuntu20.04_aarch64.tar.gz
_OUTPUT_DIR="${_OUTPUT_PREFIX}/plugins/wasi_nn"
_CMAKE_OPTIONS="-DWASMEDGE_PLUGIN_WASI_NN_BACKEND=GGML -DWASMEDGE_PLUGIN_WASI_NN_GGML_LLAMA_BLAS=OFF -DWASMEDGE_PLUGIN_WASI_NN_GGML_LLAMA_CUBLAS=ON"
_TAR_NAMES="wasi_nn-ggml"
_OUTPUT_BIN="libwasmedgePluginWasiNN.so"

echo "Debug info:"
echo "  Build number: ${_BUILD_NUMBER}"
echo "  Output prefix: ${_OUTPUT_PREFIX}"
echo "  Arch: ${_ARCH}"
echo "  Output name: ${_OUTPUT_NAME}"
echo "  Output directory: ${_OUTPUT_DIR}"
echo "  CMake options: ${_CMAKE_OPTIONS}"
echo "  Tar names: ${_TAR_NAMES}"
echo "  Output binary: ${_OUTPUT_BIN}"

git config --global --add safe.directory $(pwd)
rm -rf ${_OUTPUT_PREFIX}
echo "Building ${_TAR_NAMES} backend:"
cmake -B${_OUTPUT_PREFIX} -GNinja \
	-DCMAKE_CUDA_COMPILER=/usr/local/cuda/bin/nvcc \
	-DCMAKE_BUILD_TYPE=Release \
	-DWASMEDGE_BUILD_AOT_RUNTIME=OFF \
	-DWASMEDGE_USE_LLVM=OFF \
	-DWASMEDGE_BUILD_TOOLS=OFF \
	${_CMAKE_OPTIONS}
cmake --build ${_OUTPUT_PREFIX}

echo "Packaging ${_TAR_NAMES} backend:"
cp -f ${_OUTPUT_DIR}/${_OUTPUT_BIN} ${_OUTPUT_BIN}
tar -zcvf plugin_${_TAR_NAMES}.tar.gz ${_OUTPUT_BIN}

mv plugin_${_TAR_NAMES}.tar.gz ${_OUTPUT_NAME}
```

**Comment by minhtribk12** [comment]
Thanks for your support! :D
