### ISSUE TITLE
feat: WASI-NN PyTorch support for manylinux2014 aarch64 systems 

### ISSUE THREAD

**Issue by OrionKai** [WasmEdge/WasmEdge#3886]
### Summary

Enable support for manylinux2014 aarch64 systems in the WASI-NN PyTorch plugin

### Details

Currently, the WASI-NN PyTorch plugin only supports manylinux2014 x86_64 systems. I'd like to ask about the feasibility of adding support for manylinux2014 aarch64 systems in the near future, as I'd like to experiment with running code using this plugin on a Raspberry Pi 3.

**Comment by hydai** [comment]
Hi @OrionKai 
The manylinux2014 distro is deprecated due to the CentOS 7 is EOL. We are no longer support this distro. However, you can still try to build from source by yourself.

**Comment by OrionKai** [comment]
Hi @hydai, thank you for your prompt reply! I understand and will try to build from source. Will support for any other aarch64 systems be added in the near future?

**Comment by hydai** [comment]
We do want to support it, but not in the near future. Could you please raise an issue for this so we will know there is a need for this hardware target? And it could be one of the milestones in our next phase.

**Comment by hydai** [comment]
Since CentOS 7 is EOL, we have no plans for supporting this platform.
