### ISSUE TITLE
WasmEdge Community meeting on 3rd Dec

### ISSUE THREAD

**Issue by alabulei1** [WasmEdge/WasmEdge#3887]
### Summary

We hold a monthly [community meeting](https://wasmedge.org/docs/contribute/community#community-meeting) to showcase community-created content, introduce new features, review upcoming milestones, and engage in Q&A with the WasmEdge community. Everyone is welcome, and we encourage you to attend or present a session!

This issue aims to foster discussion within the WasmEdge community about potential topics for the meeting. If you have a topic you want to present or learn more about, please comment with your name and a brief description of the topic.

## Agenda
* Introduction
* Session 1: Demo: Datasance PoT --- Emirhan Durmus
* Session 2: TalkTalk: a voice to voice application using LlamaEdge -- Sam Liu
* Session 3:  How to bake a WasmEdge systemd-sysext image and use it with Flatcar -- Hydai
* Open Discussion
* Closing

### Appendix

Time: The first Tuesday of each month at 11PM Hong Kong Time/ 7AM PST.

[Public meeting agenda/notes](https://docs.google.com/document/d/1iFlVl7R97Lze4RDykzElJGDjjWYDlkI8Rhf8g4dQ5Rk/edit#) | [Zoom link](https://us06web.zoom.us/j/88282362606?pwd=UFhOdzlVKyswdW43c21BKy9DdkdyUT09)

**Comment by alabulei1** [comment]
Hi @apepkuss , do you want to share the talktalk project?

**Comment by apepkuss** [comment]
Of course. I'll give a presentation about how to use LlamaEdge API servers to create [talktalk app](https://github.com/LlamaEdge/talktalk?tab=readme-ov-file). Thanks!

**Comment by emirhandurmus** [comment]
@alabulei1 as discuss on the slack, I'll present our Enterprise Open Source Dsitirbuted Edge Computing platform which is called Datasance PoT. It is an Enterprise version of Eclipse ioFog. I'll discuss  both about the project and platform features, how users can manage,run,deploy both traditional and WasmEdge containers on Edge devices.  Also would like to discuss how and anyone can install containerd-wamsedge-shim from our Linux artifact repository as a repm or deb pacakage.

**Comment by hydai** [comment]
I plan to talk about how to bake a WasmEdge systemd-sysext image and use it with Flatcar.

**Comment by hydai** [comment]
@alabulei1 
Should we close this issue since it's finished?
