### ISSUE TITLE
[Install] Provide an one-line install script

### ISSUE THREAD

**Issue by juntao** [WasmEdge/WasmEdge#390]
Allow the install script to be invoked in one line. Like Rust's install process.

**Comment by SAtacker** [comment]
Does this mean that I'll have to remove `bashisms` from this script so that it is compatible with `shell`?

**Comment by juntao** [comment]
I guess the one liner could pipe to bash?

curl url | bash

Something like that?

**Comment by SAtacker** [comment]
Yes that would work with bash

**Comment by SAtacker** [comment]
Where will this oneliner be hosted ?

**Comment by juntao** [comment]
On GitHub. You can our current instruction here. We will just combine the 3 lines into one:

https://github.com/WasmEdge/WasmEdge/blob/master/docs/install.md

**Comment by SAtacker** [comment]
So, I'll change it to `wget -qO- https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash`
