### ISSUE TITLE
bug: static version of wasmedge gives error messages before executing

### ISSUE THREAD

**Issue by profitgrowinginnovator** [WasmEdge/WasmEdge#3904]
### Summary

I compiled a static version:
```
RUN --mount=type=bind,target=/src,source=. \
    cmake -S /src -B /build -G Ninja \
#        -DCMAKE_BUILD_TYPE=MinSizeRel \ [tried this as well]
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
        -DCMAKE_INSTALL_PREFIX="/install" \
        # For cross compiling
        -DCMAKE_TOOLCHAIN_FILE="$(xx-toolchain)" \
        -DWASMEDGE_BUILD_PACKAGE="TGZ" \
        -DWASMEDGE_USE_LLVM=ON \
        # Build just what we need
        -DWASMEDGE_BUILD_STATIC_LIB=ON \
        -DWASMEDGE_BUILD_TESTS=OFF \
        -DWASMEDGE_BUILD_SHARED_LIB=OFF \
        -DWASMEDGE_BUILD_TOOLS=ON \
        -DWASMEDGE_BUILD_PLUGINS=ON \
        -DWASMEDGE_BUILD_EXAMPLE=OFF \
        # Link llvm statically
        -DWASMEDGE_LINK_LLVM_STATIC=ON \
        -DWASMEDGE_LINK_TOOLS_STATIC=ON \
        # Disable extra dependencies
        -DWASMEDGE_DISABLE_LIBTINFO=ON \
        -DCMAKE_EXE_LINKER_FLAGS="-static" \
        -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=FALSE \
        -DCMAKE_SKIP_RPATH=ON
```

and when running wasmedge --help there are always error messages before wasmedge is executed:

```
#26 0.168 [2024-12-04 14:37:14.910] [error] wasmedge runtime failed: set null value into non-nullable value type, Code: 0x009
#26 0.168 [2024-12-04 14:37:14.910] [error] Address could not be matched to any shared object. Detailed error information is not available.
#26 0.168 [2024-12-04 14:37:14.910] [error] wasmedge runtime failed: set null value into non-nullable value type, Code: 0x009
#26 0.168 [2024-12-04 14:37:14.910] [error] Address could not be matched to any shared object. Detailed error information is not available.
```

### Current State

```
RUN /install/bin/wasmedge --help
#26 0.168 [2024-12-04 14:37:14.910] [error] wasmedge runtime failed: set null value into non-nullable value type, Code: 0x009
#26 0.168 [2024-12-04 14:37:14.910] [error] Address could not be matched to any shared object. Detailed error information is not available.
#26 0.168 [2024-12-04 14:37:14.910] [error] wasmedge runtime failed: set null value into non-nullable value type, Code: 0x009
#26 0.168 [2024-12-04 14:37:14.910] [error] Address could not be matched to any shared object. Detailed error information is not available.
#26 0.168 USAGE
#26 0.168 	/install/bin/wasmedge [SUBCOMMANDS] [OPTIONS] [--] WASM_OR_SO [ARG ...]
```

### Expected State

```
RUN /install/bin/wasmedge --help
#26 0.168 USAGE
#26 0.168 	/install/bin/wasmedge [SUBCOMMANDS] [OPTIONS] [--] WASM_OR_SO [ARG ...]
```

### Reproduction steps

1. build as described above
2. run with --help

### Screenshots

![DESCRIPTION](LINK.png)

### Components

CLI

### WasmEdge Version or Commit you used

0.14.1

### Operating system information

Ubuntu 24.04

### Hardware Architecture

X86_64

**Comment by profitgrowinginnovator** [comment]
Of course. 
`# syntax=docker/dockerfile:1.5-labs

ARG XX_VERSION=1.2.1
ARG ALPINE_VERSION=3.16
# alpine 3.16 ships with llvm 13.
# alpine 3.17 and 3.18 do not ship lld-static.

FROM --platform=$BUILDPLATFORM tonistiigi/xx:${XX_VERSION} AS xx
FROM --platform=$BUILDPLATFORM alpine:${ALPINE_VERSION} AS base
COPY --from=xx / /

# Install host dependencies
RUN apk add bash cmake samurai g++ clang
SHELL [ "bash", "-c" ]

# Make a cmake toolchain file
RUN cat <<'EOT' > /usr/bin/xx-toolchain && chmod a+x /usr/bin/xx-toolchain
#!/bin/bash
mkdir -p /etc/xx-toolchains/
TOOLCHAIN_FILE="/etc/xx-toolchains/$(xx-clang --print-target-triple).cmake"
[ -f "$TOOLCHAIN_FILE" ] || cat <<EOF > "$TOOLCHAIN_FILE"
set(CMAKE_CROSSCOMPILING ON)
set(CMAKE_SYSROOT "$(xx-info sysroot)")
set(CMAKE_SYSTEM_NAME "Linux")
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSTEM_PROCESSOR "$(xx-info march)")
set(CMAKE_C_COMPILER "$(which clang)")
set(CMAKE_CXX_COMPILER "$(which clang++)")
set(CMAKE_ASM_COMPILER "$(which clang)")
set(CMAKE_AR "$(which ar)")
set(CMAKE_RANLIB "$(which ranlib)")
set(PKG_CONFIG_EXECUTABLE "$(xx-clang --print-prog-name=pkg-config)")
set(CMAKE_C_COMPILER_TARGET "$(xx-clang --print-target-triple)")
set(CMAKE_CXX_COMPILER_TARGET "$(xx-clang --print-target-triple)")
set(CMAKE_ASM_COMPILER_TARGET "$(xx-clang --print-target-triple)")
EOF
echo "$TOOLCHAIN_FILE"
EOT

FROM base AS config
ARG TARGETPLATFORM

RUN apk add git llvm-dev
RUN xx-apk add \
    g++ \
    llvm-dev llvm-static \
    lld lld-dev lld-static \
    zlib-dev zlib-static

# Fix LLVMConfig.cmake to account for the sysroot
RUN sed -i 's|/usr/lib/llvm|${CMAKE_SYSROOT}usr/lib/llvm|' $(xx-info sysroot)usr/lib/cmake/llvm*/LLVMConfig.cmake
# In cmake/Helper.cmake we assume that lld is installed alongside llvm, so copy files over
RUN cp $(xx-info sysroot)usr/lib/liblld*.a $(xx-info sysroot)usr/lib/llvm*/lib/
# Use the native version of llvm-config
RUN ! xx-info is-cross || cp -f /usr/lib/llvm*/bin/llvm-config $(xx-info sysroot)usr/lib/llvm*/bin/llvm-config

RUN --mount=type=bind,target=/src,source=. \
    cmake -S /src -B /build -G Ninja \
#        -DCMAKE_BUILD_TYPE=MinSizeRel \
 	-DCMAKE_BUILD_TYPE=Release \
	-DCMAKE_POSITION_INDEPENDENT_CODE=ON \
        -DCMAKE_INSTALL_PREFIX="/install" \
        # For cross compiling
        -DCMAKE_TOOLCHAIN_FILE="$(xx-toolchain)" \
        -DWASMEDGE_BUILD_PACKAGE="TGZ" \
        -DWASMEDGE_USE_LLVM=ON \
        # Build just what we need
        -DWASMEDGE_BUILD_STATIC_LIB=ON \
        -DWASMEDGE_BUILD_TESTS=OFF \
        -DWASMEDGE_BUILD_SHARED_LIB=OFF \
        -DWASMEDGE_BUILD_TOOLS=ON \
        -DWASMEDGE_BUILD_PLUGINS=ON \
        -DWASMEDGE_BUILD_EXAMPLE=OFF \
        # Link llvm statically
        -DWASMEDGE_LINK_LLVM_STATIC=ON \
        -DWASMEDGE_LINK_TOOLS_STATIC=ON \
        # Disable extra dependencies
        -DWASMEDGE_DISABLE_LIBTINFO=ON \
    	-DCMAKE_EXE_LINKER_FLAGS="-static" \
    	-DCMAKE_INSTALL_RPATH_USE_LINK_PATH=FALSE \
    	-DCMAKE_SKIP_RPATH=ON

FROM  config AS build
RUN --mount=type=bind,target=/src,source=. \
    cmake --build /build --target install -- install package 
RUN wget https://github.com/second-state/rust-examples/releases/latest/download/hello.wasm
RUN /install/bin/wasmedge hello.wasm
#ENTRYPOINT [ "/install/bin/wasmedge","--help"]
`

**Comment by PeterD1524** [comment]
Looks like it is caused by `Plugin::getDefaultPluginPaths` in
https://github.com/WasmEdge/WasmEdge/blob/61db304fc4041dfae7cc736858a999a221260933/lib/plugin/plugin.cpp#L293-L295
To determine the default plugin path, it uses `dladdr` from the pathname of the shared object.
But you added `-DCMAKE_EXE_LINKER_FLAGS="-static"` and it is no longer a shared object, so the function fails to get the info and prints the error messages.

Probably not a big problem since plugins do not work with static libs. The message may be confusing though.
https://github.com/WasmEdge/WasmEdge/blob/61db304fc4041dfae7cc736858a999a221260933/CMakeLists.txt#L148

**Comment by profitgrowinginnovator** [comment]
Thanks for clarifying
