### ISSUE TITLE
feat: Monitor and export hardware info

### ISSUE THREAD

**Issue by DarumaDocker** [WasmEdge/WasmEdge#3914]
### Summary

I need a way to determine the hardware my LLM model is running on to dynamically analyze its performance. Could you provide an API for retrieving the machine's hardware information?

### Details

The structure can be something like:
```json
{
  "cpu": {
    "manufacturer": "Intel",
    "model": "Core i7-12700K",
    "cores": 12
  },
  "gpu": [
    {
      "manufacturer": "NVIDIA",
      "model": "RTX 3080",
      "memory": 10
    },
    {
      "manufacturer": "NVIDIA",
      "model": "RTX 3080",
      "memory": 10
    }
  ],
  "ram": {
    "total": 32
  },
  "os": {
    "name": "Ubuntu",
    "version": "22.04",
    "architecture": "x86_64"
  }
}
```

**Comment by hydai** [comment]
There are several easier ways to retrieve hardware information instead of implementing such functionalities inside the WASI-NN plugin; we have decided not to pursue this. Please try `nvidia-smi` or similar tools for this feature.
