### ISSUE TITLE
bug: install. on macOS

### ISSUE THREAD

**Issue by Bab64** [WasmEdge/WasmEdge#3918]
### Summary

The install. process on mac OS fails. I've Python 12 and 13 installed while wasmEdge tries to use 3.7 I guess?

curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash

### Current State

Initial install. message is "Using Python: /Library/Frameworks/Python.framework/Versions/3.12/bin/python3 "
and next errors:
File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 1344, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1336, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1382, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)

### Expected State

Working install. on macOS

### Reproduction steps

1. Install

### Components

CLI

### WasmEdge Version or Commit you used

Last

### Operating system information

macOS INTEL 64

### Hardware Architecture

macOS INTEL 64

**Comment by hydai** [comment]
Hi @Bab64

In case multiple versions of Python are installed, you can use `PYTHON_EXECUTABLE=<path> install.sh` to manually specify the one to use. If Python is still a problem, you can try `installer v2` via `curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install_v2.sh | bash`, which no longer uses Python to install packages.

**Comment by Bab64** [comment]
Thanks for your quick reply.
The "common" install. statement (curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash) **succeeds** with this config.: macOS 12.7.6 (21H1320) Darwin 21.6.0.
Install. shell seems to use Python 3.13?
I'm going to retry on my **second** Mac (at which occurred the install. problem) with your "new" install. statement above. Will publish a new comment on this ASAP... Regards

**Comment by Bab64** [comment]
Hi hydai.
Install. v2 (without Python) works fine on macOS. Regards.

**Comment by hydai** [comment]
Thanks for confirmation. It seems like the issue is resolved, is it fine to close this issue?

**Comment by Bab64** [comment]
Thanks for help and support
