### ISSUE TITLE
feat: Support Windows 10 for Install script.

### ISSUE THREAD

**Issue by rts-gordon** [WasmEdge/WasmEdge#3920]
### Summary

Hi there

  I install WasmEdge and WASI-NN to Windows 10 via install script , but it shows not support Windows_NT, can the install script support Windows 10? 

Thank you.

### Details

Install via Git CLI:
```
curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install_v2.sh | bash -s
``` 

errors:
```
Error: Detected Windows_NT-x86_64 - currently unsupported

Use --os and --arch to specify the OS and ARCH

        Please see --help
        If issue persists make a trace using -V and submit it to
https://github.com/WasmEdge/WasmEdge/issues/new?assignees=&labels=&template=bug_report.md

```

Install via CMD:
```
curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install_v2.sh | bash -s
``` 

errors, it shows Linux-x86_64 arch, not Windows.
```
Info: Detected Linux-x86_64
Info: WasmEdge Installation at /home/gordon/.wasmedge
Info: Fetching WasmEdge-0.14.1
```

**Comment by hydai** [comment]
Hi @rts-gordon 

1. I am unsure if the bash script can be executed correctly on Windows. I have heard that there is another command-line script called PowerShell for doing this.
2. Instead of providing a new shell script, we would like to have a new installer v3, which is written in Rust and handles most of the platforms. However, this is still in the design phase.
3. As a workaround, I think downloading the assets from the release page is easier than supporting a new script in the current installer.

Let me label this issue as a "good first issue."
We welcome contributions from those who use Windows for development.

**Comment by lhajouji** [comment]
Hi @hydai,

I’d like to take this issue and work on a solution. I’ll start by adding a check in the `install_v2.sh` script to detect Windows systems and display instructions for downloading the assets manually as a workaround. I will test it and submit a PR shortly.

Let me know if there’s any additional guidance or suggestions before I proceed.

Thank you!

**Comment by rts-gordon** [comment]
Hi @hydai  @lhajouji 

  Thanks for your quick reply. 

  Yes, it is easy to install WasmEdge from github release pages, but it need install WASINN together for [LlamaEdge](https://github.com/LlamaEdge/LlamaEdge) applications.  I have read the install script and WASINN documents, not found how to install WASINN as a WasmEdge plugin, can you please show how to do this and maybe you can impl this in install script.

 Thank you.

**Comment by hydai** [comment]
> Yes, it is easy to install WasmEdge from github release pages, but it need install WASINN together for [LlamaEdge](https://github.com/LlamaEdge/LlamaEdge) applications. I have read the install script and WASINN documents, not found how to install WASINN as a WasmEdge plugin, can you please show how to do this and maybe you can impl this in install script.

Just download one of these packages depending on your hardware, that's all:

![CleanShot 2024-12-18 at 11 07 50](https://github.com/user-attachments/assets/bc2f8f8f-9214-4b78-b358-e9ab088f2940)

**Comment by rts-gordon** [comment]
I download WasmEdge-0.14.1-windows.zip and WasmEdge-plugin-wasi_nn-ggml-0.14.1-windows_x86_64.zip, there are same folders for both zip file. 

How to install the plugin? Just unzip plugin file and replace the same folder of WasmEdge?  The file wasmedge.dll of plugin is very small than the same file of WasmEdge.

![image](https://github.com/user-attachments/assets/3ca9076b-8da5-443d-b504-a1de489cd5bc)

**Comment by hydai** [comment]
Hi @rts-gordon 

1. Do you need the AOT/JIT feature?
2. If `YES`, keep the bigger one, and copy the plugins folder `lib/wasmedge` to the bigger one.
3. If `NO`, just use the smaller one.

**Comment by rts-gordon** [comment]
@hydai 
  Thanks for your help.

  I installed WasmEdge, WASI-nn, and LlamaEdge, the version is :
```
c:\job\install\ai\llamaedge>wasmedge -v
wasmedge version 0.14.1
 (plugin "wasi_logging") version 0.1.0.0
```

run a llama model:
```
c:\job\install\ai\llamaedge>wasmedge --dir .:. --nn-preload default:GGML:AUTO:Meta-Llama-3-8B-Instruct-Q2_K.gguf llama-chat.wasm -p llama-3-chat
unknown option: nn-preload
```

there are errors: unknown option: nn-preload.

Is there something I missed?
Can you take a look at this? thank you.

**Comment by rts-gordon** [comment]
@hydai 

  thank you, it is works.
