### ISSUE TITLE
[Proposal] Python SDK for WasmEdge

### ISSUE THREAD

**Issue by SAtacker** [WasmEdge/WasmEdge#396]
## Motivation

Python is a well-known programming language and supports quick development for a variety of domains. 
WasmEdge has a `go` language SDK implemented [here](https://github.com/second-state/WasmEdge-go).
This proposal aims to implement a Python ( for the CPython implementation of Python ) SDK using the above implementation as a reference,

## Details

* Some rationale around performance- 
Python has never been intended for performance-critical applications while on the other hand, WasmEdge has different intentions. It is designed to be a lightweight and fast VM for Wasm. The idea behind python is that developers spend more time reading the code. Python SDK should be way easier to use. And as far as performance is considered, all of the code behind this package can be wrapped around the C-API to make it as closer to the native speed as possible.

* This SDK should be able to provide all the functions present in the C - API of WasmEdge (link given in the appendix).
* Stuff to look out for:
  * Data-types integrations for all the three python-c-wasm.
  * Safety (no memory access of host from `.wasm` modules) 
  * Potentially it is also possible to wrap around `WasmEdge` functionalities to support [Wasm C API](https://github.com/WebAssembly/wasm-c-api) if it doesn't already.

* The end goal should be to use WasmEdge as a backend and provide an Easy to use SDK over this.

## Appendix

* C - API for WasmEdge is already present. - [Docs](https://github.com/WasmEdge/WasmEdge/blob/master/docs/c_api.md#wasmedge-c-api-documentation)
* C - API for the CPython implementation of python is quite mature [without third-party tools](https://docs.python.org/3/extending/index.html#creating-extensions-without-third-party-tools) and `Boost.Python` is also available [Examples](https://github.com/TNG/boost-python-examples)

## Misc:

* I'll probably need help in this to make it as correct as possible if anything seems a bit off.
* Thanks a lot already :-D

**Comment by juntao** [comment]
This sounds good. Let's start from a simple API to start a standalone WasmEdge app (i.e., a Rust app compiled from main.rs). Then, we can have an API to start a function (ie., in reactor mode), pass in simple numeric parameters to the function, and receive the return value. Then, we can work to support `wasm-bindgen` for complex call arguments, such as strings and arrays.

Please create new issues for each small tasks along the way and link back to this issue. Thank you.

**Comment by juntao** [comment]
Please place the Python SDK in the bindings/python directory in this repo. Thanks.

**Comment by SAtacker** [comment]
Feel free to check [this]( https://satacker.github.io/WasmEdge/) out @juntao

**Comment by SAtacker** [comment]
Currently, the methods/classes are not at all finalized. This is just a hello world stage. But the setup feels okay for now. It uses `pytest` for small tests and a general `Makefile`

**Comment by juntao** [comment]
Can you provide an example for running a function in reactor mode? Ex: add.wasm in tools/wasmedge/examples

**Comment by SAtacker** [comment]
> Can you provide an example for running a function in reactor mode? Ex: add.wasm in tools/wasmedge/examples

Reactor mode will probably work similar to this.

For further implementation,I'll need to make a proper api structure for python as per the best practices followed.
This will need some looking around at standard documentations for it.

Several things like handling of kwargs, etc. is yet to be done even for this simple example which I haven't already because of the above mentioned subject.

And... I have midterms this coming week. I have to slow down here 😅

**Comment by SAtacker** [comment]
Closing this in favor of #2077
