### ISSUE TITLE
Unable to install using wget

### ISSUE THREAD

**Issue by shivay-fabric** [WasmEdge/WasmEdge#397]
## Description

Unable to install using wget on MacOS Big Sur - M1 chip

### Current State

```
Shivays-MacBook-Pro wasm-edge % sudo ./install.sh -p /usr/local 
./install.sh: line 40: getent: command not found
cut: illegal option -- -
usage: cut -b list [-n] [file ...]
       cut -c list [file ...]
       cut -f list [-s] [-d delim] [file ...]
tail: illegal option -- -
usage: tail [-F | -f | -r] [-q] [-b # | -c # | -n #] [file ...]
```

### Expected

wget should work 

## Environment

- Hardware Architecture: arm architecture ( Apple M1 ) 
- Operating system: MacOS Big Sur

**Comment by shivay-fabric** [comment]
@SAtacker

**Comment by SAtacker** [comment]
Thanks @shivay-fabric.
MacOs doesn't seem to support `getent` - [ref](https://serverfault.com/questions/694206/command-getent)
Sorry, I couldn't notice earlier as I didn't test it on macOS.

**Comment by juntao** [comment]
Hmm. I think MacOS is more complex. The current script installs the manylinux version. It is specifically for x86 Linux. For m1 Mac, we will need to detect the underlying platform and download the appropriate build package. TF dependency libraries also may not be available for the Mac platform.

**Comment by juntao** [comment]
Let me put together m1 install resources in the next couple of days and come back to this issue. Thanks.

**Comment by shivay-fabric** [comment]
@juntao any updates for Mac M1?

**Comment by hydai** [comment]
Hi @shivay-fabric 
I just uploaded pre-built binary for Mac M1: https://github.com/WasmEdge/WasmEdge/releases/download/0.8.2/WasmEdge-0.8.2-Darwin-M1.tar.gz

**Comment by hydai** [comment]
Hi @shivay-fabric 
Our install script supports macos M1. Please let me know if you have encountered problems :-)

If everything is fine, then I'll close this issue. Thanks.
