### ISSUE TITLE
[Proposal] Java SDK for WasmEdge

### ISSUE THREAD

**Issue by kenvifire** [WasmEdge/WasmEdge#398]
## Motivation

Provide Java SDK for WasmEdge VM.

## Details

- Wrap [ C APIs ](https://github.com/WasmEdge/WasmEdge/blob/master/docs/c_api.md#wasmedge-c-api-documentation) with Java JNI.

## Appendix

- I can work on this proposal.

**Comment by juntao** [comment]
This is great. Thank you! 

Please put your work in the bindings/java directory. We plan to use bindings/ for all language bindings in the future.

We look forward to your contributions!

**Comment by kenvifire** [comment]
Cool, thanks. @juntao Can you assign this issue to me?

**Comment by hydai** [comment]
Hi @kenvifire 
There is another issue which is your roadmap of the Java SDK. Should we move forward to that issue and close this one?

**Comment by kenvifire** [comment]
Sure, go ahead, I forgot this one.
