### ISSUE TITLE
Cannot install WasmEdge

### ISSUE THREAD

**Issue by ZHANGWENTAI** [WasmEdge/WasmEdge#412]
### Current State

Cannot install WasmEdge

## Environment

- Hardware Architecture: x86_64 
- Operating system: Ubuntu 16.04

## Steps to Reproduce
I use command ```wget -qO- https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash``` to install WasmEdge, the output is: 
```
No root permissions.
Detected Linux-x86_64
No path provided
Installing in /home/myusername/.wasmedge
WasmEdge Installation at /home/myusername/.wasmedge
Fetching WasmEdge-0.8.2

    Please see --help
    If issue perists make a trace using -V and submit it to
https://github.com/WasmEdge/WasmEdge/issues/new?assignees=&labels=&template=bug_report.md
```
but in the directory /home/myusername, there are no WasmEdge installed.

I wonder if there something wrong in the install script?

By the way, the ```rm -f``` opreation in the install script could be dangerous, I have lost my /root directory already on another CentOS server by using the command ```wget -qO- https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash``` with wrong arguments........

**Comment by hydai** [comment]
Hi @ZHANGWENTAI 

I tried to reproduce your issue, however, I cannot reproduce this error:

```
user@8785a5841606:~$ wget -qO- https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash
No root permissions.
sudo could not be found
Detected Linux-x86_64
No path provided
Installing in /home/user/.wasmedge
WasmEdge Installation at /home/user/.wasmedge
Fetching WasmEdge-0.8.2
WasmEdge-0.8.2-manylinux2014_x86_64. 100%[======================================================================>]  39.00M  31.3MB/s    in 1.2s
Installing WasmEdge-0.8.2-Linux in /home/user/.wasmedge/include
Installing WasmEdge-0.8.2-Linux in /home/user/.wasmedge/lib
Installing WasmEdge-0.8.2-Linux in /home/user/.wasmedge/bin
No extensions to be installed

source /home/user/.wasmedge/env to use wasmedge binaries
user@8785a5841606:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.7 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.7 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

Could you try to attach `-V` flag to the script and give us more information?

**Comment by ZHANGWENTAI** [comment]
I try again and the output is the same to yours....
I think I can close this issue.

**Comment by ZHANGWENTAI** [comment]
## Description

### Current State

Cannot install WasmEdge

## Environment

- Hardware Architecture: x86_64 
- Operating system: CentOS Linux release 7.9.2009 (Core)

## Steps to Reproduce

```
[root@node3 ~]# wget -qO- https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash
Detected Linux-x86_64
No path provided
Installing in /root
/bin
/sbin
/var/adm
/var/spool/lpd
/sbin
/sbin
/sbin
/var/spool/mail
/root
/usr/games
/var/ftp
/
/
/
/
/var/empty/sshd
/var/spool/postfix
/var/lib/chrony/.wasmedge
bash: line 389: $IPATH/env: ambiguous redirect
rm: cannot remove ‘/root’: Device or resource busy
rm: cannot remove ‘/root’: Device or resource busy
rm: it is dangerous to operate recursively on ‘/’
rm: use --no-preserve-root to override this failsafe
rm: it is dangerous to operate recursively on ‘/’
rm: use --no-preserve-root to override this failsafe
rm: it is dangerous to operate recursively on ‘/’
rm: use --no-preserve-root to override this failsafe
rm: it is dangerous to operate recursively on ‘/’
rm: use --no-preserve-root to override this failsafe
```
The command lead to uncertain behavior, and this time it lead to some local files deleted and I lost ssh connection to my server.

I do not want to bother you but it's really weird and cause serious demage. Could you reproduce the bug please? Thank you ：）

**Comment by hydai** [comment]
Here is my output:
```
[root@6c98323185a9 ~]# curl -o-  https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0sudo could not be found
Detected Linux-x86_64
100 14197  100 14197    0     0  49942      0 --:--:-- --:--:-- --:--:-- 49814
No path provided
Installing in /root/.wasmedge
WasmEdge Installation at /root/.wasmedge
Fetching WasmEdge-0.8.2
######################################################################## 100.0%
Installing WasmEdge-0.8.2-Linux in /root/.wasmedge/include
Installing WasmEdge-0.8.2-Linux in /root/.wasmedge/lib
Installing WasmEdge-0.8.2-Linux in /root/.wasmedge/bin
Installation of wasmedge-0.8.2 successfull
Installation of wasmedgec-0.8.2 successfull
No extensions to be installed

source /root/.wasmedge/env to use wasmedge binaries
[root@6c98323185a9 ~]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

And the `rm -rf` part, I've asked an issue #413. However, the `rm -rf` command will only be called when it uses the `default path (/path/to/user/home/.wasmedge)`.

**Comment by juntao** [comment]
@SAtacker Can you also take a look?

**Comment by SAtacker** [comment]
Okay, I am very sorry for this @ZHANGWENTAI , 
Because it did not show `sudo is not found` it found your $HOME to be the long list of files using `getent`
https://github.com/WasmEdge/WasmEdge/blob/4ee038d56488f63e5b856558560057c8e8eab193/utils/install.sh#L42 is erroneous 
This was referred from [here](https://superuser.com/questions/484277/get-home-directory-by-username).
Let me send a PR and remove the dangerous part anyway.

**Comment by SAtacker** [comment]
Your $HOME was found to be
```
Installing in /root
/bin
/sbin
/var/adm
/var/spool/lpd
/sbin
/sbin
/sbin
/var/spool/mail
/root
/usr/games
/var/ftp
/
/
/
/
/var/empty/sshd
/var/spool/postfix
/var/lib/chrony/.wasmedge
```

**Comment by SAtacker** [comment]
There were two mistakes I made, I should enclose the `$IPATH` in `" "` so that it does not split and would have saved @ZHANGWENTAI  right there and the other is it never occurred to me that $HOME directory would split

**Comment by hydai** [comment]
Oh, I noticed that we are on a different path.
I start the CentOS with `centos:7.9.2009` from docker hub, which doesn't contain `sudo` command by default. I think that's why I have a totally different result from @ZHANGWENTAI 's output.

Also, I would like to remove the `rm -rf` command with a path that may provide by a potentially dangerous variable. 
Maybe we should show a warning message or ask users' permission before we process the `rm -rf` command.
Or we should have a list which is installed by us, and then just remove these files and folders.

**Comment by hydai** [comment]
For example, Homebrew uninstaller will create a list and then only remove files from this list.

https://github.com/Homebrew/install/blob/master/uninstall.sh

**Comment by juntao** [comment]
Issue #389 discusses the uninstall options.

**Comment by ZHANGWENTAI** [comment]
Ok I'll test the fix later. Thank you all for your debugging, I close this issue now and follow up on the pr #416 .

**Comment by SAtacker** [comment]
Can we close this @ZHANGWENTAI ? (with apologies from me)

**Comment by ZHANGWENTAI** [comment]
It‘s ok. I can close this issue now.
