### ISSUE TITLE
Dangerous part in the install.sh

### ISSUE THREAD

**Issue by hydai** [WasmEdge/WasmEdge#413]
## Description

I found that the `$IPATH` will take from command line, and this `$IPATH` will be used to `rm -rf $IPATH` in `on_exit` function.
This is very dangerous if user set the `$IPATH` to `/` or `/usr/local`.

### Expected

We should not remove the whole folder. Instead, we should have a way to remove the specific files or a specific folder which contains only our data.
Or we should add a checkbox to ask users to make sure we can remove the `$IPATH`.

**Comment by SAtacker** [comment]
Thanks, @hydai. But it happens only if it is a default path.https://github.com/WasmEdge/WasmEdge/blob/650d72e2af87e6dbbb4ba92a59201d3e5d8fa865/utils/install.sh#L351
https://github.com/WasmEdge/WasmEdge/blob/650d72e2af87e6dbbb4ba92a59201d3e5d8fa865/utils/install.sh#L166

**Comment by hydai** [comment]
Ah-ha, you are right. Then, this issue is invalid.
I missed the `$default` variable.
