### ISSUE TITLE
[Rust SDK] Support wasm-bindgen

### ISSUE THREAD

**Issue by alabulei1** [WasmEdge/WasmEdge#421]
## Motivation

 Allow Rust apps to pass complex arguments to wasm functions

## Details

The SDK should correctly handle calling Rust functions with wasm-bindgen macros.

## Appendix

https://github.com/rustwasm/wasm-bindgen 

wasm-bindgen in JS SDK: https://www.secondstate.io/articles/getting-started-with-rust-function/

wasm-bindgen in Go SDK: https://www.secondstate.io/articles/extend-golang-app-with-webassembly-rust/

**Comment by hydai** [comment]
@alabulei1 Is this still available? Or do we already integrate it with wasmedge-bindgen?

**Comment by hydai** [comment]
Hi @apepkuss 
Do we already support wasmedge-bindgen in Rust SDK?

**Comment by apepkuss** [comment]
> Hi @apepkuss Do we already support wasmedge-bindgen in Rust SDK?

Yes. Rust SDK introduced the relevant [design](https://github.com/WasmEdge/wasmedge-rust-sdk/blob/main/src/dock.rs) to support `wasmedge-bindgen`. Also, [this example](https://github.com/second-state/wasmedge-rustsdk-examples/tree/main/wasmedge-bindgen) presents how to use it.

**Comment by hydai** [comment]
Closing it due to the issue being resolved.
