### ISSUE TITLE
[Rust SDK] Support adding host functions

### ISSUE THREAD

**Issue by alabulei1** [WasmEdge/WasmEdge#422]
## Motivation

Support adding Rust-based host functions to the runtime

## Details

In the Go and C SDKs, we have demonstrated that it is possible to add host functions to the WasmEdge runtime, which allows WebAssembly programs to call functions written in C or Go. We need to support that in Rust SDK as well

## Appendix

* The Go SDK host function example: https://github.com/second-state/WasmEdge-go-examples/tree/master/go_ExternRef

* The C SDK host function: https://github.com/WasmEdge/WasmEdge/blob/master/docs/c_api.md#Host-Functions

**Comment by ZhangHanDong** [comment]
Now only wasmedge-sys adds the host-func support, there should be an additional API layer on top of wasmedge-sdk, right?
