### ISSUE TITLE
LFX Workspace: Support WASI-Signature proposal

### ISSUE THREAD

**Issue by hydai** [WasmEdge/WasmEdge#424]
### Motivation
This is an umbrella issue for WASI-Signature.

### Details
@XingZYu Please describe your milestones in this issue.

**Comment by XingZYu** [comment]
# Roadmap & Milestones

1. Understand Wasm-signature proposal and relevant tools: 1 week
    - According to Wasm-signature proposal and previous discussion, 3 options are available for WasmEdge implementation, i.e. (b), (c) and (d) in "Discussed options" section of Wasm-signature proposal
    - Understand the benefits and different use-cases of these sign methods
    - Read the code of existing Wasm-signature tools to understand how *sign* and *verify* work
2. Implement the initial version of WasmEdge which supports signing Wasm modules: 4-5 weeks 
    - Update `wasmedge` binary with additional *sign* and *verify* command-line options
    - Implement basic functionality of `sign()` and `verify()` using option (b) in "Discussed options"
3. Add tests for Wasm-signature support in WasmEdge: 2 weeks

# Future Work

1. We noticed there're different signature options, they should fit into different use-case scenarios and our final implementation could integrate options (c) and (d) if possible

# Appendix

- [WebAssembly modules signatures](https://github.com/wasm-signatures/design)
- [Github: jedisct1/wasmsign](https://github.com/jedisct1/wasmsign)
- [Github: jedisct1/wasmsign2](https://github.com/jedisct1/wasmsign2)
- [Lucetc signature verification](https://bytecodealliance.github.io/lucet/Integrity-and-authentication.html#lucetc-signature-verification)

**Comment by XingZYu** [comment]
Workspace week 1:
- Read and understand Wasm-signature proposal
- Learn how to add new command line options from `argument_parser.h`

Note:
There might be two attempts while adding signature feature
- link to a existing library, or
- add as a function/module in WasmEdge

In the former case, we need to consider compatability problems (differnt OSs, architectures and platforms)

**Comment by XingZYu** [comment]
Workspace week 2:
- Implement subcommand `sign` and `verify` in argument parser

**Comment by XingZYu** [comment]
Workspace week 4:
- Complete `sign` method in `Signature` class, which accepts a parsed Wasm module and a signature byte array, and sign the module by adding a Custom Section containing the signature
- Add a third-party tool for signature algorithm (ed25519), consdier [this](https://github.com/GlitchedPolygons/GlitchEd25519.git) that fixed some bugs from [orlp/ed25519](https://github.com/orlp/ed25519) and contains CMakeLists 

Work in progress:
- Add a `keygen` function in `Signature` class for generating signature for Wasm binary
- Considering another option for `keygen`: use an existing tool for generating signature for Wasm files (e.g. [minisign](https://jedisct1.github.io/minisign/)), but it would bring some problems
  - Need some code rewriting to use it as a library
  - Only `keygen` command would be used (`-G` command line option in the case of [minisign](https://jedisct1.github.io/minisign/))

**Comment by XingZYu** [comment]
Workspace week 6:
- Implemented basic `verify` functionality
- Move `ed25519` package out of `thirdparty` and use CMake FetchContent to retrieve and build it
- Change current implementation that embeds a `SignatureEngine` in `vm` module to  executing sign and verify functions before vm init

Work in progress:
- Add tests for signature (including a test case that one Wasm module contains many customs sections)

**Comment by XingZYu** [comment]
Workspace week 11:
- Testing `sign` functionality
- Complete and fix bugs for `sign` and `verify`

**Comment by XingZYu** [comment]
Workspace week 12:
- Update test implementations in `SignatureTest`
- Testing CLI functionality of `sign` and `verify`
- Testing basic usage of `verify`
