### ISSUE TITLE
[Install] Support MacOS

### ISSUE THREAD

**Issue by juntao** [WasmEdge/WasmEdge#433]
## Motivation

Support MacOS in the install script

## Details

1 The script detects that the OS is Mac OS X.

2 It checks whether `brew` is installed. If not, ask the user to install `brew` and quit. https://brew.sh/

3 `brew install llvm`

4 Follow the regular process to install `WasmEdge-0.8.2-darwin_arm64.tar.gz` for M1 Macs and `WasmEdge-0.8.2-darwin_x86_64.tar.gz` for Intel Macs.

NOTE: We do NOT install extensions for `-e all` under Mac OS X. It is the same behavior as Linux aarch64.

**Comment by SAtacker** [comment]
I am closing this for now. Thanks.
