### ISSUE TITLE
[Challenge] Create a host function for WasmEdge

### ISSUE THREAD

**Issue by juntao** [WasmEdge/WasmEdge#444]
In this challenge, you will create a "host function" that allows Wasm  bytecode programs to "break the sandbox" and call functions external native shared libraries. Follow the instructions below, and send a link to your work in the comment. 

**Note:** Just fork the WasmEdge repo, and create a host function under `tools/wasmedge/examples /host_functions` in your own fork. Send us a pull request for your work to be showcased as an example!

## Steps:

1 Go through the QuickStart guide to create a C program that embeds WasmEdge.

https://github.com/WasmEdge/WasmEdge/blob/master/docs/c_api_quick_start.md

2 Go through the tutorial to register a C-based “host function” into WasmEdge, and run a Wasm program that calls this embedded function. 

https://github.com/WasmEdge/WasmEdge/blob/master/docs/c_api.md#Host-Functions

3 Create a new host function that calls a shared library on your system. It could be anything — SQLite, ffmpeg, git, anything you have on your system.

4 Create a wasm program that calls this host function. You could hand write a WAT file and then turn it into wasm. 

https://developer.mozilla.org/en-US/docs/WebAssembly/Text_format_to_wasm

https://webassembly.github.io/wabt/doc/wat2wasm.1.html

5 Create a complete C program to run this wasm program in an embedded WasmEdge, like in step #2.

Optional: Send your fork to us as a PR to be showcased as an official example.

**Comment by juntao** [comment]
Hi @JialuGong 

We'd love to see the host function you come up with. Send us a PR. Thanks. 

Cheers
Michael

**Comment by chinzhiweiblank** [comment]
Hi @juntao , I have created a host function under this [PR](https://github.com/chinzhiweiblank/WasmEdge/pull/1). It is very similar to the current example of `Add` because I don't know how to process strings in WasmEdge C's SDK. It is currently working but I would like to ask for help to improve the function.

```

WasmEdge_Result parse_json(void *Data, WasmEdge_MemoryInstanceContext *MemCxt,
                    const WasmEdge_Value *In, WasmEdge_Value *Out) {
    FILE *fp = fopen("test.json","r");
    char buffer[1024];
    fread(buffer, 1024, 1, fp);
    fclose(fp);

    struct json_object *number;
    json_object* parsedJson = json_tokener_parse(buffer);
    // string key = In[0];
    // json_object_object_get_ex(parsedJson, key, &value);
    // Out[0] = value;
    return WasmEdge_Result_Success;
}
```

Is there a way to get a string out of `In` and then return a string in `Out`?

**Comment by hydai** [comment]
@chinzhiweiblank Maybe you can try externref to pass the complex data structure: https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/en/src/extend/plugin/externref.md#passing-a-class

**Comment by hydai** [comment]
This is outdate, so I'm closing it.
