### ISSUE TITLE
[Install] Support Windows in the automated install script

### ISSUE THREAD

**Issue by juntao** [WasmEdge/WasmEdge#448]
Add Windows artifact support in the install script similar to what we will do for Mac OS in #433

**Comment by NIKU-SINGH** [comment]
Hey, can I work on this issue? I am beginner, could you tell me which file I need to work on in the repo

**Comment by juntao** [comment]
Sure. I assigned this to you. Please review our [install document](https://github.com/WasmEdge/WasmEdge/blob/master/docs/install.md) and [the install script](https://github.com/WasmEdge/WasmEdge/blob/master/utils/install.sh). Pay attention to how the script handles MacOS installs as the Windows process will be similar. You will need to

* Detect the Windows environment
* Detect required dependencies (e.g., git and llvm)
* Install the package (note)
* Add the env files to appropriate PowerShell config files

Note: I just checked and we do not currently have a windows zip file in our 0.8.2 release package. For the purpose of this issue, you can skip this step for now and just print a message to the console.

**Comment by KernelErr** [comment]
Hi, I'm wondering if we could make an installer for WasmEdge. You know the situation of Windows is quite different. I think we could make an installer and upload it to https://github.com/microsoft/winget-pkgs repo. So users can use `winget` command to install WasmEdge in their Powershell. @juntao

**Comment by juntao** [comment]
Sure! Can you do this?

**Comment by KernelErr** [comment]
On it. I will try to pack an installer using Visual Studio.

**Comment by KernelErr** [comment]
I packed an MSI installer and wrote a manifest for winget. How do you like to publish the installer binary? Upload it to GitHub release or create a new repository for it?

**Comment by juntao** [comment]
Thanks! I think uploading to the GitHub release repo is the best approach.

**Comment by hydai** [comment]
> I packed an MSI installer and wrote a manifest for winget. How do you like to publish the installer binary? Upload it to GitHub release or create a new repository for it? Only after having a download link for our installer, we could create a PR for winget.

We have windows CI workers on GitHub. Maybe we can use CI to build and also upload to the nightly build / release directly.

**Comment by KernelErr** [comment]
That's a good idea, and it's more convenient than manual packaging. I would figure out how to create a CI worker for it. Hope there is a way. :)

**Comment by KernelErr** [comment]
Created PR #993 for it. :D

**Comment by q82419** [comment]
This is fixed in #993.
