### ISSUE TITLE
[Doc] Add Docker instructions to the README and install and

### ISSUE THREAD

**Issue by juntao** [WasmEdge/WasmEdge#449]
Add a link to the app dev Docker instruction `utils/docker/build-appdev.md` in the following files

* README.md
* `docs/install.md`
* `docs/run.md`

**Comment by Jayita10** [comment]
I want to work on this issue, Please assign me

**Comment by juntao** [comment]
Perhaps change from

Run a standalone Wasm program or a JavaScript program from CLI 

To 

Run a standalone Wasm program or a JavaScript program from CLI or Docker

And hyperlink the word Docker.
