### ISSUE TITLE
Question : Can I run a wasm file written in go

### ISSUE THREAD

**Issue by burakakca** [WasmEdge/WasmEdge#471]
## [Features](https://github.com/WasmEdge/WasmEdge#features)
"WasmEdge can run standard WebAssembly bytecode programs compiled from C/C++, Rust, Swift, AssemblyScript, or Kotlin source code"

- Can I run, for example, go in other than the languages mentioned above?

**Comment by juntao** [comment]
In order to run a program in WasmEdge, you need to first compile it to WebAssembly bytecode. Currently, we have C/C++, Rust, Swift, AssemblyScript compilers for WebAssembly. We also have a JavaScript interpreter. I believe you can compile TinyGo to WebAssembly but not regular go.
