### ISSUE TITLE
[Install] "Darwin-x86_64 - currently unsupported" when installing wasmedge-core package

### ISSUE THREAD

**Issue by attriaayush** [WasmEdge/WasmEdge#477]
## [Install wasmedge for nodejs](https://github.com/second-state/wasmedge-core)
Following the documentation when trying to install `wasmedge-core` to run wasm functions via NodeJS. When I run `npm install -g wasmedge-core` I see a clear error that the architecture I am running on my MacOS is not supported yet i.e. `Detected Darwin-x86_64 - currently unsupported`.

Is there a recommended way I can cross compile the `wasmedge-core` module for my MacOS current architecture?

MacOS Architecture:
`Darwin Kernel Version 20.3.0; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64`

**Comment by hydai** [comment]
Awesome!

Sure, we would like to have the document on macos. Would you like to submit a PR to us?

Also, llvm 13 is just out. And we have a working PR to deal with it. https://github.com/WasmEdge/WasmEdge/pull/488
The llvm 13 support will be shipped at the next release.

**Comment by attriaayush** [comment]
@hydai Since we have a workaround in place I am happy to close this issue unless you would like to track this same issue for a proper fix.

**Comment by hydai** [comment]
Sure. @attriaayush Thanks for your contribution. It is very helpful. Have a great day :-)
