### ISSUE TITLE
Difference in packaging for `Darwin`

### ISSUE THREAD

**Issue by SAtacker** [WasmEdge/WasmEdge#482]
Can we have the same naming as previously done for `darwin` `0.8.2` 
![image](https://user-images.githubusercontent.com/61797109/137576413-ed8b30d6-31ad-4e95-bdc8-05937bdee8ab.png)

_Originally posted by @SAtacker in https://github.com/WasmEdge/WasmEdge/issues/481#issuecomment-944866554_

**Comment by hydai** [comment]
If we change it, we should change he `Linux` part together.
So here are two choices: `WasmEdge-$VERSION-$OS` or `WasmEdge-$VERSION-$OS_$ARCH`?

We should make sure all of the distributions use the same name rule.

**Comment by SAtacker** [comment]
We should change it similar to the Linux part that you have already done and suggested. 
It's just that I meant changing the ones which are not similar to Linux.
Thanks :smiley:

**Comment by hydai** [comment]
I've updated the 0.8.2 release assets. @SAtacker Could you please check it?
