### ISSUE TITLE
[Rust SDK] refactor the array-like input parameters

### ISSUE THREAD

**Issue by yanganto** [WasmEdge/WasmEdge#489]
## Motivation
Provide better memory saving and easier to use APIs for array-like input  parameters.

## Details
Currently, some of Rust sdk api are using `Option<Vec<_>>` for type of input parameters.  It may be good to implement with `&[impl AsRef<str>]` type.  There are some discussions listed in former PR and list in the Appendix.

## Appendix
https://github.com/WasmEdge/WasmEdge/pull/432#discussion_r714458267
https://github.com/WasmEdge/WasmEdge/pull/432#issuecomment-929328020

**Comment by apepkuss** [comment]
@hydai Got it, I'll check it. Thanks!

**Comment by hydai** [comment]
Since this is outdated, I am closing this.
