### ISSUE TITLE
[Rust SDK] Set up automated validation tests for WasmEdge Rust SDK examples

### ISSUE THREAD

**Issue by alabulei1** [WasmEdge/WasmEdge#491]
This is to let us get an immediate alert if the WasmEdge Rust SDK examples don't work.

**Comment by hydai** [comment]
@alabulei1 
Is this still available?

**Comment by hydai** [comment]
Hi @alabulei1 
Do we have this now?

**Comment by hydai** [comment]
Hi @apepkuss 
Do you know if we implemented this already?
