### ISSUE TITLE
[Host function] Support MySQL driver

### ISSUE THREAD

**Issue by juntao** [WasmEdge/WasmEdge#500]
Create a C-based application to register C functions in MySQL driver (Connector/C) functions into WasmEdge. The result is a new executable called `wasmedge-mysql`.

MySQL C driver: https://www.mysql.com/products/connector/

**Comment by O3Ol** [comment]
I‘d like to take it

**Comment by O3Ol** [comment]
I try to transfer string from wasm to host, but I don't know how to do it. I know that the rust could transfer the string as buffer to wasm, but I don't know how to transform the buffer into string in c language.Is there an example for me to learn about it?

**Comment by juntao** [comment]
@q82419 Can you help with that when you get a chance? We need to have an example for that. Thanks.

**Comment by hydai** [comment]
Hi @juntao 
Do we already have MySQL driver support?
