### ISSUE TITLE
[Host function] Provide a Rust API SDK for the MySQL driver functions

### ISSUE THREAD

**Issue by juntao** [WasmEdge/WasmEdge#501]
Create a Rust crate for host functions in the MySQL driver  (#500) 

Once compiled into WebAssembly, the Rust API functions will be mapped to those host functions similar to:

https://github.com/second-state/wasmedge_wasi_socket
https://github.com/second-state/wasmedge_tensorflow_interface

**Comment by hydai** [comment]
Hi @juntao 
What's the status of this issue? I remember we have the integration of MySQL database. Is that related to this issue?

**Comment by alabulei1** [comment]
We have MySQL driver with HTTP  connect, not implemented in the host function (If I'm not wrong). See docs here: https://wasmedge.org/docs/develop/rust/database/my_sql_driver

However, we need to update the docs, which could be a Hackertoberfest issue.
