### ISSUE TITLE
[Integration] Support WasmEdge on Krustlet

### ISSUE THREAD

**Issue by juntao** [WasmEdge/WasmEdge#502]
We need to support WasmEdge on krustlet. It will probably use the WadmEdge Rust SDK.

https://github.com/krustlet/krustlet

**Comment by yanganto** [comment]
The progress of integration is on this repo.
https://github.com/second-state/krustlet-wasmedge-provider

**Comment by hydai** [comment]
Hi @juntao 
Do we still need to focus on this issue?

**Comment by juntao** [comment]
No. Krustlet is not being actively developed on. I think the community consensus is containerd + runwasi. I will close this one.
