### ISSUE TITLE
[Install Script] Make sure we only use the `[0-9].[0-9].[0-9]*` version

### ISSUE THREAD

**Issue by hydai** [WasmEdge/WasmEdge#509]
## Description

We are testing a new tag called `rust/0.2.0` for the rust language binding in WasmEdge project. If this tag is pushed to GitHub. The install script will try to get this version `rust/0.2.0`. However, the script will split the string and remain the `rust` part only. Which is not our expected. An example is list in below:

```bash
$ wget -qO- https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- -e all
sudo could not be found
Detected Linux-x86_64
No path provided
Installing in /root/.wasmedge
WasmEdge Installation at /root/.wasmedge
Fetching WasmEdge-rust

    Please see --help
    If issue perists make a trace using -V and submit it to
https://github.com/WasmEdge/WasmEdge/issues/new?assignees=&labels=&template=bug_report.md
```

There will be several kinds of tags in the future:

1. Release: `[0-9].[0-9].[0-9]`
2. Pre-release: `[0-9].[0-9].[0-9]*`, such as `0.9.0-rc.1`
3. Language bindings: `language/[0-9].[0-9].[0-9]`, such as `rust/0.2.0`

The install script should only focus on `1. Release` only.

**Comment by hydai** [comment]
@q82419 `2.` will include the `rc` pre-release. I think the install script should install the stable release in normal cases.

Maybe adding a new option called `--upstream`, `--unstable`, or `--beta` is a better way to install the `rc` pre-release.

**Comment by SAtacker** [comment]
This is why https://github.com/WasmEdge/WasmEdge/pull/496#issuecomment-946381729 happened. Thanks for this.



> I mean the pattern `2.` you mentioned:
> 
> ```
> 2. Pre-release: [0-9].[0-9].[0-9]*, such as 0.9.0-rc.1
> ```
> 
> Is it better in `[0-9].[0-9].[0-9]-*` or `[0-9].[0-9].[0-9]-rc.[0-9]` format?

We only have to get the latest release (1st option only ) by default right?
