### ISSUE TITLE
[Install] Remove the `WasmEdge-image-deps` after 0.9.0-rc.1 version

### ISSUE THREAD

**Issue by q82419** [WasmEdge/WasmEdge#510]
## Motivation

The `0.9.0-rc.1` version of `WasmEdge-image` will remove the dependency of libjpeg and libpng.
After that version, we will link the libjpeg and libpng into the `libwasmedge-image_c.so`.

## Details

Remove the wasmedge-image-deps installation after `0.9.0-rc.1`.
But we need this before the `0.8.2` version. Maybe we have to maintain a simple dependency map for extensions?

**Comment by juntao** [comment]
The dependencies could be managed by the install script?

**Comment by SAtacker** [comment]
Sorry but Tensorflow deps are still on `0.8.0` https://github.com/second-state/WasmEdge-tensorflow-deps/releases and same for TFLite

**Comment by SAtacker** [comment]
What should I do in the above case?
Should I manually change the flow for WasmEdge version > 0.8.2 specifically for `WasmEdge-image-deps` and not anything else?

**Comment by q82419** [comment]
I think I can push the tag even if the code not changed.
