### ISSUE TITLE
[Install] The Darwin x86_64 should use `x86_64` arch.

### ISSUE THREAD

**Issue by hydai** [WasmEdge/WasmEdge#512]
### Current State

https://github.com/WasmEdge/WasmEdge/blob/master/utils/install.sh#L123-L129

```bash
    'Darwin')
        case $ARCH in
        'x86_64') ;; # We should set ARCH="x86_64" in this line
        'arm64') ;;
        'arm')
            ARCH="arm64"
            ;;
```

Darwin arm64: https://github.com/WasmEdge/WasmEdge/releases/download/0.8.2/WasmEdge-0.8.2-darwin_arm64.tar.gz
Darwin x86_64: https://github.com/WasmEdge/WasmEdge/releases/download/0.8.2/WasmEdge-0.8.2-darwin_x86_64.tar.gz

**Comment by SAtacker** [comment]
The `ARCH` is set at #L109 https://github.com/WasmEdge/WasmEdge/blob/master/utils/install.sh#L109-L129

**Comment by hydai** [comment]
Sorry. I missed the `;;` :-(
