### ISSUE TITLE
[Install] The wasmedge-extensions NPM package after-install script

### ISSUE THREAD

**Issue by juntao** [WasmEdge/WasmEdge#515]
The current NPM install script runs our standard script for local install to `$HOME/.wasmedge`

But it does not run `source $HOME/.wasmedge/env`, which causes the current session to fail at `wasmedge` commands (path not set up).

**Comment by dm4** [comment]
I added a post install script to show a big warning text to tell users source their env files at commit https://github.com/second-state/wasmedge-core/commit/141a3118f9837654062a55e79ab0dc671ecdcb47 . This commit is already in tag `0.9.0-rc.1` and `0.9.0`.
