### ISSUE TITLE
[Rust SDK] Support registering host functions

### ISSUE THREAD

**Issue by juntao** [WasmEdge/WasmEdge#524]
A crucial feature we need in the Rust SDK is to support registration of host functions. 

Here is an example using the Wasmtime Rust SDK to implement the trampoline functions for async tasks. Our SDK need to at least support this level of expressions -- and would preferably improve the Rust API to make it more ergonomic.

https://github.com/second-state/wasmedge-quickjs/blob/async_net/async_runtime/src/main.rs

**Comment by yanganto** [comment]
This issue may be duplicated with #422
