### ISSUE TITLE
[Install] Don't run sudo when installing WasmEdge under root.

### ISSUE THREAD

**Issue by wangshishuo** [WasmEdge/WasmEdge#579]
When I run `wget -qO- https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- -e all` in docker under user root, it will report:
```
sudo could not be found
```
Though it didn't hinder my installation, I think it's better to not run sudo.

**Comment by SAtacker** [comment]
Thanks, it was done so because `$HOME`, when run under root privileges, varies. With sudo you may run as somebody else, whereas few don't have sudo installed. So I assume that when people don't have sudo installed they are using their `$HOME` directory.

**Comment by juntao** [comment]
Do you mean that you need to test `sudo` even if the user is root? Thanks.

**Comment by SAtacker** [comment]
Yes. I'll simply remove the unnecessary logging.

**Comment by SAtacker** [comment]
Thanks for this, I'll close it for now.
