### ISSUE TITLE
[CLI] Enable wasmedge command to load extensions

### ISSUE THREAD

**Issue by juntao** [WasmEdge/WasmEdge#585]
Instead of having multiple tools binaries for extensions, we should have a unified approach that allows the `wasmedge` and `wasmedgec` commands to load extensions from the CLI via flags.  

That allows the user to run extended WasmEdge apps from a single CLI as long as they have the extension dependencies installed.

---

However, before that, we still need to install the `wasmedge-tensorflow-lite` binary as part of the install package. We will use the new `wasmedge` single binary approach and update all dependent scripts and examples when it is ready. @SAtacker @q82419

**Comment by SAtacker** [comment]
So will the `wasmedge-tensorflow-lite` be in which package?

**Comment by juntao** [comment]
Here is the release package for the binary

https://github.com/second-state/WasmEdge-tensorflow-tools/releases/tag/0.9.0-rc.2

It should be installed as before with the `-e all` and `-e tf` options. Thanks.

**Comment by hydai** [comment]
This is fixed in #593
