### ISSUE TITLE
[Go SDK] Create an example of passing strings from host functions

### ISSUE THREAD

**Issue by juntao** [WasmEdge/WasmEdge#588]
We should create a complete example of passing a string from a Go host function to a Wasm function (written in Rust), and then capturing the string return value from the Wasm function in the Go host.

Related to #563

**Comment by daixiang0** [comment]
@q82419 @juntao any update for this?

**Comment by juntao** [comment]
https://wasmedge.org/book/en/embed/go/memory.html

@daixiang0 Let me know what you think.

**Comment by daixiang0** [comment]
@juntao pretty cool!

**Comment by daixiang0** [comment]
@juntao I want to know whether wasmedge can support modifying strings without copying? In the above example, wasmedge just read the memory and copy it into a string, is it possible to directly change memory content?

**Comment by q82419** [comment]
For passing the string into the memory instance, the copying is needed because the isolation of WASM should be ensured.
For getting the buffer from memory instance, we've modified the API to return the `[]byte` as the slice of the partition of memory instance after the `WasmEdge-go v0.9.0-rc5` and the `WasmEdge 0.9.0-rc.5`. You can try to get the memory from the API and modify the content.

**Comment by daixiang0** [comment]
Sound great! As it is an RC version, I would like to try after release and become relatively stable. It would be perfect if you can provide docs for this since you know the best practices of WasmEdge~

**Comment by q82419** [comment]
Since we're working on the `0.9.0` official release, we'll refactor the all examples for every language SDKs into an example repository in the nearly future. Thanks.

**Comment by wangshishuo** [comment]
> @juntao I want to know whether wasmedge can support modifying strings without copying? In the above example, wasmedge just read the memory and copy it into a string, is it possible to directly change memory content?
> 
> Byte convert one by one does cost many resources!

@daixiang0 In your mention, can you point out which line of code it is?

**Comment by daixiang0** [comment]
```
func greet(subject *int32) *byte {
    nth := 0
    var subjectStr strings.Builder
    pointer := uintptr(unsafe.Pointer(subject))
    for {
        s := *(*int32)(unsafe.Pointer(pointer + uintptr(nth)))   <=== need to convert one by one
        if s == 0 {
            break;
        }

        subjectStr.WriteByte(byte(s))
        nth++
    }

    output := subjectStr.String()
    output = "Hello, " + output + "!"

    return &(([]byte)(output)[0])
}```
