### ISSUE TITLE
[Go SDK] Create a reference guide for Go SDK

### ISSUE THREAD

**Issue by juntao** [WasmEdge/WasmEdge#589]
It could be modeled after the C API reference guide.

**Comment by spider0061** [comment]
@juntao I would like to work on this issue. Thanks

**Comment by spider0061** [comment]
Can you share some reference and please let me know where to add this guide?

**Comment by juntao** [comment]
Here is the C API reference doc. You should put the go API in a file called go_api.md next to it. 

https://github.com/WasmEdge/WasmEdge/blob/master/docs/c_api.md

Here is a tutorial on when and how to use the GO API: https://www.secondstate.io/articles/extend-golang-app-with-webassembly-rust/

The GO SDK provides the GO API: https://github.com/second-state/WasmEdge-go

The Go examples shows how to use the Go API: https://github.com/second-state/WasmEdge-go-examples

**Comment by spider0061** [comment]
Sure Sir, working on it
