### ISSUE TITLE
[Porting] Build WasmEdge for OpenHarmony Standard edition

### ISSUE THREAD

**Issue by juntao** [WasmEdge/WasmEdge#590]
The OpenHarmony Standard Edition is a Linux-based OS for IoT devices.

https://gitee.com/openharmony/docs/blob/master/zh-cn/device-dev/quick-start/quickstart-standard.md

We should fork and modify its build script to build WasmEdge and install WasmEdge binary and header files into the system default paths. We will then provide a OpenHarmony OS image that includes WasmEdge support for applications.

**Comment by hydai** [comment]
Seems like this is finished?

**Comment by hydai** [comment]
This is resolved: https://github.com/WasmEdge/WasmEdge/tree/master/utils/ohos
