### ISSUE TITLE
[Install Script] Install wasmedge-tensorflow-tool when tf option is set

### ISSUE THREAD

**Issue by hydai** [WasmEdge/WasmEdge#592]
## Motivation

In the future, WasmEdge plans to use plug-in system to load the extensions. In the previous issue, we remove the tools part because this should be installed by the users who want to run Wasm applications with tensorflow extension in command line. However, we received a few issues that it will break our current documents for several examples and tutorials. As a compromise, we will need to install the `wasmedge-tensorflow-tool` when the `tf` option is set. This is a current workaround.

## Details

We would add the tool installation back. Which is removed in #523 : https://github.com/WasmEdge/WasmEdge/pull/523/files#diff-001b8193af60259ffc2829010784899f35764c864992fe3e96a606ad2650bb2bL104

**Comment by juntao** [comment]
Duplicates #585 ;)

**Comment by juntao** [comment]
Related to #585
