### ISSUE TITLE
[Integration] Create a HTTP service demo for k8s on crun

### ISSUE THREAD

**Issue by juntao** [WasmEdge/WasmEdge#594]
We currently have a demo for WasmEdge on k8s through `crun+wasmedge` and CRI-O

https://github.com/second-state/wasmedge-containers-examples/tree/main/kubernetes

However, this demo runs a one-off app that exits after it is done. We would like to run a long-running app that listens for HTTP traffic and respond to HTTP requests. The following Rust code can be compiled to wasm for WasmEdge.

https://github.com/second-state/wasmedge_wasi_socket/tree/main/examples/http_server

Or, you can do it in JavaScript too:

https://github.com/second-state/wasmedge-quickjs#http-request

**Comment by AvengerMoJo** [comment]
Create stand alone long run http_server in crun with wasm support. 
https://github.com/AvengerMoJo/wasmedge-containers-examples/blob/main/crio/http_server/README.md

**Comment by hydai** [comment]
This is fixed: https://github.com/second-state/wasmedge-containers-examples/blob/main/.github/workflows/kubernetes-containerd-server.yml
