### ISSUE TITLE
[Integration] Create a crunw demo for KubeEdge

### ISSUE THREAD

**Issue by juntao** [WasmEdge/WasmEdge#596]
The current `crunw` demo runs on a regular k8s setup. We would like to run it on KubeEdge.

https://github.com/second-state/crunw#readme

https://kubeedge.io/en/

Also related to #594

**Comment by juntao** [comment]
Maybe this helps. 

https://kubeedge.io/en/docs/advanced/cri/

**Comment by hydai** [comment]
I think this is resolved here: https://wasmedge.org/book/en/use_cases/kubernetes/kubernetes/kubeedge.html
