### ISSUE TITLE
[Integration] Create a crunw demo for OpenYurt

### ISSUE THREAD

**Issue by juntao** [WasmEdge/WasmEdge#597]
The current crunw demo runs on a regular k8s setup. We would like to run it on OpenYurt.

https://github.com/second-state/crunw#readme

https://github.com/openyurtio/openyurt

Also related to #594

**Comment by hydai** [comment]
This is resolved here: https://wasmedge.org/book/en/use_cases/kubernetes/kubernetes/openyurt.html
I am closing it.
