### ISSUE TITLE
[Rust SDK] Support loading wasm bytecode from an array

### ISSUE THREAD

**Issue by juntao** [WasmEdge/WasmEdge#601]
The C API allows the developer to load a WASM module from a memory buffer.

```
WasmEdge_VMLoadWasmFromBuffer
```

The Rust SDK should support this as well.

**Comment by apepkuss** [comment]
Hi @juntao, this issue is closed by #854.

**Comment by hydai** [comment]
Looks like GitHub broken again...
This PR is merged: https://github.com/WasmEdge/WasmEdge/commit/ebbb3684fb4932935b4f99c6cab7d4195c2d5897
However, it doesn't show this got merged. I am closing this manually.
