### ISSUE TITLE
[Go SDK] Support loading wasm bytecode from an array

### ISSUE THREAD

**Issue by juntao** [WasmEdge/WasmEdge#602]
The C API allows the developer to load a WASM module from a memory buffer.

```
WasmEdge_VMLoadWasmFromBuffer
```

The Go SDK should support this as well.

**Comment by wangshishuo** [comment]
This has been implemented in [wasmedge-go@0.8.2](https://github.com/second-state/WasmEdge-go/blob/v0.8.2/wasmedge/vm.go#L151)
