### ISSUE TITLE
[Rust SDK] get export

### ISSUE THREAD

**Issue by juntao** [WasmEdge/WasmEdge#607]
We need to support host function, table, global, and memory exports in our Rust SDK API. 

Related #606

**Comment by apepkuss** [comment]
Fixed.

- In `wasmedge-sys`, the `host function`, `table`, `global` and `memory` instances can be retrieved with [Instance](https://github.com/WasmEdge/WasmEdge/blob/master/bindings/rust/wasmedge-sys/src/instance/module.rs#L24-L272), [WasiModule](https://github.com/WasmEdge/WasmEdge/blob/master/bindings/rust/wasmedge-sys/src/instance/module.rs#L647-L831), or [WasmEdgeProcessModule](https://github.com/WasmEdge/WasmEdge/blob/master/bindings/rust/wasmedge-sys/src/instance/module.rs#L968-L1152).

- In `wasmedge-sdk`,  the `host function`, `table`, `global` and `memory` instances can be retrieved with [Instance](https://github.com/WasmEdge/WasmEdge/blob/master/bindings/rust/wasmedge-sdk/src/instance.rs#L10-L132), [WasiInstance](https://github.com/WasmEdge/WasmEdge/blob/master/bindings/rust/wasmedge-sdk/src/instance.rs#L135-L246), or [WasmEdgeProcessInstance](https://github.com/WasmEdge/WasmEdge/blob/master/bindings/rust/wasmedge-sdk/src/instance.rs#L249-L360).
