### ISSUE TITLE
[Go SDK] Support yield and resume

### ISSUE THREAD

**Issue by juntao** [WasmEdge/WasmEdge#611]
We need to support `yield` and `resume` operations related to the host functions.

Related to #609

**Comment by AdwitiyaMishra** [comment]
Hi @juntao , is the issue still available. I would like to work on it.

**Comment by juntao** [comment]
Hi @AdwitiyaMishra 

Thank you very much for your interest. We are experimenting with multiple approaches in the Rust SDK and have not settled on one. You can check out them and see how they can be applied on the Go side. 

The asyncify approach: https://github.com/second-state/wasmedge_asyncify

The fiber approach: https://github.com/MediosZ/WasmEdge/blob/async_demo/bindings/rust/wasmedge-sdk/examples/hello_world.rs

**Comment by hydai** [comment]
I don't think this is on the roadmap now. Closing it.
