### ISSUE TITLE
[Rust SDK] wasmedge.h is not found after current stable deb installed (0.8.2)

### ISSUE THREAD

**Issue by yanganto** [WasmEdge/WasmEdge#612]
## Description
After installed stable release `.deb`, `wasmedge-sys` can not be compiled.

### Current State
Currently, WasmEdge-0.8.2-ubuntu20.04_amd64.deb will install in the following path by default.
```
drwxr-xr-x root/root         0 2021-08-27 06:55 ./usr/
drwxr-xr-x root/root         0 2021-08-27 06:55 ./usr/bin/
-rwxr-xr-x root/root   2054544 2021-08-27 06:55 ./usr/bin/wasmedge
-rwxr-xr-x root/root   3976880 2021-08-27 06:55 ./usr/bin/wasmedgec
drwxr-xr-x root/root         0 2021-08-27 06:55 ./usr/include/
-rw-r--r-- root/root    112992 2021-08-27 06:52 ./usr/include/wasmedge.h
drwxr-xr-x root/root         0 2021-08-27 06:55 ./usr/lib/
-rw-r--r-- root/root   5331456 2021-08-27 06:55 ./usr/lib/libwasmedge_c.so
```
The rust crate `wasmedge-sys` can not be installed after `.deb` installed.
```
  process didn't exit successfully: `/home/runner/work/krustlet-wasmedge-provider/krustlet-wasmedge-provider/target/debug/build/wasmedge-sys-53d3b62cef8562b5/build-script-build` (exit status: 101)
  --- stderr
  error: header '/usr/include/wasmedge/wasmedge.h' does not exist.
```

### Expected
After `.deb` installed, `wasmedge-sys` can be installed without error.

## Environment

- Hardware Architecture: aarch64
- Operating system: Ubuntu 20.04

The environment is the GitHub CI of other project.
https://github.com/second-state/krustlet-wasmedge-provider/runs/4100622648?check_suite_focus=true

## Steps to Reproduce
```
wget https://github.com/WasmEdge/WasmEdge/releases/download/0.8.2/WasmEdge-0.8.2-ubuntu20.04_amd64.deb
dpkg -c WasmEdge-0.8.2-ubuntu20.04_amd64.deb
sudo dpkg -i WasmEdge-0.8.2-ubuntu20.04_amd64.deb
```
Then build any rust project with `wasmedge-sys` dependency.

**Comment by hydai** [comment]
Looks like the wasmedge-sys is using 0.9.0 form?
The header file is moved from `include/wasmedge.h` to `include/wasmedge/wasmedge.h` after 0.9.0-rc.1.

**Comment by ZhangHanDong** [comment]
> Looks like the wasmedge-sys is using 0.9.0 form? The header file is moved from `include/wasmedge.h` to `include/wasmedge/wasmedge.h` after 0.9.0-rc.1.

Shouldn't it be `/usr/include/wasmedge/` ?

 I copied this  to `/usr/include/wasmedge/wasmedge.h` manually when I was developing, because my development environment was never good enough to build wasmedge.
