### ISSUE TITLE
[CI] Static Code Analysis failed

### ISSUE THREAD

**Issue by hydai** [WasmEdge/WasmEdge#618]
### Current State

```bash
-- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LLD_COMMON
    linked by target "wasmedgeAOT" in directory /home/runner/work/WasmEdge/WasmEdge/lib/aot
LLD_CORE
    linked by target "wasmedgeAOT" in directory /home/runner/work/WasmEdge/WasmEdge/lib/aot
LLD_DRIVER
    linked by target "wasmedgeAOT" in directory /home/runner/work/WasmEdge/WasmEdge/lib/aot
LLD_READERWRITER
    linked by target "wasmedgeAOT" in directory /home/runner/work/WasmEdge/WasmEdge/lib/aot
LLD_SYSTEM
    linked by target "wasmedgeAOT" in directory /home/runner/work/WasmEdge/WasmEdge/lib/aot
LLD_YAML
    linked by target "wasmedgeAOT" in directory /home/runner/work/WasmEdge/WasmEdge/lib/aot

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
External Error: *** capture command failed:
*** cmake -DCMAKE_BUILD_TYPE=Debug ..
*** exited with code 1
```

### Expected

The CI of Static Code Analysis should pass

**Comment by juntao** [comment]
Hi @avinal

Do you have time to look into this? Thanks.

**Comment by avinal** [comment]
Hello @juntao, 
I have looked into this issue and couldn't find any proper reason why this is happening. Strangely enough, the same steps run just fine when running locally or even in Gitpod. As a fix, I am downgrading the clang version. This seems to be working for now.

This might have something to do with the GitHub Actions virtual environment. They have been changing the software repository of the VMs with their in-house azure version. And this is breaking a lot of packages. I discovered a couple of conflicting library issues in my projects too and no solutions so far.

**Comment by juntao** [comment]
Thanks! I guess this is specific to GitHub Action's runner VM, and we do not need to change the documentation for build instructions?

**Comment by avinal** [comment]
Yeah, there is no need. I can confirm that it works locally and on other VMs.

**Comment by beef331** [comment]
Seems this is also an issue for building on some distros, trying to build from source outside of docker(think it's causing an issue with my system). Using debian sid, seems it doesnt respect `LLVM_LIBRARY_DIR` or properly search inside of it.
