### ISSUE TITLE
[Install] Missing .profile command after installing NAPI package

### ISSUE THREAD

**Issue by juntao** [WasmEdge/WasmEdge#621]
After I do `npm install wasmedge-core` or `npm install wasmedge-extensions`, the wasmedge binaries would be installed in `~/.wasmedge/bin`. 

The regular install script should put a line for `source ~/.wasmedge/env` into `.profile` and `.bashrc` files, but the NAPI installer would not put in that line. That causes the user not able to find and use the `wasmedge` binary after installing NAPI.

**Comment by SAtacker** [comment]
I am closing this, thanks!
