### ISSUE TITLE
[Rust SDK] Review and implement apis in `rust-sys`

### ISSUE THREAD

**Issue by yanganto** [WasmEdge/WasmEdge#628]
## Motivation
Check and review the non-used CAPI in Rust crate, and make sure `rust-sys` expose as open as possible.

## Details
Following APIs need to be reviewed.
- [x] #684
- [x] #685
- [x] #686
- [x] #687
- [x] #688
- [x] #689
- [x] #690
- [x] #691
- [x] #692
- [x] #693
- [x] #694
- [x] #695
- [x] #696
- [x] #697
- [x] #698
- [x] #699
- [x] #700
- [x] #701
- [x] #702
- [x] #703
- [x] #704
- [x] #705
- [x] #709
- [x] #710
- [x] #711
- [x] #712
- [x] #713
- [x] #716
- [x] #724
- [x] #725
- [x] #677
- [x] #726
- [x] #727
- [x] #678
- [x] #679
- [x] #729
- [x] #731
- [x] #733
- [x] #680
- [x] #735
- [x] #736
- [x] #741
- [x] #742
- [x] #743
- [x] #744
- [x] #745
- [x] #675
- [x] #746
- [x] #747
- [x] #749
- [x] #674
- [x] #673 
- [x] #750
- [x] #676
- [x] #751
- [x] #753
- [x] #755
- [x] #756
- [x] #757
- [x] #758
- [x] #759
- [x] #760
- [x] #761
- [x] #762
- [x] #763
- [x] #765
- [x] #766
- [x] #767
- [x] #681
- [x] #768
- [x] #780
- [x] #781
- [x] #782
- [x] #783
- [x] #784
- [x] #785
- [x] #786
- [x] #787
- [x] #789
- [x] #790
- [x] #791
- [x] #792
- [x] #793
- [x] #794
- [x] #841
- [x] #840
- [x] #839
- [x] #838
- [x] #837
- [x] #836
- [x] #835
- [x] #834
- [x] #833
- [x] #832
- [x] #831
- [x] #830
- [x] #829
- [x] #828
- [x] #826
- [x] #827
- [x] #825
- [x] #824
- [x] #823
- [x] #822
- [x] #821
- [x] #820
- [x] #819
- [x] #818
- [x] #817
- [x] #816
- [x] #815
- [x] #814
- [x] #813
- [x] #796
- [x] [Rust SDK] WasmEdge_StringCopy https://github.com/WasmEdge/WasmEdge/pull/631
- [x] [Rust SDK] WasmEdge_StringCreateByCString https://github.com/WasmEdge/WasmEdge/pull/631
- [x] [Rust SDK] WasmEdge_StringIsEqual https://github.com/WasmEdge/WasmEdge/pull/631
- [x] #797
- [x] #682
- [x] #812
- [x] #811
- [x] #810
- [x] #809
- [x] #808
- [x] #807
- [x] #806
- [x] #805
- [x] #804
- [x] #802
- [x] #801
- [x] #800
- [x] #803
- [x] #798
- [x] #779
- [x] #778
- [x] #777
- [x] #776
- [x] #775
- [x] #774
- [x] #773
- [x] #683
- [x] #772
- [x] #771
- [x] #770
- [x] #754
- [x] #769
- [x] #748
- [x] #740
- [x] #738
- [x] #739
- [x] #734
- [x] #732
- [x] #730
- [x] #728
- [x] #723
- [x] #722
- [x] #720
- [x] #719
- [x] #717
- [x] #715
- [x] #714
- [x] #707
- [x] #706

If there is some API not exposed reasonable, mention the API in doc string, such that the CI will be passed in the future.

## Appendix
CI for inventorying 
https://github.com/WasmEdge/WasmEdge/pull/627

**Comment by apepkuss** [comment]
Hi @yanganto, I'll add the remaining APIs related to Memory in #861 after #854 is closed.

**Comment by hydai** [comment]
According to [the latest action](https://github.com/WasmEdge/WasmEdge/runs/4932690976?check_suite_focus=true), we still have the following C-API which are not exposed in `rust-sys`.

@apepkuss Could you please check if there are any of them that are not needed to expose? Maybe we should have a exclusive list to delist them.

- [ ] WasmEdge_AsyncCancel
- [ ] WasmEdge_AsyncDelete
- [ ] WasmEdge_AsyncGet
- [ ] WasmEdge_AsyncGetReturnsLength
- [ ] WasmEdge_AsyncWait
- [ ] WasmEdge_AsyncWaitFor
- [ ] WasmEdge_LimitIsEqual
- [ ] WasmEdge_ResultGetMessage
- [ ] WasmEdge_StringCopy
- [ ] WasmEdge_StringWrap
- [ ] WasmEdge_VMAsyncExecute
- [ ] WasmEdge_VMAsyncExecuteRegistered
- [ ] WasmEdge_VMAsyncRunWasmFromASTModule
- [ ] WasmEdge_VMAsyncRunWasmFromBuffer
- [ ] WasmEdge_VMAsyncRunWasmFromFile
- [ ] WasmEdge_VMRunWasmFromASTModule
- [ ] WasmEdge_VMRunWasmFromBuffer
- [ ] WasmEdge_VMRunWasmFromFile

**Comment by apepkuss** [comment]
Hi @hydai, according to the current design of `wasmedge-sys`, the following C APIs can be removed from the list. Thanks!

* WasmEdge_LimitIsEqual
* WasmEdge_ResultGetMessage
* WasmEdge_StringCopy
* WasmEdge_StringWrap
* WasmEdge_VMRunWasmFromASTModule
* WasmEdge_VMRunWasmFromBuffer
* WasmEdge_VMRunWasmFromFile

**Comment by hydai** [comment]
Hi @apepkuss 
Could you please check if this issue is done or not?

**Comment by hydai** [comment]
This is outdated, and we no longer need to check it manually.
