### ISSUE TITLE
[Integration] Run crun in containerd

### ISSUE THREAD

**Issue by juntao** [WasmEdge/WasmEdge#634]
The `crunw` binary is a drop-in replacement for `crun` and `runc`. We have a script to make `crunw` the default runtime for CRI-O.

https://github.com/second-state/crunw/blob/main/crunw_install.sh

We should be able to do the same for containerd.

**Comment by AvengerMoJo** [comment]
nice, basically just merge and replace all the crun and runc with crunw for #594 #595 #596 #597 and #598 should be straightforward.

**Comment by juntao** [comment]
Update: The `crun` project now officially supports WasmEdge. We should provide instructions and demo scripts for using `crun+wasmedge` as a containerd runtime. 

It can be added side by side with CRI-O instructions:

https://github.com/second-state/wasmedge-containers-examples/tree/main/crio

**Comment by juntao** [comment]
This is done.

https://github.com/second-state/wasmedge-containers-examples/pull/6
