### ISSUE TITLE
[Integration] Provide Fedora and RHEL packages

### ISSUE THREAD

**Issue by juntao** [WasmEdge/WasmEdge#637]
Provide WasmEdge install packages for Fedora / RHEL upstream repos.

**Comment by juntao** [comment]
Here is the process. 

https://docs.fedoraproject.org/en-US/package-maintainers/New_Package_Process_for_New_Contributors/

We should do this for the upcoming 0.9.0 release.

**Comment by hydai** [comment]
Fixed: https://src.fedoraproject.org/rpms/wasmedge
