### ISSUE TITLE
[Integration] Support runc

### ISSUE THREAD

**Issue by juntao** [WasmEdge/WasmEdge#639]
We could add WasmEdge support for `runc` via our GO SDK.

**Comment by agracey** [comment]
Seconding this request. This would be useful to allow existing platforms to add wasmedge into their stack.

**Comment by hydai** [comment]
I think this integration is replaced by runwasi. @juntao do we still have plans for supporting `runc` directly?

**Comment by hydai** [comment]
Docker uses runwasi for the WASM workload integration. IMO this issue is no longer available.
Feel free to re-open it If there is anyone who wants to integrate runc+wasmedge.
