### ISSUE TITLE
[PySDK] Use PyBind11 instead of Boost.Python

### ISSUE THREAD

**Issue by SAtacker** [WasmEdge/WasmEdge#650]
Hi @SAtacker, I noticed that PySDK uses Boost.Python as the bridge library to implement the C++ to Python conversion. How do you think about another useful library, PyBind11? 

According to the description from PyBind11 (https://pybind11.readthedocs.io/en/stable/index.html), the main issue of Boost.Python:

> Boost is an enormously large and complex suite of utility libraries that works with almost every C++ compiler in existence. This compatibility has its cost: arcane template tricks and workarounds are necessary to support the oldest and buggiest of compiler specimens. Now that C++11-compatible compilers are widely available, this heavy machinery has become an excessively large and unnecessary dependency.

In the context of WasmEdge project, PyBind11 could be better than Boost.Python for the following reasons:

- Shorter compilation time (https://pybind11.readthedocs.io/en/stable/benchmark.html#compilation-time).
- Smaller generated Python plugin (https://pybind11.readthedocs.io/en/stable/benchmark.html#module-size). 
- PyBind11 is header only, while Boost.Python is part of Boost. From the view of development, we can use the header file of PyBind11 directly, do not need to care about build, installation and dependencies.
- WasmEdge itself is not based on Boost.

The above is my thought for the choice of the bridge library. Please correct me if my description was inappropriate.

_Originally posted by @apepkuss in https://github.com/WasmEdge/WasmEdge/issues/633#issuecomment-968053918_

**Comment by juntao** [comment]
I think we would like a working Python SDK first, and then try to optimize it. If boost can get us a working SDK faster, we can live with its shortcomings for now. :)

**Comment by SAtacker** [comment]
> I think we would like a working Python SDK first, and then try to optimize it. If boost can get us a working SDK faster, we can live with its shortcomings for now. :)

I felt I should better do it right now before it becomes larger and difficult to manage.
