### ISSUE TITLE
[WASI] poll_oneoff support socket fd

### ISSUE THREAD

**Issue by L-jasmine** [WasmEdge/WasmEdge#659]
I want to use `poll_oneoff` on socket fd ,  then I can use nio in wasm.

**Comment by hydai** [comment]
Just FYI, https://github.com/rust-lang/libc/blob/master/src/wasi.rs#L602
WASI-libc on rust provides a `poll` function, I am not sure if this fits your target or not.

**Comment by L-jasmine** [comment]
> Just FYI, https://github.com/rust-lang/libc/blob/master/src/wasi.rs#L602 WASI-libc on rust provides a `poll` function, I am not sure if this fits your target or not.

yes, libc::poll call poll_oneoff. It can works in socket fd?

**Comment by hydai** [comment]
I think it should work.  The socket fd is handled by the same way as normal fd: https://github.com/WasmEdge/WasmEdge/blob/827bf4ccad4f96f233209434252663bcd9a33fb0/include/host/wasi/environ.h#L843

Could you try it first?

**Comment by L-jasmine** [comment]
> 

I try. It is not work.

https://github.com/L-jasmine/wasi_poll_test/actions/runs/1484049870

**Comment by L-jasmine** [comment]
https://github.com/WasmEdge/WasmEdge/blob/bb4183690c4564651995fbdab770abe379c37156/include/host/wasi/vinode.h#L670

sock is no __WASI_RIGHTS_POLL_FD_READWRITE  and  __WASI_RIGHTS_FD_READ. 
so it can't poll.

I will push a fix
