### ISSUE TITLE
[Rust SDK] Code Improvement

### ISSUE THREAD

**Issue by ZhangHanDong** [WasmEdge/WasmEdge#660]
1. eliminate some duplicate code.
2. Add a `host-function` interface to `wasmedge-sdk`

[#641 ](https://github.com/WasmEdge/WasmEdge/pull/641)

**Comment by apepkuss** [comment]
Fixed. The original `wasmedge-sdk` has been replaced by the new [one](https://github.com/WasmEdge/WasmEdge/tree/master/bindings/rust/wasmedge-sdk), in which [Func](https://github.com/WasmEdge/WasmEdge/blob/master/bindings/rust/wasmedge-sdk/src/externals/function.rs#L59-L147) defines the necessary APIs.
