### ISSUE TITLE
[OHOS] Integrate WasmEdge with OpenHarmony OS

### ISSUE THREAD

**Issue by apepkuss** [WasmEdge/WasmEdge#852]
## Motivation

This issue is to set up milestones to track the integration of WasmEdge on the OpenHarmony OS (OHOS) platform.

## Details
- Standard OHOS
  - [x] Musl-libc support in WasmEdge
    - #649 
    - #667 
  - [ ] Compilation and Deployment
    - [x] Interpreter Mode 
      - [x] To build WasmEdge as a third-party library with OpenHarmony toolchain 
        - [x] To support gn + ninja build system in WasmEdge 
          - #864 
    - [ ] AOT Mode (WIP)
    - [x] To deploy and verify the image on dev board (Hi3516dv300)
  - [x] Documents
    - [x] Build scripts and necessary supporting documents #902 
    - [x] Tutorial of Wasmedge compilation and deployment on OHOS (video)
  - [x] Demo
    - [x] Fibonacci wasm

- LiteOS 
  - [ ] Linux Core: hispark_taurus_linux
    - [x] Interpreter Mode
      - [x] #975
    - [ ] AOT Mode
    - [ ] Documents
  - [ ] LiteOS-A Core
    - [ ] Interpreter Mode (WIP)
      - [ ] #975
    - [ ] AOT Mode
    - [ ] Documents
  - [ ] LiteOS-M Core
    - [ ] Interpreter Mode
      - [ ] #975
    - [ ] AOT Mode
    - [ ] Documents

**Comment by hydai** [comment]
Hi @apepkuss 
What's the status of this issue?

**Comment by apepkuss** [comment]
@hydai No updates for this issue. This is the latest progress. Thanks a lot!

**Comment by hydai** [comment]
@apepkuss 
Do we have any plans to continue this work? If not, I am going to close this.

**Comment by apepkuss** [comment]
As I know, we already suspended the development plan. Thanks!

**Comment by hydai** [comment]
Since we are not going to integrate with OHOS, I am closing this issue.
