### ISSUE TITLE
Loading an image takes forever to execute

### ISSUE THREAD

**Issue by st9540808** [WasmEdge/WasmEdge#855]
## Description

I tried to load an image from a local directory. It only does two operations, read an image and decode it. After trying some examples, the operation `img.decode()` accounts for most of the execution time. I also compared the execution time with [wasmtime](https://github.com/bytecodealliance/wasmtime).
| Command | Time |
| ----------- | ------|
| `wasmtime run  --mapdir .::. ./wasi-test.wasm` | 0m0.506s |
| `wasmedge --dir .:. ./wasi-test.wasm` | 1m29.294s |

## Environment

- Hardware Architecture: x86_64
- CPU: Threadripper 3990X
- Operating system: Ubuntu 20.04

### Code
```rust
const IMG_PATH: &str = "testdata/images/1627066631835.png";

fn main() {
    let img = image::io::Reader::open(IMG_PATH).unwrap();
    let img_decode = img.decode();
}
```

### Cargo.toml
```
[package]
name = "wasi-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow        = "1.0"
log           = { version = "0.4", default-features = false }
env_logger    = "0.8"
structopt     = "0.3.21"
byteorder     = "1.4.3"
image         = "0.23.14"
ndarray       = "0.15.4"
```

**Comment by juntao** [comment]
You need to use AOT to get performance. Wasmtime has JIT turned on by default. WasmEdge's default is interpreter. 

Just do 

````
wasmedgec file.wasm file.so
```

And then

```
wasmedge file.so ...
```

**Comment by st9540808** [comment]
Thanks for the quick response! It solved my problem.
