### ISSUE TITLE
[Rust] Provide `default` of Default trait when creating instance without parameters

### ISSUE THREAD

**Issue by yanganto** [WasmEdge/WasmEdge#860]
If a user not put any additional modification to new an instance, s/he may like to use the `default` of config by Rust convention.  

We use create because the name is from C-Api, it may be nice to provide `default` function of `Default` trait to alias the create without parameters, or we can do it in different PR.

_Originally posted by @yanganto in https://github.com/WasmEdge/WasmEdge/pull/854#discussion_r761578824_

**Comment by hydai** [comment]
Hi @apepkuss 
Could you check if this issue is still available or not?

**Comment by apepkuss** [comment]
In `wasmedge-sdk`, the default `Config` has already been implemented.
