### ISSUE TITLE
[Rust] Implement APIs for Memory

### ISSUE THREAD

**Issue by apepkuss** [WasmEdge/WasmEdge#861]
## Motivation

This issue is used to track the design of the APIs for the Memory component in wasmedge-sys.

## Details

The following 7 C-APIs related to WasmEdge_MemoryInstanceContext are involved in the design:

- [ ] WasmEdge_MemoryInstanceGetMemoryType
- [ ] WasmEdge_MemoryInstanceGetData
- [ ] WasmEdge_MemoryInstanceSetData
- [ ] WasmEdge_MemoryInstanceGetPointer
- [ ] WasmEdge_MemoryInstanceGetPointerConst
- [ ] WasmEdge_MemoryInstanceGetPageSize
- [ ] WasmEdge_MemoryInstanceGrowPage

## References
#628
#854

**Comment by yanganto** [comment]
Hi @apepkuss,

May you just open a Draft PR, and mention in the descript of PR
> fix #768 
fix #780 
fix #781
fix #782
fix #783
fix #784
fix #785

, and close this issue.

Such that there will no duplicate issue and GitHub will work automatically to update the #628
