### ISSUE TITLE
[OHOS] Build WasmEdge with Gn in OpenHarmony

### ISSUE THREAD

**Issue by O3Ol** [WasmEdge/WasmEdge#864]
I tried to build wasmedge on the openharmony system, and cross-compiled it according to the wasmedge porting third-party library documentation. But when it was put into the openharmony project, because it was not a module of ohos when it was built, wasmedge could not be written into the mirror. The reply I got from Hongmeng was that the module needs to be declared in gn and built using gn. Is there an easy way to register a module (static library, executable file) built in cmake as an ohos module (ohos_static_library, ohos_executable) declared in gn? The build tool chain used by ohos is gn+ninja.

**Comment by O3Ol** [comment]
If there is no way to directly use the modules in cmake, we can only declare all the source files of static library construction, dependent libraries, cflags and cxxflags in the gn file. Maybe I need to build through gn instead of cmake, which may be a little difficult for me, so is there a workflow log of cmake build?

**Comment by hydai** [comment]
I am not familiar with gn building system. So I have no idea about how to interact with cmake from gn. However, you can use gn to rewrite the building process by yourself. You can find some log in our workflow: https://github.com/WasmEdge/WasmEdge/actions/workflows/build.yml

**Comment by O3Ol** [comment]
When I try to compile the static library by gn, it returns as following:
```
[77/495] CXX obj/third_party/WasmEdge/lib/executor/engine/wasmedgeExecutor/engine.o
FAILED: obj/third_party/WasmEdge/lib/executor/engine/wasmedgeExecutor/engine.o 
/usr/bin/ccache ../../prebuilts/clang/ohos/linux-x86_64/llvm/bin/clang++ -MMD -MF obj/third_party/WasmEdge/lib/executor/engine/wasmedgeExecutor/engine.o.d -DV8_DEPRECATION_WARNINGS -DNO_TCMALLOC -D_GNU_SOURCE -DHAVE_SYS_UIO_H -D__MUSL__ -D_LIBCPP_HAS_MUSL_LIBC -D__BUILD_LINUX_WITH_CLANG -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -DCOMPONENT_BUILD -D__GNU_SOURCE=1 -DCHROMIUM_CXX_TWEAK_INLINES -D__MUSL__ -D_LIBCPP_HAS_MUSL_LIBC -D__BUILD_LINUX_WITH_CLANG -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -Iobj/third_party/musl/usr/include/arm-linux-ohosmusl -I../../prebuilts/clang/ohos/linux-x86_64/llvm/include/c++/v1 -I../.. -Igen -I../../third_party/WasmEdge/include -I../../third_party/WasmEdge/build/include -I../../third_party/WasmEdge/build/_deps/spdlog-src/include -I../../third_party/boost -I../../third_party/WasmEdge/thirdparty -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector-strong -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -funwind-tables -fPIC -fcolor-diagnostics -fmerge-all-constants -Xclang -mllvm -Xclang -instcombine-lower-dbg-declare=0 -no-canonical-prefixes -ffunction-sections -fno-short-enums --target=arm-linux-ohosmusl -march=armv7-a -mfloat-abi=softfp -mtune=generic-armv7-a -mfpu=neon -mthumb -Wall -Werror -Wextra -Wimplicit-fallthrough -Wthread-safety -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-unneeded-internal-declaration -Wno-error=c99-designator -Wno-error=anon-enum-enum-conversion -Wno-error=implicit-fallthrough -Wno-error=sizeof-array-div -Wno-error=reorder-init-list -Wno-error=range-loop-construct -Wno-error=deprecated-copy -Wno-error=implicit-int-float-conversion -Wno-error=inconsistent-dllimport -Wno-error=unknown-warning-option -Wno-error=abstract-final-class -Wno-error=sign-compare -Wno-error=int-in-bool-context -Wno-error=xor-used-as-pow -Wno-error=return-stack-address -Wno-error=dangling-gsl -Wno-undefined-var-template -Wno-nonportable-include-path -Wno-user-defined-warnings -Wno-unused-lambda-capture -Wno-null-pointer-arithmetic -Wno-enum-compare-switch -O2 -fno-ident -fdata-sections -ffunction-sections -fomit-frame-pointer -gdwarf-3 -g2 -ggnu-pubnames -fno-common -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wall -Wextra -Werror -Wno-error=pedantic -Wno-c++20-designator -Wno-c99-extensions -Wno-covered-switch-default -Wno-documentation-unknown-command -Wno-keyword-macro -Wno-newline-eof -Wno-return-std-move-in-c++11 -Wno-shadow-field-in-constructor -Wno-signed-enum-bitfield -Wno-switch-enum -Wno-undefined-func-template -Wno-unused-const-variable -std=c++17 -fno-exceptions -fno-rtti --sysroot=obj/third_party/musl -fvisibility-inlines-hidden -fexceptions -c ../../third_party/WasmEdge/lib/executor/engine/engine.cpp -o obj/third_party/WasmEdge/lib/executor/engine/wasmedgeExecutor/engine.o
In file included from ../../third_party/WasmEdge/lib/executor/engine/engine.cpp:3:
In file included from ../../third_party/WasmEdge/include/executor/executor.h:564:
In file included from ../../third_party/WasmEdge/include/executor/engine/unary_numeric.ipp:3:
../../third_party/WasmEdge/include/common/roundeven.h:57:11: error: invalid operand in inline asm: 'frintn ${0:s}, ${0:s}'
  __asm__("frintn %s0, %s0" : "=w"(Ret) : "w"(Value));
          ^
../../third_party/WasmEdge/include/common/roundeven.h:57:11: error: invalid operand in inline asm: 'frintn ${0:s}, ${0:s}'
../../third_party/WasmEdge/include/common/roundeven.h:57:11: error: unexpected token in operand
<inline asm>:1:9: note: instantiated into assembly here
        frintn , 
               ^
```
Did I lost some settings that result it?

**Comment by hydai** [comment]
Looks like it failed at this section:
https://github.com/WasmEdge/WasmEdge/blob/master/include/common/roundeven.h#L55-L58

However, according to 9the spec](https://developer.arm.com/documentation/dui0801/g/A64-Floating-point-Instructions/FRINTN--scalar-), this should be correct. We can compile it on aarch64 platform.

You may need to check what's your target platform first and cross-compile toolchains.

**Comment by O3Ol** [comment]
The target platform is arm32, and it uses clang+musl.The version of LLVM is 10.0.1
Could it run on arm32?

**Comment by hydai** [comment]
Well, it should work:

```cpp
#elif defined(__ARM_NEON__) || defined(__ARM_NEON) || defined(__ARM_NEON_FP)
  float Ret;
  __asm__("frintn %s0, %s0" : "=w"(Ret) : "w"(Value));
  return Ret;
```

Here shows your target defined one of `__ARM_NEON__`, `__ARM_NEON`, or `__ARM_NEON_FP`.

**Comment by O3Ol** [comment]
Yeah, I find it use '-thumb' in building ohos standard. And in thumb state, '-w' is not available.

Are there some settings that support it in thumb state?

**Comment by hydai** [comment]
Will the `-thumb` defined a macro like `__ARM_NEON__`? If so, then you can add a new `#elif defined(..)` to isolate this situation.

**Comment by O3Ol** [comment]
The settings in ohos as following:
```
-march=armv7-a -mfloat-abi=softfp -mtune=generic-armv7-a -mfpu=neon -mthumb
```
We can see that the ohos standard uses 'armv7-a neon' instruction set. And according to the doc [https://community.arm.com/arm-community-blogs/b/operating-systems-blog/posts/arm-neon-programming-quick-reference](url), armv7-a neon can't use functionality 'frintn' or 'vrintn'. 

So should I use the code in 'else' for 'armv7-a' as following?
```
#elif defined(..)
  assuming(fegetround() == FE_TONEAREST);
  return std::nearbyint(Value);
```

**Comment by hydai** [comment]
The armv7-a neon lacks lots of functions. I disable the asm codegen in this target. Please use the latest master and try again.

**Comment by hydai** [comment]
The PR closed this issue. Re-open it to trace the original problem.

**Comment by hydai** [comment]
Hi @O3Ol 
I would like to know if this is still a issue. Or is this issue resolved?

**Comment by O3Ol** [comment]
@hydai The issue is resolved by writing `Gn` file. I'll close it, thanks.
