### ISSUE TITLE
[Tinygo package] Support networking Socket

### ISSUE THREAD

**Issue by alabulei1** [WasmEdge/WasmEdge#866]
## Motivation

Networking support is necessary for the area of edge computing. WasmEdge now supports Networking Socket in Rust. 
As Go is one of the main languages in cloud-native Edge Computing, maybe WasmEdge should support Networking Socket in  TinyGo.

Let me know what do you think by commenting on this issue. Thanks.

## Appendix

https://github.com/second-state/wasmedge_wasi_socket

**Comment by Marshalzxy** [comment]
Can https://github.com/alphahorizonio/tinynet solve you problems?

**Comment by hydai** [comment]
Do we still need this?

**Comment by hydai** [comment]
No updates, closing it. @alabulei1 Please feel free to re-open it if we still need this feature in tinygo.
