### ISSUE TITLE
build wasmEdge spends too much system resource

### ISSUE THREAD

**Issue by yang1992** [WasmEdge/WasmEdge#908]
### Current State

I try many times:
when build 40%+，the load is high，kswapd0 can use 100 cpu，too much D state process

### Expected

build with less system resource

## Environment

- Hardware Architecture: x86_64
- Operating system: Ubuntu 20.04 3G mem 4 core

The following information is optional. Please provide them only if you have built from source.
- C++ Compiler version:
- CMake version:
- CMake flags: (e.g. `-DCMAKE_BUILD_TYPE=Release -DWASMEDGE_BUILD_AOT_RUNTIME=ON`)
- Boost version:

## Steps to Reproduce
run cmd: cmake -DCMAKE_BUILD_TYPE=Release . && make -j

![image](https://user-images.githubusercontent.com/4115646/146552307-0c4d3e46-c945-4cb3-9116-eea4e16ec59d.png)
![image](https://user-images.githubusercontent.com/4115646/146552306-7d8aff61-c780-42e4-8e89-85a3b79f6b59.png)

**Comment by hydai** [comment]
If you are on a limited machine, please use `make -j <your cpu core number>` to limit the building process number.
