### ISSUE TITLE
What's the appropriate workflow to access the data stored in a WasmEdge Table instance

### ISSUE THREAD

**Issue by apepkuss** [WasmEdge/WasmEdge#909]
## Environment

- Hardware Architecture: x86\_64
- Operating system: Ubuntu 20.04
- WasmEdge: 0.9.0
- API: C-API `WasmEdge_TableInstanceGetData`

## Description

I'm testing the APIs of the `Table` struct of WasmEdge Rust binding, and feel confused about the error message returned by the `get_data` method (in fact, the error is returned by the C-API `WasmEdge_TableInstanceGetData`). My steps are listed as below:

1.  Create a Table instance named `table`, which is of `WasmEdge_RefType_FuncRef` type and has a limit of `[10, 20]`.
2. Try to access the data at a specific position (`offset = 10`) by calling `table.get_data(10)`.

After the second step, the C-API `WasmEdge_TableInstanceGetData` (wrapped in the `get_data` method) returns a error `{ code: 0x04, "Wrong VM's workflow"}`.

My questions are
- There seem some constraints or assumptions on the invocation to the C-API `WasmEdge_TableInstanceGetData`. If some, could you please give the details in the C-API files, such as [wasmedge.h](https://github.com/WasmEdge/WasmEdge/blob/master/include/api/wasmedge/wasmedge.h#L1413).
- Could you please describe the appropriate way or workflow to access the data of a `Table`?

Thanks a lot!

**Comment by q82419** [comment]
For the API `WasmEdge_Result WasmEdge_TableInstanceGetData(const WasmEdge_TableInstanceContext *Cxt, WasmEdge_Value *Data, const uint32_t Offset)`, the error you got will happen if the `Cxt` or the return `Data` is a `NULL` in C/C++. Please check the table instance context and the return data address you set are available.
And also, for the table instance created by the limit `[10, 20]`, the table size is `10`, which means the available offset you can access are between `0` to `9`. The `table.get_data(10)` will out of boundary unless the table grows.

**Comment by apepkuss** [comment]
@q82419 Thanks for your quick reply. I'll try it again.

**Comment by apepkuss** [comment]
Hi @q82419, 

Could I perform `get_data` to access the data at a legal position in the table before calling `set_data`? If not, then error code is `0x04` and message is `"Wrong VM's workflow"`, right? If yes, the error message could be inappropriate. It could be better if it's more precise, like "access the table before setting it".

**Comment by q82419** [comment]
It's legal for accessing data before `set_data`, and the `WasmEdge_ValueIsNullRef` with the returned value will be `TRUE`.
Can you help to check the input of `WasmEdge_TableInstanceGetData` or provide the detailed code you wrote?
As mentioned above, the `"Wrong VM's workflow"` will only happen when the context or the output data address is `nullptr`.

**Comment by apepkuss** [comment]
Hi @q82419,

The test code below is for the scenario mentioned above. Even if the index is changed to a value in the scope of the capacity, the low-level C-API still returns the error code `0x04`.

![image](https://user-images.githubusercontent.com/4726889/146894588-ccb32f56-ae45-4697-9416-5c6a30dcb67a.png)

**Comment by q82419** [comment]
Hi @apepkuss ,

I saw the #988 was closed. Is this issue cleared?
Thanks.

**Comment by apepkuss** [comment]
@q82419 Yes, the issue has been fixed by PR #980. It was caused by the inappropriate implementation of `get_data`.

**Comment by apepkuss** [comment]
Closed by #980.
