### ISSUE TITLE
[C-API] The same API doc comments for two different APIs

### ISSUE THREAD

**Issue by apepkuss** [WasmEdge/WasmEdge#911]
## Description

In [wasmedge.h](https://github.com/WasmEdge/WasmEdge/blob/master/include/api/wasmedge/wasmedge.h#L1194-L1211), `WasmEdge_CompilerCreate` and `WasmEdge_CompilerCompile` have the exactly same doc comments. Could you please refactor the doc comments for the involved APIs? Thanks a lot!

**Comment by q82419** [comment]
Thanks for figuring out.
