### ISSUE TITLE
[C-API] The default return value of WasmEdge_StatisticsGetInstrPerSecond

### ISSUE THREAD

**Issue by apepkuss** [WasmEdge/WasmEdge#913]
## Environment

- Hardware Architecture: x86\_64
- Operating system: Ubuntu 20.04
- WasmEdge: 0.9.0
- API: C-API `WasmEdge_StatisticsGetInstrPerSecond`

## Description

When I tested Rust binding to C-API WasmEdge_StatisticsGetInstrPerSecond, the return value is `NaN`. It would be better to return `0.0`. To reproduce the issue, please follow the steps below:

1. Create a Statistics instance by calling `WasmEdge_StatisticsCreate`;
2. Call `WasmEdge_StatisticsGetInstrPerSecond`.

The test code in Rust below captures the issue.
```rust
  // create a Statistics instance
  let result = Statistics::create();
  assert!(result.is_ok());
  let stat = result.unwrap();

  // check instruction count
  let count = stat.get_instr_count();
  assert_eq!(stat.get_instr_count(), 0);

  // check instruction count per second
  let count = stat.get_instr_per_second();
  assert!(count.is_nan());
  // assert!(count, 0.0);

  // check total cost
  assert_eq!(stat.get_total_cost(), 0);
```

**Comment by hydai** [comment]
Instruction per second = Total executed instructions / total execution time.
If the statistics is not enabled or the total execution time is `0.0`. Then, the instruction per second should be `Nan` which represents something is divided by zero.

https://github.com/WasmEdge/WasmEdge/pull/919#discussion_r773607515
