### ISSUE TITLE
Support the Anna KVS

### ISSUE THREAD

**Issue by juntao** [WasmEdge/WasmEdge#925]
## Motivation

In many cloud native wasm use cases, the application need to access a stateful data store. The Anna project provides a cloud native KVS for edge nodes. We should support WasmEdge applications to read / write Anna data stores via host functions. 

## Details

Create a C-based application that wraps around WasmEdge. It will

* Starts WasmEdge
* Register Anna read / write functions as host functions in this WasmEdge instance.

Then, create a Rust crate that allows developers to write Rust programs to use the WasmEdge Anna API. Those programs will be compiled into Wasm and run inside the above C wrapper runtime.

## Appendix

The Anna project: https://github.com/hydro-project/anna

**Comment by richardchien** [comment]
This issue is solved by the following two repos:

- https://github.com/second-state/wasmedge-anna: the WasmEdge wrapper runtime with Anna APIs
- https://github.com/second-state/wasmedge-anna-rs: the Rust SDK for applications

**Comment by hydai** [comment]
This is resolved in the above comments. I am closing it.
