### ISSUE TITLE
[Utils] Uninstall script does not remove lines in .zshrc

### ISSUE THREAD

**Issue by KernelErr** [WasmEdge/WasmEdge#946]
After testing WasmEdge on Raspberry Pi, I ran the uninstall script. However, the following lines are found to remain and cause some warning notice.

~/.zprofile

```
. "/home/li/.wasmedge/env"
```

~/.zshrc

```
...
. "/home/li/.wasmedge/env"
```

**Comment by SAtacker** [comment]
Thanks for this. On it.
