### ISSUE TITLE
execution failed: unreachable, Code: 0x89 In instruction: unreachable (0x00) , Bytecode offset: 0x0000a64d When executing function name: "_start"

### ISSUE THREAD

**Issue by liudonghua123** [WasmEdge/WasmEdge#953]
## Description

I installed the wasmedge on my win 11. And then I followed the docs on https://wasmedge.org/book/en/dev/rust.html.

### Current State

```shell
D:\code\rust\hello>wasmedge target/wasm32-wasi/debug/hello.wasm second state
hello
thread 'note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2021-12-29 16:47:56.603] [error] execution failed: unreachable, Code: 0x89
[2021-12-29 16:47:56.604] [error]     In instruction: unreachable (0x00) , Bytecode offset: 0x0000a64d
[2021-12-29 16:47:56.604] [error]     When executing function name: "_start"

D:\code\rust\hello>
D:\code\rust\hello>wasmedgec target/wasm32-wasi/debug/hello.wasm target/wasm32-wasi/debug/hello.wasm
[2021-12-29 16:54:17.471] [info] compile start
[2021-12-29 16:54:17.508] [info] verify start
[2021-12-29 16:54:17.522] [info] optimize start
[2021-12-29 16:54:18.403] [info] codegen start
[2021-12-29 16:54:19.189] [info] output start
lld-link: error: could not open 'libcmt.lib': no such file or directory
[2021-12-29 16:54:19.196] [info] compile done
[2021-12-29 16:54:19.200] [info] output start

D:\code\rust\hello>
```

### Expected

Work as expected on windows platform.

## Environment

- Hardware Architecture: x64
- Operating system: Microsoft Windows [Version 10.0.22000.376]

```shell
D:\code\rust\hello>wasmedge --version
wasmedge version 0.9.0

D:\code\rust\hello>rustc --version
rustc 1.57.0 (f1edd0429 2021-11-29)

D:\code\rust\hello>
```

## Steps to Reproduce

1. rustup target add wasm32-wasi
2. cargo new hello && cd hello
3. cargo build --target wasm32-wasi
4. wasmedge target/wasm32-wasi/debug/hello.wasm second state

If I use the linux version `wasmedge` to run, then it worked.

```shell
liudonghua@DESKTOP-DELL:/mnt/d/code/rust/hello$ wasmedge target/wasm32-wasi/debug/hello.wasm second state
hello
second
state
liudonghua@DESKTOP-DELL:/mnt/d/code/rust/hello$
```

**Comment by liudonghua123** [comment]
I also tried to use `wasmer` to execute the wasm, it worked.

```shell
D:\code\rust\hello>wasmer target/wasm32-wasi/debug/hello.wasm
hello

D:\code\rust\hello>wasmer target/wasm32-wasi/debug/hello.wasm second state
hello
second
state

D:\code\rust\hello>wasmer --version
wasmer 2.1.1

D:\code\rust\hello>
```

**Comment by hydai** [comment]
Hi @liudonghua123 
Thanks for reporting this. I am going to reproduce this and try to figure out. Chat soon.

**Comment by hydai** [comment]
Hi @liudonghua123 
Looks like the return value of the output related function is wrong: https://github.com/WasmEdge/WasmEdge/blob/master/lib/host/wasi/inode-win.cpp#L133

I am going to do some tests and fix this.

**Comment by liudonghua123** [comment]
I tried update to 0.9.1 and now I got `lld-link: error: could not open 'libcmt.lib': no such file or directory`, `[error] number of types not matching:0 18` errors.

```cmd
D:\code\rust\hello>cargo clean

D:\code\rust\hello>cargo build --target wasm32-wasi
   Compiling hello v0.1.0 (D:\code\rust\hello)
    Finished dev [unoptimized + debuginfo] target(s) in 1.88s

D:\code\rust\hello>wasmedge target/wasm32-wasi/debug/hello.wasm second state
hello
second
state

D:\code\rust\hello>wasmedgec target/wasm32-wasi/debug/hello.wasm target/wasm32-wasi/debug/hello.wasm
[2022-02-24 09:00:54.988] [info] compile start
[2022-02-24 09:00:55.025] [info] verify start
[2022-02-24 09:00:55.039] [info] optimize start
[2022-02-24 09:00:56.169] [info] codegen start
[2022-02-24 09:00:57.041] [info] output start
lld-link: error: could not open 'libcmt.lib': no such file or directory
[2022-02-24 09:00:57.053] [info] compile done
[2022-02-24 09:00:57.057] [info] output start

D:\code\rust\hello>wasmedge target/wasm32-wasi/debug/hello.wasm second state
[2022-02-24 09:01:03.532] [error] number of types not matching:0 18
hello
second
state

D:\code\rust\hello>cat src\main.rs
use std::env;

fn main() {
  println!("hello");
  for argument in env::args().skip(1) {
    println!("{}", argument);
  }
}
D:\code\rust\hello>wasmedge --version
wasmedge version 0.9.1

D:\code\rust\hello>ver

Microsoft Windows [Version 10.0.22000.527]

D:\code\rust\hello>
```

**Comment by liudonghua123** [comment]
For `could not open 'libcmt.lib': no such file or directory`, I can fix it by executing the `wasmedgec target/wasm32-wasi/debug/hello.wasm target/wasm32-wasi/debug/hello.wasm` in the vs 2019 x64 command prompt shell.

```cmd
D:\code\rust\hello>vs2019
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.11.7
** Copyright (c) 2021 Microsoft Corporation
**********************************************************************

D:\code\rust\hello>wasmedgec target/wasm32-wasi/debug/hello.wasm target/wasm32-wasi/debug/hello.wasm
[2022-02-24 09:04:36.493] [error] number of types not matching:0 18
[2022-02-24 09:04:36.503] [info] compile start
[2022-02-24 09:04:36.543] [info] verify start
[2022-02-24 09:04:36.558] [info] optimize start
[2022-02-24 09:04:37.706] [info] codegen start
[2022-02-24 09:04:38.611] [info] output start
lld-link: error: libcmt.lib(chkstk.obj): machine type x86 conflicts with x64
[2022-02-24 09:04:38.626] [info] compile done
[2022-02-24 09:04:38.630] [info] output start

D:\code\rust\hello>vs2019
vs2019     vs2019_64
D:\code\rust\hello>vs2019_64
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.11.7
** Copyright (c) 2021 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

D:\code\rust\hello>wasmedgec target/wasm32-wasi/debug/hello.wasm target/wasm32-wasi/debug/hello.wasm
[2022-02-24 09:05:15.744] [error] number of types not matching:0 18
[2022-02-24 09:05:15.745] [error] number of types not matching:0 18
[2022-02-24 09:05:15.754] [info] compile start
[2022-02-24 09:05:15.791] [info] verify start
[2022-02-24 09:05:15.806] [info] optimize start
[2022-02-24 09:05:16.952] [info] codegen start
[2022-02-24 09:05:17.806] [info] output start
[2022-02-24 09:05:18.035] [info] compile done
[2022-02-24 09:05:18.077] [info] output start

D:\code\rust\hello>
```

And If I did not run `wasmedge target/wasm32-wasi/debug/hello.wasm second state` before `wasmedgec target/wasm32-wasi/debug/hello.wasm target/wasm32-wasi/debug/hello.wasm`, then `[error] number of types not matching:0 18` will not shown.

```cmd
D:\code\rust\hello>cargo clean

D:\code\rust\hello>cargo build --target wasm32-wasi
   Compiling hello v0.1.0 (D:\code\rust\hello)
    Finished dev [unoptimized + debuginfo] target(s) in 1.74s

D:\code\rust\hello>wasmedgec target/wasm32-wasi/debug/hello.wasm target/wasm32-wasi/debug/hello.wasm
[2022-02-24 09:08:09.331] [info] compile start
[2022-02-24 09:08:09.374] [info] verify start
[2022-02-24 09:08:09.388] [info] optimize start
[2022-02-24 09:08:10.590] [info] codegen start
[2022-02-24 09:08:11.474] [info] output start
[2022-02-24 09:08:11.528] [info] compile done
[2022-02-24 09:08:11.562] [info] output start

D:\code\rust\hello>wasmedge target/wasm32-wasi/debug/hello.wasm second state
hello
second
state

D:\code\rust\hello>
```

**Comment by alabulei1** [comment]
> This issue still seems to be exists for me atleast: rustc 1.62.1, wasmedge 0.10.0.
> 
> 
> 
> ```shell
> 
> PS C:\Users\sob\Project\roto\wasmedge-playground\functions\rs-simple-function-aot> cargo build --target wasm32-wasi
> 
>     Finished dev [unoptimized + debuginfo] target(s) in 0.00s
> 
> PS C:\Users\sob\Project\roto\wasmedge-playground\functions\rs-simple-function-aot> wasmedgec target/wasm32-wasi/debug/rs_simple_function.wasm target/aot.wasm
> 
> [2022-09-23 19:12:56.097] [info] compile start
> 
> [2022-09-23 19:12:56.118] [info] verify start
> 
> [2022-09-23 19:12:56.125] [info] optimize start
> 
> [2022-09-23 19:12:56.768] [info] codegen start
> 
> [2022-09-23 19:12:57.259] [info] output start
> 
> lld-link: error: could not open 'libcmt.lib': no such file or directory
> 
> [2022-09-23 19:12:57.265] [error] link error
> 
> [2022-09-23 19:12:57.267] [info] output start
> 
> PS C:\Users\sob\Project\roto\wasmedge-playground\functions\rs-simple-function-aot> wasmedgec --version
> 
> C:\Program Files\WasmEdge\bin\wasmedgec.exe version 0.10.0
> 
> ```
> 
> 
> 
> But as the issue author mentioned, it seems to running directly on Visual Studio 2022 Developer Command Prompt work.
> 
> ```shell
> 
> C:\Users\sob\Project\roto\wasmedge-playground\functions\rs-simple-function-aot>wasmedgec target/wasm32-wasi/debug/rs_simple_function.wasm target/aot.wasm
> 
> [2022-09-23 19:11:57.984] [info] compile start
> 
> [2022-09-23 19:11:58.004] [info] verify start
> 
> [2022-09-23 19:11:58.010] [info] optimize start
> 
> [2022-09-23 19:11:58.652] [info] codegen start
> 
> [2022-09-23 19:11:59.121] [info] output start
> 
> [2022-09-23 19:11:59.247] [info] compile done
> 
> [2022-09-23 19:11:59.271] [info] output start
> 
> ```

@ilsubyeega Thanks for your report! Could you raise a new issue for tracking this issue? Thanks.
