### ISSUE TITLE
[C-API] Not implement `WasmEdge_VMExecuteByFuncref` API.

### ISSUE THREAD

**Issue by YHM404** [WasmEdge/WasmEdge#961]
## Description

When implementing the [`substrate`](https://github.com/paritytech/substrate/blob/master/client/executor/common/src/wasm_runtime.rs#L81) runtime API, I need to call the corresponding wasm or export ’Function‘ through `Funcref`. 
If I want call a `wasm function` in `wasmtime`, I can invoke a method like this: `call(&Funcref, Store, &TableName, &InputData, &OutputData)`.
Does wasmedge provide a similar API?

**Comment by hydai** [comment]
Hi @CQUPTYHM 
Do you have any code example of this feature? It's really hard to evaluate this with only one line. Please provide a full example with context.

**Comment by CQUPTYHM** [comment]
> Hi @CQUPTYHM Do you have any code example to show how wasmtime uses/implements of this feature? It's really hard to evaluate this with only one line. Please provide a full example with context.

Hi @hydai 
If I got a `Table index`, I can invoke a method like:
`
WasmEdge_VMContext *VMCxt = /*return a VM context*/
/*
load, validate, instantiate module....
*/

table_index = 10
TableInstance table = /*return a table instance*/

Funcref ref = GetRefFromTable(table, table_index)

res = WasmEdge_VMExecuteByFuncref(VMcxt, ref, Params, 1, Returns, 1)
`

**Comment by hydai** [comment]
> > Hi @CQUPTYHM Do you have any code example to show how wasmtime uses/implements of this feature? It's really hard to evaluate this with only one line. Please provide a full example with context.
> 
> Hi @hydai If I got a `Table index`, I can invoke a method like:
> 
> ```
> WasmEdge_VMContext *VMCxt = /*return a VM context*/
> /*
> load, validate, instantiate module....
> */
> 
> table_index = 10
> TableInstance table = /*return a table instance*/
> 
> Funcref ref = GetRefFromTable(table, table_index)
> 
> res = WasmEdge_VMExecuteByFuncref(VMcxt, ref, Params, 1, Returns, 1)
> ```

Do you have any example which is used from the current substrate implementation? For example, how do the `wasmi` or `wasmtime` use this feature.

**Comment by CQUPTYHM** [comment]
> 

```
fn extern_func(extern_: &Extern) -> Option<&Func> {
	match extern_ {
		Extern::Func(func) => Some(func),
		_ => None,
	}
}

let module: Module = ****;
let mut store = Store::new(module.engine(), *store data*);
let instance = Instance::new(&mut store, module, &[]).unwrap();
let export: Extern = instance.get_export(&mut self.store, "method_name").unwrap();
let func: Func = extern_func(&export).unwrap();

//let table = instance.get_table(&mut store, "table name").unwrap();
//let func_ref: u32 = ***;
// func_ref is a table_index.
//let val = table.get(&mut store, func_ref).unwrap();
//let func = val.funcref().unwrap();
//let func: Func = instance.get_export(&mut self.store, "method_name").unwrap();

let res = func.call(&mut store, data_ptr, *params*);
```

**Comment by CQUPTYHM** [comment]
> > > Hi @CQUPTYHM Do you have any code example to show how wasmtime uses/implements of this feature? It's really hard to evaluate this with only one line. Please provide a full example with context.
> > 
> > 
> > Hi @hydai If I got a `Table index`, I can invoke a method like:
> > ```
> > WasmEdge_VMContext *VMCxt = /*return a VM context*/
> > /*
> > load, validate, instantiate module....
> > */
> > 
> > table_index = 10
> > TableInstance table = /*return a table instance*/
> > 
> > Funcref ref = GetRefFromTable(table, table_index)
> > 
> > res = WasmEdge_VMExecuteByFuncref(VMcxt, ref, Params, 1, Returns, 1)
> > ```
> 
> Do you have any example which is used from the current substrate implementation? For example, how do the `wasmi` or `wasmtime` use this feature.

fn extern_func(extern_: &Extern) -> Option<&Func> {
	match extern_ {
		Extern::Func(func) => Some(func),
		_ => None,
	}
}

```
let module: Module = ****;
let mut store = Store::new(module.engine(), *store data*);
let instance = Instance::new(&mut store, module, &[]).unwrap();

let export: Extern = instance.get_export(&mut self.store, "method_name").unwrap();
let func: Func = extern_func(&export).unwrap();

//let table = instance.get_table(&mut store, "table name").unwrap();
//let func_ref: u32 = ***;
// func_ref is a table_index.
//let val = table.get(&mut store, func_ref).unwrap();
//let func = val.funcref().unwrap();
//let func: Func = instance.get_export(&mut self.store, "method_name").unwrap();

let res = func.call(&mut store, data_ptr, *params*);
```

**Comment by q82419** [comment]
> 

Sorry that I cannot fully understand your code.
```
//let func = val.funcref().unwrap();
//let func: Func = instance.get_export(&mut self.store, "method_name").unwrap();
```
Can you describe that what the `func` really is?
Thanks.

**Comment by CQUPTYHM** [comment]
> > 
> 
> Sorry that I cannot fully understand your code.
> 
> ```
> //let func = val.funcref().unwrap();
> //let func: Func = instance.get_export(&mut self.store, "method_name").unwrap();
> ```
> 
> Can you describe that what the `func` really is? Thanks.

Sorry, `//let func: Func = instance.get_export(&mut self.store, "method_name").unwrap();` is redundant.

func is a instance of `[wastime::func::Func](https://docs.wasmtime.dev/api/wasmtime/struct.Func.html)` .

**Comment by q82419** [comment]
I recognized that your description is to get the function instance through a `funcref` in a table instance, and then invoke that function.

For the WasmEdge's architecture, we only support getting or invoking the function instances which are exported with names now -- it fits the isolation and security of WebAssembly.
In the nearly future, we will implement the `Execute` API to invoke the function instances, which can be retrieved with exported names.
For the `funcref` in table instances, we will considering the safety and exception handling.
Thanks.

**Comment by q82419** [comment]
This API will be added in #1365 .
