### ISSUE TITLE
[Install] wget or curl

### ISSUE THREAD

**Issue by juntao** [WasmEdge/WasmEdge#966]
It seems that many projects are using `curl`, instead of `wget`, for their one-line install script -- possibly because `curl` is available by default on more platforms. 

https://daniel.haxx.se/docs/curl-vs-wget.html

What do we think? Shall we switch to `curl`?

**Comment by SAtacker** [comment]
Currently the script supports both. If you mean we prefer to check first for curl and then for wget it's quite doable. If curl is more preferred then I'll make a PR.
Also including the changes in the installation documentation.
Thanks for this.
