### ISSUE TITLE
[C-API] Two potential issues found when using the different versions of libwasmedge.so

### ISSUE THREAD

**Issue by apepkuss** [WasmEdge/WasmEdge#988]
## Environment

- Hardware Architecture: aarch64
- Docker image: appdev_aarch64:0.9.0
- Operating system: Ubuntu 20.04
- libwasmedge.so
  - Release 0.9.0
  - Master branch: commit 8c9c564b

## Steps to Reproduce

I created a test function (see below) for testing the `Table` struct and its APIs in `wasmedge-sys`. The test code runs twice against the two versions of `libwasmedge.so`: one is release 0.9.0, the other is built from the master branch (commit 8c9c564b). The printed results (line _320_) returned by these two versions are inconsistent:

- The printed result from release 0.9.0: `*** table[9]: FuncRef(0)`
- The printed result from the master branch (commit 8c9c564b): `*** table[9]: FuncRef(5192266357579010329493846515253248)`

I tried several times and got the same results as mentioned above. Here is another interesting observation. Still use the same test function below, the three environments of release 0.9.0 (on docker appdev_aarch64:0.9.0), the master branch (commit 8c9c564b on docker appdev_aarch64:0.9.0), and the github CI show the inconsistent results in line _330_:

- release 0.9.0 (on docker appdev_aarch64:0.9.0): `*** table[3]: FuncRef(5)`
- the master branch (commit 8c9c564b on docker appdev_aarch64:0.9.0): `*** table[3]: FuncRef(5)`
- the github CI: `*** table[3]: FuncRef(2594494589227184625970161752473605)`

Could you please help with the two issues mentioned above? Thanks a lot!

![image](https://user-images.githubusercontent.com/4726889/148225086-ec7765f4-6ce3-455b-8410-7e32a7d97800.png)

**Comment by q82419** [comment]
And also, I suggest to use the `WasmEdge_ValueGetExternRef` to retrieve the `externref`, or use the `WasmEdge_ValueGetFuncIdx` to retrieve the `funcref` instead of directly using the returned `WasmEdge_Value`.

**Comment by apepkuss** [comment]
> And also, I suggest to use the `WasmEdge_ValueGetExternRef` to retrieve the `externref`, or use the `WasmEdge_ValueGetFuncIdx` to retrieve the `funcref` instead of directly using the returned `WasmEdge_Value`.
> 
> https://github.com/WasmEdge/WasmEdge/blob/master/bindings/rust/wasmedge-sys/src/instance/table.rs#L82-L91
> 
> You can get the reference type of the table instance to determine the `Value` is a `FuncRef` or an `ExternRef`.

@q82419 Thanks for your quick reply. As you mentioned, the original design of the `get_data` is problematic, and hence the PR #980 is launched to fix the issues. In addition, I also launched another PR #982 which could also fix some issues related to WasmEdge_Value. I'll check the issues again after PR #982 is merged. Thanks again!

**Comment by apepkuss** [comment]
@q82419 I tried the test code again after merging #982. The printed results are same now: 
```
*** table[9]: NullRef(FuncRef)
*** table[3]: FuncRef(5)
```
The root reason of the first inconsistent results is that the original design uses the `Value` field of the returned WasmEdge_Value directly when dealing with `funcref`, but not uses `WasmEdge_ValueIsNullRef` first to check if the returned value is a null reference or not. The second issue also does not appear in the CI checks after merging #982.

Thanks a lot!
